import IdealArithmetic.MordellThueProject.SkolemTimesTable
import IdealArithmetic.MordellExamples.MordellExample17.NF3_1_1836_1.UnitsData3_1_1836_1

/-!
# The Skolem certificate at `p = 349` for `K = ℚ(θ)`, `θ³ - 6θ - 10 = 0`

`mu` is the last coordinate for the integral basis recorded in `RI3_1_1836_1`.  Iterated
multiplication of coordinate vectors modulo `349 ^ 2 = 121801` verifies

* `hC1 … hC116` : the coordinates of `zeta1 ^ r` mod `121801`, one multiplication per step;
* `not_dvd_mu_zeta1_pow` : **(S3)** -- `349 ∤ mu (zeta1 ^ r)` for every `r < 116` outside
  the surviving classes `0`, `115`;
* `zeta1_pow_116` : **(S1)**, **(S2)** and the re-centering hypotheses, i.e.
  `349 ∤ mu (zeta1 ^ r * δ)` for each surviving `r`, which is what makes each
  surviving class contain exactly one solution.

Generated by `SkolemTableNFLean.sage`.
-/

namespace NF3_1_1836_1

set_option linter.all false

open Module

noncomputable section

abbrev pS : ℕ := 349
abbrev mS : ℕ := pS ^ 2

/-- The weights picking out the last coordinate of the integral basis. -/
def kMu : Fin 3 → ℤ := ![0, 0, 1]

/-- `mu`: the last coordinate. -/
abbrev mu : O →ₗ[ℤ] ℤ := muOfBasis timesTableO.basis kMu

lemma mu_one : mu 1 = 0 := by
  have h : mu (B 0) = kMu 0 := muOfBasis_basis (b := timesTableO.basis) kMu 0
  rwa [B_one] at h

/-- The times table of `O`, reduced modulo `121801`. -/
def TMod : Fin 3 → Fin 3 → List (ZMod mS) :=
 ![ ![[1, 0, 0], [0, 1, 0], [0, 0, 1]],
 ![[0, 1, 0], [0, 0, 1], [10, 6, 0]],
 ![[0, 0, 1], [10, 6, 0], [0, 10, 6]]]

lemma hTMod : ∀ i j, List.map (algebraMap ℤ (ZMod mS)) (Table i j) = TMod i j := by decide

/-! ### The coordinate vector of `zeta1` modulo `121801` -/

lemma hbase : coordMod timesTableO.basis mS zeta1 = ![3, 3, 1] := by
  have hv : timesTableO.basis.equivFun zeta1 = ![3, 3, 1] := by
    rw [zeta1]; exact B.equivFun.apply_symm_apply _
  funext i
  simp only [coordMod, Function.comp_apply, hv]
  fin_cases i <;> decide

/-! ### The chain `zeta1 ^ 1, …, zeta1 ^ 116`, one multiplication per step -/

lemma hC0 : coordMod timesTableO.basis mS (zeta1 ^ 0) = ![1, 0, 0] := by
  rw [pow_zero, coordMod_one (b := timesTableO.basis) (i₀ := 0) B_one]
  funext i; fin_cases i <;> decide

lemma hC1 : coordMod timesTableO.basis mS (zeta1 ^ 1) = ![3, 3, 1] := by
  rw [pow_one]; exact hbase

lemma hC2 : coordMod timesTableO.basis mS (zeta1 ^ 2) = ![69, 64, 21] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC1 (by decide)

lemma hC3 : coordMod timesTableO.basis mS (zeta1 ^ 3) = ![1477, 1371, 450] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC2 (by decide)

lemma hC4 : coordMod timesTableO.basis mS (zeta1 ^ 4) = ![31641, 29370, 9640] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC3 (by decide)

lemma hC5 : coordMod timesTableO.basis mS (zeta1 ^ 5) = ![68818, 20168, 84710] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC4 (by decide)

lemma hC6 : coordMod timesTableO.basis mS (zeta1 ^ 6) = ![26210, 80224, 39105] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC5 (by decide)

lemma hC7 : coordMod timesTableO.basis mS (zeta1 ^ 7) = ![105204, 68571, 9822] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC6 (by decide)

lemma hC8 : coordMod timesTableO.basis mS (zeta1 ^ 8) = ![77972, 111558, 33912] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC7 (by decide)

lemma hC9 : coordMod timesTableO.basis mS (zeta1 ^ 9) = ![52637, 116857, 108849] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC8 (by decide)

lemma hC10 : coordMod timesTableO.basis mS (zeta1 ^ 10) = ![85314, 116162, 43038] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC9 (by decide)

lemma hC11 : coordMod timesTableO.basis mS (zeta1 ^ 11) = ![29080, 70444, 90336] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC10 (by decide)

lemma hC12 : coordMod timesTableO.basis mS (zeta1 ^ 12) = ![91332, 83818, 79028] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC11 (by decide)

lemma hC13 : coordMod timesTableO.basis mS (zeta1 ^ 13) = ![72588, 74316, 79630] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC12 (by decide)

lemma hC14 : coordMod timesTableO.basis mS (zeta1 ^ 14) = ![61197, 71223, 37798] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC13 (by decide)

lemma hC15 : coordMod timesTableO.basis mS (zeta1 ^ 15) = ![80945, 55927, 6043] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC14 (by decide)

lemma hC16 : coordMod timesTableO.basis mS (zeta1 ^ 16) = ![8987, 62775, 59511] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC15 (by decide)

lemma hC17 : coordMod timesTableO.basis mS (zeta1 ^ 17) = ![4021, 65826, 2105] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC16 (by decide)

lemma hC18 : coordMod timesTableO.basis mS (zeta1 ^ 18) = ![2667, 54432, 98643] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC17 (by decide)

lemma hC19 : coordMod timesTableO.basis mS (zeta1 ^ 19) = ![101183, 93067, 79342] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC18 (by decide)

lemma hC20 : coordMod timesTableO.basis mS (zeta1 ^ 20) = ![82250, 74101, 120054] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC19 (by decide)

lemma hC21 : coordMod timesTableO.basis mS (zeta1 ^ 21) = ![82743, 12136, 45228] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC20 (by decide)

lemma hC22 : coordMod timesTableO.basis mS (zeta1 ^ 22) = ![21215, 40424, 38999] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC21 (by decide)

lemma hC23 : coordMod timesTableO.basis mS (zeta1 ^ 23) = ![54442, 57821, 6274] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC22 (by decide)

lemma hC24 : coordMod timesTableO.basis mS (zeta1 ^ 24) = ![77149, 6780, 40769] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC23 (by decide)

lemma hC25 : coordMod timesTableO.basis mS (zeta1 ^ 25) = ![60705, 94188, 99007] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC24 (by decide)

lemma hC26 : coordMod timesTableO.basis mS (zeta1 ^ 26) = ![74772, 26172, 16322] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC25 (by decide)

lemma hC27 : coordMod timesTableO.basis mS (zeta1 ^ 27) = ![1288, 64273, 56584] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC26 (by decide)

lemma hC28 : coordMod timesTableO.basis mS (zeta1 ^ 28) = ![29895, 96056, 94358] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC27 (by decide)

lemma hC29 : coordMod timesTableO.basis mS (zeta1 ^ 29) = ![105154, 63984, 71076] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC28 (by decide)

lemma hC30 : coordMod timesTableO.basis mS (zeta1 ^ 30) = ![42557, 80023, 84183] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC29 (by decide)

lemma hC31 : coordMod timesTableO.basis mS (zeta1 ^ 31) = ![42963, 38176, 65865] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC30 (by decide)

lemma hC32 : coordMod timesTableO.basis mS (zeta1 ^ 32) = ![50579, 2474, 19470] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC31 (by decide)

lemma hC33 : coordMod timesTableO.basis mS (zeta1 ^ 33) = ![29771, 110158, 111430] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC32 (by decide)

lemma hC34 : coordMod timesTableO.basis mS (zeta1 ^ 34) = ![27156, 59541, 23304] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC33 (by decide)

lemma hC35 : coordMod timesTableO.basis mS (zeta1 ^ 35) = ![36187, 51839, 50112] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC34 (by decide)

lemma hC36 : coordMod timesTableO.basis mS (zeta1 ^ 36) = ![59694, 29432, 33707] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC35 (by decide)

lemma hC37 : coordMod timesTableO.basis mS (zeta1 ^ 37) = ![23000, 47955, 85950] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC36 (by decide)

lemma hC38 : coordMod timesTableO.basis mS (zeta1 ^ 38) = ![82025, 105772, 87808] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC37 (by decide)

lemma hC39 : coordMod timesTableO.basis mS (zeta1 ^ 39) = ![40403, 2617, 93404] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC38 (by decide)

lemma hC40 : coordMod timesTableO.basis mS (zeta1 ^ 40) = ![26275, 80452, 36283] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC39 (by decide)

lemma hC41 : coordMod timesTableO.basis mS (zeta1 ^ 41) = ![23019, 113603, 106974] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC40 (by decide)

lemma hC42 : coordMod timesTableO.basis mS (zeta1 ^ 42) = ![29471, 67323, 108584] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC41 (by decide)

lemma hC43 : coordMod timesTableO.basis mS (zeta1 ^ 43) = ![121531, 80642, 112487] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC42 (by decide)

lemma hC44 : coordMod timesTableO.basis mS (zeta1 ^ 44) = ![38986, 98773, 36029] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC43 (by decide)

lemma hC45 : coordMod timesTableO.basis mS (zeta1 ^ 45) = ![114941, 65911, 50561] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC44 (by decide)

lemma hC46 : coordMod timesTableO.basis mS (zeta1 ^ 46) = ![84743, 39511, 36917] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC45 (by decide)

lemma hC47 : coordMod timesTableO.basis mS (zeta1 ^ 47) = ![51635, 60091, 48325] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC46 (by decide)

lemma hC48 : coordMod timesTableO.basis mS (zeta1 ^ 48) = ![13147, 100008, 57828] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC47 (by decide)

lemma hC49 : coordMod timesTableO.basis mS (zeta1 ^ 49) = ![94739, 876, 102817] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC48 (by decide)

lemma hC50 : coordMod timesTableO.basis mS (zeta1 ^ 50) = ![88860, 4151, 48312] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC49 (by decide)

lemma hC51 : coordMod timesTableO.basis mS (zeta1 ^ 51) = ![52236, 73262, 48917] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC50 (by decide)

lemma hC52 : coordMod timesTableO.basis mS (zeta1 ^ 52) = ![42619, 115125, 103270] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC51 (by decide)

lemma hC53 : coordMod timesTableO.basis mS (zeta1 ^ 53) = ![114172, 36109, 99414] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC52 (by decide)

lemma hC54 : coordMod timesTableO.basis mS (zeta1 ^ 54) = ![31996, 40661, 21016] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC53 (by decide)

lemma hC55 : coordMod timesTableO.basis mS (zeta1 ^ 55) = ![36869, 75977, 99521] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC54 (by decide)

lemma hC56 : coordMod timesTableO.basis mS (zeta1 ^ 56) = ![80176, 48759, 64280] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC55 (by decide)

lemma hC57 : coordMod timesTableO.basis mS (zeta1 ^ 57) = ![98697, 43179, 74167] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC56 (by decide)

lemma hC58 : coordMod timesTableO.basis mS (zeta1 ^ 58) = ![29667, 81756, 43130] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC57 (by decide)

lemma hC59 : coordMod timesTableO.basis mS (zeta1 ^ 59) = ![8043, 83629, 54100] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC58 (by decide)

lemma hC60 : coordMod timesTableO.basis mS (zeta1 ^ 60) = ![47399, 99172, 15024] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC59 (by decide)

lemma hC61 : coordMod timesTableO.basis mS (zeta1 ^ 61) = ![1224, 115606, 114728] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC60 (by decide)

lemma hC62 : coordMod timesTableO.basis mS (zeta1 ^ 62) = ![94935, 115276, 40783] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC61 (by decide)

lemma hC63 : coordMod timesTableO.basis mS (zeta1 ^ 63) = ![103234, 28193, 77004] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC62 (by decide)

lemma hC64 : coordMod timesTableO.basis mS (zeta1 ^ 64) = ![100329, 39929, 28242] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC63 (by decide)

lemma hC65 : coordMod timesTableO.basis mS (zeta1 ^ 65) = ![85925, 111313, 108891] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC64 (by decide)

lemma hC66 : coordMod timesTableO.basis mS (zeta1 ^ 66) = ![9197, 45505, 60072] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC65 (by decide)

lemma hC67 : coordMod timesTableO.basis mS (zeta1 ^ 67) = ![92383, 48535, 77355] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC66 (by decide)

lemma hC68 : coordMod timesTableO.basis mS (zeta1 ^ 68) = ![38124, 78481, 81576] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC67 (by decide)

lemma hC69 : coordMod timesTableO.basis mS (zeta1 ^ 69) = ![57835, 59804, 33343] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC68 (by decide)

lemma hC70 : coordMod timesTableO.basis mS (zeta1 ^ 70) = ![66621, 61932, 50130] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC69 (by decide)

lemma hC71 : coordMod timesTableO.basis mS (zeta1 ^ 71) = ![8864, 90274, 94582] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC70 (by decide)

lemma hC72 : coordMod timesTableO.basis mS (zeta1 ^ 72) = ![112762, 76926, 34715] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC71 (by decide)

lemma hC73 : coordMod timesTableO.basis mS (zeta1 ^ 73) = ![78379, 53824, 46970] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC72 (by decide)

lemma hC74 : coordMod timesTableO.basis mS (zeta1 ^ 74) = ![111860, 85897, 53576] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC73 (by decide)

lemma hC75 : coordMod timesTableO.basis mS (zeta1 ^ 75) = ![407, 50960, 120929] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC74 (by decide)

lemma hC76 : coordMod timesTableO.basis mS (zeta1 ^ 76) = ![119258, 70042, 23638] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC75 (by decide)

lemma hC77 : coordMod timesTableO.basis mS (zeta1 ^ 77) = ![62120, 66603, 54922] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC76 (by decide)

lemma hC78 : coordMod timesTableO.basis mS (zeta1 ^ 78) = ![64030, 9384, 25421] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC77 (by decide)

lemma hC79 : coordMod timesTableO.basis mS (zeta1 ^ 79) = ![74152, 13926, 77369] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC78 (by decide)

lemma hC80 : coordMod timesTableO.basis mS (zeta1 ^ 80) = ![3164, 78102, 81445] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC79 (by decide)

lemma hC81 : coordMod timesTableO.basis mS (zeta1 ^ 81) = ![67036, 69646, 117868] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC80 (by decide)

lemma hC82 : coordMod timesTableO.basis mS (zeta1 ^ 82) = ![48772, 108793, 118776] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC81 (by decide)

lemma hC83 : coordMod timesTableO.basis mS (zeta1 ^ 83) = ![47287, 66345, 104324] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC82 (by decide)

lemma hC84 : coordMod timesTableO.basis mS (zeta1 ^ 84) = ![37399, 6008, 89029] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC83 (by decide)

lemma hC85 : coordMod timesTableO.basis mS (zeta1 ^ 85) = ![41724, 101260, 4077] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC84 (by decide)

lemma hC86 : coordMod timesTableO.basis mS (zeta1 ^ 86) = ![42072, 54459, 16794] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC85 (by decide)

lemma hC87 : coordMod timesTableO.basis mS (zeta1 ^ 87) = ![78417, 112171, 112993] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC86 (by decide)

lemma hC88 : coordMod timesTableO.basis mS (zeta1 ^ 88) = ![118313, 23758, 92056] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC87 (by decide)

lemma hC89 : coordMod timesTableO.basis mS (zeta1 ^ 89) = ![65572, 101304, 43683] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC88 (by decide)

lemma hC90 : coordMod timesTableO.basis mS (zeta1 ^ 90) = ![84226, 17357, 31825] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC89 (by decide)

lemma hC91 : coordMod timesTableO.basis mS (zeta1 ^ 91) = ![41187, 81981, 57319] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC90 (by decide)

lemma hC92 : coordMod timesTableO.basis mS (zeta1 ^ 92) = ![105120, 30302, 72195] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC91 (by decide)

lemma hC93 : coordMod timesTableO.basis mS (zeta1 ^ 93) = ![104608, 51717, 114975] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC92 (by decide)

lemma hC94 : coordMod timesTableO.basis mS (zeta1 ^ 94) = ![17209, 100945, 76524] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC93 (by decide)

lemma hC95 : coordMod timesTableO.basis mS (zeta1 ^ 95) = ![68170, 57779, 34352] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC94 (by decide)

lemma hC96 : coordMod timesTableO.basis mS (zeta1 ^ 96) = ![107646, 102964, 63471] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC95 (by decide)

lemma hC97 : coordMod timesTableO.basis mS (zeta1 ^ 97) = ![89882, 103578, 13369] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC96 (by decide)

lemma hC98 : coordMod timesTableO.basis mS (zeta1 ^ 98) = ![1282, 114568, 33733] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC97 (by decide)

lemma hC99 : coordMod timesTableO.basis mS (zeta1 ^ 99) = ![90899, 30666, 39578] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC98 (by decide)

lemma hC100 : coordMod timesTableO.basis mS (zeta1 ^ 100) = ![61483, 73462, 51895] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC99 (by decide)

lemma hC101 : coordMod timesTableO.basis mS (zeta1 ^ 101) = ![39899, 106249, 18118] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC100 (by decide)

lemma hC102 : coordMod timesTableO.basis mS (zeta1 ^ 102) = ![20513, 121630, 34504] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC101 (by decide)

lemma hC103 : coordMod timesTableO.basis mS (zeta1 ^ 103) = ![120541, 51704, 86934] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC102 (by decide)

lemma hC104 : coordMod timesTableO.basis mS (zeta1 ^ 104) = ![76255, 94285, 83651] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC103 (by decide)

lemma hC105 : coordMod timesTableO.basis mS (zeta1 ^ 105) = ![27115, 9130, 15760] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC104 (by decide)

lemma hC106 : coordMod timesTableO.basis mS (zeta1 ^ 106) = ![36440, 117591, 74544] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC105 (by decide)

lemma hC107 : coordMod timesTableO.basis mS (zeta1 ^ 107) = ![111122, 88045, 85701] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC106 (by decide)

lemma hC108 : coordMod timesTableO.basis mS (zeta1 ^ 108) = ![9015, 114971, 50357] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC107 (by decide)

lemma hC109 : coordMod timesTableO.basis mS (zeta1 ^ 109) = ![7843, 35760, 76335] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC108 (by decide)

lemma hC110 : coordMod timesTableO.basis mS (zeta1 ^ 110) = ![113358, 46729, 71332] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC109 (by decide)

lemma hC111 : coordMod timesTableO.basis mS (zeta1 ^ 111) = ![24100, 78309, 42926] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC110 (by decide)

lemma hC112 : coordMod timesTableO.basis mS (zeta1 ^ 112) = ![72553, 30193, 36356] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC111 (by decide)

lemma hC113 : coordMod timesTableO.basis mS (zeta1 ^ 113) = ![26856, 45752, 3132] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC112 (by decide)

lemma hC114 : coordMod timesTableO.basis mS (zeta1 ^ 114) = ![23043, 92828, 70499] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC113 (by decide)

lemma hC115 : coordMod timesTableO.basis mS (zeta1 ^ 115) = ![67354, 77130, 83411] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC114 (by decide)

lemma hC116 : coordMod timesTableO.basis mS (zeta1 ^ 116) = ![65264, 64914, 75035] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC115 (by decide)

/-! ### `(S3)`: the sieve -/

lemma hS1 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 1)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC1 kMu).mpr (by decide)

lemma hS2 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 2)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC2 kMu).mpr (by decide)

lemma hS3 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 3)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC3 kMu).mpr (by decide)

lemma hS4 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 4)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC4 kMu).mpr (by decide)

lemma hS5 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 5)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC5 kMu).mpr (by decide)

lemma hS6 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 6)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC6 kMu).mpr (by decide)

lemma hS7 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 7)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC7 kMu).mpr (by decide)

lemma hS8 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 8)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC8 kMu).mpr (by decide)

lemma hS9 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 9)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC9 kMu).mpr (by decide)

lemma hS10 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 10)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC10 kMu).mpr (by decide)

lemma hS11 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 11)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC11 kMu).mpr (by decide)

lemma hS12 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 12)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC12 kMu).mpr (by decide)

lemma hS13 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 13)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC13 kMu).mpr (by decide)

lemma hS14 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 14)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC14 kMu).mpr (by decide)

lemma hS15 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 15)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC15 kMu).mpr (by decide)

lemma hS16 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 16)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC16 kMu).mpr (by decide)

lemma hS17 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 17)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC17 kMu).mpr (by decide)

lemma hS18 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 18)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC18 kMu).mpr (by decide)

lemma hS19 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 19)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC19 kMu).mpr (by decide)

lemma hS20 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 20)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC20 kMu).mpr (by decide)

lemma hS21 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 21)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC21 kMu).mpr (by decide)

lemma hS22 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 22)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC22 kMu).mpr (by decide)

lemma hS23 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 23)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC23 kMu).mpr (by decide)

lemma hS24 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 24)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC24 kMu).mpr (by decide)

lemma hS25 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 25)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC25 kMu).mpr (by decide)

lemma hS26 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 26)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC26 kMu).mpr (by decide)

lemma hS27 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 27)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC27 kMu).mpr (by decide)

lemma hS28 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 28)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC28 kMu).mpr (by decide)

lemma hS29 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 29)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC29 kMu).mpr (by decide)

lemma hS30 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 30)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC30 kMu).mpr (by decide)

lemma hS31 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 31)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC31 kMu).mpr (by decide)

lemma hS32 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 32)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC32 kMu).mpr (by decide)

lemma hS33 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 33)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC33 kMu).mpr (by decide)

lemma hS34 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 34)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC34 kMu).mpr (by decide)

lemma hS35 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 35)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC35 kMu).mpr (by decide)

lemma hS36 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 36)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC36 kMu).mpr (by decide)

lemma hS37 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 37)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC37 kMu).mpr (by decide)

lemma hS38 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 38)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC38 kMu).mpr (by decide)

lemma hS39 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 39)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC39 kMu).mpr (by decide)

lemma hS40 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 40)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC40 kMu).mpr (by decide)

lemma hS41 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 41)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC41 kMu).mpr (by decide)

lemma hS42 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 42)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC42 kMu).mpr (by decide)

lemma hS43 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 43)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC43 kMu).mpr (by decide)

lemma hS44 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 44)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC44 kMu).mpr (by decide)

lemma hS45 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 45)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC45 kMu).mpr (by decide)

lemma hS46 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 46)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC46 kMu).mpr (by decide)

lemma hS47 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 47)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC47 kMu).mpr (by decide)

lemma hS48 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 48)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC48 kMu).mpr (by decide)

lemma hS49 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 49)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC49 kMu).mpr (by decide)

lemma hS50 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 50)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC50 kMu).mpr (by decide)

lemma hS51 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 51)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC51 kMu).mpr (by decide)

lemma hS52 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 52)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC52 kMu).mpr (by decide)

lemma hS53 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 53)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC53 kMu).mpr (by decide)

lemma hS54 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 54)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC54 kMu).mpr (by decide)

lemma hS55 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 55)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC55 kMu).mpr (by decide)

lemma hS56 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 56)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC56 kMu).mpr (by decide)

lemma hS57 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 57)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC57 kMu).mpr (by decide)

lemma hS58 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 58)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC58 kMu).mpr (by decide)

lemma hS59 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 59)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC59 kMu).mpr (by decide)

lemma hS60 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 60)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC60 kMu).mpr (by decide)

lemma hS61 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 61)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC61 kMu).mpr (by decide)

lemma hS62 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 62)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC62 kMu).mpr (by decide)

lemma hS63 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 63)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC63 kMu).mpr (by decide)

lemma hS64 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 64)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC64 kMu).mpr (by decide)

lemma hS65 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 65)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC65 kMu).mpr (by decide)

lemma hS66 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 66)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC66 kMu).mpr (by decide)

lemma hS67 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 67)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC67 kMu).mpr (by decide)

lemma hS68 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 68)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC68 kMu).mpr (by decide)

lemma hS69 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 69)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC69 kMu).mpr (by decide)

lemma hS70 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 70)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC70 kMu).mpr (by decide)

lemma hS71 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 71)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC71 kMu).mpr (by decide)

lemma hS72 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 72)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC72 kMu).mpr (by decide)

lemma hS73 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 73)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC73 kMu).mpr (by decide)

lemma hS74 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 74)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC74 kMu).mpr (by decide)

lemma hS75 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 75)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC75 kMu).mpr (by decide)

lemma hS76 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 76)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC76 kMu).mpr (by decide)

lemma hS77 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 77)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC77 kMu).mpr (by decide)

lemma hS78 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 78)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC78 kMu).mpr (by decide)

lemma hS79 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 79)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC79 kMu).mpr (by decide)

lemma hS80 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 80)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC80 kMu).mpr (by decide)

lemma hS81 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 81)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC81 kMu).mpr (by decide)

lemma hS82 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 82)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC82 kMu).mpr (by decide)

lemma hS83 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 83)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC83 kMu).mpr (by decide)

lemma hS84 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 84)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC84 kMu).mpr (by decide)

lemma hS85 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 85)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC85 kMu).mpr (by decide)

lemma hS86 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 86)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC86 kMu).mpr (by decide)

lemma hS87 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 87)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC87 kMu).mpr (by decide)

lemma hS88 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 88)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC88 kMu).mpr (by decide)

lemma hS89 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 89)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC89 kMu).mpr (by decide)

lemma hS90 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 90)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC90 kMu).mpr (by decide)

lemma hS91 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 91)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC91 kMu).mpr (by decide)

lemma hS92 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 92)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC92 kMu).mpr (by decide)

lemma hS93 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 93)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC93 kMu).mpr (by decide)

lemma hS94 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 94)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC94 kMu).mpr (by decide)

lemma hS95 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 95)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC95 kMu).mpr (by decide)

lemma hS96 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 96)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC96 kMu).mpr (by decide)

lemma hS97 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 97)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC97 kMu).mpr (by decide)

lemma hS98 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 98)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC98 kMu).mpr (by decide)

lemma hS99 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 99)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC99 kMu).mpr (by decide)

lemma hS100 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 100)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC100 kMu).mpr (by decide)

lemma hS101 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 101)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC101 kMu).mpr (by decide)

lemma hS102 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 102)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC102 kMu).mpr (by decide)

lemma hS103 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 103)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC103 kMu).mpr (by decide)

lemma hS104 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 104)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC104 kMu).mpr (by decide)

lemma hS105 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 105)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC105 kMu).mpr (by decide)

lemma hS106 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 106)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC106 kMu).mpr (by decide)

lemma hS107 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 107)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC107 kMu).mpr (by decide)

lemma hS108 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 108)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC108 kMu).mpr (by decide)

lemma hS109 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 109)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC109 kMu).mpr (by decide)

lemma hS110 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 110)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC110 kMu).mpr (by decide)

lemma hS111 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 111)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC111 kMu).mpr (by decide)

lemma hS112 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 112)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC112 kMu).mpr (by decide)

lemma hS113 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 113)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC113 kMu).mpr (by decide)

lemma hS114 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 114)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC114 kMu).mpr (by decide)

/-- **`(S3)`.**  `349 ∤ mu (zeta1 ^ r)` for every `r < 116` outside the surviving
classes 0, 115. -/
theorem not_dvd_mu_zeta1_pow : ∀ r : ℕ, r < 116 → r ≠ 0 → r ≠ 115 → ¬ ((pS : ℤ) ∣ mu (zeta1 ^ r)) := by
  intro r hr h0 h115
  interval_cases r
  · exact absurd rfl h0
  · exact hS1
  · exact hS2
  · exact hS3
  · exact hS4
  · exact hS5
  · exact hS6
  · exact hS7
  · exact hS8
  · exact hS9
  · exact hS10
  · exact hS11
  · exact hS12
  · exact hS13
  · exact hS14
  · exact hS15
  · exact hS16
  · exact hS17
  · exact hS18
  · exact hS19
  · exact hS20
  · exact hS21
  · exact hS22
  · exact hS23
  · exact hS24
  · exact hS25
  · exact hS26
  · exact hS27
  · exact hS28
  · exact hS29
  · exact hS30
  · exact hS31
  · exact hS32
  · exact hS33
  · exact hS34
  · exact hS35
  · exact hS36
  · exact hS37
  · exact hS38
  · exact hS39
  · exact hS40
  · exact hS41
  · exact hS42
  · exact hS43
  · exact hS44
  · exact hS45
  · exact hS46
  · exact hS47
  · exact hS48
  · exact hS49
  · exact hS50
  · exact hS51
  · exact hS52
  · exact hS53
  · exact hS54
  · exact hS55
  · exact hS56
  · exact hS57
  · exact hS58
  · exact hS59
  · exact hS60
  · exact hS61
  · exact hS62
  · exact hS63
  · exact hS64
  · exact hS65
  · exact hS66
  · exact hS67
  · exact hS68
  · exact hS69
  · exact hS70
  · exact hS71
  · exact hS72
  · exact hS73
  · exact hS74
  · exact hS75
  · exact hS76
  · exact hS77
  · exact hS78
  · exact hS79
  · exact hS80
  · exact hS81
  · exact hS82
  · exact hS83
  · exact hS84
  · exact hS85
  · exact hS86
  · exact hS87
  · exact hS88
  · exact hS89
  · exact hS90
  · exact hS91
  · exact hS92
  · exact hS93
  · exact hS94
  · exact hS95
  · exact hS96
  · exact hS97
  · exact hS98
  · exact hS99
  · exact hS100
  · exact hS101
  · exact hS102
  · exact hS103
  · exact hS104
  · exact hS105
  · exact hS106
  · exact hS107
  · exact hS108
  · exact hS109
  · exact hS110
  · exact hS111
  · exact hS112
  · exact hS113
  · exact hS114
  · exact absurd rfl h115

/-! ### `(S1)`, `(S2)` and the re-centering data -/

/-- The coordinates of `δ = (zeta1 ^ 116 - 1) / 349` modulo `349`. -/
def eDelta : Fin 3 → ZMod pS := ![187, 186, 215]

/-- The times table of `O`, reduced modulo `349`. -/
def TModP : Fin 3 → Fin 3 → List (ZMod pS) :=
 ![ ![[1, 0, 0], [0, 1, 0], [0, 0, 1]],
 ![[0, 1, 0], [0, 0, 1], [10, 6, 0]],
 ![[0, 0, 1], [10, 6, 0], [0, 10, 6]]]

lemma hTModP : ∀ i j, List.map (algebraMap ℤ (ZMod pS)) (Table i j) = TModP i j := by decide

lemma hP0 : coordMod timesTableO.basis pS (zeta1 ^ 0) = ![1, 0, 0] := by
  rw [coordMod_castHom (by norm_num : pS ∣ mS), hC0]
  funext i; fin_cases i <;> decide

lemma hP115 : coordMod timesTableO.basis pS (zeta1 ^ 115) = ![346, 1, 0] := by
  rw [coordMod_castHom (by norm_num : pS ∣ mS), hC115]
  funext i; fin_cases i <;> decide

/-- **`(S1)`, `(S2)` and re-centering.**  `zeta1 ^ 116 = 349 δ + 1` with `349 ∤ mu δ`,
and `349 ∤ mu (zeta1 ^ r * δ)` for each surviving class `r`, so no such class holds two
solutions. -/
theorem zeta1_pow_116 : ∃ δ : O, zeta1 ^ 116 = pS * δ + 1 ∧ ¬ ((pS : ℤ) ∣ mu δ) ∧ ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 0 * δ)) ∧ ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 115 * δ)) := by
  obtain ⟨δ, hδ, hc⟩ := exists_delta_of_coordMod (b := timesTableO.basis) (by norm_num)
    (i₀ := 0) B_one hC116 eDelta (by decide)
  refine ⟨δ, hδ, (not_dvd_muOfBasis_iff dvd_rfl hc kMu).mpr (by decide), ?_, ?_⟩
  · exact (not_dvd_muOfBasis_iff dvd_rfl (coordMod_mul timesTableT_eq_Table
      hTModP hP0 hc (c := ![187, 186, 215]) (by decide)) kMu).mpr (by decide)
  · exact (not_dvd_muOfBasis_iff dvd_rfl (coordMod_mul timesTableT_eq_Table
      hTModP hP115 hc (c := ![193, 221, 239]) (by decide)) kMu).mpr (by decide)

end

end NF3_1_1836_1
