import IdealArithmetic.MordellExamples.MordellExample79.NF2_2_316_1.ClassGroupSaturated2_2_316_1_3
import IdealArithmetic.MordellExamples.MordellExample79.NF2_2_316_1.RelationIdeals2_2_316_1F0
import IdealArithmetic.Computation.ExponentiationZMod
import IdealArithmetic.MordellThueProject.ArtinInequality
import IdealArithmetic.MordellExamples.MordellExample79.NF2_2_316_1.PrimesBelowCert2_2_316_1
import Mathlib.NumberTheory.NumberField.ClassNumber
import IdealArithmetic.Signature.ResultantRecursive
import IdealArithmetic.DedekindProject.Discriminant
import IdealArithmetic.Generation.ClassGroupGeneration

namespace NF2_2_316_1

set_option linter.all false

/- Number field `K(α)` with α root of polynomial `X^2 - 79`.
Class group structure `[3]`, generated by class of ideals `[(3, s + 2)]`. -/

/- Ring of integers with basis `[1, s]` -/

open BigOperators Classical Matrix Polynomial Module

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible

instance K_field : Field K := by
  unfold K
  exact AdjoinRoot.instField

instance K_numberField : NumberField K := by
  unfold K
  exact AdjoinRoot.instNumberFieldRat

instance : Module ℚ K := Algebra.toModule
instance : @Algebra ℤ K CommRing.toCommSemiring CommRing.toCommSemiring.toSemiring := Ring.toIntAlgebra K
instance : @CharZero K CommRing.toCommSemiring.toNonAssocSemiring.toAddCommMonoidWithOne.toAddMonoidWithOne := charZero_of_expChar_one' K

lemma K_finrank : Module.finrank ℚ K = 2 := by
  unfold K
  erw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, T_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ []
  · fin_cases hc
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']

theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by rw [O_integral_closure] ; rfl

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance DD' : IsDedekindDomain O  := by
  rw [O_integral_closure]
  exact integralClosure.isDedekindDomain ℤ ℚ K

instance : Module.Free ℤ ↥O := Module.Free.of_basis B

instance  : IdemCommSemiring (Ideal O) := Ideal.instIdemCommSemiring
instance : CharZero O := SubsemiringClass.instCharZero O

def SturmRC : SturmBuilderOfList [[-79, 0, 1], [0, 2], [316]] [-79, 0, 1] [0, 2] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 2 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [4]
  f := [1]
  epos := by decide
  fpos := by decide
  Q := [[0, 2]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 1 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^2 - 79
  l := [-79, 0, 1]
  hl := T_ofList
  hlz := by decide
  hz := by decide
  hAdj := Adj
  heq := O_integral_closure
  P := [[-79, 0, 1], [0, 2], [316]]
  SB := SturmRC
  k := 2
  r := 2
  hr := by decide
  hreq := by decide 

def IC : Ideal O := Ideal.span (Set.range (fun i ↦ B.equivFun.symm (![![9, 1]] i)))

def AIC: IdealEqSpanCertificate timesTableO IC
 ![![9, 1]] 
 ![![2, 0], ![1, 1]] where
  T := Table
  heq := timesTableT_eq_Table
  hieq := rfl 
  M :=![![![9, 1], ![79, 9]]]
  hmulB := by decide
  f := ![![![9, -1]], ![![-35, 4]]]
  g := ![![![4, 1], ![35, 9]]]
  hle1 := by decide
  hle2 := by decide

 lemma ne_dvd_torsion3 : ¬3 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by 
  refine prime_not_dvd_torsion_of_not_dvd (by decide) IC
     (ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate AIC))
     (by decide) (by decide)

def NPCU3 : pMaximalUnitsCertificateNDvdT O 3 where 
 hp := by decide
 r := 1
 huc := by 
  erw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1]
 hu := fun i => 
  match i with 
  | 0 => isUnit_zeta1
 t := 2
 hrle := by decide
 q := ![7, 13]
 hqP := by 
  intro i 
  match i with 
  | 0 => exact Sat3.hq7
  | 1 => exact Sat3.hq13
 I := ![Sat3.I0, Sat3.I1]
 hcard := fun i =>
  match i with  
  | 0 => Sat3.N0
  | 1 => Sat3.N1
 ζ := ![3, 2]
 hr := fun i =>
  match i with 
  | 0 => ((orderOf_of_IsOrderOf Sat3.R7) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf Sat3.R13) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 hpndvdt := ne_dvd_torsion3
 M := ![![1], ![2]]
 hM1 := by 
  intro i j
  fin_cases i <;> fin_cases j 
  · erw [eq_of_DiscreteLogCertificate Sat3.Log00] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log10] ; decide
 Minv := ![![1]] 
 hInv := by decide

def NPSU3 : pSaturatedClassGroupCertificateNDvdT 3 ![J0] ![3] where 
 topMaximalUnitsCertificateNDvdT := NPCU3
 a := ![alpha0]
 γ := 1
 hc := by decide
 ψ := ![0]
 iψ := ![0] 
 hψ := by decide 
 hψn := by 
  intro i 
  fin_cases i 
  · decide
 h := fun i =>
  match i with 
  | 0 => by convert J0_pow3
 N := ![![2], ![2]]
 hM2 := by 
  intro (i : Fin 2) j
  match i , j with 
  | 0, 0 => exact Sat3.Log01
  | 1, 0 => exact Sat3.Log11
 hDl := by decide 
 NInv := ![![2, 1], ![1, 1]]
 hN := by decide 

lemma T_discr : T.discr = 316 :=  by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  rw [T_ofList]

theorem K_discr : NumberField.discr K = 316 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl

lemma K_nrComplexPlaces : NumberField.InfinitePlace.nrComplexPlaces K = 0 := by
  rw [nrComplexPlaces_of_RankUnitsCertificate RC]
  rfl

lemma K_nrRealPlaces : NumberField.InfinitePlace.nrRealPlaces K = 2 := by
  rw [nrRealPlaces_of_RankUnitsCertificate RC]
  rfl

theorem K_minowski : minkowskiBoundFB K ≤ (8.898194417315588 : ℝ) := by
  refine K_minkowski_decimal _ ?_
  erw [K_nrComplexPlaces, K_discr, K_finrank]
  have hraux: √316 ≤ 17.776399 := by
      refine Real.sqrt_le_iff.mpr ?_
      norm_num
  have : 0.5 * √316 ≤ 8.8982 := by
    refine le_trans (mul_le_mul_of_nonneg (by rfl) hraux (by norm_num) (by norm_num)) ?_
    norm_num
  norm_num
  try {linarith}

def s := ![4]

def BM : (i : Fin 1) → Fin (e i) → (Fin 1 → ℕ) := by 
  rintro ⟨i, hi⟩ 
  interval_cases i 
  exact ![![0], ![2], ![1], ![1], ![2], ![1], ![2]]

lemma primesGenerationBelow : {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < 9} ⊆ Set.range (Fin.addCasesIter e 𝔭) := by
  rw [← cert_eq_𝔭]
  refine le_primes_below_bound_of_PrimesBelowBoundCertificate_le_of_eq (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv PB9

def 𝔭' : Fin 7 → nonZeroDivisors (Ideal O) := by
  intro i
  have : PB9.β i ∈ List.ofFn PB9.β := by
    simp only [List.mem_ofFn, exists_apply_eq_apply]
  refine Ideal.toNonZeroDivisorOfNeZero ((PB9.β) i)
    (fun hc => ((zero_ne_mem_of_PrimesBelowCertificate_Fn _ PB9) (hc ▸ this) ))

def J : Fin 1 → Ideal O := ![J0]

def J' :  Fin 1 → nonZeroDivisors (Ideal O) := by
  refine fun i => Ideal.toNonZeroDivisorOfNeZero (J i) (?_ )
  unfold J
  rw [← Submodule.zero_eq_bot, ← pow_ne_zero_iff (n := ![3] i) (by fin_cases i <;> decide) , NPSU3.h]
  simp only [ Submodule.zero_eq_bot, ne_eq, Ideal.span_singleton_eq_bot, NPSU3]
  fin_cases i
  · dsimp [alpha0] ; rw [(LinearEquiv.map_eq_zero_iff B.equivFun.symm)] ; decide 

lemma 𝔭'_apply : ∀ (i : Fin 7), ↑(𝔭' i) = (Fin.addCasesIter e 𝔭) i := by
  intro i
  rw [← cert_eq_𝔭]
  rfl

lemma J'_apply : ∀ (i : Fin 1), ↑(J' i) = J i := by
  intro i
  rfl

lemma relations_proof0 (i : Fin 7) : IsInClass O J (𝔭 0 i) (BM 0 i) := by
  show IsInClass O J (𝔭 0 i) (![![0], ![2], ![1], ![1], ![2], ![1], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R3N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R3N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R5N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R5N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R7N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R7N1

theorem class_group_generator : Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (J' i))) = ⊤ := by
  refine subgroup_closure_eq_classGroup'' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv
      𝔭'_apply J'_apply ?_ primesGenerationBelow (Fin.addCasesIter e BM) ?_
  · refine lt_of_le_of_lt K_minowski ?_
    norm_num
  · refine forall_addCasesIter_prop 𝔭 BM (IsInClass O J) ?_
    rintro ⟨i, hi⟩
    interval_cases i
    · exact relations_proof0

def ClassGroupO_equiv : (∀ i : Fin 1 , (ZMod (![3] i))) ≃+ Additive (ClassGroup O) := by
  haveI : ∀ (i : Fin 1), NeZero (![3] i) := by
    intro i
    fin_cases i <;>  exact {out := by decide}
  refine ClassGroup_equiv_of_pSaturatedCertificate J'_apply NPSU3.h class_group_generator ?_
  rintro ⟨p, hp1, hp2⟩
  have : ∏ i, ![3] i = ∏ i, (![3] i) ^ (![1] i)  := by decide
  rw [this] at hp2
  have hp_cases : p ∈ [3] := by
    obtain ⟨j ,hj1, hj2⟩  := Prime.exists_mem_finset_dvd (Nat.prime_iff.mp hp1) hp2
    show p ∈ List.ofFn ![3]
    rw [(Nat.prime_dvd_prime_iff_eq hp1 ?_).1 (Nat.Prime.dvd_of_dvd_pow hp1 hj2), List.mem_ofFn]
    exact ⟨j, rfl⟩
    fin_cases j <;> decide
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hp_cases
  by_cases h : p = 3
  simp_rw [h] ; right
  exact NPSU3
  omega

def class_group_equiv : (∀ i : Fin 1 , (ZMod (![3] i))) ≃+ Additive (ClassGroup (NumberField.RingOfIntegers K)) := by
 refine AddEquiv.trans ClassGroupO_equiv ?_
 exact MulEquiv.toAdditive (ClassGroup.congr
    ((Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv))

theorem class_number_K_eq_3 : NumberField.classNumber K = 3 := by
  unfold NumberField.classNumber
  rw [Fintype.card_eq_nat_card, ← Nat.card_congr (Additive.toMul),
    Nat.card_congr (class_group_equiv).symm.toEquiv, Nat.card_pi]
  simp [Fin.isValue, Fin.prod_succ]
  try decide


/-! ### Units modulo cubes

`zeta1 = 80 + 9√79` is a fundamental unit and the unit group is `3`-saturated by it:
`3` does not divide the torsion order `2` (`ne_dvd_torsion3`), which is what
`NPCU3` certifies.
-/

/-- `zeta1` as a unit of `O`. -/
def Z1 : Oˣ := isUnit_zeta1.unit

/-- **Every unit of `O` is `zeta1 ^ e` times a cube.** -/
theorem units_eq_zeta1_zpow_mul_cube (u : Oˣ) : ∃ (e : ℤ) (t : Oˣ), u = Z1 ^ e * t ^ 3 :=
  units_pow_of_pMaximalUnitsCertificateNDvdT O_integral_closure Z1 NPCU3 rfl
    (fun i => by fin_cases i; exact (IsUnit.unit_spec isUnit_zeta1).symm) u

lemma zsmul_one_eq (n : ℤ) : n • (1 : O) = (n : O) := by simp

/-- **Every unit of `O` is `zeta1 ^ e` times a cube, with `e < 3`.** -/
theorem units_eq_zeta1_pow_mul_cube (u : Oˣ) :
    ∃ (e : Fin 3) (t : Oˣ), (u : O) = zeta1 ^ (e : ℕ) * (t : O) ^ 3 := by
  obtain ⟨n, s, hn⟩ := units_eq_zeta1_zpow_mul_cube u
  have hr : 0 ≤ n % 3 := Int.emod_nonneg n (by norm_num)
  have hr3 : n % 3 < 3 := Int.emod_lt_of_pos n (by norm_num)
  refine ⟨⟨(n % 3).toNat, by omega⟩, Z1 ^ (n / 3) * s, ?_⟩
  have hZ : Z1 ^ n = Z1 ^ ((n % 3).toNat) * (Z1 ^ (n / 3)) ^ (3 : ℕ) := by
    rw [← zpow_natCast Z1 ((n % 3).toNat), Int.toNat_of_nonneg hr,
      ← zpow_natCast (Z1 ^ (n / 3)) 3, ← zpow_mul, ← zpow_add]
    congr 1
    omega
  have hu : u = Z1 ^ ((n % 3).toNat) * (Z1 ^ (n / 3) * s) ^ 3 := by
    rw [hn, hZ, mul_pow, mul_assoc]
  rw [hu]
  push_cast [IsUnit.unit_spec isUnit_zeta1]
  rfl

end

end NF2_2_316_1
