import IdealArithmetic.MordellThueProject.SkolemTimesTable
import IdealArithmetic.MordellExamples.MordellExample17.NF3_1_1836_2.UnitsData3_1_1836_2

/-!
# The Skolem certificate at `p = 409` for `K = ℚ(θ)`, `θ³ + 6θ - 6 = 0`

`mu` is the last coordinate for the integral basis recorded in `RI3_1_1836_2`.  Iterated
multiplication of coordinate vectors modulo `409 ^ 2 = 167281` verifies

* `hC1 … hC136` : the coordinates of `zeta1 ^ r` mod `167281`, one multiplication per step;
* `not_dvd_mu_zeta1_pow` : **(S3)** -- `409 ∤ mu (zeta1 ^ r)` for every `r < 136` outside
  the surviving classes `0`, `132`, `135`;
* `zeta1_pow_136` : **(S1)**, **(S2)** and the re-centering hypotheses, i.e.
  `409 ∤ mu (zeta1 ^ r * δ)` for each surviving `r`, which is what makes each
  surviving class contain exactly one solution.

Generated by `SkolemTableNFLean.sage`.
-/

namespace NF3_1_1836_2

set_option linter.all false

open Module

noncomputable section

abbrev pS : ℕ := 409
abbrev mS : ℕ := pS ^ 2

/-- The weights picking out the last coordinate of the integral basis. -/
def kMu : Fin 3 → ℤ := ![0, 0, 1]

/-- `mu`: the last coordinate. -/
abbrev mu : O →ₗ[ℤ] ℤ := muOfBasis timesTableO.basis kMu

lemma mu_one : mu 1 = 0 := by
  have h : mu (B 0) = kMu 0 := muOfBasis_basis (b := timesTableO.basis) kMu 0
  rwa [B_one] at h

/-- The times table of `O`, reduced modulo `167281`. -/
def TMod : Fin 3 → Fin 3 → List (ZMod mS) :=
 ![ ![[1, 0, 0], [0, 1, 0], [0, 0, 1]],
 ![[0, 1, 0], [0, 0, 1], [6, 167275, 0]],
 ![[0, 0, 1], [6, 167275, 0], [0, 6, 167275]]]

lemma hTMod : ∀ i j, List.map (algebraMap ℤ (ZMod mS)) (Table i j) = TMod i j := by decide

/-! ### The coordinate vector of `zeta1` modulo `167281` -/

lemma hbase : coordMod timesTableO.basis mS zeta1 = ![7, 1, 1] := by
  have hv : timesTableO.basis.equivFun zeta1 = ![7, 1, 1] := by
    rw [zeta1]; exact B.equivFun.apply_symm_apply _
  funext i
  simp only [coordMod, Function.comp_apply, hv]
  fin_cases i <;> decide

/-! ### The chain `zeta1 ^ 1, …, zeta1 ^ 136`, one multiplication per step -/

lemma hC0 : coordMod timesTableO.basis mS (zeta1 ^ 0) = ![1, 0, 0] := by
  rw [pow_zero, coordMod_one (b := timesTableO.basis) (i₀ := 0) B_one]
  funext i; fin_cases i <;> decide

lemma hC1 : coordMod timesTableO.basis mS (zeta1 ^ 1) = ![7, 1, 1] := by
  rw [pow_one]; exact hbase

lemma hC2 : coordMod timesTableO.basis mS (zeta1 ^ 2) = ![61, 8, 9] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC1 (by decide)

lemma hC3 : coordMod timesTableO.basis mS (zeta1 ^ 3) = ![529, 69, 78] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC2 (by decide)

lemma hC4 : coordMod timesTableO.basis mS (zeta1 ^ 4) = ![4585, 598, 676] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC3 (by decide)

lemma hC5 : coordMod timesTableO.basis mS (zeta1 ^ 5) = ![39739, 5183, 5859] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC4 (by decide)

lemma hC6 : coordMod timesTableO.basis mS (zeta1 ^ 6) = ![9863, 44922, 50781] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC5 (by decide)

lemma hC7 : coordMod timesTableO.basis mS (zeta1 ^ 7) = ![141416, 54785, 105566] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC6 (by decide)

lemma hC8 : coordMod timesTableO.basis mS (zeta1 ^ 8) = ![111927, 28920, 134486] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC7 (by decide)

lemma hC9 : coordMod timesTableO.basis mS (zeta1 ^ 9) = ![91115, 140847, 108052] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC8 (by decide)

lemma hC10 : coordMod timesTableO.basis mS (zeta1 ^ 10) = ![123827, 64681, 5452] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC9 (by decide)

lemma hC11 : coordMod timesTableO.basis mS (zeta1 ^ 11) = ![116620, 21227, 26679] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC10 (by decide)

lemma hC12 : coordMod timesTableO.basis mS (zeta1 ^ 12) = ![100090, 137847, 164526] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC11 (by decide)

lemma hC13 : coordMod timesTableO.basis mS (zeta1 ^ 13) = ![5653, 70656, 67901] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC12 (by decide)

lemma hC14 : coordMod timesTableO.basis mS (zeta1 ^ 14) = ![34508, 76309, 144210] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC13 (by decide)

lemma hC15 : coordMod timesTableO.basis mS (zeta1 ^ 15) = ![59141, 110817, 87746] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC14 (by decide)

lemma hC16 : coordMod timesTableO.basis mS (zeta1 ^ 16) = ![99836, 2677, 90423] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC15 (by decide)

lemma hC17 : coordMod timesTableO.basis mS (zeta1 ^ 17) = ![86485, 102513, 25655] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC16 (by decide)

lemma hC18 : coordMod timesTableO.basis mS (zeta1 ^ 18) = ![36155, 21717, 47372] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC17 (by decide)

lemma hC19 : coordMod timesTableO.basis mS (zeta1 ^ 19) = ![165776, 57872, 105244] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC18 (by decide)

lemma hC20 : coordMod timesTableO.basis mS (zeta1 ^ 20) = ![131756, 56367, 161611] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC19 (by decide)

lemma hC21 : coordMod timesTableO.basis mS (zeta1 ^ 21) = ![55507, 20842, 15172] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC20 (by decide)

lemma hC22 : coordMod timesTableO.basis mS (zeta1 ^ 22) = ![102790, 76349, 91521] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC21 (by decide)

lemma hC23 : coordMod timesTableO.basis mS (zeta1 ^ 23) = ![53940, 11858, 103379] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC22 (by decide)

lemma hC24 : coordMod timesTableO.basis mS (zeta1 ^ 24) = ![65316, 65798, 1896] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC23 (by decide)

lemma hC25 : coordMod timesTableO.basis mS (zeta1 ^ 25) = ![26971, 131114, 133010] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC24 (by decide)

lemma hC26 : coordMod timesTableO.basis mS (zeta1 ^ 26) = ![100731, 158085, 123814] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC25 (by decide)

lemma hC27 : coordMod timesTableO.basis mS (zeta1 ^ 27) = ![54577, 91535, 48068] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC26 (by decide)

lemma hC28 : coordMod timesTableO.basis mS (zeta1 ^ 28) = ![48690, 146112, 26899] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC27 (by decide)

lemma hC29 : coordMod timesTableO.basis mS (zeta1 ^ 29) = ![40648, 27521, 54420] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC28 (by decide)

lemma hC30 : coordMod timesTableO.basis mS (zeta1 ^ 30) = ![107058, 68169, 122589] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC29 (by decide)

lemma hC31 : coordMod timesTableO.basis mS (zeta1 ^ 31) = ![53863, 7946, 130535] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC30 (by decide)

lemma hC32 : coordMod timesTableO.basis mS (zeta1 ^ 32) = ![36960, 61809, 25063] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC31 (by decide)

lemma hC33 : coordMod timesTableO.basis mS (zeta1 ^ 33) = ![110828, 98769, 123832] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC32 (by decide)

lemma hC34 : coordMod timesTableO.basis mS (zeta1 ^ 34) = ![104030, 42316, 166148] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC33 (by decide)

lemma hC35 : coordMod timesTableO.basis mS (zeta1 ^ 35) = ![138903, 146346, 145213] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC34 (by decide)

lemma hC36 : coordMod timesTableO.basis mS (zeta1 ^ 36) = ![45179, 117968, 95900] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC35 (by decide)

lemma hC37 : coordMod timesTableO.basis mS (zeta1 ^ 37) = ![93932, 163147, 91766] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC36 (by decide)

lemma hC38 : coordMod timesTableO.basis mS (zeta1 ^ 38) = ![12349, 89798, 14283] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC37 (by decide)

lemma hC39 : coordMod timesTableO.basis mS (zeta1 ^ 39) = ![41805, 102147, 116430] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC38 (by decide)

lemma hC40 : coordMod timesTableO.basis mS (zeta1 ^ 40) = ![98568, 143952, 93101] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC39 (by decide)

lemma hC41 : coordMod timesTableO.basis mS (zeta1 ^ 41) = ![104922, 75239, 1059] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC40 (by decide)

lemma hC42 : coordMod timesTableO.basis mS (zeta1 ^ 42) = ![21275, 12880, 13939] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC41 (by decide)

lemma hC43 : coordMod timesTableO.basis mS (zeta1 ^ 43) = ![142558, 34155, 48094] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC42 (by decide)

lemma hC44 : coordMod timesTableO.basis mS (zeta1 ^ 44) = ![153152, 9432, 57526] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC43 (by decide)

lemma hC45 : coordMod timesTableO.basis mS (zeta1 ^ 45) = ![135564, 162584, 52829] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC44 (by decide)

lemma hC46 : coordMod timesTableO.basis mS (zeta1 ^ 46) = ![66773, 130867, 16415] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC45 (by decide)

lemma hC47 : coordMod timesTableO.basis mS (zeta1 ^ 47) = ![12855, 30359, 46774] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC46 (by decide)

lemma hC48 : coordMod timesTableO.basis mS (zeta1 ^ 48) = ![50940, 43214, 89988] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC47 (by decide)

lemma hC49 : coordMod timesTableO.basis mS (zeta1 ^ 49) = ![152106, 94154, 16861] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC48 (by decide)

lemma hC50 : coordMod timesTableO.basis mS (zeta1 ^ 50) = ![58022, 78979, 95840] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC49 (by decide)

lemma hC51 : coordMod timesTableO.basis mS (zeta1 ^ 51) = ![116820, 137001, 65560] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC50 (by decide)

lemma hC52 : coordMod timesTableO.basis mS (zeta1 ^ 52) = ![25734, 86540, 152100] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC51 (by decide)

lemma hC53 : coordMod timesTableO.basis mS (zeta1 ^ 53) = ![106449, 112274, 97093] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC52 (by decide)

lemma hC54 : coordMod timesTableO.basis mS (zeta1 ^ 54) = ![161254, 51442, 148535] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC53 (by decide)

lemma hC55 : coordMod timesTableO.basis mS (zeta1 ^ 55) = ![153987, 45415, 26669] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC54 (by decide)

lemma hC56 : coordMod timesTableO.basis mS (zeta1 ^ 56) = ![4884, 32121, 58790] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC55 (by decide)

lemma hC57 : coordMod timesTableO.basis mS (zeta1 ^ 57) = ![77811, 37005, 95795] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC56 (by decide)

lemma hC58 : coordMod timesTableO.basis mS (zeta1 ^ 58) = ![3229, 114816, 43330] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC57 (by decide)

lemma hC59 : coordMod timesTableO.basis mS (zeta1 ^ 59) = ![135074, 118045, 161375] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC58 (by decide)

lemma hC60 : coordMod timesTableO.basis mS (zeta1 ^ 60) = ![112823, 85838, 79932] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC59 (by decide)

lemma hC61 : coordMod timesTableO.basis mS (zeta1 ^ 61) = ![111571, 31380, 111312] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC60 (by decide)

lemma hC62 : coordMod timesTableO.basis mS (zeta1 ^ 62) = ![131620, 142951, 86982] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC61 (by decide)

lemma hC63 : coordMod timesTableO.basis mS (zeta1 ^ 63) = ![126285, 107290, 26991] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC62 (by decide)

lemma hC64 : coordMod timesTableO.basis mS (zeta1 ^ 64) = ![16871, 66294, 93285] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC63 (by decide)

lemma hC65 : coordMod timesTableO.basis mS (zeta1 ^ 65) = ![71885, 83165, 9169] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC64 (by decide)

lemma hC66 : coordMod timesTableO.basis mS (zeta1 ^ 66) = ![53513, 155050, 164219] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC65 (by decide)

lemma hC67 : coordMod timesTableO.basis mS (zeta1 ^ 67) = ![115552, 41282, 38220] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC66 (by decide)

lemma hC68 : coordMod timesTableO.basis mS (zeta1 ^ 68) = ![114909, 156834, 27773] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC67 (by decide)

lemma hC69 : coordMod timesTableO.basis mS (zeta1 ^ 69) = ![71914, 104462, 132235] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC68 (by decide)

lemma hC70 : coordMod timesTableO.basis mS (zeta1 ^ 70) = ![83489, 9095, 141330] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC69 (by decide)

lemma hC71 : coordMod timesTableO.basis mS (zeta1 ^ 71) = ![148725, 92584, 66633] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC70 (by decide)

lemma hC72 : coordMod timesTableO.basis mS (zeta1 ^ 72) = ![156286, 74028, 140661] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC71 (by decide)

lemma hC73 : coordMod timesTableO.basis mS (zeta1 ^ 73) = ![40202, 63033, 36413] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC72 (by decide)

lemma hC74 : coordMod timesTableO.basis mS (zeta1 ^ 74) = ![41685, 103235, 139648] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC73 (by decide)

lemma hC75 : coordMod timesTableO.basis mS (zeta1 ^ 75) = ![76283, 144920, 117287] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC74 (by decide)

lemma hC76 : coordMod timesTableO.basis mS (zeta1 ^ 76) = ![99851, 53922, 3928] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC75 (by decide)

lemma hC77 : coordMod timesTableO.basis mS (zeta1 ^ 77) = ![42371, 153773, 157701] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC76 (by decide)

lemma hC78 : coordMod timesTableO.basis mS (zeta1 ^ 78) = ![158069, 28863, 19283] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC77 (by decide)

lemma hC79 : coordMod timesTableO.basis mS (zeta1 ^ 79) = ![57111, 19651, 38934] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC78 (by decide)

lemma hC80 : coordMod timesTableO.basis mS (zeta1 ^ 80) = ![82163, 76762, 115696] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC79 (by decide)

lemma hC81 : coordMod timesTableO.basis mS (zeta1 ^ 81) = ![57079, 158925, 107340] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC80 (by decide)

lemma hC82 : coordMod timesTableO.basis mS (zeta1 ^ 82) = ![157052, 48723, 156063] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC81 (by decide)

lemma hC83 : coordMod timesTableO.basis mS (zeta1 ^ 83) = ![153427, 38494, 27276] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC82 (by decide)

lemma hC84 : coordMod timesTableO.basis mS (zeta1 ^ 84) = ![130361, 24640, 51916] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC83 (by decide)

lemma hC85 : coordMod timesTableO.basis mS (zeta1 ^ 85) = ![33615, 155001, 39636] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC84 (by decide)

lemma hC86 : coordMod timesTableO.basis mS (zeta1 ^ 86) = ![64879, 21335, 60971] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC85 (by decide)

lemma hC87 : coordMod timesTableO.basis mS (zeta1 ^ 87) = ![111584, 86214, 147185] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC86 (by decide)

lemma hC88 : coordMod timesTableO.basis mS (zeta1 ^ 88) = ![6829, 30517, 10421] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC87 (by decide)

lemma hC89 : coordMod timesTableO.basis mS (zeta1 ^ 89) = ![126150, 37346, 47767] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC88 (by decide)

lemma hC90 : coordMod timesTableO.basis mS (zeta1 ^ 90) = ![55480, 163496, 43982] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC89 (by decide)

lemma hC91 : coordMod timesTableO.basis mS (zeta1 ^ 91) = ![127699, 51695, 95677] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC90 (by decide)

lemma hC92 : coordMod timesTableO.basis mS (zeta1 ^ 92) = ![105315, 12113, 107790] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC91 (by decide)

lemma hC93 : coordMod timesTableO.basis mS (zeta1 ^ 93) = ![118375, 117428, 57937] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC92 (by decide)

lemma hC94 : coordMod timesTableO.basis mS (zeta1 ^ 94) = ![40724, 68522, 126459] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC93 (by decide)

lemma hC95 : coordMod timesTableO.basis mS (zeta1 ^ 95) = ![116706, 109246, 68424] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC94 (by decide)

lemma hC96 : coordMod timesTableO.basis mS (zeta1 ^ 96) = ![42871, 58671, 127095] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC95 (by decide)

lemma hC97 : coordMod timesTableO.basis mS (zeta1 ^ 97) = ![76445, 101542, 61356] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC96 (by decide)

lemma hC98 : coordMod timesTableO.basis mS (zeta1 ^ 98) = ![6974, 10706, 72062] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC97 (by decide)

lemma hC99 : coordMod timesTableO.basis mS (zeta1 ^ 99) = ![43583, 17680, 89742] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC98 (by decide)

lemma hC100 : coordMod timesTableO.basis mS (zeta1 ^ 100) = ![113208, 61263, 151005] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC99 (by decide)

lemma hC101 : coordMod timesTableO.basis mS (zeta1 ^ 101) = ![58692, 7190, 158195] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC100 (by decide)

lemma hC102 : coordMod timesTableO.basis mS (zeta1 ^ 102) = ![64906, 65882, 56796] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC101 (by decide)

lemma hC103 : coordMod timesTableO.basis mS (zeta1 ^ 103) = ![19443, 130788, 20303] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC102 (by decide)

lemma hC104 : coordMod timesTableO.basis mS (zeta1 ^ 104) = ![38961, 150231, 3253] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC103 (by decide)

lemma hC105 : coordMod timesTableO.basis mS (zeta1 ^ 105) = ![22664, 21911, 25164] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC104 (by decide)

lemma hC106 : coordMod timesTableO.basis mS (zeta1 ^ 106) = ![106536, 44575, 69739] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC105 (by decide)

lemma hC107 : coordMod timesTableO.basis mS (zeta1 ^ 107) = ![93388, 151111, 53569] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC106 (by decide)

lemma hC108 : coordMod timesTableO.basis mS (zeta1 ^ 108) = ![41705, 77218, 130787] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC107 (by decide)

lemma hC109 : coordMod timesTableO.basis mS (zeta1 ^ 109) = ![34436, 118923, 82429] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC108 (by decide)

lemma hC110 : coordMod timesTableO.basis mS (zeta1 ^ 110) = ![110916, 153359, 68507] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC109 (by decide)

lemma hC111 : coordMod timesTableO.basis mS (zeta1 ^ 111) = ![100236, 96994, 165501] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC110 (by decide)

lemma hC112 : coordMod timesTableO.basis mS (zeta1 ^ 112) = ![101969, 29949, 28169] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC111 (by decide)

lemma hC113 : coordMod timesTableO.basis mS (zeta1 ^ 113) = ![58805, 131918, 160087] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC112 (by decide)

lemma hC114 : coordMod timesTableO.basis mS (zeta1 ^ 114) = ![156293, 23442, 16248] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC113 (by decide)

lemma hC115 : coordMod timesTableO.basis mS (zeta1 ^ 115) = ![161224, 12454, 28702] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC114 (by decide)

lemma hC116 : coordMod timesTableO.basis mS (zeta1 ^ 116) = ![37256, 6397, 35099] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC115 (by decide)

lemma hC117 : coordMod timesTableO.basis mS (zeta1 ^ 117) = ![7925, 43653, 78752] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC116 (by decide)

lemma hC118 : coordMod timesTableO.basis mS (zeta1 ^ 118) = ![120781, 51578, 130330] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC117 (by decide)

lemma hC119 : coordMod timesTableO.basis mS (zeta1 ^ 119) = ![96824, 5078, 135408] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC118 (by decide)

lemma hC120 : coordMod timesTableO.basis mS (zeta1 ^ 120) = ![15155, 101902, 70029] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC119 (by decide)

lemma hC121 : coordMod timesTableO.basis mS (zeta1 ^ 121) = ![133985, 117057, 19805] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC120 (by decide)

lemma hC122 : coordMod timesTableO.basis mS (zeta1 ^ 122) = ![86257, 83761, 103566] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC121 (by decide)

lemma hC123 : coordMod timesTableO.basis mS (zeta1 ^ 123) = ![54951, 2737, 106303] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC122 (by decide)

lemma hC124 : coordMod timesTableO.basis mS (zeta1 ^ 124) = ![35211, 57688, 163991] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC123 (by decide)

lemma hC125 : coordMod timesTableO.basis mS (zeta1 ^ 125) = ![71022, 92899, 89609] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC124 (by decide)

lemma hC126 : coordMod timesTableO.basis mS (zeta1 ^ 126) = ![86673, 163921, 86249] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC125 (by decide)

lemma hC127 : coordMod timesTableO.basis mS (zeta1 ^ 127) = ![100359, 83313, 2281] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC126 (by decide)

lemma hC128 : coordMod timesTableO.basis mS (zeta1 ^ 128) = ![45110, 16391, 18672] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC127 (by decide)

lemma hC129 : coordMod timesTableO.basis mS (zeta1 ^ 129) = ![24305, 61501, 80173] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC128 (by decide)

lemma hC130 : coordMod timesTableO.basis mS (zeta1 ^ 130) = ![16493, 85806, 165979] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC129 (by decide)

lemma hC131 : coordMod timesTableO.basis mS (zeta1 ^ 131) = ![120632, 102299, 100997] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC130 (by decide)

lemma hC132 : coordMod timesTableO.basis mS (zeta1 ^ 132) = ![56828, 55650, 156647] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC131 (by decide)

lemma hC133 : coordMod timesTableO.basis mS (zeta1 ^ 133) = ![166049, 112478, 101844] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC132 (by decide)

lemma hC134 : coordMod timesTableO.basis mS (zeta1 ^ 134) = ![106341, 111246, 45809] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC133 (by decide)

lemma hC135 : coordMod timesTableO.basis mS (zeta1 ^ 135) = ![13907, 50306, 96115] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC134 (by decide)

lemma hC136 : coordMod timesTableO.basis mS (zeta1 ^ 136) = ![139470, 64213, 160328] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC135 (by decide)

/-! ### `(S3)`: the sieve -/

lemma hS1 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 1)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC1 kMu).mpr (by decide)

lemma hS2 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 2)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC2 kMu).mpr (by decide)

lemma hS3 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 3)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC3 kMu).mpr (by decide)

lemma hS4 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 4)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC4 kMu).mpr (by decide)

lemma hS5 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 5)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC5 kMu).mpr (by decide)

lemma hS6 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 6)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC6 kMu).mpr (by decide)

lemma hS7 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 7)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC7 kMu).mpr (by decide)

lemma hS8 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 8)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC8 kMu).mpr (by decide)

lemma hS9 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 9)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC9 kMu).mpr (by decide)

lemma hS10 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 10)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC10 kMu).mpr (by decide)

lemma hS11 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 11)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC11 kMu).mpr (by decide)

lemma hS12 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 12)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC12 kMu).mpr (by decide)

lemma hS13 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 13)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC13 kMu).mpr (by decide)

lemma hS14 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 14)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC14 kMu).mpr (by decide)

lemma hS15 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 15)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC15 kMu).mpr (by decide)

lemma hS16 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 16)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC16 kMu).mpr (by decide)

lemma hS17 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 17)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC17 kMu).mpr (by decide)

lemma hS18 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 18)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC18 kMu).mpr (by decide)

lemma hS19 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 19)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC19 kMu).mpr (by decide)

lemma hS20 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 20)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC20 kMu).mpr (by decide)

lemma hS21 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 21)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC21 kMu).mpr (by decide)

lemma hS22 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 22)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC22 kMu).mpr (by decide)

lemma hS23 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 23)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC23 kMu).mpr (by decide)

lemma hS24 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 24)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC24 kMu).mpr (by decide)

lemma hS25 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 25)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC25 kMu).mpr (by decide)

lemma hS26 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 26)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC26 kMu).mpr (by decide)

lemma hS27 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 27)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC27 kMu).mpr (by decide)

lemma hS28 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 28)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC28 kMu).mpr (by decide)

lemma hS29 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 29)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC29 kMu).mpr (by decide)

lemma hS30 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 30)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC30 kMu).mpr (by decide)

lemma hS31 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 31)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC31 kMu).mpr (by decide)

lemma hS32 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 32)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC32 kMu).mpr (by decide)

lemma hS33 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 33)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC33 kMu).mpr (by decide)

lemma hS34 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 34)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC34 kMu).mpr (by decide)

lemma hS35 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 35)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC35 kMu).mpr (by decide)

lemma hS36 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 36)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC36 kMu).mpr (by decide)

lemma hS37 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 37)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC37 kMu).mpr (by decide)

lemma hS38 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 38)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC38 kMu).mpr (by decide)

lemma hS39 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 39)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC39 kMu).mpr (by decide)

lemma hS40 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 40)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC40 kMu).mpr (by decide)

lemma hS41 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 41)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC41 kMu).mpr (by decide)

lemma hS42 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 42)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC42 kMu).mpr (by decide)

lemma hS43 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 43)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC43 kMu).mpr (by decide)

lemma hS44 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 44)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC44 kMu).mpr (by decide)

lemma hS45 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 45)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC45 kMu).mpr (by decide)

lemma hS46 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 46)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC46 kMu).mpr (by decide)

lemma hS47 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 47)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC47 kMu).mpr (by decide)

lemma hS48 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 48)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC48 kMu).mpr (by decide)

lemma hS49 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 49)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC49 kMu).mpr (by decide)

lemma hS50 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 50)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC50 kMu).mpr (by decide)

lemma hS51 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 51)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC51 kMu).mpr (by decide)

lemma hS52 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 52)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC52 kMu).mpr (by decide)

lemma hS53 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 53)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC53 kMu).mpr (by decide)

lemma hS54 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 54)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC54 kMu).mpr (by decide)

lemma hS55 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 55)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC55 kMu).mpr (by decide)

lemma hS56 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 56)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC56 kMu).mpr (by decide)

lemma hS57 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 57)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC57 kMu).mpr (by decide)

lemma hS58 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 58)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC58 kMu).mpr (by decide)

lemma hS59 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 59)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC59 kMu).mpr (by decide)

lemma hS60 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 60)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC60 kMu).mpr (by decide)

lemma hS61 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 61)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC61 kMu).mpr (by decide)

lemma hS62 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 62)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC62 kMu).mpr (by decide)

lemma hS63 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 63)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC63 kMu).mpr (by decide)

lemma hS64 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 64)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC64 kMu).mpr (by decide)

lemma hS65 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 65)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC65 kMu).mpr (by decide)

lemma hS66 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 66)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC66 kMu).mpr (by decide)

lemma hS67 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 67)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC67 kMu).mpr (by decide)

lemma hS68 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 68)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC68 kMu).mpr (by decide)

lemma hS69 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 69)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC69 kMu).mpr (by decide)

lemma hS70 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 70)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC70 kMu).mpr (by decide)

lemma hS71 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 71)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC71 kMu).mpr (by decide)

lemma hS72 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 72)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC72 kMu).mpr (by decide)

lemma hS73 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 73)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC73 kMu).mpr (by decide)

lemma hS74 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 74)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC74 kMu).mpr (by decide)

lemma hS75 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 75)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC75 kMu).mpr (by decide)

lemma hS76 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 76)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC76 kMu).mpr (by decide)

lemma hS77 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 77)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC77 kMu).mpr (by decide)

lemma hS78 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 78)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC78 kMu).mpr (by decide)

lemma hS79 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 79)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC79 kMu).mpr (by decide)

lemma hS80 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 80)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC80 kMu).mpr (by decide)

lemma hS81 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 81)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC81 kMu).mpr (by decide)

lemma hS82 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 82)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC82 kMu).mpr (by decide)

lemma hS83 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 83)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC83 kMu).mpr (by decide)

lemma hS84 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 84)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC84 kMu).mpr (by decide)

lemma hS85 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 85)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC85 kMu).mpr (by decide)

lemma hS86 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 86)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC86 kMu).mpr (by decide)

lemma hS87 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 87)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC87 kMu).mpr (by decide)

lemma hS88 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 88)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC88 kMu).mpr (by decide)

lemma hS89 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 89)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC89 kMu).mpr (by decide)

lemma hS90 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 90)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC90 kMu).mpr (by decide)

lemma hS91 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 91)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC91 kMu).mpr (by decide)

lemma hS92 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 92)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC92 kMu).mpr (by decide)

lemma hS93 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 93)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC93 kMu).mpr (by decide)

lemma hS94 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 94)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC94 kMu).mpr (by decide)

lemma hS95 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 95)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC95 kMu).mpr (by decide)

lemma hS96 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 96)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC96 kMu).mpr (by decide)

lemma hS97 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 97)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC97 kMu).mpr (by decide)

lemma hS98 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 98)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC98 kMu).mpr (by decide)

lemma hS99 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 99)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC99 kMu).mpr (by decide)

lemma hS100 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 100)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC100 kMu).mpr (by decide)

lemma hS101 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 101)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC101 kMu).mpr (by decide)

lemma hS102 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 102)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC102 kMu).mpr (by decide)

lemma hS103 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 103)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC103 kMu).mpr (by decide)

lemma hS104 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 104)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC104 kMu).mpr (by decide)

lemma hS105 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 105)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC105 kMu).mpr (by decide)

lemma hS106 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 106)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC106 kMu).mpr (by decide)

lemma hS107 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 107)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC107 kMu).mpr (by decide)

lemma hS108 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 108)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC108 kMu).mpr (by decide)

lemma hS109 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 109)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC109 kMu).mpr (by decide)

lemma hS110 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 110)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC110 kMu).mpr (by decide)

lemma hS111 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 111)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC111 kMu).mpr (by decide)

lemma hS112 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 112)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC112 kMu).mpr (by decide)

lemma hS113 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 113)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC113 kMu).mpr (by decide)

lemma hS114 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 114)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC114 kMu).mpr (by decide)

lemma hS115 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 115)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC115 kMu).mpr (by decide)

lemma hS116 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 116)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC116 kMu).mpr (by decide)

lemma hS117 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 117)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC117 kMu).mpr (by decide)

lemma hS118 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 118)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC118 kMu).mpr (by decide)

lemma hS119 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 119)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC119 kMu).mpr (by decide)

lemma hS120 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 120)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC120 kMu).mpr (by decide)

lemma hS121 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 121)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC121 kMu).mpr (by decide)

lemma hS122 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 122)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC122 kMu).mpr (by decide)

lemma hS123 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 123)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC123 kMu).mpr (by decide)

lemma hS124 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 124)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC124 kMu).mpr (by decide)

lemma hS125 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 125)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC125 kMu).mpr (by decide)

lemma hS126 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 126)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC126 kMu).mpr (by decide)

lemma hS127 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 127)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC127 kMu).mpr (by decide)

lemma hS128 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 128)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC128 kMu).mpr (by decide)

lemma hS129 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 129)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC129 kMu).mpr (by decide)

lemma hS130 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 130)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC130 kMu).mpr (by decide)

lemma hS131 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 131)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC131 kMu).mpr (by decide)

lemma hS133 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 133)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC133 kMu).mpr (by decide)

lemma hS134 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 134)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC134 kMu).mpr (by decide)

/-- **`(S3)`.**  `409 ∤ mu (zeta1 ^ r)` for every `r < 136` outside the surviving
classes 0, 132, 135. -/
theorem not_dvd_mu_zeta1_pow : ∀ r : ℕ, r < 136 → r ≠ 0 → r ≠ 132 → r ≠ 135 → ¬ ((pS : ℤ) ∣ mu (zeta1 ^ r)) := by
  intro r hr h0 h132 h135
  interval_cases r
  · exact absurd rfl h0
  · exact hS1
  · exact hS2
  · exact hS3
  · exact hS4
  · exact hS5
  · exact hS6
  · exact hS7
  · exact hS8
  · exact hS9
  · exact hS10
  · exact hS11
  · exact hS12
  · exact hS13
  · exact hS14
  · exact hS15
  · exact hS16
  · exact hS17
  · exact hS18
  · exact hS19
  · exact hS20
  · exact hS21
  · exact hS22
  · exact hS23
  · exact hS24
  · exact hS25
  · exact hS26
  · exact hS27
  · exact hS28
  · exact hS29
  · exact hS30
  · exact hS31
  · exact hS32
  · exact hS33
  · exact hS34
  · exact hS35
  · exact hS36
  · exact hS37
  · exact hS38
  · exact hS39
  · exact hS40
  · exact hS41
  · exact hS42
  · exact hS43
  · exact hS44
  · exact hS45
  · exact hS46
  · exact hS47
  · exact hS48
  · exact hS49
  · exact hS50
  · exact hS51
  · exact hS52
  · exact hS53
  · exact hS54
  · exact hS55
  · exact hS56
  · exact hS57
  · exact hS58
  · exact hS59
  · exact hS60
  · exact hS61
  · exact hS62
  · exact hS63
  · exact hS64
  · exact hS65
  · exact hS66
  · exact hS67
  · exact hS68
  · exact hS69
  · exact hS70
  · exact hS71
  · exact hS72
  · exact hS73
  · exact hS74
  · exact hS75
  · exact hS76
  · exact hS77
  · exact hS78
  · exact hS79
  · exact hS80
  · exact hS81
  · exact hS82
  · exact hS83
  · exact hS84
  · exact hS85
  · exact hS86
  · exact hS87
  · exact hS88
  · exact hS89
  · exact hS90
  · exact hS91
  · exact hS92
  · exact hS93
  · exact hS94
  · exact hS95
  · exact hS96
  · exact hS97
  · exact hS98
  · exact hS99
  · exact hS100
  · exact hS101
  · exact hS102
  · exact hS103
  · exact hS104
  · exact hS105
  · exact hS106
  · exact hS107
  · exact hS108
  · exact hS109
  · exact hS110
  · exact hS111
  · exact hS112
  · exact hS113
  · exact hS114
  · exact hS115
  · exact hS116
  · exact hS117
  · exact hS118
  · exact hS119
  · exact hS120
  · exact hS121
  · exact hS122
  · exact hS123
  · exact hS124
  · exact hS125
  · exact hS126
  · exact hS127
  · exact hS128
  · exact hS129
  · exact hS130
  · exact hS131
  · exact absurd rfl h132
  · exact hS133
  · exact hS134
  · exact absurd rfl h135

/-! ### `(S1)`, `(S2)` and the re-centering data -/

/-- The coordinates of `δ = (zeta1 ^ 136 - 1) / 409` modulo `409`. -/
def eDelta : Fin 3 → ZMod pS := ![341, 157, 392]

/-- The times table of `O`, reduced modulo `409`. -/
def TModP : Fin 3 → Fin 3 → List (ZMod pS) :=
 ![ ![[1, 0, 0], [0, 1, 0], [0, 0, 1]],
 ![[0, 1, 0], [0, 0, 1], [6, 403, 0]],
 ![[0, 0, 1], [6, 403, 0], [0, 6, 403]]]

lemma hTModP : ∀ i j, List.map (algebraMap ℤ (ZMod pS)) (Table i j) = TModP i j := by decide

lemma hP0 : coordMod timesTableO.basis pS (zeta1 ^ 0) = ![1, 0, 0] := by
  rw [coordMod_castHom (by norm_num : pS ∣ mS), hC0]
  funext i; fin_cases i <;> decide

lemma hP132 : coordMod timesTableO.basis pS (zeta1 ^ 132) = ![386, 26, 0] := by
  rw [coordMod_castHom (by norm_num : pS ∣ mS), hC132]
  funext i; fin_cases i <;> decide

lemma hP135 : coordMod timesTableO.basis pS (zeta1 ^ 135) = ![1, 408, 0] := by
  rw [coordMod_castHom (by norm_num : pS ∣ mS), hC135]
  funext i; fin_cases i <;> decide

/-- **`(S1)`, `(S2)` and re-centering.**  `zeta1 ^ 136 = 409 δ + 1` with `409 ∤ mu δ`,
and `409 ∤ mu (zeta1 ^ r * δ)` for each surviving class `r`, so no such class holds two
solutions. -/
theorem zeta1_pow_136 : ∃ δ : O, zeta1 ^ 136 = pS * δ + 1 ∧ ¬ ((pS : ℤ) ∣ mu δ) ∧ ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 0 * δ)) ∧ ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 132 * δ)) ∧ ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 135 * δ)) := by
  obtain ⟨δ, hδ, hc⟩ := exists_delta_of_coordMod (b := timesTableO.basis) (by norm_num)
    (i₀ := 0) B_one hC136 eDelta (by decide)
  refine ⟨δ, hδ, (not_dvd_muOfBasis_iff dvd_rfl hc kMu).mpr (by decide), ?_, ?_, ?_⟩
  · exact (not_dvd_muOfBasis_iff dvd_rfl (coordMod_mul timesTableT_eq_Table
      hTModP hP0 hc (c := ![341, 157, 392]) (by decide)) kMu).mpr (by decide)
  · exact (not_dvd_muOfBasis_iff dvd_rfl (coordMod_mul timesTableT_eq_Table
      hTModP hP132 hc (c := ![139, 136, 383]) (by decide)) kMu).mpr (by decide)
  · exact (not_dvd_muOfBasis_iff dvd_rfl (coordMod_mul timesTableT_eq_Table
      hTModP hP135 hc (c := ![34, 123, 235]) (by decide)) kMu).mpr (by decide)

end

end NF3_1_1836_2
