import IdealArithmetic.TimesTableAsLists
import IdealArithmetic.TimesTable.Defs
import Mathlib.RingTheory.IsAdjoinRoot
import Mathlib.LinearAlgebra.Dimension.DivisionRing
import Mathlib.LinearAlgebra.FreeModule.PID
import IdealArithmetic.AlgebraAuxiliaryLemmas
import Mathlib.LinearAlgebra.Dimension.Finite
import Mathlib.RingTheory.Adjoin.PowerBasis
import Mathlib.LinearAlgebra.Dimension.StrongRankCondition
import IdealArithmetic.QuotientModules
import Mathlib.Algebra.Module.Submodule.RestrictScalars
import Mathlib.Tactic
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.Data.Matrix.Rank
import Mathlib.Algebra.Group.Subgroup.Finsupp
import Mathlib.NumberTheory.NumberField.Units.Basic
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.GroupTheory.Complement

/- # Ideal arithmetic

We define certificates for basic ideal operations.

## Main definition
- `IdealEqSpanCertificate`: to certify an `R`-spanning set of an ideal.
- `IdealEqCertificateO` : certifies equality of ideals given `O`-generators.
- `BasisOfEqSpan`: an `R`-basis of an ideal given the right number of `R`-generators.
- `IdealMemCertificate` : certifies membership in an ideal.
- `IdealMulEqCertificate`: certifies a multiplication of ideals.
- `IsInClass` : expresses that two ideals belong to the same ideal class.


-/

section I

variable {S : Type*} {O R : Type*} [CommRing O] [CommRing R] [CommRing S]
open BigOperators Classical

/-- Condition for containment if the `R`-span is also an `S`-module. -/
lemma submodule_span_le_span_iff [Module R O] [Module S O] {ι τ : Type _} [Fintype ι] [Fintype τ]
  (v : ι → O) (w : τ → O) (I : Set O) (hI : I = Submodule.span R (Set.range w))
  (hsmul : ∀ (s : S) {x : O}, x ∈ I → s • x ∈ I) :
  (Submodule.span S (Set.range v)).carrier ⊆ (Submodule.span R (Set.range w)) ↔
  ∀ (i : ι), (∃ (a : τ → R), v i = ∑ (j : τ), (a j) • (w j) ) := by
  constructor
  · intro h i
    have hvin : v i ∈ (Submodule.span S (Set.range v)).carrier := by
      exact Submodule.subset_span (R := S) (by simp only [Set.mem_range, exists_apply_eq_apply] )
    have hvw := h hvin
    erw [Submodule.mem_span_range_iff_exists_fun] at hvw
    obtain ⟨a, ha⟩ :=  hvw
    use a
    exact ha.symm
  · intro h
    have : ∀ i , v i ∈ (Submodule.span R (Set.range w)) := by
      intro i
      rw [Submodule.mem_span_range_iff_exists_fun]
      obtain ⟨a, ha⟩ := h i
      use a
      exact ha.symm
    let P : Submodule S O :=
      { carrier := I
        add_mem' := by
          rw [hI]
          intro a b ha hb
          exact (Submodule.add_mem_iff_right (Submodule.span R (Set.range w)) ha).mpr hb
        zero_mem' := by
          rw [hI]
          exact zero_mem (Submodule.span R (Set.range w))
        smul_mem' := by
          exact hsmul }
    have hleaux : Set.range v ⊆ P := by
      rintro a ⟨i, hi⟩
      simp only [Submodule.coe_set_mk, AddSubmonoid.coe_set_mk, AddSubsemigroup.coe_set_mk, P]
      rw [← hi, hI, SetLike.mem_coe]
      exact this i
    rw [← Submodule.span_le] at hleaux
    rw [← hI]
    exact hleaux

/-- If `B` spans `O` as `ℤ`-module, then the ideal generated by `v` is the `R`-span of `vᵢ * vⱼ`. -/
lemma ideal_eq_R_span [Algebra R O] {ι τ : Type _} [Fintype ι] [Fintype τ]
    (v : ι → O) (B : τ → O) (hspan : ⊤ = Submodule.span R (Set.range B)) :
    (Ideal.span (Set.range v)).carrier =
    Submodule.span R (Set.range (fun ⟨i, j⟩ => (v i) * (B j) : ι × τ → O )) := by
  ext x
  constructor
  · intro hx
    erw [Submodule.mem_span_range_iff_exists_fun] at hx
    obtain ⟨c, hc⟩ := hx
    have hmem : ∀ i , c i ∈ Submodule.span R (Set.range B) := by
      intro i
      rw [← hspan]
      simp only [Submodule.mem_top]
    simp_rw [Submodule.mem_span_range_iff_exists_fun] at hmem
    let f : ι → (τ → R) := fun i => ((hmem i).choose)
    have hceq : ∀ i , ∑ j : τ , (f i j) • (B j) = c i := by
      intro i
      exact (hmem i).choose_spec
    simp_rw [← hceq] at hc
    erw [Submodule.mem_span_range_iff_exists_fun, ← hc]
    use (fun ⟨i, j⟩ => f i j)
    dsimp
    let F : ι → (τ → O) := fun i => (fun j => (f i j) • ((v i) * (B j)))
    rw [Fintype.sum_prod_type' F]
    simp_rw [Finset.sum_mul]
    congr ; ext i ; congr ; ext j
    rw [Algebra.smul_mul_assoc, mul_comm]
  · intro hx
    erw [Submodule.mem_span_range_iff_exists_fun] at hx
    obtain ⟨c, hc⟩ := hx
    rw [← hc]
    refine Submodule.sum_mem _ ?_
    intro i _
    dsimp
    rw [mul_comm, ← Algebra.smul_mul_assoc]
    refine Ideal.mul_mem_left _ _ (Ideal.subset_span ?_)
    exact Set.mem_range_self i.1


lemma ideal_eq_R_span' [Algebra R O] {ι τ κ: Type _} [Fintype ι] [Fintype τ]
  [Fintype κ] (v : ι → O) (B : τ → O) (w : κ → O)
  (hspan : ⊤ = Submodule.span R (Set.range B))
  (h1 : ∀ k, (∃ (f : ι → τ → R) , w k = ∑ i , ∑ j , f i j • ((v i) * (B j))))
  (h2 : ∀ i j , (∃ (g : κ → R), (v i) * (B j) = ∑ k, (g k) • (w k) )) :
   (Ideal.span (Set.range v)).carrier = Submodule.span R (Set.range w) := by
  rw [ideal_eq_R_span v B hspan]
  refine subset_antisymm ?_ ?_
  erw [submodule_span_le_span_iff _ _ ((Submodule.span R (Set.range w)).carrier)]
  · rintro ⟨i , j⟩
    use (h2 i j).choose
    exact (h2 i j).choose_spec
  · rfl
  · intro s x hx
    exact (Submodule.span R (Set.range w)).smul_mem' s hx
  erw [submodule_span_le_span_iff]
  · intro k
    use (fun ⟨i , j⟩ =>  (h1 k).choose i j)
    simp_rw [(h1 k).choose_spec]
    exact Eq.symm (Fintype.sum_prod_type fun x ↦ (h1 k).choose x.1 x.2 • (v x.1 * B x.2))
  · exact (Submodule.span R (Set.range (fun ⟨i, j⟩ => (v i) * (B j) : ι × τ → O ))).carrier
  · rfl
  · intro s x hx
    exact Submodule.smul_mem' _ s hx

-- v are O-generators and w are Z-generators. we include them as parameters so we can easily reuse
-- them and we don't have to use projections in the correctness statement. Since corrdinates are
-- in respect to a basis, we include the times table as a parameter as well.

/- For an ideal `I`, given `O`-generators `v` and `R`-generators `w`, this certifies that
  `I` equals the `R`-span of `w`. -/
structure IdealEqSpanCertificate [Algebra R O] {r n m : ℕ}
   (TT  : TimesTable (Fin r) R O) (I : Ideal O)
   (v : Fin m → Fin r → R) (w : Fin n → Fin r → R)  where
  /-- Times table in term of lists. -/
  T : Fin r → Fin r → List R
  heq : ∀ i j , T i j = List.ofFn (TT.table i j)
  hieq : I = Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (v i)))
  f : Fin n → Fin m → Fin r → R
  g : Fin m → Fin r → Fin n → R
  M : Fin m → Fin r → Fin r → R -- products (v i) * (B j)
  hmulB : ∀ i j, table_mul_list T (List.ofFn (v i)) (List.ofFn (fun k => if k = j then 1 else 0 ))
    = List.ofFn (M i j)
  hle1 : ∀ k , List.ofFn (w k) = List.sum (List.ofFn (fun i => List.sum
    (List.ofFn (fun j => List.mulPointwise (f k i j) (List.ofFn (M i j) ) ))))
  hle2 : ∀ i j, List.ofFn (M i j) =
    List.sum (List.ofFn (fun k => List.mulPointwise (g i j k) (List.ofFn (w k))))

/-- Proof of correctness of `IdealEqSpanCertificate`. -/
lemma ideal_eq_of_IdealEqSpanCertificate [Algebra R O] {r n m : ℕ} [NeZero r]
    {TT  : TimesTable (Fin r) R O} {I : Ideal O}
    {v : Fin m → Fin r → R} {w : Fin n → Fin r → R} (A : IdealEqSpanCertificate TT I v w) :
    I.carrier = Submodule.span R (Set.range (fun i => (TT.basis).equivFun.symm (w i))) := by
  rw [A.hieq]
  have aux := A.hmulB
  simp_rw [table_mul_eq_table_mul' TT.table A.T A.heq] at aux
  have hmulaux :=
    fun i j => table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis (aux i j).symm
  have : ∀ j , TT.basis.equivFun.symm (fun k ↦ if k = j then 1 else 0) = TT.basis j := by
    simp only [Basis.equivFun_symm_apply, ite_smul, one_smul, zero_smul, Finset.sum_ite_eq',
      Finset.mem_univ, ↓reduceIte, implies_true]
  simp_rw [this] at hmulaux
  refine ideal_eq_R_span' _ (TT.basis) _ ?_ ?_ ?_
  · exact Eq.symm (Basis.span_eq TT.basis)
  · intro k
    use (A.f k)
    have hle1 := A.hle1
    simp_rw [List.mulPointwise_ofFn, ← List.sum_ofFn' (Ne.symm (NeZero.ne' r))] at hle1
    convert table_sum_smul' TT.basis _ _ (hle1 k)
    simp_rw [hmulaux]
    simp only [Basis.equivFun_symm_apply, map_sum, map_smul]
  · intro i j
    use (A.g i j)
    simp_rw [hmulaux]
    refine table_sum_smul TT.basis _ _ _ ?_
    exact A.hle2 i j

/-- Certificate for `I ≤ J` given `R`-generators. -/
structure IdealLeCertificate [Algebra R O] {r n m : ℕ}
    (B  : Basis (Fin r) R O) (I : Ideal O) (J : Ideal O) (v : Fin m → Fin r → R)
    (w : Fin n → Fin r → R)  where
  hieq1 : I.carrier = Submodule.span R (Set.range (fun i => B.equivFun.symm (v i)))
  hieq2 : J.carrier = Submodule.span R (Set.range (fun j => B.equivFun.symm (w j)))
  g : Fin m → Fin n → R
  hle2 : ∀ i, List.ofFn (v i) =
    List.sum (List.ofFn (fun k => List.mulPointwise (g i k) (List.ofFn (w k))))

/-- Proof of correctness for `IdealLeCertificate`. -/
lemma ideal_le_of_certificate [Algebra R O] {r n m : ℕ}
   (B  : Basis (Fin r) R O) (I : Ideal O) (J : Ideal O) (v : Fin m → Fin r → R)
   (w : Fin n → Fin r → R) (A : IdealLeCertificate B I J v w) : I ≤ J := by
  show (I.carrier ⊆ J.carrier)
  rw [A.hieq1, A.hieq2]
  convert (submodule_span_le_span_iff (fun i => B.equivFun.symm (v i))
    (fun i => B.equivFun.symm (w i))
    _ rfl (by intro s hs ; exact fun a ↦ SMulMemClass.smul_mem s a)).2 ?_
  · intro i
    use (A.g i)
    refine table_sum_smul B w (v i) (A.g i) ?_
    exact (A.hle2 i)

/-- Certificate for `I ≤ J` using `O`-generators for `J` and `S`-generators for `I`. -/
structure IdealLeCertificateO [Algebra R O] (S : Type*) [CommRing S] [Algebra S O]
    {r n m : ℕ} (TT  : TimesTable (Fin r) R O)  (I : Ideal O) (J : Ideal O) (v : Fin m → Fin r → R)
    (w : Fin n → Fin r → R) where
  T : Fin r → Fin r → List R
  heq : ∀ i j , T i j = List.ofFn (TT.table i j)
  hieq1 : I.carrier = Submodule.span S (Set.range (fun i => TT.basis.equivFun.symm (v i)))
  hieq2 : J = Ideal.span (Set.range (fun j => TT.basis.equivFun.symm (w j)))
  g : Fin m → Fin n → Fin r → R
  hle2 : ∀ i, List.ofFn (v i) =
    List.sum (List.ofFn (fun k => table_mul_list T  (List.ofFn (g i k)) (List.ofFn (w k))))

/-- Proof of correctness of `IdealLeCertificateO`. -/
lemma ideal_le_of_IdealLeCertificateO [Algebra R O] (S : Type*) [CommRing S] [Algebra S O]
    {r n m : ℕ} (TT  : TimesTable (Fin r) R O) (I : Ideal O) (J : Ideal O) (v : Fin m → Fin r → R)
    (w : Fin n → Fin r → R) (A : IdealLeCertificateO S TT I J v w) : I ≤ J := by
  show I.carrier ⊆ J.carrier
  rw [A.hieq1, A.hieq2]
  unfold Ideal.span
  erw [submodule_span_le_span_iff (S := S) (fun j => TT.basis.equivFun.symm (v j))
    (fun j => TT.basis.equivFun.symm (w j)) J.carrier ?_ ?_]
  · intro i
    use (fun j => TT.basis.equivFun.symm (A.g i j) )
    simp_rw [smul_eq_mul]
    refine table_sum_mul TT.table TT.basis TT.basis_mul_basis _ _ _ ?_
    simp_rw [← table_mul_eq_table_mul' TT.table A.T A.heq]
    exact A.hle2 i
  · rw [A.hieq2]
    rfl
  · intro s x hx
    rw [algebra_compatible_smul O s x]
    exact J.smul_mem' ((algebraMap S O) s) hx

/-- Certifies equality of ideals from `O`-generators. -/
structure IdealEqCertificateO [Algebra R O]
    {r n m : ℕ} (TT  : TimesTable (Fin r) R O) (I : Ideal O) (J : Ideal O) (v : Fin m → Fin r → R)
    (w : Fin n → Fin r → R) where
  T : Fin r → Fin r → List R
  heq : ∀ i j , T i j = List.ofFn (TT.table i j)
  hieq1 : I = Ideal.span (Set.range (fun i => TT.basis.equivFun.symm (v i)))
  hieq2 : J = Ideal.span (Set.range (fun j => TT.basis.equivFun.symm (w j)))
  g : Fin m → Fin n → Fin r → R
  h : Fin n → Fin m → Fin r → R
  hle1 : ∀ i, List.ofFn (v i) =
    List.sum (List.ofFn (fun k => table_mul_list T  (List.ofFn (g i k)) (List.ofFn (w k))))
  hle2 : ∀ i, List.ofFn (w i) =
    List.sum (List.ofFn (fun k => table_mul_list T  (List.ofFn (h i k)) (List.ofFn (v k))))

/-- Proof of correctness of `IdealEqCertificateO`. -/
lemma ideal_eq_of_IdealEqCertificateO [Algebra R O]
    {r n m : ℕ} (TT  : TimesTable (Fin r) R O) (I : Ideal O) (J : Ideal O) (v : Fin m → Fin r → R)
    (w : Fin n → Fin r → R) (A : IdealEqCertificateO TT I J v w) : I = J := by
  let A1 : IdealLeCertificateO O TT I J v w :=
    { T := A.T
      heq := A.heq
      hieq1 := by
        rw [A.hieq1] ; rfl
      hieq2 := A.hieq2
      g := A.g
      hle2 := A.hle1 }
  let A2 : IdealLeCertificateO O TT J I w v :=
    { T := A.T
      heq := A.heq
      hieq1 := by
        rw [A.hieq2] ; rfl
      hieq2 := A.hieq1
      g := A.h
      hle2 := A.hle2 }
  refine le_antisymm ?_ ?_
  · exact ideal_le_of_IdealLeCertificateO _ TT I J v w A1
  · exact ideal_le_of_IdealLeCertificateO _ TT J I w v A2

/-- Certificate for membership `a ∈ I` from `R`-generators. -/
structure IdealMemCertificate [Algebra R O] {r m : ℕ} (B  : Basis (Fin r) R O)
    (I : Ideal O) (v : Fin m → Fin r → R)  (a : Fin r → R) where
  hieq : I.carrier = Submodule.span R (Set.range (fun i => B.equivFun.symm (v i)))
  g : Fin m → R
  hmem : List.ofFn a = List.sum (List.ofFn (fun k => List.mulPointwise (g k) (List.ofFn (v k))))

/-- Proofs correctness of `IdealMemCertificate`. -/
lemma mem_of_certificate [Algebra R O] {r m : ℕ} (B  : Basis (Fin r) R O)
    (I : Ideal O) (v : Fin m → Fin r → R)  (a : Fin r → R) (A : IdealMemCertificate B I v a) :
    B.equivFun.symm a ∈ I := by
  show B.equivFun.symm a ∈ I.carrier
  erw [A.hieq, Submodule.mem_span_range_iff_exists_fun]
  use A.g
  symm
  refine table_sum_smul B v a (A.g) (A.hmem)

-- MOVE
/-- If some collection of vectors of the same size as the rank spans the whole
space, then they are linearly independent. This is a version of
linearIndependent_of_top_le_span_of_card_eq_finrank which works over domains.

TO DO: Mathlib now contains a verison for rings that satisfy OrzechProperty.   -/
lemma linear_independent_of_top_le_span_of_card_eq_rank
  {τ : Type*} {M : Type*} [Fintype τ] [IsDomain R]
  [AddCommGroup M] [Module R M] (B : Basis τ R M) {b : τ → M}
  (hmem : ⊤ ≤ Submodule.span R (Set.range b)) : LinearIndependent R b := by
let Q := FractionRing R
let B' := Basis.baseChange Q B
have hle : ⊤ ≤ Submodule.span Q (Set.range (fun i => ( 1 ⊗ₜ (b i) : TensorProduct R Q M))) := by
  let P : TensorProduct R Q M → Prop := fun x => x ∈ Submodule.span Q
    (Set.range (fun i => ( 1 ⊗ₜ (b i) : TensorProduct R Q M)))
  have : ∀ x, P x := by
    intro z
    refine TensorProduct.induction_on z ?_ ?_ ?_
    · simp only [Submodule.zero_mem, P]
    · intro x y
      have aux : y ∈ Submodule.span R (Set.range b) := hmem trivial
      rw [Submodule.mem_span_range_iff_exists_fun] at aux
      obtain ⟨c, hc⟩ := aux
      simp only [Submodule.mem_span_range_iff_exists_fun, ← hc, TensorProduct.tmul_sum,
        TensorProduct.tmul_smul, P]
      use (fun i => (c i) • x)
      congr ; ext i
      rw [smul_assoc, TensorProduct.smul_tmul', smul_eq_mul, mul_one]
    · intro x y hx hy
      exact Submodule.add_mem _ hx hy
  intro x _
  exact this x
have := linearIndependent_of_top_le_span_of_card_eq_finrank hle (Eq.symm
  (Module.finrank_eq_card_basis B'))
rw [linearIndependent_iff'] at this ⊢
intro s g hg i his
rw [← FaithfulSMul.algebraMap_eq_zero_iff R Q]
specialize this s (fun i => (algebraMap R Q) (g i))
refine this ?_ i his
simp_rw [TensorProduct.smul_tmul', smul_eq_mul, mul_one, Algebra.algebraMap_eq_smul_one,
TensorProduct.smul_tmul, ← TensorProduct.tmul_sum _ _ (fun x => g x • b x), hg,
TensorProduct.tmul_zero]


/-- If `I` is `R`-generated by the collection `v` with the same number of elements
  as the rank of `O`, then this is a basis for `I`. -/
noncomputable def BasisOfEqSpan {τ : Type*} [Fintype τ] [IsDomain R] [IsPrincipalIdealRing R]
    [IsDomain O] [Algebra R O] (B : Basis τ R O) (I : Ideal O) (hI : I ≠ ⊥) (v : τ → O)
    (heq : I.carrier = Submodule.span R (Set.range v)) : Basis τ R I := by
  have hmem : ∀ i , v i ∈ I := by
    intro i
    show (v i) ∈ I.carrier
    rw [heq]
    refine Submodule.subset_span ⟨i, rfl⟩
  let v' := fun i => (⟨v i, hmem i⟩ : I)
  let f : I →ₗ[R] O :=
    { toFun := Subtype.val
      map_add' := fun x y ↦ rfl
      map_smul' := fun m x ↦ rfl }
  have hle : ⊤ ≤ Submodule.span R (Set.range v') := by
    have hf : Function.Injective f := by simp only [LinearMap.coe_mk, AddHom.coe_mk,
    Subtype.val_injective, f]
    have hvv : v = f ∘ v' := rfl
    intro x ?_
    rw [← Submodule.apply_mem_span_image_iff_mem_span hf, ← Set.range_comp, ← hvv]
    show (f x ∈ ((Submodule.span R (Set.range v) : Set O) ))
    rw [← heq]
    exact x.2
  refine Basis.mk (R := R) (v := v') ?_ ?_
  refine linear_independent_of_top_le_span_of_card_eq_rank (Ideal.selfBasis B I hI) ?_
  exact hle ; exact hle


lemma BasisOfEqSpan_apply  {τ : Type*} [Fintype τ] [IsDomain R] [IsPrincipalIdealRing R]
    [IsDomain O] [Algebra R O] (B : Basis τ R O) (I : Ideal O) (hI : I ≠ ⊥) (v : τ → O)
    (heq : I.carrier = Submodule.span R (Set.range v)) (i : τ) :
    (BasisOfEqSpan B I hI v heq) i = v i := by simp only [BasisOfEqSpan, Basis.coe_mk]

/-- Certifies that `a ∉ I` given `R`-generators. -/
structure IdealNeMemCertificate [Algebra R O] {r : ℕ} (B : Basis (Fin r) R O)
    (I : Ideal O) (v : Fin r → Fin r → R) (a : Fin r → R) where
  hieq : I.carrier = Submodule.span R (Set.range (fun i => B.equivFun.symm (v i)))
  ha : a ≠ 0
  d : R
  g : Fin r → R
  hmem : List.mulPointwise d (List.ofFn a) = List.sum
    (List.ofFn (fun k => List.mulPointwise (g k) (List.ofFn (v k))))
  i : Fin r
  hnedvd : ¬ d ∣ (g i)

/-- Correctness of `IdealNeMemCertificate`. -/
lemma ne_mem_of_certificate [IsDomain R] [IsPrincipalIdealRing R]
    [IsDomain O] [Algebra R O] {r : ℕ}
    (B : Basis (Fin r) R O) (I : Ideal O) (v : Fin r → Fin r → R)
    (a : Fin r → R) (A : IdealNeMemCertificate B I v a) :
    B.equivFun.symm a ∉ I := by
  by_cases hI : I = ⊥
  · rw [hI, Ideal.mem_bot]
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr A.ha
  · have hc := A.hmem
    rw [List.mulPointwise_ofFn] at hc
    let B' := BasisOfEqSpan B I hI (fun i => B.equivFun.symm (v i)) A.hieq
    have heqaux := table_sum_smul B v (A.d • a) (A.g) hc
    by_contra hmema
    have := Basis.dvd_coord_smul B' A.i ⟨B.equivFun.symm a, hmema⟩ A.d
    simp_rw [SetLike.mk_smul_of_tower_mk,
      ← LinearEquiv.map_smul B.equivFun.symm A.d a, heqaux] at this
    apply A.hnedvd
    convert this
    rw [Basis.coord_apply]
    nth_rw 1 [← Basis.repr_sum_self B' A.g]
    congr
    simp only [BasisOfEqSpan, Basis.coe_mk, B']
    rw [← Subtype.val_inj, Submodule.coe_sum]
    rfl

lemma ideal_mul_eq_span {ι τ : Type _} [Fintype ι] [Fintype τ]
    (v : ι → O) (w : τ → O)  :
    (Ideal.span (Set.range v)) * (Ideal.span (Set.range w)) =
    Ideal.span (Set.range (fun (⟨i,j⟩ : ι × τ) => (v i) * (w j) )) := by
    rw [Ideal.span_mul_span]
    congr
    ext x
    simp only [Set.mem_range, Set.iUnion_exists, Set.iUnion_iUnion_eq',
      Set.iUnion_singleton_eq_range, Set.mem_iUnion, Prod.exists]

/-- Given `O`-generators for `I` and `J`, it certifies that `I * J = ⟨w⟩`. -/
structure IdealMulEqCertificate [Algebra R O] {r n m s : ℕ}
  (TT  : TimesTable (Fin r) R O) (I₁ I₂ : Ideal O)
  (u : Fin m → Fin r → R) (v : Fin n → Fin r → R) (w : Fin s → Fin r → R) where
  T : Fin r → Fin r → List R
  heq : ∀ i j , T i j = List.ofFn (TT.table i j)
  hI1 : I₁ = Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (u i)))
  hI2 : I₂ = Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (v i)))
  M : Fin m → Fin n → Fin r → R -- products (u i) * (v j)
  hmul : ∀ i j, table_mul_list T (List.ofFn (u i)) (List.ofFn (v j)) = List.ofFn (M i j)
  f : Fin s → Fin m → Fin n → Fin r → R
  g : Fin m → Fin n → Fin s → Fin r → R
  hle1 : ∀ k , List.ofFn (w k) = List.sum (List.ofFn (fun i => List.sum
    (List.ofFn (fun j => table_mul_list T (List.ofFn (f k i j)) (List.ofFn (M i j) ) ))))
  hle2 : ∀ i j, List.ofFn (M i j) = List.sum (List.ofFn
    (fun k => table_mul_list T (List.ofFn (g i j k)) (List.ofFn (w k))))

/-- Correctness of `IdealMulEqCertificate`.  -/
lemma ideal_eq_mul_of_IdealMulEqCertificate [Algebra R O] {r n m s : ℕ} [NeZero r]
    (TT  : TimesTable (Fin r) R O) (I₁ I₂ : Ideal O)
    (u : Fin m → Fin r → R) (v : Fin n → Fin r → R) (w : Fin s → Fin r → R)
    (A : IdealMulEqCertificate TT I₁ I₂ u v w) :
    I₁ * I₂ = Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (w i))) := by
  have aux := A.hmul
  simp_rw [table_mul_eq_table_mul' TT.table A.T A.heq] at aux
  have hmulaux :=
    fun i j => table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis (aux i j).symm
  simp_rw [A.hI1, A.hI2, ideal_mul_eq_span, hmulaux]
  unfold Ideal.span
  rw [← SetLike.coe_set_eq]
  refine subset_antisymm ?_ ?_
  · erw [submodule_span_le_span_iff _ _
      ((Submodule.span O (Set.range fun i ↦ TT.basis.equivFun.symm (w i))).carrier) ]
    · rintro ⟨i,j⟩
      use (fun k => TT.basis.equivFun.symm (A.g i j k))
      dsimp
      refine table_sum_mul TT.table TT.basis TT.basis_mul_basis _ _ _ ?_
      simp_rw [← table_mul_eq_table_mul' TT.table A.T A.heq]
      exact (A.hle2 i j)
    · rfl
    · intro s x hx
      exact (Submodule.span O (Set.range fun i ↦ TT.basis.equivFun.symm (w i))).smul_mem' s hx
  · erw [submodule_span_le_span_iff (S := O) _ _
      ((Submodule.span O (Set.range fun (x : Fin m × Fin n)
         ↦ TT.basis.equivFun.symm (A.M x.1 x.2))).carrier) ]
    · intro k
      use (fun ⟨i,j⟩ => TT.basis.equivFun.symm (A.f k i j) )
      dsimp
      rw [Fintype.sum_prod_type]
      have aux := A.hle1 k
      let d : Fin m → Fin n → Fin r → R := fun i j => FnOfList r
        (table_mul_list' TT.table (List.ofFn (A.f k i j)) (List.ofFn (A.M i j)))
        (table_mul_list_length _ _ _)
      have hd : ∀ i j, List.ofFn (d i j) =
        table_mul_list' TT.table (List.ofFn (A.f k i j)) (List.ofFn (A.M i j)) :=
        fun i j ↦ listOfFn_of_FnOfList r _ (table_mul_list_length TT.table
          (List.ofFn (A.f k i j)) (List.ofFn (A.M i j)))
      have hmulaux2 := fun i j =>
        table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis (hd i j)
      simp_rw [table_mul_eq_table_mul' TT.table A.T A.heq, ← hd] at aux
      simp_rw [hmulaux2]
      exact table_sum_sum TT.basis _ _ aux
    · rfl
    · intro s x hx
      exact Submodule.smul_mem' _ s hx

/-- Given `O`-generators for `I` and `a ∈ O`, certifies generators for `⟨a⟩ * I`. -/
structure IdealMulPrincipalCertificate [Algebra R O] {r m : ℕ} [NeZero r]
  (TT  : TimesTable (Fin r) R O) (I : Ideal O)
  (α : Fin r → R) (u : Fin m → Fin r → R) (w : Fin m → Fin r → R) where
  T : Fin r → Fin r → List R
  heq : ∀ i j , T i j = List.ofFn (TT.table i j)
  hI : I = Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (u i)))
  hmul : ∀ i, table_mul_list T (List.ofFn α) (List.ofFn (u i)) = List.ofFn (w i)

/-- Correctness of  `IdealMulPrincipalCertificate`. -/
lemma  ideal_eq_principal_mul_of_IdealMulPrincipalCertificate [Algebra R O] {r m : ℕ} [NeZero r]
    (TT  : TimesTable (Fin r) R O) (I : Ideal O)
    (α : Fin r → R) (u : Fin m → Fin r → R) (w : Fin m → Fin r → R)
    (A : IdealMulPrincipalCertificate TT I α u w) :
      Ideal.span {(TT.basis).equivFun.symm α} * I =
        Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (w i))) := by
  have aux := A.hmul
  simp_rw [table_mul_eq_table_mul' TT.table A.T A.heq] at aux
  rw [A.hI, Ideal.span_mul_span]
  congr
  simp only [Set.mem_singleton_iff, Set.mem_range, Set.iUnion_exists,
    Set.iUnion_iUnion_eq', Set.iUnion_singleton_eq_range, Set.iUnion_iUnion_eq_left]
  have : (fun i ↦ TT.basis.equivFun.symm (w i)) =
    fun x ↦ TT.basis.equivFun.symm α * TT.basis.equivFun.symm (u x) := by
    ext i
    exact (table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis (aux i).symm).symm
  rw [this]

/-- `IsInClass x I` expresses that `I` is in the same ideal class as `∏ i, x i`. -/
def IsInClass (R : Type*) {n : ℕ} [CommRing R] (x : Fin n → Ideal R) :
    Ideal R → (Fin n → ℕ) → Prop := by
  intro I m
  exact ∃ (α : R) (β : R) , ∃ (_ : α ≠ 0) (_ : β ≠ 0),
    Ideal.span {α} * I = Ideal.span {β} * ∏ j, x j ^ (m j)

-- Prove element is nonzero from proof coordinates are not zero:
-- (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr hv

lemma ideal_mem_principal_class [Algebra R O] {r : ℕ} [NeZero r] (B : Basis (Fin r) R O)
    (I : Ideal O) (v : Fin r → R) (hv : v ≠ 0)
    (hI : I = Ideal.span (Set.range (fun _ : Fin 1 => B.equivFun.symm v))) :
    ∃ (α β : O), ∃ (_ : α ≠ 0), ∃ (_ : β ≠ 0),
      Ideal.span {α} * I = Ideal.span {β} := by
  use 1 , B.equivFun.symm v
  have haux : B.equivFun.symm v ≠ 0 := (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr hv
  have : Nontrivial O := nontrivial_of_ne (B.equivFun.symm v) 0 haux
  use (zero_ne_one' O).symm , haux
  simp only [Ideal.span_singleton_one, Ideal.top_mul]
  convert hI
  simp only [Basis.equivFun_symm_apply, Set.range_const]

lemma ideal_mem_principal_class'
    [Algebra R O] {r : ℕ} [NeZero r] (B : Basis (Fin r) R O)
    (I : Ideal O) {J : Ideal O} (v : Fin r → R) (hv : v ≠ 0)
    (hI : I = Ideal.span (Set.range (fun i : Fin 1 => B.equivFun.symm (![v] i) ))) :
    ∃ (α β : O), ∃ (_ : α ≠ 0), ∃ (_ : β ≠ 0),
      Ideal.span {α} * I = Ideal.span {β} * J ^ 0 := by
  convert ideal_mem_principal_class (r := r) B I v hv ?_
  · simp only [pow_zero, Ideal.one_eq_top, Ideal.mul_top]
  · rw [hI]
    refine congrArg _ ?_
    simp only [Matrix.cons_val_fin_one, Basis.equivFun_symm_apply, Set.range_const]

lemma ideal_mem_principal_class'' {O R: Type*} [CommRing O] [CommRing R]
  [Algebra R O] {r : ℕ} [NeZero r] (B : Basis (Fin r) R O)
  (I : Ideal O) (v : Fin r → R) (hv : v ≠ 0)
  (hI : I = Ideal.span (Set.range (fun i : Fin 1 => B.equivFun.symm (![v] i) ))) :
  ∃ (α β : O), ∃ (_ : α ≠ 0), ∃ (_ : β ≠ 0),
    Ideal.span {α} * I = Ideal.span {β} := by
  refine ideal_mem_principal_class (r := r) B I v hv ?_
  · rw [hI]
    refine congrArg _ ?_
    simp only [Matrix.cons_val_fin_one, Basis.equivFun_symm_apply, Set.range_const]

/-- Given `O`-generators for `I` and `r ∈ R`, certifies generators for `⟨r⟩ · I`. -/
lemma ideal_mul_span_singleton_coe [Algebra R O] {r m : ℕ} [NeZero r] (B : Basis (Fin r) R O)
  (I : Ideal O) (v : Fin m → Fin r → R)
  (hI : I = Ideal.span (Set.range (fun i => B.equivFun.symm (v i)))) (r : R) :
  Ideal.span {(algebraMap R O r)} * I =
    Ideal.span (Set.range (fun i => B.equivFun.symm ((r • v) i))) := by
rw [hI, Ideal.span_mul_span] ; congr
simp only [Set.mem_singleton_iff, Basis.equivFun_symm_apply, Set.mem_range, Set.iUnion_exists,
  Set.iUnion_iUnion_eq', Set.iUnion_singleton_eq_range, Set.iUnion_iUnion_eq_left, Pi.smul_apply,
  map_smul]
refine congrArg (f := Set.range) ?_
simp only [Basis.equivFun_symm_apply, Algebra.smul_def, Pi.smul_apply, Pi.mul_apply,
  Pi.algebraMap_apply, Algebra.id.map_eq_id, RingHom.id_apply, map_mul]

end I
