import IdealArithmetic.IdealArithmetic
import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem


open BigOperators Classical Matrix Polynomial
--------------------------------------------
-- EXAMPLE
--------------------------------------------

/- Number field `K(α)` with with α root of polynomial `X^5 - 3*X^3 + 9*X - 8`.
Class number `3`, generated by class of ideal `J = (2, α)`. We have `J ^ 3 = (α)`. -/

/- Ring of integers with basis `1, 1/2*α^4 + 1/2*α, 1/2*α^4 + 1/2*α^3 + 1/2*α^2, α^3, α^4` -/

/- Minkowski's bound is around 25 -/


def K : Type := sorry

instance : CommRing K := sorry

def O : Subalgebra ℤ K := sorry

instance : IsDomain O := sorry

noncomputable def TT : TimesTable (Fin 5) ℤ O :=
  { basis := sorry,
    table := ![ ![![1, 0, 0, 0, 0],![0, 1, 0, 0, 0],![0, 0, 1, 0, 0],![0, 0, 0, 1, 0],![0, 0, 0, 0, 1]],
                ![![0, 1, 0, 0, 0],![4, 3, -13, 10, 5],![8, -2, -14, 10, 9],![12, -27, 8, -4, 10],![4, 15, -27, 19, 6]],
                ![![0, 0, 1, 0, 0],![8, -2, -14, 10, 9],![16, -12, -19, 13, 18],![16, -28, -1, 2, 16],![12, 5, -28, 18, 13]],
                ![![0, 0, 0, 1, 0],![12, -27, 8, -4, 10],![16, -28, -1, 2, 16],![0, 16, -18, 9, 4],![24, -54, 16, -8, 19]],
                ![![0, 0, 0, 0, 1],![4, 15, -27, 19, 6],![12, 5, -28, 18, 13],![24, -54, 16, -8, 19],![0, 48, -54, 35, 3]]]
    basis_mul_basis := sorry }

noncomputable def B := TT.basis

lemma B_one : TT.basis 0 = 1 := sorry

lemma B_one_repr : TT.basis.equivFun.symm ![1, 0, 0, 0, 0] = 1 := sorry

def T : Fin 5 → Fin 5 → List ℤ :=
  ![ ![[1, 0, 0, 0, 0],[0, 1, 0, 0, 0],[0, 0, 1, 0, 0],[0, 0, 0, 1, 0],[0, 0, 0, 0, 1]],
  ![[0, 1, 0, 0, 0],[4, 3, -13, 10, 5],[8, -2, -14, 10, 9],[12, -27, 8, -4, 10],[4, 15, -27, 19, 6]],
  ![[0, 0, 1, 0, 0],[8, -2, -14, 10, 9],[16, -12, -19, 13, 18],[16, -28, -1, 2, 16],[12, 5, -28, 18, 13]],
  ![[0, 0, 0, 1, 0],[12, -27, 8, -4, 10],[16, -28, -1, 2, 16],[0, 16, -18, 9, 4],[24, -54, 16, -8, 19]],
  ![[0, 0, 0, 0, 1],[4, 15, -27, 19, 6],[12, 5, -28, 18, 13],[24, -54, 16, -8, 19],[0, 48, -54, 35, 3]]]

lemma T_eq_TT : ∀ (i j : Fin 5), T i j = List.ofFn (TT.table i j) := by
  simp ; decide

/-- We compute Log α in 𝔽₃ for prime ideals (19, α + 8), (43, α + 11), (67, α + 21) -/

def R₁ : IsOrderOf (2 : ZMod 19) 18 where
  m := 2
  P := ![2, 3]
  e := ![1, 2]
  hP := by decide
  hm := by rfl
  hid := by decide
  hnid := by decide

def R₂ : IsOrderOf (3 : ZMod 43) 42 where
  m := 3
  P := ![2, 3, 7]
  e := ![1, 1, 1]
  hP := by decide
  hm := by rfl
  hid := by decide
  hnid := by decide

def R₃ : IsOrderOf (2 : ZMod 67) 66 where
  m := 3
  P := ![2, 3, 11]
  e := ![1, 1, 1]
  hP := by decide
  hm := by rfl
  hid := by decide
  hnid := by decide

instance hp67 : Fact $ Nat.Prime 67 := by decide
instance hp19 : Fact $ Nat.Prime 19 := by decide
instance hp43 : Fact $ Nat.Prime 43 := by decide

noncomputable section

noncomputable def α := TT.basis.equivFun.symm ![0, 2, 0, 0, -1]

----------------
def I₁ : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![67, 0, 0, 0, 0], ![21, 2, 0, 0, -1]] i)))

def A₁ : IdealEqSpanCertificate O ℤ TT I₁
  ![![67, 0, 0, 0, 0], ![21, 2, 0, 0, -1]]
  ![![67, 0, 0, 0, 0], ![54, 1, 0, 0, 0], ![65, 0, 1, 0, 0], ![15, 0, 0, 1, 0], ![20, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M := ![ ![ ![67,0,0,0,0], ![0,67,0,0,0], ![0,0,67,0,0], ![0,0,0,67,0], ![0,0,0,0,67]],
  ![![21,2,0,0,-1], ![4,12,1,1,4], ![4,-9,21,2,5], ![0,0,0,21,1], ![8,-18,0,3,30]]]
  hmulB := by simp[table_mul_list] ; decide
  f := ![![![4213988785, 364804816, -3155968, -3140960, -213844560], ![-13484764112, 210661936, 37520, -13936, 0]],
  ![![3488485190, 301998003, -2612619, -2600135, -177027896], ![-11163152608, 174393213, 31060, -11728, 0]],
  ![![4085950875, 353720580, -3060077, -3045292, -207347092], ![-13075042800, 204261180, 36380, -14256, 0]],
  ![![943430325, 81672720, -706560, -703205, -47875648], ![-3018977040, 47163120, 8400, -3104, 0]],
  ![![1257907100, 108896960, -942080, -937600, -63834197], ![-4025302720, 62884160, 11200, -4160, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-54, 67, 0, 0, 0], ![-65, 0, 67, 0, 0], ![-15, 0, 0, 67, 0], ![-20, 0, 0, 0, 67]],
  ![![-1, 2, 0, 0, -1], ![-12, 12, 1, 1, 4], ![-15, -9, 21, 2, 5], ![-5, 0, 0, 21, 1], ![5, -18, 0, 3, 30]]]
  hle1 := by simp ; decide
  hle2 := by simp ; decide


lemma I1_card : Nat.card (O ⧸ I₁) = 67  := by
  refine ideal_norm_eq_prod O B I₁ ?_ _ ?_ (ideal_eq_of_IdealEqSpanCertificate O ℤ A₁)
  · exact fun hc => by
      erw [Ideal.span_eq_bot] at hc  ; simp_rw [Set.mem_range] at hc
      specialize hc (TT.basis.equivFun.symm ![67, 0, 0, 0, 0])
      have := hc ⟨0, rfl⟩
      apply_fun TT.basis.coord 0 at this
      rw [Basis.coord_equivFun_symm] at this
      simp at this
  · decide

def memAux₁ : IdealMemCertificate O ℤ B I₁
  ![![67, 0, 0, 0, 0], ![54, 1, 0, 0, 0], ![65, 0, 1, 0, 0], ![15, 0, 0, 1, 0], ![20, 0, 0, 0, 1]] ![21, 2, 0, 0, -1] where
  hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A₁
  g := ![-1, 2, 0, 0, -1]
  hmem := by decide

lemma alpha_sub_mem₁ : α - (-21) ∈ I₁ := by
  have : 21 = (21 : ℤ) • TT.basis.equivFun.symm ![1, 0, 0, 0, 0] := by
    rw [B_one_repr]
    simp only [zsmul_eq_mul, Int.cast_ofNat, mul_one]
  rw [sub_neg_eq_add, this, table_mulPointwise_eq_smul TT.basis ![1, 0, 0, 0, 0] ![21, 0, 0, 0, 0] (21) rfl]
  unfold α
  rw [table_add_list_eq_add _ _ _ ![21, 2, 0, 0, -1] rfl]
  refine mem_of_certificate O ℤ TT.basis I₁ _ ![21, 2, 0, 0, -1] memAux₁

noncomputable def φ₁ := modIdealToZMod hp67.out I₁ I1_card

def PrimRoot₁ := is_primitive_root_finite_field (n := 66) (rfl) (2 : ZMod 67) R₃

lemma phi_apply₁ : φ₁ α = - 21 := by
  have := Ideal.Quotient.eq.2 alpha_sub_mem₁
  have heq : (Ideal.Quotient.mk I₁) (- 21) = ↑(- 21 : ℤ) := by
    simp only [map_neg, Int.reduceNeg, Int.cast_neg, Int.cast_ofNat, neg_inj]
    rfl
  rw [this, heq, map_intCast]
  rfl

lemma log_of_alpha₁ : LogFiniteRing PrimRoot₁ 3 (φ₁ α) = 2 := by
  rw [phi_apply₁]
  convert LogFiniteRing_of_pow (R := ZMod 67) (ζ := 2) (p := 3) PrimRoot₁ ?_ 29
  rw [Fintype.card_units]
  decide

----------
def I₂ : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![19, 0, 0, 0, 0], ![8, 2, 0, 0, -1]] i)))

def A₂ : IdealEqSpanCertificate O ℤ TT I₂
  ![![19, 0, 0, 0, 0], ![8, 2, 0, 0, -1]]
  ![![19, 0, 0, 0, 0], ![8, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![18, 0, 0, 1, 0], ![8, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M := ![![![19, 0, 0, 0, 0], ![0, 19, 0, 0, 0], ![0, 0, 19, 0, 0], ![0, 0, 0, 19, 0], ![0, 0, 0, 0, 19]],
  ![![8, 2, 0, 0, -1], ![4, -1, 1, 1, 4], ![4, -9, 8, 2, 5], ![0, 0, 0, 8, 1], ![8, -18, 0, 3, 17]]]
  hmulB := by simp[table_mul_list] ; decide
  f := ![![![7151125, 1825995, -19323, -18411, -978588], ![-17162700, 356193, 1368, -1140, 0]],
    ![![3294140, 841138, -8901, -8409, -450774], ![-7905936, 164079, 630, -696, 0]],
    ![![-31440, -8028, 85, 174, 4314], ![75456, -1566, -6, -216, 0]],
    ![![6774750, 1729890, -18306, -17447, -927084], ![-16259400, 337446, 1296, -1068, 0]],
    ![![3011000, 768840, -8136, -7752, -412037], ![-7226400, 149976, 576, -480, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-8, 19, 0, 0, 0], ![0, 0, 19, 0, 0], ![-18, 0, 0, 19, 0], ![-8, 0, 0, 0, 19]],
  ![![0, 2, 0, 0, -1], ![-2, -1, 1, 1, 4], ![0, -9, 8, 2, 5], ![-8, 0, 0, 8, 1], ![-2, -18, 0, 3, 17]]]
  hle1 := by simp ; decide
  hle2 := by simp ; decide

lemma I2_card : Nat.card (O ⧸ I₂) = 19 := by
  refine ideal_norm_eq_prod O B I₂ ?_ _ ?_ (ideal_eq_of_IdealEqSpanCertificate O ℤ A₂)
  · exact fun hc => by
      erw [Ideal.span_eq_bot] at hc  ; simp_rw [Set.mem_range] at hc
      specialize hc (TT.basis.equivFun.symm ![19, 0, 0, 0, 0])
      have := hc ⟨0, rfl⟩
      apply_fun TT.basis.coord 0 at this
      rw [Basis.coord_equivFun_symm] at this
      simp at this
  · decide

def memAux₂ : IdealMemCertificate O ℤ B I₂
  ![![19, 0, 0, 0, 0], ![8, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![18, 0, 0, 1, 0], ![8, 0, 0, 0, 1]] ![8, 2, 0, 0, -1] where
    hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A₂
    g := ![0, 2, 0, 0, -1]
    hmem := by decide

lemma alpha_sub_mem₂ : α - (-8) ∈ I₂ := by
  have : 8 = (8 : ℤ) • TT.basis.equivFun.symm ![1, 0, 0, 0, 0] := by
    rw [B_one_repr]
    simp only [zsmul_eq_mul, Int.cast_ofNat, mul_one]
  rw [sub_neg_eq_add, this, table_mulPointwise_eq_smul TT.basis ![1, 0, 0, 0, 0] ![8, 0, 0, 0, 0] (8) rfl]
  unfold α
  rw [table_add_list_eq_add _ _ _ ![8, 2, 0, 0, -1] rfl]
  refine mem_of_certificate O ℤ TT.basis I₂ _ ![8, 2, 0, 0, -1] memAux₂

noncomputable def φ₂ := modIdealToZMod hp19.out I₂ I2_card

def PrimRoot₂ := is_primitive_root_finite_field (n := 18) (rfl) (2 : ZMod 19) R₁

lemma phi_apply₂ : φ₂ α = - 8 := by
  have := Ideal.Quotient.eq.2 alpha_sub_mem₂
  have heq : (Ideal.Quotient.mk I₂) (- 8) = ↑(- 8 : ℤ) := by
    simp only [map_neg, Int.reduceNeg, Int.cast_neg, Int.cast_ofNat, neg_inj]
    rfl
  rw [this, heq, map_intCast]
  rfl

lemma log_of_alpha₂ : LogFiniteRing PrimRoot₂ 3 (φ₂ α) = 0 := by
  rw [phi_apply₂]
  convert LogFiniteRing_of_pow (R := ZMod 19) (ζ := 2) (p := 3) PrimRoot₂ ?_ 12
  rw [Fintype.card_units]
  decide

------------------
def I₃ : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![43, 0, 0, 0, 0], ![11, 2, 0, 0, -1]] i)))

def A₃ : IdealEqSpanCertificate O ℤ TT I₃
  ![![43, 0, 0, 0, 0], ![11, 2, 0, 0, -1]]
  ![![43, 0, 0, 0, 0], ![38, 1, 0, 0, 0], ![14, 0, 1, 0, 0], ![41, 0, 0, 1, 0], ![22, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M := ![![![43, 0, 0, 0, 0],![0, 43, 0, 0, 0],![0, 0, 43, 0, 0],![0, 0, 0, 43, 0],![0, 0, 0, 0, 43]],
    ![![11, 2, 0, 0, -1],![4, 2, 1, 1, 4],![4, -9, 11, 2, 5],![0, 0, 0, 11, 1],![8, -18, 0, 3, 20]]]
  hmulB := by simp[table_mul_list] ; decide
  f := ![![![-33440971, -5831144, 192984, 195908, 3888488], ![133763884, -8366424, 6192, -6364, 0]],
    ![![-30850538, -5379447, 178035, 180703, 3587272], ![123402152, -7718337, 5712, -5756, 0]],
    ![![-10757966, -1875880, 62083, 63032, 1250928], ![43031864, -2691480, 1992, -2080, 0]],
    ![![-31885577, -5559928, 184008, 186795, 3707628], ![127542308, -7977288, 5904, -6064, 0]],
    ![![-17109334, -2983376, 98736, 100232, 1989459], ![68437336, -4280496, 3168, -3256, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-38, 43, 0, 0, 0], ![-14, 0, 43, 0, 0], ![-41, 0, 0, 43, 0], ![-22, 0, 0, 0, 43]],
    ![![-1, 2, 0, 0, -1], ![-5, 2, 1, 1, 4], ![0, -9, 11, 2, 5], ![-11, 0, 0, 11, 1], ![3, -18, 0, 3, 20]]]
  hle1 := by simp ; decide
  hle2 := by simp ; decide


lemma I3_card : Nat.card (O ⧸ I₃) = 43 := by
  refine ideal_norm_eq_prod O B I₃ ?_ _ ?_ (ideal_eq_of_IdealEqSpanCertificate O ℤ A₃)
  · exact fun hc => by
      erw [Ideal.span_eq_bot] at hc  ; simp_rw [Set.mem_range] at hc
      specialize hc (TT.basis.equivFun.symm ![43, 0, 0, 0, 0])
      have := hc ⟨0, rfl⟩
      apply_fun TT.basis.coord 0 at this
      rw [Basis.coord_equivFun_symm] at this
      simp at this
  · decide

def memAux₃ : IdealMemCertificate O ℤ B I₃
  ![![43, 0, 0, 0, 0], ![38, 1, 0, 0, 0], ![14, 0, 1, 0, 0], ![41, 0, 0, 1, 0], ![22, 0, 0, 0, 1]] ![11, 2, 0, 0, -1] where
    hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A₃
    g := ![-1, 2, 0, 0, -1]
    hmem := by decide

lemma alpha_sub_mem₃ : α - (-11) ∈ I₃ := by
  have : 11 = (11 : ℤ) • TT.basis.equivFun.symm ![1, 0, 0, 0, 0] := by
    rw [B_one_repr]
    simp only [zsmul_eq_mul, Int.cast_ofNat, mul_one]
  rw [sub_neg_eq_add, this, table_mulPointwise_eq_smul TT.basis ![1, 0, 0, 0, 0] ![11, 0, 0, 0, 0] (11) rfl]
  unfold α
  rw [table_add_list_eq_add _ _ _ ![11, 2, 0, 0, -1] rfl]
  refine mem_of_certificate O ℤ TT.basis I₃ _ ![11, 2, 0, 0, -1] memAux₃

noncomputable def φ₃ := modIdealToZMod hp43.out I₃ I3_card

def PrimRoot₃ := is_primitive_root_finite_field (n := 42) (rfl) (3 : ZMod 43) R₂

lemma phi_apply₃ : φ₃ α = - 11 := by
  have := Ideal.Quotient.eq.2 alpha_sub_mem₃
  have heq : (Ideal.Quotient.mk I₃) (- 11) = ↑(- 11 : ℤ) := by
    simp only [map_neg, Int.reduceNeg, Int.cast_neg, Int.cast_ofNat, neg_inj]
    rfl
  rw [this, heq, map_intCast]
  rfl

lemma log_of_alpha₃ : LogFiniteRing PrimRoot₃ 3 (φ₃ α) = 0 := by
  rw [phi_apply₃]
  convert LogFiniteRing_of_pow (R := ZMod 43) (ζ := 3) (p := 3) PrimRoot₃ ?_ 9
  rw [Fintype.card_units]
  decide

------------

/- Generators for the free part of torsion are -/

noncomputable def ζ₁ := TT.basis.equivFun.symm ![3, -2, -1, 1, 2]
noncomputable def ζ₁_inv := TT.basis.equivFun.symm ![3, -4, -3, 2, 4]

lemma zeta_one_mul_inv : ζ₁ * ζ₁_inv = 1 := by
  rw [← B_one_repr]
  refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
  rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
  decide

noncomputable def ζ₂ := TT.basis.equivFun.symm ![1, -2, 0, 0, 1]
noncomputable def ζ₂_inv := TT.basis.equivFun.symm ![-7, 4, 4, -3, -5]

lemma zeta_two_mul_inv : ζ₂ * ζ₂_inv = 1 := by
  rw [← B_one_repr]
  refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
  rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
  decide


------------------------
def memAux_zeta11 : IdealMemCertificate O ℤ B I₁
  ![![67, 0, 0, 0, 0], ![54, 1, 0, 0, 0], ![65, 0, 1, 0, 0], ![15, 0, 0, 1, 0], ![20, 0, 0, 0, 1]] ![-51, -2, -1, 1, 2] where
  hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A₁
  g := ![1, -2, -1, 1, 2]
  hmem := by decide

lemma zeta1_sub_mem₁ : ζ₁ - (54) ∈ I₁ := by
  have : -54 = (-54 : ℤ) • TT.basis.equivFun.symm ![1, 0, 0, 0, 0] := by
    rw [B_one_repr]
    simp only [Int.reduceNeg, neg_smul, zsmul_eq_mul, Int.cast_ofNat, mul_one]
  rw [sub_eq_add_neg, this, table_mulPointwise_eq_smul TT.basis ![1, 0, 0, 0, 0] ![-54, 0, 0, 0, 0] (-54) rfl]
  unfold ζ₁
  rw [table_add_list_eq_add _ _ _ ![-51, -2, -1, 1, 2] rfl]
  refine mem_of_certificate O ℤ TT.basis I₁ _ _ memAux_zeta11

lemma phi_apply_zeta11 : φ₁ ζ₁ = 54 := by
  have := Ideal.Quotient.eq.2 zeta1_sub_mem₁
  have heq : (Ideal.Quotient.mk I₁) (54) = ↑(54 : ℤ) := by
    simp only [map_neg, Int.reduceNeg, Int.cast_neg, Int.cast_ofNat, neg_inj]
    rfl
  rw [this, heq, map_intCast]
  rfl

lemma log_of_zeta11 : LogFiniteRing PrimRoot₁ 3 (φ₁ ζ₁) = 1 := by
  rw [phi_apply_zeta11]
  convert LogFiniteRing_of_pow (R := ZMod 67) (ζ := 2) (p := 3) PrimRoot₁ ?_ 52
  rw [Fintype.card_units]
  decide
------------------------------

def memAux_zeta21 : IdealMemCertificate O ℤ B I₁
  ![![67, 0, 0, 0, 0], ![54, 1, 0, 0, 0], ![65, 0, 1, 0, 0], ![15, 0, 0, 1, 0], ![20, 0, 0, 0, 1]] ![-21, -2, 0, 0, 1] where
  hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A₁
  g := ![1, -2, 0, 0, 1]
  hmem := by decide

lemma zeta2_sub_mem₁ : ζ₂ - (22) ∈ I₁ := by
  have : -22 = (-22 : ℤ) • TT.basis.equivFun.symm ![1, 0, 0, 0, 0] := by
    rw [B_one_repr]
    simp only [Int.reduceNeg, neg_smul, zsmul_eq_mul, Int.cast_ofNat, mul_one]
  rw [sub_eq_add_neg, this, table_mulPointwise_eq_smul TT.basis ![1, 0, 0, 0, 0] ![-22, 0, 0, 0, 0] (-22) rfl]
  unfold ζ₂
  rw [table_add_list_eq_add _ _ _ ![-21, -2, 0, 0, 1] rfl]
  refine mem_of_certificate O ℤ TT.basis I₁ _ _ memAux_zeta21

lemma phi_apply_zeta21 : φ₁ ζ₂ = 22 := by
  have := Ideal.Quotient.eq.2 zeta2_sub_mem₁
  have heq : (Ideal.Quotient.mk I₁) (22) = ↑(22 : ℤ) := by
    simp only [map_neg, Int.reduceNeg, Int.cast_neg, Int.cast_ofNat, neg_inj]
    rfl
  rw [this, heq, map_intCast]
  rfl

lemma log_of_zeta21 : LogFiniteRing PrimRoot₁ 3 (φ₁ ζ₂) = 0 := by
  rw [phi_apply_zeta21]
  convert LogFiniteRing_of_pow (R := ZMod 67) (ζ := 2) (p := 3) PrimRoot₁ ?_ 60
  rw [Fintype.card_units]
  decide

------------------------------

def memAux_zeta12 : IdealMemCertificate O ℤ B I₂
  ![![19, 0, 0, 0, 0], ![8, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![18, 0, 0, 1, 0], ![8, 0, 0, 0, 1]] ![-1, -2, -1, 1, 2] where
    hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A₂
    g := ![-1, -2, -1, 1, 2]
    hmem := by decide

lemma zeta1_sub_mem₂ : ζ₁ - (4) ∈ I₂ := by
  have : -4 = (-4 : ℤ) • TT.basis.equivFun.symm ![1, 0, 0, 0, 0] := by
    rw [B_one_repr]
    simp only [Int.reduceNeg, neg_smul, zsmul_eq_mul, Int.cast_ofNat, mul_one]
  rw [sub_eq_add_neg, this, table_mulPointwise_eq_smul TT.basis ![1, 0, 0, 0, 0] ![-4, 0, 0, 0, 0] (-4) rfl]
  unfold ζ₁
  rw [table_add_list_eq_add _ _ _ ![-1, -2, -1, 1, 2] rfl]
  refine mem_of_certificate O ℤ TT.basis I₂ _ _ memAux_zeta12

lemma phi_apply_zeta12 : φ₂ ζ₁ = 4 := by
  have := Ideal.Quotient.eq.2 zeta1_sub_mem₂
  have heq : (Ideal.Quotient.mk I₂) (4) = ↑(4 : ℤ) := by
    simp only [map_neg, Int.reduceNeg, Int.cast_neg, Int.cast_ofNat, neg_inj]
    rfl
  rw [this, heq, map_intCast]
  rfl

lemma log_of_zeta12 : LogFiniteRing PrimRoot₂ 3 (φ₂ ζ₁) = -1 := by
  rw [phi_apply_zeta12]
  convert LogFiniteRing_of_pow (R := ZMod 19) (ζ := 2) (p := 3) PrimRoot₂ ?_ 2
  rw [Fintype.card_units]
  decide

----

def memAux_zeta22 : IdealMemCertificate O ℤ B I₂
  ![![19, 0, 0, 0, 0], ![8, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![18, 0, 0, 1, 0], ![8, 0, 0, 0, 1]] ![-8, -2, 0, 0, 1] where
    hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A₂
    g := ![0, -2, 0, 0, 1]
    hmem := by decide

lemma zeta2_sub_mem₂ : ζ₂ - (9) ∈ I₂ := by
  have : -9 = (-9 : ℤ) • TT.basis.equivFun.symm ![1, 0, 0, 0, 0] := by
    rw [B_one_repr]
    simp only [Int.reduceNeg, neg_smul, zsmul_eq_mul, Int.cast_ofNat, mul_one]
  rw [sub_eq_add_neg, this, table_mulPointwise_eq_smul TT.basis ![1, 0, 0, 0, 0] ![-9, 0, 0, 0, 0] (-9) rfl]
  unfold ζ₂
  rw [table_add_list_eq_add _ _ _ ![-8, -2, 0, 0, 1] rfl]
  refine mem_of_certificate O ℤ TT.basis I₂ _ _ memAux_zeta22

lemma phi_apply_zeta22 : φ₂ ζ₂ = 9 := by
  have := Ideal.Quotient.eq.2 zeta2_sub_mem₂
  have heq : (Ideal.Quotient.mk I₂) (9) = ↑(9 : ℤ) := by
    simp only [map_neg, Int.reduceNeg, Int.cast_neg, Int.cast_ofNat, neg_inj]
    rfl
  rw [this, heq, map_intCast]
  rfl

lemma log_of_zeta22 : LogFiniteRing PrimRoot₂ 3 (φ₂ ζ₂) = -1 := by
  rw [phi_apply_zeta22]
  convert LogFiniteRing_of_pow (R := ZMod 19) (ζ := 2) (p := 3) PrimRoot₂ ?_ 8
  rw [Fintype.card_units]
  decide

-------------
def memAux_zeta31 : IdealMemCertificate O ℤ B I₃
  ![![43, 0, 0, 0, 0], ![38, 1, 0, 0, 0], ![14, 0, 1, 0, 0], ![41, 0, 0, 1, 0], ![22, 0, 0, 0, 1]] ![-5, -2, -1, 1, 2] where
    hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A₃
    g := ![0, -2, -1, 1, 2]
    hmem := by decide

lemma zeta1_sub_mem₃ : ζ₁ - (8) ∈ I₃ := by
  have : -8 = (-8 : ℤ) • TT.basis.equivFun.symm ![1, 0, 0, 0, 0] := by
    rw [B_one_repr]
    simp only [Int.reduceNeg, neg_smul, zsmul_eq_mul, Int.cast_ofNat, mul_one]
  rw [sub_eq_add_neg, this, table_mulPointwise_eq_smul TT.basis ![1, 0, 0, 0, 0] ![-8, 0, 0, 0, 0] (-8) rfl]
  unfold ζ₁
  rw [table_add_list_eq_add _ _ _ ![-5, -2, -1, 1, 2] rfl]
  refine mem_of_certificate O ℤ TT.basis I₃ _ _ (memAux_zeta31)

lemma phi_apply_zeta31 : φ₃ ζ₁ = 8 := by
  have := Ideal.Quotient.eq.2 zeta1_sub_mem₃
  have heq : (Ideal.Quotient.mk I₃) (8) = ↑(8 : ℤ) := by
    simp only [map_neg, Int.reduceNeg, Int.cast_neg, Int.cast_ofNat, neg_inj]
    rfl
  rw [this, heq, map_intCast]
  rfl

lemma log_of_zeta31 : LogFiniteRing PrimRoot₃ 3 (φ₃ ζ₁) = 0 := by
  rw [phi_apply_zeta31]
  convert LogFiniteRing_of_pow (R := ZMod 43) (ζ := 3) (p := 3) PrimRoot₃ ?_ 39
  rw [Fintype.card_units]
  decide

---------

def memAux_zeta32 : IdealMemCertificate O ℤ B I₃
  ![![43, 0, 0, 0, 0], ![38, 1, 0, 0, 0], ![14, 0, 1, 0, 0], ![41, 0, 0, 1, 0], ![22, 0, 0, 0, 1]] ![-11, -2, 0, 0, 1] where
    hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A₃
    g := ![1, -2, 0, 0, 1]
    hmem := by decide

lemma zeta2_sub_mem₃ : ζ₂ - (12) ∈ I₃ := by
  have : -12 = (-12 : ℤ) • TT.basis.equivFun.symm ![1, 0, 0, 0, 0] := by
    rw [B_one_repr]
    simp only [Int.reduceNeg, neg_smul, zsmul_eq_mul, Int.cast_ofNat, mul_one]
  rw [sub_eq_add_neg, this, table_mulPointwise_eq_smul TT.basis ![1, 0, 0, 0, 0] ![-12, 0, 0, 0, 0] (-12) rfl]
  unfold ζ₂
  rw [table_add_list_eq_add _ _ _ ![-11, -2, 0, 0, 1] rfl]
  refine mem_of_certificate O ℤ TT.basis I₃ _ _ (memAux_zeta32)

lemma phi_apply_zeta32 : φ₃ ζ₂ = 12 := by
  have := Ideal.Quotient.eq.2 zeta2_sub_mem₃
  have heq : (Ideal.Quotient.mk I₃) (12) = ↑(12 : ℤ) := by
    simp only [map_neg, Int.reduceNeg, Int.cast_neg, Int.cast_ofNat, neg_inj]
    rfl
  rw [this, heq, map_intCast]
  rfl

lemma log_of_zeta32 : LogFiniteRing PrimRoot₃ 3 (φ₃ ζ₂) = 1 := by
  rw [phi_apply_zeta32]
  convert LogFiniteRing_of_pow (R := ZMod 43) (ζ := 3) (p := 3) PrimRoot₃ ?_ 13
  rw [Fintype.card_units]
  decide


instance CR1043 : (i : Fin (Nat.succ 0).succ) → CommRing (![ZMod 19, ZMod 43] i) :=
  fun i =>
  match i with
  | 0 => by dsimp ; infer_instance
  | 1 => by dsimp ; infer_instance

instance : (i : Fin (Nat.succ 0).succ) → Fintype (![ZMod 19, ZMod 43] i) :=
  fun i =>
  match i with
  | 0 => by dsimp ; infer_instance
  | 1 => by dsimp ; infer_instance

noncomputable def φ : ∀ (i : Fin 2) , O →+* ![ZMod 19, ZMod 43] i :=
  fun i =>
  match i with
  | 0 => (φ₂.comp (Ideal.Quotient.mk I₂))
  | 1 => (φ₃.comp (Ideal.Quotient.mk I₃))

noncomputable def ζ : ∀ (i : Fin 2) , ![ZMod 19, ZMod 43] i :=
  fun i =>
  match i with
  | 0 => 2
  | 1 => 3

noncomputable def hr : ∀ (i : Fin 2) , IsPrimitiveRoot (ζ i) (Fintype.card (![ZMod 19, ZMod 43] i)ˣ) :=
  fun i =>
  match i with
  | 0 => PrimRoot₂
  | 1 => PrimRoot₃

lemma units_isUnit (i : Fin 2) : IsUnit (![ζ₁, ζ₂] i) := by
  fin_cases i
  · exact isUnit_of_mul_eq_one _ _ zeta_one_mul_inv
  · exact isUnit_of_mul_eq_one _ _ zeta_two_mul_inv


lemma matrix_log_units : MatrixLogProd 3 ![ZMod 19, ZMod 43] φ ![ζ₁, ζ₂] ζ hr = ![![-1, -1], ![0, 1]] := by
  ext i j
  rw [MatrixLogProd_def]
  fin_cases i
  · fin_cases j
    · exact log_of_zeta12
    · exact log_of_zeta22
  · fin_cases j
    · exact log_of_zeta31
    · exact log_of_zeta32


lemma matrix_log_units_rank : Matrix.rank (MatrixLogProd 3 ![ZMod 19, ZMod 43] φ ![ζ₁, ζ₂] ζ hr) = Fintype.card (Fin 2) := by
  simp only [Fintype.card_fin]
  refine le_antisymm ?_ ?_
  · exact rank_le_width (MatrixLogProd 3 ![ZMod 19, ZMod 43] φ ![ζ₁, ζ₂] ζ hr)
  · have : Matrix.rank ((MatrixLogProd 3 ![ZMod 19, ZMod 43] φ ![ζ₁, ζ₂] ζ hr) * (MatrixLogProd 3 ![ZMod 19, ZMod 43] φ ![ζ₁, ζ₂] ζ hr)) = 2 := by
      rw [matrix_log_units]
      convert Matrix.rank_one
      · ext i j
        fin_cases i <;> fin_cases j <;> rfl
      · exact strongRankCondition_of_orzechProperty (ZMod 3)
    rw [← this]
    apply Matrix.rank_mul_le_left

/-- The ideal `J = (2, α)`.  -/
def J : Ideal O :=
  Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![2, 0, 0, 0, 0], ![0, 2, 0, 0, -1]] i)))

def Mul1 : IdealMulEqCertificate O ℤ TT J J
  ![![2, 0, 0, 0, 0], ![0, 2, 0, 0, -1]] ![![2, 0, 0, 0, 0], ![0, 2, 0, 0, -1]]
  ![![4, 0, 0, 0, 0], ![0, 2, 0, 0, -1]] where
  T := T
  heq := T_eq_TT
  hI1 := rfl
  hI2 := rfl
  M := ![![![4,0,0,0,0], ![0, 4, 0 , 0, -2]], ![![0, 4, 0 , 0, -2], ![0, 0, 2 , -1, -1]]]
  hmul := by simp[table_mul_list] ; decide
  f := ![ ![![![1,0,0,0,0], ![0,0,0,0,0]], ![![0,0,0,0,0], ![0,0,0,0,0]]],
    ![![![959530, -223169, 231303, 248283 , 0], ![-1936093, -462699, -16515 , 0, -279]],
    ![![0,0,0,0,0], ![813, 144,14,0,1]]]]
  g := ![![![![1 , 0 , 0  , 0  , 0], ![0,0,0,0,0]] , ![![0,0,0,0,0], ![2,0,0,0,0]]] ,
    ![![![0, 0, 0 ,0 ,0], ![2, 0, 0 ,0 ,0]] , ![![0, 0, 0, 0, 0], ![0, 2, 0, 0, -1]]]]
  hle1 := by simp[table_mul_list] ; decide
  hle2 := by simp[table_mul_list] ; decide

def Mul2 : IdealMulEqCertificate O ℤ TT (J * J) J
  ![![4, 0, 0, 0, 0], ![0, 2, 0, 0, -1]] ![![2, 0, 0, 0, 0], ![0, 2, 0, 0, -1]]
  ![![0, 2, 0, 0, -1]] where
  T := T
  heq := T_eq_TT
  hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ Mul1
  hI2 := rfl
  M := ![![![8,0,0,0,0], ![0, 8, 0 , 0, -4]], ![![0, 4, 0 , 0, -2], ![0, 0, 2 , -1, -1]]]
  hmul := by simp[table_mul_list] ; decide
  f := ![ ![![![237953673, -57643398, 58559901, 60410931 , 0], ![-477654618,-117096441,-1832187 ,0,-11991]], ![![-195536 ,-46731,-1668,0,-27], ![99,18,0,0,1]]]]
  g := ![![![![9 , 0 , -6  , 3  , 4]] , ![![4,0,0,0,0]]] ,
    ![![![2, 0, 0 ,0 ,0]] , ![![0, 2, 0, 0, -1]]]]
  hle1 := by simp[table_mul_list] ; decide
  hle2 := by simp[table_mul_list] ; decide


lemma J_cube : J ^ 3 = Ideal.span {α} := by
  rw [pow_succ, sq, ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ Mul2]
  congr
  unfold α
  simp only [Nat.succ_eq_add_one, Nat.reduceAdd, Int.reduceNeg, cons_val_fin_one,
    Basis.equivFun_symm_apply, zsmul_eq_mul, Set.range_const]


instance K_field : Field K where
  __ := instCommRingK
  inv := sorry
  exists_pair_ne := sorry
  mul_inv_cancel := sorry
  inv_zero:= sorry
  nnqsmul := sorry
  nnqsmul_def := sorry
  qsmul_def := sorry
  qsmul := sorry

instance K_numberField : NumberField K := sorry

lemma K_finrank : Module.finrank ℚ K = 5 := sorry

theorem O_integral_closure : O = integralClosure ℤ K := by sorry



instance : Module.Finite ℤ (Additive (Oˣ ⧸ (CommGroup.torsion Oˣ))) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive (Oˣ ⧸ (CommGroup.torsion Oˣ))) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

lemma O_units_rank :  Module.finrank ℤ (Additive (Oˣ ⧸ (CommGroup.torsion Oˣ))) ≤ 2 := by
  erw [O_integral_closure, NumberField.Units.rank_modTorsion]
  unfold NumberField.Units.rank
-- Note that we already have an upper bound for the signature, given by
--  the L.I. units we found.
  sorry


lemma three_dvd_card (i : Fin 2 ): 3 ∣ Fintype.card (![ZMod 19, ZMod 43] i)ˣ := by
  fin_cases i
  · simp ; decide
  · simp ; decide


lemma three_ne_dvd_torsion : ¬3 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
  have := torsionOrder_eq_two_of_odd_finrank (K := K) (by rw [K_finrank] ; decide)
  simp only [NumberField.Units.torsionOrder] at this
  rw [← Subtype.val_inj] at this
  dsimp at this
  simp only [NumberField.Units.torsion, Fintype.card_eq_nat_card, NumberField.RingOfIntegers] at this
  rw [O_integral_closure]
  rw [this]
  decide

/-- We can write any unit `w` in `O` as `(ζ₁ ^ e₀) * (ζ₂ ^ e₁) * (t ^ 3)`, with `t` a unit. -/
lemma O_units_up_to_p_power (w : Oˣ) :
  (∃ (e : Fin 2 → ℕ) , (∃ (t : Oˣ) , w = (∏ (i : Fin 2), (![ζ₁, ζ₂] i) ^ (e i)) * t ^ 3)) := by
  have := units_up_to_p_power_of_full_rank_matrix_of_p_not_dvd_torsion (p := 3) ![ZMod 19, ZMod 43] ![ζ₁, ζ₂]
    units_isUnit φ ζ hr three_dvd_card three_ne_dvd_torsion (matrix_log_units_rank) ?_ w
  swap
  · simp only [Nat.succ_eq_add_one, zero_add, Nat.reduceAdd, Fintype.card_fin]
    exact O_units_rank
  obtain ⟨e, t, h1⟩ := this
  obtain ⟨e',h1, t', h2 ⟩ := (nat_up_to_power_of_int_up_to_power (p := 3) units_isUnit (w := w) (by norm_num) e t h1)
  use e' , t'

-----------------------------------

instance : (i : Fin 3) → CommRing (![ZMod 67, ZMod 19, ZMod 43] i) :=
  fun i =>
  match i with
  | 0 => by dsimp ; infer_instance
  | 1 => by dsimp ; infer_instance
  | 2 => by simp ; infer_instance

instance : (i : Fin 3) → Fintype (![ZMod 67, ZMod 19, ZMod 43] i) :=
  fun i =>
  match i with
  | 0 => by dsimp ; infer_instance
  | 1 => by dsimp ; infer_instance
  | 2 => by show Fintype (ZMod 43) ; infer_instance

noncomputable def φ' : ∀ (i : Fin 3) , O →+* ![ZMod 67, ZMod 19, ZMod 43] i :=
  fun i =>
  match i with
  | 0 => (φ₁.comp (Ideal.Quotient.mk I₁))
  | 1 => (φ₂.comp (Ideal.Quotient.mk I₂))
  | 2 => (φ₃.comp (Ideal.Quotient.mk I₃))

noncomputable def ζ' : ∀ (i : Fin 3) , ![ZMod 67, ZMod 19, ZMod 43] i :=
  fun i =>
  match i with
  | 0 => 2
  | 1 => 2
  | 2 => 3

noncomputable def hr' : ∀ (i : Fin 3) , IsPrimitiveRoot (ζ' i) (Fintype.card (![ZMod 67, ZMod 19, ZMod 43] i)ˣ) :=
  fun i =>
  match i with
  | 0 => PrimRoot₁
  | 1 => PrimRoot₂
  | 2 => PrimRoot₃


lemma three_dvd_card' (i : Fin 3 ): 3 ∣ Fintype.card (![ZMod 67, ZMod 19, ZMod 43] i)ˣ :=
  match i with
  | 0 => by simp ; decide
  | 1 => by simp ; decide
  | 2 => by
    have : Fintype.card (![ZMod 67, ZMod 19, ZMod 43] 2)ˣ = Fintype.card (ZMod 43)ˣ := by
      refine Fintype.card_congr' ?_
      rfl
    rw [this]
    simp ; decide


lemma matrix_log_alpha : (MatrixLogProd 3 ![ZMod 67, ZMod 19, ZMod 43] φ' (Sum.elim ![ζ₁, ζ₂] (fun (_ : Fin 1) => α)) ζ' hr') =
  ![Sum.elim ![1,0] ![-1], Sum.elim ![(-1 : ZMod 3), -1] ![0], Sum.elim ![0, 1] ![0]] := by
  ext i j
  rw [MatrixLogProd_def]
  fin_cases i
  · fin_cases j
    · exact log_of_zeta11
    · exact log_of_zeta21
    · exact log_of_alpha₁
  · fin_cases j
    · exact log_of_zeta12
    · exact log_of_zeta22
    · exact log_of_alpha₂
  · fin_cases j
    · simp ; exact log_of_zeta31
    · simp ; exact log_of_zeta32
    · simp ; exact log_of_alpha₃

lemma matrix_log_alpha_rank :
  (MatrixLogProd 3 ![ZMod 67, ZMod 19, ZMod 43] φ' (Sum.elim ![ζ₁, ζ₂] (fun (_ : Fin 1) => α)) ζ' hr').rank =
  Fintype.card (Fin 2) + 1 := by
  simp only [Fintype.card_fin]
  refine le_antisymm ?_ ?_
  ·  convert (Matrix.rank_le_card_width (MatrixLogProd 3 ![ZMod 67, ZMod 19, ZMod 43] φ' (Sum.elim ![ζ₁, ζ₂] (fun (_ : Fin 1) => α)) ζ' hr'))
  · refine le_of_eq_of_le ?_ (Matrix.rank_mul_le_left _ ((Sum.elim ![![0,-1,-1], ![0,0,1]] ![![-1,-1,-1]] : Matrix _ _ (ZMod 3))))
    convert Matrix.rank_one.symm
    · simp only [Nat.reduceAdd, Nat.succ_eq_add_one, zero_add, Fintype.card_fin]
    · rw [matrix_log_alpha]
      ext i j
      fin_cases i <;> fin_cases j <;> rfl
    · exact Fin.fintype 3
    · exact strongRankCondition_of_orzechProperty (ZMod 3)

/-- The ideal `J = (2, α)` is NOT principal. -/
theorem J_not_principal : ¬ ∃ b , J = Ideal.span {b} := by
  refine not_principal_of_full_rank_matrix (n := 3) ![ZMod 67, ZMod 19, ZMod 43]
    ![ζ₁, ζ₂] units_isUnit O_units_up_to_p_power φ' ζ' hr' three_dvd_card'
    J α ?_ ?_ ?_ matrix_log_alpha_rank
  · intro i
    fin_cases i
    · erw [phi_apply₁] ; simp ; decide
    · erw [phi_apply₂] ; simp only [Nat.succ_eq_add_one, Nat.reduceAdd, Fin.mk_one, Fin.isValue,
      cons_val_one, head_cons, isUnit_iff_ne_zero, ne_eq, neg_eq_zero] ; decide
    · erw [phi_apply₃]
      show IsUnit (-11 : ZMod 43)
      simp; decide
  · rfl
  · exact J_cube














--[Module.Finite ℤ (Additive (Sˣ ⧸ (CommGroup.torsion Sˣ)))]
--  [Module.Free ℤ (Additive (Sˣ ⧸ (CommGroup.torsion Sˣ)))]
