import IdealArithmetic.Examples.NF5_1_607500000_5.ClassGroupSaturated5_1_607500000_5_3
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F0
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F1
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F2
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F3
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F4
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F5
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F6
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F7
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F8
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F9
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F10
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F11
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F12
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F13
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F14
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F15
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F16
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F17
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F18
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F19
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F20
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F21
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F22
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F23
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F24
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F25
import IdealArithmetic.Examples.NF5_1_607500000_5.RelationIdeals5_1_607500000_5F26
import IdealArithmetic.Examples.NF5_1_607500000_5.PrimesBelowCert5_1_607500000_5
import Mathlib.NumberTheory.NumberField.ClassNumber
import IdealArithmetic.Signature.ResultantRecursive
import IdealArithmetic.DedekindProject.Discriminant
import IdealArithmetic.Generation.ClassGroupGeneration

set_option linter.all false

/- Number field `K(α)` with α root of polynomial `X^5 + 25*X^3 - 70*X^2 + 90*X - 88`.
Class group structure `[3]`, generated by class of ideals `[(2, 1/14*a^4 + 27/14*a^2 - 32/7*a + 46/7)]`. -/

/- Ring of integers with basis `[1, a, a^2, 1/7*a^3 + 3/7*a^2 + 1/7*a + 2/7, 1/14*a^4 - 1/14*a^2 + 3/7*a - 3/7]` -/

open BigOperators Classical Matrix Polynomial Module

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible

instance K_field : Field K := by
  unfold K
  exact AdjoinRoot.instField

instance K_numberField : NumberField K := by
  unfold K
  exact AdjoinRoot.instNumberFieldRat

instance : Module ℚ K := Algebra.toModule
instance : @Algebra ℤ K CommRing.toCommSemiring CommRing.toCommSemiring.toSemiring := Ring.toIntAlgebra K
instance : @CharZero K CommRing.toCommSemiring.toNonAssocSemiring.toAddCommMonoidWithOne.toAddMonoidWithOne := charZero_of_expChar_one' K

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  erw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, T_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ [2, 7]
  · fin_cases hc
    exact @pMaximal_of_MaximalOrderCertificateWLists K 2 _ IsAddTorsionFree.to_noZeroSMulDivisors_int _ O Om hm _ _ M2
    exact @pMaximal_of_MaximalOrderCertificateOfUnramifiedLists K 7 _ IsAddTorsionFree.to_noZeroSMulDivisors_int _ O Om hm _ _ M7
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [2, 7] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']

theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by rw [O_integral_closure] ; rfl

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance DD' : IsDedekindDomain O  := by
  rw [O_integral_closure]
  exact integralClosure.isDedekindDomain ℤ ℚ K

instance : Module.Free ℤ ↥O := Module.Free.of_basis B

instance  : IdemCommSemiring (Ideal O) := Ideal.instIdemCommSemiring
instance : CharZero O := SubsemiringClass.instCharZero O

def SturmRC : SturmBuilderOfList [[-88, 90, -70, 25, 0, 1], [90, -140, 75, 0, 5], [2200, -1800, 1050, -250], [-687000, 618000, -318000], [-1587600000, 264600000], [5834430000000]] [-88, 90, -70, 25, 0, 1] [90, -140, 75, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 5 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 62500, 101124000000, 70013160000000000]
  f := [1, 25, 62500, 101124000000]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [-5250, -1250], [-179400000, 79500000], [-341334000000000, -84142800000000]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 + 25*X^3 - 70*X^2 + 90*X - 88
  l := [-88, 90, -70, 25, 0, 1]
  hl := T_ofList
  hlz := by decide
  hz := by decide
  hAdj := Adj
  heq := O_integral_closure
  P := [[-88, 90, -70, 25, 0, 1], [90, -140, 75, 0, 5], [2200, -1800, 1050, -250], [-687000, 618000, -318000], [-1587600000, 264600000], [5834430000000]]
  SB := SturmRC
  k := 1
  r := 3
  hr := by decide
  hreq := by decide 

lemma ne_dvd_torsion3 : ¬3 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
 suffices ¬ 3 ∣ 2 from ?_
 · convert this
   rw [O_integral_closure, ← Fintype.card_eq_nat_card,
   ←  NumberField.Units.torsionOrder_eq_two_of_odd_finrank (by erw [K_finrank] ; decide)]
   rfl
 · decide

def NPCU3 : pMaximalUnitsCertificateNDvdT O 3 where 
 hp := by decide
 r := 2
 huc := by 
  erw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2]
 hu := fun i => 
  match i with 
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
 t := 3
 hrle := by decide
 q := ![7, 13, 37]
 hqP := by 
  intro i 
  match i with 
  | 0 => exact Sat3.hq7
  | 1 => exact Sat3.hq13
  | 2 => exact Sat3.hq37
 I := ![Sat3.I0, Sat3.I1, Sat3.I2]
 hcard := fun i =>
  match i with  
  | 0 => Sat3.N0
  | 1 => Sat3.N1
  | 2 => Sat3.N2
 ζ := ![3, 2, 2]
 hr := fun i =>
  match i with 
  | 0 => ((orderOf_of_IsOrderOf Sat3.R7) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf Sat3.R13) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf Sat3.R37) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 hpndvdt := ne_dvd_torsion3
 M := ![![0, 1], ![1, 0], ![1, 1]]
 hM1 := by 
  intro i j
  fin_cases i <;> fin_cases j 
  · erw [eq_of_DiscreteLogCertificate Sat3.Log00] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log01] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log10] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log11] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log20] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log21] ; decide
 Minv := ![![0, 1], ![1, 0]] 
 hInv := by decide

def NPSU3 : pSaturatedClassGroupCertificateNDvdT 3 ![J0] ![3] where 
 topMaximalUnitsCertificateNDvdT := NPCU3
 a := ![alpha0]
 γ := 1
 hc := by decide
 ψ := ![0]
 iψ := ![0] 
 hψ := by decide 
 hψn := by 
  intro i 
  fin_cases i 
  · decide
 h := fun i =>
  match i with 
  | 0 => by convert J0_pow3
 N := ![![0], ![0], ![2]]
 hM2 := by 
  intro (i : Fin 3) j
  match i , j with 
  | 0, 0 => exact Sat3.Log02
  | 1, 0 => exact Sat3.Log12
  | 2, 0 => exact Sat3.Log22
 hDl := by decide 
 NInv := ![![0, 1, 0], ![1, 0, 0], ![1, 1, 2]]
 hN := by decide 

lemma T_discr : T.discr = 5834430000000 :=  by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  rw [T_ofList]

theorem K_discr : NumberField.discr K = 607500000 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl

lemma K_nrComplexPlaces : NumberField.InfinitePlace.nrComplexPlaces K = 2 := by
  rw [nrComplexPlaces_of_RankUnitsCertificate RC]
  rfl

lemma K_nrRealPlaces : NumberField.InfinitePlace.nrRealPlaces K = 1 := by
  rw [nrRealPlaces_of_RankUnitsCertificate RC]
  rfl

theorem K_minowski : minkowskiBoundFB K ≤ (1534.3605833153126 : ℝ) := by
  refine K_minkowski_decimal _ ?_
  erw [K_nrComplexPlaces, K_discr, K_finrank]
  have hraux: √607500000 ≤ 24647.515098 := by
      refine Real.sqrt_le_iff.mpr ?_
      norm_num
  have : 0.0384 * √607500000 ≤ 946.47458 := by
    refine le_trans (mul_le_mul_of_nonneg (by rfl) hraux (by norm_num) (by norm_num)) ?_
    norm_num
  norm_num
  try {linarith}

def s := ![9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8]

def BM : (i : Fin 27) → Fin (e i) → (Fin 1 → ℕ) := by 
  rintro ⟨i, hi⟩ 
  interval_cases i 
  exact ![![1], ![2], ![2], ![0], ![2], ![0], ![1], ![0], ![2], ![2], ![0], ![1], ![0], ![1], ![0], ![2], ![1], ![0], ![2]]
  exact ![![0], ![2], ![1], ![1], ![2], ![2], ![2], ![1], ![0], ![0]]
  exact ![![2], ![2], ![0], ![2], ![2]]
  exact ![![0], ![1], ![2], ![1], ![0], ![0], ![0], ![1], ![0], ![0], ![0], ![2]]
  exact ![![1], ![0], ![1], ![0], ![2], ![0]]
  exact ![![1], ![1], ![0], ![2], ![1], ![0], ![1]]
  exact ![![0], ![1], ![0], ![2]]
  exact ![![1], ![1], ![0], ![0], ![0], ![2]]
  exact ![![1], ![0], ![2], ![2], ![2], ![2], ![2], ![2], ![2], ![1]]
  exact ![![0], ![2], ![2], ![0], ![0], ![0], ![1]]
  exact ![![1], ![1], ![2], ![0]]
  exact ![![1], ![1], ![1], ![2], ![2], ![1], ![1], ![1], ![1], ![2], ![2], ![0], ![1]]
  exact ![![1], ![1], ![2], ![1], ![1], ![1], ![2], ![2]]
  exact ![![0], ![1], ![0], ![1]]
  exact ![![0], ![1], ![1], ![0], ![0], ![2]]
  exact ![![2], ![1], ![1], ![1], ![2], ![2], ![0], ![0], ![2], ![1]]
  exact ![![0], ![2], ![2], ![2], ![2], ![0], ![1], ![1]]
  exact ![![2], ![1], ![1], ![2], ![0], ![1], ![1], ![2], ![1], ![0], ![1], ![0]]
  exact ![![1], ![1], ![1], ![2]]
  exact ![![1], ![2], ![0], ![1], ![1], ![2], ![2], ![0], ![0], ![1]]
  exact ![![1], ![2], ![2], ![2], ![0], ![2], ![0], ![0], ![2], ![0], ![1], ![1]]
  exact ![![1], ![1], ![0], ![1], ![2], ![0], ![1], ![1], ![2], ![2], ![0], ![0], ![2], ![0]]
  exact ![![2], ![1], ![2], ![2], ![1], ![0], ![0], ![2], ![2], ![1]]
  exact ![![2], ![1], ![2], ![2], ![2], ![1]]
  exact ![![0], ![2], ![0], ![0], ![0], ![0], ![2], ![2]]
  exact ![![1], ![2], ![2], ![2], ![1], ![2], ![2], ![0], ![0]]
  exact ![![2], ![2], ![1], ![2], ![2], ![2], ![1], ![0], ![1], ![0], ![0], ![1]]

lemma primesGenerationBelow : {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < 1535} ⊆ Set.range (Fin.addCasesIter e 𝔭) := by
  rw [← cert_eq_𝔭]
  refine le_primes_below_bound_of_PrimesBelowBoundCertificate_le_of_eq (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv PB1535

def 𝔭' : Fin 236 → nonZeroDivisors (Ideal O) := by
  intro i
  have : PB1535.β i ∈ List.ofFn PB1535.β := by
    simp only [List.mem_ofFn, exists_apply_eq_apply]
  refine Ideal.toNonZeroDivisorOfNeZero ((PB1535.β) i)
    (fun hc => ((zero_ne_mem_of_PrimesBelowCertificate_Fn _ PB1535) (hc ▸ this) ))

def J : Fin 1 → Ideal O := ![J0]

def J' :  Fin 1 → nonZeroDivisors (Ideal O) := by
  refine fun i => Ideal.toNonZeroDivisorOfNeZero (J i) (?_ )
  unfold J
  rw [← Submodule.zero_eq_bot, ← pow_ne_zero_iff (n := ![3] i) (by fin_cases i <;> decide) , NPSU3.h]
  simp only [ Submodule.zero_eq_bot, ne_eq, Ideal.span_singleton_eq_bot, NPSU3]
  fin_cases i
  · dsimp [alpha0] ; rw [(LinearEquiv.map_eq_zero_iff B.equivFun.symm)] ; decide 

lemma 𝔭'_apply : ∀ (i : Fin 236), ↑(𝔭' i) = (Fin.addCasesIter e 𝔭) i := by
  intro i
  rw [← cert_eq_𝔭]
  rfl

lemma J'_apply : ∀ (i : Fin 1), ↑(J' i) = J i := by
  intro i
  rfl

lemma relations_proof0 (i : Fin 19) : IsInClass O J (𝔭 0 i) (BM 0 i) := by
  show IsInClass O J (𝔭 0 i) (![![1], ![2], ![2], ![0], ![2], ![0], ![1], ![0], ![2], ![2], ![0], ![1], ![0], ![1], ![0], ![2], ![1], ![0], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R3N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R7N0
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R7N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R11N0
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R11N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R13N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R17N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R17N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R23N1

lemma relations_proof1 (i : Fin 10) : IsInClass O J (𝔭 1 i) (BM 1 i) := by
  show IsInClass O J (𝔭 1 i) (![![0], ![2], ![1], ![1], ![2], ![2], ![2], ![1], ![0], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R29N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R29N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R31N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R37N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R37N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R43N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R47N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof2 (i : Fin 5) : IsInClass O J (𝔭 2 i) (BM 2 i) := by
  show IsInClass O J (𝔭 2 i) (![![2], ![2], ![0], ![2], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R67N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R73N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R97N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R103N2

lemma relations_proof3 (i : Fin 12) : IsInClass O J (𝔭 3 i) (BM 3 i) := by
  show IsInClass O J (𝔭 3 i) (![![0], ![1], ![2], ![1], ![0], ![0], ![0], ![1], ![0], ![0], ![0], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R109N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R109N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R109N3
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R137N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R151N1

lemma relations_proof4 (i : Fin 6) : IsInClass O J (𝔭 4 i) (BM 4 i) := by
  show IsInClass O J (𝔭 4 i) (![![1], ![0], ![1], ![0], ![2], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R157N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R163N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R181N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof5 (i : Fin 7) : IsInClass O J (𝔭 5 i) (BM 5 i) := by
  show IsInClass O J (𝔭 5 i) (![![1], ![1], ![0], ![2], ![1], ![0], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R199N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R223N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R227N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R229N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R241N2

lemma relations_proof6 (i : Fin 4) : IsInClass O J (𝔭 6 i) (BM 6 i) := by
  show IsInClass O J (𝔭 6 i) (![![0], ![1], ![0], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R257N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R271N1

lemma relations_proof7 (i : Fin 6) : IsInClass O J (𝔭 7 i) (BM 7 i) := by
  show IsInClass O J (𝔭 7 i) (![![1], ![1], ![0], ![0], ![0], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R313N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R331N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R359N2

lemma relations_proof8 (i : Fin 10) : IsInClass O J (𝔭 8 i) (BM 8 i) := by
  show IsInClass O J (𝔭 8 i) (![![1], ![0], ![2], ![2], ![2], ![2], ![2], ![2], ![2], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R367N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R373N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R379N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R379N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R383N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R397N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R397N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R401N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R419N1

lemma relations_proof9 (i : Fin 7) : IsInClass O J (𝔭 9 i) (BM 9 i) := by
  show IsInClass O J (𝔭 9 i) (![![0], ![2], ![2], ![0], ![0], ![0], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R431N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R433N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R463N2

lemma relations_proof10 (i : Fin 4) : IsInClass O J (𝔭 10 i) (BM 10 i) := by
  show IsInClass O J (𝔭 10 i) (![![1], ![1], ![2], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R467N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R467N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R503N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof11 (i : Fin 13) : IsInClass O J (𝔭 11 i) (BM 11 i) := by
  show IsInClass O J (𝔭 11 i) (![![1], ![1], ![1], ![2], ![2], ![1], ![1], ![1], ![1], ![2], ![2], ![0], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R547N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R557N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R557N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R557N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R563N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R563N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R569N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R571N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R571N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R577N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R587N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R593N2

lemma relations_proof12 (i : Fin 8) : IsInClass O J (𝔭 12 i) (BM 12 i) := by
  show IsInClass O J (𝔭 12 i) (![![1], ![1], ![2], ![1], ![1], ![1], ![2], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R599N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R599N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R601N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R601N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R617N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R617N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R631N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R641N1

lemma relations_proof13 (i : Fin 4) : IsInClass O J (𝔭 13 i) (BM 13 i) := by
  show IsInClass O J (𝔭 13 i) (![![0], ![1], ![0], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R653N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R701N2

lemma relations_proof14 (i : Fin 6) : IsInClass O J (𝔭 14 i) (BM 14 i) := by
  show IsInClass O J (𝔭 14 i) (![![0], ![1], ![1], ![0], ![0], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R719N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R727N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R761N1

lemma relations_proof15 (i : Fin 10) : IsInClass O J (𝔭 15 i) (BM 15 i) := by
  show IsInClass O J (𝔭 15 i) (![![2], ![1], ![1], ![1], ![2], ![2], ![0], ![0], ![2], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R773N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R773N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R773N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R787N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R809N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R809N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R823N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R823N2

lemma relations_proof16 (i : Fin 8) : IsInClass O J (𝔭 16 i) (BM 16 i) := by
  show IsInClass O J (𝔭 16 i) (![![0], ![2], ![2], ![2], ![2], ![0], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R853N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R859N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R859N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R863N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R881N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R881N3

lemma relations_proof17 (i : Fin 12) : IsInClass O J (𝔭 17 i) (BM 17 i) := by
  show IsInClass O J (𝔭 17 i) (![![2], ![1], ![1], ![2], ![0], ![1], ![1], ![2], ![1], ![0], ![1], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R887N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R887N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R887N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R907N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R911N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R919N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R929N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R937N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R953N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof18 (i : Fin 4) : IsInClass O J (𝔭 18 i) (BM 18 i) := by
  show IsInClass O J (𝔭 18 i) (![![1], ![1], ![1], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R983N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R991N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R997N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R997N2

lemma relations_proof19 (i : Fin 10) : IsInClass O J (𝔭 19 i) (BM 19 i) := by
  show IsInClass O J (𝔭 19 i) (![![1], ![2], ![0], ![1], ![1], ![2], ![2], ![0], ![0], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1021N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1039N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1039N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1051N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1061N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1061N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1069N1

lemma relations_proof20 (i : Fin 12) : IsInClass O J (𝔭 20 i) (BM 20 i) := by
  show IsInClass O J (𝔭 20 i) (![![1], ![2], ![2], ![2], ![0], ![2], ![0], ![0], ![2], ![0], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1087N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1087N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1091N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1091N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1093N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1109N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1117N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1129N2

lemma relations_proof21 (i : Fin 14) : IsInClass O J (𝔭 21 i) (BM 21 i) := by
  show IsInClass O J (𝔭 21 i) (![![1], ![1], ![0], ![1], ![2], ![0], ![1], ![1], ![2], ![2], ![0], ![0], ![2], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1151N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1151N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1153N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1153N3
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1181N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1181N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1193N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1193N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1193N4
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof22 (i : Fin 10) : IsInClass O J (𝔭 22 i) (BM 22 i) := by
  show IsInClass O J (𝔭 22 i) (![![2], ![1], ![2], ![2], ![1], ![0], ![0], ![2], ![2], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1229N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1231N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1237N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1249N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1249N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1259N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1277N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1279N1

lemma relations_proof23 (i : Fin 6) : IsInClass O J (𝔭 23 i) (BM 23 i) := by
  show IsInClass O J (𝔭 23 i) (![![2], ![1], ![2], ![2], ![2], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1291N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1291N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1307N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1307N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1319N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1319N2

lemma relations_proof24 (i : Fin 8) : IsInClass O J (𝔭 24 i) (BM 24 i) := by
  show IsInClass O J (𝔭 24 i) (![![0], ![2], ![0], ![0], ![0], ![0], ![2], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1361N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1423N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1423N2

lemma relations_proof25 (i : Fin 9) : IsInClass O J (𝔭 25 i) (BM 25 i) := by
  show IsInClass O J (𝔭 25 i) (![![1], ![2], ![2], ![2], ![1], ![2], ![2], ![0], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1429N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1433N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1433N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1451N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1453N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1471N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1481N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof26 (i : Fin 12) : IsInClass O J (𝔭 26 i) (BM 26 i) := by
  show IsInClass O J (𝔭 26 i) (![![2], ![2], ![1], ![2], ![2], ![2], ![1], ![0], ![1], ![0], ![0], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1483N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1487N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1487N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1487N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1489N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1489N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1499N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1523N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1531N2

theorem class_group_generator : Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (J' i))) = ⊤ := by
  refine subgroup_closure_eq_classGroup'' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv
      𝔭'_apply J'_apply ?_ primesGenerationBelow (Fin.addCasesIter e BM) ?_
  · refine lt_of_le_of_lt K_minowski ?_
    norm_num
  · refine forall_addCasesIter_prop 𝔭 BM (IsInClass O J) ?_
    rintro ⟨i, hi⟩
    interval_cases i
    · exact relations_proof0
    · exact relations_proof1
    · exact relations_proof2
    · exact relations_proof3
    · exact relations_proof4
    · exact relations_proof5
    · exact relations_proof6
    · exact relations_proof7
    · exact relations_proof8
    · exact relations_proof9
    · exact relations_proof10
    · exact relations_proof11
    · exact relations_proof12
    · exact relations_proof13
    · exact relations_proof14
    · exact relations_proof15
    · exact relations_proof16
    · exact relations_proof17
    · exact relations_proof18
    · exact relations_proof19
    · exact relations_proof20
    · exact relations_proof21
    · exact relations_proof22
    · exact relations_proof23
    · exact relations_proof24
    · exact relations_proof25
    · exact relations_proof26

def ClassGroupO_equiv : (∀ i : Fin 1 , (ZMod (![3] i))) ≃+ Additive (ClassGroup O) := by
  haveI : ∀ (i : Fin 1), NeZero (![3] i) := by
    intro i
    fin_cases i <;>  exact {out := by decide}
  refine ClassGroup_equiv_of_pSaturatedCertificate J'_apply NPSU3.h class_group_generator ?_
  rintro ⟨p, hp1, hp2⟩
  have : ∏ i, ![3] i = ∏ i, (![3] i) ^ (![1] i)  := by decide
  rw [this] at hp2
  have hp_cases : p ∈ [3] := by
    obtain ⟨j ,hj1, hj2⟩  := Prime.exists_mem_finset_dvd (Nat.prime_iff.mp hp1) hp2
    show p ∈ List.ofFn ![3]
    rw [(Nat.prime_dvd_prime_iff_eq hp1 ?_).1 (Nat.Prime.dvd_of_dvd_pow hp1 hj2), List.mem_ofFn]
    exact ⟨j, rfl⟩
    fin_cases j <;> decide
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hp_cases
  by_cases h : p = 3
  simp_rw [h] ; right
  exact NPSU3
  omega

def class_group_equiv : (∀ i : Fin 1 , (ZMod (![3] i))) ≃+ Additive (ClassGroup (NumberField.RingOfIntegers K)) := by
 refine AddEquiv.trans ClassGroupO_equiv ?_
 exact MulEquiv.toAdditive (ClassGroup.congr
    ((Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv))

theorem class_number_K_eq_3 : NumberField.classNumber K = 3 := by
  unfold NumberField.classNumber
  rw [Fintype.card_eq_nat_card, ← Nat.card_congr (Additive.toMul),
    Nat.card_congr (class_group_equiv).symm.toEquiv, Nat.card_pi]
  simp [Fin.isValue, Fin.prod_succ]
  try decide
