import IdealArithmetic.Examples.NF5_1_1240312500_5.ClassGroupSaturated5_1_1240312500_5_2
import IdealArithmetic.Examples.NF5_1_1240312500_5.RelationIdeals5_1_1240312500_5
import IdealArithmetic.Examples.NF5_1_1240312500_5.PrimesBelowCert5_1_1240312500_5
import Mathlib.NumberTheory.NumberField.ClassNumber
import IdealArithmetic.ResultantRecursive
import IdealArithmetic.DiscriminantSubalgebraBuilder
import IdealArithmetic.ClassGroupGeneration

/- Number field `K(α)` with with α root of polynomial `X^5 - 10*X^2 - 285*X + 774`.
Class group structure `[2, 2]`, generated by class of ideals `((2, 5/126*a^4 + 1/42*a^3 + 3/14*a^2 - 59/126*a - 172/21), (2, 13/252*a^4 + 11/84*a^3 + 5/28*a^2 + 23/252*a - 485/42)`. -/

/- Ring of integers with basis `[1, a, a^2, 1/2*a^3 - 1/2*a, 1/252*a^4 + 17/84*a^3 + 9/28*a^2 + 89/252*a - 5/42]` -/

open BigOperators Classical Matrix Polynomial

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible 

noncomputable instance K_field : Field K := by
  unfold K
  infer_instance

instance K_numberField : NumberField K := by
  unfold K
  infer_instance

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  rw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, T_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out 

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ [2, 3, 7]
  · fin_cases hc
    exact pMaximal_of_MaximalOrderCertificateWLists 2 O Om hm M2
    exact pMaximal_of_MaximalOrderCertificateWLists 3 O Om hm M3
    exact pMaximal_of_MaximalOrderCertificateWLists 7 O Om hm M7
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [2, 3, 7] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']


theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by rw [O_integral_closure] ; rfl



instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance DD' : IsDedekindDomain O  := by
  rw [O_integral_closure]
  exact integralClosure.isDedekindDomain ℤ ℚ K

instance : Module.Free ℤ ↥O := Module.Free.of_basis B 


def SturmRC : SturmBuilderOfList [[774, -285, -10, 0, 0, 1], [-285, -20, 0, 0, 5], [-19350, 5700, 150], [-27386100000, 8731800000], [-315059220000000]] [774, -285, -10, 0, 0, 1] [-285, -20, 0, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic 
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 3375000, 76244331240000000000]
  f := [1, 125, 675000]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [176962500, -4275000, 112500], [53879175000000, 1309770000000]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 3 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 - 10*X^2 - 285*X + 774
  l := [774, -285, -10, 0, 0, 1]
  hl := T_ofList
  hlz := by decide
  hz := by decide
  hAdj := Adj
  heq := O_integral_closure
  P := [[774, -285, -10, 0, 0, 1], [-285, -20, 0, 0, 5], [-19350, 5700, 150], [-27386100000, 8731800000], [-315059220000000]]
  SB := SturmRC
  k := 1
  r := 3
  hr := by decide
  hreq := by decide 

def NPCU2 : pMaximailUnitsCertificateDvdT O 2 where 
 hp := by decide
 r := 2
 huc := by 
  rw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2]
 hu := fun i => 
  match i with 
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
 v := v
 m := 2
 hm := by norm_num
 hmv := v_pow_one
 t := 5
 hrle := by decide
 q := ![3, 17, 31, 31, 7]
 hqP := by 
  intro i 
  match i with 
  | 0 => exact Sat2.hq3
  | 1 => exact Sat2.hq17
  | 2 => exact Sat2.hq31
  | 3 => exact Sat2.hq31
  | 4 => exact Sat2.hq7
 I := ![Sat2.I0, Sat2.I1, Sat2.I2, Sat2.I3, Sat2.I4]
 hcard := fun i =>
  match i with  
  | 0 => Sat2.N0
  | 1 => Sat2.N1
  | 2 => Sat2.N2
  | 3 => Sat2.N3
  | 4 => Sat2.N4
 ζ := ![2, 3, 3, 3, 3]
 hr := fun i =>
  match i with 
  | 0 => ((orderOf_of_IsOrderOf Sat2.R3) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf Sat2.R17) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf Sat2.R31) ▸ IsPrimitiveRoot.orderOf _)
  | 3 => ((orderOf_of_IsOrderOf Sat2.R31) ▸ IsPrimitiveRoot.orderOf _)
  | 4 => ((orderOf_of_IsOrderOf Sat2.R7) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 M := ![![0, 0, 1], ![0, 1, 0], ![1, 1, 1], ![0, 0, 1], ![0, 0, 1]]
 hM1 := by 
  intro i j hj
  fin_cases i <;> interval_cases j 
  · erw [eq_of_DiscreteLogCertificate Sat2.Log00] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log01] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log10] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log11] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log20] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log21] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log30] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log31] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log40] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log41] ; decide
 hM2 := by 
  intro i 
  fin_cases i 
  · erw [eq_of_DiscreteLogCertificate Sat2.Log02] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log12] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log22] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log32] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log42] ; decide
 Minv := ![![1, 1, 1], ![0, 1, 0], ![1, 0, 0]]
 hInv := by decide

def NPSU2 : pSaturatedClassGroupCertificateDvdT 2 ![J0, J1] ![2, 2] where 
 topMaximailUnitsCertificateDvdT := NPCU2
 a := ![alpha0,alpha1]
 γ := 2
 hc := by decide
 ψ := ![0, 1]
 iψ := ![0, 1] 
 hψ := by decide 
 hψn := by 
  intro i 
  fin_cases i 
  · decide
  · decide
 h := fun i =>
  match i with 
  | 0 => J0_pow2
  | 1 => J1_pow2
 N := ![![1, 1], ![1, 1], ![1, 1], ![0, 0], ![1, 0]]
 hM3 := by 
  intro (i : Fin 5) j
  match i , j with 
  | 0, 0 => exact Sat2.Log03
  | 0, 1 => exact Sat2.Log04
  | 1, 0 => exact Sat2.Log13
  | 1, 1 => exact Sat2.Log14
  | 2, 0 => exact Sat2.Log23
  | 2, 1 => exact Sat2.Log24
  | 3, 0 => exact Sat2.Log33
  | 3, 1 => exact Sat2.Log34
  | 4, 0 => exact Sat2.Log43
  | 4, 1 => exact Sat2.Log44
 hDl := by decide 
 NInv := ![![0, 1, 1, 1, 0], ![1, 1, 0, 1, 0], ![0, 0, 0, 1, 0], ![0, 0, 0, 1, 1], ![1, 0, 0, 0, 1]]
 hN := by decide 

lemma T_discr : T.discriminant = 315059220000000 :=  by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  rw [T_ofList]

theorem K_discr : NumberField.discr K = 1240312500 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl

lemma K_nrComplexPlaces : NumberField.InfinitePlace.nrComplexPlaces K = 2 := by
  rw [nrComplexPlaces_of_RankUnitsCertificate RC]
  rfl

theorem K_minowski : MinkowskiBound K ≤ (2192.396009137476 : ℝ) := by
  refine K_minkowski_decimal _ ?_
  rw [K_nrComplexPlaces, K_discr, K_finrank]
  have hraux: √1240312500 ≤ 35218.070656 := by
      refine Real.sqrt_le_iff.mpr ?_
      norm_num
  have : 24/625 * √1240312500 ≤ 1352.373913 := by
    refine le_trans (mul_le_mul_of_nonneg (by rfl) hraux (by norm_num) (by norm_num)) ?_
    norm_num
  norm_num
  try {linarith}

set_option maxHeartbeats 3200000

def g : Fin 327 → Ideal O := ![I2N0, I2N1, I2N2, I3N0, I3N1, I5N0, I7N0, I7N1, I13N1, I17N1, I23N1, I31N1, I31N2, I37N0, I37N1, I37N2, I37N3, I41N0, I41N1, I41N2, I43N1, I53N1, I59N1, I59N2, I61N1, I61N2, I67N1, I71N1, I71N2, I73N1, I73N2, I73N3, I79N1, I79N2, I83N1, I89N2, I107N1, I109N1, I109N2, I113N1, I127N1, I131N0, I131N1, I131N2, I131N3, I131N4, I137N1, I139N1, I139N2, I149N1, I149N2, I151N1, I151N2, I157N1, I157N2, I157N3, I163N1, I167N1, I173N1, I179N2, I181N1, I181N2, I191N2, I197N1, I197N2, I197N3, I227N1, I239N2, I241N2, I251N1, I251N2, I257N1, I269N2, I271N2, I293N1, I317N1, I347N1, I347N2, I347N3, I349N1, I349N2, I359N1, I359N2, I373N1, I379N2, I389N1, I389N2, I409N1, I409N2, I419N2, I431N2, I433N1, I439N2, I443N1, I449N1, I449N2, I457N1, I463N1, I467N1, I467N2, I467N3, I479N1, I479N2, I503N1, I521N1, I521N2, I541N1, I541N2, I547N1, I557N1, I557N2, I557N3, I571N1, I571N2, I577N1, I593N1, I599N1, I599N2, I607N1, I617N1, I619N2, I631N1, I631N2, I641N1, I641N2, I643N1, I653N1, I659N0, I659N1, I659N2, I659N3, I659N4, I673N1, I683N1, I709N1, I709N2, I719N2, I727N1, I733N1, I733N2, I733N3, I743N1, I757N1, I757N2, I757N3, I773N1, I787N1, I809N2, I829N1, I829N2, I853N1, I857N1, I857N2, I857N3, I881N2, I883N1, I887N1, I911N2, I919N2, I929N2, I947N1, I977N1, I977N2, I977N3, I983N1, I991N1, I991N2, I997N1, I1013N1, I1019N2, I1021N1, I1021N2, I1031N2, I1039N1, I1039N2, I1049N1, I1049N2, I1051N2, I1061N2, I1087N1, I1091N1, I1091N2, I1093N1, I1103N1, I1103N2, I1103N3, I1117N1, I1123N1, I1129N1, I1129N2, I1151N1, I1151N2, I1153N1, I1163N1, I1163N2, I1163N3, I1171N2, I1181N2, I1213N1, I1217N1, I1217N2, I1217N3, I1223N1, I1223N2, I1223N3, I1229N1, I1229N2, I1237N1, I1237N2, I1237N3, I1249N1, I1249N2, I1259N1, I1259N2, I1277N1, I1279N1, I1279N2, I1291N2, I1297N1, I1303N1, I1361N1, I1361N2, I1367N1, I1373N1, I1409N2, I1427N1, I1439N1, I1439N2, I1447N1, I1451N2, I1453N1, I1471N1, I1471N2, I1493N1, I1493N2, I1493N3, I1499N2, I1511N1, I1511N2, I1531N1, I1531N2, I1543N1, I1553N1, I1559N2, I1567N1, I1579N0, I1579N1, I1579N2, I1579N3, I1579N4, I1583N1, I1613N1, I1613N2, I1613N3, I1619N2, I1621N1, I1621N2, I1627N1, I1627N2, I1627N3, I1637N1, I1637N2, I1637N3, I1657N1, I1663N1, I1699N1, I1699N2, I1723N1, I1733N1, I1741N1, I1741N2, I1747N1, I1759N1, I1759N2, I1777N1, I1777N2, I1777N3, I1783N1, I1783N2, I1783N3, I1787N1, I1823N1, I1831N1, I1831N2, I1847N1, I1861N1, I1861N2, I1877N1, I1879N1, I1879N2, I1889N1, I1889N2, I1901N2, I1913N1, I1931N1, I1931N2, I1933N1, I1949N2, I1973N1, I1987N1, I2003N1, I2017N1, I2027N1, I2039N2, I2053N1, I2053N2, I2053N3, I2063N1, I2069N2, I2087N1, I2087N2, I2087N3, I2089N1, I2089N2, I2111N1, I2111N2, I2113N1, I2137N1, I2143N1, I2153N1, I2161N0, I2161N1, I2161N2, I2161N3, I2161N4, I2179N1, I2179N2]

lemma primesGenerationBelowAux {x} : x ∈ (List.ofFn PB2193.Il).flatten ↔ x ∈ List.ofFn g := by
  have h1: (List.ofFn PB2193.Il).flatten = [I2N0, I2N1, I2N2, I2N2, I2N2, I3N0, I3N1, I3N1, I3N1, I5N0, I5N0, I5N0, I5N0, I5N0, I7N0, I7N1, I7N1, I7N1, I13N1, I17N1, I23N1, I31N1, I31N2, I37N0, I37N1, I37N2, I37N3, I41N0, I41N1, I41N2, I43N1, I53N1, I59N1, I59N2, I61N1, I61N2, I67N1, I71N1, I71N2, I73N1, I73N2, I73N3, I79N1, I79N2, I83N1, I89N2, I107N1, I109N1, I109N2, I113N1, I127N1, I131N0, I131N1, I131N2, I131N3, I131N4, I137N1, I139N1, I139N2, I149N1, I149N2, I151N1, I151N2, I157N1, I157N2, I157N3, I163N1, I167N1, I173N1, I179N2, I181N1, I181N2, I191N2, I197N1, I197N2, I197N3, I227N1, I239N2, I241N2, I251N1, I251N2, I257N1, I269N2, I271N2, I293N1, I317N1, I347N1, I347N2, I347N3, I349N1, I349N2, I359N1, I359N2, I373N1, I379N2, I389N1, I389N2, I409N1, I409N2, I419N2, I431N2, I433N1, I439N2, I443N1, I449N1, I449N2, I457N1, I463N1, I467N1, I467N2, I467N3, I479N1, I479N2, I503N1, I521N1, I521N2, I541N1, I541N2, I547N1, I557N1, I557N2, I557N3, I571N1, I571N2, I577N1, I593N1, I599N1, I599N2, I607N1, I617N1, I619N2, I631N1, I631N2, I641N1, I641N2, I643N1, I653N1, I659N0, I659N1, I659N2, I659N3, I659N4, I673N1, I683N1, I709N1, I709N2, I719N2, I727N1, I733N1, I733N2, I733N3, I743N1, I757N1, I757N2, I757N3, I773N1, I787N1, I809N2, I829N1, I829N2, I853N1, I857N1, I857N2, I857N3, I881N2, I883N1, I887N1, I911N2, I919N2, I929N2, I947N1, I977N1, I977N2, I977N3, I983N1, I991N1, I991N2, I997N1, I1013N1, I1019N2, I1021N1, I1021N2, I1031N2, I1039N1, I1039N2, I1049N1, I1049N2, I1051N2, I1061N2, I1087N1, I1091N1, I1091N2, I1093N1, I1103N1, I1103N2, I1103N3, I1117N1, I1123N1, I1129N1, I1129N2, I1151N1, I1151N2, I1153N1, I1163N1, I1163N2, I1163N3, I1171N2, I1181N2, I1213N1, I1217N1, I1217N2, I1217N3, I1223N1, I1223N2, I1223N3, I1229N1, I1229N2, I1237N1, I1237N2, I1237N3, I1249N1, I1249N2, I1259N1, I1259N2, I1277N1, I1279N1, I1279N2, I1291N2, I1297N1, I1303N1, I1361N1, I1361N2, I1367N1, I1373N1, I1409N2, I1427N1, I1439N1, I1439N2, I1447N1, I1451N2, I1453N1, I1471N1, I1471N2, I1493N1, I1493N2, I1493N3, I1499N2, I1511N1, I1511N2, I1531N1, I1531N2, I1543N1, I1553N1, I1559N2, I1567N1, I1579N0, I1579N1, I1579N2, I1579N3, I1579N4, I1583N1, I1613N1, I1613N2, I1613N3, I1619N2, I1621N1, I1621N2, I1627N1, I1627N2, I1627N3, I1637N1, I1637N2, I1637N3, I1657N1, I1663N1, I1699N1, I1699N2, I1723N1, I1733N1, I1741N1, I1741N2, I1747N1, I1759N1, I1759N2, I1777N1, I1777N2, I1777N3, I1783N1, I1783N2, I1783N3, I1787N1, I1823N1, I1831N1, I1831N2, I1847N1, I1861N1, I1861N2, I1877N1, I1879N1, I1879N2, I1889N1, I1889N2, I1901N2, I1913N1, I1931N1, I1931N2, I1933N1, I1949N2, I1973N1, I1987N1, I2003N1, I2017N1, I2027N1, I2039N2, I2053N1, I2053N2, I2053N3, I2063N1, I2069N2, I2087N1, I2087N2, I2087N3, I2089N1, I2089N2, I2111N1, I2111N2, I2113N1, I2137N1, I2143N1, I2153N1, I2161N0, I2161N1, I2161N2, I2161N3, I2161N4, I2179N1, I2179N2] := by rfl
  have h2: List.ofFn g = [I2N0, I2N1, I2N2, I3N0, I3N1, I5N0, I7N0, I7N1, I13N1, I17N1, I23N1, I31N1, I31N2, I37N0, I37N1, I37N2, I37N3, I41N0, I41N1, I41N2, I43N1, I53N1, I59N1, I59N2, I61N1, I61N2, I67N1, I71N1, I71N2, I73N1, I73N2, I73N3, I79N1, I79N2, I83N1, I89N2, I107N1, I109N1, I109N2, I113N1, I127N1, I131N0, I131N1, I131N2, I131N3, I131N4, I137N1, I139N1, I139N2, I149N1, I149N2, I151N1, I151N2, I157N1, I157N2, I157N3, I163N1, I167N1, I173N1, I179N2, I181N1, I181N2, I191N2, I197N1, I197N2, I197N3, I227N1, I239N2, I241N2, I251N1, I251N2, I257N1, I269N2, I271N2, I293N1, I317N1, I347N1, I347N2, I347N3, I349N1, I349N2, I359N1, I359N2, I373N1, I379N2, I389N1, I389N2, I409N1, I409N2, I419N2, I431N2, I433N1, I439N2, I443N1, I449N1, I449N2, I457N1, I463N1, I467N1, I467N2, I467N3, I479N1, I479N2, I503N1, I521N1, I521N2, I541N1, I541N2, I547N1, I557N1, I557N2, I557N3, I571N1, I571N2, I577N1, I593N1, I599N1, I599N2, I607N1, I617N1, I619N2, I631N1, I631N2, I641N1, I641N2, I643N1, I653N1, I659N0, I659N1, I659N2, I659N3, I659N4, I673N1, I683N1, I709N1, I709N2, I719N2, I727N1, I733N1, I733N2, I733N3, I743N1, I757N1, I757N2, I757N3, I773N1, I787N1, I809N2, I829N1, I829N2, I853N1, I857N1, I857N2, I857N3, I881N2, I883N1, I887N1, I911N2, I919N2, I929N2, I947N1, I977N1, I977N2, I977N3, I983N1, I991N1, I991N2, I997N1, I1013N1, I1019N2, I1021N1, I1021N2, I1031N2, I1039N1, I1039N2, I1049N1, I1049N2, I1051N2, I1061N2, I1087N1, I1091N1, I1091N2, I1093N1, I1103N1, I1103N2, I1103N3, I1117N1, I1123N1, I1129N1, I1129N2, I1151N1, I1151N2, I1153N1, I1163N1, I1163N2, I1163N3, I1171N2, I1181N2, I1213N1, I1217N1, I1217N2, I1217N3, I1223N1, I1223N2, I1223N3, I1229N1, I1229N2, I1237N1, I1237N2, I1237N3, I1249N1, I1249N2, I1259N1, I1259N2, I1277N1, I1279N1, I1279N2, I1291N2, I1297N1, I1303N1, I1361N1, I1361N2, I1367N1, I1373N1, I1409N2, I1427N1, I1439N1, I1439N2, I1447N1, I1451N2, I1453N1, I1471N1, I1471N2, I1493N1, I1493N2, I1493N3, I1499N2, I1511N1, I1511N2, I1531N1, I1531N2, I1543N1, I1553N1, I1559N2, I1567N1, I1579N0, I1579N1, I1579N2, I1579N3, I1579N4, I1583N1, I1613N1, I1613N2, I1613N3, I1619N2, I1621N1, I1621N2, I1627N1, I1627N2, I1627N3, I1637N1, I1637N2, I1637N3, I1657N1, I1663N1, I1699N1, I1699N2, I1723N1, I1733N1, I1741N1, I1741N2, I1747N1, I1759N1, I1759N2, I1777N1, I1777N2, I1777N3, I1783N1, I1783N2, I1783N3, I1787N1, I1823N1, I1831N1, I1831N2, I1847N1, I1861N1, I1861N2, I1877N1, I1879N1, I1879N2, I1889N1, I1889N2, I1901N2, I1913N1, I1931N1, I1931N2, I1933N1, I1949N2, I1973N1, I1987N1, I2003N1, I2017N1, I2027N1, I2039N2, I2053N1, I2053N2, I2053N3, I2063N1, I2069N2, I2087N1, I2087N2, I2087N3, I2089N1, I2089N2, I2111N1, I2111N2, I2113N1, I2137N1, I2143N1, I2153N1, I2161N0, I2161N1, I2161N2, I2161N3, I2161N4, I2179N1, I2179N2] := by rfl
  rw [h1, h2]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left] 

lemma primesGenerationBelow : {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < 2193} ⊆ Set.range g := by
  refine le_primes_below_bound_of_PrimesBelowBoundCertificate' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv g PB2193 ?_
  intro x hx
  exact primesGenerationBelowAux.1 hx 

def BM : Matrix (Fin 327) (Fin 2) ℕ := ![![1, 0], ![0, 1], ![1, 1], ![0, 1], ![0, 1], ![0, 0], ![1, 1], ![1, 1], ![0, 0], ![0, 1], ![1, 1], ![1, 0], ![0, 1], ![0, 1], ![1, 0], ![1, 0], ![0, 1], ![0, 1], ![1, 1], ![1, 0], ![1, 1], ![1, 1], ![0, 1], ![1, 1], ![1, 1], ![0, 1], ![0, 1], ![1, 0], ![0, 1], ![1, 0], ![0, 0], ![0, 0], ![0, 0], ![1, 0], ![1, 1], ![0, 0], ![0, 0], ![0, 1], ![1, 1], ![1, 0], ![0, 0], ![0, 1], ![1, 0], ![0, 0], ![0, 0], ![1, 1], ![1, 0], ![1, 0], ![0, 0], ![0, 1], ![0, 1], ![1, 0], ![1, 0], ![0, 1], ![0, 0], ![0, 0], ![1, 0], ![1, 1], ![1, 0], ![1, 1], ![1, 1], ![1, 1], ![0, 1], ![0, 0], ![1, 0], ![1, 1], ![0, 0], ![1, 1], ![1, 1], ![0, 1], ![1, 1], ![0, 0], ![0, 0], ![1, 1], ![1, 1], ![0, 0], ![0, 1], ![1, 0], ![1, 0], ![1, 0], ![1, 0], ![1, 1], ![1, 1], ![1, 0], ![1, 1], ![1, 1], ![1, 0], ![0, 0], ![1, 0], ![1, 1], ![1, 0], ![1, 0], ![1, 0], ![1, 1], ![1, 1], ![1, 0], ![1, 1], ![0, 1], ![1, 0], ![1, 1], ![0, 1], ![1, 1], ![0, 0], ![1, 0], ![1, 0], ![1, 1], ![0, 0], ![1, 0], ![0, 0], ![0, 0], ![1, 0], ![0, 1], ![1, 0], ![1, 1], ![0, 1], ![0, 1], ![0, 1], ![1, 1], ![0, 0], ![1, 1], ![1, 1], ![0, 1], ![0, 0], ![1, 0], ![1, 1], ![1, 1], ![0, 0], ![1, 1], ![1, 0], ![1, 1], ![1, 0], ![0, 0], ![1, 1], ![1, 1], ![1, 0], ![1, 1], ![0, 1], ![0, 0], ![1, 1], ![1, 0], ![1, 1], ![0, 0], ![1, 1], ![1, 1], ![1, 1], ![1, 0], ![1, 0], ![0, 0], ![0, 1], ![0, 1], ![0, 1], ![0, 0], ![0, 1], ![1, 0], ![1, 1], ![0, 1], ![0, 0], ![0, 1], ![1, 0], ![0, 1], ![0, 1], ![0, 0], ![0, 0], ![0, 0], ![0, 1], ![1, 1], ![0, 0], ![1, 1], ![1, 1], ![1, 0], ![0, 1], ![0, 0], ![0, 1], ![0, 0], ![0, 0], ![1, 1], ![1, 1], ![0, 1], ![1, 0], ![0, 0], ![1, 0], ![0, 0], ![1, 1], ![1, 1], ![1, 0], ![1, 0], ![1, 0], ![1, 1], ![1, 1], ![0, 0], ![1, 0], ![0, 1], ![0, 0], ![0, 1], ![1, 0], ![0, 1], ![1, 0], ![0, 0], ![0, 1], ![0, 1], ![1, 0], ![0, 0], ![1, 1], ![0, 0], ![0, 0], ![0, 0], ![1, 0], ![0, 0], ![0, 1], ![0, 1], ![0, 0], ![0, 1], ![1, 1], ![0, 0], ![0, 0], ![0, 0], ![0, 1], ![1, 0], ![1, 0], ![0, 0], ![0, 0], ![0, 1], ![1, 0], ![0, 1], ![0, 1], ![1, 0], ![0, 1], ![1, 1], ![0, 1], ![1, 0], ![1, 1], ![1, 1], ![1, 0], ![1, 1], ![0, 0], ![0, 0], ![0, 0], ![0, 1], ![0, 1], ![1, 1], ![1, 1], ![1, 0], ![0, 1], ![0, 1], ![1, 1], ![0, 0], ![1, 0], ![1, 0], ![1, 0], ![1, 0], ![1, 0], ![0, 1], ![0, 1], ![1, 1], ![1, 0], ![0, 1], ![0, 1], ![0, 0], ![0, 0], ![0, 1], ![1, 0], ![0, 1], ![1, 0], ![0, 0], ![0, 0], ![0, 1], ![1, 1], ![0, 1], ![0, 0], ![0, 0], ![0, 0], ![1, 0], ![0, 0], ![0, 0], ![0, 0], ![0, 0], ![0, 0], ![0, 1], ![1, 0], ![1, 1], ![1, 0], ![1, 1], ![1, 1], ![1, 1], ![1, 0], ![1, 0], ![0, 1], ![0, 0], ![0, 0], ![1, 0], ![1, 1], ![1, 0], ![1, 0], ![0, 1], ![0, 1], ![0, 0], ![0, 0], ![0, 0], ![0, 0], ![1, 1], ![0, 1], ![1, 1], ![0, 1], ![0, 0], ![0, 0], ![0, 0], ![1, 0], ![1, 0], ![1, 0], ![0, 1], ![1, 1], ![1, 1], ![1, 0], ![1, 0], ![1, 1], ![1, 1], ![1, 0], ![1, 1], ![1, 1], ![0, 0], ![1, 1], ![0, 1], ![1, 0], ![1, 1], ![1, 1], ![0, 0], ![0, 1]] 

def g' : Fin 327 → nonZeroDivisors (Ideal O) := by
  intro i
  have : g i ∈ (List.ofFn PB2193.Il).flatten := by 
    simp only [primesGenerationBelowAux, List.mem_ofFn, exists_apply_eq_apply]
  exact Ideal.toNonZeroDivisorOfNeZero (g i) 
    (fun hc => ((zero_ne_mem_of_PrimesBelowCertificate _ PB2193) (hc ▸ this) ))
    
def x : Fin 2 → Ideal O := ![J0,J1] 
    
def x' :  Fin 2 → nonZeroDivisors (Ideal O) := by 
  refine fun i => Ideal.toNonZeroDivisorOfNeZero (x i) (?_ )
  unfold x
  rw [← Submodule.zero_eq_bot, ← pow_ne_zero_iff (n := ![2, 2] i) (by fin_cases i <;> decide) , NPSU2.h] 
  simp only [ Submodule.zero_eq_bot, ne_eq, Ideal.span_singleton_eq_bot, NPSU2]
  fin_cases i    
  · dsimp [alpha0]
    rw [(LinearEquiv.map_eq_zero_iff B.equivFun.symm)]
    decide 
  · dsimp [alpha1]
    rw [(LinearEquiv.map_eq_zero_iff B.equivFun.symm)]
    decide 

lemma g'_apply : ∀ (i : Fin 327), ↑(g' i) = g i := by
  intro i
  rfl

lemma x'_apply : ∀ (i : Fin 2), ↑(x' i) = x i := by
  intro i
  rfl

theorem class_group_generator : Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (x' i))) = ⊤ := by
    refine subgroup_closure_eq_classGroup'' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv
      g'_apply x'_apply ?_ primesGenerationBelow BM ?_
    · refine lt_of_le_of_lt K_minowski ?_
      norm_num
    · intro i
      simp only [Fin.isValue, Fin.prod_univ_succ, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, mul_one]
      fin_cases i 
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2N0))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R3N0))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R3N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R7N0))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R7N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R17N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R23N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R31N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R31N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R37N0))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R37N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R37N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R37N3))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R41N0))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R41N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R41N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R43N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R53N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R59N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R59N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R61N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R61N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R67N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R71N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R71N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R73N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R79N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R83N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R109N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R109N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R113N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R131N0))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R131N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R131N4))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R137N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R139N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R149N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R149N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R151N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R151N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R157N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R163N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R167N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R173N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R179N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R181N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R181N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R191N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R197N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R197N3))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R239N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R241N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R251N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R251N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R271N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R293N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R347N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R347N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R347N3))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R349N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R349N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R359N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R359N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R373N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R379N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R389N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R389N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R409N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R419N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R431N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R433N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R439N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R443N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R449N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R449N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R457N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R463N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R467N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R467N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R467N3))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R479N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R503N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R521N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R521N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R541N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R557N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R557N3))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R571N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R571N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R577N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R593N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R599N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R599N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R617N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R619N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R631N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R641N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R641N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R643N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R659N0))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R659N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R659N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R659N3))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R673N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R683N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R709N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R709N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R719N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R733N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R733N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R733N3))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R757N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R757N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R757N3))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R773N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R787N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R829N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R829N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R853N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R857N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R857N3))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R881N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R883N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R911N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R919N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R929N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R947N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R983N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R991N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R997N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1013N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1019N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1021N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1031N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1049N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1049N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1051N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1061N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1091N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1093N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1103N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1103N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1103N3))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1117N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1123N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1129N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1151N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1151N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1163N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1163N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1163N3))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1171N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1213N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1217N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1217N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1223N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1229N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1237N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1237N3))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1249N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1259N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1279N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1291N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1297N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1361N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1367N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1373N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1409N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1427N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1439N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1439N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1447N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1451N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1453N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1471N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1471N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1493N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1511N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1511N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1531N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1531N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1543N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1553N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1559N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1567N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1579N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1579N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1579N3))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1579N4))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1583N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1613N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1613N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1613N3))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1619N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1621N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1621N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1627N3))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1637N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1637N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1637N3))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1699N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1699N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1723N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1747N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1783N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1783N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1783N3))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1787N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1823N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1831N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1831N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1847N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1861N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1861N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1879N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1889N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1889N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1901N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1913N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1931N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R1987N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2003N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2017N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2027N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2053N3))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2063N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2069N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2087N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2087N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2087N3))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2089N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2089N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2111N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2111N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2113N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2137N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2143N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2161N0))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2161N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2161N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2161N3))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2161N4))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2179N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)

def ClassGroupO_equiv : (∀ i : Fin 2 , (ZMod (![2, 2] i))) ≃+ Additive (ClassGroup O) := by
  haveI : ∀ (i : Fin 2), NeZero (![2, 2] i) := by
    intro i
    fin_cases i <;>  exact {out := by decide}
  refine ClassGroup_equiv_of_pSaturatedCertificate x'_apply NPSU2.h class_group_generator ?_
  rintro ⟨p, hp1, hp2⟩
  have : ∏ i, ![2, 2] i = ∏ i, (![2] i) ^ (![2] i)  := by decide
  rw [this] at hp2
  have hp_cases : p ∈ [2] := by
    obtain ⟨j ,hj1, hj2⟩  := Prime.exists_mem_finset_dvd (Nat.prime_iff.mp hp1) hp2
    show p ∈ List.ofFn ![2]
    rw [(Nat.prime_dvd_prime_iff_eq hp1 ?_).1 (Nat.Prime.dvd_of_dvd_pow hp1 hj2), List.mem_ofFn]
    exact ⟨j, rfl⟩ 
    fin_cases j <;> decide
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hp_cases 
  by_cases h : p = 2
  simp_rw [h] ; left
  exact NPSU2 
  omega 

def class_group_equiv : (∀ i : Fin 2 , (ZMod (![2, 2] i))) ≃+ Additive (ClassGroup (NumberField.RingOfIntegers K)) := by
 refine AddEquiv.trans ClassGroupO_equiv ?_
 exact MulEquiv.toAdditive (ClassGroup.congr
    ((Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv))

theorem class_number_K_eq_4 : NumberField.classNumber K = 4 := by
  unfold NumberField.classNumber
  rw [Fintype.card_eq_nat_card, ← Nat.card_congr (Additive.toMul),
    Nat.card_congr (class_group_equiv).symm.toEquiv, Nat.card_pi]
  simp only [Fin.isValue, Fin.prod_univ_two]
  simp
