import IdealArithmetic.Examples.NF6.NonPrincipalExample6
import Mathlib.NumberTheory.NumberField.ClassNumber
import IdealArithmetic.ResultantRecursive
import IdealArithmetic.DiscriminantSubalgebraBuilder

/- Number field `K(α)` with with α root of polynomial `X^5 + 10*X^3 - 10*X^2 - 15*X - 18`.
Class number `5`, generated by class of ideal `J = (2, -1/8*a^4 - 1/8*a^3 - 11/8*a^2 - 1/8*a + 11/4)`. We have `J ^ 5` is principal. -/

/- Ring of integers with basis `[1, a, a^2, 1/2*a^3 - 1/2*a, 1/24*a^4 - 1/8*a^3 - 5/24*a^2 + 5/24*a - 1/4]` -/

open BigOperators Classical Matrix Polynomial

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible

noncomputable instance K_field : Field K := by
  unfold K
  infer_instance

instance K_numberField : NumberField K := by
  unfold K
  infer_instance

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  rw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, T_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ [2, 3]
  · fin_cases hc
    exact pMaximal_of_MaximalOrderCertificateWLists 2 O Om hm M2
    exact pMaximal_of_MaximalOrderCertificateOfUnramifiedLists 3 O Om hm M3
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [2, 3] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']


theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by rw [O_integral_closure] ; rfl


instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K


def SturmRC : SturmBuilderOfList [[-18, -15, -10, 10, 0, 1], [-15, -20, 30, 0, 5], [9, 6, 3, -2], [-3, -4, -9], [-39, -25], [1]] [-18, -15, -10, 10, 0, 1] [-15, -20, 30, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 5 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 4, 81, 625]
  f := [50, 25, 16, 11664]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [-15, -10], [-35, 18], [-251, 225]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 + 10*X^3 - 10*X^2 - 15*X - 18
  l := [-18, -15, -10, 10, 0, 1]
  hl := T_ofList
  hlz := by decide
  hz := by decide
  hAdj := Adj
  heq := O_integral_closure
  P := [[-18, -15, -10, 10, 0, 1], [-15, -20, 30, 0, 5], [9, 6, 3, -2], [-3, -4, -9], [-39, -25], [1]]
  SB := SturmRC
  k := 1
  r := 3
  hr := by decide
  hreq := by decide

lemma ne_dvd_torsion5 : ¬5 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
 suffices ¬ 5 ∣ 2 from ?_
 · convert this
   rw [O_integral_closure, ← Fintype.card_eq_nat_card,
   ←  NumberField.Units.torsionOrder_eq_two_of_odd_finrank (by rw [K_finrank] ; decide)]
   rfl
 · decide

def NPCJ : NonPrincipalCertificateNDvdT J where
 p := 5
 hp := by decide
 r := 2
 huc := by
  rw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2]
 hu := fun i =>
  match i with
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
 q := ![11, 31, 151]
 hqP := by
  intro i
  match i with
  | 0 => exact hq11
  | 1 => exact hq31
  | 2 => exact hq151
 I := ![I0, I1, I2]
 hcard := fun i =>
  match i with
  | 0 => N0
  | 1 => N1
  | 2 => N2
 ζ := ![2, 3, 6]
 hr := fun i =>
  match i with
  | 0 => ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf R151) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 a := alpha
 n := 5
 hpdvd := by decide
 hJ := J5
 hpndvdt := ne_dvd_torsion5
 M := ![![4, 4, 3], ![3, 2, 4], ![3, 4, 0]]
 hM1 := by
  intro j i hj
  fin_cases i <;> interval_cases j
  · erw [eq_of_DiscreteLogCertificate Log00] ; decide
  · erw [eq_of_DiscreteLogCertificate Log01] ; decide
  · erw [eq_of_DiscreteLogCertificate Log10] ; decide
  · erw [eq_of_DiscreteLogCertificate Log11] ; decide
  · erw [eq_of_DiscreteLogCertificate Log20] ; decide
  · erw [eq_of_DiscreteLogCertificate Log21] ; decide
 hM2 := by
  intro i
  match i with
  | 0 => exact Log02
  | 1 => exact Log12
  | 2 => exact Log22
 hDl := by decide
 Minv := ![![2, 1, 0], ![1, 3, 4], ![3, 3, 3]]
 hInv := by decide
 N := ![![2, 1], ![2, 4]]
 hNiv := by decide

theorem J_not_principal : ¬ ∃ b, J = Ideal.span {b} :=
  not_principal_of_NonPrincipalCertificateNDvdT NPCJ


theorem T_discr : discriminant T = 14400000000 := by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  rw [T_ofList]

theorem K_discr : NumberField.discr K = 6250000 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl

lemma K_nrComplexPlaces : NumberField.InfinitePlace.nrComplexPlaces K = 2 := by
  rw [nrComplexPlaces_of_RankUnitsCertificate RC]
  rfl

theorem K_minowski (C : ClassGroup (NumberField.RingOfIntegers K)) :
  ∃ (I : (nonZeroDivisors (Ideal (NumberField.RingOfIntegers K)))),
    ClassGroup.mk0 I = C ∧
    ↑(Ideal.absNorm (↑I : Ideal (NumberField.RingOfIntegers K)) ) ≤ (155.63 : ℝ) := by
  obtain ⟨I, hI1, hI2⟩ := NumberField.exists_ideal_in_class_of_norm_le (K := K) C
  use I
  refine ⟨hI1, ?_ ⟩
  · refine le_trans hI2 ?_
    rw [K_nrComplexPlaces, K_discr, K_finrank]
    norm_num
    have := Real.pi_gt_d20
    have : (4 / Real.pi) ^ 2 < (4 / 3.14159265358979323846) ^ 2 := by
      refine (sq_lt_sq₀ ?_ ?_).mpr ?_
      · refine div_nonneg (by norm_num) (by exact Real.pi_nonneg)
      · refine div_nonneg (by norm_num) (by norm_num)
      · refine div_lt_div_of_pos_left (by norm_num) (by norm_num) this
    nlinarith
