import IdealArithmetic.Examples.NF6.NonPrincipalExample6
import Mathlib.NumberTheory.NumberField.ClassNumber
import IdealArithmetic.ResultantRecursive
import IdealArithmetic.DiscriminantSubalgebraBuilder
import IdealArithmetic.ClassGroupGeneration
import IdealArithmetic.Examples.NF6.RelationsIdeals

/- Number field `K(α)` with with α root of polynomial `X^5 + 10*X^3 - 10*X^2 - 15*X - 18`.
Class number `5`, generated by class of ideal `J = (2, -1/8*a^4 - 1/8*a^3 - 11/8*a^2 - 1/8*a + 11/4)`. We have `J ^ 5` is principal. -/

/- Ring of integers with basis `[1, a, a^2, 1/2*a^3 - 1/2*a, 1/24*a^4 - 1/8*a^3 - 5/24*a^2 + 5/24*a - 1/4]` -/

open BigOperators Classical Matrix Polynomial

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible

noncomputable instance K_field : Field K := by
  unfold K
  infer_instance

instance K_numberField : NumberField K := by
  unfold K
  infer_instance

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  rw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, T_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ [2, 3]
  · fin_cases hc
    exact pMaximal_of_MaximalOrderCertificateWLists 2 O Om hm M2
    exact pMaximal_of_MaximalOrderCertificateOfUnramifiedLists 3 O Om hm M3
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [2, 3] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']


theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by rw [O_integral_closure] ; rfl



instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance DD' : IsDedekindDomain O  := by
  rw [O_integral_closure]
  exact integralClosure.isDedekindDomain ℤ ℚ K

instance : Module.Free ℤ ↥O := Module.Free.of_basis B


def SturmRC : SturmBuilderOfList [[-18, -15, -10, 10, 0, 1], [-15, -20, 30, 0, 5], [450, 300, 150, -100], [-7500, -10000, -22500], [-19500000, -12500000], [14400000000]] [-18, -15, -10, 10, 0, 1] [-15, -20, 30, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 5 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 10000, 506250000, 156250000000000]
  f := [1, 25, 10000, 506250000]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [-750, -500], [-4375000, 2250000], [-313750000000, 281250000000]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 + 10*X^3 - 10*X^2 - 15*X - 18
  l := [-18, -15, -10, 10, 0, 1]
  hl := T_ofList
  hlz := by decide
  hz := by decide
  hAdj := Adj
  heq := O_integral_closure
  P := [[-18, -15, -10, 10, 0, 1], [-15, -20, 30, 0, 5], [450, 300, 150, -100], [-7500, -10000, -22500], [-19500000, -12500000], [14400000000]]
  SB := SturmRC
  k := 1
  r := 3
  hr := by decide
  hreq := by decide

lemma ne_dvd_torsion5 : ¬5 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
 suffices ¬ 5 ∣ 2 from ?_
 · convert this
   rw [O_integral_closure, ← Fintype.card_eq_nat_card,
   ←  NumberField.Units.torsionOrder_eq_two_of_odd_finrank (by rw [K_finrank] ; decide)]
   rfl
 · decide

def NPCJ : NonPrincipalCertificateNDvdT J where
 p := 5
 hp := by decide
 r := 2
 huc := by
  rw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2]
 hu := fun i =>
  match i with
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
 q := ![11, 31, 151]
 hqP := by
  intro i
  match i with
  | 0 => exact hq11
  | 1 => exact hq31
  | 2 => exact hq151
 I := ![I0, I1, I2]
 hcard := fun i =>
  match i with
  | 0 => N0
  | 1 => N1
  | 2 => N2
 ζ := ![2, 3, 6]
 hr := fun i =>
  match i with
  | 0 => ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf R151) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 a := alpha
 n := 5
 hpdvd := by decide
 hJ := J5
 hpndvdt := ne_dvd_torsion5
 M := ![![4, 4, 3], ![3, 2, 4], ![3, 4, 0]]
 hM1 := by
  intro j i hj
  fin_cases i <;> interval_cases j
  · erw [eq_of_DiscreteLogCertificate Log00] ; decide
  · erw [eq_of_DiscreteLogCertificate Log01] ; decide
  · erw [eq_of_DiscreteLogCertificate Log10] ; decide
  · erw [eq_of_DiscreteLogCertificate Log11] ; decide
  · erw [eq_of_DiscreteLogCertificate Log20] ; decide
  · erw [eq_of_DiscreteLogCertificate Log21] ; decide
 hM2 := by
  intro i
  match i with
  | 0 => exact Log02
  | 1 => exact Log12
  | 2 => exact Log22
 hDl := by decide
 Minv := ![![2, 1, 0], ![1, 3, 4], ![3, 3, 3]]
 hInv := by decide
 N := ![![2, 1], ![2, 4]]
 hNiv := by decide

theorem J_not_principal : ¬ ∃ b, J = Ideal.span {b} :=
  not_principal_of_NonPrincipalCertificateNDvdT NPCJ

lemma T_discr : T.discriminant = 14400000000 :=  by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  rw [T_ofList]

theorem K_discr : NumberField.discr K = 6250000 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl

lemma K_nrComplexPlaces : NumberField.InfinitePlace.nrComplexPlaces K = 2 := by
  rw [nrComplexPlaces_of_RankUnitsCertificate RC]
  rfl

theorem K_minowski : MinkowskiBound K ≤ (155.6393380746308 : ℝ) := by
  refine K_minkowski_decimal _ ?_
  rw [K_nrComplexPlaces, K_discr, K_finrank]
  norm_num


def g : Fin 29 → Ideal O := ![I151N2, I139N2, I131N2, I127N2, I107N2, I103N2, I83N2, I79N2, I71N2, I67N2, I59N2, I47N2, I43N2, I31N2, I23N2, I19N2, I11N0, I11N1, I11N2, I7N0, I7N1, I7N2, I5N, I3N0, I3N1, I3N2, I2N0, I2N1, I2N2]

lemma primesGenerationBelowAux {x} : x ∈ (List.ofFn PB153.Il).flatten ↔ x ∈ List.ofFn g := by
  have h2: List.ofFn g = [I151N2, I139N2, I131N2, I127N2, I107N2, I103N2, I83N2, I79N2, I71N2, I67N2, I59N2, I47N2, I43N2, I31N2, I23N2, I19N2, I11N0, I11N1, I11N2, I7N0, I7N1, I7N2, I5N, I3N0, I3N1, I3N2, I2N0, I2N1, I2N2] := by rfl
  have h1: (List.ofFn PB153.Il).flatten = [I151N2, I139N2, I131N2, I127N2, I107N2, I103N2, I83N2, I79N2, I71N2, I67N2, I59N2, I47N2, I43N2, I31N2, I23N2, I19N2, I11N0, I11N1, I11N2, I7N0, I7N1, I7N2, I5N, I5N, I5N, I5N, I5N, I3N0, I3N1, I3N2, I2N0, I2N1, I2N1, I2N2, I2N2] := by rfl
  --have h2: List.ofFn g = [I151N2, I139N2, I131N2, I127N2, I107N2, I103N2, I83N2, I79N2, I71N2, I67N2, I59N2, I47N2, I43N2, I31N2, I23N2, I19N2, I11N0, I11N1, I11N2, I7N0, I7N1, I7N2, I5N, I3N0, I3N1, I3N2, I2N0, I2N1, I2N2] := by rfl
  rw [ h1, h2, ]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]
  --simp [or_comm, or_assoc]



lemma primesGenerationBelow : {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < 156} ⊆ Set.range g := by
  refine le_primes_below_bound_of_PrimesBelowBoundCertificate' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv g PB153 ?_
  intro x hx
  exact primesGenerationBelowAux.1 hx

def BM : Matrix (Fin 29) (Fin 1) ℕ := !![0;1;3;1;0;2;3;2;2;3;4;2;0;3;1;3;2;2;1;0;0;0;3;4;4;2;1;1;1]

def g' : Fin 29 → nonZeroDivisors (Ideal O) := by
  intro i
  have : g i ∈ (List.ofFn PB153.Il).flatten := by
    simp only [primesGenerationBelowAux, List.mem_ofFn, exists_apply_eq_apply]
  exact Ideal.toNonZeroDivisorOfNeZero (g i)
    (fun hc => ((zero_ne_mem_of_PrimesBelowCertificate _ PB153) (hc ▸ this) ))

def x : Fin 1 → Ideal O := ![J]

def x' :  Fin 1 → nonZeroDivisors (Ideal O) := by
  refine fun i => Ideal.toNonZeroDivisorOfNeZero (x i) (fun hc => (J_not_principal ⟨0, ?_⟩ ))
  ext
  simp only [x, Fin.fin_one_eq_zero i, Fin.isValue, cons_val_fin_one, ne_eq] at hc
  simp only [hc, Ideal.mem_span_singleton, Ideal.mem_bot, zero_dvd_iff]

lemma g'_apply : ∀ (i : Fin 29), ↑(g' i) = g i := by
  intro i
  rfl

lemma x'_apply : ∀ (i : Fin 1), ↑(x' i) = x i := by
  intro i
  rfl

theorem class_group_generator : Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (x' i))) = ⊤ := by
    refine subgroup_closure_eq_classGroup'' (r := Fin 1) (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv
      g'_apply x'_apply ?_ primesGenerationBelow BM ?_
    · refine lt_of_le_of_lt K_minowski ?_
      norm_num
    · simp only [Finset.univ_unique, Fin.default_eq_zero, Fin.isValue, Finset.prod_singleton]
      intro i
      fin_cases i
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R139N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R131N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R127N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R103N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R83N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R79N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R71N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R67N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R59N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R47N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R31N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R23N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R19N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R11N0))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R11N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R11N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · exact ideal_mem_principal_class' O ℤ B _ _ (by decide) rfl
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R5N0))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R3N0))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R3N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R3N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2N0))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2N1))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
      · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2N2))))
        refine Nat.cast_ne_zero.2 (by decide)
        exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)

def class_group_O_equiv : ZMod 5 ≃+ Additive (ClassGroup O) := by
  refine equivClassGroupCyclicOfSaturated (I := J) (I' := x' 0) (rfl) J5 ?_ ?_
  convert class_group_generator
  intro p hp hpdvd
  have : p = 5 := ((prime_dvd_prime_iff_eq (q := 5) (Nat.prime_iff.mp hp))
    (Nat.prime_iff.mp (by decide))).1 hpdvd
  simp only [this, Nat.ofNat_pos, Nat.div_self, pow_one]
  exact J_not_principal

def class_group_equiv : ZMod 5 ≃+ Additive (ClassGroup (NumberField.RingOfIntegers K)) := by
  refine AddEquiv.trans class_group_O_equiv ?_
  exact MulEquiv.toAdditive (ClassGroup.congr
    ((Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv))

theorem class_number_K_eq_5 : NumberField.classNumber K = 5 := by
  unfold NumberField.classNumber
  rw [Fintype.card_eq_nat_card, ← Nat.card_congr (Additive.toMul),
    Nat.card_congr (class_group_equiv).symm.toEquiv]
  exact Nat.card_eq_fintype_card


#print axioms  class_number_K_eq_5
