import IdealArithmetic.Saturation.PrincipalityCertificate
import IdealArithmetic.Examples.NF5_1_9112500000_1.PrimesBelowCert5_1_9112500000_1
import Mathlib.NumberTheory.NumberField.ClassNumber
import IdealArithmetic.Signature.ResultantRecursive
import IdealArithmetic.DedekindProject.Discriminant
import IdealArithmetic.Generation.ClassGroupGeneration

set_option linter.all false

/- Number field `K(α)` with α root of polynomial `X^5 - 75*X^3 - 150*X^2 - 3600`.
Class group structure `[]`, generated by class of ideals `[]`. -/

/- Ring of integers with basis `[1, a, 1/2*a^2 - 1/2*a, 1/60*a^3 - 1/4*a^2 - 1/2*a, 1/60*a^4 - 1/4*a^2 - 1/2*a]` -/

open BigOperators Classical Matrix Polynomial Module

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible

instance K_field : Field K := by
  unfold K
  exact AdjoinRoot.instField

instance K_numberField : NumberField K := by
  unfold K
  exact AdjoinRoot.instNumberFieldRat

instance : Module ℚ K := Algebra.toModule
instance : @Algebra ℤ K CommRing.toCommSemiring CommRing.toCommSemiring.toSemiring := Ring.toIntAlgebra K
instance : @CharZero K CommRing.toCommSemiring.toNonAssocSemiring.toAddCommMonoidWithOne.toAddMonoidWithOne := charZero_of_expChar_one' K

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  erw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, T_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ [2, 3, 5]
  · fin_cases hc
    exact @pMaximal_of_MaximalOrderCertificateWLists K 2 _ IsAddTorsionFree.to_noZeroSMulDivisors_int _ O Om hm _ _ M2
    exact @pMaximal_of_MaximalOrderCertificateWLists K 3 _ IsAddTorsionFree.to_noZeroSMulDivisors_int _ O Om hm _ _ M3
    exact @pMaximal_of_MaximalOrderCertificateWLists K 5 _ IsAddTorsionFree.to_noZeroSMulDivisors_int _ O Om hm _ _ M5
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [2, 3, 5] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']

theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by rw [O_integral_closure] ; rfl

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance DD' : IsDedekindDomain O  := by
  rw [O_integral_closure]
  exact integralClosure.isDedekindDomain ℤ ℚ K

instance : Module.Free ℤ ↥O := Module.Free.of_basis B

instance  : IdemCommSemiring (Ideal O) := Ideal.instIdemCommSemiring
instance : CharZero O := SubsemiringClass.instCharZero O

def SturmRC : SturmBuilderOfList [[-3600, 0, -150, -75, 0, 1], [0, -300, -225, 0, 5], [90000, 0, 2250, 750], [-40500000, 20250000, 4050000], [-2187000000000, -437400000000], [472392000000000000]] [-3600, 0, -150, -75, 0, 1] [0, -300, -225, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 5 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 562500, 16402500000000, 191318760000000000000000]
  f := [1, 25, 562500, 16402500000000]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [-11250, 3750], [-6075000000, 3037500000], [0, -1771470000000000000]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 - 75*X^3 - 150*X^2 - 3600
  l := [-3600, 0, -150, -75, 0, 1]
  hl := T_ofList
  hlz := by decide
  hz := by decide
  hAdj := Adj
  heq := O_integral_closure
  P := [[-3600, 0, -150, -75, 0, 1], [0, -300, -225, 0, 5], [90000, 0, 2250, 750], [-40500000, 20250000, 4050000], [-2187000000000, -437400000000], [472392000000000000]]
  SB := SturmRC
  k := 1
  r := 3
  hr := by decide
  hreq := by decide 


lemma T_discr : T.discr = 472392000000000000 :=  by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  rw [T_ofList]

theorem K_discr : NumberField.discr K = 9112500000 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl

lemma K_nrComplexPlaces : NumberField.InfinitePlace.nrComplexPlaces K = 2 := by
  rw [nrComplexPlaces_of_RankUnitsCertificate RC]
  rfl

lemma K_nrRealPlaces : NumberField.InfinitePlace.nrRealPlaces K = 1 := by
  rw [nrRealPlaces_of_RankUnitsCertificate RC]
  rfl

theorem K_minowski : minkowskiBoundFB K ≤ (5942.5242564238415 : ℝ) := by
  refine K_minkowski_decimal _ ?_
  erw [K_nrComplexPlaces, K_discr, K_finrank]
  have hraux: √9112500000 ≤ 95459.41547 := by
      refine Real.sqrt_le_iff.mpr ?_
      norm_num
  have : 0.0384 * √9112500000 ≤ 3665.651554 := by
    refine le_trans (mul_le_mul_of_nonneg (by rfl) hraux (by norm_num) (by norm_num)) ?_
    norm_num
  norm_num
  try {linarith}

set_option maxRecDepth 20000

def s := ![9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 6]

def BM : (i : Fin 87) → Fin (e i) → (Fin 1 → ℕ) := by 
  rintro ⟨i, hi⟩ 
  interval_cases i 
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0]]

lemma primesGenerationBelow : {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < 5943} ⊆ Set.range (Fin.addCasesIter e 𝔭) := by
  rw [← cert_eq_𝔭]
  refine le_primes_below_bound_of_PrimesBelowBoundCertificate_le_of_eq (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv PB5943

def 𝔭' : Fin 785 → nonZeroDivisors (Ideal O) := by
  intro i
  have : PB5943.β i ∈ List.ofFn PB5943.β := by
    simp only [List.mem_ofFn, exists_apply_eq_apply]
  refine Ideal.toNonZeroDivisorOfNeZero ((PB5943.β) i)
    (fun hc => ((zero_ne_mem_of_PrimesBelowCertificate_Fn _ PB5943) (hc ▸ this) ))

def J : Fin 1 → Ideal O := ![⊤]

def J' :  Fin 1 → nonZeroDivisors (Ideal O) := by
  refine fun i => Ideal.toNonZeroDivisorOfNeZero (J i) (?_ )
  unfold J
  simp 

lemma 𝔭'_apply : ∀ (i : Fin 785), ↑(𝔭' i) = (Fin.addCasesIter e 𝔭) i := by
  intro i
  rw [← cert_eq_𝔭]
  rfl

lemma J'_apply : ∀ (i : Fin 1), ↑(J' i) = J i := by
  intro i
  rfl

lemma relations_proof0 (i : Fin 15) : IsInClass O J (𝔭 0 i) (BM 0 i) := by
  show IsInClass O J (𝔭 0 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof1 (i : Fin 15) : IsInClass O J (𝔭 1 i) (BM 1 i) := by
  show IsInClass O J (𝔭 1 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof2 (i : Fin 9) : IsInClass O J (𝔭 2 i) (BM 2 i) := by
  show IsInClass O J (𝔭 2 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof3 (i : Fin 15) : IsInClass O J (𝔭 3 i) (BM 3 i) := by
  show IsInClass O J (𝔭 3 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof4 (i : Fin 4) : IsInClass O J (𝔭 4 i) (BM 4 i) := by
  show IsInClass O J (𝔭 4 i) (![![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof5 (i : Fin 10) : IsInClass O J (𝔭 5 i) (BM 5 i) := by
  show IsInClass O J (𝔭 5 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof6 (i : Fin 13) : IsInClass O J (𝔭 6 i) (BM 6 i) := by
  show IsInClass O J (𝔭 6 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof7 (i : Fin 11) : IsInClass O J (𝔭 7 i) (BM 7 i) := by
  show IsInClass O J (𝔭 7 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof8 (i : Fin 8) : IsInClass O J (𝔭 8 i) (BM 8 i) := by
  show IsInClass O J (𝔭 8 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof9 (i : Fin 8) : IsInClass O J (𝔭 9 i) (BM 9 i) := by
  show IsInClass O J (𝔭 9 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof10 (i : Fin 3) : IsInClass O J (𝔭 10 i) (BM 10 i) := by
  show IsInClass O J (𝔭 10 i) (![![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof11 (i : Fin 15) : IsInClass O J (𝔭 11 i) (BM 11 i) := by
  show IsInClass O J (𝔭 11 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof12 (i : Fin 9) : IsInClass O J (𝔭 12 i) (BM 12 i) := by
  show IsInClass O J (𝔭 12 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof13 (i : Fin 8) : IsInClass O J (𝔭 13 i) (BM 13 i) := by
  show IsInClass O J (𝔭 13 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof14 (i : Fin 7) : IsInClass O J (𝔭 14 i) (BM 14 i) := by
  show IsInClass O J (𝔭 14 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof15 (i : Fin 2) : IsInClass O J (𝔭 15 i) (BM 15 i) := by
  show IsInClass O J (𝔭 15 i) (![![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof16 (i : Fin 14) : IsInClass O J (𝔭 16 i) (BM 16 i) := by
  show IsInClass O J (𝔭 16 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof17 (i : Fin 10) : IsInClass O J (𝔭 17 i) (BM 17 i) := by
  show IsInClass O J (𝔭 17 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof18 (i : Fin 7) : IsInClass O J (𝔭 18 i) (BM 18 i) := by
  show IsInClass O J (𝔭 18 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof19 (i : Fin 10) : IsInClass O J (𝔭 19 i) (BM 19 i) := by
  show IsInClass O J (𝔭 19 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof20 (i : Fin 7) : IsInClass O J (𝔭 20 i) (BM 20 i) := by
  show IsInClass O J (𝔭 20 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof21 (i : Fin 7) : IsInClass O J (𝔭 21 i) (BM 21 i) := by
  show IsInClass O J (𝔭 21 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof22 (i : Fin 10) : IsInClass O J (𝔭 22 i) (BM 22 i) := by
  show IsInClass O J (𝔭 22 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof23 (i : Fin 9) : IsInClass O J (𝔭 23 i) (BM 23 i) := by
  show IsInClass O J (𝔭 23 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof24 (i : Fin 3) : IsInClass O J (𝔭 24 i) (BM 24 i) := by
  show IsInClass O J (𝔭 24 i) (![![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof25 (i : Fin 8) : IsInClass O J (𝔭 25 i) (BM 25 i) := by
  show IsInClass O J (𝔭 25 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof26 (i : Fin 5) : IsInClass O J (𝔭 26 i) (BM 26 i) := by
  show IsInClass O J (𝔭 26 i) (![![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof27 (i : Fin 9) : IsInClass O J (𝔭 27 i) (BM 27 i) := by
  show IsInClass O J (𝔭 27 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof28 (i : Fin 9) : IsInClass O J (𝔭 28 i) (BM 28 i) := by
  show IsInClass O J (𝔭 28 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof29 (i : Fin 7) : IsInClass O J (𝔭 29 i) (BM 29 i) := by
  show IsInClass O J (𝔭 29 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof30 (i : Fin 10) : IsInClass O J (𝔭 30 i) (BM 30 i) := by
  show IsInClass O J (𝔭 30 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof31 (i : Fin 10) : IsInClass O J (𝔭 31 i) (BM 31 i) := by
  show IsInClass O J (𝔭 31 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof32 (i : Fin 10) : IsInClass O J (𝔭 32 i) (BM 32 i) := by
  show IsInClass O J (𝔭 32 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof33 (i : Fin 9) : IsInClass O J (𝔭 33 i) (BM 33 i) := by
  show IsInClass O J (𝔭 33 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof34 (i : Fin 8) : IsInClass O J (𝔭 34 i) (BM 34 i) := by
  show IsInClass O J (𝔭 34 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof35 (i : Fin 12) : IsInClass O J (𝔭 35 i) (BM 35 i) := by
  show IsInClass O J (𝔭 35 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof36 (i : Fin 6) : IsInClass O J (𝔭 36 i) (BM 36 i) := by
  show IsInClass O J (𝔭 36 i) (![![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof37 (i : Fin 8) : IsInClass O J (𝔭 37 i) (BM 37 i) := by
  show IsInClass O J (𝔭 37 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof38 (i : Fin 11) : IsInClass O J (𝔭 38 i) (BM 38 i) := by
  show IsInClass O J (𝔭 38 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof39 (i : Fin 6) : IsInClass O J (𝔭 39 i) (BM 39 i) := by
  show IsInClass O J (𝔭 39 i) (![![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof40 (i : Fin 16) : IsInClass O J (𝔭 40 i) (BM 40 i) := by
  show IsInClass O J (𝔭 40 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof41 (i : Fin 9) : IsInClass O J (𝔭 41 i) (BM 41 i) := by
  show IsInClass O J (𝔭 41 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof42 (i : Fin 8) : IsInClass O J (𝔭 42 i) (BM 42 i) := by
  show IsInClass O J (𝔭 42 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof43 (i : Fin 14) : IsInClass O J (𝔭 43 i) (BM 43 i) := by
  show IsInClass O J (𝔭 43 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof44 (i : Fin 5) : IsInClass O J (𝔭 44 i) (BM 44 i) := by
  show IsInClass O J (𝔭 44 i) (![![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof45 (i : Fin 9) : IsInClass O J (𝔭 45 i) (BM 45 i) := by
  show IsInClass O J (𝔭 45 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof46 (i : Fin 10) : IsInClass O J (𝔭 46 i) (BM 46 i) := by
  show IsInClass O J (𝔭 46 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof47 (i : Fin 9) : IsInClass O J (𝔭 47 i) (BM 47 i) := by
  show IsInClass O J (𝔭 47 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof48 (i : Fin 8) : IsInClass O J (𝔭 48 i) (BM 48 i) := by
  show IsInClass O J (𝔭 48 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof49 (i : Fin 9) : IsInClass O J (𝔭 49 i) (BM 49 i) := by
  show IsInClass O J (𝔭 49 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof50 (i : Fin 7) : IsInClass O J (𝔭 50 i) (BM 50 i) := by
  show IsInClass O J (𝔭 50 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof51 (i : Fin 6) : IsInClass O J (𝔭 51 i) (BM 51 i) := by
  show IsInClass O J (𝔭 51 i) (![![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof52 (i : Fin 9) : IsInClass O J (𝔭 52 i) (BM 52 i) := by
  show IsInClass O J (𝔭 52 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof53 (i : Fin 8) : IsInClass O J (𝔭 53 i) (BM 53 i) := by
  show IsInClass O J (𝔭 53 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof54 (i : Fin 8) : IsInClass O J (𝔭 54 i) (BM 54 i) := by
  show IsInClass O J (𝔭 54 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof55 (i : Fin 6) : IsInClass O J (𝔭 55 i) (BM 55 i) := by
  show IsInClass O J (𝔭 55 i) (![![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof56 (i : Fin 9) : IsInClass O J (𝔭 56 i) (BM 56 i) := by
  show IsInClass O J (𝔭 56 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof57 (i : Fin 13) : IsInClass O J (𝔭 57 i) (BM 57 i) := by
  show IsInClass O J (𝔭 57 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof58 (i : Fin 6) : IsInClass O J (𝔭 58 i) (BM 58 i) := by
  show IsInClass O J (𝔭 58 i) (![![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof59 (i : Fin 10) : IsInClass O J (𝔭 59 i) (BM 59 i) := by
  show IsInClass O J (𝔭 59 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof60 (i : Fin 14) : IsInClass O J (𝔭 60 i) (BM 60 i) := by
  show IsInClass O J (𝔭 60 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof61 (i : Fin 14) : IsInClass O J (𝔭 61 i) (BM 61 i) := by
  show IsInClass O J (𝔭 61 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof62 (i : Fin 8) : IsInClass O J (𝔭 62 i) (BM 62 i) := by
  show IsInClass O J (𝔭 62 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof63 (i : Fin 12) : IsInClass O J (𝔭 63 i) (BM 63 i) := by
  show IsInClass O J (𝔭 63 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof64 (i : Fin 8) : IsInClass O J (𝔭 64 i) (BM 64 i) := by
  show IsInClass O J (𝔭 64 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof65 (i : Fin 9) : IsInClass O J (𝔭 65 i) (BM 65 i) := by
  show IsInClass O J (𝔭 65 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof66 (i : Fin 10) : IsInClass O J (𝔭 66 i) (BM 66 i) := by
  show IsInClass O J (𝔭 66 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof67 (i : Fin 11) : IsInClass O J (𝔭 67 i) (BM 67 i) := by
  show IsInClass O J (𝔭 67 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof68 (i : Fin 5) : IsInClass O J (𝔭 68 i) (BM 68 i) := by
  show IsInClass O J (𝔭 68 i) (![![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof69 (i : Fin 10) : IsInClass O J (𝔭 69 i) (BM 69 i) := by
  show IsInClass O J (𝔭 69 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof70 (i : Fin 5) : IsInClass O J (𝔭 70 i) (BM 70 i) := by
  show IsInClass O J (𝔭 70 i) (![![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof71 (i : Fin 9) : IsInClass O J (𝔭 71 i) (BM 71 i) := by
  show IsInClass O J (𝔭 71 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof72 (i : Fin 9) : IsInClass O J (𝔭 72 i) (BM 72 i) := by
  show IsInClass O J (𝔭 72 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof73 (i : Fin 8) : IsInClass O J (𝔭 73 i) (BM 73 i) := by
  show IsInClass O J (𝔭 73 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof74 (i : Fin 7) : IsInClass O J (𝔭 74 i) (BM 74 i) := by
  show IsInClass O J (𝔭 74 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof75 (i : Fin 11) : IsInClass O J (𝔭 75 i) (BM 75 i) := by
  show IsInClass O J (𝔭 75 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof76 (i : Fin 15) : IsInClass O J (𝔭 76 i) (BM 76 i) := by
  show IsInClass O J (𝔭 76 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof77 (i : Fin 14) : IsInClass O J (𝔭 77 i) (BM 77 i) := by
  show IsInClass O J (𝔭 77 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof78 (i : Fin 6) : IsInClass O J (𝔭 78 i) (BM 78 i) := by
  show IsInClass O J (𝔭 78 i) (![![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof79 (i : Fin 13) : IsInClass O J (𝔭 79 i) (BM 79 i) := by
  show IsInClass O J (𝔭 79 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof80 (i : Fin 7) : IsInClass O J (𝔭 80 i) (BM 80 i) := by
  show IsInClass O J (𝔭 80 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof81 (i : Fin 6) : IsInClass O J (𝔭 81 i) (BM 81 i) := by
  show IsInClass O J (𝔭 81 i) (![![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof82 (i : Fin 11) : IsInClass O J (𝔭 82 i) (BM 82 i) := by
  show IsInClass O J (𝔭 82 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof83 (i : Fin 8) : IsInClass O J (𝔭 83 i) (BM 83 i) := by
  show IsInClass O J (𝔭 83 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof84 (i : Fin 6) : IsInClass O J (𝔭 84 i) (BM 84 i) := by
  show IsInClass O J (𝔭 84 i) (![![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof85 (i : Fin 8) : IsInClass O J (𝔭 85 i) (BM 85 i) := by
  show IsInClass O J (𝔭 85 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof86 (i : Fin 5) : IsInClass O J (𝔭 86 i) (BM 86 i) := by
  show IsInClass O J (𝔭 86 i) (![![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

theorem class_group_generator : Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (J' i))) = ⊤ := by
  refine subgroup_closure_eq_classGroup'' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv
      𝔭'_apply J'_apply ?_ primesGenerationBelow (Fin.addCasesIter e BM) ?_
  · refine lt_of_le_of_lt K_minowski ?_
    norm_num
  · refine forall_addCasesIter_prop 𝔭 BM (IsInClass O J) ?_
    rintro ⟨i, hi⟩
    interval_cases i
    · exact relations_proof0
    · exact relations_proof1
    · exact relations_proof2
    · exact relations_proof3
    · exact relations_proof4
    · exact relations_proof5
    · exact relations_proof6
    · exact relations_proof7
    · exact relations_proof8
    · exact relations_proof9
    · exact relations_proof10
    · exact relations_proof11
    · exact relations_proof12
    · exact relations_proof13
    · exact relations_proof14
    · exact relations_proof15
    · exact relations_proof16
    · exact relations_proof17
    · exact relations_proof18
    · exact relations_proof19
    · exact relations_proof20
    · exact relations_proof21
    · exact relations_proof22
    · exact relations_proof23
    · exact relations_proof24
    · exact relations_proof25
    · exact relations_proof26
    · exact relations_proof27
    · exact relations_proof28
    · exact relations_proof29
    · exact relations_proof30
    · exact relations_proof31
    · exact relations_proof32
    · exact relations_proof33
    · exact relations_proof34
    · exact relations_proof35
    · exact relations_proof36
    · exact relations_proof37
    · exact relations_proof38
    · exact relations_proof39
    · exact relations_proof40
    · exact relations_proof41
    · exact relations_proof42
    · exact relations_proof43
    · exact relations_proof44
    · exact relations_proof45
    · exact relations_proof46
    · exact relations_proof47
    · exact relations_proof48
    · exact relations_proof49
    · exact relations_proof50
    · exact relations_proof51
    · exact relations_proof52
    · exact relations_proof53
    · exact relations_proof54
    · exact relations_proof55
    · exact relations_proof56
    · exact relations_proof57
    · exact relations_proof58
    · exact relations_proof59
    · exact relations_proof60
    · exact relations_proof61
    · exact relations_proof62
    · exact relations_proof63
    · exact relations_proof64
    · exact relations_proof65
    · exact relations_proof66
    · exact relations_proof67
    · exact relations_proof68
    · exact relations_proof69
    · exact relations_proof70
    · exact relations_proof71
    · exact relations_proof72
    · exact relations_proof73
    · exact relations_proof74
    · exact relations_proof75
    · exact relations_proof76
    · exact relations_proof77
    · exact relations_proof78
    · exact relations_proof79
    · exact relations_proof80
    · exact relations_proof81
    · exact relations_proof82
    · exact relations_proof83
    · exact relations_proof84
    · exact relations_proof85
    · exact relations_proof86

def ClassGroupO_equiv : (∀ i : Fin 1 , (ZMod (![1] i))) ≃+ Additive (ClassGroup O) := by
  haveI : ∀ (i : Fin 1), NeZero (![1] i) := by
    intro i
    fin_cases i <;>  exact {out := by decide}
  refine ClassGroup_equiv_of_pSaturatedCertificate J'_apply (a := ![1]) (n := ![1])
    (by simp [J]; exact Eq.symm Ideal.span_singleton_one) class_group_generator ?_
  rintro ⟨p, hp1, hp2⟩
  simp at hp2
  exact (Nat.Prime.ne_one hp1 hp2).elim

def class_group_equiv : (∀ i : Fin 1 , (ZMod (![1] i))) ≃+ Additive (ClassGroup (NumberField.RingOfIntegers K)) := by
 refine AddEquiv.trans ClassGroupO_equiv ?_
 exact MulEquiv.toAdditive (ClassGroup.congr
    ((Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv))

theorem class_number_K_eq_1 : NumberField.classNumber K = 1 := by
  unfold NumberField.classNumber
  rw [Fintype.card_eq_nat_card, ← Nat.card_congr (Additive.toMul),
    Nat.card_congr (class_group_equiv).symm.toEquiv, Nat.card_pi]
  simp [Fin.isValue, Fin.prod_succ]
  try decide
