import IdealArithmetic.Examples.NF3_1_623807_1.ClassGroupSaturated3_1_623807_1_5
import IdealArithmetic.Examples.NF3_1_623807_1.RelationIdeals3_1_623807_1F0
import IdealArithmetic.Examples.NF3_1_623807_1.RelationIdeals3_1_623807_1F1
import IdealArithmetic.Examples.NF3_1_623807_1.RelationIdeals3_1_623807_1F2
import IdealArithmetic.Examples.NF3_1_623807_1.RelationIdeals3_1_623807_1F3
import IdealArithmetic.Examples.NF3_1_623807_1.RelationIdeals3_1_623807_1F4
import IdealArithmetic.Examples.NF3_1_623807_1.PrimesBelowCert3_1_623807_1
import Mathlib.NumberTheory.NumberField.ClassNumber
import IdealArithmetic.Signature.ResultantRecursive
import IdealArithmetic.DedekindProject.Discriminant
import IdealArithmetic.Generation.ClassGroupGeneration

set_option linter.all false

/- Number field `K(α)` with α root of polynomial `X^3 - X - 304`.
Class group structure `[5]`, generated by class of ideals `[(2, 1/2*a^2 - 1/2*a + 1)]`. -/

/- Ring of integers with basis `[1, a, 1/2*a^2 - 1/2*a]` -/

open BigOperators Classical Matrix Polynomial Module

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible

instance K_field : Field K := by
  unfold K
  exact AdjoinRoot.instField

instance K_numberField : NumberField K := by
  unfold K
  exact AdjoinRoot.instNumberFieldRat

instance : Module ℚ K := Algebra.toModule
instance : @Algebra ℤ K CommRing.toCommSemiring CommRing.toCommSemiring.toSemiring := Ring.toIntAlgebra K
instance : @CharZero K CommRing.toCommSemiring.toNonAssocSemiring.toAddCommMonoidWithOne.toAddMonoidWithOne := charZero_of_expChar_one' K

lemma K_finrank : Module.finrank ℚ K = 3 := by
  unfold K
  erw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, T_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ [2]
  · fin_cases hc
    exact @pMaximal_of_MaximalOrderCertificateOfUnramifiedLists K 2 _ IsAddTorsionFree.to_noZeroSMulDivisors_int _ O Om hm _ _ M2
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [2] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']

theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by rw [O_integral_closure] ; rfl

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance DD' : IsDedekindDomain O  := by
  rw [O_integral_closure]
  exact integralClosure.isDedekindDomain ℤ ℚ K

instance : Module.Free ℤ ↥O := Module.Free.of_basis B

instance  : IdemCommSemiring (Ideal O) := Ideal.instIdemCommSemiring
instance : CharZero O := SubsemiringClass.instCharZero O

def SturmRC : SturmBuilderOfList [[-304, -1, 0, 1], [-1, 0, 3], [2736, 6], [-2495228]] [-304, -1, 0, 1] [-1, 0, 3] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 3 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [9, 36]
  f := [1, 9]
  epos := by decide
  fpos := by decide
  Q := [[0, 3], [-8208, 18]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 2 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^3 - X - 304
  l := [-304, -1, 0, 1]
  hl := T_ofList
  hlz := by decide
  hz := by decide
  hAdj := Adj
  heq := O_integral_closure
  P := [[-304, -1, 0, 1], [-1, 0, 3], [2736, 6], [-2495228]]
  SB := SturmRC
  k := 1
  r := 2
  hr := by decide
  hreq := by decide 

lemma ne_dvd_torsion5 : ¬5 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
 suffices ¬ 5 ∣ 2 from ?_
 · convert this
   rw [O_integral_closure, ← Fintype.card_eq_nat_card,
   ←  NumberField.Units.torsionOrder_eq_two_of_odd_finrank (by erw [K_finrank] ; decide)]
   rfl
 · decide

def NPCU5 : pMaximalUnitsCertificateNDvdT O 5 where 
 hp := by decide
 r := 1
 huc := by 
  erw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1]
 hu := fun i => 
  match i with 
  | 0 => isUnit_zeta1
 t := 2
 hrle := by decide
 q := ![31, 41]
 hqP := by 
  intro i 
  match i with 
  | 0 => exact Sat5.hq31
  | 1 => exact Sat5.hq41
 I := ![Sat5.I0, Sat5.I1]
 hcard := fun i =>
  match i with  
  | 0 => Sat5.N0
  | 1 => Sat5.N1
 ζ := ![3, 6]
 hr := fun i =>
  match i with 
  | 0 => ((orderOf_of_IsOrderOf Sat5.R31) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf Sat5.R41) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 hpndvdt := ne_dvd_torsion5
 M := ![![1], ![0]]
 hM1 := by 
  intro i j
  fin_cases i <;> fin_cases j 
  · erw [eq_of_DiscreteLogCertificate Sat5.Log00] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat5.Log10] ; decide
 Minv := ![![1]] 
 hInv := by decide

def NPSU5 : pSaturatedClassGroupCertificateNDvdT 5 ![J0] ![5] where 
 topMaximalUnitsCertificateNDvdT := NPCU5
 a := ![alpha0]
 γ := 1
 hc := by decide
 ψ := ![0]
 iψ := ![0] 
 hψ := by decide 
 hψn := by 
  intro i 
  fin_cases i 
  · decide
 h := fun i =>
  match i with 
  | 0 => by convert J0_pow5
 N := ![![1], ![3]]
 hM2 := by 
  intro (i : Fin 2) j
  match i , j with 
  | 0, 0 => exact Sat5.Log01
  | 1, 0 => exact Sat5.Log11
 hDl := by decide 
 NInv := ![![1, 3], ![0, 2]]
 hN := by decide 

lemma T_discr : T.discr = -2495228 :=  by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  rw [T_ofList]

theorem K_discr : NumberField.discr K = -623807 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl

lemma K_nrComplexPlaces : NumberField.InfinitePlace.nrComplexPlaces K = 1 := by
  rw [nrComplexPlaces_of_RankUnitsCertificate RC]
  rfl

lemma K_nrRealPlaces : NumberField.InfinitePlace.nrRealPlaces K = 1 := by
  rw [nrRealPlaces_of_RankUnitsCertificate RC]
  rfl

theorem K_minowski : minkowskiBoundFB K ≤ (223.48179982502862 : ℝ) := by
  refine K_minkowski_decimal _ ?_
  erw [K_nrComplexPlaces, K_discr, K_finrank]
  have hraux: √623807 ≤ 789.814545 := by
      refine Real.sqrt_le_iff.mpr ?_
      norm_num
  have : 0.2222222222222222 * √623807 ≤ 175.524343 := by
    refine le_trans (mul_le_mul_of_nonneg (by rfl) hraux (by norm_num) (by norm_num)) ?_
    norm_num
  norm_num
  try {linarith}

def s := ![11, 11, 11, 11, 4]

def BM : (i : Fin 5) → Fin (e i) → (Fin 1 → ℕ) := by 
  rintro ⟨i, hi⟩ 
  interval_cases i 
  exact ![![3], ![1], ![1], ![0], ![2], ![3], ![1], ![4], ![0], ![0], ![3], ![1], ![1], ![2], ![3], ![4]]
  exact ![![1], ![2], ![1], ![2], ![4], ![4], ![4], ![2], ![2], ![1], ![2], ![4], ![3], ![1], ![2], ![2]]
  exact ![![0], ![4], ![3], ![1], ![1], ![3], ![3], ![4], ![0], ![4], ![4], ![2], ![0]]
  exact ![![2], ![0], ![0], ![0], ![1]]
  exact ![![3], ![3], ![4], ![3]]

lemma primesGenerationBelow : {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < 224} ⊆ Set.range (Fin.addCasesIter e 𝔭) := by
  rw [← cert_eq_𝔭]
  refine le_primes_below_bound_of_PrimesBelowBoundCertificate_le_of_eq (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv PB224

def 𝔭' : Fin 54 → nonZeroDivisors (Ideal O) := by
  intro i
  have : PB224.β i ∈ List.ofFn PB224.β := by
    simp only [List.mem_ofFn, exists_apply_eq_apply]
  refine Ideal.toNonZeroDivisorOfNeZero ((PB224.β) i)
    (fun hc => ((zero_ne_mem_of_PrimesBelowCertificate_Fn _ PB224) (hc ▸ this) ))

def J : Fin 1 → Ideal O := ![J0]

def J' :  Fin 1 → nonZeroDivisors (Ideal O) := by
  refine fun i => Ideal.toNonZeroDivisorOfNeZero (J i) (?_ )
  unfold J
  rw [← Submodule.zero_eq_bot, ← pow_ne_zero_iff (n := ![5] i) (by fin_cases i <;> decide) , NPSU5.h]
  simp only [ Submodule.zero_eq_bot, ne_eq, Ideal.span_singleton_eq_bot, NPSU5]
  fin_cases i
  · dsimp [alpha0] ; rw [(LinearEquiv.map_eq_zero_iff B.equivFun.symm)] ; decide 

lemma 𝔭'_apply : ∀ (i : Fin 54), ↑(𝔭' i) = (Fin.addCasesIter e 𝔭) i := by
  intro i
  rw [← cert_eq_𝔭]
  rfl

lemma J'_apply : ∀ (i : Fin 1), ↑(J' i) = J i := by
  intro i
  rfl

lemma relations_proof0 (i : Fin 16) : IsInClass O J (𝔭 0 i) (BM 0 i) := by
  show IsInClass O J (𝔭 0 i) (![![3], ![1], ![1], ![0], ![2], ![3], ![1], ![4], ![0], ![0], ![3], ![1], ![1], ![2], ![3], ![4]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R5N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R5N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R7N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R7N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R19N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R19N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R19N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R23N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R29N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R31N1

lemma relations_proof1 (i : Fin 16) : IsInClass O J (𝔭 1 i) (BM 1 i) := by
  show IsInClass O J (𝔭 1 i) (![![1], ![2], ![1], ![2], ![4], ![4], ![4], ![2], ![2], ![1], ![2], ![4], ![3], ![1], ![2], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R37N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R41N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R41N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R41N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R43N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R47N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R47N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R47N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R53N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R59N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R59N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R61N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R67N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R71N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R73N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R79N1

lemma relations_proof2 (i : Fin 13) : IsInClass O J (𝔭 2 i) (BM 2 i) := by
  show IsInClass O J (𝔭 2 i) (![![0], ![4], ![3], ![1], ![1], ![3], ![3], ![4], ![0], ![4], ![4], ![2], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R97N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R97N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R101N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R101N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R101N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R109N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R109N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R127N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R127N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R127N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof3 (i : Fin 5) : IsInClass O J (𝔭 3 i) (BM 3 i) := by
  show IsInClass O J (𝔭 3 i) (![![2], ![0], ![0], ![0], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R149N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R191N1

lemma relations_proof4 (i : Fin 4) : IsInClass O J (𝔭 4 i) (BM 4 i) := by
  show IsInClass O J (𝔭 4 i) (![![3], ![3], ![4], ![3]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R199N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R199N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R199N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R223N1

theorem class_group_generator : Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (J' i))) = ⊤ := by
  refine subgroup_closure_eq_classGroup'' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv
      𝔭'_apply J'_apply ?_ primesGenerationBelow (Fin.addCasesIter e BM) ?_
  · refine lt_of_le_of_lt K_minowski ?_
    norm_num
  · refine forall_addCasesIter_prop 𝔭 BM (IsInClass O J) ?_
    rintro ⟨i, hi⟩
    interval_cases i
    · exact relations_proof0
    · exact relations_proof1
    · exact relations_proof2
    · exact relations_proof3
    · exact relations_proof4

def ClassGroupO_equiv : (∀ i : Fin 1 , (ZMod (![5] i))) ≃+ Additive (ClassGroup O) := by
  haveI : ∀ (i : Fin 1), NeZero (![5] i) := by
    intro i
    fin_cases i <;>  exact {out := by decide}
  refine ClassGroup_equiv_of_pSaturatedCertificate J'_apply NPSU5.h class_group_generator ?_
  rintro ⟨p, hp1, hp2⟩
  have : ∏ i, ![5] i = ∏ i, (![5] i) ^ (![1] i)  := by decide
  rw [this] at hp2
  have hp_cases : p ∈ [5] := by
    obtain ⟨j ,hj1, hj2⟩  := Prime.exists_mem_finset_dvd (Nat.prime_iff.mp hp1) hp2
    show p ∈ List.ofFn ![5]
    rw [(Nat.prime_dvd_prime_iff_eq hp1 ?_).1 (Nat.Prime.dvd_of_dvd_pow hp1 hj2), List.mem_ofFn]
    exact ⟨j, rfl⟩
    fin_cases j <;> decide
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hp_cases
  by_cases h : p = 5
  simp_rw [h] ; right
  exact NPSU5
  omega

def class_group_equiv : (∀ i : Fin 1 , (ZMod (![5] i))) ≃+ Additive (ClassGroup (NumberField.RingOfIntegers K)) := by
 refine AddEquiv.trans ClassGroupO_equiv ?_
 exact MulEquiv.toAdditive (ClassGroup.congr
    ((Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv))

theorem class_number_K_eq_5 : NumberField.classNumber K = 5 := by
  unfold NumberField.classNumber
  rw [Fintype.card_eq_nat_card, ← Nat.card_congr (Additive.toMul),
    Nat.card_congr (class_group_equiv).symm.toEquiv, Nat.card_pi]
  simp [Fin.isValue, Fin.prod_succ]
  try decide
