import IdealArithmetic.Examples.SmallDisc.NonPrincipalExampleSmallDisc
import Mathlib.NumberTheory.NumberField.ClassNumber
import IdealArithmetic.ResultantRecursive
import IdealArithmetic.DiscriminantSubalgebraBuilder
import IdealArithmetic.Examples.SmallDisc.RelationsIdeals

/- Number field `K(α)` with with α root of polynomial `X^5 + 20*X - 16`.
Class number `3`, generated by class of ideal `J = (2, 1/4*a^3 + 1/2*a + 1)`. We have `J ^ 3` is principal. -/

/- Ring of integers with basis `[1, a, 1/2*a^2, 1/4*a^3 - 1/2*a, 1/4*a^4]` -/

open BigOperators Classical Matrix Polynomial

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible

noncomputable instance K_field : Field K := by
  unfold K
  infer_instance

instance K_numberField : NumberField K := by
  unfold K
  infer_instance

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  rw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, T_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ [2]
  · fin_cases hc
    exact pMaximal_of_MaximalOrderCertificateWLists 2 O Om hm M2
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [2] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']


theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by rw [O_integral_closure] ; rfl


instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K


def SturmRC : SturmBuilderOfList [[-16, 20, 0, 0, 0, 1], [20, 0, 0, 0, 5], [400, -400], [-1024000000]] [-16, 20, 0, 0, 0, 1] [20, 0, 0, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 3 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 25600000000]
  f := [1, 625]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [-320000000, -320000000, -320000000, -320000000]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 2 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 + 20*X - 16
  l := [-16, 20, 0, 0, 0, 1]
  hl := T_ofList
  hlz := by decide
  hz := by decide
  hAdj := Adj
  heq := O_integral_closure
  P := [[-16, 20, 0, 0, 0, 1], [20, 0, 0, 0, 5], [400, -400], [-1024000000]]
  SB := SturmRC
  k := 1
  r := 3
  hr := by decide
  hreq := by decide

lemma ne_dvd_torsion3 : ¬3 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
 suffices ¬ 3 ∣ 2 from ?_
 · convert this
   rw [O_integral_closure, ← Fintype.card_eq_nat_card,
   ←  NumberField.Units.torsionOrder_eq_two_of_odd_finrank (by rw [K_finrank] ; decide)]
   rfl
 · decide

def NPCJ : NonPrincipalCertificateNDvdT J where
 p := 3
 hp := by decide
 r := 2
 huc := by
  rw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2]
 hu := fun i =>
  match i with
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
 q := ![7, 7, 37]
 hqP := by
  intro i
  match i with
  | 0 => exact hq7
  | 1 => exact hq7
  | 2 => exact hq37
 I := ![I0, I1, I2]
 hcard := fun i =>
  match i with
  | 0 => N0
  | 1 => N1
  | 2 => N2
 ζ := ![3, 3, 2]
 hr := fun i =>
  match i with
  | 0 => ((orderOf_of_IsOrderOf R7) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf R7) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf R37) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 a := alpha
 n := 3
 hpdvd := by decide
 hJ := J3
 hpndvdt := ne_dvd_torsion3
 M := ![![2, 0, 0], ![2, 1, 0], ![0, 0, 1]]
 hM1 := by
  intro j i hj
  fin_cases i <;> interval_cases j
  · erw [eq_of_DiscreteLogCertificate Log00] ; decide
  · erw [eq_of_DiscreteLogCertificate Log01] ; decide
  · erw [eq_of_DiscreteLogCertificate Log10] ; decide
  · erw [eq_of_DiscreteLogCertificate Log11] ; decide
  · erw [eq_of_DiscreteLogCertificate Log20] ; decide
  · erw [eq_of_DiscreteLogCertificate Log21] ; decide
 hM2 := by
  intro i
  match i with
  | 0 => exact Log02
  | 1 => exact Log12
  | 2 => exact Log22
 hDl := by decide
 Minv := ![![2, 0, 0], ![2, 1, 0], ![0, 0, 1]]
 hInv := by decide
 N := ![![2, 0], ![2, 1]]
 hNiv := by decide

theorem J_not_principal : ¬ ∃ b, J = Ideal.span {b} :=
  not_principal_of_NonPrincipalCertificateNDvdT NPCJ


theorem T_discr : discriminant T = 1024000000 := by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  rw [T_ofList]

theorem K_discr : NumberField.discr K = 1000000 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl

lemma K_nrComplexPlaces : NumberField.InfinitePlace.nrComplexPlaces K = 2 := by
  rw [nrComplexPlaces_of_RankUnitsCertificate RC]
  rfl


theorem K_minowski :
  (4 / Real.pi) ^ NumberField.InfinitePlace.nrComplexPlaces K *
          (↑(Module.finrank ℚ K).factorial / ↑(Module.finrank ℚ K) ^ Module.finrank ℚ K * √|↑(NumberField.discr K)|) ≤ (62.2518 : ℝ) := by
  rw [K_nrComplexPlaces, K_discr, K_finrank]
  norm_num
  have := Real.pi_gt_d20
  have : (4 / Real.pi) ^ 2 < (4 / 3.14159265358979323846) ^ 2 := by
    refine (sq_lt_sq₀ ?_ ?_).mpr ?_
    · refine div_nonneg (by norm_num) (by exact Real.pi_nonneg)
    · refine div_nonneg (by norm_num) (by norm_num)
    · refine div_lt_div_of_pos_left (by norm_num) (by norm_num) this
  nlinarith

--instance DD : IsDedekindDomainInv O := by
--  rw [← isDedekindDomain_iff_isDedekindDomainInv, O_integral_closure]
-- exact integralClosure.isDedekindDomain ℤ ℚ K

instance DD' : IsDedekindDomain O  := by
  rw [O_integral_closure]
  exact integralClosure.isDedekindDomain ℤ ℚ K

instance : Module.Free ℤ ↥O := Module.Free.of_basis B -- Remove from assumptions in theorem?


def g := ![I43N1, I43N2, I41N1, I41N2, I37N2, I29N1, I29N2, I23N2, I17N1, I17N2, I11N1, I11N2, I7N1, I7N2, I5N, I2N0,I2N1]



lemma primesGenerationBelow :
  {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < 63} ⊆ Set.range g := by
  sorry
/-
lemma le_primes_below_bound_of_PrimesBelowBoundCertificate' {O : Subalgebra ℤ K}
    [IsDedekindDomain ↥O] [Module.Free ℤ ↥O]  {B r : ℕ} (φ : O ≃+* Oκ) (g : Fin r → Ideal O)
    (A : PrimesBelowBoundCertificate O B)
    (h : List.flatten (List.ofFn A.Il) ⊆ List.ofFn g) :
    {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < B} ⊆ Set.range g := by

-/
