import IdealArithmetic.Examples.SmallDisc.NonPrincipalExampleSmallDisc
import Mathlib.NumberTheory.NumberField.ClassNumber
import IdealArithmetic.ResultantRecursive
import IdealArithmetic.DiscriminantSubalgebraBuilder
import IdealArithmetic.Examples.SmallDisc.RelationsIdeals

/- Number field `K(α)` with with α root of polynomial `X^5 + 20*X - 16`.
Class number `3`, generated by class of ideal `J = (2, 1/4*a^3 + 1/2*a + 1)`. We have `J ^ 3` is principal. -/

/- Ring of integers with basis `[1, a, 1/2*a^2, 1/4*a^3 - 1/2*a, 1/4*a^4]` -/

open BigOperators Classical Matrix Polynomial

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible

noncomputable instance K_field : Field K := by
  unfold K
  infer_instance

instance K_numberField : NumberField K := by
  unfold K
  infer_instance

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  rw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, T_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ [2]
  · fin_cases hc
    exact pMaximal_of_MaximalOrderCertificateWLists 2 O Om hm M2
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [2] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']


theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by rw [O_integral_closure] ; rfl


instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K


def SturmRC : SturmBuilderOfList [[-16, 20, 0, 0, 0, 1], [20, 0, 0, 0, 5], [400, -400], [-1024000000]] [-16, 20, 0, 0, 0, 1] [20, 0, 0, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 3 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 25600000000]
  f := [1, 625]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [-320000000, -320000000, -320000000, -320000000]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 2 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 + 20*X - 16
  l := [-16, 20, 0, 0, 0, 1]
  hl := T_ofList
  hlz := by decide
  hz := by decide
  hAdj := Adj
  heq := O_integral_closure
  P := [[-16, 20, 0, 0, 0, 1], [20, 0, 0, 0, 5], [400, -400], [-1024000000]]
  SB := SturmRC
  k := 1
  r := 3
  hr := by decide
  hreq := by decide

lemma ne_dvd_torsion3 : ¬3 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
 suffices ¬ 3 ∣ 2 from ?_
 · convert this
   rw [O_integral_closure, ← Fintype.card_eq_nat_card,
   ←  NumberField.Units.torsionOrder_eq_two_of_odd_finrank (by rw [K_finrank] ; decide)]
   rfl
 · decide

def NPCJ : NonPrincipalCertificateNDvdT J where
 p := 3
 hp := by decide
 r := 2
 huc := by
  rw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2]
 hu := fun i =>
  match i with
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
 q := ![7, 7, 37]
 hqP := by
  intro i
  match i with
  | 0 => exact hq7
  | 1 => exact hq7
  | 2 => exact hq37
 I := ![I0, I1, I2]
 hcard := fun i =>
  match i with
  | 0 => N0
  | 1 => N1
  | 2 => N2
 ζ := ![3, 3, 2]
 hr := fun i =>
  match i with
  | 0 => ((orderOf_of_IsOrderOf R7) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf R7) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf R37) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 a := alpha
 n := 3
 hpdvd := by decide
 hJ := J3
 hpndvdt := ne_dvd_torsion3
 M := ![![2, 0, 0], ![2, 1, 0], ![0, 0, 1]]
 hM1 := by
  intro j i hj
  fin_cases i <;> interval_cases j
  · erw [eq_of_DiscreteLogCertificate Log00] ; decide
  · erw [eq_of_DiscreteLogCertificate Log01] ; decide
  · erw [eq_of_DiscreteLogCertificate Log10] ; decide
  · erw [eq_of_DiscreteLogCertificate Log11] ; decide
  · erw [eq_of_DiscreteLogCertificate Log20] ; decide
  · erw [eq_of_DiscreteLogCertificate Log21] ; decide
 hM2 := by
  intro i
  match i with
  | 0 => exact Log02
  | 1 => exact Log12
  | 2 => exact Log22
 hDl := by decide
 Minv := ![![2, 0, 0], ![2, 1, 0], ![0, 0, 1]]
 hInv := by decide
 N := ![![2, 0], ![2, 1]]
 hNiv := by decide

theorem J_not_principal : ¬ ∃ b, J = Ideal.span {b} :=
  not_principal_of_NonPrincipalCertificateNDvdT NPCJ

theorem T_discr : discriminant T = 1024000000 := by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  rw [T_ofList]

theorem K_discr : NumberField.discr K = 1000000 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl

lemma K_nrComplexPlaces : NumberField.InfinitePlace.nrComplexPlaces K = 2 := by
  rw [nrComplexPlaces_of_RankUnitsCertificate RC]
  rfl

theorem K_minkowski_decimal {F : Type*} [Field F] [NumberField F] (r : ℝ)
    (h : (4 / 3.14159265358979323846 : ℝ) ^ NumberField.InfinitePlace.nrComplexPlaces F
    * (↑(Module.finrank ℚ F).factorial / ↑(Module.finrank ℚ F) ^ Module.finrank ℚ F * √|↑(NumberField.discr F)|) ≤ r) :
    MinkowskiBound F ≤ r  := by
  unfold MinkowskiBound
  have := Real.pi_gt_d20
  have : (4 / Real.pi) ^ (NumberField.InfinitePlace.nrComplexPlaces F) ≤
    (4 / 3.14159265358979323846) ^ (NumberField.InfinitePlace.nrComplexPlaces F) := by
    refine pow_le_pow_left₀ ?_ ?_ _
    · refine div_nonneg (by norm_num) (by exact Real.pi_nonneg)
    · refine le_of_lt ?_
      refine div_lt_div_of_pos_left (by norm_num) (by norm_num) this
  refine le_trans ?_ h
  refine mul_le_mul_of_nonneg_right this ?_
  refine mul_nonneg ?_ ?_
  · refine div_nonneg ?_ ?_
    · simp only [Nat.cast_nonneg]
    · simp only [Nat.cast_nonneg, pow_nonneg]
  · simp only [Real.sqrt_nonneg]


theorem K_minowski :
  MinkowskiBound K ≤ (62.2518 : ℝ) := by
  refine K_minkowski_decimal _ ?_
  rw [K_nrComplexPlaces, K_discr, K_finrank]
  norm_num

--instance DD : IsDedekindDomainInv O := by
--  rw [← isDedekindDomain_iff_isDedekindDomainInv, O_integral_closure]
-- exact integralClosure.isDedekindDomain ℤ ℚ K

instance DD' : IsDedekindDomain O  := by
  rw [O_integral_closure]
  exact integralClosure.isDedekindDomain ℤ ℚ K

instance : Module.Free ℤ ↥O := Module.Free.of_basis B -- Remove from assumptions in theorem?


def g : Fin 17 → Ideal O := ![I43N1, I43N2, I41N1, I41N2, I37N2, I29N1, I29N2, I23N2, I17N1, I17N2, I11N1, I11N2, I7N1, I7N2, I5N, I2N0,I2N1]

-- We cannot just dedup the list, because comparison between ideals is not decidable.
lemma primesGenerationBelowAux {x} : x ∈ (List.ofFn PB17.Il).flatten ↔ x ∈ List.ofFn g := by
  unfold g
  have h1: (List.ofFn PB17.Il).flatten = [I43N1, I43N2, I41N1, I41N2, I37N2, I29N1, I29N2, I23N2, I17N1, I17N2, I11N1, I11N2, I7N1,
    I7N2, I5N, I5N, I5N, I5N, I5N, I2N0,I2N1, I2N1, I2N1, I2N1] := by rfl
  have h2: List.ofFn ![I43N1, I43N2, I41N1, I41N2, I37N2, I29N1, I29N2, I23N2, I17N1, I17N2, I11N1, I11N2, I7N1, I7N2, I5N, I2N0, I2N1] =
    [I43N1, I43N2, I41N1, I41N2, I37N2, I29N1, I29N2, I23N2, I17N1, I17N2, I11N1, I11N2, I7N1, I7N2, I5N, I2N0, I2N1] := by rfl
  rw [h1, h2]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]


-- To do: Note : Need to find a better way to compare lists
lemma primesGenerationBelow :
  {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < 63} ⊆ Set.range g := by
refine le_primes_below_bound_of_PrimesBelowBoundCertificate' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv g PB17 ?_
intro x hx
exact primesGenerationBelowAux.1 hx


--Matrxix describing relations between elements in g and J
def BM : Matrix (Fin 17) (Fin 1) ℕ := !![2; 1; 1; 2; 0; 2; 1; 0 ; 1; 2 ; 2 ; 1 ; 1; 2; 0 ; 2; 1]


def g' : Fin 17 → nonZeroDivisors (Ideal O) := by
  intro i
  refine Ideal.toNonZeroDivisorOfNeZero (g i) ?_
  have : g i ∈ (List.ofFn PB17.Il).flatten := by
    rw [primesGenerationBelowAux, List.mem_ofFn]
    use i
  intro hc
  rw [hc] at this
  exact (zero_ne_mem_of_PrimesBelowCertificate 63 PB17) this


def x : Fin 1 → Ideal O := ![J]

def x' : Fin 1 → nonZeroDivisors (Ideal O) := fun _ => g' (16)


lemma g'_apply : ∀ (i : Fin 17), ↑(g' i) = g i := by
  intro i
  rfl

lemma x'_apply : ∀ (i : Fin 1), ↑(x' i) = x i := by
  intro i
  rw [Fin.fin_one_eq_zero i]
  rfl





-- Remove extra variable r
-- To do : change ideal_mem_principal_class so that it matches this
theorem class_group_generator :
  Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (x' i))) = ⊤ := by

refine subgroup_closure_eq_classGroup'' (r := Fin 1) (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv
  g'_apply x'_apply ?_ primesGenerationBelow BM ?_
· refine lt_of_le_of_lt K_minowski ?_
  norm_num
· simp only [Finset.univ_unique, Fin.default_eq_zero, Fin.isValue, Finset.prod_singleton]
  intro i
  fin_cases i
  · use 2 , (B.equivFun.symm ![2, 0, 1, 0, 1]), (two_ne_zero) ,
      ((LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide))
    exact R43N1
  · use 2, B.equivFun.symm ![2, -1, 1, 0, 1], (two_ne_zero),
      ((LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide))
    exact R43N2
  · use 2, B.equivFun.symm ![6, 1, 1, 2, 1], (two_ne_zero),
      ((LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide))
    exact R41N1
  · use 2, B.equivFun.symm ![6, 0, 1, 0, 1], (two_ne_zero),
      ((LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide))
    exact R41N2
  · exact ideal_mem_principal_class' O ℤ B I37N2 ![1, 1, 0, 0, 0] (by decide) rfl
  · use 2, B.equivFun.symm ![6, 0, -1, 0, 1], two_ne_zero,
      ((LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide))
    exact R29N1
  · use 2, B.equivFun.symm ![2, 1, -1, 0, 1], two_ne_zero,
      ((LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide))
    exact R29N2
  · exact ideal_mem_principal_class' O ℤ B I23N2 ![3, 0, 0, 1, 1] (by decide) rfl
  · use 2, B.equivFun.symm ![-2, 1, 1, 0, -1], two_ne_zero,
      ((LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide))
    exact R17N1
  · use 2, B.equivFun.symm ![10, 1, 0, 2, 2], two_ne_zero,
      ((LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide))
    exact R17N2
  · use 2, B.equivFun.symm ![2, 1, 0, 0, 0], two_ne_zero,
      ((LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide))
    exact R11N1
  · use 2, B.equivFun.symm ![6, -1, -1, 0, 1], two_ne_zero,
      ((LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide))
    exact R11N2
  · use 2, B.equivFun.symm ![2, 1, 1, 2, 1], two_ne_zero,
      ((LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide))
    exact R7N1
  · use 2, B.equivFun.symm ![2, -1, 0, 0, 0], two_ne_zero,
      ((LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide))
    exact R7N2
  · exact ideal_mem_principal_class' O ℤ B I5N ![1, -1, 0, 0, 0] (by decide) rfl
  · use 2, B.equivFun.symm ![0, 1, 0, 0, 0], two_ne_zero,
      ((LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide))
    exact R2N0
  · use 1, 1, one_ne_zero, one_ne_zero
    exact R2N1


def class_group_O_equiv_ZMod3 : ZMod 3 ≃+ Additive (ClassGroup O) := by
  refine equivClassGroupCyclicOfSaturated (I := J) (I' := x' 0) (rfl) J3 ?_ ?_
  exact class_group_generator
  intro p hp hpdvd
  have : p = 3 := by
    rw [← prime_dvd_prime_iff_eq (Nat.prime_iff.mp hp)]
    exact hpdvd
    exact Nat.prime_iff.mp Nat.prime_three
  simp only [this, Nat.ofNat_pos, Nat.div_self, pow_one]
  exact J_not_principal

def class_group_equiv_ZMod3 : ZMod 3 ≃+ Additive (ClassGroup (NumberField.RingOfIntegers K)) := by
  refine AddEquiv.trans class_group_O_equiv_ZMod3 ?_
  exact MulEquiv.toAdditive (ClassGroup.congr
    ((Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv))


theorem class_number_K_eq_3 : NumberField.classNumber K = 3 := by
  unfold NumberField.classNumber
  rw [Fintype.card_eq_nat_card, ← Nat.card_congr (Additive.toMul),
    Nat.card_congr (class_group_equiv_ZMod3).symm.toEquiv]
  simp only [Nat.card_eq_fintype_card, ZMod.card]




#print axioms class_number_K_eq_3













/- def Ideal.toNonZeroDivisorOfNormPos {R : Type} [CommRing R] [IsDomain R]
  (I : Ideal R) (hp : Nat.card (R ⧸ I) > 0) : nonZeroDivisors (Ideal R) := by
  refine ⟨I, ?_⟩
  simp only [mem_nonZeroDivisors_iff_ne_zero, Submodule.zero_eq_bot, ne_eq]
  intro hc
  rw [hc, Nat.card_congr (RingEquiv.quotientBot R).toEquiv] at hp -/
