import IdealArithmetic.Saturation.PrincipalityCertificate
import IdealArithmetic.Examples.NF5_3_3037500000_1.PrimesBelowCert5_3_3037500000_1
import Mathlib.NumberTheory.NumberField.ClassNumber
import IdealArithmetic.Signature.ResultantRecursive
import IdealArithmetic.DedekindProject.Discriminant
import IdealArithmetic.Generation.ClassGroupGeneration

set_option linter.all false

/- Number field `K(α)` with α root of polynomial `X^5 - 60*X^3 - 330*X^2 - 765*X - 666`.
Class group structure `[]`, generated by class of ideals `[]`. -/

/- Ring of integers with basis `[1, a, a^2, 1/6*a^3 - 1/2*a, 1/12*a^4 - 1/12*a^3 + 1/4*a^2 + 1/4*a - 1/2]` -/

open BigOperators Classical Matrix Polynomial Module

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible

instance K_field : Field K := by
  unfold K
  exact AdjoinRoot.instField

instance K_numberField : NumberField K := by
  unfold K
  exact AdjoinRoot.instNumberFieldRat

instance : Module ℚ K := Algebra.toModule
instance : @Algebra ℤ K CommRing.toCommSemiring CommRing.toCommSemiring.toSemiring := Ring.toIntAlgebra K
instance : @CharZero K CommRing.toCommSemiring.toNonAssocSemiring.toAddCommMonoidWithOne.toAddMonoidWithOne := charZero_of_expChar_one' K

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  erw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, T_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ [2, 3]
  · fin_cases hc
    exact @pMaximal_of_MaximalOrderCertificateWLists K 2 _ IsAddTorsionFree.to_noZeroSMulDivisors_int _ O Om hm _ _ M2
    exact @pMaximal_of_MaximalOrderCertificateWLists K 3 _ IsAddTorsionFree.to_noZeroSMulDivisors_int _ O Om hm _ _ M3
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [2, 3] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']

theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by rw [O_integral_closure] ; rfl

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance DD' : IsDedekindDomain O  := by
  rw [O_integral_closure]
  exact integralClosure.isDedekindDomain ℤ ℚ K

instance : Module.Free ℤ ↥O := Module.Free.of_basis B

instance  : IdemCommSemiring (Ideal O) := Ideal.instIdemCommSemiring
instance : CharZero O := SubsemiringClass.instCharZero O

def SturmRC : SturmBuilderOfList [[-666, -765, -330, -60, 0, 1], [-765, -660, -180, 0, 5], [16650, 15300, 4950, 600], [-5467500, -3645000, -472500], [-8019000000, -3645000000], [-15746400000000]] [-666, -765, -330, -60, 0, 1] [-765, -660, -180, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 5 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 360000, 223256250000, 13286025000000000000]
  f := [1, 25, 360000, 223256250000]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [-24750, 3000], [-151875000, -283500000], [9497047500000000, 1722262500000000]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 - 60*X^3 - 330*X^2 - 765*X - 666
  l := [-666, -765, -330, -60, 0, 1]
  hl := T_ofList
  hlz := by decide
  hz := by decide
  hAdj := Adj
  heq := O_integral_closure
  P := [[-666, -765, -330, -60, 0, 1], [-765, -660, -180, 0, 5], [16650, 15300, 4950, 600], [-5467500, -3645000, -472500], [-8019000000, -3645000000], [-15746400000000]]
  SB := SturmRC
  k := 3
  r := 4
  hr := by decide
  hreq := by decide 


lemma T_discr : T.discr = -15746400000000 :=  by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  rw [T_ofList]

theorem K_discr : NumberField.discr K = -3037500000 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl

lemma K_nrComplexPlaces : NumberField.InfinitePlace.nrComplexPlaces K = 1 := by
  rw [nrComplexPlaces_of_RankUnitsCertificate RC]
  rfl

lemma K_nrRealPlaces : NumberField.InfinitePlace.nrRealPlaces K = 3 := by
  rw [nrRealPlaces_of_RankUnitsCertificate RC]
  rfl

theorem K_minowski : minkowskiBoundFB K ≤ (2694.642145063585 : ℝ) := by
  refine K_minkowski_decimal _ ?_
  erw [K_nrComplexPlaces, K_discr, K_finrank]
  have hraux: √3037500000 ≤ 55113.519223 := by
      refine Real.sqrt_le_iff.mpr ?_
      norm_num
  have : 0.0384 * √3037500000 ≤ 2116.369138 := by
    refine le_trans (mul_le_mul_of_nonneg (by rfl) hraux (by norm_num) (by norm_num)) ?_
    norm_num
  norm_num
  try {linarith}

def s := ![9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 5]

def BM : (i : Fin 44) → Fin (e i) → (Fin 1 → ℕ) := by 
  rintro ⟨i, hi⟩ 
  interval_cases i 
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0]]

lemma primesGenerationBelow : {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < 2695} ⊆ Set.range (Fin.addCasesIter e 𝔭) := by
  rw [← cert_eq_𝔭]
  refine le_primes_below_bound_of_PrimesBelowBoundCertificate_le_of_eq (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv PB2695

def 𝔭' : Fin 399 → nonZeroDivisors (Ideal O) := by
  intro i
  have : PB2695.β i ∈ List.ofFn PB2695.β := by
    simp only [List.mem_ofFn, exists_apply_eq_apply]
  refine Ideal.toNonZeroDivisorOfNeZero ((PB2695.β) i)
    (fun hc => ((zero_ne_mem_of_PrimesBelowCertificate_Fn _ PB2695) (hc ▸ this) ))

def J : Fin 1 → Ideal O := ![⊤]

def J' :  Fin 1 → nonZeroDivisors (Ideal O) := by
  refine fun i => Ideal.toNonZeroDivisorOfNeZero (J i) (?_ )
  unfold J
  simp 

lemma 𝔭'_apply : ∀ (i : Fin 399), ↑(𝔭' i) = (Fin.addCasesIter e 𝔭) i := by
  intro i
  rw [← cert_eq_𝔭]
  rfl

lemma J'_apply : ∀ (i : Fin 1), ↑(J' i) = J i := by
  intro i
  rfl

lemma relations_proof0 (i : Fin 16) : IsInClass O J (𝔭 0 i) (BM 0 i) := by
  show IsInClass O J (𝔭 0 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof1 (i : Fin 14) : IsInClass O J (𝔭 1 i) (BM 1 i) := by
  show IsInClass O J (𝔭 1 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof2 (i : Fin 2) : IsInClass O J (𝔭 2 i) (BM 2 i) := by
  show IsInClass O J (𝔭 2 i) (![![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof3 (i : Fin 8) : IsInClass O J (𝔭 3 i) (BM 3 i) := by
  show IsInClass O J (𝔭 3 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof4 (i : Fin 5) : IsInClass O J (𝔭 4 i) (BM 4 i) := by
  show IsInClass O J (𝔭 4 i) (![![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof5 (i : Fin 8) : IsInClass O J (𝔭 5 i) (BM 5 i) := by
  show IsInClass O J (𝔭 5 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof6 (i : Fin 11) : IsInClass O J (𝔭 6 i) (BM 6 i) := by
  show IsInClass O J (𝔭 6 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof7 (i : Fin 9) : IsInClass O J (𝔭 7 i) (BM 7 i) := by
  show IsInClass O J (𝔭 7 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof8 (i : Fin 8) : IsInClass O J (𝔭 8 i) (BM 8 i) := by
  show IsInClass O J (𝔭 8 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof9 (i : Fin 4) : IsInClass O J (𝔭 9 i) (BM 9 i) := by
  show IsInClass O J (𝔭 9 i) (![![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof10 (i : Fin 10) : IsInClass O J (𝔭 10 i) (BM 10 i) := by
  show IsInClass O J (𝔭 10 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof11 (i : Fin 11) : IsInClass O J (𝔭 11 i) (BM 11 i) := by
  show IsInClass O J (𝔭 11 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof12 (i : Fin 6) : IsInClass O J (𝔭 12 i) (BM 12 i) := by
  show IsInClass O J (𝔭 12 i) (![![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof13 (i : Fin 11) : IsInClass O J (𝔭 13 i) (BM 13 i) := by
  show IsInClass O J (𝔭 13 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof14 (i : Fin 11) : IsInClass O J (𝔭 14 i) (BM 14 i) := by
  show IsInClass O J (𝔭 14 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof15 (i : Fin 7) : IsInClass O J (𝔭 15 i) (BM 15 i) := by
  show IsInClass O J (𝔭 15 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof16 (i : Fin 9) : IsInClass O J (𝔭 16 i) (BM 16 i) := by
  show IsInClass O J (𝔭 16 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof17 (i : Fin 8) : IsInClass O J (𝔭 17 i) (BM 17 i) := by
  show IsInClass O J (𝔭 17 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof18 (i : Fin 13) : IsInClass O J (𝔭 18 i) (BM 18 i) := by
  show IsInClass O J (𝔭 18 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof19 (i : Fin 7) : IsInClass O J (𝔭 19 i) (BM 19 i) := by
  show IsInClass O J (𝔭 19 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof20 (i : Fin 11) : IsInClass O J (𝔭 20 i) (BM 20 i) := by
  show IsInClass O J (𝔭 20 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof21 (i : Fin 8) : IsInClass O J (𝔭 21 i) (BM 21 i) := by
  show IsInClass O J (𝔭 21 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof22 (i : Fin 2) : IsInClass O J (𝔭 22 i) (BM 22 i) := by
  show IsInClass O J (𝔭 22 i) (![![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof23 (i : Fin 6) : IsInClass O J (𝔭 23 i) (BM 23 i) := by
  show IsInClass O J (𝔭 23 i) (![![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof24 (i : Fin 12) : IsInClass O J (𝔭 24 i) (BM 24 i) := by
  show IsInClass O J (𝔭 24 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof25 (i : Fin 6) : IsInClass O J (𝔭 25 i) (BM 25 i) := by
  show IsInClass O J (𝔭 25 i) (![![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof26 (i : Fin 10) : IsInClass O J (𝔭 26 i) (BM 26 i) := by
  show IsInClass O J (𝔭 26 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof27 (i : Fin 3) : IsInClass O J (𝔭 27 i) (BM 27 i) := by
  show IsInClass O J (𝔭 27 i) (![![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof28 (i : Fin 12) : IsInClass O J (𝔭 28 i) (BM 28 i) := by
  show IsInClass O J (𝔭 28 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof29 (i : Fin 7) : IsInClass O J (𝔭 29 i) (BM 29 i) := by
  show IsInClass O J (𝔭 29 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof30 (i : Fin 4) : IsInClass O J (𝔭 30 i) (BM 30 i) := by
  show IsInClass O J (𝔭 30 i) (![![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof31 (i : Fin 19) : IsInClass O J (𝔭 31 i) (BM 31 i) := by
  show IsInClass O J (𝔭 31 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof32 (i : Fin 6) : IsInClass O J (𝔭 32 i) (BM 32 i) := by
  show IsInClass O J (𝔭 32 i) (![![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof33 (i : Fin 2) : IsInClass O J (𝔭 33 i) (BM 33 i) := by
  show IsInClass O J (𝔭 33 i) (![![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof34 (i : Fin 14) : IsInClass O J (𝔭 34 i) (BM 34 i) := by
  show IsInClass O J (𝔭 34 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof35 (i : Fin 17) : IsInClass O J (𝔭 35 i) (BM 35 i) := by
  show IsInClass O J (𝔭 35 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof36 (i : Fin 16) : IsInClass O J (𝔭 36 i) (BM 36 i) := by
  show IsInClass O J (𝔭 36 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof37 (i : Fin 11) : IsInClass O J (𝔭 37 i) (BM 37 i) := by
  show IsInClass O J (𝔭 37 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof38 (i : Fin 13) : IsInClass O J (𝔭 38 i) (BM 38 i) := by
  show IsInClass O J (𝔭 38 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof39 (i : Fin 13) : IsInClass O J (𝔭 39 i) (BM 39 i) := by
  show IsInClass O J (𝔭 39 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof40 (i : Fin 11) : IsInClass O J (𝔭 40 i) (BM 40 i) := by
  show IsInClass O J (𝔭 40 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof41 (i : Fin 6) : IsInClass O J (𝔭 41 i) (BM 41 i) := by
  show IsInClass O J (𝔭 41 i) (![![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof42 (i : Fin 8) : IsInClass O J (𝔭 42 i) (BM 42 i) := by
  show IsInClass O J (𝔭 42 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof43 (i : Fin 4) : IsInClass O J (𝔭 43 i) (BM 43 i) := by
  show IsInClass O J (𝔭 43 i) (![![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

theorem class_group_generator : Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (J' i))) = ⊤ := by
  refine subgroup_closure_eq_classGroup'' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv
      𝔭'_apply J'_apply ?_ primesGenerationBelow (Fin.addCasesIter e BM) ?_
  · refine lt_of_le_of_lt K_minowski ?_
    norm_num
  · refine forall_addCasesIter_prop 𝔭 BM (IsInClass O J) ?_
    rintro ⟨i, hi⟩
    interval_cases i
    · exact relations_proof0
    · exact relations_proof1
    · exact relations_proof2
    · exact relations_proof3
    · exact relations_proof4
    · exact relations_proof5
    · exact relations_proof6
    · exact relations_proof7
    · exact relations_proof8
    · exact relations_proof9
    · exact relations_proof10
    · exact relations_proof11
    · exact relations_proof12
    · exact relations_proof13
    · exact relations_proof14
    · exact relations_proof15
    · exact relations_proof16
    · exact relations_proof17
    · exact relations_proof18
    · exact relations_proof19
    · exact relations_proof20
    · exact relations_proof21
    · exact relations_proof22
    · exact relations_proof23
    · exact relations_proof24
    · exact relations_proof25
    · exact relations_proof26
    · exact relations_proof27
    · exact relations_proof28
    · exact relations_proof29
    · exact relations_proof30
    · exact relations_proof31
    · exact relations_proof32
    · exact relations_proof33
    · exact relations_proof34
    · exact relations_proof35
    · exact relations_proof36
    · exact relations_proof37
    · exact relations_proof38
    · exact relations_proof39
    · exact relations_proof40
    · exact relations_proof41
    · exact relations_proof42
    · exact relations_proof43

def ClassGroupO_equiv : (∀ i : Fin 1 , (ZMod (![1] i))) ≃+ Additive (ClassGroup O) := by
  haveI : ∀ (i : Fin 1), NeZero (![1] i) := by
    intro i
    fin_cases i <;>  exact {out := by decide}
  refine ClassGroup_equiv_of_pSaturatedCertificate J'_apply (a := ![1]) (n := ![1])
    (by simp [J]; exact Eq.symm Ideal.span_singleton_one) class_group_generator ?_
  rintro ⟨p, hp1, hp2⟩
  simp at hp2
  exact (Nat.Prime.ne_one hp1 hp2).elim

def class_group_equiv : (∀ i : Fin 1 , (ZMod (![1] i))) ≃+ Additive (ClassGroup (NumberField.RingOfIntegers K)) := by
 refine AddEquiv.trans ClassGroupO_equiv ?_
 exact MulEquiv.toAdditive (ClassGroup.congr
    ((Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv))

theorem class_number_K_eq_1 : NumberField.classNumber K = 1 := by
  unfold NumberField.classNumber
  rw [Fintype.card_eq_nat_card, ← Nat.card_congr (Additive.toMul),
    Nat.card_congr (class_group_equiv).symm.toEquiv, Nat.card_pi]
  simp [Fin.isValue, Fin.prod_succ]
  try decide
