import IdealArithmetic.Examples.NF5_1_421875000_2.ClassGroupSaturated5_1_421875000_2_3
import IdealArithmetic.Examples.NF5_1_421875000_2.RelationIdeals5_1_421875000_2F0
import IdealArithmetic.Examples.NF5_1_421875000_2.RelationIdeals5_1_421875000_2F1
import IdealArithmetic.Examples.NF5_1_421875000_2.RelationIdeals5_1_421875000_2F2
import IdealArithmetic.Examples.NF5_1_421875000_2.RelationIdeals5_1_421875000_2F3
import IdealArithmetic.Examples.NF5_1_421875000_2.RelationIdeals5_1_421875000_2F4
import IdealArithmetic.Examples.NF5_1_421875000_2.RelationIdeals5_1_421875000_2F5
import IdealArithmetic.Examples.NF5_1_421875000_2.RelationIdeals5_1_421875000_2F6
import IdealArithmetic.Examples.NF5_1_421875000_2.RelationIdeals5_1_421875000_2F7
import IdealArithmetic.Examples.NF5_1_421875000_2.RelationIdeals5_1_421875000_2F8
import IdealArithmetic.Examples.NF5_1_421875000_2.RelationIdeals5_1_421875000_2F9
import IdealArithmetic.Examples.NF5_1_421875000_2.RelationIdeals5_1_421875000_2F10
import IdealArithmetic.Examples.NF5_1_421875000_2.RelationIdeals5_1_421875000_2F11
import IdealArithmetic.Examples.NF5_1_421875000_2.RelationIdeals5_1_421875000_2F12
import IdealArithmetic.Examples.NF5_1_421875000_2.RelationIdeals5_1_421875000_2F13
import IdealArithmetic.Examples.NF5_1_421875000_2.RelationIdeals5_1_421875000_2F14
import IdealArithmetic.Examples.NF5_1_421875000_2.RelationIdeals5_1_421875000_2F15
import IdealArithmetic.Examples.NF5_1_421875000_2.RelationIdeals5_1_421875000_2F16
import IdealArithmetic.Examples.NF5_1_421875000_2.RelationIdeals5_1_421875000_2F17
import IdealArithmetic.Examples.NF5_1_421875000_2.RelationIdeals5_1_421875000_2F18
import IdealArithmetic.Examples.NF5_1_421875000_2.RelationIdeals5_1_421875000_2F19
import IdealArithmetic.Examples.NF5_1_421875000_2.RelationIdeals5_1_421875000_2F20
import IdealArithmetic.Examples.NF5_1_421875000_2.RelationIdeals5_1_421875000_2F21
import IdealArithmetic.Examples.NF5_1_421875000_2.RelationIdeals5_1_421875000_2F22
import IdealArithmetic.Examples.NF5_1_421875000_2.PrimesBelowCert5_1_421875000_2
import Mathlib.NumberTheory.NumberField.ClassNumber
import IdealArithmetic.Signature.ResultantRecursive
import IdealArithmetic.DedekindProject.Discriminant
import IdealArithmetic.Generation.ClassGroupGeneration

set_option linter.all false

/- Number field `K(α)` with α root of polynomial `X^5 + 75*X - 180`.
Class group structure `[3]`, generated by class of ideals `[(2, 1/24*a^4 + 1/8*a^3 + 3/8*a^2 + 1/8*a + 7/2)]`. -/

/- Ring of integers with basis `[1, a, a^2, 1/2*a^3 - 1/2*a, 1/48*a^4 - 3/16*a^3 - 5/16*a^2 - 3/16*a + 1/4]` -/

open BigOperators Classical Matrix Polynomial Module

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible

instance K_field : Field K := by
  unfold K
  exact AdjoinRoot.instField

instance K_numberField : NumberField K := by
  unfold K
  exact AdjoinRoot.instNumberFieldRat

instance : Module ℚ K := Algebra.toModule
instance : @Algebra ℤ K CommRing.toCommSemiring CommRing.toCommSemiring.toSemiring := Ring.toIntAlgebra K
instance : @CharZero K CommRing.toCommSemiring.toNonAssocSemiring.toAddCommMonoidWithOne.toAddMonoidWithOne := charZero_of_expChar_one' K

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  erw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, T_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ [2, 3]
  · fin_cases hc
    exact @pMaximal_of_MaximalOrderCertificateWLists K 2 _ IsAddTorsionFree.to_noZeroSMulDivisors_int _ O Om hm _ _ M2
    exact @pMaximal_of_MaximalOrderCertificateWLists K 3 _ IsAddTorsionFree.to_noZeroSMulDivisors_int _ O Om hm _ _ M3
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [2, 3] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']

theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by rw [O_integral_closure] ; rfl

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance DD' : IsDedekindDomain O  := by
  rw [O_integral_closure]
  exact integralClosure.isDedekindDomain ℤ ℚ K

instance : Module.Free ℤ ↥O := Module.Free.of_basis B

instance  : IdemCommSemiring (Ideal O) := Ideal.instIdemCommSemiring
instance : CharZero O := SubsemiringClass.instCharZero O

def SturmRC : SturmBuilderOfList [[-180, 75, 0, 0, 0, 1], [75, 0, 0, 0, 5], [4500, -1500], [-3888000000000]] [-180, 75, 0, 0, 0, 1] [75, 0, 0, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 3 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 5062500000000]
  f := [1, 625]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [-455625000000, -151875000000, -50625000000, -16875000000]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 2 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 + 75*X - 180
  l := [-180, 75, 0, 0, 0, 1]
  hl := T_ofList
  hlz := by decide
  hz := by decide
  hAdj := Adj
  heq := O_integral_closure
  P := [[-180, 75, 0, 0, 0, 1], [75, 0, 0, 0, 5], [4500, -1500], [-3888000000000]]
  SB := SturmRC
  k := 1
  r := 3
  hr := by decide
  hreq := by decide 

lemma ne_dvd_torsion3 : ¬3 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
 suffices ¬ 3 ∣ 2 from ?_
 · convert this
   rw [O_integral_closure, ← Fintype.card_eq_nat_card,
   ←  NumberField.Units.torsionOrder_eq_two_of_odd_finrank (by erw [K_finrank] ; decide)]
   rfl
 · decide

def NPCU3 : pMaximalUnitsCertificateNDvdT O 3 where 
 hp := by decide
 r := 2
 huc := by 
  erw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2]
 hu := fun i => 
  match i with 
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
 t := 3
 hrle := by decide
 q := ![13, 13, 31]
 hqP := by 
  intro i 
  match i with 
  | 0 => exact Sat3.hq13
  | 1 => exact Sat3.hq13
  | 2 => exact Sat3.hq31
 I := ![Sat3.I0, Sat3.I1, Sat3.I2]
 hcard := fun i =>
  match i with  
  | 0 => Sat3.N0
  | 1 => Sat3.N1
  | 2 => Sat3.N2
 ζ := ![2, 2, 3]
 hr := fun i =>
  match i with 
  | 0 => ((orderOf_of_IsOrderOf Sat3.R13) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf Sat3.R13) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf Sat3.R31) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 hpndvdt := ne_dvd_torsion3
 M := ![![1, 2], ![2, 0], ![1, 1]]
 hM1 := by 
  intro i j
  fin_cases i <;> fin_cases j 
  · erw [eq_of_DiscreteLogCertificate Sat3.Log00] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log01] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log10] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log11] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log20] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log21] ; decide
 Minv := ![![0, 2], ![2, 2]] 
 hInv := by decide

def NPSU3 : pSaturatedClassGroupCertificateNDvdT 3 ![J0] ![3] where 
 topMaximalUnitsCertificateNDvdT := NPCU3
 a := ![alpha0]
 γ := 1
 hc := by decide
 ψ := ![0]
 iψ := ![0] 
 hψ := by decide 
 hψn := by 
  intro i 
  fin_cases i 
  · decide
 h := fun i =>
  match i with 
  | 0 => by convert J0_pow3
 N := ![![2], ![0], ![2]]
 hM2 := by 
  intro (i : Fin 3) j
  match i , j with 
  | 0, 0 => exact Sat3.Log02
  | 1, 0 => exact Sat3.Log12
  | 2, 0 => exact Sat3.Log22
 hDl := by decide 
 NInv := ![![0, 2, 0], ![1, 0, 2], ![1, 2, 1]]
 hN := by decide 

lemma T_discr : T.discr = 3888000000000 :=  by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  rw [T_ofList]

theorem K_discr : NumberField.discr K = 421875000 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl

lemma K_nrComplexPlaces : NumberField.InfinitePlace.nrComplexPlaces K = 2 := by
  rw [nrComplexPlaces_of_RankUnitsCertificate RC]
  rfl

lemma K_nrRealPlaces : NumberField.InfinitePlace.nrRealPlaces K = 1 := by
  rw [nrRealPlaces_of_RankUnitsCertificate RC]
  rfl

theorem K_minowski : minkowskiBoundFB K ≤ (1278.6354860960937 : ℝ) := by
  refine K_minkowski_decimal _ ?_
  erw [K_nrComplexPlaces, K_discr, K_finrank]
  have hraux: √421875000 ≤ 20539.595916 := by
      refine Real.sqrt_le_iff.mpr ?_
      norm_num
  have : 0.0384 * √421875000 ≤ 788.730483 := by
    refine le_trans (mul_le_mul_of_nonneg (by rfl) hraux (by norm_num) (by norm_num)) ?_
    norm_num
  norm_num
  try {linarith}

def s := ![9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8]

def BM : (i : Fin 23) → Fin (e i) → (Fin 1 → ℕ) := by 
  rintro ⟨i, hi⟩ 
  interval_cases i 
  exact ![![0], ![2], ![2], ![1], ![1], ![2], ![0], ![2], ![1], ![1], ![0]]
  exact ![![1], ![0], ![2], ![1], ![1]]
  exact ![![0], ![1], ![0], ![2], ![1], ![0], ![1], ![2], ![2], ![1], ![2], ![0], ![1], ![1], ![2]]
  exact ![![1], ![2], ![1], ![2], ![0], ![0], ![0], ![0], ![0], ![1]]
  exact ![![0], ![2], ![2], ![0], ![2], ![1], ![0], ![2], ![0]]
  exact ![![2], ![1], ![0], ![1], ![2], ![0], ![0]]
  exact ![![1], ![2], ![0], ![2], ![0], ![1], ![1], ![1]]
  exact ![![1], ![0], ![2], ![2], ![2], ![1], ![1], ![1], ![1], ![2]]
  exact ![![0], ![1], ![2], ![2], ![0], ![2], ![0]]
  exact ![![0], ![2], ![1], ![2], ![0], ![1], ![2], ![1], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![1], ![0], ![1], ![2], ![2], ![1], ![2], ![1]]
  exact ![![1], ![1], ![1], ![0], ![1], ![0], ![1], ![0], ![1], ![1], ![2]]
  exact ![![0], ![1], ![2], ![0], ![2], ![2], ![1], ![1], ![0], ![2]]
  exact ![![2], ![2], ![0], ![0], ![0], ![2], ![0], ![1], ![1], ![0]]
  exact ![![0], ![0], ![0], ![1], ![0], ![0]]
  exact ![![2], ![2], ![1], ![0], ![0], ![1], ![1], ![1]]
  exact ![![1], ![2], ![2], ![2], ![2]]
  exact ![![0], ![2], ![0], ![0], ![1], ![0], ![2]]
  exact ![![1], ![0], ![2], ![2], ![2], ![0], ![0], ![1]]
  exact ![![1], ![0], ![2], ![2], ![1], ![0], ![1], ![1], ![2], ![0]]
  exact ![![1], ![0], ![2], ![1], ![1]]
  exact ![![0], ![2], ![1], ![2], ![1], ![0], ![0], ![0], ![1], ![2], ![0], ![2], ![1], ![0], ![0]]
  exact ![![2], ![2], ![2], ![1], ![1]]

lemma primesGenerationBelow : {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < 1279} ⊆ Set.range (Fin.addCasesIter e 𝔭) := by
  rw [← cert_eq_𝔭]
  refine le_primes_below_bound_of_PrimesBelowBoundCertificate_le_of_eq (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv PB1279

def 𝔭' : Fin 204 → nonZeroDivisors (Ideal O) := by
  intro i
  have : PB1279.β i ∈ List.ofFn PB1279.β := by
    simp only [List.mem_ofFn, exists_apply_eq_apply]
  refine Ideal.toNonZeroDivisorOfNeZero ((PB1279.β) i)
    (fun hc => ((zero_ne_mem_of_PrimesBelowCertificate_Fn _ PB1279) (hc ▸ this) ))

def J : Fin 1 → Ideal O := ![J0]

def J' :  Fin 1 → nonZeroDivisors (Ideal O) := by
  refine fun i => Ideal.toNonZeroDivisorOfNeZero (J i) (?_ )
  unfold J
  rw [← Submodule.zero_eq_bot, ← pow_ne_zero_iff (n := ![3] i) (by fin_cases i <;> decide) , NPSU3.h]
  simp only [ Submodule.zero_eq_bot, ne_eq, Ideal.span_singleton_eq_bot, NPSU3]
  fin_cases i
  · dsimp [alpha0] ; rw [(LinearEquiv.map_eq_zero_iff B.equivFun.symm)] ; decide 

lemma 𝔭'_apply : ∀ (i : Fin 204), ↑(𝔭' i) = (Fin.addCasesIter e 𝔭) i := by
  intro i
  rw [← cert_eq_𝔭]
  rfl

lemma J'_apply : ∀ (i : Fin 1), ↑(J' i) = J i := by
  intro i
  rfl

lemma relations_proof0 (i : Fin 11) : IsInClass O J (𝔭 0 i) (BM 0 i) := by
  show IsInClass O J (𝔭 0 i) (![![0], ![2], ![2], ![1], ![1], ![2], ![0], ![2], ![1], ![1], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R3N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R3N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R11N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R13N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R13N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof1 (i : Fin 5) : IsInClass O J (𝔭 1 i) (BM 1 i) := by
  show IsInClass O J (𝔭 1 i) (![![1], ![0], ![2], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R31N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R47N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R47N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R61N1

lemma relations_proof2 (i : Fin 15) : IsInClass O J (𝔭 2 i) (BM 2 i) := by
  show IsInClass O J (𝔭 2 i) (![![0], ![1], ![0], ![2], ![1], ![0], ![1], ![2], ![2], ![1], ![2], ![0], ![1], ![1], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R71N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R83N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R83N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R89N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R89N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R97N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R97N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R97N3
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R101N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R103N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R103N2

lemma relations_proof3 (i : Fin 10) : IsInClass O J (𝔭 3 i) (BM 3 i) := by
  show IsInClass O J (𝔭 3 i) (![![1], ![2], ![1], ![2], ![0], ![0], ![0], ![0], ![0], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R107N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R113N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R113N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R131N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R149N2

lemma relations_proof4 (i : Fin 9) : IsInClass O J (𝔭 4 i) (BM 4 i) := by
  show IsInClass O J (𝔭 4 i) (![![0], ![2], ![2], ![0], ![2], ![1], ![0], ![2], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R163N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R163N3
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R173N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R179N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R179N3
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof5 (i : Fin 7) : IsInClass O J (𝔭 5 i) (BM 5 i) := by
  show IsInClass O J (𝔭 5 i) (![![2], ![1], ![0], ![1], ![2], ![0], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R199N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R223N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R227N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R229N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof6 (i : Fin 8) : IsInClass O J (𝔭 6 i) (BM 6 i) := by
  show IsInClass O J (𝔭 6 i) (![![1], ![2], ![0], ![2], ![0], ![1], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R263N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R269N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R271N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R283N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R293N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R307N1

lemma relations_proof7 (i : Fin 10) : IsInClass O J (𝔭 7 i) (BM 7 i) := by
  show IsInClass O J (𝔭 7 i) (![![1], ![0], ![2], ![2], ![2], ![1], ![1], ![1], ![1], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R313N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R313N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R317N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R337N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R347N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R347N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R353N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R353N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R359N2

lemma relations_proof8 (i : Fin 7) : IsInClass O J (𝔭 8 i) (BM 8 i) := by
  show IsInClass O J (𝔭 8 i) (![![0], ![1], ![2], ![2], ![0], ![2], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R367N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R383N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R389N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R397N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof9 (i : Fin 10) : IsInClass O J (𝔭 9 i) (BM 9 i) := by
  show IsInClass O J (𝔭 9 i) (![![0], ![2], ![1], ![2], ![0], ![1], ![2], ![1], ![0], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R431N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R431N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R433N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R433N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R439N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R443N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof10 (i : Fin 12) : IsInClass O J (𝔭 10 i) (BM 10 i) := by
  show IsInClass O J (𝔭 10 i) (![![0], ![0], ![0], ![0], ![1], ![0], ![1], ![2], ![2], ![1], ![2], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R491N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R509N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R509N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R521N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R523N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R523N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R523N3

lemma relations_proof11 (i : Fin 11) : IsInClass O J (𝔭 11 i) (BM 11 i) := by
  show IsInClass O J (𝔭 11 i) (![![1], ![1], ![1], ![0], ![1], ![0], ![1], ![0], ![1], ![1], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R541N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R547N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R547N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R557N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R563N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R571N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R577N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R587N2

lemma relations_proof12 (i : Fin 10) : IsInClass O J (𝔭 12 i) (BM 12 i) := by
  show IsInClass O J (𝔭 12 i) (![![0], ![1], ![2], ![0], ![2], ![2], ![1], ![1], ![0], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R599N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R617N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R619N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R631N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R641N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R643N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R643N3

lemma relations_proof13 (i : Fin 10) : IsInClass O J (𝔭 13 i) (BM 13 i) := by
  show IsInClass O J (𝔭 13 i) (![![2], ![2], ![0], ![0], ![0], ![2], ![0], ![1], ![1], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R647N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R647N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R673N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R683N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R691N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof14 (i : Fin 6) : IsInClass O J (𝔭 14 i) (BM 14 i) := by
  show IsInClass O J (𝔭 14 i) (![![0], ![0], ![0], ![1], ![0], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R751N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof15 (i : Fin 8) : IsInClass O J (𝔭 15 i) (BM 15 i) := by
  show IsInClass O J (𝔭 15 i) (![![2], ![2], ![1], ![0], ![0], ![1], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R769N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R773N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R787N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R823N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R827N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R827N2

lemma relations_proof16 (i : Fin 5) : IsInClass O J (𝔭 16 i) (BM 16 i) := by
  show IsInClass O J (𝔭 16 i) (![![1], ![2], ![2], ![2], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R839N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R857N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R857N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R877N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R877N2

lemma relations_proof17 (i : Fin 7) : IsInClass O J (𝔭 17 i) (BM 17 i) := by
  show IsInClass O J (𝔭 17 i) (![![0], ![2], ![0], ![0], ![1], ![0], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R907N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R947N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R953N2

lemma relations_proof18 (i : Fin 8) : IsInClass O J (𝔭 18 i) (BM 18 i) := by
  show IsInClass O J (𝔭 18 i) (![![1], ![0], ![2], ![2], ![2], ![0], ![0], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R967N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R983N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R997N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1009N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1013N3

lemma relations_proof19 (i : Fin 10) : IsInClass O J (𝔭 19 i) (BM 19 i) := by
  show IsInClass O J (𝔭 19 i) (![![1], ![0], ![2], ![2], ![1], ![0], ![1], ![1], ![2], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1021N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1021N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1031N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1031N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1049N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1051N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1051N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof20 (i : Fin 5) : IsInClass O J (𝔭 20 i) (BM 20 i) := by
  show IsInClass O J (𝔭 20 i) (![![1], ![0], ![2], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1087N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1091N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1093N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1093N2

lemma relations_proof21 (i : Fin 15) : IsInClass O J (𝔭 21 i) (BM 21 i) := by
  show IsInClass O J (𝔭 21 i) (![![0], ![2], ![1], ![2], ![1], ![0], ![0], ![0], ![1], ![2], ![0], ![2], ![1], ![0], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1151N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1153N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1153N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1153N3
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1181N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1193N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1201N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1201N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof22 (i : Fin 5) : IsInClass O J (𝔭 22 i) (BM 22 i) := by
  show IsInClass O J (𝔭 22 i) (![![2], ![2], ![2], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1223N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1229N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1229N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1237N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1259N1

theorem class_group_generator : Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (J' i))) = ⊤ := by
  refine subgroup_closure_eq_classGroup'' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv
      𝔭'_apply J'_apply ?_ primesGenerationBelow (Fin.addCasesIter e BM) ?_
  · refine lt_of_le_of_lt K_minowski ?_
    norm_num
  · refine forall_addCasesIter_prop 𝔭 BM (IsInClass O J) ?_
    rintro ⟨i, hi⟩
    interval_cases i
    · exact relations_proof0
    · exact relations_proof1
    · exact relations_proof2
    · exact relations_proof3
    · exact relations_proof4
    · exact relations_proof5
    · exact relations_proof6
    · exact relations_proof7
    · exact relations_proof8
    · exact relations_proof9
    · exact relations_proof10
    · exact relations_proof11
    · exact relations_proof12
    · exact relations_proof13
    · exact relations_proof14
    · exact relations_proof15
    · exact relations_proof16
    · exact relations_proof17
    · exact relations_proof18
    · exact relations_proof19
    · exact relations_proof20
    · exact relations_proof21
    · exact relations_proof22

def ClassGroupO_equiv : (∀ i : Fin 1 , (ZMod (![3] i))) ≃+ Additive (ClassGroup O) := by
  haveI : ∀ (i : Fin 1), NeZero (![3] i) := by
    intro i
    fin_cases i <;>  exact {out := by decide}
  refine ClassGroup_equiv_of_pSaturatedCertificate J'_apply NPSU3.h class_group_generator ?_
  rintro ⟨p, hp1, hp2⟩
  have : ∏ i, ![3] i = ∏ i, (![3] i) ^ (![1] i)  := by decide
  rw [this] at hp2
  have hp_cases : p ∈ [3] := by
    obtain ⟨j ,hj1, hj2⟩  := Prime.exists_mem_finset_dvd (Nat.prime_iff.mp hp1) hp2
    show p ∈ List.ofFn ![3]
    rw [(Nat.prime_dvd_prime_iff_eq hp1 ?_).1 (Nat.Prime.dvd_of_dvd_pow hp1 hj2), List.mem_ofFn]
    exact ⟨j, rfl⟩
    fin_cases j <;> decide
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hp_cases
  by_cases h : p = 3
  simp_rw [h] ; right
  exact NPSU3
  omega

def class_group_equiv : (∀ i : Fin 1 , (ZMod (![3] i))) ≃+ Additive (ClassGroup (NumberField.RingOfIntegers K)) := by
 refine AddEquiv.trans ClassGroupO_equiv ?_
 exact MulEquiv.toAdditive (ClassGroup.congr
    ((Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv))

theorem class_number_K_eq_3 : NumberField.classNumber K = 3 := by
  unfold NumberField.classNumber
  rw [Fintype.card_eq_nat_card, ← Nat.card_congr (Additive.toMul),
    Nat.card_congr (class_group_equiv).symm.toEquiv, Nat.card_pi]
  simp [Fin.isValue, Fin.prod_succ]
  try decide
