import IdealArithmetic.Examples.NF5_1_405000000_1.ClassGroupSaturated5_1_405000000_1_2
import IdealArithmetic.Examples.NF5_1_405000000_1.RelationIdeals5_1_405000000_1F0
import IdealArithmetic.Examples.NF5_1_405000000_1.RelationIdeals5_1_405000000_1F1
import IdealArithmetic.Examples.NF5_1_405000000_1.RelationIdeals5_1_405000000_1F2
import IdealArithmetic.Examples.NF5_1_405000000_1.RelationIdeals5_1_405000000_1F3
import IdealArithmetic.Examples.NF5_1_405000000_1.RelationIdeals5_1_405000000_1F4
import IdealArithmetic.Examples.NF5_1_405000000_1.RelationIdeals5_1_405000000_1F5
import IdealArithmetic.Examples.NF5_1_405000000_1.RelationIdeals5_1_405000000_1F6
import IdealArithmetic.Examples.NF5_1_405000000_1.RelationIdeals5_1_405000000_1F7
import IdealArithmetic.Examples.NF5_1_405000000_1.RelationIdeals5_1_405000000_1F8
import IdealArithmetic.Examples.NF5_1_405000000_1.RelationIdeals5_1_405000000_1F9
import IdealArithmetic.Examples.NF5_1_405000000_1.RelationIdeals5_1_405000000_1F10
import IdealArithmetic.Examples.NF5_1_405000000_1.RelationIdeals5_1_405000000_1F11
import IdealArithmetic.Examples.NF5_1_405000000_1.RelationIdeals5_1_405000000_1F12
import IdealArithmetic.Examples.NF5_1_405000000_1.RelationIdeals5_1_405000000_1F13
import IdealArithmetic.Examples.NF5_1_405000000_1.RelationIdeals5_1_405000000_1F14
import IdealArithmetic.Examples.NF5_1_405000000_1.RelationIdeals5_1_405000000_1F15
import IdealArithmetic.Examples.NF5_1_405000000_1.RelationIdeals5_1_405000000_1F16
import IdealArithmetic.Examples.NF5_1_405000000_1.RelationIdeals5_1_405000000_1F17
import IdealArithmetic.Examples.NF5_1_405000000_1.RelationIdeals5_1_405000000_1F18
import IdealArithmetic.Examples.NF5_1_405000000_1.RelationIdeals5_1_405000000_1F19
import IdealArithmetic.Examples.NF5_1_405000000_1.RelationIdeals5_1_405000000_1F20
import IdealArithmetic.Examples.NF5_1_405000000_1.RelationIdeals5_1_405000000_1F21
import IdealArithmetic.Examples.NF5_1_405000000_1.RelationIdeals5_1_405000000_1F22
import IdealArithmetic.Examples.NF5_1_405000000_1.PrimesBelowCert5_1_405000000_1
import Mathlib.NumberTheory.NumberField.ClassNumber
import IdealArithmetic.Signature.ResultantRecursive
import IdealArithmetic.DedekindProject.Discriminant
import IdealArithmetic.Generation.ClassGroupGeneration

set_option linter.all false

/- Number field `K(α)` with α root of polynomial `X^5 + 15*X^3 - 50*X^2 - 480`.
Class group structure `[2]`, generated by class of ideals `[(2, 1/8*a^4 + 1/2*a^3 - 1/8*a^2 + 5/4*a - 27)]`. -/

/- Ring of integers with basis `[1, a, a^2, 1/2*a^3 - 1/2*a, 1/8*a^4 - 1/8*a^2 - 1/4*a]` -/

open BigOperators Classical Matrix Polynomial Module

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible

instance K_field : Field K := by
  unfold K
  exact AdjoinRoot.instField

instance K_numberField : NumberField K := by
  unfold K
  exact AdjoinRoot.instNumberFieldRat

instance : Module ℚ K := Algebra.toModule
instance : @Algebra ℤ K CommRing.toCommSemiring CommRing.toCommSemiring.toSemiring := Ring.toIntAlgebra K
instance : @CharZero K CommRing.toCommSemiring.toNonAssocSemiring.toAddCommMonoidWithOne.toAddMonoidWithOne := charZero_of_expChar_one' K

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  erw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, T_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ [2]
  · fin_cases hc
    exact @pMaximal_of_MaximalOrderCertificateWLists K 2 _ IsAddTorsionFree.to_noZeroSMulDivisors_int _ O Om hm _ _ M2
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [2] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']

theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by rw [O_integral_closure] ; rfl

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance DD' : IsDedekindDomain O  := by
  rw [O_integral_closure]
  exact integralClosure.isDedekindDomain ℤ ℚ K

instance : Module.Free ℤ ↥O := Module.Free.of_basis B

instance  : IdemCommSemiring (Ideal O) := Ideal.instIdemCommSemiring
instance : CharZero O := SubsemiringClass.instCharZero O

def SturmRC : SturmBuilderOfList [[-480, 0, -50, 15, 0, 1], [0, -100, 45, 0, 5], [12000, 0, 750, -150], [-1800000, -270000, -153000], [-64800000, 27000000], [103680000000]] [-480, 0, -50, 15, 0, 1] [0, -100, 45, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 5 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 22500, 23409000000, 729000000000000]
  f := [1, 25, 22500, 23409000000]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [-3750, -750], [-155250000, 22950000], [-17204400000000, -4131000000000]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 + 15*X^3 - 50*X^2 - 480
  l := [-480, 0, -50, 15, 0, 1]
  hl := T_ofList
  hlz := by decide
  hz := by decide
  hAdj := Adj
  heq := O_integral_closure
  P := [[-480, 0, -50, 15, 0, 1], [0, -100, 45, 0, 5], [12000, 0, 750, -150], [-1800000, -270000, -153000], [-64800000, 27000000], [103680000000]]
  SB := SturmRC
  k := 1
  r := 3
  hr := by decide
  hreq := by decide 

def NPCU2 : pMaximalUnitsCertificateDvdT O 2 where 
 hp := by decide
 r := 2
 huc := by 
  erw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2]
 hu := fun i => 
  match i with 
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
 v := v
 m := 2
 hm := by norm_num
 hmv := v_pow_one
 t := 4
 hrle := by decide
 q := ![3, 3, 7, 11]
 hqP := by 
  intro i 
  match i with 
  | 0 => exact Sat2.hq3
  | 1 => exact Sat2.hq3
  | 2 => exact Sat2.hq7
  | 3 => exact Sat2.hq11
 I := ![Sat2.I0, Sat2.I1, Sat2.I2, Sat2.I3]
 hcard := fun i =>
  match i with  
  | 0 => Sat2.N0
  | 1 => Sat2.N1
  | 2 => Sat2.N2
  | 3 => Sat2.N3
 ζ := ![2, 2, 3, 2]
 hr := fun i =>
  match i with 
  | 0 => ((orderOf_of_IsOrderOf Sat2.R3) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf Sat2.R3) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf Sat2.R7) ▸ IsPrimitiveRoot.orderOf _)
  | 3 => ((orderOf_of_IsOrderOf Sat2.R11) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 M := ![![0, 1, 1], ![0, 0, 1], ![1, 1, 1], ![0, 1, 1]]
 hM1 := by 
  intro i j hj
  fin_cases i <;> interval_cases j 
  · erw [eq_of_DiscreteLogCertificate Sat2.Log00] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log01] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log10] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log11] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log20] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log21] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log30] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log31] ; decide
 hM2 := by 
  intro i 
  fin_cases i 
  · erw [eq_of_DiscreteLogCertificate Sat2.Log02] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log12] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log22] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log32] ; decide
 Minv := ![![1, 0, 1], ![1, 1, 0], ![0, 1, 0]]
 hInv := by decide

def NPSU2 : pSaturatedClassGroupCertificateDvdT 2 ![J0] ![2] where 
 topMaximalUnitsCertificateDvdT := NPCU2
 a := ![alpha0]
 γ := 1
 hc := by decide
 ψ := ![0]
 iψ := ![0] 
 hψ := by decide 
 hψn := by 
  intro i 
  fin_cases i 
  · decide
 h := fun i =>
  match i with 
  | 0 => by convert J0_pow2
 N := ![![1], ![1], ![0], ![0]]
 hM3 := by 
  intro (i : Fin 4) j
  match i , j with 
  | 0, 0 => exact Sat2.Log03
  | 1, 0 => exact Sat2.Log13
  | 2, 0 => exact Sat2.Log23
  | 3, 0 => exact Sat2.Log33
 hDl := by decide 
 NInv := ![![0, 0, 1, 1], ![1, 1, 0, 0], ![1, 1, 0, 1], ![1, 0, 0, 1]]
 hN := by decide 

lemma T_discr : T.discr = 103680000000 :=  by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  rw [T_ofList]

theorem K_discr : NumberField.discr K = 405000000 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl

lemma K_nrComplexPlaces : NumberField.InfinitePlace.nrComplexPlaces K = 2 := by
  rw [nrComplexPlaces_of_RankUnitsCertificate RC]
  rfl

lemma K_nrRealPlaces : NumberField.InfinitePlace.nrRealPlaces K = 1 := by
  rw [nrRealPlaces_of_RankUnitsCertificate RC]
  rfl

theorem K_minowski : minkowskiBoundFB K ≤ (1252.802005221415 : ℝ) := by
  refine K_minkowski_decimal _ ?_
  erw [K_nrComplexPlaces, K_discr, K_finrank]
  have hraux: √405000000 ≤ 20124.611807 := by
      refine Real.sqrt_le_iff.mpr ?_
      norm_num
  have : 0.0384 * √405000000 ≤ 772.795093 := by
    refine le_trans (mul_le_mul_of_nonneg (by rfl) hraux (by norm_num) (by norm_num)) ?_
    norm_num
  norm_num
  try {linarith}

def s := ![9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 6]

def BM : (i : Fin 23) → Fin (e i) → (Fin 1 → ℕ) := by 
  rintro ⟨i, hi⟩ 
  interval_cases i 
  exact ![![0], ![1], ![1], ![0], ![0], ![0], ![1], ![1], ![0], ![1], ![0], ![0], ![1], ![1], ![0]]
  exact ![![0], ![1], ![1], ![1], ![0], ![1], ![1], ![1], ![1], ![1]]
  exact ![![1], ![0], ![1], ![0], ![1]]
  exact ![![1], ![0], ![1], ![1], ![1], ![0], ![1], ![0], ![0], ![1], ![1]]
  exact ![![1], ![1], ![1]]
  exact ![![1], ![0], ![0], ![0], ![1], ![0], ![0], ![1], ![0], ![1]]
  exact ![![1], ![1], ![1], ![1], ![1], ![0], ![1], ![0], ![0], ![1], ![1], ![1]]
  exact ![![1], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![1], ![1], ![0], ![0], ![1]]
  exact ![![0], ![1], ![1], ![0], ![0], ![1], ![0], ![1], ![0]]
  exact ![![0], ![0], ![1], ![1], ![0], ![1], ![1], ![0], ![0], ![1]]
  exact ![![1], ![1], ![0], ![0]]
  exact ![![1], ![0], ![0], ![1], ![1], ![0], ![1], ![1], ![1], ![1], ![1], ![0], ![0]]
  exact ![![0], ![0], ![0], ![1], ![0], ![0], ![0], ![1], ![1]]
  exact ![![0], ![1], ![1], ![0], ![1], ![0]]
  exact ![![1], ![1], ![1], ![0], ![1], ![0], ![0], ![1]]
  exact ![![1], ![0], ![0], ![0], ![1], ![0], ![0]]
  exact ![![1], ![1], ![1], ![1], ![1], ![0]]
  exact ![![0], ![1], ![1], ![1], ![1], ![1]]
  exact ![![1], ![1], ![0], ![0], ![0], ![0], ![1], ![1], ![1], ![1], ![0]]
  exact ![![0], ![1], ![1]]
  exact ![![0], ![1], ![1], ![1], ![0], ![0], ![1], ![0], ![1], ![1]]
  exact ![![1], ![0], ![0], ![0], ![1]]

lemma primesGenerationBelow : {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < 1253} ⊆ Set.range (Fin.addCasesIter e 𝔭) := by
  rw [← cert_eq_𝔭]
  refine le_primes_below_bound_of_PrimesBelowBoundCertificate_le_of_eq (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv PB1253

def 𝔭' : Fin 187 → nonZeroDivisors (Ideal O) := by
  intro i
  have : PB1253.β i ∈ List.ofFn PB1253.β := by
    simp only [List.mem_ofFn, exists_apply_eq_apply]
  refine Ideal.toNonZeroDivisorOfNeZero ((PB1253.β) i)
    (fun hc => ((zero_ne_mem_of_PrimesBelowCertificate_Fn _ PB1253) (hc ▸ this) ))

def J : Fin 1 → Ideal O := ![J0]

def J' :  Fin 1 → nonZeroDivisors (Ideal O) := by
  refine fun i => Ideal.toNonZeroDivisorOfNeZero (J i) (?_ )
  unfold J
  rw [← Submodule.zero_eq_bot, ← pow_ne_zero_iff (n := ![2] i) (by fin_cases i <;> decide) , NPSU2.h]
  simp only [ Submodule.zero_eq_bot, ne_eq, Ideal.span_singleton_eq_bot, NPSU2]
  fin_cases i
  · dsimp [alpha0] ; rw [(LinearEquiv.map_eq_zero_iff B.equivFun.symm)] ; decide 

lemma 𝔭'_apply : ∀ (i : Fin 187), ↑(𝔭' i) = (Fin.addCasesIter e 𝔭) i := by
  intro i
  rw [← cert_eq_𝔭]
  rfl

lemma J'_apply : ∀ (i : Fin 1), ↑(J' i) = J i := by
  intro i
  rfl

lemma relations_proof0 (i : Fin 15) : IsInClass O J (𝔭 0 i) (BM 0 i) := by
  show IsInClass O J (𝔭 0 i) (![![0], ![1], ![1], ![0], ![0], ![0], ![1], ![1], ![0], ![1], ![0], ![0], ![1], ![1], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R7N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R11N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R13N0
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R13N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R17N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof1 (i : Fin 10) : IsInClass O J (𝔭 1 i) (BM 1 i) := by
  show IsInClass O J (𝔭 1 i) (![![0], ![1], ![1], ![1], ![0], ![1], ![1], ![1], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R29N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R29N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R37N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R41N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R43N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R47N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R59N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R59N2

lemma relations_proof2 (i : Fin 5) : IsInClass O J (𝔭 2 i) (BM 2 i) := by
  show IsInClass O J (𝔭 2 i) (![![1], ![0], ![1], ![0], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R67N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R79N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R83N1

lemma relations_proof3 (i : Fin 11) : IsInClass O J (𝔭 3 i) (BM 3 i) := by
  show IsInClass O J (𝔭 3 i) (![![1], ![0], ![1], ![1], ![1], ![0], ![1], ![0], ![0], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R107N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R107N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R109N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R109N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R131N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R139N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R151N2

lemma relations_proof4 (i : Fin 3) : IsInClass O J (𝔭 4 i) (BM 4 i) := by
  show IsInClass O J (𝔭 4 i) (![![1], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R179N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R179N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R197N1

lemma relations_proof5 (i : Fin 10) : IsInClass O J (𝔭 5 i) (BM 5 i) := by
  show IsInClass O J (𝔭 5 i) (![![1], ![0], ![0], ![0], ![1], ![0], ![0], ![1], ![0], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R199N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R223N3
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R241N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R251N2

lemma relations_proof6 (i : Fin 12) : IsInClass O J (𝔭 6 i) (BM 6 i) := by
  show IsInClass O J (𝔭 6 i) (![![1], ![1], ![1], ![1], ![1], ![0], ![1], ![0], ![0], ![1], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R257N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R263N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R269N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R269N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R271N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R277N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R281N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R283N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R293N1

lemma relations_proof7 (i : Fin 5) : IsInClass O J (𝔭 7 i) (BM 7 i) := by
  show IsInClass O J (𝔭 7 i) (![![1], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R347N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof8 (i : Fin 9) : IsInClass O J (𝔭 8 i) (BM 8 i) := by
  show IsInClass O J (𝔭 8 i) (![![0], ![0], ![0], ![0], ![1], ![1], ![0], ![0], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R389N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R397N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R409N2

lemma relations_proof9 (i : Fin 9) : IsInClass O J (𝔭 9 i) (BM 9 i) := by
  show IsInClass O J (𝔭 9 i) (![![0], ![1], ![1], ![0], ![0], ![1], ![0], ![1], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R421N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R421N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R439N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R461N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof10 (i : Fin 10) : IsInClass O J (𝔭 10 i) (BM 10 i) := by
  show IsInClass O J (𝔭 10 i) (![![0], ![0], ![1], ![1], ![0], ![1], ![1], ![0], ![0], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R479N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R487N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R499N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R499N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R523N1

lemma relations_proof11 (i : Fin 4) : IsInClass O J (𝔭 11 i) (BM 11 i) := by
  show IsInClass O J (𝔭 11 i) (![![1], ![1], ![0], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R563N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R577N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof12 (i : Fin 13) : IsInClass O J (𝔭 12 i) (BM 12 i) := by
  show IsInClass O J (𝔭 12 i) (![![1], ![0], ![0], ![1], ![1], ![0], ![1], ![1], ![1], ![1], ![1], ![0], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R599N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R613N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R613N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R617N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R631N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R631N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R631N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R631N3
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof13 (i : Fin 9) : IsInClass O J (𝔭 13 i) (BM 13 i) := by
  show IsInClass O J (𝔭 13 i) (![![0], ![0], ![0], ![1], ![0], ![0], ![0], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R673N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R683N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R701N2

lemma relations_proof14 (i : Fin 6) : IsInClass O J (𝔭 14 i) (BM 14 i) := by
  show IsInClass O J (𝔭 14 i) (![![0], ![1], ![1], ![0], ![1], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R733N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R739N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R743N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof15 (i : Fin 8) : IsInClass O J (𝔭 15 i) (BM 15 i) := by
  show IsInClass O J (𝔭 15 i) (![![1], ![1], ![1], ![0], ![1], ![0], ![0], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R769N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R773N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R787N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R809N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R821N2

lemma relations_proof16 (i : Fin 7) : IsInClass O J (𝔭 16 i) (BM 16 i) := by
  show IsInClass O J (𝔭 16 i) (![![1], ![0], ![0], ![0], ![1], ![0], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R829N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R883N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof17 (i : Fin 6) : IsInClass O J (𝔭 17 i) (BM 17 i) := by
  show IsInClass O J (𝔭 17 i) (![![1], ![1], ![1], ![1], ![1], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R887N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R907N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R919N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R937N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R941N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof18 (i : Fin 6) : IsInClass O J (𝔭 18 i) (BM 18 i) := by
  show IsInClass O J (𝔭 18 i) (![![0], ![1], ![1], ![1], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R983N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R983N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R983N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R997N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1013N1

lemma relations_proof19 (i : Fin 11) : IsInClass O J (𝔭 19 i) (BM 19 i) := by
  show IsInClass O J (𝔭 19 i) (![![1], ![1], ![0], ![0], ![0], ![0], ![1], ![1], ![1], ![1], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1049N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1051N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1061N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1061N4
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1063N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1069N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof20 (i : Fin 3) : IsInClass O J (𝔭 20 i) (BM 20 i) := by
  show IsInClass O J (𝔭 20 i) (![![0], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1129N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1129N2

lemma relations_proof21 (i : Fin 10) : IsInClass O J (𝔭 21 i) (BM 21 i) := by
  show IsInClass O J (𝔭 21 i) (![![0], ![1], ![1], ![1], ![0], ![0], ![1], ![0], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1151N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1153N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1171N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1181N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1187N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1187N3

lemma relations_proof22 (i : Fin 5) : IsInClass O J (𝔭 22 i) (BM 22 i) := by
  show IsInClass O J (𝔭 22 i) (![![1], ![0], ![0], ![0], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1217N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1237N1

theorem class_group_generator : Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (J' i))) = ⊤ := by
  refine subgroup_closure_eq_classGroup'' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv
      𝔭'_apply J'_apply ?_ primesGenerationBelow (Fin.addCasesIter e BM) ?_
  · refine lt_of_le_of_lt K_minowski ?_
    norm_num
  · refine forall_addCasesIter_prop 𝔭 BM (IsInClass O J) ?_
    rintro ⟨i, hi⟩
    interval_cases i
    · exact relations_proof0
    · exact relations_proof1
    · exact relations_proof2
    · exact relations_proof3
    · exact relations_proof4
    · exact relations_proof5
    · exact relations_proof6
    · exact relations_proof7
    · exact relations_proof8
    · exact relations_proof9
    · exact relations_proof10
    · exact relations_proof11
    · exact relations_proof12
    · exact relations_proof13
    · exact relations_proof14
    · exact relations_proof15
    · exact relations_proof16
    · exact relations_proof17
    · exact relations_proof18
    · exact relations_proof19
    · exact relations_proof20
    · exact relations_proof21
    · exact relations_proof22

def ClassGroupO_equiv : (∀ i : Fin 1 , (ZMod (![2] i))) ≃+ Additive (ClassGroup O) := by
  haveI : ∀ (i : Fin 1), NeZero (![2] i) := by
    intro i
    fin_cases i <;>  exact {out := by decide}
  refine ClassGroup_equiv_of_pSaturatedCertificate J'_apply NPSU2.h class_group_generator ?_
  rintro ⟨p, hp1, hp2⟩
  have : ∏ i, ![2] i = ∏ i, (![2] i) ^ (![1] i)  := by decide
  rw [this] at hp2
  have hp_cases : p ∈ [2] := by
    obtain ⟨j ,hj1, hj2⟩  := Prime.exists_mem_finset_dvd (Nat.prime_iff.mp hp1) hp2
    show p ∈ List.ofFn ![2]
    rw [(Nat.prime_dvd_prime_iff_eq hp1 ?_).1 (Nat.Prime.dvd_of_dvd_pow hp1 hj2), List.mem_ofFn]
    exact ⟨j, rfl⟩
    fin_cases j <;> decide
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hp_cases
  by_cases h : p = 2
  simp_rw [h] ; left
  exact NPSU2
  omega

def class_group_equiv : (∀ i : Fin 1 , (ZMod (![2] i))) ≃+ Additive (ClassGroup (NumberField.RingOfIntegers K)) := by
 refine AddEquiv.trans ClassGroupO_equiv ?_
 exact MulEquiv.toAdditive (ClassGroup.congr
    ((Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv))

theorem class_number_K_eq_2 : NumberField.classNumber K = 2 := by
  unfold NumberField.classNumber
  rw [Fintype.card_eq_nat_card, ← Nat.card_congr (Additive.toMul),
    Nat.card_congr (class_group_equiv).symm.toEquiv, Nat.card_pi]
  simp [Fin.isValue, Fin.prod_succ]
  try decide
