import IdealArithmetic.Examples.NF5_1_48600000_1.ClassGroupSaturated5_1_48600000_1_5
import IdealArithmetic.Examples.NF5_1_48600000_1.RelationIdeals5_1_48600000_1F0
import IdealArithmetic.Examples.NF5_1_48600000_1.RelationIdeals5_1_48600000_1F1
import IdealArithmetic.Examples.NF5_1_48600000_1.RelationIdeals5_1_48600000_1F2
import IdealArithmetic.Examples.NF5_1_48600000_1.RelationIdeals5_1_48600000_1F3
import IdealArithmetic.Examples.NF5_1_48600000_1.RelationIdeals5_1_48600000_1F4
import IdealArithmetic.Examples.NF5_1_48600000_1.RelationIdeals5_1_48600000_1F5
import IdealArithmetic.Examples.NF5_1_48600000_1.RelationIdeals5_1_48600000_1F6
import IdealArithmetic.Examples.NF5_1_48600000_1.RelationIdeals5_1_48600000_1F7
import IdealArithmetic.Examples.NF5_1_48600000_1.RelationIdeals5_1_48600000_1F8
import IdealArithmetic.Examples.NF5_1_48600000_1.RelationIdeals5_1_48600000_1F9
import IdealArithmetic.Examples.NF5_1_48600000_1.PrimesBelowCert5_1_48600000_1
import Mathlib.NumberTheory.NumberField.ClassNumber
import IdealArithmetic.Signature.ResultantRecursive
import IdealArithmetic.DedekindProject.Discriminant
import IdealArithmetic.Generation.ClassGroupGeneration

set_option linter.all false

/- Number field `K(α)` with α root of polynomial `X^5 + 5*X^3 - 30*X^2 - 96`.
Class group structure `[5]`, generated by class of ideals `[(2, 1/16*a^4 - 1/4*a^3 + 5/16*a^2 - 17/8*a + 11/2)]`. -/

/- Ring of integers with basis `[1, a, 1/2*a^2 - 1/2*a, 1/2*a^3 - 1/2*a, 1/16*a^4 - 1/4*a^3 - 3/16*a^2 + 3/8*a - 1/2]` -/

open BigOperators Classical Matrix Polynomial Module

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible

instance K_field : Field K := by
  unfold K
  exact AdjoinRoot.instField

instance K_numberField : NumberField K := by
  unfold K
  exact AdjoinRoot.instNumberFieldRat

instance : Module ℚ K := Algebra.toModule
instance : @Algebra ℤ K CommRing.toCommSemiring CommRing.toCommSemiring.toSemiring := Ring.toIntAlgebra K
instance : @CharZero K CommRing.toCommSemiring.toNonAssocSemiring.toAddCommMonoidWithOne.toAddMonoidWithOne := charZero_of_expChar_one' K

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  erw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, T_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ [2]
  · fin_cases hc
    exact @pMaximal_of_MaximalOrderCertificateWLists K 2 _ IsAddTorsionFree.to_noZeroSMulDivisors_int _ O Om hm _ _ M2
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [2] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']

theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by rw [O_integral_closure] ; rfl

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance DD' : IsDedekindDomain O  := by
  rw [O_integral_closure]
  exact integralClosure.isDedekindDomain ℤ ℚ K

instance : Module.Free ℤ ↥O := Module.Free.of_basis B

instance  : IdemCommSemiring (Ideal O) := Ideal.instIdemCommSemiring
instance : CharZero O := SubsemiringClass.instCharZero O

def SturmRC : SturmBuilderOfList [[-96, 0, -30, 5, 0, 1], [0, -60, 15, 0, 5], [2400, 0, 450, -50], [-216000, -18000, -42000], [17280000, -38880000], [199065600000]] [-96, 0, -30, 5, 0, 1] [0, -60, 15, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 5 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 2500, 1764000000, 1511654400000000]
  f := [1, 25, 2500, 1764000000]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [-2250, -250], [-19800000, 2100000], [1425600000000, 1632960000000]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 + 5*X^3 - 30*X^2 - 96
  l := [-96, 0, -30, 5, 0, 1]
  hl := T_ofList
  hlz := by decide
  hz := by decide
  hAdj := Adj
  heq := O_integral_closure
  P := [[-96, 0, -30, 5, 0, 1], [0, -60, 15, 0, 5], [2400, 0, 450, -50], [-216000, -18000, -42000], [17280000, -38880000], [199065600000]]
  SB := SturmRC
  k := 1
  r := 3
  hr := by decide
  hreq := by decide 

lemma ne_dvd_torsion5 : ¬5 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
 suffices ¬ 5 ∣ 2 from ?_
 · convert this
   rw [O_integral_closure, ← Fintype.card_eq_nat_card,
   ←  NumberField.Units.torsionOrder_eq_two_of_odd_finrank (by erw [K_finrank] ; decide)]
   rfl
 · decide

def NPCU5 : pMaximalUnitsCertificateNDvdT O 5 where 
 hp := by decide
 r := 2
 huc := by 
  erw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2]
 hu := fun i => 
  match i with 
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
 t := 3
 hrle := by decide
 q := ![11, 11, 31]
 hqP := by 
  intro i 
  match i with 
  | 0 => exact Sat5.hq11
  | 1 => exact Sat5.hq11
  | 2 => exact Sat5.hq31
 I := ![Sat5.I0, Sat5.I1, Sat5.I2]
 hcard := fun i =>
  match i with  
  | 0 => Sat5.N0
  | 1 => Sat5.N1
  | 2 => Sat5.N2
 ζ := ![2, 2, 3]
 hr := fun i =>
  match i with 
  | 0 => ((orderOf_of_IsOrderOf Sat5.R11) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf Sat5.R11) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf Sat5.R31) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 hpndvdt := ne_dvd_torsion5
 M := ![![2, 4], ![3, 3], ![1, 4]]
 hM1 := by 
  intro i j
  fin_cases i <;> fin_cases j 
  · erw [eq_of_DiscreteLogCertificate Sat5.Log00] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat5.Log01] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat5.Log10] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat5.Log11] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat5.Log20] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat5.Log21] ; decide
 Minv := ![![2, 4], ![3, 3]] 
 hInv := by decide

def NPSU5 : pSaturatedClassGroupCertificateNDvdT 5 ![J0] ![5] where 
 topMaximalUnitsCertificateNDvdT := NPCU5
 a := ![alpha0]
 γ := 1
 hc := by decide
 ψ := ![0]
 iψ := ![0] 
 hψ := by decide 
 hψn := by 
  intro i 
  fin_cases i 
  · decide
 h := fun i =>
  match i with 
  | 0 => by convert J0_pow5
 N := ![![3], ![1], ![0]]
 hM2 := by 
  intro (i : Fin 3) j
  match i , j with 
  | 0, 0 => exact Sat5.Log02
  | 1, 0 => exact Sat5.Log12
  | 2, 0 => exact Sat5.Log22
 hDl := by decide 
 NInv := ![![2, 4, 0], ![2, 4, 4], ![3, 2, 3]]
 hN := by decide 

lemma T_discr : T.discr = 199065600000 :=  by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  rw [T_ofList]

theorem K_discr : NumberField.discr K = 48600000 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl

lemma K_nrComplexPlaces : NumberField.InfinitePlace.nrComplexPlaces K = 2 := by
  rw [nrComplexPlaces_of_RankUnitsCertificate RC]
  rfl

lemma K_nrRealPlaces : NumberField.InfinitePlace.nrRealPlaces K = 1 := by
  rw [nrRealPlaces_of_RankUnitsCertificate RC]
  rfl

theorem K_minowski : minkowskiBoundFB K ≤ (433.98988087191697 : ℝ) := by
  refine K_minkowski_decimal _ ?_
  erw [K_nrComplexPlaces, K_discr, K_finrank]
  have hraux: √48600000 ≤ 6971.370033 := by
      refine Real.sqrt_le_iff.mpr ?_
      norm_num
  have : 0.0384 * √48600000 ≤ 267.710609 := by
    refine le_trans (mul_le_mul_of_nonneg (by rfl) hraux (by norm_num) (by norm_num)) ?_
    norm_num
  norm_num
  try {linarith}

def s := ![9, 9, 9, 9, 9, 9, 9, 9, 9, 3]

def BM : (i : Fin 10) → Fin (e i) → (Fin 1 → ℕ) := by 
  rintro ⟨i, hi⟩ 
  interval_cases i 
  exact ![![2], ![1], ![3], ![4], ![2], ![1], ![0], ![2], ![2], ![1], ![3], ![0]]
  exact ![![2], ![3], ![0], ![4], ![4]]
  exact ![![1], ![0], ![1], ![2], ![4], ![1], ![3], ![0], ![2], ![4], ![0]]
  exact ![![1], ![2], ![0], ![3], ![4]]
  exact ![![1], ![1], ![1], ![2], ![4], ![0], ![0], ![0], ![1]]
  exact ![![2], ![1], ![3], ![4], ![1], ![1], ![2], ![0], ![3]]
  exact ![![1]]
  exact ![![0], ![0], ![3], ![1], ![1], ![4], ![2], ![1]]
  exact ![![2], ![2], ![2], ![1], ![1], ![3], ![0], ![3], ![3], ![3], ![1], ![1], ![1], ![0]]
  exact ![![3], ![3], ![2]]

lemma primesGenerationBelow : {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < 434} ⊆ Set.range (Fin.addCasesIter e 𝔭) := by
  rw [← cert_eq_𝔭]
  refine le_primes_below_bound_of_PrimesBelowBoundCertificate_le_of_eq (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv PB434

def 𝔭' : Fin 77 → nonZeroDivisors (Ideal O) := by
  intro i
  have : PB434.β i ∈ List.ofFn PB434.β := by
    simp only [List.mem_ofFn, exists_apply_eq_apply]
  refine Ideal.toNonZeroDivisorOfNeZero ((PB434.β) i)
    (fun hc => ((zero_ne_mem_of_PrimesBelowCertificate_Fn _ PB434) (hc ▸ this) ))

def J : Fin 1 → Ideal O := ![J0]

def J' :  Fin 1 → nonZeroDivisors (Ideal O) := by
  refine fun i => Ideal.toNonZeroDivisorOfNeZero (J i) (?_ )
  unfold J
  rw [← Submodule.zero_eq_bot, ← pow_ne_zero_iff (n := ![5] i) (by fin_cases i <;> decide) , NPSU5.h]
  simp only [ Submodule.zero_eq_bot, ne_eq, Ideal.span_singleton_eq_bot, NPSU5]
  fin_cases i
  · dsimp [alpha0] ; rw [(LinearEquiv.map_eq_zero_iff B.equivFun.symm)] ; decide 

lemma 𝔭'_apply : ∀ (i : Fin 77), ↑(𝔭' i) = (Fin.addCasesIter e 𝔭) i := by
  intro i
  rw [← cert_eq_𝔭]
  rfl

lemma J'_apply : ∀ (i : Fin 1), ↑(J' i) = J i := by
  intro i
  rfl

lemma relations_proof0 (i : Fin 12) : IsInClass O J (𝔭 0 i) (BM 0 i) := by
  show IsInClass O J (𝔭 0 i) (![![2], ![1], ![3], ![4], ![2], ![1], ![0], ![2], ![2], ![1], ![3], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R3N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R3N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R3N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R11N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R11N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R13N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R19N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof1 (i : Fin 5) : IsInClass O J (𝔭 1 i) (BM 1 i) := by
  show IsInClass O J (𝔭 1 i) (![![2], ![3], ![0], ![4], ![4]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R31N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R31N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R41N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R61N2

lemma relations_proof2 (i : Fin 11) : IsInClass O J (𝔭 2 i) (BM 2 i) := by
  show IsInClass O J (𝔭 2 i) (![![1], ![0], ![1], ![2], ![4], ![1], ![3], ![0], ![2], ![4], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R67N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R71N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R73N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R83N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R97N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R101N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R101N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R103N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof3 (i : Fin 5) : IsInClass O J (𝔭 3 i) (BM 3 i) := by
  show IsInClass O J (𝔭 3 i) (![![1], ![2], ![0], ![3], ![4]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R109N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R109N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R139N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R151N1

lemma relations_proof4 (i : Fin 9) : IsInClass O J (𝔭 4 i) (BM 4 i) := by
  show IsInClass O J (𝔭 4 i) (![![1], ![1], ![1], ![2], ![4], ![0], ![0], ![0], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R157N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R157N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R157N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R167N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R179N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R193N3

lemma relations_proof5 (i : Fin 9) : IsInClass O J (𝔭 5 i) (BM 5 i) := by
  show IsInClass O J (𝔭 5 i) (![![2], ![1], ![3], ![4], ![1], ![1], ![2], ![0], ![3]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R199N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R211N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R211N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R211N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R227N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R233N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R239N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R251N2

lemma relations_proof6 (i : Fin 1) : IsInClass O J (𝔭 6 i) (BM 6 i) := by
  show IsInClass O J (𝔭 6 i) (![![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R277N1

lemma relations_proof7 (i : Fin 8) : IsInClass O J (𝔭 7 i) (BM 7 i) := by
  show IsInClass O J (𝔭 7 i) (![![0], ![0], ![3], ![1], ![1], ![4], ![2], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R313N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R317N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R317N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R337N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R347N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R353N2

lemma relations_proof8 (i : Fin 14) : IsInClass O J (𝔭 8 i) (BM 8 i) := by
  show IsInClass O J (𝔭 8 i) (![![2], ![2], ![2], ![1], ![1], ![3], ![0], ![3], ![3], ![3], ![1], ![1], ![1], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R367N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R367N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R379N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R379N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R379N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R383N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R383N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R389N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R389N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R389N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R401N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R409N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof9 (i : Fin 3) : IsInClass O J (𝔭 9 i) (BM 9 i) := by
  show IsInClass O J (𝔭 9 i) (![![3], ![3], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R431N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R431N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R433N1

theorem class_group_generator : Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (J' i))) = ⊤ := by
  refine subgroup_closure_eq_classGroup'' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv
      𝔭'_apply J'_apply ?_ primesGenerationBelow (Fin.addCasesIter e BM) ?_
  · refine lt_of_le_of_lt K_minowski ?_
    norm_num
  · refine forall_addCasesIter_prop 𝔭 BM (IsInClass O J) ?_
    rintro ⟨i, hi⟩
    interval_cases i
    · exact relations_proof0
    · exact relations_proof1
    · exact relations_proof2
    · exact relations_proof3
    · exact relations_proof4
    · exact relations_proof5
    · exact relations_proof6
    · exact relations_proof7
    · exact relations_proof8
    · exact relations_proof9

def ClassGroupO_equiv : (∀ i : Fin 1 , (ZMod (![5] i))) ≃+ Additive (ClassGroup O) := by
  haveI : ∀ (i : Fin 1), NeZero (![5] i) := by
    intro i
    fin_cases i <;>  exact {out := by decide}
  refine ClassGroup_equiv_of_pSaturatedCertificate J'_apply NPSU5.h class_group_generator ?_
  rintro ⟨p, hp1, hp2⟩
  have : ∏ i, ![5] i = ∏ i, (![5] i) ^ (![1] i)  := by decide
  rw [this] at hp2
  have hp_cases : p ∈ [5] := by
    obtain ⟨j ,hj1, hj2⟩  := Prime.exists_mem_finset_dvd (Nat.prime_iff.mp hp1) hp2
    show p ∈ List.ofFn ![5]
    rw [(Nat.prime_dvd_prime_iff_eq hp1 ?_).1 (Nat.Prime.dvd_of_dvd_pow hp1 hj2), List.mem_ofFn]
    exact ⟨j, rfl⟩
    fin_cases j <;> decide
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hp_cases
  by_cases h : p = 5
  simp_rw [h] ; right
  exact NPSU5
  omega

def class_group_equiv : (∀ i : Fin 1 , (ZMod (![5] i))) ≃+ Additive (ClassGroup (NumberField.RingOfIntegers K)) := by
 refine AddEquiv.trans ClassGroupO_equiv ?_
 exact MulEquiv.toAdditive (ClassGroup.congr
    ((Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv))

theorem class_number_K_eq_5 : NumberField.classNumber K = 5 := by
  unfold NumberField.classNumber
  rw [Fintype.card_eq_nat_card, ← Nat.card_congr (Additive.toMul),
    Nat.card_congr (class_group_equiv).symm.toEquiv, Nat.card_pi]
  simp [Fin.isValue, Fin.prod_succ]
  try decide
