import IdealArithmetic.Examples.NF3_3_587412_2.ClassGroupSaturated3_3_587412_2_3
import IdealArithmetic.Examples.NF3_3_587412_2.RelationIdeals3_3_587412_2F0
import IdealArithmetic.Examples.NF3_3_587412_2.RelationIdeals3_3_587412_2F1
import IdealArithmetic.Examples.NF3_3_587412_2.RelationIdeals3_3_587412_2F2
import IdealArithmetic.Examples.NF3_3_587412_2.RelationIdeals3_3_587412_2F3
import IdealArithmetic.Examples.NF3_3_587412_2.PrimesBelowCert3_3_587412_2
import Mathlib.NumberTheory.NumberField.ClassNumber
import IdealArithmetic.Signature.ResultantRecursive
import IdealArithmetic.DedekindProject.Discriminant
import IdealArithmetic.Generation.ClassGroupGeneration

set_option linter.all false

/- Number field `K(α)` with α root of polynomial `X^3 - 210*X - 1162`.
Class group structure `[3, 3]`, generated by class of ideals `[(5, a + 2), (13, a + 3)]`. -/

/- Ring of integers with basis `[1, a, a^2]` -/

open BigOperators Classical Matrix Polynomial Module

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible

instance K_field : Field K := by
  unfold K
  exact AdjoinRoot.instField

instance K_numberField : NumberField K := by
  unfold K
  exact AdjoinRoot.instNumberFieldRat

instance : Module ℚ K := Algebra.toModule
instance : @Algebra ℤ K CommRing.toCommSemiring CommRing.toCommSemiring.toSemiring := Ring.toIntAlgebra K
instance : @CharZero K CommRing.toCommSemiring.toNonAssocSemiring.toAddCommMonoidWithOne.toAddMonoidWithOne := charZero_of_expChar_one' K

lemma K_finrank : Module.finrank ℚ K = 3 := by
  unfold K
  erw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, T_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ []
  · fin_cases hc
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']

theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by rw [O_integral_closure] ; rfl

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance DD' : IsDedekindDomain O  := by
  rw [O_integral_closure]
  exact integralClosure.isDedekindDomain ℤ ℚ K

instance : Module.Free ℤ ↥O := Module.Free.of_basis B

instance  : IdemCommSemiring (Ideal O) := Ideal.instIdemCommSemiring
instance : CharZero O := SubsemiringClass.instCharZero O

def SturmRC : SturmBuilderOfList [[-1162, -210, 0, 1], [-210, 0, 3], [10458, 1260], [587412]] [-1162, -210, 0, 1] [-210, 0, 3] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 3 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [9, 1587600]
  f := [1, 9]
  epos := by decide
  fpos := by decide
  Q := [[0, 3], [-31374, 3780]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 2 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^3 - 210*X - 1162
  l := [-1162, -210, 0, 1]
  hl := T_ofList
  hlz := by decide
  hz := by decide
  hAdj := Adj
  heq := O_integral_closure
  P := [[-1162, -210, 0, 1], [-210, 0, 3], [10458, 1260], [587412]]
  SB := SturmRC
  k := 3
  r := 3
  hr := by decide
  hreq := by decide 

lemma ne_dvd_torsion3 : ¬3 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
 suffices ¬ 3 ∣ 2 from ?_
 · convert this
   rw [O_integral_closure, ← Fintype.card_eq_nat_card,
   ←  NumberField.Units.torsionOrder_eq_two_of_odd_finrank (by erw [K_finrank] ; decide)]
   rfl
 · decide

def NPCU3 : pMaximalUnitsCertificateNDvdT O 3 where 
 hp := by decide
 r := 2
 huc := by 
  erw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2]
 hu := fun i => 
  match i with 
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
 t := 4
 hrle := by decide
 q := ![7, 19, 31, 37]
 hqP := by 
  intro i 
  match i with 
  | 0 => exact Sat3.hq7
  | 1 => exact Sat3.hq19
  | 2 => exact Sat3.hq31
  | 3 => exact Sat3.hq37
 I := ![Sat3.I0, Sat3.I1, Sat3.I2, Sat3.I3]
 hcard := fun i =>
  match i with  
  | 0 => Sat3.N0
  | 1 => Sat3.N1
  | 2 => Sat3.N2
  | 3 => Sat3.N3
 ζ := ![3, 2, 3, 2]
 hr := fun i =>
  match i with 
  | 0 => ((orderOf_of_IsOrderOf Sat3.R7) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf Sat3.R19) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf Sat3.R31) ▸ IsPrimitiveRoot.orderOf _)
  | 3 => ((orderOf_of_IsOrderOf Sat3.R37) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 hpndvdt := ne_dvd_torsion3
 M := ![![2, 1], ![2, 2], ![0, 2], ![2, 1]]
 hM1 := by 
  intro i j
  fin_cases i <;> fin_cases j 
  · erw [eq_of_DiscreteLogCertificate Sat3.Log00] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log01] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log10] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log11] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log20] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log21] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log30] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log31] ; decide
 Minv := ![![1, 1], ![2, 1]] 
 hInv := by decide

def NPSU3 : pSaturatedClassGroupCertificateNDvdT 3 ![J0, J1] ![3, 3] where 
 topMaximalUnitsCertificateNDvdT := NPCU3
 a := ![alpha0,alpha1]
 γ := 2
 hc := by decide
 ψ := ![0, 1]
 iψ := ![0, 1] 
 hψ := by decide 
 hψn := by 
  intro i 
  fin_cases i 
  · decide
  · decide
 h := fun i =>
  match i with 
  | 0 => by convert J0_pow3
  | 1 => by convert J1_pow3
 N := ![![2, 1], ![2, 0], ![0, 0], ![1, 1]]
 hM2 := by 
  intro (i : Fin 4) j
  match i , j with 
  | 0, 0 => exact Sat3.Log02
  | 0, 1 => exact Sat3.Log03
  | 1, 0 => exact Sat3.Log12
  | 1, 1 => exact Sat3.Log13
  | 2, 0 => exact Sat3.Log22
  | 2, 1 => exact Sat3.Log23
  | 3, 0 => exact Sat3.Log32
  | 3, 1 => exact Sat3.Log33
 hDl := by decide 
 NInv := ![![2, 2, 1, 1], ![0, 0, 2, 0], ![1, 0, 0, 2], ![1, 2, 2, 0]]
 hN := by decide 

lemma T_discr : T.discr = 587412 :=  by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  rw [T_ofList]

theorem K_discr : NumberField.discr K = 587412 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl

lemma K_nrComplexPlaces : NumberField.InfinitePlace.nrComplexPlaces K = 0 := by
  rw [nrComplexPlaces_of_RankUnitsCertificate RC]
  rfl

lemma K_nrRealPlaces : NumberField.InfinitePlace.nrRealPlaces K = 3 := by
  rw [nrRealPlaces_of_RankUnitsCertificate RC]
  rfl

theorem K_minowski : minkowskiBoundFB K ≤ (170.32735084835014 : ℝ) := by
  refine K_minkowski_decimal _ ?_
  erw [K_nrComplexPlaces, K_discr, K_finrank]
  have hraux: √587412 ≤ 766.428089 := by
      refine Real.sqrt_le_iff.mpr ?_
      norm_num
  have : 0.2222222222222222 * √587412 ≤ 170.327353 := by
    refine le_trans (mul_le_mul_of_nonneg (by rfl) hraux (by norm_num) (by norm_num)) ?_
    norm_num
  norm_num
  try {linarith}

def s := ![11, 11, 11, 6]

def BM : (i : Fin 4) → Fin (e i) → (Fin 2 → ℕ) := by 
  rintro ⟨i, hi⟩ 
  interval_cases i 
  exact ![![1, 1], ![2, 2], ![2, 0], ![1, 0], ![2, 0], ![0, 2], ![0, 1], ![2, 1], ![1, 2], ![1, 0], ![0, 2], ![2, 2]]
  exact ![![1, 2], ![1, 2], ![0, 2], ![2, 2], ![1, 1], ![0, 0], ![0, 0], ![0, 0], ![2, 1], ![2, 1], ![2, 1], ![1, 1]]
  exact ![![0, 2], ![0, 2], ![0, 2], ![1, 2], ![0, 2], ![2, 0], ![2, 0], ![2, 0], ![1, 0], ![2, 1], ![0, 1], ![1, 0]]
  exact ![![0, 1], ![0, 1], ![0, 1], ![1, 2], ![0, 1]]

lemma primesGenerationBelow : {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < 171} ⊆ Set.range (Fin.addCasesIter e 𝔭) := by
  rw [← cert_eq_𝔭]
  refine le_primes_below_bound_of_PrimesBelowBoundCertificate_le_of_eq (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv PB171

def 𝔭' : Fin 41 → nonZeroDivisors (Ideal O) := by
  intro i
  have : PB171.β i ∈ List.ofFn PB171.β := by
    simp only [List.mem_ofFn, exists_apply_eq_apply]
  refine Ideal.toNonZeroDivisorOfNeZero ((PB171.β) i)
    (fun hc => ((zero_ne_mem_of_PrimesBelowCertificate_Fn _ PB171) (hc ▸ this) ))

def J : Fin 2 → Ideal O := ![J0,J1]

def J' :  Fin 2 → nonZeroDivisors (Ideal O) := by
  refine fun i => Ideal.toNonZeroDivisorOfNeZero (J i) (?_ )
  unfold J
  rw [← Submodule.zero_eq_bot, ← pow_ne_zero_iff (n := ![3, 3] i) (by fin_cases i <;> decide) , NPSU3.h]
  simp only [ Submodule.zero_eq_bot, ne_eq, Ideal.span_singleton_eq_bot, NPSU3]
  fin_cases i
  · dsimp [alpha0] ; rw [(LinearEquiv.map_eq_zero_iff B.equivFun.symm)] ; decide 
  · dsimp [alpha1] ; rw [(LinearEquiv.map_eq_zero_iff B.equivFun.symm)] ; decide 

lemma 𝔭'_apply : ∀ (i : Fin 41), ↑(𝔭' i) = (Fin.addCasesIter e 𝔭) i := by
  intro i
  rw [← cert_eq_𝔭]
  rfl

lemma J'_apply : ∀ (i : Fin 2), ↑(J' i) = J i := by
  intro i
  rfl

lemma relations_proof0 (i : Fin 12) : IsInClass O J (𝔭 0 i) (BM 0 i) := by
  show IsInClass O J (𝔭 0 i) (![![1, 1], ![2, 2], ![2, 0], ![1, 0], ![2, 0], ![0, 2], ![0, 1], ![2, 1], ![1, 2], ![1, 0], ![0, 2], ![2, 2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R3N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R5N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R5N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R7N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R13N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R13N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R17N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R19N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R23N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R29N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R31N1

lemma relations_proof1 (i : Fin 12) : IsInClass O J (𝔭 1 i) (BM 1 i) := by
  show IsInClass O J (𝔭 1 i) (![![1, 2], ![1, 2], ![0, 2], ![2, 2], ![1, 1], ![0, 0], ![0, 0], ![0, 0], ![2, 1], ![2, 1], ![2, 1], ![1, 1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R37N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R37N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R43N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R59N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R61N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R73N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R73N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R73N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R79N1

lemma relations_proof2 (i : Fin 12) : IsInClass O J (𝔭 2 i) (BM 2 i) := by
  show IsInClass O J (𝔭 2 i) (![![0, 2], ![0, 2], ![0, 2], ![1, 2], ![0, 2], ![2, 0], ![2, 0], ![2, 0], ![1, 0], ![2, 1], ![0, 1], ![1, 0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R83N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R83N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R83N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R89N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R97N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R101N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R101N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R101N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R103N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R109N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R113N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R131N1

lemma relations_proof3 (i : Fin 5) : IsInClass O J (𝔭 3 i) (BM 3 i) := by
  show IsInClass O J (𝔭 3 i) (![![0, 1], ![0, 1], ![0, 1], ![1, 2], ![0, 1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R139N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R139N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R139N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R163N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R167N1

theorem class_group_generator : Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (J' i))) = ⊤ := by
  refine subgroup_closure_eq_classGroup'' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv
      𝔭'_apply J'_apply ?_ primesGenerationBelow (Fin.addCasesIter e BM) ?_
  · refine lt_of_le_of_lt K_minowski ?_
    norm_num
  · refine forall_addCasesIter_prop 𝔭 BM (IsInClass O J) ?_
    rintro ⟨i, hi⟩
    interval_cases i
    · exact relations_proof0
    · exact relations_proof1
    · exact relations_proof2
    · exact relations_proof3

def ClassGroupO_equiv : (∀ i : Fin 2 , (ZMod (![3, 3] i))) ≃+ Additive (ClassGroup O) := by
  haveI : ∀ (i : Fin 2), NeZero (![3, 3] i) := by
    intro i
    fin_cases i <;>  exact {out := by decide}
  refine ClassGroup_equiv_of_pSaturatedCertificate J'_apply NPSU3.h class_group_generator ?_
  rintro ⟨p, hp1, hp2⟩
  have : ∏ i, ![3, 3] i = ∏ i, (![3] i) ^ (![2] i)  := by decide
  rw [this] at hp2
  have hp_cases : p ∈ [3] := by
    obtain ⟨j ,hj1, hj2⟩  := Prime.exists_mem_finset_dvd (Nat.prime_iff.mp hp1) hp2
    show p ∈ List.ofFn ![3]
    rw [(Nat.prime_dvd_prime_iff_eq hp1 ?_).1 (Nat.Prime.dvd_of_dvd_pow hp1 hj2), List.mem_ofFn]
    exact ⟨j, rfl⟩
    fin_cases j <;> decide
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hp_cases
  by_cases h : p = 3
  simp_rw [h] ; right
  exact NPSU3
  omega

def class_group_equiv : (∀ i : Fin 2 , (ZMod (![3, 3] i))) ≃+ Additive (ClassGroup (NumberField.RingOfIntegers K)) := by
 refine AddEquiv.trans ClassGroupO_equiv ?_
 exact MulEquiv.toAdditive (ClassGroup.congr
    ((Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv))

theorem class_number_K_eq_9 : NumberField.classNumber K = 9 := by
  unfold NumberField.classNumber
  rw [Fintype.card_eq_nat_card, ← Nat.card_congr (Additive.toMul),
    Nat.card_congr (class_group_equiv).symm.toEquiv, Nat.card_pi]
  simp [Fin.isValue, Fin.prod_succ]
  try decide
