import IdealArithmetic.IdealArithmetic
import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem
import IdealArithmetic.PrincipalityCertificate
import IdealArithmetic.Examples.NF49.NF49RI


--------------------------------------------
-- EXAMPLE
--------------------------------------------

/- Number field `K(α)` with with α root of polynomial `X^5 + 15*X^3 - 70*X^2 + 60*X - 24`.
Class number `5`, generated by class of ideal `J = (2, -5/24*a^4 - 1/12*a^3 - 71/24*a^2 + 13*a - 9/2)`. We have `J ^ 5 = (α)`. -/

/- Ring of integers with basis `[1, a, a^2, 1/2*a^3 - 1/2*a, 1/24*a^4 - 1/12*a^3 - 5/24*a^2 - 1/2*a - 1/2]` -/

open BigOperators Classical Matrix Polynomial

lemma B_one : B 0 = 1 := by
  refine basisOfBuilderLists_zero_eq_one _ _ BQ

lemma B_one_repr : B.equivFun.symm ![1, 0, 0, 0, 0] = 1 := by
  rw [Basis.equivFun_symm_eq_repr_symm']
  apply_fun B.repr
  rw [← B_one]
  simp only [Basis.repr_symm_apply, Basis.repr_linearCombination, Fin.isValue, Basis.repr_self]
  ext i
  fin_cases i <;> norm_num
  · exact LinearEquiv.injective B.repr

instance : IsDomain O := by
  haveI hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) T) :=
  {out := (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible}
  letI hola : Field K := by unfold K ; exact AdjoinRoot.instField
  refine Subalgebra.isDomain O

noncomputable section

instance hq41 : Fact $ Nat.Prime 41 := by decide
instance hq61 : Fact $ Nat.Prime 61 := by decide
instance hq71 : Fact $ Nat.Prime 71 := by decide

def R41 : IsOrderOf (6 : ZMod 41) 40 where
 m := 2
 P := ![2, 5]
 e := ![3, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def R61 : IsOrderOf (2 : ZMod 61) 60 where
 m := 3
 P := ![2, 3, 5]
 e := ![2, 1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def R71 : IsOrderOf (7 : ZMod 71) 70 where
 m := 3
 P := ![2, 5, 7]
 e := ![1, 1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide


def I0 : Ideal O := Ideal.span (Set.range (fun i ↦ B.equivFun.symm (![![41, 0, 0, 0, 0], ![-5, 1, 0, 0, 0]] i)))
def I1 : Ideal O := Ideal.span (Set.range (fun i ↦ B.equivFun.symm (![![61, 0, 0, 0, 0], ![-14, 1, 0, 0, 0]] i)))
def I2 : Ideal O := Ideal.span (Set.range (fun i ↦ B.equivFun.symm (![![71, 0, 0, 0, 0], ![34, 1, 0, 0, 0]] i)))

def A0: IdealEqSpanCertificate O ℤ timesTableO I0
 ![![41, 0, 0, 0, 0], ![-5, 1, 0, 0, 0]]
 ![![41, 0, 0, 0, 0], ![36, 1, 0, 0, 0], ![16, 0, 1, 0, 0], ![22, 0, 0, 1, 0], ![37, 0, 0, 0, 1]] where
  T := Table
  heq := timesTableT_eq_Table
  hieq := rfl
  M :=![![![41, 0, 0, 0, 0], ![0, 41, 0, 0, 0], ![0, 0, 41, 0, 0], ![0, 0, 0, 41, 0], ![0, 0, 0, 0, 41]], ![![-5, 1, 0, 0, 0], ![0, -5, 1, 0, 0], ![0, 1, -5, 2, 0], ![6, 7, 2, -3, 12], ![0, -5, 2, -2, -7]]]
  hmulB := by decide
  f := ![![![1006668, -953290, 3876099, -1552752, 3024], ![8242271, 180195, 31815918, -10332, 0]], ![![898806, -851150, 3460796, -1386383, 2700], ![7359132, 160884, 28407014, -9225, 0]], ![![395480, -374504, 1522746, -610007, 1188], ![3238062, 70808, 12499055, -4059, 0]], ![![539282, -510690, 2076483, -831832, 1620], ![4415466, 96537, 17044254, -5535, 0]], ![![908456, -860286, 3497943, -1401264, 2729], ![7438143, 162615, 28711926, -9324, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-36, 41, 0, 0, 0], ![-16, 0, 41, 0, 0], ![-22, 0, 0, 41, 0], ![-37, 0, 0, 0, 41]], ![![-1, 1, 0, 0, 0], ![4, -5, 1, 0, 0], ![0, 1, -5, 2, 0], ![-16, 7, 2, -3, 12], ![11, -5, 2, -2, -7]]]
  hle1 := by decide
  hle2 := by decide

lemma N0 : Nat.card (O ⧸ I0) = 41 := by
 exact ideal_norm_eq_prod' _ _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A0)

def A1: IdealEqSpanCertificate O ℤ timesTableO I1
 ![![61, 0, 0, 0, 0], ![-14, 1, 0, 0, 0]]
 ![![61, 0, 0, 0, 0], ![47, 1, 0, 0, 0], ![48, 0, 1, 0, 0], ![38, 0, 0, 1, 0], ![59, 0, 0, 0, 1]] where
  T := Table
  heq := timesTableT_eq_Table
  hieq := rfl
  M :=![![![61, 0, 0, 0, 0], ![0, 61, 0, 0, 0], ![0, 0, 61, 0, 0], ![0, 0, 0, 61, 0], ![0, 0, 0, 0, 61]], ![![-14, 1, 0, 0, 0], ![0, -14, 1, 0, 0], ![0, 1, -14, 2, 0], ![6, 7, 2, -12, 12], ![0, -5, 2, -2, -16]]]
  hmulB := by decide
  f := ![![![68001043, -16453633, 180148421, -25765180, 17172], ![296252844, 5520317, 785314244, -87291, 0]], ![![52604629, -12728296, 139360223, -19931572, 13284], ![229176940, 4270427, 607507784, -67527, 0]], ![![53887600, -13038730, 142759058, -20417680, 13608], ![234766322, 4374555, 622324196, -69174, 0]], ![![42340284, -10244717, 112167888, -16042471, 10692], ![184459370, 3437174, 488969260, -54351, 0]], ![![65771485, -15914177, 174241916, -24920420, 16609], ![286539568, 5339286, 759566236, -84429, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-47, 61, 0, 0, 0], ![-48, 0, 61, 0, 0], ![-38, 0, 0, 61, 0], ![-59, 0, 0, 0, 61]], ![![-1, 1, 0, 0, 0], ![10, -14, 1, 0, 0], ![9, 1, -14, 2, 0], ![-11, 7, 2, -12, 12], ![19, -5, 2, -2, -16]]]
  hle1 := by decide
  hle2 := by decide

lemma N1 : Nat.card (O ⧸ I1) = 61 :=
 ideal_norm_eq_prod' _ _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A1)

def A2: IdealEqSpanCertificate O ℤ timesTableO I2
 ![![71, 0, 0, 0, 0], ![34, 1, 0, 0, 0]]
 ![![71, 0, 0, 0, 0], ![34, 1, 0, 0, 0], ![51, 0, 1, 0, 0], ![39, 0, 0, 1, 0], ![9, 0, 0, 0, 1]] where
  T := Table
  heq := timesTableT_eq_Table
  hieq := rfl
  M :=![![![71, 0, 0, 0, 0], ![0, 71, 0, 0, 0], ![0, 0, 71, 0, 0], ![0, 0, 0, 71, 0], ![0, 0, 0, 0, 71]], ![![34, 1, 0, 0, 0], ![0, 34, 1, 0, 0], ![0, 1, 34, 2, 0], ![6, 7, 2, 36, 12], ![0, -5, 2, -2, 32]]]
  hmulB := by decide
  f := ![![![108669917, 10619598, 398550101, 23533944, 27540], ![-226899599, 9016787, -832522002, -162945, 0]], ![![53269552, 5205664, 195367644, 11536244, 13500], ![-111225262, 4420034, -408098912, -79875, 0]], ![![78838905, 7704411, 289144061, 17073638, 19980], ![-164613321, 6541586, -603986279, -118215, 0]], ![![59661899, 5830336, 218811824, 12920597, 15120], ![-124572295, 4950458, -457070913, -89460, 0]], ![![13775035, 1346134, 50520435, 2983176, 3491], ![-28761869, 1142997, -105530958, -20655, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-34, 71, 0, 0, 0], ![-51, 0, 71, 0, 0], ![-39, 0, 0, 71, 0], ![-9, 0, 0, 0, 71]], ![![0, 1, 0, 0, 0], ![-17, 34, 1, 0, 0], ![-26, 1, 34, 2, 0], ![-26, 7, 2, 36, 12], ![-2, -5, 2, -2, 32]]]
  hle1 := by decide
  hle2 := by decide

lemma N2 : Nat.card (O ⧸ I2) = 71 :=
 ideal_norm_eq_prod' _ _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A2)


def zeta1 := B.equivFun.symm ![1640, 830, 1218, 991, 2364]

def zeta2 := B.equivFun.symm ![133, -209, 93, 18, 98]

def alpha := B.equivFun.symm ![-2422, 2032, -692, -138, -851]

def Log00Mem : IdealMemCertificate O ℤ B I0
  ![![41, 0, 0, 0, 0], ![36, 1, 0, 0, 0], ![16, 0, 1, 0, 0], ![22, 0, 0, 1, 0], ![37, 0, 0, 0, 1]] ![1608, 830, 1218, 991, 2364] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-3830, 830, 1218, 991, 2364]
 hmem := by decide


def Log00: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R41) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![1640, 830, 1218, 991, 2364]
 hxeq :=  rfl
 m:= 32
 C := ![1608, 830, 1218, 991, 2364]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log00Mem
 k :=  10
 hpow := by decide
 heql := by decide

def Log01Mem : IdealMemCertificate O ℤ B I0
  ![![41, 0, 0, 0, 0], ![36, 1, 0, 0, 0], ![16, 0, 1, 0, 0], ![22, 0, 0, 1, 0], ![37, 0, 0, 0, 1]] ![118, -209, 93, 18, 98] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![52, -209, 93, 18, 98]
 hmem := by decide

def Log01: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R41) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![133, -209, 93, 18, 98]
 hxeq :=  rfl
 m:= 15
 C := ![118, -209, 93, 18, 98]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log01Mem
 k :=  37
 hpow := by decide
 heql := by decide

def Log02Mem : IdealMemCertificate O ℤ B I0
  ![![41, 0, 0, 0, 0], ![36, 1, 0, 0, 0], ![16, 0, 1, 0, 0], ![22, 0, 0, 1, 0], ![37, 0, 0, 0, 1]] ![-2455, 2032, -692, -138, -851] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-732, 2032, -692, -138, -851]
 hmem := by decide

def Log02: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R41) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 3 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-2422, 2032, -692, -138, -851]
 hxeq :=  rfl
 m:= 33
 C := ![-2455, 2032, -692, -138, -851]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log02Mem
 k :=  18
 hpow := by decide
 heql := by decide

def Log10Mem : IdealMemCertificate O ℤ B I1
  ![![61, 0, 0, 0, 0], ![47, 1, 0, 0, 0], ![48, 0, 1, 0, 0], ![38, 0, 0, 1, 0], ![59, 0, 0, 0, 1]] ![1633, 830, 1218, 991, 2364] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-4475, 830, 1218, 991, 2364]
 hmem := by decide

def Log10: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 4 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![1640, 830, 1218, 991, 2364]
 hxeq :=  rfl
 m:= 7
 C := ![1633, 830, 1218, 991, 2364]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log10Mem
 k :=  49
 hpow := by decide
 heql := by decide

def Log11Mem : IdealMemCertificate O ℤ B I1
  ![![61, 0, 0, 0, 0], ![47, 1, 0, 0, 0], ![48, 0, 1, 0, 0], ![38, 0, 0, 1, 0], ![59, 0, 0, 0, 1]] ![131, -209, 93, 18, 98] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-16, -209, 93, 18, 98]
 hmem := by decide

def Log11: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![133, -209, 93, 18, 98]
 hxeq :=  rfl
 m:= 2
 C := ![131, -209, 93, 18, 98]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log11Mem
 k :=  1
 hpow := by decide
 heql := by decide

def Log12Mem : IdealMemCertificate O ℤ B I1
  ![![61, 0, 0, 0, 0], ![47, 1, 0, 0, 0], ![48, 0, 1, 0, 0], ![38, 0, 0, 1, 0], ![59, 0, 0, 0, 1]] ![-2437, 2032, -692, -138, -851] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-152, 2032, -692, -138, -851]
 hmem := by decide

def Log12: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 3 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-2422, 2032, -692, -138, -851]
 hxeq :=  rfl
 m:= 15
 C := ![-2437, 2032, -692, -138, -851]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log12Mem
 k :=  28
 hpow := by decide
 heql := by decide

def Log20Mem : IdealMemCertificate O ℤ B I2
  ![![71, 0, 0, 0, 0], ![34, 1, 0, 0, 0], ![51, 0, 1, 0, 0], ![39, 0, 0, 1, 0], ![9, 0, 0, 0, 1]] ![1589, 830, 1218, 991, 2364] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![-2094, 830, 1218, 991, 2364]
 hmem := by decide

def Log20: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R71) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![1640, 830, 1218, 991, 2364]
 hxeq :=  rfl
 m:= 51
 C := ![1589, 830, 1218, 991, 2364]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log20Mem
 k :=  5
 hpow := by decide
 heql := by decide

def Log21Mem : IdealMemCertificate O ℤ B I2
  ![![71, 0, 0, 0, 0], ![34, 1, 0, 0, 0], ![51, 0, 1, 0, 0], ![39, 0, 0, 1, 0], ![9, 0, 0, 0, 1]] ![73, -209, 93, 18, 98] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![12, -209, 93, 18, 98]
 hmem := by decide

def Log21: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R71) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![133, -209, 93, 18, 98]
 hxeq :=  rfl
 m:= 60
 C := ![73, -209, 93, 18, 98]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log21Mem
 k :=  66
 hpow := by decide
 heql := by decide

def Log22Mem : IdealMemCertificate O ℤ B I2
  ![![71, 0, 0, 0, 0], ![34, 1, 0, 0, 0], ![51, 0, 1, 0, 0], ![39, 0, 0, 1, 0], ![9, 0, 0, 0, 1]] ![-2462, 2032, -692, -138, -851] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![-327, 2032, -692, -138, -851]
 hmem := by decide

def Log22: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R71) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-2422, 2032, -692, -138, -851]
 hxeq :=  rfl
 m:= 40
 C := ![-2462, 2032, -692, -138, -851]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log22Mem
 k :=  46
 hpow := by decide
 heql := by decide


def J : Ideal O := Ideal.span (Set.range (fun i ↦ B.equivFun.symm (![![2, 0, 0, 0, 0], ![-7, 10, -4, -1, -5]] i)))
def MulJ0 : IdealMulEqCertificate O ℤ timesTableO (J) J
  ![![2, 0, 0, 0, 0], ![-7, 10, -4, -1, -5]] ![![2, 0, 0, 0, 0], ![-7, 10, -4, -1, -5]]
  ![![2, 0, 0, 0, 0], ![8, -3, 1, 0, 1]] where
 T := Table
 heq := timesTableT_eq_Table
 hI1 := rfl
 hI2 := rfl
 M :=  ![![![4, 0, 0, 0, 0], ![-14, 20, -8, -2, -10]], ![![-14, 20, -8, -2, -10], ![-44, 34, -10, -2, -13]]]
 hmul := by decide
 f :=  ![![![![-276347, 53335, 146660, 113148, 245026], ![271450, -384705, 6921, 0, 22353]], ![![0, 0, 0, 0, 0], ![-471, -24, 0, 0, -1]]], ![![![-76049, 14703, 40389, 31146, 67482], ![74704, -105879, 1884, 0, 6147]], ![![0, 0, 0, 0, 0], ![-129, -7, -1, 0, 0]]]]
 g :=  ![![![![2, 0, 0, 0, 0], ![0, 0, 0, 0, 0]], ![![257, 642, -120, 29, -210], ![-66, -298, -30, 0, 0]]], ![![![257, 642, -120, 29, -210], ![-66, -298, -30, 0, 0]], ![![406, 1002, -185, 46, -326], ![-107, -467, -47, 0, 0]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ1 : IdealMulEqCertificate O ℤ timesTableO (J*J) J
  ![![2, 0, 0, 0, 0], ![8, -3, 1, 0, 1]] ![![2, 0, 0, 0, 0], ![-7, 10, -4, -1, -5]]
  ![![4, 0, 0, 0, 0], ![-8, 17, -7, -2, -9]] where
 T := Table
 heq := timesTableT_eq_Table
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ timesTableO _ _ _ _ _ MulJ0
 hI2 := rfl
 M :=  ![![![4, 0, 0, 0, 0], ![-14, 20, -8, -2, -10]], ![![16, -6, 2, 0, 2], ![-32, 55, -23, -6, -27]]]
 hmul := by decide
 f :=  ![![![![84, -26, -40, -31, -68], ![-74, 108, 0, 0, -6]], ![![0, 0, 0, 0, 0], ![0, 0, 0, 0, 0]]], ![![![-297242, -917142, -688327, 57242, -1096717], ![544466, -492324, 770961, 0, 181359]], ![![0, 0, 0, 0, 0], ![-22067, -570, -26, 0, 0]]]]
 g :=  ![![![![10594, -2109, -3489, -4287, -6009], ![-8262, 9036, 324, 0, -6]], ![![-38477, 7601, 12703, 15589, 21866], ![30045, -32844, -1176, 0, 21]]], ![![![42760, -8466, -14110, -17319, -24292], ![-33378, 36492, 1308, 0, -24]], ![![-88372, 17448, 29178, 35806, 50223], ![69011, -75438, -2700, 0, 48]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ2 : IdealMulEqCertificate O ℤ timesTableO (J*J*J) J
  ![![4, 0, 0, 0, 0], ![-8, 17, -7, -2, -9]] ![![2, 0, 0, 0, 0], ![-7, 10, -4, -1, -5]]
  ![![4, 0, 0, 0, 0], ![6, -3, 1, 0, 1]] where
 T := Table
 heq := timesTableT_eq_Table
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ timesTableO _ _ _ _ _ MulJ1
 hI2 := rfl
 M :=  ![![![8, 0, 0, 0, 0], ![-28, 40, -16, -4, -20]], ![![-16, 34, -14, -4, -18], ![-106, 103, -35, -8, -43]]]
 hmul := by decide
 f :=  ![![![![-487245378490, 172647485030, 301322591210, 231479952308, 551426110021], ![471645816264, -708645438578, -42430434620, 0, 5196264423]], ![![1708083822, 34488555, 1426904, 0, 0], ![-19479, -272, 138, 0, -1]]], ![![![-501577859723, 177725966930, 310186093200, 238289010369, 567646488333], ![485519431304, -729490474566, -43678539646, 0, 5349114232]], ![![1758327663, 35503047, 1468877, 0, 0], ![-20052, -280, 142, 0, -1]]]]
 g :=  ![![![![410, 708, -428, -32, -1052], ![-272, -2112, 64, 0, 0]], ![![-6799, -11555, 6997, 521, 17217], ![4528, 34620, -1044, 0, 0]]], ![![![-5395, -9167, 5551, 413, 13659], ![3594, 27468, -828, 0, 0]], ![![-19096, -32456, 19655, 1465, 48363], ![12713, 97236, -2934, 0, 0]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ3 : IdealMulEqCertificate O ℤ timesTableO (J*J*J*J) J
  ![![4, 0, 0, 0, 0], ![6, -3, 1, 0, 1]] ![![2, 0, 0, 0, 0], ![-7, 10, -4, -1, -5]]
  ![![-2422, 2032, -692, -138, -851]] where
 T := Table
 heq := timesTableT_eq_Table
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ timesTableO _ _ _ _ _ MulJ2
 hI2 := rfl
 M :=  ![![![8, 0, 0, 0, 0], ![-28, 40, -16, -4, -20]], ![![12, -6, 2, 0, 2], ![-18, 35, -15, -4, -17]]]
 hmul := by decide
 f :=  ![![![![-1141417615015, 259961403860, 590347818801, 523934688194, 1087931728530], ![1132276368893, -1657976109531, 10327424198, 0, 42208944764]], ![![2552945847, -374618619, -11031777, 0, 0], ![-139065, -519, -3243, 0, 0]]]]
 g :=  ![![![![-11, -18, -2, 3, -28]], ![![13, -54, 46, -24, -5]]], ![![![30, 26, 18, -4, 60]], ![![-9, 103, -71, 47, 31]]]]
 hle1 := by decide
 hle2 := by decide

lemma J5 : J ^ 5 =  Ideal.span {alpha} := by
 simp only [pow_succ, pow_one, pow_zero, one_mul]
 simp [ideal_eq_mul_of_IdealMulEqCertificate O ℤ timesTableO _ _ _ _ _ MulJ3, alpha]
 rfl

lemma isUnit_zeta1 : IsUnit zeta1 := by
 apply isUnit_of_mul_eq_one _ (B.equivFun.symm ![-5424574, 3240098, -817290, -84269, -1056426])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul timesTableO.table B _ _ _ timesTableO.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ timesTableT_eq_Table]
 decide

lemma isUnit_zeta2 : IsUnit zeta2 := by
 apply isUnit_of_mul_eq_one _ (B.equivFun.symm ![190721077, -40049621, 221123523, 75455658, 207020810])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul timesTableO.table B _ _ _ timesTableO.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ timesTableT_eq_Table]
 decide
