
import IdealArithmetic.CertificateDedekind
import IdealArithmetic.CertifyAdjoinRoot
import Mathlib.Tactic.NormNum.Prime
import IdealArithmetic.MaximalAPI
import Mathlib.NumberTheory.NumberField.Basic
import IdealArithmetic.Examples.NF25.Irreducible25
import IdealArithmetic.ResultantRecursive
import IdealArithmetic.DiscriminantSubalgebraBuilder

/- Number field `K(α)` with with α root of polynomial `X^5 + 5*X^3 - 30*X^2 - 96`.
Class number `5`, generated by class of ideal `J = (2, 1/16*a^4 - 1/4*a^3 + 5/16*a^2 - 17/8*a + 11/2)`. We have `J ^ 5` is principal. -/

/- Ring of integers with basis `[1, a, 1/2*a^2 - 1/2*a, 1/2*a^3 - 1/2*a, 1/16*a^4 - 1/4*a^3 - 3/16*a^2 + 3/8*a - 1/2]` -/

open Polynomial

noncomputable def T : ℤ[X] := X^5 + 5*X^3 - 30*X^2 - 96
lemma T_def : T = X^5 + 5*X^3 - 30*X^2 - 96 := rfl

def K := AdjoinRoot (map (algebraMap ℤ ℚ) T)

noncomputable instance : CommRing K := by
  unfold K
  infer_instance

noncomputable instance : Algebra ℚ K := by
  unfold K
  infer_instance

local notation "l" => [-96, 0, -30, 5, 0, 1]

noncomputable def Adj : IsAdjoinRoot K (map (algebraMap ℤ ℚ) T) :=
   AdjoinRoot.isAdjoinRoot _

local notation "θ" => Adj.root

lemma T_ofList : ofList l = T := by
  rw [T_def] ; norm_num ; ring

-- We build the subalgebra with integral basis
-- [1, a, 1/2*a^2 - 1/2*a, 1/2*a^3 - 1/2*a, 1/16*a^4 - 1/4*a^3 - 3/16*a^2 + 3/8*a - 1/2]

noncomputable def BQ : SubalgebraBuilderLists 5 ℤ  ℚ K T l where
 d :=  16
 hlen := rfl
 htr := rfl
 hofL := T_ofList.symm
 hm := rfl
 B := ![![16, 0, 0, 0, 0], ![0, 16, 0, 0, 0], ![0, -8, 8, 0, 0], ![0, -8, 0, 8, 0], ![-8, 6, -3, -4, 1]]
 a := ![ ![![1, 0, 0, 0, 0],![0, 1, 0, 0, 0],![0, 0, 1, 0, 0],![0, 0, 0, 1, 0],![0, 0, 0, 0, 1]],
      ![![0, 1, 0, 0, 0],![0, 1, 2, 0, 0],![0, 0, -1, 1, 0],![4, 0, 2, 4, 8],![4, 1, 3, -3, -4]],
      ![![0, 0, 1, 0, 0],![0, 0, -1, 1, 0],![2, 0, 2, 1, 4],![22, 6, 14, -5, -4],![-16, 0, -11, 3, -2]],
      ![![0, 0, 0, 1, 0],![4, 0, 2, 4, 8],![22, 6, 14, -5, -4],![-14, 30, -10, 1, -28],![-12, -18, 0, 10, 30]],
      ![![0, 0, 0, 0, 1],![4, 1, 3, -3, -4],![-16, 0, -11, 3, -2],![-12, -18, 0, 10, 30],![30, 9, 12, -12, -20]]]
 s := ![![[], [], [], [], []],![[], [], [], [], [-16]],![[], [], [], [-64], [40, -8]],![[], [], [-64],
  [0, -64], [72, 32, -8]],![[], [-16], [40, -8], [72, 32, -8], [-106, -5, 8, -1]]]
 h := Adj
 honed := by decide
 hd := by norm_num
 hcc := by decide
 hin := by decide
 hsymma := by decide
 hc_le := by decide

lemma T_degree : T.natDegree = 5 := (SubalgebraBuilderOfList T l BQ).hdeg

lemma T_monic : Monic T := by
  rw [← T_ofList]
  refine monic_ofList l rfl

lemma T_irreducible : Irreducible T := irreducible_T

noncomputable def Om : Subalgebra ℤ K := integralClosure ℤ K

noncomputable def O := subalgebraOfBuilderLists T l BQ

def hm : O ≤ Om := le_integralClosure_of_basis O (basisOfBuilderLists T l BQ)

noncomputable def B' : Basis (Fin 5) ℤ Om :=
  Basis.reindex (AdjoinRoot.basisIntegralClosure T_monic
    (Irreducible.prime T_irreducible)) (finCongr T_degree)

instance OmFree : Module.Free ℤ Om := Module.Free.of_basis B'
instance OmFinite : Module.Finite ℤ Om := Module.Finite.of_basis B'

noncomputable def timesTableO : TimesTable (Fin 5) ℤ O :=
  timesTableOfSubalgebraBuilderLists T l BQ

noncomputable def B : Basis (Fin 5) ℤ O := timesTableO.basis

def Table : Fin 5 → Fin 5 → List ℤ :=
 ![ ![[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]],
 ![[0, 1, 0, 0, 0], [0, 1, 2, 0, 0], [0, 0, -1, 1, 0], [4, 0, 2, 4, 8], [4, 1, 3, -3, -4]],
 ![[0, 0, 1, 0, 0], [0, 0, -1, 1, 0], [2, 0, 2, 1, 4], [22, 6, 14, -5, -4], [-16, 0, -11, 3, -2]],
 ![[0, 0, 0, 1, 0], [4, 0, 2, 4, 8], [22, 6, 14, -5, -4], [-14, 30, -10, 1, -28], [-12, -18, 0, 10, 30]],
 ![[0, 0, 0, 0, 1], [4, 1, 3, -3, -4], [-16, 0, -11, 3, -2], [-12, -18, 0, 10, 30], [30, 9, 12, -12, -20]]]

lemma timesTableT_eq_Table :  ∀ i j , Table i j = List.ofFn (timesTableO.table i j) := by decide

lemma hroot_mem : θ ∈ O := by
  refine root_in_subalgebra_lists T l BQ ![0, 1, 0, 0, 0] [] (by decide)

instance hp2: Fact $ Nat.Prime 2 := fact_iff.2 (by norm_num)
instance hp3: Fact $ Nat.Prime 3 := fact_iff.2 (by norm_num)
instance hp5: Fact $ Nat.Prime 5 := fact_iff.2 (by norm_num)

def CD3: CertificateDedekindCriterionLists l 3 where
 n :=  3
 a' := []
 b' :=  [2]
 k := [1, 0, 1, 0, 1]
 f := [32, 0, 10, -1]
 g :=  [0, 2, 0, 1]
 h :=  [0, 0, 1]
 a :=  [2, 2, 1]
 b :=  [1, 1, 1]
 c :=  []
 hdvdpow := rfl
 hcop := rfl
 hf := by rfl
 habc := by rfl

def CD5: CertificateDedekindCriterionLists l 5 where
 n :=  5
 a' := []
 b' :=  [1]
 k := [1]
 f := [20, 1, 7, 0, 1]
 g :=  [4, 1]
 h :=  [1, 1, 1, 1, 1]
 a :=  [4]
 b :=  [4, 3, 1, 1]
 c :=  []
 hdvdpow := rfl
 hcop := rfl
 hf := by rfl
 habc := by rfl

noncomputable def D : CertificateDedekindAlmostAllLists T l [2] where
 n := 3
 p := ![2, 3, 5]
 exp := ![18, 5, 5]
 pdgood := [3, 5]
 hsub := by decide
 hp := by
  intro i ; fin_cases i
  exact hp2.out
  exact hp3.out
  exact hp5.out
 a := [-2073600000, -453600000, 86400000, 194400000]
 b := [725760000, 1080000000, 12960000, -17280000, -38880000]
 hab := by decide
 hd := by
  intro p hp
  fin_cases hp
  exact satisfiesDedekindCriterion_of_certificate_lists T l 3 T_ofList CD3
  exact satisfiesDedekindCriterion_of_certificate_lists T l 5 T_ofList CD5

noncomputable def M2 : MaximalOrderCertificateWLists 2 O Om hm where
 m := 2
 n := 3
 t :=  3
 hpos := by decide
 TT := timesTableO
 B' := B'
 T := Table
 heq := timesTableT_eq_Table
 TMod := ![![[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]],
![[0, 1, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 1, 0], [0, 0, 0, 0, 0], [0, 1, 1, 1, 0]],
![[0, 0, 1, 0, 0], [0, 0, 1, 1, 0], [0, 0, 0, 1, 0], [0, 0, 0, 1, 0], [0, 0, 1, 1, 0]],
![[0, 0, 0, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 0]],
![[0, 0, 0, 0, 1], [0, 1, 1, 1, 0], [0, 0, 1, 1, 0], [0, 0, 0, 0, 0], [0, 1, 0, 0, 0]]]
 hTMod := by decide
 hle := by decide
 b1 := ![![0, 1, 0, 0, 1],![0, 0, 1, 1, 0]]
 b2 := ![![1, 0, 0, 0, 0],![0, 1, 0, 0, 0],![0, 0, 1, 0, 0]]
 v := ![![0, 1, 0, 0, 1],![0, 0, 1, 1, 0]]
 w := ![![1, 0, 0, 0, 0],![0, 1, 0, 0, 0],![0, 0, 1, 0, 0]]
 wFrob := ![![1, 0, 0, 0, 0],![0, 1, 0, 0, 0],![0, 0, 0, 1, 0]]
 v_ind := ![1, 2]
 w_ind := ![0, 1, 3]
 hmod1 := by decide
 hmod2 := by decide
 hindv := by decide
 hindw := by decide
 hvFrobKer := by decide
 hwFrobComp := by decide
 g := ![![1, 1, 0, 1, 1],![0, 1, 0, 0, 0],![0, 1, 0, 1, 1],![0, 0, 1, 1, 0],![0, 0, 0, 1, 0]]
 w1 := ![1, 0]
 w2 := ![1, 0, 0]
 a := ![![13, -2],![-4, -3],![12, -2],![36, 20],![38, 16]]
 c := ![![16, -8, 12],![2, 4, 4],![15, -8, 12],![-12, -27, -14],![-4, -28, -7]]
 hmulw := by decide
 ac_indw := ![Sum.inl 0, Sum.inl 1, Sum.inr 0, Sum.inr 1, Sum.inr 2]
 hacindw := by decide


open BigOperators Classical Matrix Polynomial

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible

noncomputable instance K_field : Field K := by
  unfold K
  infer_instance

instance K_numberField : NumberField K := by
  unfold K
  infer_instance

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ [2]
  · fin_cases hc
    exact pMaximal_of_MaximalOrderCertificateWLists 2 O Om hm M2
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [2] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']


theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by
  rw [O_integral_closure] ; rfl


def SturmRC : SturmBuilderOfList [[-96, 0, -30, 5, 0, 1], [0, -60, 15, 0, 5], [48, 0, 9, -1], [-36, -3, -7], [4, -9], [1]] [-96, 0, -30, 5, 0, 1] [0, -60, 15, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 5 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 1, 49, 81]
  f := [50, 60, 6, 3136]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [-45, -5], [-66, 7], [55, 63]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)

theorem T_discr : discriminant T = 199065600000 := by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  rw [T_ofList]

theorem K_discr : NumberField.discr K = 48600000 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl
