import IdealArithmetic.MordellThueProject.SkolemTimesTable
import IdealArithmetic.MordellExamples.MordellExample17.NF3_1_204_1.UnitsData3_1_204_1

/-!
# The Skolem certificate at `p = 307` for `K = ℚ(θ)`, `θ³ - 12θ - 18 = 0`

`mu` is the last coordinate for the integral basis recorded in `RI3_1_204_1`.  Iterated
multiplication of coordinate vectors modulo `307 ^ 2 = 94249` verifies

* `hC1 … hC102` : the coordinates of `zeta1 ^ r` mod `94249`, one multiplication per step;
* `not_dvd_mu_zeta1_pow` : **(S3)** -- `307 ∤ mu (zeta1 ^ r)` for every `r < 102` outside
  the surviving class `0`;
* `zeta1_pow_102` : **(S1)**, **(S2)** and the re-centering hypothesis, i.e.
  `307 ∤ mu (zeta1 ^ r * δ)` for each surviving `r`, which is what makes each
  surviving class contain exactly one solution.

Generated by `SkolemTableNFLean.sage`.
-/

namespace NF3_1_204_1

set_option linter.all false

open Module

noncomputable section

abbrev pS : ℕ := 307
abbrev mS : ℕ := pS ^ 2

/-- The weights picking out the last coordinate of the integral basis. -/
def kMu : Fin 3 → ℤ := ![0, 0, 1]

/-- `mu`: the last coordinate. -/
abbrev mu : O →ₗ[ℤ] ℤ := muOfBasis timesTableO.basis kMu

lemma mu_one : mu 1 = 0 := by
  have h : mu (B 0) = kMu 0 := muOfBasis_basis (b := timesTableO.basis) kMu 0
  rwa [B_one] at h

/-- The times table of `O`, reduced modulo `94249`. -/
def TMod : Fin 3 → Fin 3 → List (ZMod mS) :=
 ![ ![[1, 0, 0], [0, 1, 0], [0, 0, 1]],
 ![[0, 1, 0], [0, 0, 3], [6, 4, 0]],
 ![[0, 0, 1], [6, 4, 0], [0, 2, 4]]]

lemma hTMod : ∀ i j, List.map (algebraMap ℤ (ZMod mS)) (Table i j) = TMod i j := by decide

/-! ### The coordinate vector of `zeta1` modulo `94249` -/

lemma hbase : coordMod timesTableO.basis mS zeta1 = ![1, 1, 1] := by
  have hv : timesTableO.basis.equivFun zeta1 = ![1, 1, 1] := by
    rw [zeta1]; exact B.equivFun.apply_symm_apply _
  funext i
  simp only [coordMod, Function.comp_apply, hv]
  fin_cases i <;> decide

/-! ### The chain `zeta1 ^ 1, …, zeta1 ^ 102`, one multiplication per step -/

lemma hC0 : coordMod timesTableO.basis mS (zeta1 ^ 0) = ![1, 0, 0] := by
  rw [pow_zero, coordMod_one (b := timesTableO.basis) (i₀ := 0) B_one]
  funext i; fin_cases i <;> decide

lemma hC1 : coordMod timesTableO.basis mS (zeta1 ^ 1) = ![1, 1, 1] := by
  rw [pow_one]; exact hbase

lemma hC2 : coordMod timesTableO.basis mS (zeta1 ^ 2) = ![13, 12, 9] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC1 (by decide)

lemma hC3 : coordMod timesTableO.basis mS (zeta1 ^ 3) = ![139, 127, 94] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC2 (by decide)

lemma hC4 : coordMod timesTableO.basis mS (zeta1 ^ 4) = ![1465, 1338, 990] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC3 (by decide)

lemma hC5 : coordMod timesTableO.basis mS (zeta1 ^ 5) = ![15433, 14095, 10429] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC4 (by decide)

lemma hC6 : coordMod timesTableO.basis mS (zeta1 ^ 6) = ![68328, 54233, 15614] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC5 (by decide)

lemma hC7 : coordMod timesTableO.basis mS (zeta1 ^ 7) = ![16165, 56181, 26350] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC6 (by decide)

lemma hC8 : coordMod timesTableO.basis mS (zeta1 ^ 8) = ![40106, 78174, 33711] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC7 (by decide)

lemma hC9 : coordMod timesTableO.basis mS (zeta1 ^ 9) = ![51673, 67748, 66187] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC8 (by decide)

lemma hC10 : coordMod timesTableO.basis mS (zeta1 ^ 10) = ![7042, 33543, 20358] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC9 (by decide)

lemma hC11 : coordMod timesTableO.basis mS (zeta1 ^ 11) = ![47701, 14158, 20963] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC10 (by decide)

lemma hC12 : coordMod timesTableO.basis mS (zeta1 ^ 12) = ![69929, 55771, 6492] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC11 (by decide)

lemma hC13 : coordMod timesTableO.basis mS (zeta1 ^ 13) = ![66511, 10740, 81204] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC12 (by decide)

lemma hC14 : coordMod timesTableO.basis mS (zeta1 ^ 14) = ![52681, 41941, 33506] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC13 (by decide)

lemma hC15 : coordMod timesTableO.basis mS (zeta1 ^ 15) = ![34118, 86426, 63287] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC14 (by decide)

lemma hC16 : coordMod timesTableO.basis mS (zeta1 ^ 16) = ![84155, 91978, 44337] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC15 (by decide)

lemma hC17 : coordMod timesTableO.basis mS (zeta1 ^ 17) = ![53804, 56075, 16280] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC16 (by decide)

lemma hC18 : coordMod timesTableO.basis mS (zeta1 ^ 18) = ![16689, 54863, 20682] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC17 (by decide)

lemma hC19 : coordMod timesTableO.basis mS (zeta1 ^ 19) = ![92963, 38100, 1941] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC18 (by decide)

lemma hC20 : coordMod timesTableO.basis mS (zeta1 ^ 20) = ![50462, 12362, 28470] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC19 (by decide)

lemma hC21 : coordMod timesTableO.basis mS (zeta1 ^ 21) = ![12707, 345, 41400] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC20 (by decide)

lemma hC22 : coordMod timesTableO.basis mS (zeta1 ^ 22) = ![74679, 74334, 32244] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC21 (by decide)

lemma hC23 : coordMod timesTableO.basis mS (zeta1 ^ 23) = ![54404, 74319, 81905] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC22 (by decide)

lemma hC24 : coordMod timesTableO.basis mS (zeta1 ^ 24) = ![49258, 69188, 27143] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC23 (by decide)

lemma hC25 : coordMod timesTableO.basis mS (zeta1 ^ 25) = ![61750, 86811, 15541] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC24 (by decide)

lemma hC26 : coordMod timesTableO.basis mS (zeta1 ^ 26) = ![16119, 23557, 22892] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC25 (by decide)

lemma hC27 : coordMod timesTableO.basis mS (zeta1 ^ 27) = ![12066, 82758, 12752] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC26 (by decide)

lemma hC28 : coordMod timesTableO.basis mS (zeta1 ^ 28) = ![19632, 31123, 41353] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC27 (by decide)

lemma hC29 : coordMod timesTableO.basis mS (zeta1 ^ 29) = ![77492, 46369, 37019] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC28 (by decide)

lemma hC30 : coordMod timesTableO.basis mS (zeta1 ^ 30) = ![12326, 60206, 24698] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC29 (by decide)

lemma hC31 : coordMod timesTableO.basis mS (zeta1 ^ 31) = ![50505, 84548, 33687] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC30 (by decide)

lemma hC32 : coordMod timesTableO.basis mS (zeta1 ^ 32) = ![5923, 15624, 1339] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC31 (by decide)

lemma hC33 : coordMod timesTableO.basis mS (zeta1 ^ 33) = ![13452, 92077, 59490] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC32 (by decide)

lemma hC34 : coordMod timesTableO.basis mS (zeta1 ^ 34) = ![74613, 76785, 21639] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC33 (by decide)

lemma hC35 : coordMod timesTableO.basis mS (zeta1 ^ 35) = ![5414, 22878, 36167] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC34 (by decide)

lemma hC36 : coordMod timesTableO.basis mS (zeta1 ^ 36) = ![76937, 54059, 66385] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC35 (by decide)

lemma hC37 : coordMod timesTableO.basis mS (zeta1 ^ 37) = ![45609, 85799, 5545] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC36 (by decide)

lemma hC38 : coordMod timesTableO.basis mS (zeta1 ^ 38) = ![28179, 36629, 47984] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC37 (by decide)

lemma hC39 : coordMod timesTableO.basis mS (zeta1 ^ 39) = ![64612, 27983, 990] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC38 (by decide)

lemma hC40 : coordMod timesTableO.basis mS (zeta1 ^ 40) = ![49952, 21969, 59262] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC39 (by decide)

lemma hC41 : coordMod timesTableO.basis mS (zeta1 ^ 41) = ![66093, 44124, 35173] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC40 (by decide)

lemma hC42 : coordMod timesTableO.basis mS (zeta1 ^ 42) = ![70630, 26506, 91583] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC41 (by decide)

lemma hC43 : coordMod timesTableO.basis mS (zeta1 ^ 43) = ![25172, 92915, 42569] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC42 (by decide)

lemma hC44 : coordMod timesTableO.basis mS (zeta1 ^ 44) = ![84084, 85418, 45517] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC43 (by decide)

lemma hC45 : coordMod timesTableO.basis mS (zeta1 ^ 45) = ![21453, 30284, 2429] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC44 (by decide)

lemma hC46 : coordMod timesTableO.basis mS (zeta1 ^ 46) = ![29233, 93198, 30201] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC45 (by decide)

lemma hC47 : coordMod timesTableO.basis mS (zeta1 ^ 47) = ![15635, 16686, 82836] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC46 (by decide)

lemma hC48 : coordMod timesTableO.basis mS (zeta1 ^ 48) = ![47273, 30587, 8628] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC47 (by decide)

lemma hC49 : coordMod timesTableO.basis mS (zeta1 ^ 49) = ![94065, 63478, 87925] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC48 (by decide)

lemma hC50 : coordMod timesTableO.basis mS (zeta1 ^ 50) = ![59993, 90764, 64381] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC49 (by decide)

lemma hC51 : coordMod timesTableO.basis mS (zeta1 ^ 51) = ![48373, 51858, 88696] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC50 (by decide)

lemma hC52 : coordMod timesTableO.basis mS (zeta1 ^ 52) = ![43456, 85847, 81933] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC51 (by decide)

lemma hC53 : coordMod timesTableO.basis mS (zeta1 ^ 53) = ![13397, 21799, 50919] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC52 (by decide)

lemma hC54 : coordMod timesTableO.basis mS (zeta1 ^ 54) = ![72709, 50910, 50642] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC53 (by decide)

lemma hC55 : coordMod timesTableO.basis mS (zeta1 ^ 55) = ![22278, 65617, 7404] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC54 (by decide)

lemma hC56 : coordMod timesTableO.basis mS (zeta1 ^ 56) = ![83408, 17791, 67651] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC55 (by decide)

lemma hC57 : coordMod timesTableO.basis mS (zeta1 ^ 57) = ![30566, 12775, 3791] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC56 (by decide)

lemma hC58 : coordMod timesTableO.basis mS (zeta1 ^ 58) = ![35713, 22938, 87846] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC57 (by decide)

lemma hC59 : coordMod timesTableO.basis mS (zeta1 ^ 59) = ![40674, 17736, 72512] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC58 (by decide)

lemma hC60 : coordMod timesTableO.basis mS (zeta1 ^ 60) = ![16668, 93181, 79446] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC59 (by decide)

lemma hC61 : coordMod timesTableO.basis mS (zeta1 ^ 61) = ![15691, 16759, 33698] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC60 (by decide)

lemma hC62 : coordMod timesTableO.basis mS (zeta1 ^ 62) = ![35686, 18927, 45960] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC61 (by decide)

lemma hC63 : coordMod timesTableO.basis mS (zeta1 ^ 63) = ![48012, 29085, 39520] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC62 (by decide)

lemma hC64 : coordMod timesTableO.basis mS (zeta1 ^ 64) = ![82646, 53561, 50120] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC63 (by decide)

lemma hC65 : coordMod timesTableO.basis mS (zeta1 ^ 65) = ![44989, 85677, 22684] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC64 (by decide)

lemma hC66 : coordMod timesTableO.basis mS (zeta1 ^ 66) = ![35412, 43984, 38444] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC65 (by decide)

lemma hC67 : coordMod timesTableO.basis mS (zeta1 ^ 67) = ![58735, 14751, 76837] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC66 (by decide)

lemma hC68 : coordMod timesTableO.basis mS (zeta1 ^ 68) = ![42769, 28018, 15928] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC67 (by decide)

lemma hC69 : coordMod timesTableO.basis mS (zeta1 ^ 69) = ![23698, 89929, 17965] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC68 (by decide)

lemma hC70 : coordMod timesTableO.basis mS (zeta1 ^ 70) = ![11319, 15639, 6314] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC69 (by decide)

lemma hC71 : coordMod timesTableO.basis mS (zeta1 ^ 71) = ![48788, 33149, 89806] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC70 (by decide)

lemma hC72 : coordMod timesTableO.basis mS (zeta1 ^ 72) = ![32526, 93626, 31771] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC71 (by decide)

lemma hC73 : coordMod timesTableO.basis mS (zeta1 ^ 73) = ![30916, 31539, 1014] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC72 (by decide)

lemma hC74 : coordMod timesTableO.basis mS (zeta1 ^ 74) = ![37736, 6197, 36354] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC73 (by decide)

lemma hC75 : coordMod timesTableO.basis mS (zeta1 ^ 75) = ![10295, 4098, 49599] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC74 (by decide)

lemma hC76 : coordMod timesTableO.basis mS (zeta1 ^ 76) = ![49730, 45632, 82086] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC75 (by decide)

lemma hC77 : coordMod timesTableO.basis mS (zeta1 ^ 77) = ![62046, 16414, 31562] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC76 (by decide)

lemma hC78 : coordMod timesTableO.basis mS (zeta1 ^ 78) = ![67155, 50741, 80600] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC77 (by decide)

lemma hC79 : coordMod timesTableO.basis mS (zeta1 ^ 79) = ![6960, 50468, 56884] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC78 (by decide)

lemma hC80 : coordMod timesTableO.basis mS (zeta1 ^ 80) = ![85578, 35110, 65788] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC79 (by decide)

lemma hC81 : coordMod timesTableO.basis mS (zeta1 ^ 81) = ![31223, 90362, 48603] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC80 (by decide)

lemma hC82 : coordMod timesTableO.basis mS (zeta1 ^ 82) = ![16772, 20659, 74079] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC81 (by decide)

lemma hC83 : coordMod timesTableO.basis mS (zeta1 ^ 83) = ![19706, 93296, 72148] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC82 (by decide)

lemma hC84 : coordMod timesTableO.basis mS (zeta1 ^ 84) = ![69880, 70833, 591] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC83 (by decide)

lemma hC85 : coordMod timesTableO.basis mS (zeta1 ^ 85) = ![27179, 50595, 2587] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC84 (by decide)

lemma hC86 : coordMod timesTableO.basis mS (zeta1 ^ 86) = ![63524, 12929, 3401] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC85 (by decide)

lemma hC87 : coordMod timesTableO.basis mS (zeta1 ^ 87) = ![67255, 54326, 25067] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC86 (by decide)

lemma hC88 : coordMod timesTableO.basis mS (zeta1 ^ 88) = ![72368, 18042, 72821] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC87 (by decide)

lemma hC89 : coordMod timesTableO.basis mS (zeta1 ^ 89) = ![52052, 34010, 19354] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC88 (by decide)

lemma hC90 : coordMod timesTableO.basis mS (zeta1 ^ 90) = ![89489, 55479, 62354] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC89 (by decide)

lemma hC91 : coordMod timesTableO.basis mS (zeta1 ^ 91) = ![42495, 81265, 2202] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC90 (by decide)

lemma hC92 : coordMod timesTableO.basis mS (zeta1 ^ 92) = ![72052, 85036, 14553] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC91 (by decide)

lemma hC93 : coordMod timesTableO.basis mS (zeta1 ^ 93) = ![9843, 19056, 22929] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC92 (by decide)

lemma hC94 : coordMod timesTableO.basis mS (zeta1 ^ 94) = ![73255, 54199, 87407] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC93 (by decide)

lemma hC95 : coordMod timesTableO.basis mS (zeta1 ^ 95) = ![74650, 20451, 13144] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC94 (by decide)

lemma hC96 : coordMod timesTableO.basis mS (zeta1 ^ 96) = ![87722, 67271, 13225] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC95 (by decide)

lemma hC97 : coordMod timesTableO.basis mS (zeta1 ^ 97) = ![5204, 32182, 72913] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC96 (by decide)

lemma hC98 : coordMod timesTableO.basis mS (zeta1 ^ 98) = ![70280, 38098, 89319] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC97 (by decide)

lemma hC99 : coordMod timesTableO.basis mS (zeta1 ^ 99) = ![80790, 42692, 65675] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC98 (by decide)

lemma hC100 : coordMod timesTableO.basis mS (zeta1 ^ 100) = ![71249, 28557, 65996] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC99 (by decide)

lemma hC101 : coordMod timesTableO.basis mS (zeta1 ^ 101) = ![73073, 44516, 15655] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC100 (by decide)

lemma hC102 : coordMod timesTableO.basis mS (zeta1 ^ 102) = ![57103, 12587, 2149] :=
  coordMod_pow_succ timesTableT_eq_Table hTMod hbase hC101 (by decide)

/-! ### `(S3)`: the sieve -/

lemma hS1 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 1)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC1 kMu).mpr (by decide)

lemma hS2 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 2)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC2 kMu).mpr (by decide)

lemma hS3 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 3)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC3 kMu).mpr (by decide)

lemma hS4 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 4)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC4 kMu).mpr (by decide)

lemma hS5 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 5)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC5 kMu).mpr (by decide)

lemma hS6 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 6)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC6 kMu).mpr (by decide)

lemma hS7 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 7)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC7 kMu).mpr (by decide)

lemma hS8 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 8)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC8 kMu).mpr (by decide)

lemma hS9 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 9)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC9 kMu).mpr (by decide)

lemma hS10 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 10)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC10 kMu).mpr (by decide)

lemma hS11 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 11)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC11 kMu).mpr (by decide)

lemma hS12 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 12)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC12 kMu).mpr (by decide)

lemma hS13 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 13)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC13 kMu).mpr (by decide)

lemma hS14 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 14)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC14 kMu).mpr (by decide)

lemma hS15 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 15)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC15 kMu).mpr (by decide)

lemma hS16 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 16)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC16 kMu).mpr (by decide)

lemma hS17 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 17)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC17 kMu).mpr (by decide)

lemma hS18 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 18)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC18 kMu).mpr (by decide)

lemma hS19 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 19)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC19 kMu).mpr (by decide)

lemma hS20 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 20)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC20 kMu).mpr (by decide)

lemma hS21 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 21)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC21 kMu).mpr (by decide)

lemma hS22 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 22)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC22 kMu).mpr (by decide)

lemma hS23 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 23)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC23 kMu).mpr (by decide)

lemma hS24 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 24)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC24 kMu).mpr (by decide)

lemma hS25 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 25)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC25 kMu).mpr (by decide)

lemma hS26 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 26)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC26 kMu).mpr (by decide)

lemma hS27 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 27)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC27 kMu).mpr (by decide)

lemma hS28 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 28)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC28 kMu).mpr (by decide)

lemma hS29 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 29)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC29 kMu).mpr (by decide)

lemma hS30 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 30)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC30 kMu).mpr (by decide)

lemma hS31 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 31)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC31 kMu).mpr (by decide)

lemma hS32 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 32)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC32 kMu).mpr (by decide)

lemma hS33 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 33)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC33 kMu).mpr (by decide)

lemma hS34 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 34)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC34 kMu).mpr (by decide)

lemma hS35 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 35)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC35 kMu).mpr (by decide)

lemma hS36 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 36)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC36 kMu).mpr (by decide)

lemma hS37 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 37)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC37 kMu).mpr (by decide)

lemma hS38 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 38)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC38 kMu).mpr (by decide)

lemma hS39 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 39)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC39 kMu).mpr (by decide)

lemma hS40 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 40)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC40 kMu).mpr (by decide)

lemma hS41 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 41)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC41 kMu).mpr (by decide)

lemma hS42 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 42)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC42 kMu).mpr (by decide)

lemma hS43 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 43)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC43 kMu).mpr (by decide)

lemma hS44 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 44)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC44 kMu).mpr (by decide)

lemma hS45 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 45)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC45 kMu).mpr (by decide)

lemma hS46 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 46)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC46 kMu).mpr (by decide)

lemma hS47 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 47)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC47 kMu).mpr (by decide)

lemma hS48 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 48)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC48 kMu).mpr (by decide)

lemma hS49 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 49)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC49 kMu).mpr (by decide)

lemma hS50 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 50)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC50 kMu).mpr (by decide)

lemma hS51 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 51)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC51 kMu).mpr (by decide)

lemma hS52 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 52)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC52 kMu).mpr (by decide)

lemma hS53 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 53)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC53 kMu).mpr (by decide)

lemma hS54 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 54)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC54 kMu).mpr (by decide)

lemma hS55 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 55)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC55 kMu).mpr (by decide)

lemma hS56 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 56)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC56 kMu).mpr (by decide)

lemma hS57 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 57)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC57 kMu).mpr (by decide)

lemma hS58 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 58)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC58 kMu).mpr (by decide)

lemma hS59 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 59)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC59 kMu).mpr (by decide)

lemma hS60 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 60)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC60 kMu).mpr (by decide)

lemma hS61 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 61)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC61 kMu).mpr (by decide)

lemma hS62 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 62)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC62 kMu).mpr (by decide)

lemma hS63 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 63)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC63 kMu).mpr (by decide)

lemma hS64 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 64)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC64 kMu).mpr (by decide)

lemma hS65 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 65)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC65 kMu).mpr (by decide)

lemma hS66 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 66)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC66 kMu).mpr (by decide)

lemma hS67 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 67)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC67 kMu).mpr (by decide)

lemma hS68 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 68)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC68 kMu).mpr (by decide)

lemma hS69 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 69)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC69 kMu).mpr (by decide)

lemma hS70 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 70)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC70 kMu).mpr (by decide)

lemma hS71 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 71)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC71 kMu).mpr (by decide)

lemma hS72 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 72)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC72 kMu).mpr (by decide)

lemma hS73 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 73)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC73 kMu).mpr (by decide)

lemma hS74 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 74)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC74 kMu).mpr (by decide)

lemma hS75 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 75)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC75 kMu).mpr (by decide)

lemma hS76 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 76)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC76 kMu).mpr (by decide)

lemma hS77 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 77)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC77 kMu).mpr (by decide)

lemma hS78 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 78)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC78 kMu).mpr (by decide)

lemma hS79 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 79)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC79 kMu).mpr (by decide)

lemma hS80 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 80)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC80 kMu).mpr (by decide)

lemma hS81 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 81)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC81 kMu).mpr (by decide)

lemma hS82 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 82)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC82 kMu).mpr (by decide)

lemma hS83 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 83)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC83 kMu).mpr (by decide)

lemma hS84 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 84)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC84 kMu).mpr (by decide)

lemma hS85 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 85)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC85 kMu).mpr (by decide)

lemma hS86 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 86)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC86 kMu).mpr (by decide)

lemma hS87 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 87)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC87 kMu).mpr (by decide)

lemma hS88 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 88)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC88 kMu).mpr (by decide)

lemma hS89 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 89)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC89 kMu).mpr (by decide)

lemma hS90 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 90)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC90 kMu).mpr (by decide)

lemma hS91 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 91)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC91 kMu).mpr (by decide)

lemma hS92 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 92)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC92 kMu).mpr (by decide)

lemma hS93 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 93)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC93 kMu).mpr (by decide)

lemma hS94 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 94)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC94 kMu).mpr (by decide)

lemma hS95 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 95)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC95 kMu).mpr (by decide)

lemma hS96 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 96)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC96 kMu).mpr (by decide)

lemma hS97 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 97)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC97 kMu).mpr (by decide)

lemma hS98 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 98)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC98 kMu).mpr (by decide)

lemma hS99 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 99)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC99 kMu).mpr (by decide)

lemma hS100 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 100)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC100 kMu).mpr (by decide)

lemma hS101 : ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 101)) :=
  (not_dvd_muOfBasis_iff (by norm_num) hC101 kMu).mpr (by decide)

/-- **`(S3)`.**  `307 ∤ mu (zeta1 ^ r)` for every `r < 102` outside the surviving
class 0. -/
theorem not_dvd_mu_zeta1_pow : ∀ r : ℕ, r < 102 → r ≠ 0 → ¬ ((pS : ℤ) ∣ mu (zeta1 ^ r)) := by
  intro r hr h0
  interval_cases r
  · exact absurd rfl h0
  · exact hS1
  · exact hS2
  · exact hS3
  · exact hS4
  · exact hS5
  · exact hS6
  · exact hS7
  · exact hS8
  · exact hS9
  · exact hS10
  · exact hS11
  · exact hS12
  · exact hS13
  · exact hS14
  · exact hS15
  · exact hS16
  · exact hS17
  · exact hS18
  · exact hS19
  · exact hS20
  · exact hS21
  · exact hS22
  · exact hS23
  · exact hS24
  · exact hS25
  · exact hS26
  · exact hS27
  · exact hS28
  · exact hS29
  · exact hS30
  · exact hS31
  · exact hS32
  · exact hS33
  · exact hS34
  · exact hS35
  · exact hS36
  · exact hS37
  · exact hS38
  · exact hS39
  · exact hS40
  · exact hS41
  · exact hS42
  · exact hS43
  · exact hS44
  · exact hS45
  · exact hS46
  · exact hS47
  · exact hS48
  · exact hS49
  · exact hS50
  · exact hS51
  · exact hS52
  · exact hS53
  · exact hS54
  · exact hS55
  · exact hS56
  · exact hS57
  · exact hS58
  · exact hS59
  · exact hS60
  · exact hS61
  · exact hS62
  · exact hS63
  · exact hS64
  · exact hS65
  · exact hS66
  · exact hS67
  · exact hS68
  · exact hS69
  · exact hS70
  · exact hS71
  · exact hS72
  · exact hS73
  · exact hS74
  · exact hS75
  · exact hS76
  · exact hS77
  · exact hS78
  · exact hS79
  · exact hS80
  · exact hS81
  · exact hS82
  · exact hS83
  · exact hS84
  · exact hS85
  · exact hS86
  · exact hS87
  · exact hS88
  · exact hS89
  · exact hS90
  · exact hS91
  · exact hS92
  · exact hS93
  · exact hS94
  · exact hS95
  · exact hS96
  · exact hS97
  · exact hS98
  · exact hS99
  · exact hS100
  · exact hS101

/-! ### `(S1)`, `(S2)` and the re-centering data -/

/-- The coordinates of `δ = (zeta1 ^ 102 - 1) / 307` modulo `307`. -/
def eDelta : Fin 3 → ZMod pS := ![186, 41, 7]

/-- The times table of `O`, reduced modulo `307`. -/
def TModP : Fin 3 → Fin 3 → List (ZMod pS) :=
 ![ ![[1, 0, 0], [0, 1, 0], [0, 0, 1]],
 ![[0, 1, 0], [0, 0, 3], [6, 4, 0]],
 ![[0, 0, 1], [6, 4, 0], [0, 2, 4]]]

lemma hTModP : ∀ i j, List.map (algebraMap ℤ (ZMod pS)) (Table i j) = TModP i j := by decide

lemma hP0 : coordMod timesTableO.basis pS (zeta1 ^ 0) = ![1, 0, 0] := by
  rw [coordMod_castHom (by norm_num : pS ∣ mS), hC0]
  funext i; fin_cases i <;> decide

/-- **`(S1)`, `(S2)` and re-centering.**  `zeta1 ^ 102 = 307 δ + 1` with `307 ∤ mu δ`,
and `307 ∤ mu (zeta1 ^ r * δ)` for each surviving class `r`, so no such class holds two
solutions. -/
theorem zeta1_pow_102 : ∃ δ : O, zeta1 ^ 102 = pS * δ + 1 ∧ ¬ ((pS : ℤ) ∣ mu δ) ∧ ¬ ((pS : ℤ) ∣ mu (zeta1 ^ 0 * δ)) := by
  obtain ⟨δ, hδ, hc⟩ := exists_delta_of_coordMod (b := timesTableO.basis) (by norm_num)
    (i₀ := 0) B_one hC102 eDelta (by decide)
  refine ⟨δ, hδ, (not_dvd_muOfBasis_iff dvd_rfl hc kMu).mpr (by decide), ?_⟩
  · exact (not_dvd_muOfBasis_iff dvd_rfl (coordMod_mul timesTableT_eq_Table
      hTModP hP0 hc (c := ![186, 41, 7]) (by decide)) kMu).mpr (by decide)

end

end NF3_1_204_1
