import IdealArithmetic.Examples.NF5_1_2025000000_5.ClassGroupSaturated5_1_2025000000_5_5
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F0
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F1
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F2
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F3
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F4
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F5
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F6
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F7
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F8
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F9
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F10
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F11
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F12
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F13
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F14
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F15
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F16
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F17
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F18
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F19
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F20
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F21
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F22
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F23
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F24
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F25
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F26
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F27
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F28
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F29
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F30
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F31
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F32
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F33
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F34
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F35
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F36
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F37
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F38
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F39
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F40
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F41
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F42
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F43
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F44
import IdealArithmetic.Examples.NF5_1_2025000000_5.RelationIdeals5_1_2025000000_5F45
import IdealArithmetic.Examples.NF5_1_2025000000_5.PrimesBelowCert5_1_2025000000_5
import Mathlib.NumberTheory.NumberField.ClassNumber
import IdealArithmetic.Signature.ResultantRecursive
import IdealArithmetic.DedekindProject.Discriminant
import IdealArithmetic.Generation.ClassGroupGeneration

set_option linter.all false

/- Number field `K(α)` with α root of polynomial `X^5 + 10*X^3 - 40*X^2 - 15*X - 232`.
Class group structure `[5]`, generated by class of ideals `[(2, 1/4*a^3 - 1/2*a^2 + 7/4*a - 7)]`. -/

/- Ring of integers with basis `[1, a, a^2, 1/4*a^3 - 1/2*a^2 - 1/4*a, 1/4*a^4 - 1/4*a^2 - 1/2*a]` -/

open BigOperators Classical Matrix Polynomial Module

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible

instance K_field : Field K := by
  unfold K
  exact AdjoinRoot.instField

instance K_numberField : NumberField K := by
  unfold K
  exact AdjoinRoot.instNumberFieldRat

instance : Module ℚ K := Algebra.toModule
instance : @Algebra ℤ K CommRing.toCommSemiring CommRing.toCommSemiring.toSemiring := Ring.toIntAlgebra K
instance : @CharZero K CommRing.toCommSemiring.toNonAssocSemiring.toAddCommMonoidWithOne.toAddMonoidWithOne := charZero_of_expChar_one' K

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  erw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, T_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ [2]
  · fin_cases hc
    exact @pMaximal_of_MaximalOrderCertificateWLists K 2 _ IsAddTorsionFree.to_noZeroSMulDivisors_int _ O Om hm _ _ M2
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [2] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']

theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by rw [O_integral_closure] ; rfl

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance DD' : IsDedekindDomain O  := by
  rw [O_integral_closure]
  exact integralClosure.isDedekindDomain ℤ ℚ K

instance : Module.Free ℤ ↥O := Module.Free.of_basis B

instance  : IdemCommSemiring (Ideal O) := Ideal.instIdemCommSemiring
instance : CharZero O := SubsemiringClass.instCharZero O

def SturmRC : SturmBuilderOfList [[-232, -15, -40, 10, 0, 1], [-15, -80, 30, 0, 5], [5800, 300, 600, -100], [-690000, -120000, -90000], [-144000000, -72000000], [518400000000]] [-232, -15, -40, 10, 0, 1] [-15, -80, 30, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 5 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 10000, 8100000000, 5184000000000000]
  f := [1, 25, 10000, 8100000000]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [-3000, -500], [-66000000, 9000000], [-4320000000000, 6480000000000]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 + 10*X^3 - 40*X^2 - 15*X - 232
  l := [-232, -15, -40, 10, 0, 1]
  hl := T_ofList
  hlz := by decide
  hz := by decide
  hAdj := Adj
  heq := O_integral_closure
  P := [[-232, -15, -40, 10, 0, 1], [-15, -80, 30, 0, 5], [5800, 300, 600, -100], [-690000, -120000, -90000], [-144000000, -72000000], [518400000000]]
  SB := SturmRC
  k := 1
  r := 3
  hr := by decide
  hreq := by decide 

lemma ne_dvd_torsion5 : ¬5 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
 suffices ¬ 5 ∣ 2 from ?_
 · convert this
   rw [O_integral_closure, ← Fintype.card_eq_nat_card,
   ←  NumberField.Units.torsionOrder_eq_two_of_odd_finrank (by erw [K_finrank] ; decide)]
   rfl
 · decide

def NPCU5 : pMaximalUnitsCertificateNDvdT O 5 where 
 hp := by decide
 r := 2
 huc := by 
  erw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2]
 hu := fun i => 
  match i with 
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
 t := 3
 hrle := by decide
 q := ![31, 41, 61]
 hqP := by 
  intro i 
  match i with 
  | 0 => exact Sat5.hq31
  | 1 => exact Sat5.hq41
  | 2 => exact Sat5.hq61
 I := ![Sat5.I0, Sat5.I1, Sat5.I2]
 hcard := fun i =>
  match i with  
  | 0 => Sat5.N0
  | 1 => Sat5.N1
  | 2 => Sat5.N2
 ζ := ![3, 6, 2]
 hr := fun i =>
  match i with 
  | 0 => ((orderOf_of_IsOrderOf Sat5.R31) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf Sat5.R41) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf Sat5.R61) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 hpndvdt := ne_dvd_torsion5
 M := ![![4, 2], ![2, 4], ![2, 3]]
 hM1 := by 
  intro i j
  fin_cases i <;> fin_cases j 
  · erw [eq_of_DiscreteLogCertificate Sat5.Log00] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat5.Log01] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat5.Log10] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat5.Log11] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat5.Log20] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat5.Log21] ; decide
 Minv := ![![2, 4], ![4, 2]] 
 hInv := by decide

def NPSU5 : pSaturatedClassGroupCertificateNDvdT 5 ![J0] ![5] where 
 topMaximalUnitsCertificateNDvdT := NPCU5
 a := ![alpha0]
 γ := 1
 hc := by decide
 ψ := ![0]
 iψ := ![0] 
 hψ := by decide 
 hψn := by 
  intro i 
  fin_cases i 
  · decide
 h := fun i =>
  match i with 
  | 0 => by convert J0_pow5
 N := ![![0], ![3], ![1]]
 hM2 := by 
  intro (i : Fin 3) j
  match i , j with 
  | 0, 0 => exact Sat5.Log02
  | 1, 0 => exact Sat5.Log12
  | 2, 0 => exact Sat5.Log22
 hDl := by decide 
 NInv := ![![0, 1, 2], ![3, 3, 1], ![1, 4, 4]]
 hN := by decide 

lemma T_discr : T.discr = 518400000000 :=  by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  rw [T_ofList]

theorem K_discr : NumberField.discr K = 2025000000 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl

lemma K_nrComplexPlaces : NumberField.InfinitePlace.nrComplexPlaces K = 2 := by
  rw [nrComplexPlaces_of_RankUnitsCertificate RC]
  rfl

lemma K_nrRealPlaces : NumberField.InfinitePlace.nrRealPlaces K = 1 := by
  rw [nrRealPlaces_of_RankUnitsCertificate RC]
  rfl

theorem K_minowski : minkowskiBoundFB K ≤ (2801.338085343355 : ℝ) := by
  refine K_minkowski_decimal _ ?_
  erw [K_nrComplexPlaces, K_discr, K_finrank]
  have hraux: √2025000000 ≤ 45000.00001 := by
      refine Real.sqrt_le_iff.mpr ?_
      norm_num
  have : 0.0384 * √2025000000 ≤ 1728.01 := by
    refine le_trans (mul_le_mul_of_nonneg (by rfl) hraux (by norm_num) (by norm_num)) ?_
    norm_num
  norm_num
  try {linarith}

def s := ![9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 3]

def BM : (i : Fin 46) → Fin (e i) → (Fin 1 → ℕ) := by 
  rintro ⟨i, hi⟩ 
  interval_cases i 
  exact ![![1], ![1], ![1], ![4], ![2], ![1], ![2], ![4], ![4], ![1], ![1]]
  exact ![![2], ![2], ![3], ![3], ![3], ![3], ![4], ![0], ![0], ![0], ![2], ![2], ![2], ![4], ![4], ![1], ![1]]
  exact ![![3], ![3], ![2], ![2], ![2], ![2], ![2], ![3], ![3], ![1], ![2], ![2], ![0]]
  exact ![![0], ![0], ![4], ![1], ![1], ![4], ![4], ![1]]
  exact ![![0], ![2], ![2], ![3], ![3], ![0], ![0]]
  exact ![![0], ![1], ![1], ![4], ![4], ![0]]
  exact ![![0], ![4], ![4], ![3], ![2], ![2], ![3], ![3], ![0], ![0], ![0], ![0]]
  exact ![![1], ![1], ![4], ![4], ![3], ![3], ![4], ![4], ![2], ![2], ![0], ![0], ![2], ![4], ![4]]
  exact ![![3], ![1], ![1], ![1], ![1], ![3]]
  exact ![![2], ![2], ![3], ![0], ![0], ![0], ![0], ![0], ![1], ![1], ![4]]
  exact ![![3], ![3], ![2], ![2], ![4], ![2], ![2], ![4], ![4], ![2], ![2]]
  exact ![![4], ![2], ![2], ![0], ![4], ![3], ![4], ![0]]
  exact ![![0], ![0], ![3], ![3], ![3], ![3], ![3], ![4], ![0], ![0]]
  exact ![![2], ![4], ![4], ![3], ![4], ![0], ![0]]
  exact ![![3], ![3], ![3], ![0], ![0]]
  exact ![![3], ![4], ![4], ![2], ![1], ![1], ![1], ![1]]
  exact ![![1], ![1], ![0], ![0], ![4], ![4], ![4], ![4], ![3], ![3]]
  exact ![![0], ![0], ![1], ![3], ![3], ![2], ![4], ![4], ![2]]
  exact ![![2], ![2], ![1], ![3], ![3], ![4], ![4]]
  exact ![![2], ![2], ![0], ![0], ![3], ![3]]
  exact ![![0], ![0], ![2], ![2], ![2], ![4], ![4], ![3], ![3], ![1], ![2], ![2]]
  exact ![![4], ![2], ![2], ![0]]
  exact ![![3], ![3], ![2], ![2], ![3], ![4], ![0], ![0], ![0], ![0], ![0], ![4], ![1], ![2]]
  exact ![![3], ![3], ![1], ![1], ![2], ![2], ![2]]
  exact ![![4], ![4], ![1]]
  exact ![![2], ![2], ![2], ![0], ![0], ![4], ![3], ![3]]
  exact ![![3], ![3], ![4], ![4], ![1], ![1], ![1], ![1], ![3]]
  exact ![![2], ![3], ![3], ![2], ![2], ![2], ![2], ![3], ![3], ![2]]
  exact ![![0], ![0], ![4], ![4], ![3], ![2], ![2], ![4], ![4], ![4]]
  exact ![![3], ![3], ![0], ![2], ![2], ![2], ![3], ![3]]
  exact ![![4], ![4], ![2], ![2], ![3], ![3], ![4], ![0]]
  exact ![![1], ![3], ![3], ![1]]
  exact ![![1], ![1], ![0], ![0], ![4], ![4], ![0], ![0], ![0], ![0]]
  exact ![![2], ![4], ![4], ![0], ![0], ![0], ![2], ![2], ![1], ![3]]
  exact ![![1], ![1], ![1], ![1], ![2], ![2], ![4], ![4], ![3]]
  exact ![![0], ![4], ![4], ![2], ![0], ![0]]
  exact ![![1], ![2], ![2], ![4]]
  exact ![![3], ![3], ![3], ![3], ![3], ![1], ![3], ![3], ![4]]
  exact ![![3], ![3], ![1], ![1], ![4], ![2], ![2], ![0], ![0], ![2], ![2]]
  exact ![![3], ![3], ![3], ![0], ![0], ![0], ![0], ![0]]
  exact ![![4], ![4], ![2], ![1], ![1], ![2], ![2]]
  exact ![![3], ![1], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![2], ![0], ![2], ![2]]
  exact ![![1], ![1], ![0], ![0], ![0], ![1], ![1], ![4], ![4]]
  exact ![![3], ![3], ![2], ![2], ![3], ![4], ![4], ![0], ![0], ![3], ![3], ![1], ![1]]
  exact ![![2], ![2]]

lemma primesGenerationBelow : {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < 2802} ⊆ Set.range (Fin.addCasesIter e 𝔭) := by
  rw [← cert_eq_𝔭]
  refine le_primes_below_bound_of_PrimesBelowBoundCertificate_le_of_eq (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv PB2802

def 𝔭' : Fin 397 → nonZeroDivisors (Ideal O) := by
  intro i
  have : PB2802.β i ∈ List.ofFn PB2802.β := by
    simp only [List.mem_ofFn, exists_apply_eq_apply]
  refine Ideal.toNonZeroDivisorOfNeZero ((PB2802.β) i)
    (fun hc => ((zero_ne_mem_of_PrimesBelowCertificate_Fn _ PB2802) (hc ▸ this) ))

def J : Fin 1 → Ideal O := ![J0]

def J' :  Fin 1 → nonZeroDivisors (Ideal O) := by
  refine fun i => Ideal.toNonZeroDivisorOfNeZero (J i) (?_ )
  unfold J
  rw [← Submodule.zero_eq_bot, ← pow_ne_zero_iff (n := ![5] i) (by fin_cases i <;> decide) , NPSU5.h]
  simp only [ Submodule.zero_eq_bot, ne_eq, Ideal.span_singleton_eq_bot, NPSU5]
  fin_cases i
  · dsimp [alpha0] ; rw [(LinearEquiv.map_eq_zero_iff B.equivFun.symm)] ; decide 

lemma 𝔭'_apply : ∀ (i : Fin 397), ↑(𝔭' i) = (Fin.addCasesIter e 𝔭) i := by
  intro i
  rw [← cert_eq_𝔭]
  rfl

lemma J'_apply : ∀ (i : Fin 1), ↑(J' i) = J i := by
  intro i
  rfl

lemma relations_proof0 (i : Fin 11) : IsInClass O J (𝔭 0 i) (BM 0 i) := by
  show IsInClass O J (𝔭 0 i) (![![1], ![1], ![1], ![4], ![2], ![1], ![2], ![4], ![4], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R3N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R3N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R5N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R13N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R13N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R13N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R23N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R23N2

lemma relations_proof1 (i : Fin 17) : IsInClass O J (𝔭 1 i) (BM 1 i) := by
  show IsInClass O J (𝔭 1 i) (![![2], ![2], ![3], ![3], ![3], ![3], ![4], ![0], ![0], ![0], ![2], ![2], ![2], ![4], ![4], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R29N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R29N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R31N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R31N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R41N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R41N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R41N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R47N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R47N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R53N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R59N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R59N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R61N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R61N2

lemma relations_proof2 (i : Fin 13) : IsInClass O J (𝔭 2 i) (BM 2 i) := by
  show IsInClass O J (𝔭 2 i) (![![3], ![3], ![2], ![2], ![2], ![2], ![2], ![3], ![3], ![1], ![2], ![2], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R67N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R67N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R79N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R79N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R79N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R79N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R79N4
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R83N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R83N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R89N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R97N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R97N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof3 (i : Fin 8) : IsInClass O J (𝔭 3 i) (BM 3 i) := by
  show IsInClass O J (𝔭 3 i) (![![0], ![0], ![4], ![1], ![1], ![4], ![4], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R109N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R127N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R127N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R137N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R137N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R139N2

lemma relations_proof4 (i : Fin 7) : IsInClass O J (𝔭 4 i) (BM 4 i) := by
  show IsInClass O J (𝔭 4 i) (![![0], ![2], ![2], ![3], ![3], ![0], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R179N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R179N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R181N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R181N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof5 (i : Fin 6) : IsInClass O J (𝔭 5 i) (BM 5 i) := by
  show IsInClass O J (𝔭 5 i) (![![0], ![1], ![1], ![4], ![4], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R227N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R227N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R241N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R241N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof6 (i : Fin 12) : IsInClass O J (𝔭 6 i) (BM 6 i) := by
  show IsInClass O J (𝔭 6 i) (![![0], ![4], ![4], ![3], ![2], ![2], ![3], ![3], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R263N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R263N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R269N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R271N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R271N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R281N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R281N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof7 (i : Fin 15) : IsInClass O J (𝔭 7 i) (BM 7 i) := by
  show IsInClass O J (𝔭 7 i) (![![1], ![1], ![4], ![4], ![3], ![3], ![4], ![4], ![2], ![2], ![0], ![0], ![2], ![4], ![4]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R311N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R311N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R313N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R313N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R317N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R317N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R337N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R337N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R347N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R347N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R353N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R359N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R359N2

lemma relations_proof8 (i : Fin 6) : IsInClass O J (𝔭 8 i) (BM 8 i) := by
  show IsInClass O J (𝔭 8 i) (![![3], ![1], ![1], ![1], ![1], ![3]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R367N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R373N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R373N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R389N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R389N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R419N2

lemma relations_proof9 (i : Fin 11) : IsInClass O J (𝔭 9 i) (BM 9 i) := by
  show IsInClass O J (𝔭 9 i) (![![2], ![2], ![3], ![0], ![0], ![0], ![0], ![0], ![1], ![1], ![4]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R421N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R421N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R433N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R461N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R461N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R463N2

lemma relations_proof10 (i : Fin 11) : IsInClass O J (𝔭 10 i) (BM 10 i) := by
  show IsInClass O J (𝔭 10 i) (![![3], ![3], ![2], ![2], ![4], ![2], ![2], ![4], ![4], ![2], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R467N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R467N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R479N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R479N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R487N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R503N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R503N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R509N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R509N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R521N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R521N2

lemma relations_proof11 (i : Fin 8) : IsInClass O J (𝔭 11 i) (BM 11 i) := by
  show IsInClass O J (𝔭 11 i) (![![4], ![2], ![2], ![0], ![4], ![3], ![4], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R541N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R547N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R547N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R563N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R569N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R587N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof12 (i : Fin 10) : IsInClass O J (𝔭 12 i) (BM 12 i) := by
  show IsInClass O J (𝔭 12 i) (![![0], ![0], ![3], ![3], ![3], ![3], ![3], ![4], ![0], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R617N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R617N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R619N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R631N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R631N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R641N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof13 (i : Fin 7) : IsInClass O J (𝔭 13 i) (BM 13 i) := by
  show IsInClass O J (𝔭 13 i) (![![2], ![4], ![4], ![3], ![4], ![0], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R647N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R659N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R659N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R683N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R691N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof14 (i : Fin 5) : IsInClass O J (𝔭 14 i) (BM 14 i) := by
  show IsInClass O J (𝔭 14 i) (![![3], ![3], ![3], ![0], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R719N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R733N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R733N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof15 (i : Fin 8) : IsInClass O J (𝔭 15 i) (BM 15 i) := by
  show IsInClass O J (𝔭 15 i) (![![3], ![4], ![4], ![2], ![1], ![1], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R769N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R809N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R809N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R821N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R823N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R823N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R827N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R827N2

lemma relations_proof16 (i : Fin 10) : IsInClass O J (𝔭 16 i) (BM 16 i) := by
  show IsInClass O J (𝔭 16 i) (![![1], ![1], ![0], ![0], ![4], ![4], ![4], ![4], ![3], ![3]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R839N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R839N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R859N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R859N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R863N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R863N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R881N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R881N2

lemma relations_proof17 (i : Fin 9) : IsInClass O J (𝔭 17 i) (BM 17 i) := by
  show IsInClass O J (𝔭 17 i) (![![0], ![0], ![1], ![3], ![3], ![2], ![4], ![4], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R911N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R919N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R919N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R929N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R937N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R941N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R953N2

lemma relations_proof18 (i : Fin 7) : IsInClass O J (𝔭 18 i) (BM 18 i) := by
  show IsInClass O J (𝔭 18 i) (![![2], ![2], ![1], ![3], ![3], ![4], ![4]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R971N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R971N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R977N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R983N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R983N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R991N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R991N2

lemma relations_proof19 (i : Fin 6) : IsInClass O J (𝔭 19 i) (BM 19 i) := by
  show IsInClass O J (𝔭 19 i) (![![2], ![2], ![0], ![0], ![3], ![3]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1021N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1021N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1069N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1069N2

lemma relations_proof20 (i : Fin 12) : IsInClass O J (𝔭 20 i) (BM 20 i) := by
  show IsInClass O J (𝔭 20 i) (![![0], ![0], ![2], ![2], ![2], ![4], ![4], ![3], ![3], ![1], ![2], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1097N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1097N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1103N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1109N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1109N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1117N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1117N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1123N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1129N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1129N2

lemma relations_proof21 (i : Fin 4) : IsInClass O J (𝔭 21 i) (BM 21 i) := by
  show IsInClass O J (𝔭 21 i) (![![4], ![2], ![2], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1163N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1171N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1171N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof22 (i : Fin 14) : IsInClass O J (𝔭 22 i) (BM 22 i) := by
  show IsInClass O J (𝔭 22 i) (![![3], ![3], ![2], ![2], ![3], ![4], ![0], ![0], ![0], ![0], ![0], ![4], ![1], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1217N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1217N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1229N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1229N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1231N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1237N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1259N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1277N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1279N2

lemma relations_proof23 (i : Fin 7) : IsInClass O J (𝔭 23 i) (BM 23 i) := by
  show IsInClass O J (𝔭 23 i) (![![3], ![3], ![1], ![1], ![2], ![2], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1283N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1283N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1289N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1289N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1297N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1297N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1321N2

lemma relations_proof24 (i : Fin 3) : IsInClass O J (𝔭 24 i) (BM 24 i) := by
  show IsInClass O J (𝔭 24 i) (![![4], ![4], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1409N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1409N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1427N2

lemma relations_proof25 (i : Fin 8) : IsInClass O J (𝔭 25 i) (BM 25 i) := by
  show IsInClass O J (𝔭 25 i) (![![2], ![2], ![2], ![0], ![0], ![4], ![3], ![3]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1429N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1447N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1447N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1459N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1481N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1481N2

lemma relations_proof26 (i : Fin 9) : IsInClass O J (𝔭 26 i) (BM 26 i) := by
  show IsInClass O J (𝔭 26 i) (![![3], ![3], ![4], ![4], ![1], ![1], ![1], ![1], ![3]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1483N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1483N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1487N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1487N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1489N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1489N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1511N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1523N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1531N2

lemma relations_proof27 (i : Fin 10) : IsInClass O J (𝔭 27 i) (BM 27 i) := by
  show IsInClass O J (𝔭 27 i) (![![2], ![3], ![3], ![2], ![2], ![2], ![2], ![3], ![3], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1553N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1567N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1567N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1571N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1571N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1579N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1579N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1583N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1583N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1597N2

lemma relations_proof28 (i : Fin 10) : IsInClass O J (𝔭 28 i) (BM 28 i) := by
  show IsInClass O J (𝔭 28 i) (![![0], ![0], ![4], ![4], ![3], ![2], ![2], ![4], ![4], ![4]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1609N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1609N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1619N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1621N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1621N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1637N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1637N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1663N2

lemma relations_proof29 (i : Fin 8) : IsInClass O J (𝔭 29 i) (BM 29 i) := by
  show IsInClass O J (𝔭 29 i) (![![3], ![3], ![0], ![2], ![2], ![2], ![3], ![3]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1667N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1667N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1697N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1697N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1721N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1733N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1733N2

lemma relations_proof30 (i : Fin 8) : IsInClass O J (𝔭 30 i) (BM 30 i) := by
  show IsInClass O J (𝔭 30 i) (![![4], ![4], ![2], ![2], ![3], ![3], ![4], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1741N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1741N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1747N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1753N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1783N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1783N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1787N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof31 (i : Fin 4) : IsInClass O J (𝔭 31 i) (BM 31 i) := by
  show IsInClass O J (𝔭 31 i) (![![1], ![3], ![3], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1811N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1831N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1831N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1861N2

lemma relations_proof32 (i : Fin 10) : IsInClass O J (𝔭 32 i) (BM 32 i) := by
  show IsInClass O J (𝔭 32 i) (![![1], ![1], ![0], ![0], ![4], ![4], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1889N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1889N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1913N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1913N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof33 (i : Fin 10) : IsInClass O J (𝔭 33 i) (BM 33 i) := by
  show IsInClass O J (𝔭 33 i) (![![2], ![4], ![4], ![0], ![0], ![0], ![2], ![2], ![1], ![3]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1979N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1987N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R1987N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2003N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2003N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2011N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2017N2

lemma relations_proof34 (i : Fin 9) : IsInClass O J (𝔭 34 i) (BM 34 i) := by
  show IsInClass O J (𝔭 34 i) (![![1], ![1], ![1], ![1], ![2], ![2], ![4], ![4], ![3]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2027N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2027N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2039N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2039N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2053N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2053N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2063N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2063N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2083N2

lemma relations_proof35 (i : Fin 6) : IsInClass O J (𝔭 35 i) (BM 35 i) := by
  show IsInClass O J (𝔭 35 i) (![![0], ![4], ![4], ![2], ![0], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2113N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2113N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2129N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof36 (i : Fin 4) : IsInClass O J (𝔭 36 i) (BM 36 i) := by
  show IsInClass O J (𝔭 36 i) (![![1], ![2], ![2], ![4]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2161N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2203N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2203N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2213N2

lemma relations_proof37 (i : Fin 9) : IsInClass O J (𝔭 37 i) (BM 37 i) := by
  show IsInClass O J (𝔭 37 i) (![![3], ![3], ![3], ![3], ![3], ![1], ![3], ![3], ![4]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2267N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2267N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2267N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2267N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2267N4
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2273N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2281N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2281N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2287N2

lemma relations_proof38 (i : Fin 11) : IsInClass O J (𝔭 38 i) (BM 38 i) := by
  show IsInClass O J (𝔭 38 i) (![![3], ![3], ![1], ![1], ![4], ![2], ![2], ![0], ![0], ![2], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2333N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2333N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2339N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2339N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2341N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2347N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2347N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2371N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2371N2

lemma relations_proof39 (i : Fin 8) : IsInClass O J (𝔭 39 i) (BM 39 i) := by
  show IsInClass O J (𝔭 39 i) (![![3], ![3], ![3], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2381N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2383N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2383N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof40 (i : Fin 7) : IsInClass O J (𝔭 40 i) (BM 40 i) := by
  show IsInClass O J (𝔭 40 i) (![![4], ![4], ![2], ![1], ![1], ![2], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2437N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2437N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2447N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2473N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2477N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2503N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2521N2

lemma relations_proof41 (i : Fin 11) : IsInClass O J (𝔭 41 i) (BM 41 i) := by
  show IsInClass O J (𝔭 41 i) (![![3], ![1], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2531N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2539N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof42 (i : Fin 4) : IsInClass O J (𝔭 42 i) (BM 42 i) := by
  show IsInClass O J (𝔭 42 i) (![![2], ![0], ![2], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2621N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2671N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2671N2

lemma relations_proof43 (i : Fin 9) : IsInClass O J (𝔭 43 i) (BM 43 i) := by
  show IsInClass O J (𝔭 43 i) (![![1], ![1], ![0], ![0], ![0], ![1], ![1], ![4], ![4]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2689N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2689N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2711N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2711N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2713N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2713N2

lemma relations_proof44 (i : Fin 13) : IsInClass O J (𝔭 44 i) (BM 44 i) := by
  show IsInClass O J (𝔭 44 i) (![![3], ![3], ![2], ![2], ![3], ![4], ![4], ![0], ![0], ![3], ![3], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2719N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2719N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2729N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2729N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2731N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2741N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2741N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2767N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2767N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2777N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2777N2

lemma relations_proof45 (i : Fin 2) : IsInClass O J (𝔭 45 i) (BM 45 i) := by
  show IsInClass O J (𝔭 45 i) (![![2], ![2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2797N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R2797N2

theorem class_group_generator : Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (J' i))) = ⊤ := by
  refine subgroup_closure_eq_classGroup'' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv
      𝔭'_apply J'_apply ?_ primesGenerationBelow (Fin.addCasesIter e BM) ?_
  · refine lt_of_le_of_lt K_minowski ?_
    norm_num
  · refine forall_addCasesIter_prop 𝔭 BM (IsInClass O J) ?_
    rintro ⟨i, hi⟩
    interval_cases i
    · exact relations_proof0
    · exact relations_proof1
    · exact relations_proof2
    · exact relations_proof3
    · exact relations_proof4
    · exact relations_proof5
    · exact relations_proof6
    · exact relations_proof7
    · exact relations_proof8
    · exact relations_proof9
    · exact relations_proof10
    · exact relations_proof11
    · exact relations_proof12
    · exact relations_proof13
    · exact relations_proof14
    · exact relations_proof15
    · exact relations_proof16
    · exact relations_proof17
    · exact relations_proof18
    · exact relations_proof19
    · exact relations_proof20
    · exact relations_proof21
    · exact relations_proof22
    · exact relations_proof23
    · exact relations_proof24
    · exact relations_proof25
    · exact relations_proof26
    · exact relations_proof27
    · exact relations_proof28
    · exact relations_proof29
    · exact relations_proof30
    · exact relations_proof31
    · exact relations_proof32
    · exact relations_proof33
    · exact relations_proof34
    · exact relations_proof35
    · exact relations_proof36
    · exact relations_proof37
    · exact relations_proof38
    · exact relations_proof39
    · exact relations_proof40
    · exact relations_proof41
    · exact relations_proof42
    · exact relations_proof43
    · exact relations_proof44
    · exact relations_proof45

def ClassGroupO_equiv : (∀ i : Fin 1 , (ZMod (![5] i))) ≃+ Additive (ClassGroup O) := by
  haveI : ∀ (i : Fin 1), NeZero (![5] i) := by
    intro i
    fin_cases i <;>  exact {out := by decide}
  refine ClassGroup_equiv_of_pSaturatedCertificate J'_apply NPSU5.h class_group_generator ?_
  rintro ⟨p, hp1, hp2⟩
  have : ∏ i, ![5] i = ∏ i, (![5] i) ^ (![1] i)  := by decide
  rw [this] at hp2
  have hp_cases : p ∈ [5] := by
    obtain ⟨j ,hj1, hj2⟩  := Prime.exists_mem_finset_dvd (Nat.prime_iff.mp hp1) hp2
    show p ∈ List.ofFn ![5]
    rw [(Nat.prime_dvd_prime_iff_eq hp1 ?_).1 (Nat.Prime.dvd_of_dvd_pow hp1 hj2), List.mem_ofFn]
    exact ⟨j, rfl⟩
    fin_cases j <;> decide
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hp_cases
  by_cases h : p = 5
  simp_rw [h] ; right
  exact NPSU5
  omega

def class_group_equiv : (∀ i : Fin 1 , (ZMod (![5] i))) ≃+ Additive (ClassGroup (NumberField.RingOfIntegers K)) := by
 refine AddEquiv.trans ClassGroupO_equiv ?_
 exact MulEquiv.toAdditive (ClassGroup.congr
    ((Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv))

theorem class_number_K_eq_5 : NumberField.classNumber K = 5 := by
  unfold NumberField.classNumber
  rw [Fintype.card_eq_nat_card, ← Nat.card_congr (Additive.toMul),
    Nat.card_congr (class_group_equiv).symm.toEquiv, Nat.card_pi]
  simp [Fin.isValue, Fin.prod_succ]
  try decide
