import IdealArithmetic.IdealArithmetic
import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem
import IdealArithmetic.PrincipalityCertificate
import Mathlib.RingTheory.AdjoinRoot

--------------------------------------------
-- EXAMPLE
--------------------------------------------

/- Number field `K(α)` with with α root of polynomial `X^5 + 75*X^3 - 50*X^2 + 1500*X - 1800`.
Class number `2`, generated by class of ideal `J = (2, 1/30*a^4 + 3/2*a^2 - 2/3*a + 10)`. We have `J ^ 2 = (α)`. -/

/- Ring of integers with basis `[1, a, a^2, 1/10*a^3 - 1/2*a, 1/120*a^4 - 1/20*a^3 + 1/8*a^2 - 1/6*a - 1/2]` -/

open BigOperators Classical Matrix Polynomial

noncomputable def P : ℤ[X] := X^5 + 75*X^3 - 50*X^2 + 1500*X - 1800

def K := AdjoinRoot (map (algebraMap ℤ ℚ) P)

lemma P_irreducible : Irreducible P := sorry
lemma P_degree : P.natDegree = 5 := sorry
lemma P_monic : Monic P := sorry

--local notation "K" =>  AdjoinRoot (map (algebraMap ℤ ℚ) (X^5 + 75*X^3 - 50*X^2 + 1500*X - 1800 ))

noncomputable instance : CommRing K := by
  unfold K
  infer_instance

noncomputable instance : Algebra ℚ K := by
  unfold K
  infer_instance

noncomputable def Adj_K : IsAdjoinRoot K (map (algebraMap ℤ ℚ) (X^5 + 75*X^3 - 50*X^2 + 1500*X - 1800 )) := by
  unfold K
  exact AdjoinRoot.isAdjoinRoot (Polynomial.map (algebraMap ℤ ℚ) (X^5 + 75*X^3 - 50*X^2 + 1500*X - 1800))


lemma ofList_poly : ofList [-1800, 1500, -50, 75, 0, 1] = X^5 + 75*X^3 - 50*X^2 + 1500*X - 1800   := by
  simp ; ring


noncomputable def O : Subalgebra ℤ K := sorry

noncomputable def TT : TimesTable (Fin 5) ℤ O where
    basis := sorry
    table := ![![![1, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![0, 0, 0, 0, 1]], ![![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 5, 0, 10, 0], ![6, 5, -2, 6, 12], ![12, -18, 1, -8, -6]], ![![0, 0, 1, 0, 0], ![0, 5, 0, 10, 0], ![60, 50, -15, 60, 120], ![180, -190, 5, -80, 0], ![-120, 85, -8, 10, -60]], ![![0, 0, 0, 1, 0], ![6, 5, -2, 6, 12], ![180, -190, 5, -80, 0], ![-51, -22, -2, -46, -102], ![-72, 106, 0, 50, 51]], ![![0, 0, 0, 0, 1], ![12, -18, 1, -8, -6], ![-120, 85, -8, 10, -60], ![-72, 106, 0, 50, 51], ![87, -93, 3, -29, -9]]]
    basis_mul_basis := sorry

noncomputable def B := TT.basis

lemma B_one : TT.basis 0 = 1 := sorry

lemma B_one_repr : TT.basis.equivFun.symm ![1, 0, 0, 0, 0] = 1 := sorry

def T : Fin 5 → Fin 5 → List ℤ :=
    ![![[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]], ![[0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 5, 0, 10, 0], [6, 5, -2, 6, 12], [12, -18, 1, -8, -6]], ![[0, 0, 1, 0, 0], [0, 5, 0, 10, 0], [60, 50, -15, 60, 120], [180, -190, 5, -80, 0], [-120, 85, -8, 10, -60]], ![[0, 0, 0, 1, 0], [6, 5, -2, 6, 12], [180, -190, 5, -80, 0], [-51, -22, -2, -46, -102], [-72, 106, 0, 50, 51]], ![[0, 0, 0, 0, 1], [12, -18, 1, -8, -6], [-120, 85, -8, 10, -60], [-72, 106, 0, 50, 51], [87, -93, 3, -29, -9]]]

lemma T_eq_TT : ∀ (i j : Fin 5), T i j = List.ofFn (TT.table i j) := by
  simp ; decide



instance : IsDomain O := by
  haveI hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) :=
  {out := (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible}
  letI hola : Field K := by
    unfold K
    exact AdjoinRoot.instField
  haveI : IsDomain K := by infer_instance
  refine Subalgebra.isDomain O

noncomputable section

instance hq11 : Fact $ Nat.Prime 11 := by decide
instance hq3 : Fact $ Nat.Prime 3 := by decide
instance hq29 : Fact $ Nat.Prime 29 := by decide

def R11 : IsOrderOf (2 : ZMod 11) 10 where
 m := 2
 P := ![2, 5]
 e := ![1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def R3 : IsOrderOf (2 : ZMod 3) 2 where
 m := 1
 P := ![2]
 e := ![1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def R29 : IsOrderOf (2 : ZMod 29) 28 where
 m := 2
 P := ![2, 7]
 e := ![2, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def I0 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![3, 0, 0, 0, 0], ![12, 0, 1, 2, 4]] i)))
def I1 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![3, 0, 0, 0, 0], ![1, 1, 0, 0, 0]] i)))
def I2 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![11, 0, 0, 0, 0], ![2, 1, 0, 0, 0]] i)))
def I3 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![29, 0, 0, 0, 0], ![-11, 1, 0, 0, 0]] i)))

def A0: IdealEqSpanCertificate O ℤ TT I0
 ![![3, 0, 0, 0, 0], ![12, 0, 1, 2, 4]]
 ![![3, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![0, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![3, 0, 0, 0, 0], ![0, 3, 0, 0, 0], ![0, 0, 3, 0, 0], ![0, 0, 0, 3, 0], ![0, 0, 0, 0, 3]], ![![12, 0, 1, 2, 4], ![60, -45, 0, -10, 0], ![-60, 10, -25, -60, -120], ![-210, 190, 1, 40, 0], ![84, -75, 4, -6, 18]]]
  hmulB := by decide
  f := ![![![1, 0, 0, 0, 0], ![0, 0, 0, 0, 0]], ![![33710, -112123, -12338, -51150, -51900], ![27465, -7564, -382, -1, 0]], ![![33546, -111590, -12278, -50904, -51648], ![27336, -7528, -380, -1, 0]], ![![-16, 30, 2, 11, 8], ![-6, 2, 0, 0, 0]], ![![-33542, 111530, 12272, 50878, 51623], ![-27317, 7524, 380, 1, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![0, 3, 0, 0, 0], ![0, 0, 3, 0, 0], ![0, 0, 0, 3, 0], ![0, 0, 0, 0, 3]], ![![4, 0, 1, 2, 4], ![20, -45, 0, -10, 0], ![-20, 10, -25, -60, -120], ![-70, 190, 1, 40, 0], ![28, -75, 4, -6, 18]]]
  hle1 := by decide
  hle2 := by decide

lemma N0 : Nat.card (O ⧸ I0) = 3 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A0)

def A1: IdealEqSpanCertificate O ℤ TT I1
 ![![3, 0, 0, 0, 0], ![1, 1, 0, 0, 0]]
 ![![3, 0, 0, 0, 0], ![1, 1, 0, 0, 0], ![2, 0, 1, 0, 0], ![2, 0, 0, 1, 0], ![2, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![3, 0, 0, 0, 0], ![0, 3, 0, 0, 0], ![0, 0, 3, 0, 0], ![0, 0, 0, 3, 0], ![0, 0, 0, 0, 3]], ![![1, 1, 0, 0, 0], ![0, 1, 1, 0, 0], ![0, 5, 1, 10, 0], ![6, 5, -2, 7, 12], ![12, -18, 1, -8, -5]]]
  hmulB := by decide
  f := ![![![80, 165, 34, 408, -20], ![-93, 42, -132, 0, -12]], ![![38, 81, 17, 204, -10], ![-41, 21, -66, 0, -6]], ![![78, 155, 34, 388, -20], ![-88, 37, -126, 0, -12]], ![![40, 85, 17, 211, -10], ![-46, 23, -68, 0, -6]], ![![52, 109, 23, 272, -13], ![-58, 27, -88, 0, -8]]]
  g := ![![![1, 0, 0, 0, 0], ![-1, 3, 0, 0, 0], ![-2, 0, 3, 0, 0], ![-2, 0, 0, 3, 0], ![-2, 0, 0, 0, 3]], ![![0, 1, 0, 0, 0], ![-1, 1, 1, 0, 0], ![-9, 5, 1, 10, 0], ![-11, 5, -2, 7, 12], ![18, -18, 1, -8, -5]]]
  hle1 := by decide
  hle2 := by decide

lemma N1 : Nat.card (O ⧸ I1) = 3 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A1)

def A2: IdealEqSpanCertificate O ℤ TT I2
 ![![11, 0, 0, 0, 0], ![2, 1, 0, 0, 0]]
 ![![11, 0, 0, 0, 0], ![2, 1, 0, 0, 0], ![7, 0, 1, 0, 0], ![2, 0, 0, 1, 0], ![5, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![11, 0, 0, 0, 0], ![0, 11, 0, 0, 0], ![0, 0, 11, 0, 0], ![0, 0, 0, 11, 0], ![0, 0, 0, 0, 11]], ![![2, 1, 0, 0, 0], ![0, 2, 1, 0, 0], ![0, 5, 2, 10, 0], ![6, 5, -2, 8, 12], ![12, -18, 1, -8, -4]]]
  hmulB := by decide
  f := ![![![31881, 99466, 33015, 173712, 288], ![-174548, 18051, -190872, -264, 0]], ![![10614, 33119, 10993, 57844, 96], ![-58112, 6017, -63558, -88, 0]], ![![21249, 66293, 22004, 115778, 192], ![-116338, 12035, -127215, -176, 0]], ![![5314, 16582, 5504, 28963, 48], ![-29094, 3016, -31824, -44, 0]], ![![14491, 45212, 15007, 78960, 131], ![-79338, 8203, -86760, -120, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-2, 11, 0, 0, 0], ![-7, 0, 11, 0, 0], ![-2, 0, 0, 11, 0], ![-5, 0, 0, 0, 11]], ![![0, 1, 0, 0, 0], ![-1, 2, 1, 0, 0], ![-4, 5, 2, 10, 0], ![-6, 5, -2, 8, 12], ![7, -18, 1, -8, -4]]]
  hle1 := by decide
  hle2 := by decide

lemma N2 : Nat.card (O ⧸ I2) = 11 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A2)

def A3: IdealEqSpanCertificate O ℤ TT I3
 ![![29, 0, 0, 0, 0], ![-11, 1, 0, 0, 0]]
 ![![29, 0, 0, 0, 0], ![18, 1, 0, 0, 0], ![24, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![26, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![29, 0, 0, 0, 0], ![0, 29, 0, 0, 0], ![0, 0, 29, 0, 0], ![0, 0, 0, 29, 0], ![0, 0, 0, 0, 29]], ![![-11, 1, 0, 0, 0], ![0, -11, 1, 0, 0], ![0, 5, -11, 10, 0], ![6, 5, -2, -5, 12], ![12, -18, 1, -8, -17]]]
  hmulB := by decide
  f := ![![![288475, 2554, -76068, 66700, 5520], ![753246, -21808, -200100, -13340, 0]], ![![188130, 1671, -49610, 43500, 3600], ![491232, -14210, -130500, -8700, 0]], ![![238312, 2112, -62839, 55100, 4560], ![622264, -18008, -165300, -11020, 0]], ![![22, -1, 1, -1, 0], ![58, 4, 3, 0, 0]], ![![258632, 2291, -68199, 59800, 4949], ![675322, -19549, -179400, -11960, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-18, 29, 0, 0, 0], ![-24, 0, 29, 0, 0], ![0, 0, 0, 29, 0], ![-26, 0, 0, 0, 29]], ![![-1, 1, 0, 0, 0], ![6, -11, 1, 0, 0], ![6, 5, -11, 10, 0], ![-12, 5, -2, -5, 12], ![26, -18, 1, -8, -17]]]
  hle1 := by decide
  hle2 := by decide

lemma N3 : Nat.card (O ⧸ I3) = 29 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A3)

def zeta1 := TT.basis.equivFun.symm ![182324, 9067, 6907, 7553, 13056]

def zeta2 := TT.basis.equivFun.symm ![-72669884397944627058787560488909268342246905518, 82985971093890408022594220611166386447259808587, -3735936183153940820862254239694302055990969, 26147479080084701663246027607699450796542032423, 21912863062765865898830397051820364795846902466]

def v := TT.basis.equivFun.symm ![-1, 0, 0, 0, 0]

def alpha := TT.basis.equivFun.symm ![-175286832746540796364, -10347030789858541610, -6699466941848258956, -7823139234159720716, -13102657848843259256]

def Log00Mem : IdealMemCertificate O ℤ B I0
  ![![3, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![0, 0, 0, 0, 1]] ![182322, 9067, 6907, 7553, 13056] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![60774, 9067, 6907, 7553, 13056]
 hmem := by decide

def Log00: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R3) ▸ IsPrimitiveRoot.orderOf _) 2 zeta1 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![182324, 9067, 6907, 7553, 13056]
 hxeq :=  rfl
 m:= 2
 C := ![182322, 9067, 6907, 7553, 13056]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log00Mem
 k :=  1
 hpow := by decide
 heql := by decide

def Log01Mem : IdealMemCertificate O ℤ B I0
  ![![3, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![0, 0, 0, 0, 1]] ![-72669884397944627058787560488909268342246905520, 82985971093890408022594220611166386447259808587, -3735936183153940820862254239694302055990969, 26147479080084701663246027607699450796542032423, 21912863062765865898830397051820364795846902466] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-24223294799314875686262520162969756114082301840, 82985971093890408022594220611166386447259808587, -3735936183153940820862254239694302055990969, 26147479080084701663246027607699450796542032423, 21912863062765865898830397051820364795846902466]
 hmem := by decide

def Log01: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R3) ▸ IsPrimitiveRoot.orderOf _) 2 zeta2 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-72669884397944627058787560488909268342246905518, 82985971093890408022594220611166386447259808587, -3735936183153940820862254239694302055990969, 26147479080084701663246027607699450796542032423, 21912863062765865898830397051820364795846902466]
 hxeq :=  rfl
 m:= 2
 C := ![-72669884397944627058787560488909268342246905520, 82985971093890408022594220611166386447259808587, -3735936183153940820862254239694302055990969, 26147479080084701663246027607699450796542032423, 21912863062765865898830397051820364795846902466]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log01Mem
 k :=  1
 hpow := by decide
 heql := by decide

def Log02Mem : IdealMemCertificate O ℤ B I0
  ![![3, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![0, 0, 0, 0, 1]] ![-3, 0, 0, 0, 0] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-1, 0, 0, 0, 0]
 hmem := by decide

def Log02: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R3) ▸ IsPrimitiveRoot.orderOf _) 2 v 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-1, 0, 0, 0, 0]
 hxeq :=  rfl
 m:= 2
 C := ![-3, 0, 0, 0, 0]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log02Mem
 k :=  1
 hpow := by decide
 heql := by decide

def Log03Mem : IdealMemCertificate O ℤ B I0
  ![![3, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![0, 0, 0, 0, 1]] ![-175286832746540796366, -10347030789858541610, -6699466941848258956, -7823139234159720716, -13102657848843259256] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-58428944248846932122, -10347030789858541610, -6699466941848258956, -7823139234159720716, -13102657848843259256]
 hmem := by decide

def Log03: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R3) ▸ IsPrimitiveRoot.orderOf _) 2 alpha 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-175286832746540796364, -10347030789858541610, -6699466941848258956, -7823139234159720716, -13102657848843259256]
 hxeq :=  rfl
 m:= 2
 C := ![-175286832746540796366, -10347030789858541610, -6699466941848258956, -7823139234159720716, -13102657848843259256]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log03Mem
 k :=  1
 hpow := by decide
 heql := by decide

def Log10Mem : IdealMemCertificate O ℤ B I1
  ![![3, 0, 0, 0, 0], ![1, 1, 0, 0, 0], ![2, 0, 1, 0, 0], ![2, 0, 0, 1, 0], ![2, 0, 0, 0, 1]] ![182323, 9067, 6907, 7553, 13056] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![39408, 9067, 6907, 7553, 13056]
 hmem := by decide

def Log10: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R3) ▸ IsPrimitiveRoot.orderOf _) 2 zeta1 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![182324, 9067, 6907, 7553, 13056]
 hxeq :=  rfl
 m:= 1
 C := ![182323, 9067, 6907, 7553, 13056]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log10Mem
 k :=  0
 hpow := by decide
 heql := by decide

def Log11Mem : IdealMemCertificate O ℤ B I1
  ![![3, 0, 0, 0, 0], ![1, 1, 0, 0, 0], ![2, 0, 1, 0, 0], ![2, 0, 0, 1, 0], ![2, 0, 0, 0, 1]] ![-72669884397944627058787560488909268342246905520, 82985971093890408022594220611166386447259808587, -3735936183153940820862254239694302055990969, 26147479080084701663246027607699450796542032423, 21912863062765865898830397051820364795846902466] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-83923022635056620774630968636878632456724200649, 82985971093890408022594220611166386447259808587, -3735936183153940820862254239694302055990969, 26147479080084701663246027607699450796542032423, 21912863062765865898830397051820364795846902466]
 hmem := by decide

def Log11: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R3) ▸ IsPrimitiveRoot.orderOf _) 2 zeta2 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-72669884397944627058787560488909268342246905518, 82985971093890408022594220611166386447259808587, -3735936183153940820862254239694302055990969, 26147479080084701663246027607699450796542032423, 21912863062765865898830397051820364795846902466]
 hxeq :=  rfl
 m:= 2
 C := ![-72669884397944627058787560488909268342246905520, 82985971093890408022594220611166386447259808587, -3735936183153940820862254239694302055990969, 26147479080084701663246027607699450796542032423, 21912863062765865898830397051820364795846902466]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log11Mem
 k :=  1
 hpow := by decide
 heql := by decide

def Log12Mem : IdealMemCertificate O ℤ B I1
  ![![3, 0, 0, 0, 0], ![1, 1, 0, 0, 0], ![2, 0, 1, 0, 0], ![2, 0, 0, 1, 0], ![2, 0, 0, 0, 1]] ![-3, 0, 0, 0, 0] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-1, 0, 0, 0, 0]
 hmem := by decide

def Log12: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R3) ▸ IsPrimitiveRoot.orderOf _) 2 v 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-1, 0, 0, 0, 0]
 hxeq :=  rfl
 m:= 2
 C := ![-3, 0, 0, 0, 0]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log12Mem
 k :=  1
 hpow := by decide
 heql := by decide

def Log13Mem : IdealMemCertificate O ℤ B I1
  ![![3, 0, 0, 0, 0], ![1, 1, 0, 0, 0], ![2, 0, 1, 0, 0], ![2, 0, 0, 1, 0], ![2, 0, 0, 0, 1]] ![-175286832746540796366, -10347030789858541610, -6699466941848258956, -7823139234159720716, -13102657848843259256] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-36563091302326592300, -10347030789858541610, -6699466941848258956, -7823139234159720716, -13102657848843259256]
 hmem := by decide

def Log13: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R3) ▸ IsPrimitiveRoot.orderOf _) 2 alpha 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-175286832746540796364, -10347030789858541610, -6699466941848258956, -7823139234159720716, -13102657848843259256]
 hxeq :=  rfl
 m:= 2
 C := ![-175286832746540796366, -10347030789858541610, -6699466941848258956, -7823139234159720716, -13102657848843259256]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log13Mem
 k :=  1
 hpow := by decide
 heql := by decide

def Log20Mem : IdealMemCertificate O ℤ B I2
  ![![11, 0, 0, 0, 0], ![2, 1, 0, 0, 0], ![7, 0, 1, 0, 0], ![2, 0, 0, 1, 0], ![5, 0, 0, 0, 1]] ![182322, 9067, 6907, 7553, 13056] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![3223, 9067, 6907, 7553, 13056]
 hmem := by decide

def Log20: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _) 2 zeta1 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![182324, 9067, 6907, 7553, 13056]
 hxeq :=  rfl
 m:= 2
 C := ![182322, 9067, 6907, 7553, 13056]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log20Mem
 k :=  1
 hpow := by decide
 heql := by decide

def Log21Mem : IdealMemCertificate O ℤ B I2
  ![![11, 0, 0, 0, 0], ![2, 1, 0, 0, 0], ![7, 0, 1, 0, 0], ![2, 0, 0, 1, 0], ![5, 0, 0, 0, 1]] ![-72669884397944627058787560488909268342246905521, 82985971093890408022594220611166386447259808587, -3735936183153940820862254239694302055990969, 26147479080084701663246027607699450796542032423, 21912863062765865898830397051820364795846902466] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![-36406813500585645303534000582369536972244833008, 82985971093890408022594220611166386447259808587, -3735936183153940820862254239694302055990969, 26147479080084701663246027607699450796542032423, 21912863062765865898830397051820364795846902466]
 hmem := by decide

def Log21: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _) 2 zeta2 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-72669884397944627058787560488909268342246905518, 82985971093890408022594220611166386447259808587, -3735936183153940820862254239694302055990969, 26147479080084701663246027607699450796542032423, 21912863062765865898830397051820364795846902466]
 hxeq :=  rfl
 m:= 3
 C := ![-72669884397944627058787560488909268342246905521, 82985971093890408022594220611166386447259808587, -3735936183153940820862254239694302055990969, 26147479080084701663246027607699450796542032423, 21912863062765865898830397051820364795846902466]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log21Mem
 k :=  8
 hpow := by decide
 heql := by decide

def Log22Mem : IdealMemCertificate O ℤ B I2
  ![![11, 0, 0, 0, 0], ![2, 1, 0, 0, 0], ![7, 0, 1, 0, 0], ![2, 0, 0, 1, 0], ![5, 0, 0, 0, 1]] ![-11, 0, 0, 0, 0] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![-1, 0, 0, 0, 0]
 hmem := by decide

def Log22: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _) 2 v 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-1, 0, 0, 0, 0]
 hxeq :=  rfl
 m:= 10
 C := ![-11, 0, 0, 0, 0]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log22Mem
 k :=  5
 hpow := by decide
 heql := by decide

def Log23Mem : IdealMemCertificate O ℤ B I2
  ![![11, 0, 0, 0, 0], ![2, 1, 0, 0, 0], ![7, 0, 1, 0, 0], ![2, 0, 0, 1, 0], ![5, 0, 0, 0, 1]] ![-175286832746540796368, -10347030789858541610, -6699466941848258956, -7823139234159720716, -13102657848843259256] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![-2412448623759105704, -10347030789858541610, -6699466941848258956, -7823139234159720716, -13102657848843259256]
 hmem := by decide

def Log23: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _) 2 alpha 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-175286832746540796364, -10347030789858541610, -6699466941848258956, -7823139234159720716, -13102657848843259256]
 hxeq :=  rfl
 m:= 4
 C := ![-175286832746540796368, -10347030789858541610, -6699466941848258956, -7823139234159720716, -13102657848843259256]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log23Mem
 k :=  2
 hpow := by decide
 heql := by decide

def Log30Mem : IdealMemCertificate O ℤ B I3
  ![![29, 0, 0, 0, 0], ![18, 1, 0, 0, 0], ![24, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![26, 0, 0, 0, 1]] ![182303, 9067, 6907, 7553, 13056] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A3
 g := ![-16763, 9067, 6907, 7553, 13056]
 hmem := by decide

def Log30: DiscreteLogCertificate N3 ((orderOf_of_IsOrderOf R29) ▸ IsPrimitiveRoot.orderOf _) 2 zeta1 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![182324, 9067, 6907, 7553, 13056]
 hxeq :=  rfl
 m:= 21
 C := ![182303, 9067, 6907, 7553, 13056]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log30Mem
 k :=  17
 hpow := by decide
 heql := by decide

def Log31Mem : IdealMemCertificate O ℤ B I3
  ![![29, 0, 0, 0, 0], ![18, 1, 0, 0, 0], ![24, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![26, 0, 0, 0, 1]] ![-72669884397944627058787560488909268342246905527, 82985971093890408022594220611166386447259808587, -3735936183153940820862254239694302055990969, 26147479080084701663246027607699450796542032423, 21912863062765865898830397051820364795846902466] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A3
 g := ![-73657315215568578974323212439154518821917211757, 82985971093890408022594220611166386447259808587, -3735936183153940820862254239694302055990969, 26147479080084701663246027607699450796542032423, 21912863062765865898830397051820364795846902466]
 hmem := by decide

def Log31: DiscreteLogCertificate N3 ((orderOf_of_IsOrderOf R29) ▸ IsPrimitiveRoot.orderOf _) 2 zeta2 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-72669884397944627058787560488909268342246905518, 82985971093890408022594220611166386447259808587, -3735936183153940820862254239694302055990969, 26147479080084701663246027607699450796542032423, 21912863062765865898830397051820364795846902466]
 hxeq :=  rfl
 m:= 9
 C := ![-72669884397944627058787560488909268342246905527, 82985971093890408022594220611166386447259808587, -3735936183153940820862254239694302055990969, 26147479080084701663246027607699450796542032423, 21912863062765865898830397051820364795846902466]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log31Mem
 k :=  10
 hpow := by decide
 heql := by decide

def Log32Mem : IdealMemCertificate O ℤ B I3
  ![![29, 0, 0, 0, 0], ![18, 1, 0, 0, 0], ![24, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![26, 0, 0, 0, 1]] ![-29, 0, 0, 0, 0] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A3
 g := ![-1, 0, 0, 0, 0]
 hmem := by decide

def Log32: DiscreteLogCertificate N3 ((orderOf_of_IsOrderOf R29) ▸ IsPrimitiveRoot.orderOf _) 2 v 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-1, 0, 0, 0, 0]
 hxeq :=  rfl
 m:= 28
 C := ![-29, 0, 0, 0, 0]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log32Mem
 k :=  14
 hpow := by decide
 heql := by decide

def Log33Mem : IdealMemCertificate O ℤ B I3
  ![![29, 0, 0, 0, 0], ![18, 1, 0, 0, 0], ![24, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![26, 0, 0, 0, 1]] ![-175286832746540796382, -10347030789858541610, -6699466941848258956, -7823139234159720716, -13102657848843259256] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A3
 g := ![17669518349834341662, -10347030789858541610, -6699466941848258956, -7823139234159720716, -13102657848843259256]
 hmem := by decide

def Log33: DiscreteLogCertificate N3 ((orderOf_of_IsOrderOf R29) ▸ IsPrimitiveRoot.orderOf _) 2 alpha 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-175286832746540796364, -10347030789858541610, -6699466941848258956, -7823139234159720716, -13102657848843259256]
 hxeq :=  rfl
 m:= 18
 C := ![-175286832746540796382, -10347030789858541610, -6699466941848258956, -7823139234159720716, -13102657848843259256]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log33Mem
 k :=  11
 hpow := by decide
 heql := by decide

def J : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![2, 0, 0, 0, 0], ![12, 1, 1, 2, 4]] i)))
def MulJ0 : IdealMulEqCertificate O ℤ TT (J) J
  ![![2, 0, 0, 0, 0], ![12, 1, 1, 2, 4]] ![![2, 0, 0, 0, 0], ![12, 1, 1, 2, 4]]
  ![![-175286832746540796364, -10347030789858541610, -6699466941848258956, -7823139234159720716, -13102657848843259256]] where
 T := T
 heq := T_eq_TT
 hI1 := rfl
 hI2 := rfl
 M :=  ![![![4, 0, 0, 0, 0], ![24, 2, 2, 4, 8]], ![![24, 2, 2, 4, 8], ![120, 0, 6, 0, 0]]]
 hmul := by decide
 f :=  ![![![![19324184048290798433, -11002964441259362228, -1884054821233655593, -18788198296129383830, -36940491437389722116], ![16832413487589453651, 0, 0, 0, 0]], ![![0, 0, 0, 0, 0], ![-5471345772015423981, 0, 0, 0, 0]]]]
 g :=  ![![![![211634648193893, -107723351479138, 49247758873357, 48022243478474, 225422155622474]], ![![2482669213662912, -2901010573366097, -24097070242637, -954386055596758, -890929841407946]]], ![![![2482669213662912, -2901010573366097, -24097070242637, -954386055596758, -890929841407946]], ![![-16828644528438420, 14708941685534445, -1658088877540116, 1875778447689510, -4660732740144180]]]]
 hle1 := by decide
 hle2 := by decide

lemma J2 : J ^ 2 =  Ideal.span {alpha} := by
 simp only [pow_succ, pow_one, pow_zero, one_mul]
 simp [ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ0, alpha]

lemma isUnit_zeta1 : IsUnit zeta1 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![68078, -251247, -79053, -269863, -369426])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide

lemma isUnit_zeta2 : IsUnit zeta2 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![-32707014916392676823502412576923329918983295903666307693559684, -1930666925071420710533004967825244597131962159044631410841767, -1250062892720242287645494217143430672681366570779776837805005, -1459730474990433573349477125828298890409219249172968005906833, -2444843226337328222198209297348857493679866448050357471912496])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide

lemma isUnit_v : IsUnit v := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![-1, 0, 0, 0, 0])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide

lemma v_pow_one : v ^ 2 = 1 := by
  rw [← B_one_repr]
  apply table_nPow_sq_table_eq_pow TT.table T TT.basis _ TT.basis_mul_basis T_eq_TT _ (by norm_num)
  decide


instance hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible

noncomputable instance K_field : Field K := by
  unfold K
  infer_instance

instance K_numberField : NumberField K := by
  unfold K
  infer_instance

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  rw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, P_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by sorry

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K


def SturmRC : SturmBuilderOfList [[-1800, 1500, -50, 75, 0, 1], [1500, -100, 225, 0, 5], [60, -40, 1, -1], [-60, 0, -1], [0, -1], [1]] [-1800, 1500, -50, 75, 0, 1] [1500, -100, 225, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 5 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 1, 1, 1]
  f := [750, 30, 20, 60]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [-5, -5], [-1, 1], [0, 1]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 + 75*X^3 - 50*X^2 + 1500*X - 1800
  l := [-1800, 1500, -50, 75, 0, 1]
  hl := ofList_poly
  hlz := by decide
  hz := by decide
  hAdj := Adj_K
  heq := O_integral_closure
  P := [[-1800, 1500, -50, 75, 0, 1], [1500, -100, 225, 0, 5], [60, -40, 1, -1], [-60, 0, -1], [0, -1], [1]]
  SB := SturmRC
  k := 1
  r := 3
  hr := by decide
  hreq := by decide


def NPCJ : NonPrincipalCertificateDvdT J where
 p := 2
 hp := by decide
 r := 2
 huc := by
  rw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2]
 hu := fun i =>
  match i with
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
 v := v
 m := 2
 hm := by norm_num
 hmv := v_pow_one
 q := ![3, 3, 11, 29]
 hqP := by
  intro i
  match i with
  | 0 => exact hq3
  | 1 => exact hq3
  | 2 => exact hq11
  | 3 => exact hq29
 I := ![I0, I1, I2, I3]
 hcard := fun i =>
  match i with
  | 0 => N0
  | 1 => N1
  | 2 => N2
  | 3 => N3
 ζ := ![2, 2, 2, 2]
 hr := fun i =>
  match i with
  | 0 => ((orderOf_of_IsOrderOf R3) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf R3) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _)
  | 3 => ((orderOf_of_IsOrderOf R29) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 a := alpha
 n := 2
 hpdvd := by decide
 hJ := J2
 M := ![![1, 1, 1, 1], ![0, 1, 1, 1], ![1, 0, 1, 0], ![1, 0, 0, 1]]
 hM1 := by
  intro j i hj
  fin_cases i <;> interval_cases j
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log00] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log01] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log10] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log11] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log20] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log21] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log30] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log31] ; decide
 hM2 := by
  intro j
  fin_cases j
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log02] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log12] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log22] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log32] ; decide
 hM3 := by
  intro i
  match i with
  | 0 => exact Log03
  | 1 => exact Log13
  | 2 => exact Log23
  | 3 => exact Log33
 hDl := by decide
 Minv := ![![1, 1, 0, 0], ![0, 1, 1, 1], ![1, 1, 1, 0], ![1, 1, 0, 1]]
 hInv := by decide
 N := ![![1, 1, 0], ![1, 0, 1], ![1, 1, 1]]
 hNiv := by decide

theorem J_not_principal : ¬ ∃ b, J = Ideal.span {b} :=
  not_principal_of_NonPrincipalCertificateDvdT NPCJ
