import IdealArithmetic.IdealArithmetic
import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem
import IdealArithmetic.PrincipalityCertificate
import Mathlib.RingTheory.AdjoinRoot

--------------------------------------------
-- EXAMPLE
--------------------------------------------

/- Number field `K(α)` with with α root of polynomial `X^5 - 40*X^3 - 40*X^2 + 435*X + 868`.
Class number `5`, generated by class of ideal `J = (2, 1/4*a^4 - 3/4*a^3 - 27/4*a^2 + 45/4*a + 54)`. We have `J ^ 5 = (α)`. -/

/- Ring of integers with basis `[1, a, a^2, 1/2*a^3 - 1/2*a, 1/12*a^4 + 1/12*a^3 - 1/4*a^2 + 5/12*a - 1/3]` -/

open BigOperators Classical Matrix Polynomial

noncomputable def P : ℤ[X] := X^5 - 40*X^3 - 40*X^2 + 435*X + 868

def K := AdjoinRoot (map (algebraMap ℤ ℚ) P)

lemma P_irreducible : Irreducible P := sorry
lemma P_degree : P.natDegree = 5 := sorry
lemma P_monic : Monic P := sorry

--local notation "K" =>  AdjoinRoot (map (algebraMap ℤ ℚ) (X^5 - 40*X^3 - 40*X^2 + 435*X + 868 ))

noncomputable instance : CommRing K := by
  unfold K
  infer_instance

noncomputable instance : Algebra ℚ K := by
  unfold K
  infer_instance

noncomputable def Adj_K : IsAdjoinRoot K (map (algebraMap ℤ ℚ) (X^5 - 40*X^3 - 40*X^2 + 435*X + 868 )) := by
  unfold K
  exact AdjoinRoot.isAdjoinRoot (Polynomial.map (algebraMap ℤ ℚ) (X^5 - 40*X^3 - 40*X^2 + 435*X + 868))


lemma ofList_poly : ofList [868, 435, -40, -40, 0, 1] = X^5 - 40*X^3 - 40*X^2 + 435*X + 868   := by
  simp ; ring


noncomputable def O : Subalgebra ℤ K := sorry

noncomputable def TT : TimesTable (Fin 5) ℤ O where
    basis := sorry
    table := ![![![1, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![0, 0, 0, 0, 1]], ![![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 1, 0, 2, 0], ![2, -3, 1, -1, 6], ![-72, -34, 4, 6, 1]], ![![0, 0, 1, 0, 0], ![0, 1, 0, 2, 0], ![4, -6, 3, -2, 12], ![-434, -198, 20, 39, 0], ![-60, -120, -24, 8, 37]], ![![0, 0, 0, 1, 0], ![2, -3, 1, -1, 6], ![-434, -198, 20, 39, 0], ![38, -264, -80, 1, 114], ![-1288, -666, 16, 80, 42]], ![![0, 0, 0, 0, 1], ![-72, -34, 4, 6, 1], ![-60, -120, -24, 8, 37], ![-1288, -666, 16, 80, 42], ![-718, -598, -61, 49, 88]]]
    basis_mul_basis := sorry

noncomputable def B := TT.basis

lemma B_one : TT.basis 0 = 1 := sorry

lemma B_one_repr : TT.basis.equivFun.symm ![1, 0, 0, 0, 0] = 1 := sorry

def T : Fin 5 → Fin 5 → List ℤ :=
    ![![[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]], ![[0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 1, 0, 2, 0], [2, -3, 1, -1, 6], [-72, -34, 4, 6, 1]], ![[0, 0, 1, 0, 0], [0, 1, 0, 2, 0], [4, -6, 3, -2, 12], [-434, -198, 20, 39, 0], [-60, -120, -24, 8, 37]], ![[0, 0, 0, 1, 0], [2, -3, 1, -1, 6], [-434, -198, 20, 39, 0], [38, -264, -80, 1, 114], [-1288, -666, 16, 80, 42]], ![[0, 0, 0, 0, 1], [-72, -34, 4, 6, 1], [-60, -120, -24, 8, 37], [-1288, -666, 16, 80, 42], [-718, -598, -61, 49, 88]]]

lemma T_eq_TT : ∀ (i j : Fin 5), T i j = List.ofFn (TT.table i j) := by
  simp ; decide



instance : IsDomain O := by
  haveI hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) :=
  {out := (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible}
  letI hola : Field K := by
    unfold K
    exact AdjoinRoot.instField
  haveI : IsDomain K := by infer_instance
  refine Subalgebra.isDomain O

noncomputable section

instance hq61 : Fact $ Nat.Prime 61 := by decide
instance hq31 : Fact $ Nat.Prime 31 := by decide

def R61 : IsOrderOf (2 : ZMod 61) 60 where
 m := 3
 P := ![2, 3, 5]
 e := ![2, 1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def R31 : IsOrderOf (3 : ZMod 31) 30 where
 m := 3
 P := ![2, 3, 5]
 e := ![1, 1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def I0 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![31, 0, 0, 0, 0], ![0, 1, 0, 0, 0]] i)))
def I1 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![31, 0, 0, 0, 0], ![-11, 1, 0, 0, 0]] i)))
def I2 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![61, 0, 0, 0, 0], ![6, 1, 0, 0, 0]] i)))

def A0: IdealEqSpanCertificate O ℤ TT I0
 ![![31, 0, 0, 0, 0], ![0, 1, 0, 0, 0]]
 ![![31, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![21, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![31, 0, 0, 0, 0], ![0, 31, 0, 0, 0], ![0, 0, 31, 0, 0], ![0, 0, 0, 31, 0], ![0, 0, 0, 0, 31]], ![![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 1, 0, 2, 0], ![2, -3, 1, -1, 6], ![-72, -34, 4, 6, 1]]]
  hmulB := by decide
  f := ![![![-31, -208, 0, -496, -96], ![0, -496, 7936, 496, 0]], ![![0, 0, 0, 0, 0], ![1, 0, 0, 0, 0]], ![![0, 0, 0, 0, 0], ![0, 1, 0, 0, 0]], ![![0, -1, 0, -1, 0], ![15, 0, 16, 0, 0]], ![![-21, -141, 0, -336, -65], ![3, -336, 5376, 336, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![0, 31, 0, 0, 0], ![0, 0, 31, 0, 0], ![0, 0, 0, 31, 0], ![-21, 0, 0, 0, 31]], ![![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 1, 0, 2, 0], ![-4, -3, 1, -1, 6], ![-3, -34, 4, 6, 1]]]
  hle1 := by decide
  hle2 := by decide

lemma N0 : Nat.card (O ⧸ I0) = 31 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A0)

def A1: IdealEqSpanCertificate O ℤ TT I1
 ![![31, 0, 0, 0, 0], ![-11, 1, 0, 0, 0]]
 ![![31, 0, 0, 0, 0], ![20, 1, 0, 0, 0], ![3, 0, 1, 0, 0], ![22, 0, 0, 1, 0], ![28, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![31, 0, 0, 0, 0], ![0, 31, 0, 0, 0], ![0, 0, 31, 0, 0], ![0, 0, 0, 31, 0], ![0, 0, 0, 0, 31]], ![![-11, 1, 0, 0, 0], ![0, -11, 1, 0, 0], ![0, 1, -11, 2, 0], ![2, -3, 1, -12, 6], ![-72, -34, 4, 6, -10]]]
  hmulB := by decide
  f := ![![![171408, -16519, -18138, -930, 2160], ![481027, -4557, -52545, -11160, 0]], ![![114276, -11013, -12092, -620, 1440], ![320696, -3038, -35030, -7440, 0]], ![![21412, -2056, -2302, -110, 270], ![60089, -557, -6665, -1395, 0]], ![![121422, -11704, -12846, -659, 1530], ![340750, -3234, -37215, -7905, 0]], ![![154840, -14919, -16383, -840, 1951], ![434532, -4107, -47460, -10080, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-20, 31, 0, 0, 0], ![-3, 0, 31, 0, 0], ![-22, 0, 0, 31, 0], ![-28, 0, 0, 0, 31]], ![![-1, 1, 0, 0, 0], ![7, -11, 1, 0, 0], ![-1, 1, -11, 2, 0], ![5, -3, 1, -12, 6], ![24, -34, 4, 6, -10]]]
  hle1 := by decide
  hle2 := by decide

lemma N1 : Nat.card (O ⧸ I1) = 31 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A1)

def A2: IdealEqSpanCertificate O ℤ TT I2
 ![![61, 0, 0, 0, 0], ![6, 1, 0, 0, 0]]
 ![![61, 0, 0, 0, 0], ![6, 1, 0, 0, 0], ![25, 0, 1, 0, 0], ![44, 0, 0, 1, 0], ![54, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![61, 0, 0, 0, 0], ![0, 61, 0, 0, 0], ![0, 0, 61, 0, 0], ![0, 0, 0, 61, 0], ![0, 0, 0, 0, 61]], ![![6, 1, 0, 0, 0], ![0, 6, 1, 0, 0], ![0, 1, 6, 2, 0], ![2, -3, 1, 5, 6], ![-72, -34, 4, 6, 7]]]
  hmulB := by decide
  f := ![![![3613861, 3507480, 17783939, 5937679, 8514], ![-36712057, 563152, -180882812, -86559, 0]], ![![420192, 407831, 2067849, 690411, 990], ![-4268596, 65514, -21032373, -10065, 0]], ![![1512775, 1468248, 7444463, 2485548, 3564], ![-15367797, 235766, -75718629, -36234, 0]], ![![2605334, 2528645, 12820978, 4280652, 6138], ![-26466754, 406013, -130403878, -62403, 0]], ![![3199146, 3104980, 15743159, 5256306, 7537], ![-32499100, 498535, -160125768, -76626, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-6, 61, 0, 0, 0], ![-25, 0, 61, 0, 0], ![-44, 0, 0, 61, 0], ![-54, 0, 0, 0, 61]], ![![0, 1, 0, 0, 0], ![-1, 6, 1, 0, 0], ![-4, 1, 6, 2, 0], ![-9, -3, 1, 5, 6], ![-10, -34, 4, 6, 7]]]
  hle1 := by decide
  hle2 := by decide

lemma N2 : Nat.card (O ⧸ I2) = 61 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A2)

def zeta1 := TT.basis.equivFun.symm ![-128547, -93443, -10436, 5627, 8855]

def zeta2 := TT.basis.equivFun.symm ![630777067853, 455760802015, 48555409531, -28976360690, -44398778352]

def alpha := TT.basis.equivFun.symm ![7001899, 1456956, -648479, -339780, 395103]

def Log00Mem : IdealMemCertificate O ℤ B I0
  ![![31, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![21, 0, 0, 0, 1]] ![-128571, -93443, -10436, 5627, 8855] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-10146, -93443, -10436, 5627, 8855]
 hmem := by decide

def Log00: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 3 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-128547, -93443, -10436, 5627, 8855]
 hxeq :=  rfl
 m:= 24
 C := ![-128571, -93443, -10436, 5627, 8855]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log00Mem
 k :=  13
 hpow := by decide
 heql := by decide

def Log01Mem : IdealMemCertificate O ℤ B I0
  ![![31, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![21, 0, 0, 0, 1]] ![630777067824, 455760802015, 48555409531, -28976360690, -44398778352] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![50424239136, 455760802015, 48555409531, -28976360690, -44398778352]
 hmem := by decide

def Log01: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 4 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![630777067853, 455760802015, 48555409531, -28976360690, -44398778352]
 hxeq :=  rfl
 m:= 29
 C := ![630777067824, 455760802015, 48555409531, -28976360690, -44398778352]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log01Mem
 k :=  9
 hpow := by decide
 heql := by decide

def Log02Mem : IdealMemCertificate O ℤ B I0
  ![![31, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![21, 0, 0, 0, 1]] ![7001890, 1456956, -648479, -339780, 395103] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-41783, 1456956, -648479, -339780, 395103]
 hmem := by decide

def Log02: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![7001899, 1456956, -648479, -339780, 395103]
 hxeq :=  rfl
 m:= 9
 C := ![7001890, 1456956, -648479, -339780, 395103]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log02Mem
 k :=  2
 hpow := by decide
 heql := by decide

def Log10Mem : IdealMemCertificate O ℤ B I1
  ![![31, 0, 0, 0, 0], ![20, 1, 0, 0, 0], ![3, 0, 1, 0, 0], ![22, 0, 0, 1, 0], ![28, 0, 0, 0, 1]] ![-128567, -93443, -10436, 5627, 8855] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![45157, -93443, -10436, 5627, 8855]
 hmem := by decide

def Log10: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 3 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-128547, -93443, -10436, 5627, 8855]
 hxeq :=  rfl
 m:= 20
 C := ![-128567, -93443, -10436, 5627, 8855]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log10Mem
 k :=  8
 hpow := by decide
 heql := by decide

def Log11Mem : IdealMemCertificate O ℤ B I1
  ![![31, 0, 0, 0, 0], ![20, 1, 0, 0, 0], ![3, 0, 1, 0, 0], ![22, 0, 0, 1, 0], ![28, 0, 0, 0, 1]] ![630777067850, 455760802015, 48555409531, -28976360690, -44398778352] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-217724499097, 455760802015, 48555409531, -28976360690, -44398778352]
 hmem := by decide

def Log11: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![630777067853, 455760802015, 48555409531, -28976360690, -44398778352]
 hxeq :=  rfl
 m:= 3
 C := ![630777067850, 455760802015, 48555409531, -28976360690, -44398778352]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log11Mem
 k :=  1
 hpow := by decide
 heql := by decide

def Log12Mem : IdealMemCertificate O ℤ B I1
  ![![31, 0, 0, 0, 0], ![20, 1, 0, 0, 0], ![3, 0, 1, 0, 0], ![22, 0, 0, 1, 0], ![28, 0, 0, 0, 1]] ![7001896, 1456956, -648479, -339780, 395103] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-767081, 1456956, -648479, -339780, 395103]
 hmem := by decide

def Log12: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![7001899, 1456956, -648479, -339780, 395103]
 hxeq :=  rfl
 m:= 3
 C := ![7001896, 1456956, -648479, -339780, 395103]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log12Mem
 k :=  1
 hpow := by decide
 heql := by decide

def Log20Mem : IdealMemCertificate O ℤ B I2
  ![![61, 0, 0, 0, 0], ![6, 1, 0, 0, 0], ![25, 0, 1, 0, 0], ![44, 0, 0, 1, 0], ![54, 0, 0, 0, 1]] ![-128557, -93443, -10436, 5627, 8855] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![-537, -93443, -10436, 5627, 8855]
 hmem := by decide

def Log20: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 3 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-128547, -93443, -10436, 5627, 8855]
 hxeq :=  rfl
 m:= 10
 C := ![-128557, -93443, -10436, 5627, 8855]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log20Mem
 k :=  23
 hpow := by decide
 heql := by decide

def Log21Mem : IdealMemCertificate O ℤ B I2
  ![![61, 0, 0, 0, 0], ![6, 1, 0, 0, 0], ![25, 0, 1, 0, 0], ![44, 0, 0, 1, 0], ![54, 0, 0, 0, 1]] ![630777067811, 455760802015, 48555409531, -28976360690, -44398778352] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![5816736374, 455760802015, 48555409531, -28976360690, -44398778352]
 hmem := by decide

def Log21: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![630777067853, 455760802015, 48555409531, -28976360690, -44398778352]
 hxeq :=  rfl
 m:= 42
 C := ![630777067811, 455760802015, 48555409531, -28976360690, -44398778352]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log21Mem
 k :=  56
 hpow := by decide
 heql := by decide

def Log22Mem : IdealMemCertificate O ℤ B I2
  ![![61, 0, 0, 0, 0], ![6, 1, 0, 0, 0], ![25, 0, 1, 0, 0], ![44, 0, 0, 1, 0], ![54, 0, 0, 0, 1]] ![7001895, 1456956, -648479, -339780, 395103] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![132572, 1456956, -648479, -339780, 395103]
 hmem := by decide

def Log22: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![7001899, 1456956, -648479, -339780, 395103]
 hxeq :=  rfl
 m:= 4
 C := ![7001895, 1456956, -648479, -339780, 395103]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log22Mem
 k :=  2
 hpow := by decide
 heql := by decide

def J : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![2, 0, 0, 0, 0], ![55, 9, -6, -2, 3]] i)))
def MulJ0 : IdealMulEqCertificate O ℤ TT (J) J
  ![![2, 0, 0, 0, 0], ![55, 9, -6, -2, 3]] ![![2, 0, 0, 0, 0], ![55, 9, -6, -2, 3]]
  ![![2, 0, 0, 0, 0], ![33, 4, -4, -1, 2]] where
 T := T
 heq := T_eq_TT
 hI1 := rfl
 hI2 := rfl
 M :=  ![![![4, 0, 0, 0, 0], ![110, 18, -12, -4, 6]], ![![110, 18, -12, -4, 6], ![99, 60, -8, -15, 12]]]
 hmul := by decide
 f :=  ![![![![646760235767385, -9179423088449871, -4292325306564235, -22944529395458, 2567180042404146], ![-6770806901726852, -1683488947101927, 0, -556636539015, -2654268930]], ![![0, 0, 0, 0, 0], ![-10507340, 11628, 0, 9, 0]]], ![![![4775737172029307584, -67781705857780854522, -31694925549463618978, -169424519116569049, 18956293967662398346], ![-49996262010206863262, -12431037498518627226, 0, -4110255491402490, -19599366337872]], ![![0, 0, 0, 0, 0], ![-77587166649, 85862236, 0, 66456, -2]]]]
 g :=  ![![![![-31, -4, 4, 1, -2], ![2, 0, 0, 0, 0]], ![![-17, 1051, 416, -36, -304], ![712, 168, 0, 0, -6]]], ![![![-17, 1051, 416, -36, -304], ![712, 168, 0, 0, -6]], ![![-58, 1972, 782, -72, -567], ![1351, 320, 0, 0, -12]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ1 : IdealMulEqCertificate O ℤ TT (J*J) J
  ![![2, 0, 0, 0, 0], ![33, 4, -4, -1, 2]] ![![2, 0, 0, 0, 0], ![55, 9, -6, -2, 3]]
  ![![4, 0, 0, 0, 0], ![13, 10, 0, -1, 0]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ0
 hI2 := rfl
 M :=  ![![![4, 0, 0, 0, 0], ![110, 18, -12, -4, 6]], ![![66, 8, -8, -2, 4], ![-135, -2, 11, -2, -1]]]
 hmul := by decide
 f :=  ![![![![-73304490867020, 1040405522822558, 486496683600811, 2600551011955, -290966892861771], ![767410412751786, 190808417072325, 0, 63089767083, 300426936]], ![![0, 0, 0, 0, 0], ![-1354460, 20082, 0, 0, -4]]], ![![![-238300320102943, 3382179811810863, 1581517231207762, 8453945062072, -945883436174583], ![2494719557371282, 620285419472604, 0, 205094006019, 976636413]], ![![0, 0, 0, 0, 0], ![-4403117, 65283, 0, 0, -13]]]]
 g :=  ![![![![165020951, -198710798, -130156803, -15280156, 83770779], ![43361168, 55781487, -2562399, 7302, -6]], ![![3960844926, -4769470829, -3124032996, -366755420, 2010672294], ![1040757848, 1338871284, -61502886, 175263, -144]]], ![![![2145952513, -2584059228, -1692574835, -198705006, 1089365359], ![563873858, 725389215, -33321747, 94956, -78]], ![![-4210206695, 5069741000, 3320711828, 389845134, -2137257601], ![-1106280523, -1423162212, 65374905, -186297, 153]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ2 : IdealMulEqCertificate O ℤ TT (J*J*J) J
  ![![4, 0, 0, 0, 0], ![13, 10, 0, -1, 0]] ![![2, 0, 0, 0, 0], ![55, 9, -6, -2, 3]]
  ![![4, 0, 0, 0, 0], ![31, 4, -4, -1, 2]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ1
 hI2 := rfl
 M :=  ![![![8, 0, 0, 0, 0], ![220, 36, -24, -8, 12]], ![![26, 20, 0, -2, 0], ![-167, -44, 15, 4, -3]]]
 hmul := by decide
 f :=  ![![![![-518790436848815321513677, 7363916468020444948883077, 3442833265642597495557595, 18666966803885491594785, -2059640660455264428449036], ![5434259338335006307408084, 1352700998577312200659941, 0, 191589927333233489193, 391383581305416812]], ![![4665941204050998, 263557088985243, 0, 0, 3664424557542], ![-12318618694, 55217616, 0, 19413, 4]]], ![![![-4539236016160467977880437, 64431709756779260071682725, 30123594513355427134249635, 163329471806285041999467, -18021139948290122146957052], ![47547880526786051265676980, 11835663604623723032057841, 0, 1676345276846377293219, 3424470310568088334]], ![![40825363881731682, 2306032929024231, 0, 0, 32062441303144], ![-107783632221, 483134949, 0, 169857, 35]]]]
 g :=  ![![![![-4172, -66040, -26192, 1138, 18208], ![-63320, -13608, -24, 0, 0]], ![![-4505904, -71441638, -28334309, 1231097, 19696972], ![-68487272, -14719743, -26661, 0, 42]]], ![![![-1059674, -16801200, -6663479, 289523, 4632206], ![-16106350, -3461691, -6273, 0, 10]], ![![3957285, 62743678, 24884629, -1081213, -17298879], ![60148953, 12927621, 23418, 0, -37]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ3 : IdealMulEqCertificate O ℤ TT (J*J*J*J) J
  ![![4, 0, 0, 0, 0], ![31, 4, -4, -1, 2]] ![![2, 0, 0, 0, 0], ![55, 9, -6, -2, 3]]
  ![![7001899, 1456956, -648479, -339780, 395103]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ2
 hI2 := rfl
 M :=  ![![![8, 0, 0, 0, 0], ![220, 36, -24, -8, 12]], ![![62, 8, -8, -2, 4], ![-245, -20, 23, 2, -7]]]
 hmul := by decide
 f :=  ![![![![-9680930965923710767117982639, 137414959666901174325957838242, 64245268985660839278567096901, 348336427709172034454735782, -38434091342997938259624229160], ![101406436538964641111473379689, 25242186548421671655603437927, 0, 3575178826552430245906128, 7297065936908231017940]], ![![52858754170027933983, -122802167730112029, 0, 0, 1576399374981718], ![4532420791015, -8884274292, 0, 0, -7650378]]]]
 g :=  ![![![![1052, 1329, -277, -200, 198]], ![![-64158, -11568, 6692, 1895, -2826]]], ![![![-27194, -5411, 2909, 878, -1264]], ![![149873, 17285, -14207, -2984, 5308]]]]
 hle1 := by decide
 hle2 := by decide

lemma J5 : J ^ 5 =  Ideal.span {alpha} := by
 simp only [pow_succ, pow_one, pow_zero, one_mul]
 simp [ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ3, alpha]
lemma isUnit_zeta1 : IsUnit zeta1 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![-609307, 155029, 24866, -21233, 8267])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide

lemma isUnit_zeta2 : IsUnit zeta2 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![-119655258297208879370401570668697119, -24897875605938232957612576843259477, 11081841423197789437942793796535971, 5806491070781033663530911374803324, -6751905473927252215729268177059776])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide



instance hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible

noncomputable instance K_field : Field K := by
  unfold K
  infer_instance

instance K_numberField : NumberField K := by
  unfold K
  infer_instance

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  rw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, P_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by sorry

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K


def SturmRC : SturmBuilderOfList [[868, 435, -40, -40, 0, 1], [435, -80, -120, 0, 5], [-217, -87, 6, 4], [-1, -1], [1]] [868, 435, -40, -40, 0, 1] [435, -80, -120, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 16, 1]
  f := [100, 450, 128]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [-30, 20], [89, -2, -4]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 3 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 - 40*X^3 - 40*X^2 + 435*X + 868
  l := [868, 435, -40, -40, 0, 1]
  hl := ofList_poly
  hlz := by decide
  hz := by decide
  hAdj := Adj_K
  heq := O_integral_closure
  P := [[868, 435, -40, -40, 0, 1], [435, -80, -120, 0, 5], [-217, -87, 6, 4], [-1, -1], [1]]
  SB := SturmRC
  k := 1
  r := 3
  hr := by decide
  hreq := by decide

lemma ne_dvd_torsion5 : ¬5 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
 suffices ¬ 5 ∣ 2 from ?_
 · convert this
   rw [O_integral_closure, ← Fintype.card_eq_nat_card,
   ←  NumberField.Units.torsionOrder_eq_two_of_odd_finrank (by rw [K_finrank] ; decide)]
   rfl
 · decide

def NPCJ : NonPrincipalCertificateNDvdT J where
 p := 5
 hp := by decide
 r := 2
 huc := by
  rw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2]
 hu := fun i =>
  match i with
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
 q := ![31, 31, 61]
 hqP := by
  intro i
  match i with
  | 0 => exact hq31
  | 1 => exact hq31
  | 2 => exact hq61
 I := ![I0, I1, I2]
 hcard := fun i =>
  match i with
  | 0 => N0
  | 1 => N1
  | 2 => N2
 ζ := ![3, 3, 2]
 hr := fun i =>
  match i with
  | 0 => ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 a := alpha
 n := 5
 hpdvd := by decide
 hJ := J5
 hpndvdt := ne_dvd_torsion5
 M := ![![3, 4, 2], ![3, 1, 1], ![3, 1, 2]]
 hM1 := by
  intro j i hj
  fin_cases i <;> interval_cases j
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log00] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log01] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log10] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log11] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log20] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log21] ; decide
 hM2 := by
  intro i
  match i with
  | 0 => exact Log02
  | 1 => exact Log12
  | 2 => exact Log22
 hDl := by decide
 Minv := ![![1, 4, 2], ![2, 0, 3], ![0, 4, 1]]
 hInv := by decide
 N := ![![1, 1], ![2, 3]]
 hNiv := by decide

theorem J_not_principal : ¬ ∃ b, J = Ideal.span {b} :=
  not_principal_of_NonPrincipalCertificateNDvdT NPCJ
