import IdealArithmetic.IdealArithmetic
import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem
import IdealArithmetic.PrincipalityCertificate
import Mathlib.RingTheory.AdjoinRoot

--------------------------------------------
-- EXAMPLE
--------------------------------------------

/- Number field `K(α)` with with α root of polynomial `X^5 - 15*X^3 - 10*X^2 + 210*X + 432`.
Class number `5`, generated by class of ideal `J = (2, -1/42*a^4 + 1/7*a^3 - 3/14*a^2 - 22/21*a - 10/7)`. We have `J ^ 5 = (α)`. -/

/- Ring of integers with basis `[1, a, a^2, 1/7*a^3 - 2/7*a^2 + 1/7*a - 1/7, 1/42*a^4 - 1/14*a^2 + 4/21*a + 2/7]` -/

open BigOperators Classical Matrix Polynomial

noncomputable def P : ℤ[X] := X^5 - 15*X^3 - 10*X^2 + 210*X + 432

def K := AdjoinRoot (map (algebraMap ℤ ℚ) P)

lemma P_irreducible : Irreducible P := sorry
lemma P_degree : P.natDegree = 5 := sorry
lemma P_monic : Monic P := sorry

--local notation "K" =>  AdjoinRoot (map (algebraMap ℤ ℚ) (X^5 - 15*X^3 - 10*X^2 + 210*X + 432 ))

noncomputable instance : CommRing K := by
  unfold K
  infer_instance

noncomputable instance : Algebra ℚ K := by
  unfold K
  infer_instance

noncomputable def Adj_K : IsAdjoinRoot K (map (algebraMap ℤ ℚ) (X^5 - 15*X^3 - 10*X^2 + 210*X + 432 )) := by
  unfold K
  exact AdjoinRoot.isAdjoinRoot (Polynomial.map (algebraMap ℤ ℚ) (X^5 - 15*X^3 - 10*X^2 + 210*X + 432))


lemma ofList_poly : ofList [432, 210, -10, -15, 0, 1] = X^5 - 15*X^3 - 10*X^2 + 210*X + 432   := by
  simp ; ring


noncomputable def O : Subalgebra ℤ K := sorry

noncomputable def TT : TimesTable (Fin 5) ℤ O where
    basis := sorry
    table := ![![![1, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![0, 0, 0, 0, 1]], ![![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![1, -1, 2, 7, 0], ![-2, -1, 0, -2, 6], ![-10, -5, 1, 2, 0]], ![![0, 0, 1, 0, 0], ![1, -1, 2, 7, 0], ![-12, -8, 3, 0, 42], ![-56, -30, 5, 16, -12], ![-3, -13, -3, 3, 12]], ![![0, 0, 0, 1, 0], ![-2, -1, 0, -2, 6], ![-56, -30, 5, 16, -12], ![29, 6, -6, -8, 18], ![-19, -6, 0, -1, -1]], ![![0, 0, 0, 0, 1], ![-10, -5, 1, 2, 0], ![-3, -13, -3, 3, 12], ![-19, -6, 0, -1, -1], ![-6, -5, -1, 0, -1]]]
    basis_mul_basis := sorry

noncomputable def B := TT.basis

lemma B_one : TT.basis 0 = 1 := sorry

lemma B_one_repr : TT.basis.equivFun.symm ![1, 0, 0, 0, 0] = 1 := sorry

def T : Fin 5 → Fin 5 → List ℤ :=
    ![![[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]], ![[0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [1, -1, 2, 7, 0], [-2, -1, 0, -2, 6], [-10, -5, 1, 2, 0]], ![[0, 0, 1, 0, 0], [1, -1, 2, 7, 0], [-12, -8, 3, 0, 42], [-56, -30, 5, 16, -12], [-3, -13, -3, 3, 12]], ![[0, 0, 0, 1, 0], [-2, -1, 0, -2, 6], [-56, -30, 5, 16, -12], [29, 6, -6, -8, 18], [-19, -6, 0, -1, -1]], ![[0, 0, 0, 0, 1], [-10, -5, 1, 2, 0], [-3, -13, -3, 3, 12], [-19, -6, 0, -1, -1], [-6, -5, -1, 0, -1]]]

lemma T_eq_TT : ∀ (i j : Fin 5), T i j = List.ofFn (TT.table i j) := by
  simp ; decide



instance : IsDomain O := by
  haveI hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) :=
  {out := (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible}
  letI hola : Field K := by
    unfold K
    exact AdjoinRoot.instField
  haveI : IsDomain K := by infer_instance
  refine Subalgebra.isDomain O

noncomputable section

instance hq101 : Fact $ Nat.Prime 101 := by decide
instance hq61 : Fact $ Nat.Prime 61 := by decide
instance hq31 : Fact $ Nat.Prime 31 := by decide

def R101 : IsOrderOf (2 : ZMod 101) 100 where
 m := 2
 P := ![2, 5]
 e := ![2, 2]
 hP := by decide
 hm := by rfl
 hid := by sorry
 hnid := by decide

def R61 : IsOrderOf (2 : ZMod 61) 60 where
 m := 3
 P := ![2, 3, 5]
 e := ![2, 1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def R31 : IsOrderOf (3 : ZMod 31) 30 where
 m := 3
 P := ![2, 3, 5]
 e := ![1, 1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def I0 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![31, 0, 0, 0, 0], ![10, 1, 0, 0, 0]] i)))
def I1 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![61, 0, 0, 0, 0], ![-11, 1, 0, 0, 0]] i)))
def I2 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![101, 0, 0, 0, 0], ![10, 1, 0, 0, 0]] i)))

def A0: IdealEqSpanCertificate O ℤ TT I0
 ![![31, 0, 0, 0, 0], ![10, 1, 0, 0, 0]]
 ![![31, 0, 0, 0, 0], ![10, 1, 0, 0, 0], ![24, 0, 1, 0, 0], ![18, 0, 0, 1, 0], ![29, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![31, 0, 0, 0, 0], ![0, 31, 0, 0, 0], ![0, 0, 31, 0, 0], ![0, 0, 0, 31, 0], ![0, 0, 0, 0, 31]], ![![10, 1, 0, 0, 0], ![0, 10, 1, 0, 0], ![1, -1, 12, 7, 0], ![-2, -1, 0, 8, 6], ![-10, -5, 1, 2, 10]]]
  hmulB := by decide
  f := ![![![46671279, 5221624, 4467174, 2548014, -1596], ![-143549964, -2960562, -11293486, 8246, 0]], ![![17194422, 1923723, 1645776, 938728, -588], ![-52886030, -1090704, -4160696, 3038, 0]], ![![36844847, 4122229, 3526630, 2011541, -1260], ![-113326152, -2337213, -8915693, 6510, 0]], ![![27020302, 3023052, 2586267, 1475171, -924], ![-83108144, -1714005, -6538356, 4774, 0]], ![![43660241, 4884744, 4178969, 2383626, -1493], ![-134288714, -2769551, -10564874, 7714, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-10, 31, 0, 0, 0], ![-24, 0, 31, 0, 0], ![-18, 0, 0, 31, 0], ![-29, 0, 0, 0, 31]], ![![0, 1, 0, 0, 0], ![-4, 10, 1, 0, 0], ![-13, -1, 12, 7, 0], ![-10, -1, 0, 8, 6], ![-10, -5, 1, 2, 10]]]
  hle1 := by decide
  hle2 := by decide

lemma N0 : Nat.card (O ⧸ I0) = 31 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A0)

def A1: IdealEqSpanCertificate O ℤ TT I1
 ![![61, 0, 0, 0, 0], ![-11, 1, 0, 0, 0]]
 ![![61, 0, 0, 0, 0], ![50, 1, 0, 0, 0], ![1, 0, 1, 0, 0], ![26, 0, 0, 1, 0], ![44, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![61, 0, 0, 0, 0], ![0, 61, 0, 0, 0], ![0, 0, 61, 0, 0], ![0, 0, 0, 61, 0], ![0, 0, 0, 0, 61]], ![![-11, 1, 0, 0, 0], ![0, -11, 1, 0, 0], ![1, -1, -9, 7, 0], ![-2, -1, 0, -13, 6], ![-10, -5, 1, 2, -11]]]
  hmulB := by decide
  f := ![![![20960568, -1986780, -272910, 247111, -14256], ![116038226, -310551, -1884229, 144936, 0]], ![![17467221, -1655663, -227426, 205927, -11880], ![96698970, -258823, -1570201, 120780, 0]], ![![388159, -36789, -5054, 4576, -264], ![2148858, -5733, -34892, 2684, 0]], ![![8927660, -846216, -116240, 105251, -6072], ![49423748, -132238, -802542, 61732, 0]], ![![15119104, -1433089, -196853, 178244, -10283], ![83699736, -224011, -1359116, 104544, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-50, 61, 0, 0, 0], ![-1, 0, 61, 0, 0], ![-26, 0, 0, 61, 0], ![-44, 0, 0, 0, 61]], ![![-1, 1, 0, 0, 0], ![9, -11, 1, 0, 0], ![-2, -1, -9, 7, 0], ![2, -1, 0, -13, 6], ![11, -5, 1, 2, -11]]]
  hle1 := by decide
  hle2 := by decide

lemma N1 : Nat.card (O ⧸ I1) = 61 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A1)

def A2: IdealEqSpanCertificate O ℤ TT I2
 ![![101, 0, 0, 0, 0], ![10, 1, 0, 0, 0]]
 ![![101, 0, 0, 0, 0], ![10, 1, 0, 0, 0], ![1, 0, 1, 0, 0], ![72, 0, 0, 1, 0], ![40, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![101, 0, 0, 0, 0], ![0, 101, 0, 0, 0], ![0, 0, 101, 0, 0], ![0, 0, 0, 101, 0], ![0, 0, 0, 0, 101]], ![![10, 1, 0, 0, 0], ![0, 10, 1, 0, 0], ![1, -1, 12, 7, 0], ![-2, -1, 0, 8, 6], ![-10, -5, 1, 2, 10]]]
  hmulB := by decide
  f := ![![![-46445053581, -4630919069, -750289018, -434531492, -40044], ![468468286163, 552411218, 6268898300, 674074, 0]], ![![-4941030050, -492657637, -79819061, -46227380, -4260], ![49837726538, 58767961, 666913100, 71710, 0]], ![![-494095527, -49265026, -7981786, -4622668, -426], ![4983697227, 5876787, 66690300, 7171, 0]], ![![-33104453094, -3300761461, -534780470, -309719255, -28542], ![333908246618, 393739870, 4468257300, 480457, 0]], ![![-18394080640, -1834027360, -297144166, -172091680, -15859], ![185531994660, 218776766, 2482732000, 266960, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-10, 101, 0, 0, 0], ![-1, 0, 101, 0, 0], ![-72, 0, 0, 101, 0], ![-40, 0, 0, 0, 101]], ![![0, 1, 0, 0, 0], ![-1, 10, 1, 0, 0], ![-5, -1, 12, 7, 0], ![-8, -1, 0, 8, 6], ![-5, -5, 1, 2, 10]]]
  hle1 := by decide
  hle2 := by decide

lemma N2 : Nat.card (O ⧸ I2) = 101 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A2)

def zeta1 := TT.basis.equivFun.symm ![31, 3, -3, 2, 4]

def zeta2 := TT.basis.equivFun.symm ![392694878126, 289411646068, 23958228906, -45790090041, -121311276284]

def alpha := TT.basis.equivFun.symm ![6757389, 6027576, -1809813, -4094779, 6741089]

def Log00Mem : IdealMemCertificate O ℤ B I0
  ![![31, 0, 0, 0, 0], ![10, 1, 0, 0, 0], ![24, 0, 1, 0, 0], ![18, 0, 0, 1, 0], ![29, 0, 0, 0, 1]] ![17, 3, -3, 2, 4] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-3, 3, -3, 2, 4]
 hmem := by decide

def Log00: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![31, 3, -3, 2, 4]
 hxeq :=  rfl
 m:= 14
 C := ![17, 3, -3, 2, 4]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log00Mem
 k :=  22
 hpow := by decide
 heql := by decide

def Log01Mem : IdealMemCertificate O ℤ B I0
  ![![31, 0, 0, 0, 0], ![10, 1, 0, 0, 0], ![24, 0, 1, 0, 0], ![18, 0, 0, 1, 0], ![29, 0, 0, 0, 1]] ![392694878105, 289411646068, 23958228906, -45790090041, -121311276284] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![40833211505, 289411646068, 23958228906, -45790090041, -121311276284]
 hmem := by decide

def Log01: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 4 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![392694878126, 289411646068, 23958228906, -45790090041, -121311276284]
 hxeq :=  rfl
 m:= 21
 C := ![392694878105, 289411646068, 23958228906, -45790090041, -121311276284]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log01Mem
 k :=  29
 hpow := by decide
 heql := by decide

def Log02Mem : IdealMemCertificate O ℤ B I0
  ![![31, 0, 0, 0, 0], ![10, 1, 0, 0, 0], ![24, 0, 1, 0, 0], ![18, 0, 0, 1, 0], ![29, 0, 0, 0, 1]] ![6757387, 6027576, -1809813, -4094779, 6741089] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-4253820, 6027576, -1809813, -4094779, 6741089]
 hmem := by decide

def Log02: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 4 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![6757389, 6027576, -1809813, -4094779, 6741089]
 hxeq :=  rfl
 m:= 2
 C := ![6757387, 6027576, -1809813, -4094779, 6741089]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log02Mem
 k :=  24
 hpow := by decide
 heql := by decide

def Log10Mem : IdealMemCertificate O ℤ B I1
  ![![61, 0, 0, 0, 0], ![50, 1, 0, 0, 0], ![1, 0, 1, 0, 0], ![26, 0, 0, 1, 0], ![44, 0, 0, 0, 1]] ![9, 3, -3, 2, 4] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-6, 3, -3, 2, 4]
 hmem := by decide

def Log10: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![31, 3, -3, 2, 4]
 hxeq :=  rfl
 m:= 22
 C := ![9, 3, -3, 2, 4]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log10Mem
 k :=  16
 hpow := by decide
 heql := by decide

def Log11Mem : IdealMemCertificate O ℤ B I1
  ![![61, 0, 0, 0, 0], ![50, 1, 0, 0, 0], ![1, 0, 1, 0, 0], ![26, 0, 0, 1, 0], ![44, 0, 0, 0, 1]] ![392694878113, 289411646068, 23958228906, -45790090041, -121311276284] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-124157494371, 289411646068, 23958228906, -45790090041, -121311276284]
 hmem := by decide

def Log11: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![392694878126, 289411646068, 23958228906, -45790090041, -121311276284]
 hxeq :=  rfl
 m:= 13
 C := ![392694878113, 289411646068, 23958228906, -45790090041, -121311276284]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log11Mem
 k :=  40
 hpow := by decide
 heql := by decide

def Log12Mem : IdealMemCertificate O ℤ B I1
  ![![61, 0, 0, 0, 0], ![50, 1, 0, 0, 0], ![1, 0, 1, 0, 0], ![26, 0, 0, 1, 0], ![44, 0, 0, 0, 1]] ![6757349, 6027576, -1809813, -4094779, 6741089] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-7917300, 6027576, -1809813, -4094779, 6741089]
 hmem := by decide

def Log12: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![6757389, 6027576, -1809813, -4094779, 6741089]
 hxeq :=  rfl
 m:= 40
 C := ![6757349, 6027576, -1809813, -4094779, 6741089]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log12Mem
 k :=  25
 hpow := by decide
 heql := by decide

def Log20Mem : IdealMemCertificate O ℤ B I2
  ![![101, 0, 0, 0, 0], ![10, 1, 0, 0, 0], ![1, 0, 1, 0, 0], ![72, 0, 0, 1, 0], ![40, 0, 0, 0, 1]] ![28, 3, -3, 2, 4] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![-3, 3, -3, 2, 4]
 hmem := by decide

def Log20: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R101) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 4 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![31, 3, -3, 2, 4]
 hxeq :=  rfl
 m:= 3
 C := ![28, 3, -3, 2, 4]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log20Mem
 k :=  69
 hpow := by decide
 heql := by decide

def Log21Mem : IdealMemCertificate O ℤ B I2
  ![![101, 0, 0, 0, 0], ![10, 1, 0, 0, 0], ![1, 0, 1, 0, 0], ![72, 0, 0, 1, 0], ![40, 0, 0, 0, 1]] ![392694878105, 289411646068, 23958228906, -45790090041, -121311276284] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![55682749731, 289411646068, 23958228906, -45790090041, -121311276284]
 hmem := by decide

def Log21: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R101) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 3 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![392694878126, 289411646068, 23958228906, -45790090041, -121311276284]
 hxeq :=  rfl
 m:= 21
 C := ![392694878105, 289411646068, 23958228906, -45790090041, -121311276284]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log21Mem
 k :=  78
 hpow := by decide
 heql := by decide

def Log22Mem : IdealMemCertificate O ℤ B I2
  ![![101, 0, 0, 0, 0], ![10, 1, 0, 0, 0], ![1, 0, 1, 0, 0], ![72, 0, 0, 1, 0], ![40, 0, 0, 0, 1]] ![6757365, 6027576, -1809813, -4094779, 6741089] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![-262654, 6027576, -1809813, -4094779, 6741089]
 hmem := by decide

def Log22: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R101) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![6757389, 6027576, -1809813, -4094779, 6741089]
 hxeq :=  rfl
 m:= 24
 C := ![6757365, 6027576, -1809813, -4094779, 6741089]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log22Mem
 k :=  72
 hpow := by decide
 heql := by decide

def J : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![2, 0, 0, 0, 0], ![-1, -1, 0, 1, -1]] i)))
def MulJ0 : IdealMulEqCertificate O ℤ TT (J) J
  ![![2, 0, 0, 0, 0], ![-1, -1, 0, 1, -1]] ![![2, 0, 0, 0, 0], ![-1, -1, 0, 1, -1]]
  ![![4, 0, 0, 0, 0], ![1, -1, 0, 1, -1]] where
 T := T
 heq := T_eq_TT
 hI1 := rfl
 hI2 := rfl
 M :=  ![![![4, 0, 0, 0, 0], ![-2, -2, 0, 2, -2]], ![![-2, -2, 0, 2, -2], ![46, 7, -4, 0, 9]]]
 hmul := by decide
 f :=  ![![![![-22213529875, -1569246315, 7913385103, 5105326877, -13439357082], ![21163730076, 7741606335, -64417038, 3552369, 0]], ![![0, 0, 0, 0, 0], ![137574, 29034, 80, -4, 0]]], ![![![-5549879078, -392064086, 1977098222, 1275526536, -3357719692], ![5287594698, 1934180622, -16094100, 887532, 0]], ![![0, 0, 0, 0, 0], ![34372, 7254, 20, -1, 0]]]]
 g :=  ![![![![39592879, 21630177, -9301636, -16777170, 26419298], ![-6308440, -18168004, 123560, -936, 0]], ![![-39592863, -21630167, 9301632, 16777162, -26419286], ![6308442, 18167996, -123560, 936, 0]]], ![![![-39592863, -21630167, 9301632, 16777162, -26419286], ![6308442, 18167996, -123560, 936, 0]], ![![454943148, 248542186, -106880724, -192778564, 303571723], ![-72487328, -208759986, 1419770, -10755, 0]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ1 : IdealMulEqCertificate O ℤ TT (J*J) J
  ![![4, 0, 0, 0, 0], ![1, -1, 0, 1, -1]] ![![2, 0, 0, 0, 0], ![-1, -1, 0, 1, -1]]
  ![![8, 0, 0, 0, 0], ![-3, -1, 0, 1, -1]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ0
 hI2 := rfl
 M :=  ![![![8, 0, 0, 0, 0], ![-4, -4, 0, 4, -4]], ![![2, -2, 0, 2, -2], ![44, 5, -4, 2, 7]]]
 hmul := by decide
 f :=  ![![![![397531867990734314, 27893742348618692, -145106077744799001, -97083339209664766, 245628233364103941], ![-384068591456560854, -143748159971933853, 528079133892002, -12615488647811, 0]], ![![-2080528997636, 245563380444, -2043337128, 112983220, 0], ![1772676, 164100, 256, -8, 0]]], ![![![-149085324493888486, -10460916379890490, 54418748353334522, 36408907799463444, -92117306371024152], ![144036227522133288, 53909492044332554, -198044120167432, 4731153324170, 0]], ![![780255284436, -92092984752, 766307316, -42371798, 0], ![-664802, -61542, -96, 3, 0]]]]
 g :=  ![![![![356089321, 32376803, -103795616, -182968192, 292027624], ![-196955072, -410948744, 2807856, -7312, 0]], ![![-1035530386, -94153802, 301844252, 532083137, -849234901], ![572757884, 1195065080, -8165424, 21264, 0]]], ![![![-339720534, -30888500, 99024318, 174557473, -278603639], ![187901402, 392058168, -2678784, 6976, 0]], ![![2042403031, 185701949, -595335126, -1049441159, 1674967682], ![-1129664978, -2357057374, 16104874, -41939, 0]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ2 : IdealMulEqCertificate O ℤ TT (J*J*J) J
  ![![8, 0, 0, 0, 0], ![-3, -1, 0, 1, -1]] ![![2, 0, 0, 0, 0], ![-1, -1, 0, 1, -1]]
  ![![16, 0, 0, 0, 0], ![5, -1, 0, 1, -1]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ1
 hI2 := rfl
 M :=  ![![![16, 0, 0, 0, 0], ![-8, -8, 0, 8, -8]], ![![-6, -2, 0, 2, -2], ![48, 9, -4, -2, 11]]]
 hmul := by decide
 f :=  ![![![![591014104229934078, 41347350134862996, -217927705651177541, -147936689602241970, 368314217236521869], ![-574306180601780454, -216973718721738585, 376573787936430, -4184970465495, 0]], ![![568702257144, 9706679464, -66011264, 483144, 0], ![18216, -10008, -128, 16, 0]]], ![![![184899857871360822, 12935595121295492, -68179086611878535, -46282267522286223, 115227785481985068], ![-179672752998463801, -67880630032920525, 117811807483425, -1309275766395, 0]], ![![177919555163, 3036752661, -20651746, 151152, 0], ![5698, -3132, -40, 5, 0]]]]
 g :=  ![![![![-4655397294003, -5548149125881, 1220837427360, 2491173753124, -3710054915404], ![-720475542208, 9791269605360, 4462318944, -9144096, 0]], ![![5688843957939, 6779776813729, -1491849821544, -3044186748986, 4533646036258], ![880413136936, -11964823068240, -5452904352, 11173984, 0]]], ![![![2586060312983, 3081981484903, -678171812226, -1383840125528, 2060925237916], ![400222169794, -5439023168400, -2478805824, 5079520, 0]], ![![-17004087317622, -20264911076292, 4459173923182, 9099145217126, -13551173777595], ![-2631575407318, 35763135304170, 16298858330, -33399299, 0]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ3 : IdealMulEqCertificate O ℤ TT (J*J*J*J) J
  ![![16, 0, 0, 0, 0], ![5, -1, 0, 1, -1]] ![![2, 0, 0, 0, 0], ![-1, -1, 0, 1, -1]]
  ![![6757389, 6027576, -1809813, -4094779, 6741089]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ2
 hI2 := rfl
 M :=  ![![![32, 0, 0, 0, 0], ![-16, -16, 0, 16, -16]], ![![10, -2, 0, 2, -2], ![40, 1, -4, 6, 3]]]
 hmul := by decide
 f :=  ![![![![2285805598629361466992594077007, 159690479400750397020568876939, -846789914712538750802982132322, -578606417432429052007102413410, 1430036481361841564838029014689], ![-2227069488412191240429147191022, -844994470462653117552984374386, 713573996749418342947826872, -3836485126116364422058938, 0]], ![![-165569486591031533971935, 1521665590949611756793, -10396959428329584894, 27071913480634912, 0], ![10518351625446, -454171208667, 380223597, -6757389, 0]]]]
 g :=  ![![![![-7195003945163553, -284813996408281, 478536430519426, 722685512057452, -1815308619309563]], ![![10327863093324795, 408828123568259, -686901463465510, -1037358295414948, 2605732955152041]]], ![![![-1407143592770733, -55701733207073, 93588478511596, 141337280094676, -355024112847081]], ![![2019844115381504, 79955463403221, -134338910797965, -202878565449839, 509609231663930]]]]
 hle1 := by decide
 hle2 := by decide

lemma J5 : J ^ 5 =  Ideal.span {alpha} := by
 simp only [pow_succ, pow_one, pow_zero, one_mul]
 simp [ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ3, alpha]
lemma isUnit_zeta1 : IsUnit zeta1 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![5, 5, 1, 0, -2])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide

lemma isUnit_zeta2 : IsUnit zeta2 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![1323656430514361333763019035544884124, 52396896613201827574416019036216166, -88035785431112560403462538678308764, -132951605386877252994020568737983675, 333960195940188787746016313219786422])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide



instance hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible

noncomputable instance K_field : Field K := by
  unfold K
  infer_instance

instance K_numberField : NumberField K := by
  unfold K
  infer_instance

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  rw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, P_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by sorry

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K


def SturmRC : SturmBuilderOfList [[432, 210, -10, -15, 0, 1], [210, -20, -45, 0, 5], [-72, -28, 1, 1], [3, -4, -2], [3, 1], [1]] [432, 210, -10, -15, 0, 1] [210, -20, -45, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 5 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 1, 4, 1]
  f := [150, 50, 98, 3]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [-5, 5], [2, -2], [2, -2]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 - 15*X^3 - 10*X^2 + 210*X + 432
  l := [432, 210, -10, -15, 0, 1]
  hl := ofList_poly
  hlz := by decide
  hz := by decide
  hAdj := Adj_K
  heq := O_integral_closure
  P := [[432, 210, -10, -15, 0, 1], [210, -20, -45, 0, 5], [-72, -28, 1, 1], [3, -4, -2], [3, 1], [1]]
  SB := SturmRC
  k := 1
  r := 3
  hr := by decide
  hreq := by decide

lemma ne_dvd_torsion5 : ¬5 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
 suffices ¬ 5 ∣ 2 from ?_
 · convert this
   rw [O_integral_closure, ← Fintype.card_eq_nat_card,
   ←  NumberField.Units.torsionOrder_eq_two_of_odd_finrank (by rw [K_finrank] ; decide)]
   rfl
 · decide

def NPCJ : NonPrincipalCertificateNDvdT J where
 p := 5
 hp := by decide
 r := 2
 huc := by
  rw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2]
 hu := fun i =>
  match i with
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
 q := ![31, 61, 101]
 hqP := by
  intro i
  match i with
  | 0 => exact hq31
  | 1 => exact hq61
  | 2 => exact hq101
 I := ![I0, I1, I2]
 hcard := fun i =>
  match i with
  | 0 => N0
  | 1 => N1
  | 2 => N2
 ζ := ![3, 2, 2]
 hr := fun i =>
  match i with
  | 0 => ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf R101) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 a := alpha
 n := 5
 hpdvd := by decide
 hJ := J5
 hpndvdt := ne_dvd_torsion5
 M := ![![2, 4, 4], ![1, 0, 0], ![4, 3, 2]]
 hM1 := by
  intro j i hj
  fin_cases i <;> interval_cases j
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log00] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log01] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log10] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log11] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log20] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log21] ; decide
 hM2 := by
  intro i
  match i with
  | 0 => exact Log02
  | 1 => exact Log12
  | 2 => exact Log22
 hDl := by decide
 Minv := ![![0, 1, 0], ![2, 2, 1], ![2, 0, 4]]
 hInv := by decide
 N := ![![0, 1], ![4, 2]]
 hNiv := by decide

theorem J_not_principal : ¬ ∃ b, J = Ideal.span {b} :=
  not_principal_of_NonPrincipalCertificateNDvdT NPCJ
