import IdealArithmetic.IdealArithmetic
import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem
import IdealArithmetic.PrincipalityCertificate
import Mathlib.RingTheory.AdjoinRoot


open BigOperators Classical Matrix Polynomial
--------------------------------------------
-- EXAMPLE
--------------------------------------------

/- Number field `K(α)` with with α root of polynomial `X^5 + 5*X^3 - 30*X^2 - 96 `.
Class number `5`, generated by class of ideal `J = (2, -1/8*a^4 - 1/8*a^3 - 11/8*a^2 - 1/8*a + 11/4)`. We have `J ^ 5 = (α)`. -/

/- Ring of integers with basis `1, a, a^2, 1/2*a^3 - 1/2*a, 1/24*a^4 - 1/8*a^3 - 5/24*a^2 + 5/24*a - 1/4` -/

/- Minkowski's bound is around 25 -/


/-- TIP : Reveal to Lean that K is a field and number field until the very end, otherwise things slow down. -/

noncomputable def P : ℤ[X] := (X^5 + 5*X^3 - 30*X^2 - 96  )

def K := AdjoinRoot (map (algebraMap ℤ ℚ) P)

lemma P_irreducible : Irreducible P := sorry
lemma P_degree : P.natDegree = 5 := sorry
lemma P_monic : Monic P := sorry

--local notation "K" =>  AdjoinRoot (map (algebraMap ℤ ℚ) (X^5 + 10*X^3 - 10*X^2 - 15*X - 18 ))

noncomputable instance : CommRing K := by
  unfold K
  infer_instance

noncomputable instance : Algebra ℚ K := by
  unfold K
  infer_instance

noncomputable def Adj_K : IsAdjoinRoot K (map (algebraMap ℤ ℚ) (X^5 + 5*X^3 - 30*X^2 - 96  )) := by
  unfold K
  exact AdjoinRoot.isAdjoinRoot (Polynomial.map (algebraMap ℤ ℚ) (X^5 + 5*X^3 - 30*X^2 - 96 ))


lemma ofList_poly : ofList [-96, 0, -30, 5, 0, 1] = X^5 + 5*X^3 - 30*X^2 - 96   := by
  simp ; ring


noncomputable def O : Subalgebra ℤ K := sorry

noncomputable def TT : TimesTable (Fin 5) ℤ O :=
  { basis := sorry,
    table := ![ ![![1, 0, 0, 0, 0],![0, 1, 0, 0, 0],![0, 0, 1, 0, 0],![0, 0, 0, 1, 0],![0, 0, 0, 0, 1]],
![![0, 1, 0, 0, 0],![0, 1, 2, 0, 0],![0, 0, -1, 1, 0],![4, 0, 2, 4, 8],![4, 1, 3, -3, -4]],
![![0, 0, 1, 0, 0],![0, 0, -1, 1, 0],![2, 0, 2, 1, 4],![22, 6, 14, -5, -4],![-16, 0, -11, 3, -2]],
![![0, 0, 0, 1, 0],![4, 0, 2, 4, 8],![22, 6, 14, -5, -4],![-14, 30, -10, 1, -28],![-12, -18, 0, 10, 30]],
![![0, 0, 0, 0, 1],![4, 1, 3, -3, -4],![-16, 0, -11, 3, -2],![-12, -18, 0, 10, 30],![30, 9, 12, -12, -20]]]
    basis_mul_basis := sorry }

noncomputable def B := TT.basis

lemma B_one : TT.basis 0 = 1 := sorry

lemma B_one_repr : TT.basis.equivFun.symm ![1, 0, 0, 0, 0] = 1 := sorry

def T : Fin 5 → Fin 5 → List ℤ :=
  ![ ![[1, 0, 0, 0, 0],[0, 1, 0, 0, 0],[0, 0, 1, 0, 0],[0, 0, 0, 1, 0],[0, 0, 0, 0, 1]],
![[0, 1, 0, 0, 0],[0, 1, 2, 0, 0],[0, 0, -1, 1, 0],[4, 0, 2, 4, 8],[4, 1, 3, -3, -4]],
![[0, 0, 1, 0, 0],[0, 0, -1, 1, 0],[2, 0, 2, 1, 4],[22, 6, 14, -5, -4],[-16, 0, -11, 3, -2]],
![[0, 0, 0, 1, 0],[4, 0, 2, 4, 8],[22, 6, 14, -5, -4],[-14, 30, -10, 1, -28],[-12, -18, 0, 10, 30]],
![[0, 0, 0, 0, 1],[4, 1, 3, -3, -4],[-16, 0, -11, 3, -2],[-12, -18, 0, 10, 30],[30, 9, 12, -12, -20]]]

lemma T_eq_TT : ∀ (i j : Fin 5), T i j = List.ofFn (TT.table i j) := by
  simp ; decide


instance : IsDomain O := by
  haveI hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) :=
  {out := (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible}
  letI hola : Field K := by
    unfold K
    exact AdjoinRoot.instField
  haveI : IsDomain K := by infer_instance
  refine Subalgebra.isDomain O


noncomputable section

instance hq11 : Fact $ Nat.Prime 11 := by decide
instance hq31 : Fact $ Nat.Prime 31 := by decide

def R11 : IsOrderOf (2 : ZMod 11) 10 where
 m := 2
 P := ![2, 5]
 e := ![1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def R31 : IsOrderOf (3 : ZMod 31) 30 where
 m := 3
 P := ![2, 3, 5]
 e := ![1, 1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def I0 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![11, 0, 0, 0, 0], ![1, 1, 0, 0, 0]] i)))
def I1 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![11, 0, 0, 0, 0], ![6, 1, 0, 0, 0]] i)))
def I2 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![31, 0, 0, 0, 0], ![3, 1, 0, 0, 0]] i)))

def A0: IdealEqSpanCertificate O ℤ TT I0
 ![![11, 0, 0, 0, 0], ![1, 1, 0, 0, 0]]
 ![![11, 0, 0, 0, 0], ![1, 1, 0, 0, 0], ![10, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![9, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![11, 0, 0, 0, 0], ![0, 11, 0, 0, 0], ![0, 0, 11, 0, 0], ![0, 0, 0, 11, 0], ![0, 0, 0, 0, 11]], ![![1, 1, 0, 0, 0], ![0, 2, 2, 0, 0], ![0, 0, 0, 1, 0], ![4, 0, 2, 5, 8], ![4, 1, 3, -3, -3]]]
  hmulB := by decide
  f := ![![![144, 63, 40, 0, 160], ![-693, 0, 1100, -220, 0]], ![![14, 6, 4, 0, 16], ![-65, 0, 110, -22, 0]], ![![130, 58, 37, 0, 144], ![-628, -5, 990, -198, 0]], ![![0, 0, 0, 0, 0], ![0, 0, 1, 0, 0]], ![![118, 51, 32, 0, 131], ![-569, 4, 900, -180, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-1, 11, 0, 0, 0], ![-10, 0, 11, 0, 0], ![0, 0, 0, 11, 0], ![-9, 0, 0, 0, 11]], ![![0, 1, 0, 0, 0], ![-2, 2, 2, 0, 0], ![0, 0, 0, 1, 0], ![-8, 0, 2, 5, 8], ![0, 1, 3, -3, -3]]]
  hle1 := by decide
  hle2 := by decide

lemma N0 : Nat.card (O ⧸ I0) = 11 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A0)

def A1: IdealEqSpanCertificate O ℤ TT I1
 ![![11, 0, 0, 0, 0], ![6, 1, 0, 0, 0]]
 ![![11, 0, 0, 0, 0], ![6, 1, 0, 0, 0], ![1, 0, 1, 0, 0], ![6, 0, 0, 1, 0], ![1, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![11, 0, 0, 0, 0], ![0, 11, 0, 0, 0], ![0, 0, 11, 0, 0], ![0, 0, 0, 11, 0], ![0, 0, 0, 0, 11]], ![![6, 1, 0, 0, 0], ![0, 7, 2, 0, 0], ![0, 0, 5, 1, 0], ![4, 0, 2, 10, 8], ![4, 1, 3, -3, 2]]]
  hmulB := by decide
  f := ![![![65, -20, 405, 121, 32], ![-88, 44, -891, -44, 0]], ![![58, -21, 405, 121, 32], ![-76, 44, -891, -44, 0]], ![![31, -7, 181, 56, 16], ![-42, 17, -396, -22, 0]], ![![26, -13, 204, 61, 16], ![-32, 25, -450, -22, 0]], ![![-5, -10, 35, 11, 3], ![12, 14, -81, -4, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-6, 11, 0, 0, 0], ![-1, 0, 11, 0, 0], ![-6, 0, 0, 11, 0], ![-1, 0, 0, 0, 11]], ![![0, 1, 0, 0, 0], ![-4, 7, 2, 0, 0], ![-1, 0, 5, 1, 0], ![-6, 0, 2, 10, 8], ![1, 1, 3, -3, 2]]]
  hle1 := by decide
  hle2 := by decide

lemma N1 : Nat.card (O ⧸ I1) = 11 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A1)

def A2: IdealEqSpanCertificate O ℤ TT I2
 ![![31, 0, 0, 0, 0], ![3, 1, 0, 0, 0]]
 ![![31, 0, 0, 0, 0], ![3, 1, 0, 0, 0], ![25, 0, 1, 0, 0], ![12, 0, 0, 1, 0], ![7, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![31, 0, 0, 0, 0], ![0, 31, 0, 0, 0], ![0, 0, 31, 0, 0], ![0, 0, 0, 31, 0], ![0, 0, 0, 0, 31]], ![![3, 1, 0, 0, 0], ![0, 4, 2, 0, 0], ![0, 0, 2, 1, 0], ![4, 0, 2, 7, 8], ![4, 1, 3, -3, -1]]]
  hmulB := by decide
  f := ![![![6282, 1971, 15144, 7750, 208], ![-63829, 682, -234608, -806, 0]], ![![958, 298, 2336, 1196, 32], ![-9733, 124, -36208, -124, 0]], ![![5312, 1663, 12805, 6554, 176], ![-53973, 605, -198400, -682, 0]], ![![2416, 756, 5824, 2981, 80], ![-24548, 278, -90240, -310, 0]], ![![1416, 441, 3418, 1750, 47], ![-14387, 179, -52976, -182, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-3, 31, 0, 0, 0], ![-25, 0, 31, 0, 0], ![-12, 0, 0, 31, 0], ![-7, 0, 0, 0, 31]], ![![0, 1, 0, 0, 0], ![-2, 4, 2, 0, 0], ![-2, 0, 2, 1, 0], ![-6, 0, 2, 7, 8], ![-1, 1, 3, -3, -1]]]
  hle1 := by decide
  hle2 := by decide

lemma N2 : Nat.card (O ⧸ I2) = 31 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A2)

def zeta1 := TT.basis.equivFun.symm ![-15, -12, 5, 5, 8]

def zeta2 := TT.basis.equivFun.symm ![26991, 99902, -36483, -33365, -61972]

def alpha := TT.basis.equivFun.symm ![658, 471, 553, 230, 264]

def Log00Mem : IdealMemCertificate O ℤ B I0
  ![![11, 0, 0, 0, 0], ![1, 1, 0, 0, 0], ![10, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![9, 0, 0, 0, 1]] ![-22, -12, 5, 5, 8] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-12, -12, 5, 5, 8]
 hmem := by decide

def Log00: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-15, -12, 5, 5, 8]
 hxeq :=  rfl
 m:= 7
 C := ![-22, -12, 5, 5, 8]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log00Mem
 k :=  7
 hpow := by decide
 heql := by decide

def Log01Mem : IdealMemCertificate O ℤ B I0
  ![![11, 0, 0, 0, 0], ![1, 1, 0, 0, 0], ![10, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![9, 0, 0, 0, 1]] ![26986, 99902, -36483, -33365, -61972] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![77242, 99902, -36483, -33365, -61972]
 hmem := by decide

def Log01: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 4 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![26991, 99902, -36483, -33365, -61972]
 hxeq :=  rfl
 m:= 5
 C := ![26986, 99902, -36483, -33365, -61972]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log01Mem
 k :=  4
 hpow := by decide
 heql := by decide

def Log02Mem : IdealMemCertificate O ℤ B I0
  ![![11, 0, 0, 0, 0], ![1, 1, 0, 0, 0], ![10, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![9, 0, 0, 0, 1]] ![655, 471, 553, 230, 264] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-702, 471, 553, 230, 264]
 hmem := by decide

def Log02: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 3 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![658, 471, 553, 230, 264]
 hxeq :=  rfl
 m:= 3
 C := ![655, 471, 553, 230, 264]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log02Mem
 k :=  8
 hpow := by decide
 heql := by decide

def Log10Mem : IdealMemCertificate O ℤ B I1
  ![![11, 0, 0, 0, 0], ![6, 1, 0, 0, 0], ![1, 0, 1, 0, 0], ![6, 0, 0, 1, 0], ![1, 0, 0, 0, 1]] ![-18, -12, 5, 5, 8] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![1, -12, 5, 5, 8]
 hmem := by decide

def Log10: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 3 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-15, -12, 5, 5, 8]
 hxeq :=  rfl
 m:= 3
 C := ![-18, -12, 5, 5, 8]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log10Mem
 k :=  8
 hpow := by decide
 heql := by decide

def Log11Mem : IdealMemCertificate O ℤ B I1
  ![![11, 0, 0, 0, 0], ![6, 1, 0, 0, 0], ![1, 0, 1, 0, 0], ![6, 0, 0, 1, 0], ![1, 0, 0, 0, 1]] ![26988, 99902, -36483, -33365, -61972] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-24889, 99902, -36483, -33365, -61972]
 hmem := by decide

def Log11: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 3 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![26991, 99902, -36483, -33365, -61972]
 hxeq :=  rfl
 m:= 3
 C := ![26988, 99902, -36483, -33365, -61972]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log11Mem
 k :=  8
 hpow := by decide
 heql := by decide

def Log12Mem : IdealMemCertificate O ℤ B I1
  ![![11, 0, 0, 0, 0], ![6, 1, 0, 0, 0], ![1, 0, 1, 0, 0], ![6, 0, 0, 1, 0], ![1, 0, 0, 0, 1]] ![656, 471, 553, 230, 264] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-397, 471, 553, 230, 264]
 hmem := by decide

def Log12: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![658, 471, 553, 230, 264]
 hxeq :=  rfl
 m:= 2
 C := ![656, 471, 553, 230, 264]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log12Mem
 k :=  1
 hpow := by decide
 heql := by decide

def Log20Mem : IdealMemCertificate O ℤ B I2
  ![![31, 0, 0, 0, 0], ![3, 1, 0, 0, 0], ![25, 0, 1, 0, 0], ![12, 0, 0, 1, 0], ![7, 0, 0, 0, 1]] ![-43, -12, 5, 5, 8] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![-8, -12, 5, 5, 8]
 hmem := by decide

def Log20: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-15, -12, 5, 5, 8]
 hxeq :=  rfl
 m:= 28
 C := ![-43, -12, 5, 5, 8]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log20Mem
 k :=  16
 hpow := by decide
 heql := by decide

def Log21Mem : IdealMemCertificate O ℤ B I2
  ![![31, 0, 0, 0, 0], ![3, 1, 0, 0, 0], ![25, 0, 1, 0, 0], ![12, 0, 0, 1, 0], ![7, 0, 0, 0, 1]] ![26970, 99902, -36483, -33365, -61972] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![47533, 99902, -36483, -33365, -61972]
 hmem := by decide

def Log21: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 4 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![26991, 99902, -36483, -33365, -61972]
 hxeq :=  rfl
 m:= 21
 C := ![26970, 99902, -36483, -33365, -61972]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log21Mem
 k :=  29
 hpow := by decide
 heql := by decide

def Log22Mem : IdealMemCertificate O ℤ B I2
  ![![31, 0, 0, 0, 0], ![3, 1, 0, 0, 0], ![25, 0, 1, 0, 0], ![12, 0, 0, 1, 0], ![7, 0, 0, 0, 1]] ![657, 471, 553, 230, 264] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![-619, 471, 553, 230, 264]
 hmem := by decide

def Log22: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![658, 471, 553, 230, 264]
 hxeq :=  rfl
 m:= 1
 C := ![657, 471, 553, 230, 264]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log22Mem
 k :=  0
 hpow := by decide
 heql := by decide

def J : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![2, 0, 0, 0, 0], ![6, -2, 1, 0, 1]] i)))
def MulJ0 : IdealMulEqCertificate O ℤ TT (J) J
  ![![2, 0, 0, 0, 0], ![6, -2, 1, 0, 1]] ![![2, 0, 0, 0, 0], ![6, -2, 1, 0, 1]]
  ![![2, 0, 0, 0, 0], ![2, 1, 1, 0, 0]] where
 T := T
 heq := T_eq_TT
 hI1 := rfl
 hI2 := rfl
 M :=  ![![![4, 0, 0, 0, 0], ![12, -4, 2, 0, 2]], ![![12, -4, 2, 0, 2], ![20, -15, 4, 3, 8]]]
 hmul := by decide
 f :=  ![![![![-15933728, -28565530, 12085710, 10708530, 22581086], ![-1902234, 9998736, -297984, -247086, 0]], ![![0, 0, 0, 0, 0], ![-45985, 3307, 168, 1, 0]]], ![![![-284184, -509476, 215554, 190990, 402741], ![-33924, 178332, -5313, -4407, 0]], ![![0, 0, 0, 0, 0], ![-820, 59, 3, 0, 0]]]]
 g :=  ![![![![2, 0, 0, 0, 0], ![0, 0, 0, 0, 0]], ![![10, -21, 3, 0, 13], ![2, 12, -6, 0, 0]]], ![![![10, -21, 3, 0, 13], ![2, 12, -6, 0, 0]], ![![29, -69, 10, 0, 42], ![0, 41, -19, 0, 0]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ1 : IdealMulEqCertificate O ℤ TT (J*J) J
  ![![2, 0, 0, 0, 0], ![2, 1, 1, 0, 0]] ![![2, 0, 0, 0, 0], ![6, -2, 1, 0, 1]]
  ![![4, 0, 0, 0, 0], ![-2, -5, 0, 1, 2]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ0
 hI2 := rfl
 M :=  ![![![4, 0, 0, 0, 0], ![12, -4, 2, 0, 2]], ![![4, 2, 2, 0, 0], ![2, 1, -1, 0, 0]]]
 hmul := by decide
 f :=  ![![![![-201, -346, 144, 131, 274], ![-26, 120, -6, -3, 0]], ![![0, 0, 0, 0, 0], ![2, 2, 0, 0, 0]]], ![![![30, 45, -15, -21, -46], ![29, -6, 15, 0, 0]], ![![0, 0, 0, 0, 0], ![-6, -1, -5, 0, 0]]]]
 g :=  ![![![![-265583, 113140, 43933, 43587, -1383], ![1574, 88566, -304, 6, 0]], ![![-918260, 391181, 151900, 150703, -4781], ![5439, 306219, -1052, 21, 0]]], ![![![-529672, 225645, 87620, 86929, -2758], ![3140, 176634, -606, 12, 0]], ![![-4590, 1959, 759, 753, -25], ![30, 1531, -5, 0, 0]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ2 : IdealMulEqCertificate O ℤ TT (J*J*J) J
  ![![4, 0, 0, 0, 0], ![-2, -5, 0, 1, 2]] ![![2, 0, 0, 0, 0], ![6, -2, 1, 0, 1]]
  ![![4, 0, 0, 0, 0], ![2, 1, 1, 0, 0]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ1
 hI2 := rfl
 M :=  ![![![8, 0, 0, 0, 0], ![24, -8, 4, 0, 4]], ![![-4, -10, 0, 2, 4], ![-18, -19, 8, 7, 12]]]
 hmul := by decide
 f :=  ![![![![-88652566380, -158279211992, 64983548070, 59608114831, 124808952192], ![-12782237006, 56582156939, -2063884571, -612228477, 0]], ![![-251881686, -41057679, 1201026, 0, 0], ![-100611, 889, -36, 9, 0]]], ![![![-83500668541, -149081076362, 61207136250, 56144087443, 117555885564], ![-12039418334, 53293978122, -1943945304, -576649829, 0]], ![![-237243989, -38671680, 1131231, 0, 0], ![-94767, 838, -35, 9, 0]]]]
 g :=  ![![![![4, -13, 1, 0, 8], ![4, 16, -8, 0, 0]], ![![2, 3, -1, 0, -3], ![4, -8, 4, 0, 0]]], ![![![-20, 46, -10, 0, -33], ![4, -66, 34, 0, 0]], ![![-47, 114, -21, 0, -80], ![2, -159, 83, 0, 0]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ3 : IdealMulEqCertificate O ℤ TT (J*J*J*J) J
  ![![4, 0, 0, 0, 0], ![2, 1, 1, 0, 0]] ![![2, 0, 0, 0, 0], ![6, -2, 1, 0, 1]]
  ![![658, 471, 553, 230, 264]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ2
 hI2 := rfl
 M :=  ![![![8, 0, 0, 0, 0], ![24, -8, 4, 0, 4]], ![![4, 2, 2, 0, 0], ![2, 1, -1, 0, 0]]]
 hmul := by decide
 f :=  ![![![![-293568, -524900, 216686, 197471, 414092], ![-40394, 188419, -5719, -2121, 0]], ![![741, 879, -741, 0, 0], ![247, -224, -82, 0, 0]]]]
 g :=  ![![![![-156, 21, -95, 29, -13]], ![![229, -11, 126, -53, -18]]], ![![![102, 17, 37, -35, -53]], ![![-113, -35, -27, 47, 91]]]]
 hle1 := by decide
 hle2 := by decide

lemma J5 : J ^ 5 =  Ideal.span {alpha} := by
 simp only [pow_succ, pow_one, pow_zero, one_mul]
 simp [ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ3, alpha]
lemma isUnit_zeta1 : IsUnit zeta1 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![-1191, -846, -991, -411, -472])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide

lemma isUnit_zeta2 : IsUnit zeta2 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![-93249, -16708, -32775, 32563, 50708])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide


 instance hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible

noncomputable instance K_field : Field K := by
  unfold K
  infer_instance

instance K_numberField : NumberField K := by
  unfold K
  infer_instance

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  rw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, P_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by sorry
--------------------------------------------------------------------

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

def SturmRC : SturmBuilderOfList [[-96, 0, -30, 5, 0, 1], [0, -60, 15, 0, 5], [48, 0, 9, -1], [-36, -3, -7], [4, -9], [1]] [-96, 0, -30, 5, 0, 1] [0, -60, 15, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 5 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 1, 49, 81]
  f := [50, 60, 6, 3136]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [-45, -5], [-66, 7], [55, 63]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 + 5*X^3 - 30*X^2 - 96
  l := [-96, 0, -30, 5, 0, 1]
  hl := ofList_poly
  hlz := by decide
  hz := by decide
  hAdj := Adj_K
  heq := O_integral_closure
  P := [[-96, 0, -30, 5, 0, 1], [0, -60, 15, 0, 5], [48, 0, 9, -1], [-36, -3, -7], [4, -9], [1]]
  SB := SturmRC
  k := 1
  r := 3
  hr := by decide
  hreq := by decide

lemma ne_dvd_torsion5 : ¬5 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
 suffices ¬ 5 ∣ 2 from ?_
 · convert this
   rw [O_integral_closure, ← Fintype.card_eq_nat_card]
   convert (Subtype.val_inj.2
    (torsionOrder_eq_two_of_odd_finrank (by rw [K_finrank] ; decide)))
 · decide

def NPCJ : NonPrincipalCertificateNDvdT J where
 p := 5
 hp := by decide
 r := 2
 huc := by
  rw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2]
 hu := fun i =>
  match i with
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
 q := ![11, 11, 31]
 hqP := by
  intro i
  match i with
  | 0 => exact hq11
  | 1 => exact hq11
  | 2 => exact hq31
 I := ![I0, I1, I2]
 hcard := fun i =>
  match i with
  | 0 => N0
  | 1 => N1
  | 2 => N2
 ζ := ![2, 2, 3]
 hr := fun i =>
  match i with
  | 0 => ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 a := alpha
 n := 5
 hpdvd := by decide
 hJ := J5
 hpndvdt := ne_dvd_torsion5
 M := ![![2, 4, 3], ![3, 3, 1], ![1, 4, 0]]
 hM1 := by
  intro j i hj
  fin_cases i <;> interval_cases j
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log00] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log01] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log10] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log11] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log20] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log21] ; decide
 hM2 := by
  intro i
  match i with
  | 0 => exact Log02
  | 1 => exact Log12
  | 2 => exact Log22
 hDl := by decide
 Minv := ![![2, 4, 0], ![2, 4, 4], ![3, 2, 3]]
 hInv := by decide
 N := ![![2, 4], ![3, 3]]
 hNiv := by decide

theorem J_not_principal : ¬ ∃ b, J = Ideal.span {b} :=
  not_principal_of_NonPrincipalCertificateNDvdT NPCJ
