import IdealArithmetic.IdealArithmetic
import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem
import IdealArithmetic.PrincipalityCertificate
import Mathlib.RingTheory.AdjoinRoot

--------------------------------------------
-- EXAMPLE
--------------------------------------------

/- Number field `K(α)` with with α root of polynomial `X^5 + 15*X^3 - 70*X^2 + 60*X - 24`.
Class number `5`, generated by class of ideal `J = (2, -5/24*a^4 - 1/12*a^3 - 71/24*a^2 + 13*a - 9/2)`. We have `J ^ 5 = (α)`. -/

/- Ring of integers with basis `[1, a, a^2, 1/2*a^3 - 1/2*a, 1/24*a^4 - 1/12*a^3 - 5/24*a^2 - 1/2*a - 1/2]` -/

open BigOperators Classical Matrix Polynomial

noncomputable def P : ℤ[X] := X^5 + 15*X^3 - 70*X^2 + 60*X - 24

def K := AdjoinRoot (map (algebraMap ℤ ℚ) P)

lemma P_irreducible : Irreducible P := sorry
lemma P_degree : P.natDegree = 5 := sorry
lemma P_monic : Monic P := sorry

--local notation "K" =>  AdjoinRoot (map (algebraMap ℤ ℚ) (X^5 + 15*X^3 - 70*X^2 + 60*X - 24 ))

noncomputable instance : CommRing K := by
  unfold K
  infer_instance

noncomputable instance : Algebra ℚ K := by
  unfold K
  infer_instance

noncomputable def Adj_K : IsAdjoinRoot K (map (algebraMap ℤ ℚ) (X^5 + 15*X^3 - 70*X^2 + 60*X - 24 )) := by
  unfold K
  exact AdjoinRoot.isAdjoinRoot (Polynomial.map (algebraMap ℤ ℚ) (X^5 + 15*X^3 - 70*X^2 + 60*X - 24))


lemma ofList_poly : ofList [-24, 60, -70, 15, 0, 1] = X^5 + 15*X^3 - 70*X^2 + 60*X - 24   := by
  simp ; ring


noncomputable def O : Subalgebra ℤ K := sorry

noncomputable def TT : TimesTable (Fin 5) ℤ O where
    basis := sorry
    table := ![![![1, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![0, 0, 0, 0, 1]], ![![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 1, 0, 2, 0], ![6, 7, 2, 2, 12], ![0, -5, 2, -2, -2]], ![![0, 0, 1, 0, 0], ![0, 1, 0, 2, 0], ![12, 14, 5, 4, 24], ![12, -38, 35, -16, 0], ![-12, -2, -13, 4, -20]], ![![0, 0, 0, 1, 0], ![6, 7, 2, 2, 12], ![12, -38, 35, -16, 0], ![-51, -36, -36, 18, -102], ![12, 54, -18, 12, 45]], ![![0, 0, 0, 0, 1], ![0, -5, 2, -2, -2], ![-12, -2, -13, 4, -20], ![12, 54, -18, 12, 45], ![6, -18, 18, -10, 1]]]
    basis_mul_basis := sorry

noncomputable def B := TT.basis

lemma B_one : TT.basis 0 = 1 := sorry

lemma B_one_repr : TT.basis.equivFun.symm ![1, 0, 0, 0, 0] = 1 := sorry

def T : Fin 5 → Fin 5 → List ℤ :=
    ![![[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]], ![[0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 1, 0, 2, 0], [6, 7, 2, 2, 12], [0, -5, 2, -2, -2]], ![[0, 0, 1, 0, 0], [0, 1, 0, 2, 0], [12, 14, 5, 4, 24], [12, -38, 35, -16, 0], [-12, -2, -13, 4, -20]], ![[0, 0, 0, 1, 0], [6, 7, 2, 2, 12], [12, -38, 35, -16, 0], [-51, -36, -36, 18, -102], [12, 54, -18, 12, 45]], ![[0, 0, 0, 0, 1], [0, -5, 2, -2, -2], [-12, -2, -13, 4, -20], [12, 54, -18, 12, 45], [6, -18, 18, -10, 1]]]

lemma T_eq_TT : ∀ (i j : Fin 5), T i j = List.ofFn (TT.table i j) := by
  simp ; decide



instance : IsDomain O := by
  haveI hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) :=
  {out := (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible}
  letI hola : Field K := by
    unfold K
    exact AdjoinRoot.instField
  haveI : IsDomain K := by infer_instance
  refine Subalgebra.isDomain O

noncomputable section

instance hq41 : Fact $ Nat.Prime 41 := by decide
instance hq61 : Fact $ Nat.Prime 61 := by decide
instance hq71 : Fact $ Nat.Prime 71 := by decide

def R41 : IsOrderOf (6 : ZMod 41) 40 where
 m := 2
 P := ![2, 5]
 e := ![3, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def R61 : IsOrderOf (2 : ZMod 61) 60 where
 m := 3
 P := ![2, 3, 5]
 e := ![2, 1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def R71 : IsOrderOf (7 : ZMod 71) 70 where
 m := 3
 P := ![2, 5, 7]
 e := ![1, 1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def I0 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![41, 0, 0, 0, 0], ![-5, 1, 0, 0, 0]] i)))
def I1 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![61, 0, 0, 0, 0], ![-14, 1, 0, 0, 0]] i)))
def I2 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![71, 0, 0, 0, 0], ![34, 1, 0, 0, 0]] i)))

def A0: IdealEqSpanCertificate O ℤ TT I0
 ![![41, 0, 0, 0, 0], ![-5, 1, 0, 0, 0]]
 ![![41, 0, 0, 0, 0], ![36, 1, 0, 0, 0], ![16, 0, 1, 0, 0], ![22, 0, 0, 1, 0], ![37, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![41, 0, 0, 0, 0], ![0, 41, 0, 0, 0], ![0, 0, 41, 0, 0], ![0, 0, 0, 41, 0], ![0, 0, 0, 0, 41]], ![![-5, 1, 0, 0, 0], ![0, -5, 1, 0, 0], ![0, 1, -5, 2, 0], ![6, 7, 2, -3, 12], ![0, -5, 2, -2, -7]]]
  hmulB := by decide
  f := ![![![1006668, -953290, 3876099, -1552752, 3024], ![8242271, 180195, 31815918, -10332, 0]], ![![898806, -851150, 3460796, -1386383, 2700], ![7359132, 160884, 28407014, -9225, 0]], ![![395480, -374504, 1522746, -610007, 1188], ![3238062, 70808, 12499055, -4059, 0]], ![![539282, -510690, 2076483, -831832, 1620], ![4415466, 96537, 17044254, -5535, 0]], ![![908456, -860286, 3497943, -1401264, 2729], ![7438143, 162615, 28711926, -9324, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-36, 41, 0, 0, 0], ![-16, 0, 41, 0, 0], ![-22, 0, 0, 41, 0], ![-37, 0, 0, 0, 41]], ![![-1, 1, 0, 0, 0], ![4, -5, 1, 0, 0], ![0, 1, -5, 2, 0], ![-16, 7, 2, -3, 12], ![11, -5, 2, -2, -7]]]
  hle1 := by decide
  hle2 := by decide

lemma N0 : Nat.card (O ⧸ I0) = 41 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A0)

def A1: IdealEqSpanCertificate O ℤ TT I1
 ![![61, 0, 0, 0, 0], ![-14, 1, 0, 0, 0]]
 ![![61, 0, 0, 0, 0], ![47, 1, 0, 0, 0], ![48, 0, 1, 0, 0], ![38, 0, 0, 1, 0], ![59, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![61, 0, 0, 0, 0], ![0, 61, 0, 0, 0], ![0, 0, 61, 0, 0], ![0, 0, 0, 61, 0], ![0, 0, 0, 0, 61]], ![![-14, 1, 0, 0, 0], ![0, -14, 1, 0, 0], ![0, 1, -14, 2, 0], ![6, 7, 2, -12, 12], ![0, -5, 2, -2, -16]]]
  hmulB := by decide
  f := ![![![68001043, -16453633, 180148421, -25765180, 17172], ![296252844, 5520317, 785314244, -87291, 0]], ![![52604629, -12728296, 139360223, -19931572, 13284], ![229176940, 4270427, 607507784, -67527, 0]], ![![53887600, -13038730, 142759058, -20417680, 13608], ![234766322, 4374555, 622324196, -69174, 0]], ![![42340284, -10244717, 112167888, -16042471, 10692], ![184459370, 3437174, 488969260, -54351, 0]], ![![65771485, -15914177, 174241916, -24920420, 16609], ![286539568, 5339286, 759566236, -84429, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-47, 61, 0, 0, 0], ![-48, 0, 61, 0, 0], ![-38, 0, 0, 61, 0], ![-59, 0, 0, 0, 61]], ![![-1, 1, 0, 0, 0], ![10, -14, 1, 0, 0], ![9, 1, -14, 2, 0], ![-11, 7, 2, -12, 12], ![19, -5, 2, -2, -16]]]
  hle1 := by decide
  hle2 := by decide

lemma N1 : Nat.card (O ⧸ I1) = 61 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A1)

def A2: IdealEqSpanCertificate O ℤ TT I2
 ![![71, 0, 0, 0, 0], ![34, 1, 0, 0, 0]]
 ![![71, 0, 0, 0, 0], ![34, 1, 0, 0, 0], ![51, 0, 1, 0, 0], ![39, 0, 0, 1, 0], ![9, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![71, 0, 0, 0, 0], ![0, 71, 0, 0, 0], ![0, 0, 71, 0, 0], ![0, 0, 0, 71, 0], ![0, 0, 0, 0, 71]], ![![34, 1, 0, 0, 0], ![0, 34, 1, 0, 0], ![0, 1, 34, 2, 0], ![6, 7, 2, 36, 12], ![0, -5, 2, -2, 32]]]
  hmulB := by decide
  f := ![![![108669917, 10619598, 398550101, 23533944, 27540], ![-226899599, 9016787, -832522002, -162945, 0]], ![![53269552, 5205664, 195367644, 11536244, 13500], ![-111225262, 4420034, -408098912, -79875, 0]], ![![78838905, 7704411, 289144061, 17073638, 19980], ![-164613321, 6541586, -603986279, -118215, 0]], ![![59661899, 5830336, 218811824, 12920597, 15120], ![-124572295, 4950458, -457070913, -89460, 0]], ![![13775035, 1346134, 50520435, 2983176, 3491], ![-28761869, 1142997, -105530958, -20655, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-34, 71, 0, 0, 0], ![-51, 0, 71, 0, 0], ![-39, 0, 0, 71, 0], ![-9, 0, 0, 0, 71]], ![![0, 1, 0, 0, 0], ![-17, 34, 1, 0, 0], ![-26, 1, 34, 2, 0], ![-26, 7, 2, 36, 12], ![-2, -5, 2, -2, 32]]]
  hle1 := by decide
  hle2 := by decide

lemma N2 : Nat.card (O ⧸ I2) = 71 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A2)

def zeta1 := TT.basis.equivFun.symm ![1640, 830, 1218, 991, 2364]

def zeta2 := TT.basis.equivFun.symm ![133, -209, 93, 18, 98]

def alpha := TT.basis.equivFun.symm ![-2422, 2032, -692, -138, -851]

def Log00Mem : IdealMemCertificate O ℤ B I0
  ![![41, 0, 0, 0, 0], ![36, 1, 0, 0, 0], ![16, 0, 1, 0, 0], ![22, 0, 0, 1, 0], ![37, 0, 0, 0, 1]] ![1608, 830, 1218, 991, 2364] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-3830, 830, 1218, 991, 2364]
 hmem := by decide

def Log00: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R41) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![1640, 830, 1218, 991, 2364]
 hxeq :=  rfl
 m:= 32
 C := ![1608, 830, 1218, 991, 2364]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log00Mem
 k :=  10
 hpow := by decide
 heql := by decide

def Log01Mem : IdealMemCertificate O ℤ B I0
  ![![41, 0, 0, 0, 0], ![36, 1, 0, 0, 0], ![16, 0, 1, 0, 0], ![22, 0, 0, 1, 0], ![37, 0, 0, 0, 1]] ![118, -209, 93, 18, 98] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![52, -209, 93, 18, 98]
 hmem := by decide

def Log01: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R41) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![133, -209, 93, 18, 98]
 hxeq :=  rfl
 m:= 15
 C := ![118, -209, 93, 18, 98]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log01Mem
 k :=  37
 hpow := by decide
 heql := by decide

def Log02Mem : IdealMemCertificate O ℤ B I0
  ![![41, 0, 0, 0, 0], ![36, 1, 0, 0, 0], ![16, 0, 1, 0, 0], ![22, 0, 0, 1, 0], ![37, 0, 0, 0, 1]] ![-2455, 2032, -692, -138, -851] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-732, 2032, -692, -138, -851]
 hmem := by decide

def Log02: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R41) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 3 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-2422, 2032, -692, -138, -851]
 hxeq :=  rfl
 m:= 33
 C := ![-2455, 2032, -692, -138, -851]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log02Mem
 k :=  18
 hpow := by decide
 heql := by decide

def Log10Mem : IdealMemCertificate O ℤ B I1
  ![![61, 0, 0, 0, 0], ![47, 1, 0, 0, 0], ![48, 0, 1, 0, 0], ![38, 0, 0, 1, 0], ![59, 0, 0, 0, 1]] ![1633, 830, 1218, 991, 2364] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-4475, 830, 1218, 991, 2364]
 hmem := by decide

def Log10: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 4 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![1640, 830, 1218, 991, 2364]
 hxeq :=  rfl
 m:= 7
 C := ![1633, 830, 1218, 991, 2364]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log10Mem
 k :=  49
 hpow := by decide
 heql := by decide

def Log11Mem : IdealMemCertificate O ℤ B I1
  ![![61, 0, 0, 0, 0], ![47, 1, 0, 0, 0], ![48, 0, 1, 0, 0], ![38, 0, 0, 1, 0], ![59, 0, 0, 0, 1]] ![131, -209, 93, 18, 98] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-16, -209, 93, 18, 98]
 hmem := by decide

def Log11: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![133, -209, 93, 18, 98]
 hxeq :=  rfl
 m:= 2
 C := ![131, -209, 93, 18, 98]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log11Mem
 k :=  1
 hpow := by decide
 heql := by decide

def Log12Mem : IdealMemCertificate O ℤ B I1
  ![![61, 0, 0, 0, 0], ![47, 1, 0, 0, 0], ![48, 0, 1, 0, 0], ![38, 0, 0, 1, 0], ![59, 0, 0, 0, 1]] ![-2437, 2032, -692, -138, -851] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-152, 2032, -692, -138, -851]
 hmem := by decide

def Log12: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 3 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-2422, 2032, -692, -138, -851]
 hxeq :=  rfl
 m:= 15
 C := ![-2437, 2032, -692, -138, -851]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log12Mem
 k :=  28
 hpow := by decide
 heql := by decide

def Log20Mem : IdealMemCertificate O ℤ B I2
  ![![71, 0, 0, 0, 0], ![34, 1, 0, 0, 0], ![51, 0, 1, 0, 0], ![39, 0, 0, 1, 0], ![9, 0, 0, 0, 1]] ![1589, 830, 1218, 991, 2364] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![-2094, 830, 1218, 991, 2364]
 hmem := by decide

def Log20: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R71) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![1640, 830, 1218, 991, 2364]
 hxeq :=  rfl
 m:= 51
 C := ![1589, 830, 1218, 991, 2364]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log20Mem
 k :=  5
 hpow := by decide
 heql := by decide

def Log21Mem : IdealMemCertificate O ℤ B I2
  ![![71, 0, 0, 0, 0], ![34, 1, 0, 0, 0], ![51, 0, 1, 0, 0], ![39, 0, 0, 1, 0], ![9, 0, 0, 0, 1]] ![73, -209, 93, 18, 98] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![12, -209, 93, 18, 98]
 hmem := by decide

def Log21: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R71) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![133, -209, 93, 18, 98]
 hxeq :=  rfl
 m:= 60
 C := ![73, -209, 93, 18, 98]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log21Mem
 k :=  66
 hpow := by decide
 heql := by decide

def Log22Mem : IdealMemCertificate O ℤ B I2
  ![![71, 0, 0, 0, 0], ![34, 1, 0, 0, 0], ![51, 0, 1, 0, 0], ![39, 0, 0, 1, 0], ![9, 0, 0, 0, 1]] ![-2462, 2032, -692, -138, -851] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![-327, 2032, -692, -138, -851]
 hmem := by decide

def Log22: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R71) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-2422, 2032, -692, -138, -851]
 hxeq :=  rfl
 m:= 40
 C := ![-2462, 2032, -692, -138, -851]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log22Mem
 k :=  46
 hpow := by decide
 heql := by decide

def J : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![2, 0, 0, 0, 0], ![-7, 10, -4, -1, -5]] i)))
def MulJ0 : IdealMulEqCertificate O ℤ TT (J) J
  ![![2, 0, 0, 0, 0], ![-7, 10, -4, -1, -5]] ![![2, 0, 0, 0, 0], ![-7, 10, -4, -1, -5]]
  ![![2, 0, 0, 0, 0], ![8, -3, 1, 0, 1]] where
 T := T
 heq := T_eq_TT
 hI1 := rfl
 hI2 := rfl
 M :=  ![![![4, 0, 0, 0, 0], ![-14, 20, -8, -2, -10]], ![![-14, 20, -8, -2, -10], ![-44, 34, -10, -2, -13]]]
 hmul := by decide
 f :=  ![![![![-276347, 53335, 146660, 113148, 245026], ![271450, -384705, 6921, 0, 22353]], ![![0, 0, 0, 0, 0], ![-471, -24, 0, 0, -1]]], ![![![-76049, 14703, 40389, 31146, 67482], ![74704, -105879, 1884, 0, 6147]], ![![0, 0, 0, 0, 0], ![-129, -7, -1, 0, 0]]]]
 g :=  ![![![![2, 0, 0, 0, 0], ![0, 0, 0, 0, 0]], ![![257, 642, -120, 29, -210], ![-66, -298, -30, 0, 0]]], ![![![257, 642, -120, 29, -210], ![-66, -298, -30, 0, 0]], ![![406, 1002, -185, 46, -326], ![-107, -467, -47, 0, 0]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ1 : IdealMulEqCertificate O ℤ TT (J*J) J
  ![![2, 0, 0, 0, 0], ![8, -3, 1, 0, 1]] ![![2, 0, 0, 0, 0], ![-7, 10, -4, -1, -5]]
  ![![4, 0, 0, 0, 0], ![-8, 17, -7, -2, -9]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ0
 hI2 := rfl
 M :=  ![![![4, 0, 0, 0, 0], ![-14, 20, -8, -2, -10]], ![![16, -6, 2, 0, 2], ![-32, 55, -23, -6, -27]]]
 hmul := by decide
 f :=  ![![![![84, -26, -40, -31, -68], ![-74, 108, 0, 0, -6]], ![![0, 0, 0, 0, 0], ![0, 0, 0, 0, 0]]], ![![![-297242, -917142, -688327, 57242, -1096717], ![544466, -492324, 770961, 0, 181359]], ![![0, 0, 0, 0, 0], ![-22067, -570, -26, 0, 0]]]]
 g :=  ![![![![10594, -2109, -3489, -4287, -6009], ![-8262, 9036, 324, 0, -6]], ![![-38477, 7601, 12703, 15589, 21866], ![30045, -32844, -1176, 0, 21]]], ![![![42760, -8466, -14110, -17319, -24292], ![-33378, 36492, 1308, 0, -24]], ![![-88372, 17448, 29178, 35806, 50223], ![69011, -75438, -2700, 0, 48]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ2 : IdealMulEqCertificate O ℤ TT (J*J*J) J
  ![![4, 0, 0, 0, 0], ![-8, 17, -7, -2, -9]] ![![2, 0, 0, 0, 0], ![-7, 10, -4, -1, -5]]
  ![![4, 0, 0, 0, 0], ![6, -3, 1, 0, 1]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ1
 hI2 := rfl
 M :=  ![![![8, 0, 0, 0, 0], ![-28, 40, -16, -4, -20]], ![![-16, 34, -14, -4, -18], ![-106, 103, -35, -8, -43]]]
 hmul := by decide
 f :=  ![![![![-487245378490, 172647485030, 301322591210, 231479952308, 551426110021], ![471645816264, -708645438578, -42430434620, 0, 5196264423]], ![![1708083822, 34488555, 1426904, 0, 0], ![-19479, -272, 138, 0, -1]]], ![![![-501577859723, 177725966930, 310186093200, 238289010369, 567646488333], ![485519431304, -729490474566, -43678539646, 0, 5349114232]], ![![1758327663, 35503047, 1468877, 0, 0], ![-20052, -280, 142, 0, -1]]]]
 g :=  ![![![![410, 708, -428, -32, -1052], ![-272, -2112, 64, 0, 0]], ![![-6799, -11555, 6997, 521, 17217], ![4528, 34620, -1044, 0, 0]]], ![![![-5395, -9167, 5551, 413, 13659], ![3594, 27468, -828, 0, 0]], ![![-19096, -32456, 19655, 1465, 48363], ![12713, 97236, -2934, 0, 0]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ3 : IdealMulEqCertificate O ℤ TT (J*J*J*J) J
  ![![4, 0, 0, 0, 0], ![6, -3, 1, 0, 1]] ![![2, 0, 0, 0, 0], ![-7, 10, -4, -1, -5]]
  ![![-2422, 2032, -692, -138, -851]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ2
 hI2 := rfl
 M :=  ![![![8, 0, 0, 0, 0], ![-28, 40, -16, -4, -20]], ![![12, -6, 2, 0, 2], ![-18, 35, -15, -4, -17]]]
 hmul := by decide
 f :=  ![![![![-1141417615015, 259961403860, 590347818801, 523934688194, 1087931728530], ![1132276368893, -1657976109531, 10327424198, 0, 42208944764]], ![![2552945847, -374618619, -11031777, 0, 0], ![-139065, -519, -3243, 0, 0]]]]
 g :=  ![![![![-11, -18, -2, 3, -28]], ![![13, -54, 46, -24, -5]]], ![![![30, 26, 18, -4, 60]], ![![-9, 103, -71, 47, 31]]]]
 hle1 := by decide
 hle2 := by decide

lemma J5 : J ^ 5 =  Ideal.span {alpha} := by
 simp only [pow_succ, pow_one, pow_zero, one_mul]
 simp [ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ3, alpha]
lemma isUnit_zeta1 : IsUnit zeta1 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![-5424574, 3240098, -817290, -84269, -1056426])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide

lemma isUnit_zeta2 : IsUnit zeta2 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![190721077, -40049621, 221123523, 75455658, 207020810])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide



instance hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible

noncomputable instance K_field : Field K := by
  unfold K
  infer_instance

instance K_numberField : NumberField K := by
  unfold K
  infer_instance

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  rw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, P_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by sorry

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K


def SturmRC : SturmBuilderOfList [[-24, 60, -70, 15, 0, 1], [60, -140, 45, 0, 5], [4, -8, 7, -1], [-4, 8, -5], [2, -9], [1]] [-24, 60, -70, 15, 0, 1] [60, -140, 45, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 5 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 1, 25, 81]
  f := [150, 50, 4, 200]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [-35, -5], [-27, 5], [-62, 45]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 + 15*X^3 - 70*X^2 + 60*X - 24
  l := [-24, 60, -70, 15, 0, 1]
  hl := ofList_poly
  hlz := by decide
  hz := by decide
  hAdj := Adj_K
  heq := O_integral_closure
  P := [[-24, 60, -70, 15, 0, 1], [60, -140, 45, 0, 5], [4, -8, 7, -1], [-4, 8, -5], [2, -9], [1]]
  SB := SturmRC
  k := 1
  r := 3
  hr := by decide
  hreq := by decide

lemma ne_dvd_torsion5 : ¬5 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
 suffices ¬ 5 ∣ 2 from ?_
 · convert this
   rw [O_integral_closure, ← Fintype.card_eq_nat_card]
   convert (Subtype.val_inj.2
    (torsionOrder_eq_two_of_odd_finrank (by rw [K_finrank] ; decide)))
 · decide

def NPCJ : NonPrincipalCertificateNDvdT J where
 p := 5
 hp := by decide
 r := 2
 huc := by
  rw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2]
 hu := fun i =>
  match i with
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
 q := ![41, 61, 71]
 hqP := by
  intro i
  match i with
  | 0 => exact hq41
  | 1 => exact hq61
  | 2 => exact hq71
 I := ![I0, I1, I2]
 hcard := fun i =>
  match i with
  | 0 => N0
  | 1 => N1
  | 2 => N2
 ζ := ![6, 2, 7]
 hr := fun i =>
  match i with
  | 0 => ((orderOf_of_IsOrderOf R41) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf R71) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 a := alpha
 n := 5
 hpdvd := by decide
 hJ := J5
 hpndvdt := ne_dvd_torsion5
 M := ![![0, 2, 3], ![4, 1, 3], ![0, 1, 1]]
 hM1 := by
  intro j i hj
  fin_cases i <;> interval_cases j
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log00] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log01] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log10] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log11] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log20] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log21] ; decide
 hM2 := by
  intro i
  match i with
  | 0 => exact Log02
  | 1 => exact Log12
  | 2 => exact Log22
 hDl := by decide
 Minv := ![![2, 4, 2], ![4, 0, 3], ![1, 0, 3]]
 hInv := by decide
 N := ![![3, 4], ![3, 0]]
 hNiv := by decide

theorem J_not_principal : ¬ ∃ b, J = Ideal.span {b} :=
  not_principal_of_NonPrincipalCertificateNDvdT NPCJ
