import IdealArithmetic.IdealArithmetic
import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem
import IdealArithmetic.PrincipalityCertificate
import Mathlib.RingTheory.AdjoinRoot

--------------------------------------------
-- EXAMPLE
--------------------------------------------

/- Number field `K(α)` with with α root of polynomial `X^5 + 10*X^3 - 40*X^2 - 15*X - 232`.
Class number `5`, generated by class of ideal `J = (2, 1/4*a^4 + 7/4*a^2 - 15/2*a - 5)`. We have `J ^ 5 = (α)`. -/

/- Ring of integers with basis `[1, a, a^2, 1/4*a^3 - 1/2*a^2 - 1/4*a, 1/4*a^4 - 1/4*a^2 - 1/2*a]` -/

open BigOperators Classical Matrix Polynomial

noncomputable def P : ℤ[X] := X^5 + 10*X^3 - 40*X^2 - 15*X - 232

def K := AdjoinRoot (map (algebraMap ℤ ℚ) P)

lemma P_irreducible : Irreducible P := sorry
lemma P_degree : P.natDegree = 5 := sorry
lemma P_monic : Monic P := sorry

--local notation "K" =>  AdjoinRoot (map (algebraMap ℤ ℚ) (X^5 + 10*X^3 - 40*X^2 - 15*X - 232 ))

noncomputable instance : CommRing K := by
  unfold K
  infer_instance

noncomputable instance : Algebra ℚ K := by
  unfold K
  infer_instance

noncomputable def Adj_K : IsAdjoinRoot K (map (algebraMap ℤ ℚ) (X^5 + 10*X^3 - 40*X^2 - 15*X - 232 )) := by
  unfold K
  exact AdjoinRoot.isAdjoinRoot (Polynomial.map (algebraMap ℤ ℚ) (X^5 + 10*X^3 - 40*X^2 - 15*X - 232))


lemma ofList_poly : ofList [-232, -15, -40, 10, 0, 1] = X^5 + 10*X^3 - 40*X^2 - 15*X - 232   := by
  simp ; ring


noncomputable def O : Subalgebra ℤ K := sorry

noncomputable def TT : TimesTable (Fin 5) ℤ O where
    basis := sorry
    table := ![![![1, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![0, 0, 0, 0, 1]], ![![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 1, 2, 4, 0], ![0, 0, -1, -2, 1], ![58, 1, 4, -11, 0]], ![![0, 0, 1, 0, 0], ![0, 1, 2, 4, 0], ![0, 2, 1, 0, 4], ![58, 0, 4, -11, -2], ![0, 62, 20, 38, -11]], ![![0, 0, 0, 1, 0], ![0, 0, -1, -2, 1], ![58, 0, 4, -11, -2], ![-58, 15, 1, 21, -2], ![-174, -29, -6, 15, 15]], ![![0, 0, 0, 0, 1], ![58, 1, 4, -11, 0], ![0, 62, 20, 38, -11], ![-174, -29, -6, 15, 15], ![522, -161, 12, -151, 34]]]
    basis_mul_basis := sorry

noncomputable def B := TT.basis

lemma B_one : TT.basis 0 = 1 := sorry

lemma B_one_repr : TT.basis.equivFun.symm ![1, 0, 0, 0, 0] = 1 := sorry

def T : Fin 5 → Fin 5 → List ℤ :=
    ![![[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]], ![[0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 1, 2, 4, 0], [0, 0, -1, -2, 1], [58, 1, 4, -11, 0]], ![[0, 0, 1, 0, 0], [0, 1, 2, 4, 0], [0, 2, 1, 0, 4], [58, 0, 4, -11, -2], [0, 62, 20, 38, -11]], ![[0, 0, 0, 1, 0], [0, 0, -1, -2, 1], [58, 0, 4, -11, -2], [-58, 15, 1, 21, -2], [-174, -29, -6, 15, 15]], ![[0, 0, 0, 0, 1], [58, 1, 4, -11, 0], [0, 62, 20, 38, -11], [-174, -29, -6, 15, 15], [522, -161, 12, -151, 34]]]

lemma T_eq_TT : ∀ (i j : Fin 5), T i j = List.ofFn (TT.table i j) := by
  simp ; decide



instance : IsDomain O := by
  haveI hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) :=
  {out := (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible}
  letI hola : Field K := by
    unfold K
    exact AdjoinRoot.instField
  haveI : IsDomain K := by infer_instance
  refine Subalgebra.isDomain O

noncomputable section

instance hq41 : Fact $ Nat.Prime 41 := by decide
instance hq61 : Fact $ Nat.Prime 61 := by decide
instance hq31 : Fact $ Nat.Prime 31 := by decide

def R41 : IsOrderOf (6 : ZMod 41) 40 where
 m := 2
 P := ![2, 5]
 e := ![3, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def R61 : IsOrderOf (2 : ZMod 61) 60 where
 m := 3
 P := ![2, 3, 5]
 e := ![2, 1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def R31 : IsOrderOf (3 : ZMod 31) 30 where
 m := 3
 P := ![2, 3, 5]
 e := ![1, 1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def I0 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![31, 0, 0, 0, 0], ![-3, 1, 0, 0, 0]] i)))
def I1 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![41, 0, 0, 0, 0], ![-12, 1, 0, 0, 0]] i)))
def I2 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![61, 0, 0, 0, 0], ![-6, 1, 0, 0, 0]] i)))

def A0: IdealEqSpanCertificate O ℤ TT I0
 ![![31, 0, 0, 0, 0], ![-3, 1, 0, 0, 0]]
 ![![31, 0, 0, 0, 0], ![28, 1, 0, 0, 0], ![22, 0, 1, 0, 0], ![14, 0, 0, 1, 0], ![30, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![31, 0, 0, 0, 0], ![0, 31, 0, 0, 0], ![0, 0, 31, 0, 0], ![0, 0, 0, 31, 0], ![0, 0, 0, 0, 31]], ![![-3, 1, 0, 0, 0], ![0, -3, 1, 0, 0], ![0, 1, -1, 4, 0], ![0, 0, -1, -5, 1], ![58, 1, 4, -11, -3]]]
  hmulB := by decide
  f := ![![![2050, -5788, 4867, -22072, 280], ![21173, 651, 160208, -8680, 0]], ![![1942, -5483, 4610, -20914, 266], ![20058, 620, 151776, -8246, 0]], ![![1528, -4320, 3633, -16486, 210], ![15782, 497, 119629, -6510, 0]], ![![926, -2604, 2190, -9935, 126], ![9564, 318, 72114, -3906, 0]], ![![1986, -5602, 4710, -21360, 271], ![20512, 630, 155040, -8400, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-28, 31, 0, 0, 0], ![-22, 0, 31, 0, 0], ![-14, 0, 0, 31, 0], ![-30, 0, 0, 0, 31]], ![![-1, 1, 0, 0, 0], ![2, -3, 1, 0, 0], ![-2, 1, -1, 4, 0], ![2, 0, -1, -5, 1], ![6, 1, 4, -11, -3]]]
  hle1 := by decide
  hle2 := by decide

lemma N0 : Nat.card (O ⧸ I0) = 31 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A0)

def A1: IdealEqSpanCertificate O ℤ TT I1
 ![![41, 0, 0, 0, 0], ![-12, 1, 0, 0, 0]]
 ![![41, 0, 0, 0, 0], ![29, 1, 0, 0, 0], ![20, 0, 1, 0, 0], ![12, 0, 0, 1, 0], ![24, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![41, 0, 0, 0, 0], ![0, 41, 0, 0, 0], ![0, 0, 41, 0, 0], ![0, 0, 0, 41, 0], ![0, 0, 0, 0, 41]], ![![-12, 1, 0, 0, 0], ![0, -12, 1, 0, 0], ![0, 1, -10, 4, 0], ![0, 0, -1, -14, 1], ![58, 1, 4, -11, -12]]]
  hmulB := by decide
  f := ![![![-66287, 20650, -175984, 77736, -504], ![-226484, -8692, -724470, 20664, 0]], ![![-46907, 14611, -124513, 55006, -357], ![-160268, -6150, -512582, 14637, 0]], ![![-33212, 10350, -88182, 38944, -252], ![-113476, -4345, -363014, 10332, 0]], ![![-19308, 6024, -51314, 22667, -147], ![-65970, -2519, -211242, 6027, 0]], ![![-38808, 12088, -103015, 45504, -295], ![-132596, -5089, -424080, 12096, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-29, 41, 0, 0, 0], ![-20, 0, 41, 0, 0], ![-12, 0, 0, 41, 0], ![-24, 0, 0, 0, 41]], ![![-1, 1, 0, 0, 0], ![8, -12, 1, 0, 0], ![3, 1, -10, 4, 0], ![4, 0, -1, -14, 1], ![9, 1, 4, -11, -12]]]
  hle1 := by decide
  hle2 := by decide

lemma N1 : Nat.card (O ⧸ I1) = 41 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A1)

def A2: IdealEqSpanCertificate O ℤ TT I2
 ![![61, 0, 0, 0, 0], ![-6, 1, 0, 0, 0]]
 ![![61, 0, 0, 0, 0], ![55, 1, 0, 0, 0], ![25, 0, 1, 0, 0], ![57, 0, 0, 1, 0], ![54, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![61, 0, 0, 0, 0], ![0, 61, 0, 0, 0], ![0, 0, 61, 0, 0], ![0, 0, 0, 61, 0], ![0, 0, 0, 0, 61]], ![![-6, 1, 0, 0, 0], ![0, -6, 1, 0, 0], ![0, 1, -4, 4, 0], ![0, 0, -1, -8, 1], ![58, 1, 4, -11, -6]]]
  hmulB := by decide
  f := ![![![31507, -36757, 127334, -133224, 645], ![320311, 5185, 1952976, -39345, 0]], ![![29365, -34270, 118742, -124240, 602], ![298535, 4880, 1821216, -36722, 0]], ![![14623, -17077, 59179, -61928, 301], ![148663, 2441, 907680, -18361, 0]], ![![29403, -34303, 118849, -124347, 602], ![298921, 4881, 1822848, -36722, 0]], ![![27894, -32534, 112721, -117936, 571], ![283580, 4645, 1728864, -34830, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-55, 61, 0, 0, 0], ![-25, 0, 61, 0, 0], ![-57, 0, 0, 61, 0], ![-54, 0, 0, 0, 61]], ![![-1, 1, 0, 0, 0], ![5, -6, 1, 0, 0], ![-3, 1, -4, 4, 0], ![7, 0, -1, -8, 1], ![14, 1, 4, -11, -6]]]
  hle1 := by decide
  hle2 := by decide

lemma N2 : Nat.card (O ⧸ I2) = 61 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A2)

def zeta1 := TT.basis.equivFun.symm ![-94349, -49754, -42647, -22399, -6349]

def zeta2 := TT.basis.equivFun.symm ![4436583, 499539, 81866, -425045, -249983]

def alpha := TT.basis.equivFun.symm ![-3, 30, -3, 4, -3]

def Log00Mem : IdealMemCertificate O ℤ B I0
  ![![31, 0, 0, 0, 0], ![28, 1, 0, 0, 0], ![22, 0, 1, 0, 0], ![14, 0, 0, 1, 0], ![30, 0, 0, 0, 1]] ![-94351, -49754, -42647, -22399, -6349] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![88421, -49754, -42647, -22399, -6349]
 hmem := by decide

def Log00: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 4 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-94349, -49754, -42647, -22399, -6349]
 hxeq :=  rfl
 m:= 2
 C := ![-94351, -49754, -42647, -22399, -6349]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log00Mem
 k :=  24
 hpow := by decide
 heql := by decide

def Log01Mem : IdealMemCertificate O ℤ B I0
  ![![31, 0, 0, 0, 0], ![28, 1, 0, 0, 0], ![22, 0, 1, 0, 0], ![14, 0, 0, 1, 0], ![30, 0, 0, 0, 1]] ![4436569, 499539, 81866, -425045, -249983] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![67695, 499539, 81866, -425045, -249983]
 hmem := by decide

def Log01: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![4436583, 499539, 81866, -425045, -249983]
 hxeq :=  rfl
 m:= 14
 C := ![4436569, 499539, 81866, -425045, -249983]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log01Mem
 k :=  22
 hpow := by decide
 heql := by decide

def Log02Mem : IdealMemCertificate O ℤ B I0
  ![![31, 0, 0, 0, 0], ![28, 1, 0, 0, 0], ![22, 0, 1, 0, 0], ![14, 0, 0, 1, 0], ![30, 0, 0, 0, 1]] ![-4, 30, -3, 4, -3] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-24, 30, -3, 4, -3]
 hmem := by decide

def Log02: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-3, 30, -3, 4, -3]
 hxeq :=  rfl
 m:= 1
 C := ![-4, 30, -3, 4, -3]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log02Mem
 k :=  0
 hpow := by decide
 heql := by decide

def Log10Mem : IdealMemCertificate O ℤ B I1
  ![![41, 0, 0, 0, 0], ![29, 1, 0, 0, 0], ![20, 0, 1, 0, 0], ![12, 0, 0, 1, 0], ![24, 0, 0, 0, 1]] ![-94364, -49754, -42647, -22399, -6349] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![63966, -49754, -42647, -22399, -6349]
 hmem := by decide

def Log10: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R41) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-94349, -49754, -42647, -22399, -6349]
 hxeq :=  rfl
 m:= 15
 C := ![-94364, -49754, -42647, -22399, -6349]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log10Mem
 k :=  37
 hpow := by decide
 heql := by decide

def Log11Mem : IdealMemCertificate O ℤ B I1
  ![![41, 0, 0, 0, 0], ![29, 1, 0, 0, 0], ![20, 0, 1, 0, 0], ![12, 0, 0, 1, 0], ![24, 0, 0, 0, 1]] ![4436576, 499539, 81866, -425045, -249983] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-14323, 499539, 81866, -425045, -249983]
 hmem := by decide

def Log11: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R41) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 4 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![4436583, 499539, 81866, -425045, -249983]
 hxeq :=  rfl
 m:= 7
 C := ![4436576, 499539, 81866, -425045, -249983]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log11Mem
 k :=  39
 hpow := by decide
 heql := by decide

def Log12Mem : IdealMemCertificate O ℤ B I1
  ![![41, 0, 0, 0, 0], ![29, 1, 0, 0, 0], ![20, 0, 1, 0, 0], ![12, 0, 0, 1, 0], ![24, 0, 0, 0, 1]] ![-34, 30, -3, 4, -3] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-20, 30, -3, 4, -3]
 hmem := by decide

def Log12: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R41) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 3 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-3, 30, -3, 4, -3]
 hxeq :=  rfl
 m:= 31
 C := ![-34, 30, -3, 4, -3]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log12Mem
 k :=  28
 hpow := by decide
 heql := by decide

def Log20Mem : IdealMemCertificate O ℤ B I2
  ![![61, 0, 0, 0, 0], ![55, 1, 0, 0, 0], ![25, 0, 1, 0, 0], ![57, 0, 0, 1, 0], ![54, 0, 0, 0, 1]] ![-94372, -49754, -42647, -22399, -6349] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![87342, -49754, -42647, -22399, -6349]
 hmem := by decide

def Log20: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-94349, -49754, -42647, -22399, -6349]
 hxeq :=  rfl
 m:= 23
 C := ![-94372, -49754, -42647, -22399, -6349]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log20Mem
 k :=  57
 hpow := by decide
 heql := by decide

def Log21Mem : IdealMemCertificate O ℤ B I2
  ![![61, 0, 0, 0, 0], ![55, 1, 0, 0, 0], ![25, 0, 1, 0, 0], ![57, 0, 0, 1, 0], ![54, 0, 0, 0, 1]] ![4436532, 499539, 81866, -425045, -249983] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![207244, 499539, 81866, -425045, -249983]
 hmem := by decide

def Log21: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 3 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![4436583, 499539, 81866, -425045, -249983]
 hxeq :=  rfl
 m:= 51
 C := ![4436532, 499539, 81866, -425045, -249983]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log21Mem
 k :=  53
 hpow := by decide
 heql := by decide

def Log22Mem : IdealMemCertificate O ℤ B I2
  ![![61, 0, 0, 0, 0], ![55, 1, 0, 0, 0], ![25, 0, 1, 0, 0], ![57, 0, 0, 1, 0], ![54, 0, 0, 0, 1]] ![-6, 30, -3, 4, -3] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![-27, 30, -3, 4, -3]
 hmem := by decide

def Log22: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-3, 30, -3, 4, -3]
 hxeq :=  rfl
 m:= 3
 C := ![-6, 30, -3, 4, -3]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log22Mem
 k :=  6
 hpow := by decide
 heql := by decide

def J : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![2, 0, 0, 0, 0], ![-5, -7, 2, 0, 1]] i)))
def MulJ0 : IdealMulEqCertificate O ℤ TT (J) J
  ![![2, 0, 0, 0, 0], ![-5, -7, 2, 0, 1]] ![![2, 0, 0, 0, 0], ![-5, -7, 2, 0, 1]]
  ![![2, 0, 0, 0, 0], ![-3, 1, 1, 1, 0]] where
 T := T
 heq := T_eq_TT
 hI1 := rfl
 hI2 := rfl
 M :=  ![![![4, 0, 0, 0, 0], ![-10, -14, 4, 0, 2]], ![![-10, -14, 4, 0, 2], ![-265, 123, 13, 43, -4]]]
 hmul := by decide
 f :=  ![![![![-1289195021830, 859282094960, -90282808812, 162007939555, -69869209239], ![90282808812, 52041183865, -16751419956, -198908013, 0]], ![![0, 0, 0, 0, 0], ![911588, -54317, -5417, 3, 0]]], ![![![3867091500868, -2577517311234, 270813861807, -485961794444, 209580878461], ![-270813861807, -156103627772, 50247846645, 596647878, 0]], ![![0, 0, 0, 0, 0], ![-2734413, 162931, 16249, -9, 0]]]]
 g :=  ![![![![52, 36, 22, 0, 0], ![-44, 8, -4, 0, 0]], ![![48, 30, 21, -3, 0], ![-42, 10, -4, 0, 0]]], ![![![48, 30, 21, -3, 0], ![-42, 10, -4, 0, 0]], ![![-4816, -3490, -2179, -30, 0], ![4379, -780, 388, 0, 0]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ1 : IdealMulEqCertificate O ℤ TT (J*J) J
  ![![2, 0, 0, 0, 0], ![-3, 1, 1, 1, 0]] ![![2, 0, 0, 0, 0], ![-5, -7, 2, 0, 1]]
  ![![4, 0, 0, 0, 0], ![-19, -6, 3, 2, 1]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ0
 hI2 := rfl
 M :=  ![![![4, 0, 0, 0, 0], ![-10, -14, 4, 0, 2]], ![![-6, 2, 2, 2, 0], ![15, 49, 7, 9, -2]]]
 hmul := by decide
 f :=  ![![![![173632846183, -115739993622, 12144401688, -21827315979, 9406668735], ![-12144401688, -7008076086, 2257960299, 26147385, 0]], ![![0, 0, 0, 0, 0], ![-342436, 2934, -4, 0, 0]]], ![![![-564398095530, 376215868244, -39475694470, 70950259931, -30576622090], ![39475694470, 22779934116, -7339558848, -84992757, 0]], ![![0, 0, 0, 0, 0], ![1113097, -9537, 13, 0, 0]]]]
 g :=  ![![![![89320589, -198598908, 62935183, 12002081, 29975582], ![-65678020, -27353462, -160878, 18, 0]], ![![-257249398, 571978567, -181257686, -34566831, -86331748], ![189157248, 78779859, 463341, -51, 0]]], ![![![-148866511, 330995726, -104891195, -20003322, -49958933], ![109462558, 45588764, 268128, -30, 0]], ![![294779566, -655424546, 207701399, 39609794, 98926695], ![-216753421, -90273062, -530940, 57, 0]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ2 : IdealMulEqCertificate O ℤ TT (J*J*J) J
  ![![4, 0, 0, 0, 0], ![-19, -6, 3, 2, 1]] ![![2, 0, 0, 0, 0], ![-5, -7, 2, 0, 1]]
  ![![4, 0, 0, 0, 0], ![-3, 1, 1, 1, 0]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ1
 hI2 := rfl
 M :=  ![![![8, 0, 0, 0, 0], ![-20, -28, 8, 0, 4]], ![![-38, -12, 6, 4, 2], ![-253, 220, 7, 54, -13]]]
 hmul := by decide
 f :=  ![![![![6380939616770453496874, -4260834158151537724206, 434008387585905606880, -808133401354934402792, 342825426447880987355], ![-434008387585905606880, -257032095746267717767, 84432935288098447190, 411977482333302382, 0]], ![![17061125335433742, -99140225797932, 539735265447, 0, 0], ![-3795488270, -5070651, -8871, -3, 0]]], ![![![-6378781450401720070022, 4259393055502845467832, -433861596930909534245, 807860073846291232824, -342709475765043938360], ![433861596930909534245, 256945162150584293767, -84404378314941499199, -411838142988245673, 0]], ![![-17055354908330043, 99106694513520, -539552715765, 0, 0], ![3794204557, 5068936, 8868, 3, 0]]]]
 g :=  ![![![![2, 0, 0, 0, 0], ![0, 0, 0, 0, 0]], ![![-353, -126, -58, 39, 0], ![232, -68, 36, 0, 0]]], ![![![-179, -64, -30, 19, 0], ![122, -34, 18, 0, 0]], ![![2039, 750, 337, -237, 0], ![-1315, 413, -213, 0, 0]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ3 : IdealMulEqCertificate O ℤ TT (J*J*J*J) J
  ![![4, 0, 0, 0, 0], ![-3, 1, 1, 1, 0]] ![![2, 0, 0, 0, 0], ![-5, -7, 2, 0, 1]]
  ![![-3, 30, -3, 4, -3]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ2
 hI2 := rfl
 M :=  ![![![8, 0, 0, 0, 0], ![-20, -28, 8, 0, 4]], ![![-6, 2, 2, 2, 0], ![15, 49, 7, 9, -2]]]
 hmul := by decide
 f :=  ![![![![-640166110980752, 427461170750013, -43551699756614, 81067826049107, -34395560627270], ![43551699756614, 25786595720630, -8470260736651, -43131236568, 0]], ![![20065663746, 2562194548, -115643835, 0, 0], ![2348481, -20097, 33, 0, 0]]]]
 g :=  ![![![![-22, 18, 1, 11, -3]], ![![84, -5, 2, -14, -1]]], ![![![118, 2, 2, -16, -4]], ![![-5, -36, 2, -13, 10]]]]
 hle1 := by decide
 hle2 := by decide

lemma J5 : J ^ 5 =  Ideal.span {alpha} := by
 simp only [pow_succ, pow_one, pow_zero, one_mul]
 simp [ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ3, alpha]
lemma isUnit_zeta1 : IsUnit zeta1 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![6540991, -13889124, 1249807, -2240413, 1315887])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide

lemma isUnit_zeta2 : IsUnit zeta2 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![-1728271045, -771064391, -677595114, -313890231, -96712103])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide



instance hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible

noncomputable instance K_field : Field K := by
  unfold K
  infer_instance

instance K_numberField : NumberField K := by
  unfold K
  infer_instance

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  rw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, P_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by sorry

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K


def SturmRC : SturmBuilderOfList [[-232, -15, -40, 10, 0, 1], [-15, -80, 30, 0, 5], [58, 3, 6, -1], [-23, -4, -3], [-2, -1], [1]] [-232, -15, -40, 10, 0, 1] [-15, -80, 30, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 5 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 1, 9, 1]
  f := [100, 75, 8, 27]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [-30, -5], [-22, 3], [-2, 3]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 + 10*X^3 - 40*X^2 - 15*X - 232
  l := [-232, -15, -40, 10, 0, 1]
  hl := ofList_poly
  hlz := by decide
  hz := by decide
  hAdj := Adj_K
  heq := O_integral_closure
  P := [[-232, -15, -40, 10, 0, 1], [-15, -80, 30, 0, 5], [58, 3, 6, -1], [-23, -4, -3], [-2, -1], [1]]
  SB := SturmRC
  k := 1
  r := 3
  hr := by decide
  hreq := by decide

lemma ne_dvd_torsion5 : ¬5 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
 suffices ¬ 5 ∣ 2 from ?_
 · convert this
   rw [O_integral_closure, ← Fintype.card_eq_nat_card,
   ←  NumberField.Units.torsionOrder_eq_two_of_odd_finrank (by rw [K_finrank] ; decide)]
   rfl
 · decide

def NPCJ : NonPrincipalCertificateNDvdT J where
 p := 5
 hp := by decide
 r := 2
 huc := by
  rw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2]
 hu := fun i =>
  match i with
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
 q := ![31, 41, 61]
 hqP := by
  intro i
  match i with
  | 0 => exact hq31
  | 1 => exact hq41
  | 2 => exact hq61
 I := ![I0, I1, I2]
 hcard := fun i =>
  match i with
  | 0 => N0
  | 1 => N1
  | 2 => N2
 ζ := ![3, 6, 2]
 hr := fun i =>
  match i with
  | 0 => ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf R41) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 a := alpha
 n := 5
 hpdvd := by decide
 hJ := J5
 hpndvdt := ne_dvd_torsion5
 M := ![![4, 2, 0], ![2, 4, 3], ![2, 3, 1]]
 hM1 := by
  intro j i hj
  fin_cases i <;> interval_cases j
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log00] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log01] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log10] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log11] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log20] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log21] ; decide
 hM2 := by
  intro i
  match i with
  | 0 => exact Log02
  | 1 => exact Log12
  | 2 => exact Log22
 hDl := by decide
 Minv := ![![0, 1, 2], ![3, 3, 1], ![1, 4, 4]]
 hInv := by decide
 N := ![![2, 4], ![4, 2]]
 hNiv := by decide

theorem J_not_principal : ¬ ∃ b, J = Ideal.span {b} :=
  not_principal_of_NonPrincipalCertificateNDvdT NPCJ
