import IdealArithmetic.IdealArithmetic
import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem
import IdealArithmetic.PrincipalityCertificate
import Mathlib.RingTheory.AdjoinRoot


open BigOperators Classical Matrix Polynomial

--------------------------------------------
-- EXAMPLE
--------------------------------------------

/- Number field `K(α)` with with α root of polynomial `X^5 - 20*X^3 - 50*X^2 - 45*X - 26`.
Class number `3`, generated by class of ideal `J = (2, a)`. We have `J ^ 3 = (α)`. -/

/- Ring of integers with basis `[1, a, a^2, 1/2*a^3 - 1/2*a, 1/4*a^4 - 1/4*a^3 - 1/4*a^2 - 1/4*a - 1/2]` -/

noncomputable def P : ℤ[X] := X^5 - 20*X^3 - 50*X^2 - 45*X - 26

def K := AdjoinRoot (map (algebraMap ℤ ℚ) P)

lemma P_irreducible : Irreducible P := sorry
lemma P_degree : P.natDegree = 5 := sorry
lemma P_monic : Monic P := sorry

--local notation "K" =>  AdjoinRoot (map (algebraMap ℤ ℚ) (X^5 - 20*X^3 - 50*X^2 - 45*X - 26 ))

noncomputable instance : CommRing K := by
  unfold K
  infer_instance

noncomputable instance : Algebra ℚ K := by
  unfold K
  infer_instance

noncomputable def Adj_K : IsAdjoinRoot K (map (algebraMap ℤ ℚ) (X^5 - 20*X^3 - 50*X^2 - 45*X - 26 )) := by
  unfold K
  exact AdjoinRoot.isAdjoinRoot (Polynomial.map (algebraMap ℤ ℚ) (X^5 - 20*X^3 - 50*X^2 - 45*X - 26))


lemma ofList_poly : ofList [-26, -45, -50, -20, 0, 1] = X^5 - 20*X^3 - 50*X^2 - 45*X - 26   := by
  simp ; ring


noncomputable def O : Subalgebra ℤ K := sorry

noncomputable def TT : TimesTable (Fin 5) ℤ O where
    basis := sorry
    table := ![![![1, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![0, 0, 0, 0, 1]], ![![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 1, 0, 2, 0], ![1, 1, 0, 1, 2], ![6, 15, 12, 9, -1]], ![![0, 0, 1, 0, 0], ![0, 1, 0, 2, 0], ![2, 2, 1, 2, 4], ![13, 32, 25, 19, 0], ![3, 12, 3, 24, 19]], ![![0, 0, 0, 1, 0], ![1, 1, 0, 1, 2], ![13, 32, 25, 19, 0], ![9, 28, 16, 34, 18], ![66, 150, 114, 96, 15]], ![![0, 0, 0, 0, 1], ![6, 15, 12, 9, -1], ![3, 12, 3, 24, 19], ![66, 150, 114, 96, 15], ![57, 168, 102, 177, 81]]]
    basis_mul_basis := sorry

noncomputable def B := TT.basis

lemma B_one : TT.basis 0 = 1 := sorry

lemma B_one_repr : TT.basis.equivFun.symm ![1, 0, 0, 0, 0] = 1 := sorry

def T : Fin 5 → Fin 5 → List ℤ :=
    ![![[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]], ![[0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 1, 0, 2, 0], [1, 1, 0, 1, 2], [6, 15, 12, 9, -1]], ![[0, 0, 1, 0, 0], [0, 1, 0, 2, 0], [2, 2, 1, 2, 4], [13, 32, 25, 19, 0], [3, 12, 3, 24, 19]], ![[0, 0, 0, 1, 0], [1, 1, 0, 1, 2], [13, 32, 25, 19, 0], [9, 28, 16, 34, 18], [66, 150, 114, 96, 15]], ![[0, 0, 0, 0, 1], [6, 15, 12, 9, -1], [3, 12, 3, 24, 19], [66, 150, 114, 96, 15], [57, 168, 102, 177, 81]]]

lemma T_eq_TT : ∀ (i j : Fin 5), T i j = List.ofFn (TT.table i j) := by
  simp ; decide



instance : IsDomain O := by
  haveI hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) :=
  {out := (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible}
  letI hola : Field K := by
    unfold K
    exact AdjoinRoot.instField
  haveI : IsDomain K := by infer_instance
  refine Subalgebra.isDomain O

noncomputable section

instance hq31 : Fact $ Nat.Prime 31 := by decide
instance hq13 : Fact $ Nat.Prime 13 := by decide
instance hq7 : Fact $ Nat.Prime 7 := by decide

def R31 : IsOrderOf (3 : ZMod 31) 30 where
 m := 3
 P := ![2, 3, 5]
 e := ![1, 1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def R13 : IsOrderOf (2 : ZMod 13) 12 where
 m := 2
 P := ![2, 3]
 e := ![2, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def R7 : IsOrderOf (3 : ZMod 7) 6 where
 m := 2
 P := ![2, 3]
 e := ![1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def I0 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![7, 0, 0, 0, 0], ![-1, 1, 0, 0, 0]] i)))
def I1 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![13, 0, 0, 0, 0], ![0, 1, 0, 0, 0]] i)))
def I2 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![31, 0, 0, 0, 0], ![-10, 1, 0, 0, 0]] i)))

def A0: IdealEqSpanCertificate O ℤ TT I0
 ![![7, 0, 0, 0, 0], ![-1, 1, 0, 0, 0]]
 ![![7, 0, 0, 0, 0], ![6, 1, 0, 0, 0], ![6, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![1, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![7, 0, 0, 0, 0], ![0, 7, 0, 0, 0], ![0, 0, 7, 0, 0], ![0, 0, 0, 7, 0], ![0, 0, 0, 0, 7]], ![![-1, 1, 0, 0, 0], ![0, -1, 1, 0, 0], ![0, 1, -1, 2, 0], ![1, 1, 0, 0, 2], ![6, 15, 12, 9, -2]]]
  hmulB := by decide
  f := ![![![56, -7, 0, 0, 48], ![217, 0, 0, -168, 0]], ![![56, -7, 0, 0, 48], ![218, 0, 0, -168, 0]], ![![46, -5, 0, 0, 40], ![176, 1, 0, -140, 0]], ![![0, 0, 0, -1, 0], ![0, 4, 4, 0, 0]], ![![8, -1, 0, 0, 7], ![31, 0, 0, -24, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-6, 7, 0, 0, 0], ![-6, 0, 7, 0, 0], ![0, 0, 0, 7, 0], ![-1, 0, 0, 0, 7]], ![![-1, 1, 0, 0, 0], ![0, -1, 1, 0, 0], ![0, 1, -1, 2, 0], ![-1, 1, 0, 0, 2], ![-22, 15, 12, 9, -2]]]
  hle1 := by decide
  hle2 := by decide

lemma N0 : Nat.card (O ⧸ I0) = 7 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A0)

def A1: IdealEqSpanCertificate O ℤ TT I1
 ![![13, 0, 0, 0, 0], ![0, 1, 0, 0, 0]]
 ![![13, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![7, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![13, 0, 0, 0, 0], ![0, 13, 0, 0, 0], ![0, 0, 13, 0, 0], ![0, 0, 0, 13, 0], ![0, 0, 0, 0, 13]], ![![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 1, 0, 2, 0], ![1, 1, 0, 1, 2], ![6, 15, 12, 9, -1]]]
  hmulB := by decide
  f := ![![![0, 5, 0, 13, -2], ![13, 0, -91, 13, 0]], ![![0, 0, 0, 0, 0], ![1, 0, 0, 0, 0]], ![![0, 0, 0, 0, 0], ![0, 1, 0, 0, 0]], ![![0, -1, 0, -1, 0], ![6, 0, 7, 0, 0]], ![![0, 3, 0, 7, -1], ![3, 0, -49, 7, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![0, 13, 0, 0, 0], ![0, 0, 13, 0, 0], ![0, 0, 0, 13, 0], ![-7, 0, 0, 0, 13]], ![![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 1, 0, 2, 0], ![-1, 1, 0, 1, 2], ![1, 15, 12, 9, -1]]]
  hle1 := by decide
  hle2 := by decide

lemma N1 : Nat.card (O ⧸ I1) = 13 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A1)

def A2: IdealEqSpanCertificate O ℤ TT I2
 ![![31, 0, 0, 0, 0], ![-10, 1, 0, 0, 0]]
 ![![31, 0, 0, 0, 0], ![21, 1, 0, 0, 0], ![24, 0, 1, 0, 0], ![1, 0, 0, 1, 0], ![10, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![31, 0, 0, 0, 0], ![0, 31, 0, 0, 0], ![0, 0, 31, 0, 0], ![0, 0, 0, 31, 0], ![0, 0, 0, 0, 31]], ![![-10, 1, 0, 0, 0], ![0, -10, 1, 0, 0], ![0, 1, -10, 2, 0], ![1, 1, 0, -9, 2], ![6, 15, 12, 9, -11]]]
  hmulB := by decide
  f := ![![![-24453, 5666, -39290, 7998, -28], ![-75764, -2170, -122016, 434, 0]], ![![-24983, 5783, -40128, 8166, -28], ![-77406, -2232, -124620, 434, 0]], ![![-24830, 5754, -39889, 8118, -28], ![-76932, -2200, -123876, 434, 0]], ![![71, -14, 85, -17, 0], ![220, 5, 264, 0, 0]], ![![-7890, 1836, -12675, 2580, -9], ![-24446, -675, -39360, 140, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-21, 31, 0, 0, 0], ![-24, 0, 31, 0, 0], ![-1, 0, 0, 31, 0], ![-10, 0, 0, 0, 31]], ![![-1, 1, 0, 0, 0], ![6, -10, 1, 0, 0], ![7, 1, -10, 2, 0], ![-1, 1, 0, -9, 2], ![-16, 15, 12, 9, -11]]]
  hle1 := by decide
  hle2 := by decide

lemma N2 : Nat.card (O ⧸ I2) = 31 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A2)

def zeta1 := TT.basis.equivFun.symm ![5, 22, 16, 12, -8]

def zeta2 := TT.basis.equivFun.symm ![15916, -121319, -63617, -104665, 61214]

def alpha := TT.basis.equivFun.symm ![-2, -1, 0, 0, 0]

def Log00Mem : IdealMemCertificate O ℤ B I0
  ![![7, 0, 0, 0, 0], ![6, 1, 0, 0, 0], ![6, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![1, 0, 0, 0, 1]] ![3, 22, 16, 12, -8] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-31, 22, 16, 12, -8]
 hmem := by decide

def Log00: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R7) ▸ IsPrimitiveRoot.orderOf _) 3 zeta1 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![5, 22, 16, 12, -8]
 hxeq :=  rfl
 m:= 2
 C := ![3, 22, 16, 12, -8]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log00Mem
 k :=  2
 hpow := by decide
 heql := by decide

def Log01Mem : IdealMemCertificate O ℤ B I0
  ![![7, 0, 0, 0, 0], ![6, 1, 0, 0, 0], ![6, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![1, 0, 0, 0, 1]] ![15913, -121319, -63617, -104665, 61214] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![152045, -121319, -63617, -104665, 61214]
 hmem := by decide

def Log01: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R7) ▸ IsPrimitiveRoot.orderOf _) 3 zeta2 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![15916, -121319, -63617, -104665, 61214]
 hxeq :=  rfl
 m:= 3
 C := ![15913, -121319, -63617, -104665, 61214]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log01Mem
 k :=  1
 hpow := by decide
 heql := by decide

def Log02Mem : IdealMemCertificate O ℤ B I0
  ![![7, 0, 0, 0, 0], ![6, 1, 0, 0, 0], ![6, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![1, 0, 0, 0, 1]] ![-6, -1, 0, 0, 0] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![0, -1, 0, 0, 0]
 hmem := by decide

def Log02: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R7) ▸ IsPrimitiveRoot.orderOf _) 3 alpha 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-2, -1, 0, 0, 0]
 hxeq :=  rfl
 m:= 4
 C := ![-6, -1, 0, 0, 0]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log02Mem
 k :=  4
 hpow := by decide
 heql := by decide

def Log10Mem : IdealMemCertificate O ℤ B I1
  ![![13, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![7, 0, 0, 0, 1]] ![-4, 22, 16, 12, -8] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![4, 22, 16, 12, -8]
 hmem := by decide

def Log10: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R13) ▸ IsPrimitiveRoot.orderOf _) 3 zeta1 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![5, 22, 16, 12, -8]
 hxeq :=  rfl
 m:= 9
 C := ![-4, 22, 16, 12, -8]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log10Mem
 k :=  8
 hpow := by decide
 heql := by decide

def Log11Mem : IdealMemCertificate O ℤ B I1
  ![![13, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![7, 0, 0, 0, 1]] ![15904, -121319, -63617, -104665, 61214] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-31738, -121319, -63617, -104665, 61214]
 hmem := by decide

def Log11: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R13) ▸ IsPrimitiveRoot.orderOf _) 3 zeta2 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![15916, -121319, -63617, -104665, 61214]
 hxeq :=  rfl
 m:= 12
 C := ![15904, -121319, -63617, -104665, 61214]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log11Mem
 k :=  6
 hpow := by decide
 heql := by decide

def Log12Mem : IdealMemCertificate O ℤ B I1
  ![![13, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![7, 0, 0, 0, 1]] ![-13, -1, 0, 0, 0] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-1, -1, 0, 0, 0]
 hmem := by decide

def Log12: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R13) ▸ IsPrimitiveRoot.orderOf _) 3 alpha 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-2, -1, 0, 0, 0]
 hxeq :=  rfl
 m:= 11
 C := ![-13, -1, 0, 0, 0]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log12Mem
 k :=  7
 hpow := by decide
 heql := by decide

def Log20Mem : IdealMemCertificate O ℤ B I2
  ![![31, 0, 0, 0, 0], ![21, 1, 0, 0, 0], ![24, 0, 1, 0, 0], ![1, 0, 0, 1, 0], ![10, 0, 0, 0, 1]] ![3, 22, 16, 12, -8] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![-25, 22, 16, 12, -8]
 hmem := by decide

def Log20: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 3 zeta1 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![5, 22, 16, 12, -8]
 hxeq :=  rfl
 m:= 2
 C := ![3, 22, 16, 12, -8]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log20Mem
 k :=  24
 hpow := by decide
 heql := by decide

def Log21Mem : IdealMemCertificate O ℤ B I2
  ![![31, 0, 0, 0, 0], ![21, 1, 0, 0, 0], ![24, 0, 1, 0, 0], ![1, 0, 0, 1, 0], ![10, 0, 0, 0, 1]] ![15886, -121319, -63617, -104665, 61214] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![115578, -121319, -63617, -104665, 61214]
 hmem := by decide

def Log21: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 3 zeta2 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![15916, -121319, -63617, -104665, 61214]
 hxeq :=  rfl
 m:= 30
 C := ![15886, -121319, -63617, -104665, 61214]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log21Mem
 k :=  15
 hpow := by decide
 heql := by decide

def Log22Mem : IdealMemCertificate O ℤ B I2
  ![![31, 0, 0, 0, 0], ![21, 1, 0, 0, 0], ![24, 0, 1, 0, 0], ![1, 0, 0, 1, 0], ![10, 0, 0, 0, 1]] ![-21, -1, 0, 0, 0] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![0, -1, 0, 0, 0]
 hmem := by decide

def Log22: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 3 alpha 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-2, -1, 0, 0, 0]
 hxeq :=  rfl
 m:= 19
 C := ![-21, -1, 0, 0, 0]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log22Mem
 k :=  4
 hpow := by decide
 heql := by decide

def J : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![2, 0, 0, 0, 0], ![0, 1, 0, 0, 0]] i)))
def MulJ0 : IdealMulEqCertificate O ℤ TT (J) J
  ![![2, 0, 0, 0, 0], ![0, 1, 0, 0, 0]] ![![2, 0, 0, 0, 0], ![0, 1, 0, 0, 0]]
  ![![4, 0, 0, 0, 0], ![2, 1, 0, 0, 0]] where
 T := T
 heq := T_eq_TT
 hI1 := rfl
 hI2 := rfl
 M :=  ![![![4, 0, 0, 0, 0], ![0, 2, 0, 0, 0]], ![![0, 2, 0, 0, 0], ![0, 0, 1, 0, 0]]]
 hmul := by decide
 f :=  ![![![![0, 5142, 3398, 1180, -4565], ![-3856, 1700, 0, 4192, -708]], ![![0, 0, 0, 0, 0], ![-212, -304, 0, 8, 4]]], ![![![0, 2548, 1684, 585, -2263], ![-1909, 844, 0, 2078, -351]], ![![0, 0, 0, 0, 0], ![-106, -151, 0, 4, 2]]]]
 g :=  ![![![![-2, 7, 0, -28, -13], ![4, -16, 32, 28, -4]], ![![-2, 13, 0, -28, -11], ![4, -28, 38, 24, -4]]], ![![![-2, 13, 0, -28, -11], ![4, -28, 38, 24, -4]], ![![1, 0, 0, 0, 0], ![-2, 1, 0, 0, 0]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ1 : IdealMulEqCertificate O ℤ TT (J*J) J
  ![![4, 0, 0, 0, 0], ![2, 1, 0, 0, 0]] ![![2, 0, 0, 0, 0], ![0, 1, 0, 0, 0]]
  ![![-2, -1, 0, 0, 0]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ0
 hI2 := rfl
 M :=  ![![![8, 0, 0, 0, 0], ![0, 4, 0, 0, 0]], ![![4, 2, 0, 0, 0], ![0, 2, 1, 0, 0]]]
 hmul := by decide
 f :=  ![![![![0, 2775962, 1827907, 598422, -2425143], ![-2081971, 913954, 0, 2242257, -380814]], ![![42627, -33228, 0, -16390, 2769], ![-1316, 1035, 0, -28, -2]]]]
 g :=  ![![![![7, 18, 15, 2, -4]], ![![-11, -18, -15, -2, 4]]], ![![![-2, 0, 0, 0, 0]], ![![0, -1, 0, 0, 0]]]]
 hle1 := by decide
 hle2 := by decide

lemma J3 : J ^ 3 =  Ideal.span {alpha} := by
 simp only [pow_succ, pow_one, pow_zero, one_mul]
 simp [ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ1, alpha]
lemma isUnit_zeta1 : IsUnit zeta1 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![1437, 818, 4, -92, 8])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide

lemma isUnit_zeta2 : IsUnit zeta2 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![125956, 310429, 219097, 245985, 75296])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide



instance hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible

noncomputable instance K_field : Field K := by
  unfold K
  infer_instance

instance K_numberField : NumberField K := by
  unfold K
  infer_instance

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  rw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, P_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by sorry

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K


def SturmRC : SturmBuilderOfList [[-26, -45, -50, -20, 0, 1], [-45, -100, -60, 0, 5], [13, 18, 15, 4], [-17, 34, 13], [-5, -3], [1]] [-26, -45, -50, -20, 0, 1] [-45, -100, -60, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 5 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 16, 169, 9]
  f := [50, 15, 640, 338]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [-75, 20], [59, 52], [-37, -39]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 - 20*X^3 - 50*X^2 - 45*X - 26
  l := [-26, -45, -50, -20, 0, 1]
  hl := ofList_poly
  hlz := by decide
  hz := by decide
  hAdj := Adj_K
  heq := O_integral_closure
  P := [[-26, -45, -50, -20, 0, 1], [-45, -100, -60, 0, 5], [13, 18, 15, 4], [-17, 34, 13], [-5, -3], [1]]
  SB := SturmRC
  k := 1
  r := 3
  hr := by decide
  hreq := by decide

lemma ne_dvd_torsion3 : ¬3 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
 suffices ¬ 3 ∣ 2 from ?_
 · convert this
   rw [O_integral_closure, ← Fintype.card_eq_nat_card]
   convert (Subtype.val_inj.2
    (torsionOrder_eq_two_of_odd_finrank (by rw [K_finrank] ; decide)))
 · decide

def NPCJ : NonPrincipalCertificateNDvdT J where
 p := 3
 hp := by decide
 r := 2
 huc := by
  rw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2]
 hu := fun i =>
  match i with
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
 q := ![7, 13, 31]
 hqP := by
  intro i
  match i with
  | 0 => exact hq7
  | 1 => exact hq13
  | 2 => exact hq31
 I := ![I0, I1, I2]
 hcard := fun i =>
  match i with
  | 0 => N0
  | 1 => N1
  | 2 => N2
 ζ := ![3, 2, 3]
 hr := fun i =>
  match i with
  | 0 => ((orderOf_of_IsOrderOf R7) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf R13) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 a := alpha
 n := 3
 hpdvd := by decide
 hJ := J3
 hpndvdt := ne_dvd_torsion3
 M := ![![2, 1, 1], ![2, 0, 1], ![0, 0, 1]]
 hM1 := by
  intro j i hj
  fin_cases i <;> interval_cases j
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log00] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log01] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log10] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log11] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log20] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log21] ; decide
 hM2 := by
  intro i
  match i with
  | 0 => exact Log02
  | 1 => exact Log12
  | 2 => exact Log22
 hDl := by decide
 Minv := ![![0, 2, 1], ![1, 2, 0], ![0, 0, 1]]
 hInv := by decide
 N := ![![0, 2], ![1, 2]]
 hNiv := by decide

theorem J_not_principal : ¬ ∃ b, J = Ideal.span {b} :=
  not_principal_of_NonPrincipalCertificateNDvdT NPCJ
