import IdealArithmetic.IdealArithmetic
import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem
import IdealArithmetic.PrincipalityCertificate
import Mathlib.RingTheory.AdjoinRoot

--------------------------------------------
-- EXAMPLE
--------------------------------------------

/- Number field `K(α)` with with α root of polynomial `X^5 - 90*X^3 - 240*X^2 + 2160*X + 10368`.
Class number `5`, generated by class of ideal `J = (2, 1/72*a^4 + 1/12*a^3 - 3/4*a^2 - 35/6*a - 5)`. We have `J ^ 5 = (α)`. -/

/- Ring of integers with basis `[1, a, 1/2*a^2, 1/12*a^3 - 1/2*a, 1/144*a^4 - 1/8*a^2 + 1/3*a]` -/

open BigOperators Classical Matrix Polynomial

noncomputable def P : ℤ[X] := X^5 - 90*X^3 - 240*X^2 + 2160*X + 10368

def K := AdjoinRoot (map (algebraMap ℤ ℚ) P)

lemma P_irreducible : Irreducible P := sorry
lemma P_degree : P.natDegree = 5 := sorry
lemma P_monic : Monic P := sorry

--local notation "K" =>  AdjoinRoot (map (algebraMap ℤ ℚ) (X^5 - 90*X^3 - 240*X^2 + 2160*X + 10368 ))

noncomputable instance : CommRing K := by
  unfold K
  infer_instance

noncomputable instance : Algebra ℚ K := by
  unfold K
  infer_instance

noncomputable def Adj_K : IsAdjoinRoot K (map (algebraMap ℤ ℚ) (X^5 - 90*X^3 - 240*X^2 + 2160*X + 10368 )) := by
  unfold K
  exact AdjoinRoot.isAdjoinRoot (Polynomial.map (algebraMap ℤ ℚ) (X^5 - 90*X^3 - 240*X^2 + 2160*X + 10368))


lemma ofList_poly : ofList [10368, 2160, -240, -90, 0, 1] = X^5 - 90*X^3 - 240*X^2 + 2160*X + 10368   := by
  simp ; ring


noncomputable def O : Subalgebra ℤ K := sorry

noncomputable def TT : TimesTable (Fin 5) ℤ O where
    basis := sorry
    table := ![![![1, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![0, 0, 0, 0, 1]], ![![0, 1, 0, 0, 0], ![0, 0, 2, 0, 0], ![0, 3, 0, 6, 0], ![0, -4, 2, 0, 12], ![-72, -12, 4, 6, 0]], ![![0, 0, 1, 0, 0], ![0, 3, 0, 6, 0], ![0, -12, 9, 0, 36], ![-432, -69, 20, 42, 0], ![0, -42, -6, 12, 36]], ![![0, 0, 0, 1, 0], ![0, -4, 2, 0, 12], ![-432, -69, 20, 42, 0], ![0, -88, -10, 20, 78], ![-396, -77, 12, 27, 24]], ![![0, 0, 0, 0, 1], ![-72, -12, 4, 6, 0], ![0, -42, -6, 12, 36], ![-396, -77, 12, 27, 24], ![-168, -60, 2, 18, 21]]]
    basis_mul_basis := sorry

noncomputable def B := TT.basis

lemma B_one : TT.basis 0 = 1 := sorry

lemma B_one_repr : TT.basis.equivFun.symm ![1, 0, 0, 0, 0] = 1 := sorry

def T : Fin 5 → Fin 5 → List ℤ :=
    ![![[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]], ![[0, 1, 0, 0, 0], [0, 0, 2, 0, 0], [0, 3, 0, 6, 0], [0, -4, 2, 0, 12], [-72, -12, 4, 6, 0]], ![[0, 0, 1, 0, 0], [0, 3, 0, 6, 0], [0, -12, 9, 0, 36], [-432, -69, 20, 42, 0], [0, -42, -6, 12, 36]], ![[0, 0, 0, 1, 0], [0, -4, 2, 0, 12], [-432, -69, 20, 42, 0], [0, -88, -10, 20, 78], [-396, -77, 12, 27, 24]], ![[0, 0, 0, 0, 1], [-72, -12, 4, 6, 0], [0, -42, -6, 12, 36], [-396, -77, 12, 27, 24], [-168, -60, 2, 18, 21]]]

lemma T_eq_TT : ∀ (i j : Fin 5), T i j = List.ofFn (TT.table i j) := by
  simp ; decide



instance : IsDomain O := by
  haveI hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) :=
  {out := (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible}
  letI hola : Field K := by
    unfold K
    exact AdjoinRoot.instField
  haveI : IsDomain K := by infer_instance
  refine Subalgebra.isDomain O

noncomputable section

instance hq41 : Fact $ Nat.Prime 41 := by decide
instance hq11 : Fact $ Nat.Prime 11 := by decide
instance hq31 : Fact $ Nat.Prime 31 := by decide

def R41 : IsOrderOf (6 : ZMod 41) 40 where
 m := 2
 P := ![2, 5]
 e := ![3, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def R11 : IsOrderOf (2 : ZMod 11) 10 where
 m := 2
 P := ![2, 5]
 e := ![1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def R31 : IsOrderOf (3 : ZMod 31) 30 where
 m := 3
 P := ![2, 3, 5]
 e := ![1, 1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def I0 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![11, 0, 0, 0, 0], ![-1, 1, 0, 0, 0]] i)))
def I1 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![31, 0, 0, 0, 0], ![7, 1, 0, 0, 0]] i)))
def I2 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![41, 0, 0, 0, 0], ![4, 1, 0, 0, 0]] i)))
def I3 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![41, 0, 0, 0, 0], ![-19, 1, 0, 0, 0]] i)))

def A0: IdealEqSpanCertificate O ℤ TT I0
 ![![11, 0, 0, 0, 0], ![-1, 1, 0, 0, 0]]
 ![![11, 0, 0, 0, 0], ![10, 1, 0, 0, 0], ![5, 0, 1, 0, 0], ![5, 0, 0, 1, 0], ![2, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![11, 0, 0, 0, 0], ![0, 11, 0, 0, 0], ![0, 0, 11, 0, 0], ![0, 0, 0, 11, 0], ![0, 0, 0, 0, 11]], ![![-1, 1, 0, 0, 0], ![0, -1, 2, 0, 0], ![0, 3, -1, 6, 0], ![0, -4, 2, -1, 12], ![-72, -12, 4, 6, -1]]]
  hmulB := by decide
  f := ![![![4, 73416, -22881, 148302, -864], ![33, -10824, -271755, 792, 0]], ![![2, 73418, -22881, 148302, -864], ![12, -10824, -271755, 792, 0]], ![![2, 40760, -12703, 82336, -480], ![17, -6011, -150876, 440, 0]], ![![2, 32632, -10171, 65917, -384], ![17, -4806, -120789, 352, 0]], ![![2, 13347, -4160, 26964, -157], ![20, -1969, -49410, 144, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-10, 11, 0, 0, 0], ![-5, 0, 11, 0, 0], ![-5, 0, 0, 11, 0], ![-2, 0, 0, 0, 11]], ![![-1, 1, 0, 0, 0], ![0, -1, 2, 0, 0], ![-5, 3, -1, 6, 0], ![1, -4, 2, -1, 12], ![0, -12, 4, 6, -1]]]
  hle1 := by decide
  hle2 := by decide

lemma N0 : Nat.card (O ⧸ I0) = 11 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A0)

def A1: IdealEqSpanCertificate O ℤ TT I1
 ![![31, 0, 0, 0, 0], ![7, 1, 0, 0, 0]]
 ![![31, 0, 0, 0, 0], ![7, 1, 0, 0, 0], ![22, 0, 1, 0, 0], ![7, 0, 0, 1, 0], ![23, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![31, 0, 0, 0, 0], ![0, 31, 0, 0, 0], ![0, 0, 31, 0, 0], ![0, 0, 0, 31, 0], ![0, 0, 0, 0, 31]], ![![7, 1, 0, 0, 0], ![0, 7, 2, 0, 0], ![0, 3, 7, 6, 0], ![0, -4, 2, 7, 12], ![-72, -12, 4, 6, 7]]]
  hmulB := by decide
  f := ![![![400058, 485550, 1075594, 930744, -864], ![-1771681, 166129, -4811448, 2232, 0]], ![![133196, 161663, 358128, 309900, -288], ![-589867, 55335, -1602018, 744, 0]], ![![311022, 377497, 836238, 723622, -672], ![-1377380, 129162, -3740739, 1736, 0]], ![![88900, 107906, 239038, 206847, -192], ![-393699, 36923, -1069288, 496, 0]], ![![296824, 360243, 798020, 690552, -641], ![-1314503, 123278, -3569784, 1656, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-7, 31, 0, 0, 0], ![-22, 0, 31, 0, 0], ![-7, 0, 0, 31, 0], ![-23, 0, 0, 0, 31]], ![![0, 1, 0, 0, 0], ![-3, 7, 2, 0, 0], ![-7, 3, 7, 6, 0], ![-11, -4, 2, 7, 12], ![-9, -12, 4, 6, 7]]]
  hle1 := by decide
  hle2 := by decide

lemma N1 : Nat.card (O ⧸ I1) = 31 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A1)

def A2: IdealEqSpanCertificate O ℤ TT I2
 ![![41, 0, 0, 0, 0], ![4, 1, 0, 0, 0]]
 ![![41, 0, 0, 0, 0], ![4, 1, 0, 0, 0], ![33, 0, 1, 0, 0], ![17, 0, 0, 1, 0], ![38, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![41, 0, 0, 0, 0], ![0, 41, 0, 0, 0], ![0, 0, 41, 0, 0], ![0, 0, 0, 41, 0], ![0, 0, 0, 0, 41]], ![![4, 1, 0, 0, 0], ![0, 4, 2, 0, 0], ![0, 3, 4, 6, 0], ![0, -4, 2, 4, 12], ![-72, -12, 4, 6, 4]]]
  hmulB := by decide
  f := ![![![3037301, 5918212, 6941008, 10472302, -9744], ![-31132325, 841894, -71582925, 33292, 0]], ![![314220, 612266, 718082, 1083414, -1008], ![-3220754, 87125, -7405625, 3444, 0]], ![![2513621, 4897819, 5744269, 8666712, -8064], ![-25764607, 696734, -59240900, 27552, 0]], ![![1256813, 2448912, 2872140, 4333367, -4032], ![-12882329, 348404, -29620525, 13776, 0]], ![![2815062, 5485170, 6433128, 9706036, -9031], ![-28854376, 780320, -66345150, 30856, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-4, 41, 0, 0, 0], ![-33, 0, 41, 0, 0], ![-17, 0, 0, 41, 0], ![-38, 0, 0, 0, 41]], ![![0, 1, 0, 0, 0], ![-2, 4, 2, 0, 0], ![-6, 3, 4, 6, 0], ![-14, -4, 2, 4, 12], ![-10, -12, 4, 6, 4]]]
  hle1 := by decide
  hle2 := by decide

lemma N2 : Nat.card (O ⧸ I2) = 41 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A2)

def A3: IdealEqSpanCertificate O ℤ TT I3
 ![![41, 0, 0, 0, 0], ![-19, 1, 0, 0, 0]]
 ![![41, 0, 0, 0, 0], ![22, 1, 0, 0, 0], ![4, 0, 1, 0, 0], ![29, 0, 0, 1, 0], ![15, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![41, 0, 0, 0, 0], ![0, 41, 0, 0, 0], ![0, 0, 41, 0, 0], ![0, 0, 0, 41, 0], ![0, 0, 0, 0, 41]], ![![-19, 1, 0, 0, 0], ![0, -19, 2, 0, 0], ![0, 3, -19, 6, 0], ![0, -4, 2, -19, 12], ![-72, -12, 4, 6, -19]]]
  hmulB := by decide
  f := ![![![-6960440, 1440481, -9575856, 3048186, -6120], ![-15019899, -964894, -20763056, 20910, 0]], ![![-4094138, 847299, -5632484, 1792932, -3600], ![-8834720, -567522, -12212752, 12300, 0]], ![![-818734, 169453, -1126377, 358548, -720], ![-1766742, -113467, -2442288, 2460, 0]], ![![-4913270, 1016820, -6759442, 2151665, -4320], ![-10602321, -681087, -14656304, 14760, 0]], ![![-2546508, 527006, -3503362, 1115190, -2239], ![-5495097, -353009, -7596240, 7650, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-22, 41, 0, 0, 0], ![-4, 0, 41, 0, 0], ![-29, 0, 0, 41, 0], ![-15, 0, 0, 0, 41]], ![![-1, 1, 0, 0, 0], ![10, -19, 2, 0, 0], ![-4, 3, -19, 6, 0], ![11, -4, 2, -19, 12], ![7, -12, 4, 6, -19]]]
  hle1 := by decide
  hle2 := by decide

lemma N3 : Nat.card (O ⧸ I3) = 41 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A3)

def zeta1 := TT.basis.equivFun.symm ![113, -54, 0, 22, -22]

def zeta2 := TT.basis.equivFun.symm ![28009, 10036, 920, -1530, -2672]

def zeta3 := TT.basis.equivFun.symm ![-383105, -37964, 30148, 17252, -40006]

def alpha := TT.basis.equivFun.symm ![267863, 87239, 721, -21807, -31202]

def Log00Mem : IdealMemCertificate O ℤ B I0
  ![![11, 0, 0, 0, 0], ![10, 1, 0, 0, 0], ![5, 0, 1, 0, 0], ![5, 0, 0, 1, 0], ![2, 0, 0, 0, 1]] ![109, -54, 0, 22, -22] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![53, -54, 0, 22, -22]
 hmem := by decide

def Log00: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![113, -54, 0, 22, -22]
 hxeq :=  rfl
 m:= 4
 C := ![109, -54, 0, 22, -22]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log00Mem
 k :=  2
 hpow := by decide
 heql := by decide

def Log01Mem : IdealMemCertificate O ℤ B I0
  ![![11, 0, 0, 0, 0], ![10, 1, 0, 0, 0], ![5, 0, 1, 0, 0], ![5, 0, 0, 1, 0], ![2, 0, 0, 0, 1]] ![28001, 10036, 920, -1530, -2672] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-5815, 10036, 920, -1530, -2672]
 hmem := by decide

def Log01: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 3 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![28009, 10036, 920, -1530, -2672]
 hxeq :=  rfl
 m:= 8
 C := ![28001, 10036, 920, -1530, -2672]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log01Mem
 k :=  3
 hpow := by decide
 heql := by decide

def Log02Mem : IdealMemCertificate O ℤ B I0
  ![![11, 0, 0, 0, 0], ![10, 1, 0, 0, 0], ![5, 0, 1, 0, 0], ![5, 0, 0, 1, 0], ![2, 0, 0, 0, 1]] ![-383109, -37964, 30148, 17252, -40006] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-14587, -37964, 30148, 17252, -40006]
 hmem := by decide

def Log02: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _) 5 zeta3 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-383105, -37964, 30148, 17252, -40006]
 hxeq :=  rfl
 m:= 4
 C := ![-383109, -37964, 30148, 17252, -40006]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log02Mem
 k :=  2
 hpow := by decide
 heql := by decide

def Log03Mem : IdealMemCertificate O ℤ B I0
  ![![11, 0, 0, 0, 0], ![10, 1, 0, 0, 0], ![5, 0, 1, 0, 0], ![5, 0, 0, 1, 0], ![2, 0, 0, 0, 1]] ![267856, 87239, 721, -21807, -31202] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-39700, 87239, 721, -21807, -31202]
 hmem := by decide

def Log03: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![267863, 87239, 721, -21807, -31202]
 hxeq :=  rfl
 m:= 7
 C := ![267856, 87239, 721, -21807, -31202]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log03Mem
 k :=  7
 hpow := by decide
 heql := by decide

def Log10Mem : IdealMemCertificate O ℤ B I1
  ![![31, 0, 0, 0, 0], ![7, 1, 0, 0, 0], ![22, 0, 1, 0, 0], ![7, 0, 0, 1, 0], ![23, 0, 0, 0, 1]] ![107, -54, 0, 22, -22] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![27, -54, 0, 22, -22]
 hmem := by decide

def Log10: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![113, -54, 0, 22, -22]
 hxeq :=  rfl
 m:= 6
 C := ![107, -54, 0, 22, -22]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log10Mem
 k :=  25
 hpow := by decide
 heql := by decide

def Log11Mem : IdealMemCertificate O ℤ B I1
  ![![31, 0, 0, 0, 0], ![7, 1, 0, 0, 0], ![22, 0, 1, 0, 0], ![7, 0, 0, 1, 0], ![23, 0, 0, 0, 1]] ![27998, 10036, 920, -1530, -2672] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![312, 10036, 920, -1530, -2672]
 hmem := by decide

def Log11: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 3 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![28009, 10036, 920, -1530, -2672]
 hxeq :=  rfl
 m:= 11
 C := ![27998, 10036, 920, -1530, -2672]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log11Mem
 k :=  23
 hpow := by decide
 heql := by decide

def Log12Mem : IdealMemCertificate O ℤ B I1
  ![![31, 0, 0, 0, 0], ![7, 1, 0, 0, 0], ![22, 0, 1, 0, 0], ![7, 0, 0, 1, 0], ![23, 0, 0, 0, 1]] ![-383111, -37964, 30148, 17252, -40006] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![605, -37964, 30148, 17252, -40006]
 hmem := by decide

def Log12: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 zeta3 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-383105, -37964, 30148, 17252, -40006]
 hxeq :=  rfl
 m:= 6
 C := ![-383111, -37964, 30148, 17252, -40006]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log12Mem
 k :=  25
 hpow := by decide
 heql := by decide

def Log13Mem : IdealMemCertificate O ℤ B I1
  ![![31, 0, 0, 0, 0], ![7, 1, 0, 0, 0], ![22, 0, 1, 0, 0], ![7, 0, 0, 1, 0], ![23, 0, 0, 0, 1]] ![267833, 87239, 721, -21807, -31202] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![16503, 87239, 721, -21807, -31202]
 hmem := by decide

def Log13: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![267863, 87239, 721, -21807, -31202]
 hxeq :=  rfl
 m:= 30
 C := ![267833, 87239, 721, -21807, -31202]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log13Mem
 k :=  15
 hpow := by decide
 heql := by decide

def Log20Mem : IdealMemCertificate O ℤ B I2
  ![![41, 0, 0, 0, 0], ![4, 1, 0, 0, 0], ![33, 0, 1, 0, 0], ![17, 0, 0, 1, 0], ![38, 0, 0, 0, 1]] ![101, -54, 0, 22, -22] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![19, -54, 0, 22, -22]
 hmem := by decide

def Log20: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R41) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![113, -54, 0, 22, -22]
 hxeq :=  rfl
 m:= 12
 C := ![101, -54, 0, 22, -22]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log20Mem
 k :=  27
 hpow := by decide
 heql := by decide

def Log21Mem : IdealMemCertificate O ℤ B I2
  ![![41, 0, 0, 0, 0], ![4, 1, 0, 0, 0], ![33, 0, 1, 0, 0], ![17, 0, 0, 1, 0], ![38, 0, 0, 0, 1]] ![27992, 10036, 920, -1530, -2672] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![2074, 10036, 920, -1530, -2672]
 hmem := by decide

def Log21: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R41) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 3 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![28009, 10036, 920, -1530, -2672]
 hxeq :=  rfl
 m:= 17
 C := ![27992, 10036, 920, -1530, -2672]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log21Mem
 k :=  33
 hpow := by decide
 heql := by decide

def Log22Mem : IdealMemCertificate O ℤ B I2
  ![![41, 0, 0, 0, 0], ![4, 1, 0, 0, 0], ![33, 0, 1, 0, 0], ![17, 0, 0, 1, 0], ![38, 0, 0, 0, 1]] ![-383137, -37964, 30148, 17252, -40006] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![19, -37964, 30148, 17252, -40006]
 hmem := by decide

def Log22: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R41) ▸ IsPrimitiveRoot.orderOf _) 5 zeta3 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-383105, -37964, 30148, 17252, -40006]
 hxeq :=  rfl
 m:= 32
 C := ![-383137, -37964, 30148, 17252, -40006]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log22Mem
 k :=  10
 hpow := by decide
 heql := by decide

def Log23Mem : IdealMemCertificate O ℤ B I2
  ![![41, 0, 0, 0, 0], ![4, 1, 0, 0, 0], ![33, 0, 1, 0, 0], ![17, 0, 0, 1, 0], ![38, 0, 0, 0, 1]] ![267836, 87239, 721, -21807, -31202] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![35402, 87239, 721, -21807, -31202]
 hmem := by decide

def Log23: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R41) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![267863, 87239, 721, -21807, -31202]
 hxeq :=  rfl
 m:= 27
 C := ![267836, 87239, 721, -21807, -31202]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log23Mem
 k :=  5
 hpow := by decide
 heql := by decide

def Log30Mem : IdealMemCertificate O ℤ B I3
  ![![41, 0, 0, 0, 0], ![22, 1, 0, 0, 0], ![4, 0, 1, 0, 0], ![29, 0, 0, 1, 0], ![15, 0, 0, 0, 1]] ![104, -54, 0, 22, -22] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A3
 g := ![24, -54, 0, 22, -22]
 hmem := by decide

def Log30: DiscreteLogCertificate N3 ((orderOf_of_IsOrderOf R41) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![113, -54, 0, 22, -22]
 hxeq :=  rfl
 m:= 9
 C := ![104, -54, 0, 22, -22]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log30Mem
 k :=  30
 hpow := by decide
 heql := by decide

def Log31Mem : IdealMemCertificate O ℤ B I3
  ![![41, 0, 0, 0, 0], ![22, 1, 0, 0, 0], ![4, 0, 1, 0, 0], ![29, 0, 0, 1, 0], ![15, 0, 0, 0, 1]] ![27969, 10036, 920, -1530, -2672] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A3
 g := ![-2733, 10036, 920, -1530, -2672]
 hmem := by decide

def Log31: DiscreteLogCertificate N3 ((orderOf_of_IsOrderOf R41) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![28009, 10036, 920, -1530, -2672]
 hxeq :=  rfl
 m:= 40
 C := ![27969, 10036, 920, -1530, -2672]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log31Mem
 k :=  20
 hpow := by decide
 heql := by decide

def Log32Mem : IdealMemCertificate O ℤ B I3
  ![![41, 0, 0, 0, 0], ![22, 1, 0, 0, 0], ![4, 0, 1, 0, 0], ![29, 0, 0, 1, 0], ![15, 0, 0, 0, 1]] ![-383119, -37964, 30148, 17252, -40006] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A3
 g := ![10519, -37964, 30148, 17252, -40006]
 hmem := by decide

def Log32: DiscreteLogCertificate N3 ((orderOf_of_IsOrderOf R41) ▸ IsPrimitiveRoot.orderOf _) 5 zeta3 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-383105, -37964, 30148, 17252, -40006]
 hxeq :=  rfl
 m:= 14
 C := ![-383119, -37964, 30148, 17252, -40006]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log32Mem
 k :=  25
 hpow := by decide
 heql := by decide

def Log33Mem : IdealMemCertificate O ℤ B I3
  ![![41, 0, 0, 0, 0], ![22, 1, 0, 0, 0], ![4, 0, 1, 0, 0], ![29, 0, 0, 1, 0], ![15, 0, 0, 0, 1]] ![267840, 87239, 721, -21807, -31202] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A3
 g := ![-13509, 87239, 721, -21807, -31202]
 hmem := by decide

def Log33: DiscreteLogCertificate N3 ((orderOf_of_IsOrderOf R41) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![267863, 87239, 721, -21807, -31202]
 hxeq :=  rfl
 m:= 23
 C := ![267840, 87239, 721, -21807, -31202]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log33Mem
 k :=  36
 hpow := by decide
 heql := by decide

def J : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![2, 0, 0, 0, 0], ![-5, -6, -1, 1, 2]] i)))
def MulJ0 : IdealMulEqCertificate O ℤ TT (J) J
  ![![2, 0, 0, 0, 0], ![-5, -6, -1, 1, 2]] ![![2, 0, 0, 0, 0], ![-5, -6, -1, 1, 2]]
  ![![2, 0, 0, 0, 0], ![-5, -5, -1, 1, 2]] where
 T := T
 heq := T_eq_TT
 hI1 := rfl
 hI2 := rfl
 M :=  ![![![4, 0, 0, 0, 0], ![-10, -12, -2, 2, 4]], ![![-10, -12, -2, 2, 4], ![361, 90, 1, -14, -14]]]
 hmul := by decide
 f :=  ![![![![17107326674067, -9449506302600, -3283131391887, 1283085492523, 4564539858348], ![-7572149476804, 0, 166530654324, 372332856, 383172]], ![![0, 0, 0, 0, 0], ![-18146, 0, -3, 0, 0]]], ![![![-67503239085230384816, 37286496910643699861, 12954800449959926318, -5062884950919498674, -18011068078759352080], ![29878696201945797905, 0, -657107845546364358, -1469176001401617, -1511945845557]], ![![0, 0, 0, 0, 0], ![71601669101, 0, 11837550, 1597, 2]]]]
 g :=  ![![![![267, -149, -59, 37, 50], ![-182, 0, 0, 4, 0]], ![![-73154, 41870, 16490, -10361, -14120], ![50670, 0, 0, -1106, -4]]], ![![![-73154, 41870, 16490, -10361, -14120], ![50670, 0, 0, -1106, -4]], ![![274432, -157064, -61856, 38869, 52970], ![-190069, 0, 0, 4149, 14]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ1 : IdealMulEqCertificate O ℤ TT (J*J) J
  ![![2, 0, 0, 0, 0], ![-5, -5, -1, 1, 2]] ![![2, 0, 0, 0, 0], ![-5, -6, -1, 1, 2]]
  ![![4, 0, 0, 0, 0], ![-7, -7, -1, 1, 2]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ0
 hI2 := rfl
 M :=  ![![![4, 0, 0, 0, 0], ![-10, -12, -2, 2, 4]], ![![-10, -10, -2, 2, 4], ![217, 54, -1, -8, -2]]]
 hmul := by decide
 f :=  ![![![![-420406694497221, 232218379421040, 80681829859255, -31531387420270, -112172011373829], ![186082977966358, 0, -4092433738218, -9149986821, -8657403]], ![![0, 0, 0, 0, 0], ![2857244, 0, 0, 2340, 18]]], ![![![699417186883287, -386334299151670, -134227782790760, 52457761916438, 186616991758298], ![-309580305641287, 0, 6808451269107, 15222540759, 14403045]], ![![0, 0, 0, 0, 0], ![-4753505, 0, 0, -3893, -30]]]]
 g :=  ![![![![2481590316271, -1402372859729, -253713800446, 179453712635, 359985732090], ![-1600345804632, 145648619100, 358504860, 1401700, 8928]], ![![-5813705774169, 3285386447031, 594383922669, -420412297108, -843350780164], ![3749184377482, -341215958295, -839881491, -3283810, -20916]]], ![![![-5810373822385, 3283503525935, 594043269280, -420171350359, -842867438858], ![3747035644458, -341020400562, -839400138, -3281928, -20904]], ![![134924703774034, -76247373081326, -13794484586810, 9756944512428, 19572516844009], ![-87011213015415, 7918952882076, 19492001448, 76210789, 485418]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ2 : IdealMulEqCertificate O ℤ TT (J*J*J) J
  ![![4, 0, 0, 0, 0], ![-7, -7, -1, 1, 2]] ![![2, 0, 0, 0, 0], ![-5, -6, -1, 1, 2]]
  ![![4, 0, 0, 0, 0], ![29, 5, -1, -1, 0]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ1
 hI2 := rfl
 M :=  ![![![8, 0, 0, 0, 0], ![-20, -24, -4, 4, 8]], ![![-14, -14, -2, 2, 4], ![515, 138, 5, -22, -30]]]
 hmul := by decide
 f :=  ![![![![13278202814739326120866784759228, -7334139565495493602299280245071, -2548973598463526182053842723139, 995799022987520648216477071524, 3544214311196574226495371834357], ![-5876487718439736853638589431160, 0, 129384677071393211329112058059, 124019044320508867740467887, 56140113836210584720813]], ![![7867073225505851702604, 0, 0, 7274545551602095233, 15438018318050629], ![-5717372147572, 0, -601545375, -29304, -18]]], ![![![97375752378750320806650593419739, -53784941245823634053352080028316, -18692907873679682720122456599922, 7302696037584053972391999761540, 25991509540824561514167873321671], ![-43095245712948469996145141961964, 0, 948843036357544760404997165176, 909494147551188327658834479, 411703744829191860431288]], ![![57693212330059857680298, 0, 0, 53347908311389329813, 113214767836532831], ![-41928371050421, 0, -4411435365, -214901, -132]]]]
 g :=  ![![![![-296585333, 1775027763, 497455307, -354217543, -731489448], ![32731724, -244594272, 0, 550888, -23952]], ![![694223928, -4154847632, -1164404882, 829125015, 1712213888], ![-76615876, 572527344, 0, -1289476, 56064]]], ![![![495554302, -2965833446, -831181130, 591850031, 1222220806], ![-54690318, 408684240, 0, -920460, 40020]], ![![-19042455679, 113966827159, 31939445684, -22742770759, -46965761922], ![2101561755, -15704336388, 0, 35370127, -1537848]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ3 : IdealMulEqCertificate O ℤ TT (J*J*J*J) J
  ![![4, 0, 0, 0, 0], ![29, 5, -1, -1, 0]] ![![2, 0, 0, 0, 0], ![-5, -6, -1, 1, 2]]
  ![![267863, 87239, 721, -21807, -31202]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ2
 hI2 := rfl
 M :=  ![![![8, 0, 0, 0, 0], ![-20, -24, -4, 4, 8]], ![![58, 10, -2, -2, 0], ![-73, -46, -15, 2, 28]]]
 hmul := by decide
 f :=  ![![![![-2640679919753725234320166499, 1458564489173645710352007521, 506922783543873415825525010, -198037830683023131657862890, -704849598807359285339821206], ![1168676425942568395662878534, 0, -25731155333174894679454931, -24665235826602458212510, -5549945445205089950]], ![![116959604147655457287, 0, 0, 90356226271811019, -1311695751134664], ![3621256658375, 0, 0, 785292143, 1204302]]]]
 g :=  ![![![![-19880, -1609, 1506, 750, -1880]], ![![-12748, -8980, 2161, 3848, -5676]]], ![![![82598, -2816, -4828, 908, 2468]], ![![505465, 16652, -34639, -8801, 34164]]]]
 hle1 := by decide
 hle2 := by decide

lemma J5 : J ^ 5 =  Ideal.span {alpha} := by
 simp only [pow_succ, pow_one, pow_zero, one_mul]
 simp [ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ3, alpha]

lemma isUnit_zeta1 : IsUnit zeta1 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![-9487, -3242, -280, 514, 826])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide

lemma isUnit_zeta2 : IsUnit zeta2 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![276889, -1012, -11072, -12390, 23912])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide

lemma isUnit_zeta3 : IsUnit zeta3 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![3198898752415, 1041910152748, 8679201204, -260365018060, -372576911846])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide



instance hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible

noncomputable instance K_field : Field K := by
  unfold K
  infer_instance

instance K_numberField : NumberField K := by
  unfold K
  infer_instance

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  rw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, P_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by sorry

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K


def SturmRC : SturmBuilderOfList [[10368, 2160, -240, -90, 0, 1], [2160, -480, -270, 0, 5], [-288, -48, 4, 1], [72, 0, -1], [0, -1], [-1]] [10368, 2160, -240, -90, 0, 1] [2160, -480, -270, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 5 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 1, 1, 1]
  f := [900, 50, 24, 72]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [-20, 5], [-4, -1], [0, 1]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 - 90*X^3 - 240*X^2 + 2160*X + 10368
  l := [10368, 2160, -240, -90, 0, 1]
  hl := ofList_poly
  hlz := by decide
  hz := by decide
  hAdj := Adj_K
  heq := O_integral_closure
  P := [[10368, 2160, -240, -90, 0, 1], [2160, -480, -270, 0, 5], [-288, -48, 4, 1], [72, 0, -1], [0, -1], [-1]]
  SB := SturmRC
  k := 3
  r := 4
  hr := by decide
  hreq := by decide

lemma ne_dvd_torsion5 : ¬5 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
 suffices ¬ 5 ∣ 2 from ?_
 · convert this
   rw [O_integral_closure, ← Fintype.card_eq_nat_card,
   ←  NumberField.Units.torsionOrder_eq_two_of_odd_finrank (by rw [K_finrank] ; decide)]
   rfl
 · decide

def NPCJ : NonPrincipalCertificateNDvdT J where
 p := 5
 hp := by decide
 r := 3
 huc := by
  rw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2, zeta3]
 hu := fun i =>
  match i with
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
  | 2 => isUnit_zeta3
 q := ![11, 31, 41, 41]
 hqP := by
  intro i
  match i with
  | 0 => exact hq11
  | 1 => exact hq31
  | 2 => exact hq41
  | 3 => exact hq41
 I := ![I0, I1, I2, I3]
 hcard := fun i =>
  match i with
  | 0 => N0
  | 1 => N1
  | 2 => N2
  | 3 => N3
 ζ := ![2, 3, 6, 6]
 hr := fun i =>
  match i with
  | 0 => ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf R41) ▸ IsPrimitiveRoot.orderOf _)
  | 3 => ((orderOf_of_IsOrderOf R41) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 a := alpha
 n := 5
 hpdvd := by decide
 hJ := J5
 hpndvdt := ne_dvd_torsion5
 M := ![![2, 3, 2, 2], ![0, 3, 0, 0], ![2, 3, 0, 0], ![0, 0, 0, 1]]
 hM1 := by
  intro j i hj
  fin_cases i <;> interval_cases j
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log00] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log01] ; decide
  · dsimp ; erw [eq_of_DiscreteLogCertificate Log02] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log10] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log11] ; decide
  · dsimp ; erw [eq_of_DiscreteLogCertificate Log12] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log20] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log21] ; decide
  · dsimp ; erw [eq_of_DiscreteLogCertificate Log22] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log30] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log31] ; decide
  · dsimp ; erw [eq_of_DiscreteLogCertificate Log32] ; decide
 hM2 := by
  intro i
  match i with
  | 0 => exact Log03
  | 1 => exact Log13
  | 2 => exact Log23
  | 3 => exact Log33
 hDl := by decide
 Minv := ![![0, 2, 3, 0], ![0, 2, 0, 0], ![3, 0, 2, 4], ![0, 0, 0, 1]]
 hInv := by decide
 N := ![![0, 2, 3], ![0, 2, 0], ![3, 0, 2]]
 hNiv := by decide

theorem J_not_principal : ¬ ∃ b, J = Ideal.span {b} :=
  not_principal_of_NonPrincipalCertificateNDvdT NPCJ
