import IdealArithmetic.IdealArithmetic
import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem
import IdealArithmetic.PrincipalityCertificate
import Mathlib.RingTheory.AdjoinRoot

--------------------------------------------
-- EXAMPLE
--------------------------------------------

/- Number field `K(α)` with with α root of polynomial `X^5 + 15*X^3 - 100*X^2 + 150*X - 120`.
Class number `5`, generated by class of ideal `J = (2, 1/18*a^4 + 2/9*a^3 + 31/18*a^2 - 5/3*a - 1/3)`. We have `J ^ 5 = (α)`. -/

/- Ring of integers with basis `[1, a, a^2, 1/3*a^3 - 1/3*a^2, 1/54*a^4 - 1/27*a^3 + 19/54*a^2 + 4/9*a - 1/9]` -/

open BigOperators Classical Matrix Polynomial

noncomputable def P : ℤ[X] := X^5 + 15*X^3 - 100*X^2 + 150*X - 120

def K := AdjoinRoot (map (algebraMap ℤ ℚ) P)

lemma P_irreducible : Irreducible P := sorry
lemma P_degree : P.natDegree = 5 := sorry
lemma P_monic : Monic P := sorry

--local notation "K" =>  AdjoinRoot (map (algebraMap ℤ ℚ) (X^5 + 15*X^3 - 100*X^2 + 150*X - 120 ))

noncomputable instance : CommRing K := by
  unfold K
  infer_instance

noncomputable instance : Algebra ℚ K := by
  unfold K
  infer_instance

noncomputable def Adj_K : IsAdjoinRoot K (map (algebraMap ℤ ℚ) (X^5 + 15*X^3 - 100*X^2 + 150*X - 120 )) := by
  unfold K
  exact AdjoinRoot.isAdjoinRoot (Polynomial.map (algebraMap ℤ ℚ) (X^5 + 15*X^3 - 100*X^2 + 150*X - 120))


lemma ofList_poly : ofList [-120, 150, -100, 15, 0, 1] = X^5 + 15*X^3 - 100*X^2 + 150*X - 120   := by
  simp ; ring


noncomputable def O : Subalgebra ℤ K := sorry

noncomputable def TT : TimesTable (Fin 5) ℤ O where
    basis := sorry
    table := ![![![1, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![0, 0, 0, 0, 1]], ![![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 1, 3, 0], ![2, -8, -6, 1, 18], ![2, -2, 3, 0, -2]], ![![0, 0, 1, 0, 0], ![0, 0, 1, 3, 0], ![6, -24, -17, 6, 54], ![38, -42, 34, -17, -18], ![-4, 6, -5, 9, 4]], ![![0, 0, 0, 1, 0], ![2, -8, -6, 1, 18], ![38, -42, 34, -17, -18], ![-36, 84, 2, 34, -84], ![10, -30, -12, -5, 50]], ![![0, 0, 0, 0, 1], ![2, -2, 3, 0, -2], ![-4, 6, -5, 9, 4], ![10, -30, -12, -5, 50], ![4, 0, 8, 1, -13]]]
    basis_mul_basis := sorry

noncomputable def B := TT.basis

lemma B_one : TT.basis 0 = 1 := sorry

lemma B_one_repr : TT.basis.equivFun.symm ![1, 0, 0, 0, 0] = 1 := sorry

def T : Fin 5 → Fin 5 → List ℤ :=
    ![![[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]], ![[0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 3, 0], [2, -8, -6, 1, 18], [2, -2, 3, 0, -2]], ![[0, 0, 1, 0, 0], [0, 0, 1, 3, 0], [6, -24, -17, 6, 54], [38, -42, 34, -17, -18], [-4, 6, -5, 9, 4]], ![[0, 0, 0, 1, 0], [2, -8, -6, 1, 18], [38, -42, 34, -17, -18], [-36, 84, 2, 34, -84], [10, -30, -12, -5, 50]], ![[0, 0, 0, 0, 1], [2, -2, 3, 0, -2], [-4, 6, -5, 9, 4], [10, -30, -12, -5, 50], [4, 0, 8, 1, -13]]]

lemma T_eq_TT : ∀ (i j : Fin 5), T i j = List.ofFn (TT.table i j) := by
  simp ; decide



instance : IsDomain O := by
  haveI hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) :=
  {out := (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible}
  letI hola : Field K := by
    unfold K
    exact AdjoinRoot.instField
  haveI : IsDomain K := by infer_instance
  refine Subalgebra.isDomain O

noncomputable section

instance hq61 : Fact $ Nat.Prime 61 := by decide
instance hq31 : Fact $ Nat.Prime 31 := by decide

def R61 : IsOrderOf (2 : ZMod 61) 60 where
 m := 3
 P := ![2, 3, 5]
 e := ![2, 1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def R31 : IsOrderOf (3 : ZMod 31) 30 where
 m := 3
 P := ![2, 3, 5]
 e := ![1, 1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def I0 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![31, 0, 0, 0, 0], ![5, 1, 0, 0, 0]] i)))
def I1 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![61, 0, 0, 0, 0], ![13, 1, 0, 0, 0]] i)))
def I2 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![61, 0, 0, 0, 0], ![17, 1, 0, 0, 0]] i)))

def A0: IdealEqSpanCertificate O ℤ TT I0
 ![![31, 0, 0, 0, 0], ![5, 1, 0, 0, 0]]
 ![![31, 0, 0, 0, 0], ![5, 1, 0, 0, 0], ![6, 0, 1, 0, 0], ![19, 0, 0, 1, 0], ![29, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![31, 0, 0, 0, 0], ![0, 31, 0, 0, 0], ![0, 0, 31, 0, 0], ![0, 0, 0, 31, 0], ![0, 0, 0, 0, 31]], ![![5, 1, 0, 0, 0], ![0, 5, 1, 0, 0], ![0, 0, 6, 3, 0], ![2, -8, -6, 6, 18], ![2, -2, 3, 0, 3]]]
  hmulB := by decide
  f := ![![![-147895, 2624951, 552087, 7506, -6804], ![912268, -16438401, -100998, 11718, 0]], ![![-24656, 437508, 92018, 1251, -1134], ![152087, -2739842, -16833, 1953, 0]], ![![-32877, 583405, 122703, 1668, -1512], ![202797, -3653504, -22444, 2604, 0]], ![![-90388, 1604128, 337381, 4585, -4158], ![557545, -10045645, -61700, 7161, 0]], ![![-138365, 2455597, 516471, 7023, -6365], ![853484, -15377859, -94495, 10962, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-5, 31, 0, 0, 0], ![-6, 0, 31, 0, 0], ![-19, 0, 0, 31, 0], ![-29, 0, 0, 0, 31]], ![![0, 1, 0, 0, 0], ![-1, 5, 1, 0, 0], ![-3, 0, 6, 3, 0], ![-18, -8, -6, 6, 18], ![-3, -2, 3, 0, 3]]]
  hle1 := by decide
  hle2 := by decide

lemma N0 : Nat.card (O ⧸ I0) = 31 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A0)

def A1: IdealEqSpanCertificate O ℤ TT I1
 ![![61, 0, 0, 0, 0], ![13, 1, 0, 0, 0]]
 ![![61, 0, 0, 0, 0], ![13, 1, 0, 0, 0], ![14, 0, 1, 0, 0], ![16, 0, 0, 1, 0], ![32, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![61, 0, 0, 0, 0], ![0, 61, 0, 0, 0], ![0, 0, 61, 0, 0], ![0, 0, 0, 61, 0], ![0, 0, 0, 0, 61]], ![![13, 1, 0, 0, 0], ![0, 13, 1, 0, 0], ![0, 0, 14, 3, 0], ![2, -8, -6, 14, 18], ![2, -2, 3, 0, 11]]]
  hmulB := by decide
  f := ![![![-2982160, 99808546, 8095691, 60996, -29484], ![13977845, -469346139, -1706536, 99918, 0]], ![![-639028, 21387586, 1734796, 13071, -6318], ![2995223, -100574360, -365695, 21411, 0]], ![![-710057, 23764183, 1927565, 14523, -7020], ![3328147, -111750230, -406321, 23790, 0]], ![![-781057, 26140307, 2120288, 15973, -7722], ![3660935, -122923870, -446906, 26169, 0]], ![![-1564415, 52358577, 4246920, 31998, -15467], ![7332655, -246214348, -895234, 52416, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-13, 61, 0, 0, 0], ![-14, 0, 61, 0, 0], ![-16, 0, 0, 61, 0], ![-32, 0, 0, 0, 61]], ![![0, 1, 0, 0, 0], ![-3, 13, 1, 0, 0], ![-4, 0, 14, 3, 0], ![-10, -8, -6, 14, 18], ![-6, -2, 3, 0, 11]]]
  hle1 := by decide
  hle2 := by decide

lemma N1 : Nat.card (O ⧸ I1) = 61 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A1)

def A2: IdealEqSpanCertificate O ℤ TT I2
 ![![61, 0, 0, 0, 0], ![17, 1, 0, 0, 0]]
 ![![61, 0, 0, 0, 0], ![17, 1, 0, 0, 0], ![16, 0, 1, 0, 0], ![26, 0, 0, 1, 0], ![48, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![61, 0, 0, 0, 0], ![0, 61, 0, 0, 0], ![0, 0, 61, 0, 0], ![0, 0, 0, 61, 0], ![0, 0, 0, 0, 61]], ![![17, 1, 0, 0, 0], ![0, 17, 1, 0, 0], ![0, 0, 18, 3, 0], ![2, -8, -6, 18, 18], ![2, -2, 3, 0, 15]]]
  hmulB := by decide
  f := ![![![-1536893, 19332778, 1242500, -10926, -26244], ![5504274, -69652484, -311466, 88938, 0]], ![![-455410, 5728328, 368138, -3240, -7776], ![1631019, -20638130, -92232, 26352, 0]], ![![-426944, 5370284, 345137, -3036, -7290], ![1529070, -19348162, -86498, 24705, 0]], ![![-654631, 8234315, 529204, -4655, -11178], ![2344515, -29666746, -132634, 37881, 0]], ![![-1209381, 15212677, 977702, -8598, -20651], ![4331313, -54808514, -245078, 69984, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-17, 61, 0, 0, 0], ![-16, 0, 61, 0, 0], ![-26, 0, 0, 61, 0], ![-48, 0, 0, 0, 61]], ![![0, 1, 0, 0, 0], ![-5, 17, 1, 0, 0], ![-6, 0, 18, 3, 0], ![-18, -8, -6, 18, 18], ![-12, -2, 3, 0, 15]]]
  hle1 := by decide
  hle2 := by decide

lemma N2 : Nat.card (O ⧸ I2) = 61 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A2)

def zeta1 := TT.basis.equivFun.symm ![27037, -23656, -848, 864, 9562]

def zeta2 := TT.basis.equivFun.symm ![-1193171, 1499625, -194433, -337974, -1287680]

def alpha := TT.basis.equivFun.symm ![-1032, 392, 34, 21, -95]

def Log00Mem : IdealMemCertificate O ℤ B I0
  ![![31, 0, 0, 0, 0], ![5, 1, 0, 0, 0], ![6, 0, 1, 0, 0], ![19, 0, 0, 1, 0], ![29, 0, 0, 0, 1]] ![27033, -23656, -848, 864, 9562] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-4623, -23656, -848, 864, 9562]
 hmem := by decide

def Log00: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 3 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![27037, -23656, -848, 864, 9562]
 hxeq :=  rfl
 m:= 4
 C := ![27033, -23656, -848, 864, 9562]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log00Mem
 k :=  18
 hpow := by decide
 heql := by decide

def Log01Mem : IdealMemCertificate O ℤ B I0
  ![![31, 0, 0, 0, 0], ![5, 1, 0, 0, 0], ![6, 0, 1, 0, 0], ![19, 0, 0, 1, 0], ![29, 0, 0, 0, 1]] ![-1193172, 1499625, -194433, -337974, -1287680] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![1169017, 1499625, -194433, -337974, -1287680]
 hmem := by decide

def Log01: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-1193171, 1499625, -194433, -337974, -1287680]
 hxeq :=  rfl
 m:= 1
 C := ![-1193172, 1499625, -194433, -337974, -1287680]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log01Mem
 k :=  0
 hpow := by decide
 heql := by decide

def Log02Mem : IdealMemCertificate O ℤ B I0
  ![![31, 0, 0, 0, 0], ![5, 1, 0, 0, 0], ![6, 0, 1, 0, 0], ![19, 0, 0, 1, 0], ![29, 0, 0, 0, 1]] ![-1060, 392, 34, 21, -95] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-28, 392, 34, 21, -95]
 hmem := by decide

def Log02: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-1032, 392, 34, 21, -95]
 hxeq :=  rfl
 m:= 28
 C := ![-1060, 392, 34, 21, -95]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log02Mem
 k :=  16
 hpow := by decide
 heql := by decide

def Log10Mem : IdealMemCertificate O ℤ B I1
  ![![61, 0, 0, 0, 0], ![13, 1, 0, 0, 0], ![14, 0, 1, 0, 0], ![16, 0, 0, 1, 0], ![32, 0, 0, 0, 1]] ![27004, -23656, -848, 864, 9562] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![436, -23656, -848, 864, 9562]
 hmem := by decide

def Log10: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![27037, -23656, -848, 864, 9562]
 hxeq :=  rfl
 m:= 33
 C := ![27004, -23656, -848, 864, 9562]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log10Mem
 k :=  21
 hpow := by decide
 heql := by decide

def Log11Mem : IdealMemCertificate O ℤ B I1
  ![![61, 0, 0, 0, 0], ![13, 1, 0, 0, 0], ![14, 0, 1, 0, 0], ![16, 0, 0, 1, 0], ![32, 0, 0, 0, 1]] ![-1193217, 1499625, -194433, -337974, -1287680] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![469624, 1499625, -194433, -337974, -1287680]
 hmem := by decide

def Log11: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 3 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-1193171, 1499625, -194433, -337974, -1287680]
 hxeq :=  rfl
 m:= 46
 C := ![-1193217, 1499625, -194433, -337974, -1287680]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log11Mem
 k :=  58
 hpow := by decide
 heql := by decide

def Log12Mem : IdealMemCertificate O ℤ B I1
  ![![61, 0, 0, 0, 0], ![13, 1, 0, 0, 0], ![14, 0, 1, 0, 0], ![16, 0, 0, 1, 0], ![32, 0, 0, 0, 1]] ![-1036, 392, 34, 21, -95] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-64, 392, 34, 21, -95]
 hmem := by decide

def Log12: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-1032, 392, 34, 21, -95]
 hxeq :=  rfl
 m:= 4
 C := ![-1036, 392, 34, 21, -95]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log12Mem
 k :=  2
 hpow := by decide
 heql := by decide

def Log20Mem : IdealMemCertificate O ℤ B I2
  ![![61, 0, 0, 0, 0], ![17, 1, 0, 0, 0], ![16, 0, 1, 0, 0], ![26, 0, 0, 1, 0], ![48, 0, 0, 0, 1]] ![26985, -23656, -848, 864, 9562] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![-635, -23656, -848, 864, 9562]
 hmem := by decide

def Log20: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![27037, -23656, -848, 864, 9562]
 hxeq :=  rfl
 m:= 52
 C := ![26985, -23656, -848, 864, 9562]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log20Mem
 k :=  42
 hpow := by decide
 heql := by decide

def Log21Mem : IdealMemCertificate O ℤ B I2
  ![![61, 0, 0, 0, 0], ![17, 1, 0, 0, 0], ![16, 0, 1, 0, 0], ![26, 0, 0, 1, 0], ![48, 0, 0, 0, 1]] ![-1193186, 1499625, -194433, -337974, -1287680] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![770821, 1499625, -194433, -337974, -1287680]
 hmem := by decide

def Log21: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 3 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-1193171, 1499625, -194433, -337974, -1287680]
 hxeq :=  rfl
 m:= 15
 C := ![-1193186, 1499625, -194433, -337974, -1287680]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log21Mem
 k :=  28
 hpow := by decide
 heql := by decide

def Log22Mem : IdealMemCertificate O ℤ B I2
  ![![61, 0, 0, 0, 0], ![17, 1, 0, 0, 0], ![16, 0, 1, 0, 0], ![26, 0, 0, 1, 0], ![48, 0, 0, 0, 1]] ![-1076, 392, 34, 21, -95] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![-70, 392, 34, 21, -95]
 hmem := by decide

def Log22: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-1032, 392, 34, 21, -95]
 hxeq :=  rfl
 m:= 44
 C := ![-1076, 392, 34, 21, -95]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log22Mem
 k :=  17
 hpow := by decide
 heql := by decide

def J : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![2, 0, 0, 0, 0], ![0, -3, 1, 1, 3]] i)))
def MulJ0 : IdealMulEqCertificate O ℤ TT (J) J
  ![![2, 0, 0, 0, 0], ![0, -3, 1, 1, 3]] ![![2, 0, 0, 0, 0], ![0, -3, 1, 1, 3]]
  ![![2, 0, 0, 0, 0], ![6, -2, 0, 0, 1]] where
 T := T
 heq := T_eq_TT
 hI1 := rfl
 hI2 := rfl
 M :=  ![![![4, 0, 0, 0, 0], ![0, -6, 2, 2, 6]], ![![0, -6, 2, 2, 6], ![70, -84, 8, 15, 69]]]
 hmul := by decide
 f :=  ![![![![603293701959, -271666372867, -187179085472, 37015701145, 125025767580], ![519956518513, -146660911881, -1035430269, 0, -13687557]], ![![0, 0, 0, 0, 0], ![-59139, -215, -9, 0, -1]]], ![![![1853680236162, -834722100659, -575126460365, 113734443805, 384154175041], ![1597618405270, -450630319674, -3181463058, 0, -42056388]], ![![0, 0, 0, 0, 0], ![-181710, -660, -28, 0, -3]]]]
 g :=  ![![![![2, 0, 0, 0, 0], ![0, 0, 0, 0, 0]], ![![-4, 3, 0, 4, 7], ![0, 0, -2, 0, 0]]], ![![![-4, 3, 0, 4, 7], ![0, 0, -2, 0, 0]], ![![-3, 22, 0, 30, 55], ![5, -7, -15, 0, 0]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ1 : IdealMulEqCertificate O ℤ TT (J*J) J
  ![![2, 0, 0, 0, 0], ![6, -2, 0, 0, 1]] ![![2, 0, 0, 0, 0], ![0, -3, 1, 1, 3]]
  ![![4, 0, 0, 0, 0], ![-12, 14, 0, -1, -7]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ0
 hI2 := rfl
 M :=  ![![![4, 0, 0, 0, 0], ![0, -6, 2, 2, 6]], ![![12, -4, 0, 0, 2], ![-4, -8, 2, 5, 15]]]
 hmul := by decide
 f :=  ![![![![7960615882, -3584709522, -2469880271, 488434462, 1649754102], ![6860972542, -1935231435, -13662873, 0, -180747]], ![![0, 0, 0, 0, 0], ![-3462, -294, -6, 0, 0]]], ![![![-23884756217, 10755438322, 7410543231, -1465481848, -4949865085], ![-20585424415, 5806401381, 40993611, 0, 542307]], ![![0, 0, 0, 0, 0], ![10387, 882, 18, 0, 0]]]]
 g :=  ![![![![853, 588, 0, 162, 0], ![-528, 504, 168, 0, 0]], ![![10523, 7285, 0, 2006, -3], ![-6529, 6225, 2079, 0, 5]]], ![![![6808, 4712, 0, 1296, -4], ![-4224, 4028, 1344, 0, 2]], ![![18117, 12541, 0, 3454, -4], ![-11240, 10717, 3579, 0, 9]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ2 : IdealMulEqCertificate O ℤ TT (J*J*J) J
  ![![4, 0, 0, 0, 0], ![-12, 14, 0, -1, -7]] ![![2, 0, 0, 0, 0], ![0, -3, 1, 1, 3]]
  ![![4, 0, 0, 0, 0], ![6, -2, 0, 0, 1]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ1
 hI2 := rfl
 M :=  ![![![8, 0, 0, 0, 0], ![0, -12, 4, 4, 12]], ![![-24, 28, 0, -2, -14], ![2, -10, -2, -4, -9]]]
 hmul := by decide
 f :=  ![![![![-3876134595326, 1751631776320, 1196093272483, -251685249707, -794264500393], ![-3346640403681, 957391229781, 2904338640, 0, 16516213]], ![![-107504, -209543, 0, 0, 0], ![132947, 10113, 21, 0, 3]]], ![![![-3878434526038, 1752671118899, 1196802982526, -251834588855, -794735782615], ![-3348626155428, 957959304351, 2906061949, 0, 16526013]], ![![-107568, -209667, 0, 0, 0], ![133026, 10119, 21, 0, 3]]]]
 g :=  ![![![![2, 0, 0, 0, 0], ![0, 0, 0, 0, 0]], ![![-8, -33, 0, -8, -3], ![8, 16, 12, 0, 0]]], ![![![0, 19, 0, 4, 1], ![-6, -6, -6, 0, 0]], ![![3, 27, 0, 8, 4], ![-5, -14, -12, 0, 0]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ3 : IdealMulEqCertificate O ℤ TT (J*J*J*J) J
  ![![4, 0, 0, 0, 0], ![6, -2, 0, 0, 1]] ![![2, 0, 0, 0, 0], ![0, -3, 1, 1, 3]]
  ![![-1032, 392, 34, 21, -95]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ2
 hI2 := rfl
 M :=  ![![![8, 0, 0, 0, 0], ![0, -12, 4, 4, 12]], ![![12, -4, 0, 0, 2], ![-4, -8, 2, 5, 15]]]
 hmul := by decide
 f :=  ![![![![953084725213204, -430700499856980, -294101751776143, 61885675830229, 195297971454412], ![822889668994133, -235408426461957, -714133308938, 0, -4063855586]], ![![-320274724, 33054629, 39206943, 0, 0], ![4356327, 390684, 1548, 0, 0]]]]
 g :=  ![![![![-22, 23, -13, -1, -2]], ![![-141, 214, 0, -17, -225]]], ![![![-10, 16, 8, -10, -32]], ![![-130, 119, -59, -52, -33]]]]
 hle1 := by decide
 hle2 := by decide

lemma J5 : J ^ 5 =  Ideal.span {alpha} := by
 simp only [pow_succ, pow_one, pow_zero, one_mul]
 simp [ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ3, alpha]
lemma isUnit_zeta1 : IsUnit zeta1 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![1237, 12952, 15792, 1268, -39958])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide

lemma isUnit_zeta2 : IsUnit zeta2 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![10676839, -4412835, -348407, -177106, 1177610])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide



instance hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible

noncomputable instance K_field : Field K := by
  unfold K
  infer_instance

instance K_numberField : NumberField K := by
  unfold K
  infer_instance

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  rw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, P_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by sorry

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K


def SturmRC : SturmBuilderOfList [[-120, 150, -100, 15, 0, 1], [150, -200, 45, 0, 5], [20, -20, 10, -1], [-230, 220, -89], [-16, -35], [1]] [-120, 150, -100, 15, 0, 1] [150, -200, 45, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 5 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 1, 7921, 1225]
  f := [150, 5, 270, 427734]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [-50, -5], [-670, 89], [-9124, 3115]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 + 15*X^3 - 100*X^2 + 150*X - 120
  l := [-120, 150, -100, 15, 0, 1]
  hl := ofList_poly
  hlz := by decide
  hz := by decide
  hAdj := Adj_K
  heq := O_integral_closure
  P := [[-120, 150, -100, 15, 0, 1], [150, -200, 45, 0, 5], [20, -20, 10, -1], [-230, 220, -89], [-16, -35], [1]]
  SB := SturmRC
  k := 1
  r := 3
  hr := by decide
  hreq := by decide

lemma ne_dvd_torsion5 : ¬5 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
 suffices ¬ 5 ∣ 2 from ?_
 · convert this
   rw [O_integral_closure, ← Fintype.card_eq_nat_card,
   ←  NumberField.Units.torsionOrder_eq_two_of_odd_finrank (by rw [K_finrank] ; decide)]
   rfl
 · decide

def NPCJ : NonPrincipalCertificateNDvdT J where
 p := 5
 hp := by decide
 r := 2
 huc := by
  rw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2]
 hu := fun i =>
  match i with
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
 q := ![31, 61, 61]
 hqP := by
  intro i
  match i with
  | 0 => exact hq31
  | 1 => exact hq61
  | 2 => exact hq61
 I := ![I0, I1, I2]
 hcard := fun i =>
  match i with
  | 0 => N0
  | 1 => N1
  | 2 => N2
 ζ := ![3, 2, 2]
 hr := fun i =>
  match i with
  | 0 => ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf R61) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 a := alpha
 n := 5
 hpdvd := by decide
 hJ := J5
 hpndvdt := ne_dvd_torsion5
 M := ![![3, 0, 1], ![1, 3, 2], ![2, 3, 2]]
 hM1 := by
  intro j i hj
  fin_cases i <;> interval_cases j
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log00] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log01] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log10] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log11] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log20] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log21] ; decide
 hM2 := by
  intro i
  match i with
  | 0 => exact Log02
  | 1 => exact Log12
  | 2 => exact Log22
 hDl := by decide
 Minv := ![![0, 4, 1], ![1, 2, 0], ![1, 3, 2]]
 hInv := by decide
 N := ![![2, 0], ![1, 2]]
 hNiv := by decide

theorem J_not_principal : ¬ ∃ b, J = Ideal.span {b} :=
  not_principal_of_NonPrincipalCertificateNDvdT NPCJ
