import IdealArithmetic.IdealArithmetic
import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem
import IdealArithmetic.PrincipalityCertificate
import Mathlib.RingTheory.AdjoinRoot

--------------------------------------------
-- EXAMPLE
--------------------------------------------

/- Number field `K(α)` with with α root of polynomial `X^5 + 75*X^3 - 150*X^2 + 1350*X - 4860`.
Class number `3`, generated by class of ideal `J = (2, 1/72*a^4 - 1/24*a^3 + 2/3*a^2 - 31/12*a + 17/2)`. We have `J ^ 3 = (α)`. -/

/- Ring of integers with basis `[1, a, a^2, 1/6*a^3 - 1/2*a^2, 1/432*a^4 + 1/48*a^3 - 5/36*a^2 - 7/72*a + 1/4]` -/

open BigOperators Classical Matrix Polynomial

noncomputable def P : ℤ[X] := X^5 + 75*X^3 - 150*X^2 + 1350*X - 4860

def K := AdjoinRoot (map (algebraMap ℤ ℚ) P)

lemma P_irreducible : Irreducible P := sorry
lemma P_degree : P.natDegree = 5 := sorry
lemma P_monic : Monic P := sorry

--local notation "K" =>  AdjoinRoot (map (algebraMap ℤ ℚ) (X^5 + 75*X^3 - 150*X^2 + 1350*X - 4860 ))

noncomputable instance : CommRing K := by
  unfold K
  infer_instance

noncomputable instance : Algebra ℚ K := by
  unfold K
  infer_instance

noncomputable def Adj_K : IsAdjoinRoot K (map (algebraMap ℤ ℚ) (X^5 + 75*X^3 - 150*X^2 + 1350*X - 4860 )) := by
  unfold K
  exact AdjoinRoot.isAdjoinRoot (Polynomial.map (algebraMap ℤ ℚ) (X^5 + 75*X^3 - 150*X^2 + 1350*X - 4860))


lemma ofList_poly : ofList [-4860, 1350, -150, 75, 0, 1] = X^5 + 75*X^3 - 150*X^2 + 1350*X - 4860   := by
  simp ; ring


noncomputable def O : Subalgebra ℤ K := sorry

noncomputable def TT : TimesTable (Fin 5) ℤ O where
    basis := sorry
    table := ![![![1, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0], ![0, 0, 0, 0, 1]], ![![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 3, 6, 0], ![-18, 7, 4, -12, 72], ![9, -2, 0, -3, 9]], ![![0, 0, 1, 0, 0], ![0, 0, 3, 6, 0], ![-108, 42, 33, -54, 432], ![864, -246, -29, -48, -216], ![135, -30, -14, 9, -135]], ![![0, 0, 0, 1, 0], ![-18, 7, 4, -12, 72], ![864, -246, -29, -48, -216], ![-612, 283, -73, 199, -792], ![-297, 93, 1, 31, -27]], ![![0, 0, 0, 0, 1], ![9, -2, 0, -3, 9], ![135, -30, -14, 9, -135], ![-297, 93, 1, 31, -27], ![-69, 17, 4, 1, 30]]]
    basis_mul_basis := sorry

noncomputable def B := TT.basis

lemma B_one : TT.basis 0 = 1 := sorry

lemma B_one_repr : TT.basis.equivFun.symm ![1, 0, 0, 0, 0] = 1 := sorry

def T : Fin 5 → Fin 5 → List ℤ :=
    ![![[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]], ![[0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 3, 6, 0], [-18, 7, 4, -12, 72], [9, -2, 0, -3, 9]], ![[0, 0, 1, 0, 0], [0, 0, 3, 6, 0], [-108, 42, 33, -54, 432], [864, -246, -29, -48, -216], [135, -30, -14, 9, -135]], ![[0, 0, 0, 1, 0], [-18, 7, 4, -12, 72], [864, -246, -29, -48, -216], [-612, 283, -73, 199, -792], [-297, 93, 1, 31, -27]], ![[0, 0, 0, 0, 1], [9, -2, 0, -3, 9], [135, -30, -14, 9, -135], [-297, 93, 1, 31, -27], [-69, 17, 4, 1, 30]]]

lemma T_eq_TT : ∀ (i j : Fin 5), T i j = List.ofFn (TT.table i j) := by
  simp ; decide



instance : IsDomain O := by
  haveI hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) :=
  {out := (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible}
  letI hola : Field K := by
    unfold K
    exact AdjoinRoot.instField
  haveI : IsDomain K := by infer_instance
  refine Subalgebra.isDomain O

noncomputable section

instance hq19 : Fact $ Nat.Prime 19 := by decide
instance hq7 : Fact $ Nat.Prime 7 := by decide

def R19 : IsOrderOf (2 : ZMod 19) 18 where
 m := 2
 P := ![2, 3]
 e := ![1, 2]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def R7 : IsOrderOf (3 : ZMod 7) 6 where
 m := 2
 P := ![2, 3]
 e := ![1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def I0 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![7, 0, 0, 0, 0], ![2, 1, 0, 0, 0]] i)))
def I1 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![19, 0, 0, 0, 0], ![-2, 1, 0, 0, 0]] i)))
def I2 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![7, 0, 0, 0, 0], ![-2, 1, 0, 0, 0]] i)))

def A0: IdealEqSpanCertificate O ℤ TT I0
 ![![7, 0, 0, 0, 0], ![2, 1, 0, 0, 0]]
 ![![7, 0, 0, 0, 0], ![2, 1, 0, 0, 0], ![3, 0, 1, 0, 0], ![1, 0, 0, 1, 0], ![4, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![7, 0, 0, 0, 0], ![0, 7, 0, 0, 0], ![0, 0, 7, 0, 0], ![0, 0, 0, 7, 0], ![0, 0, 0, 0, 7]], ![![2, 1, 0, 0, 0], ![0, 2, 1, 0, 0], ![0, 0, 5, 6, 0], ![-18, 7, 4, -10, 72], ![9, -2, 0, -3, 11]]]
  hmulB := by decide
  f := ![![![-675, -62, -5751, -7098, 432], ![1988, -630, 8211, -42, 0]], ![![-678, -61, -5795, -7152, 432], ![1996, -637, 8274, -42, 0]], ![![-679, -62, -5795, -7152, 432], ![2000, -636, 8274, -42, 0]], ![![-1, -2, 10, 13, 0], ![4, 5, -15, 0, 0]], ![![-384, -34, -3286, -4056, 247], ![1130, -362, 4692, -24, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-2, 7, 0, 0, 0], ![-3, 0, 7, 0, 0], ![-1, 0, 0, 7, 0], ![-4, 0, 0, 0, 7]], ![![0, 1, 0, 0, 0], ![-1, 2, 1, 0, 0], ![-3, 0, 5, 6, 0], ![-46, 7, 4, -10, 72], ![-4, -2, 0, -3, 11]]]
  hle1 := by decide
  hle2 := by decide

lemma N0 : Nat.card (O ⧸ I0) = 7 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A0)

def A1: IdealEqSpanCertificate O ℤ TT I1
 ![![19, 0, 0, 0, 0], ![-2, 1, 0, 0, 0]]
 ![![19, 0, 0, 0, 0], ![17, 1, 0, 0, 0], ![15, 0, 1, 0, 0], ![7, 0, 0, 1, 0], ![1, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![19, 0, 0, 0, 0], ![0, 19, 0, 0, 0], ![0, 0, 19, 0, 0], ![0, 0, 0, 19, 0], ![0, 0, 0, 0, 19]], ![![-2, 1, 0, 0, 0], ![0, -2, 1, 0, 0], ![0, 0, 1, 6, 0], ![-18, 7, 4, -14, 72], ![9, -2, 0, -3, 7]]]
  hmulB := by decide
  f := ![![![13703, -6813, 6265, 38760, -2376], ![124526, -266, -121277, 627, 0]], ![![12455, -6191, 5695, 35238, -2160], ![113184, -228, -110257, 570, 0]], ![![11211, -5573, 5125, 31710, -1944], ![101880, -208, -99218, 513, 0]], ![![4985, -2478, 2278, 14095, -864], ![45302, -92, -44102, 228, 0]], ![![725, -359, 329, 2040, -125], ![6590, 0, -6383, 33, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-17, 19, 0, 0, 0], ![-15, 0, 19, 0, 0], ![-7, 0, 0, 19, 0], ![-1, 0, 0, 0, 19]], ![![-1, 1, 0, 0, 0], ![1, -2, 1, 0, 0], ![-3, 0, 1, 6, 0], ![-9, 7, 4, -14, 72], ![3, -2, 0, -3, 7]]]
  hle1 := by decide
  hle2 := by decide

lemma N1 : Nat.card (O ⧸ I1) = 19 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A1)

def A2: IdealEqSpanCertificate O ℤ TT I2
 ![![7, 0, 0, 0, 0], ![-2, 1, 0, 0, 0]]
 ![![7, 0, 0, 0, 0], ![5, 1, 0, 0, 0], ![3, 0, 1, 0, 0], ![3, 0, 0, 1, 0], ![6, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![7, 0, 0, 0, 0], ![0, 7, 0, 0, 0], ![0, 0, 7, 0, 0], ![0, 0, 0, 7, 0], ![0, 0, 0, 0, 7]], ![![-2, 1, 0, 0, 0], ![0, -2, 1, 0, 0], ![0, 0, 1, 6, 0], ![-18, 7, 4, -14, 72], ![9, -2, 0, -3, 7]]]
  hmulB := by decide
  f := ![![![1961, -982, 706, 4550, -720], ![6230, -77, -5145, 70, 0]], ![![1571, -787, 565, 3640, -576], ![4992, -63, -4116, 56, 0]], ![![1177, -588, 422, 2724, -432], ![3740, -41, -3080, 42, 0]], ![![785, -392, 282, 1821, -288], ![2494, -27, -2059, 28, 0]], ![![1682, -842, 605, 3900, -617], ![5344, -65, -4410, 60, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-5, 7, 0, 0, 0], ![-3, 0, 7, 0, 0], ![-3, 0, 0, 7, 0], ![-6, 0, 0, 0, 7]], ![![-1, 1, 0, 0, 0], ![1, -2, 1, 0, 0], ![-3, 0, 1, 6, 0], ![-65, 7, 4, -14, 72], ![-2, -2, 0, -3, 7]]]
  hle1 := by decide
  hle2 := by decide

lemma N2 : Nat.card (O ⧸ I2) = 7 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A2)

def zeta1 := TT.basis.equivFun.symm ![-2288805750138070, 620125621715449, 93403693655176, 22466222402355, 682300270585169]

def zeta2 := TT.basis.equivFun.symm ![-54324600083209633790, -4967282771824132614, -4453797873765804231, 1284007303743294015, -15311415569050906829]

def alpha := TT.basis.equivFun.symm ![10068117025306292741207, 920598809183421036433, 825434632072257476354, -237969304875711315349, 2837709977494504993054]

def Log00Mem : IdealMemCertificate O ℤ B I0
  ![![7, 0, 0, 0, 0], ![2, 1, 0, 0, 0], ![3, 0, 1, 0, 0], ![1, 0, 0, 1, 0], ![4, 0, 0, 0, 1]] ![-2288805750138074, 620125621715449, 93403693655176, 22466222402355, 682300270585169] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-937276482753933, 620125621715449, 93403693655176, 22466222402355, 682300270585169]
 hmem := by decide

def Log00: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R7) ▸ IsPrimitiveRoot.orderOf _) 3 zeta1 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-2288805750138070, 620125621715449, 93403693655176, 22466222402355, 682300270585169]
 hxeq :=  rfl
 m:= 4
 C := ![-2288805750138074, 620125621715449, 93403693655176, 22466222402355, 682300270585169]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log00Mem
 k :=  4
 hpow := by decide
 heql := by decide

def Log01Mem : IdealMemCertificate O ℤ B I0
  ![![7, 0, 0, 0, 0], ![2, 1, 0, 0, 0], ![3, 0, 1, 0, 0], ![1, 0, 0, 1, 0], ![4, 0, 0, 0, 1]] ![-54324600083209633796, -4967282771824132614, -4453797873765804231, 1284007303743294015, -15311415569050906829] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![4133287722028053918, -4967282771824132614, -4453797873765804231, 1284007303743294015, -15311415569050906829]
 hmem := by decide

def Log01: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R7) ▸ IsPrimitiveRoot.orderOf _) 3 zeta2 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-54324600083209633790, -4967282771824132614, -4453797873765804231, 1284007303743294015, -15311415569050906829]
 hxeq :=  rfl
 m:= 6
 C := ![-54324600083209633796, -4967282771824132614, -4453797873765804231, 1284007303743294015, -15311415569050906829]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log01Mem
 k :=  3
 hpow := by decide
 heql := by decide

def Log02Mem : IdealMemCertificate O ℤ B I0
  ![![7, 0, 0, 0, 0], ![2, 1, 0, 0, 0], ![3, 0, 1, 0, 0], ![1, 0, 0, 1, 0], ![4, 0, 0, 0, 1]] ![10068117025306292741202, 920598809183421036433, 825434632072257476354, -237969304875711315349, 2837709977494504993054] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-766036442054232916799, 920598809183421036433, 825434632072257476354, -237969304875711315349, 2837709977494504993054]
 hmem := by decide

def Log02: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R7) ▸ IsPrimitiveRoot.orderOf _) 3 alpha 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![10068117025306292741207, 920598809183421036433, 825434632072257476354, -237969304875711315349, 2837709977494504993054]
 hxeq :=  rfl
 m:= 5
 C := ![10068117025306292741202, 920598809183421036433, 825434632072257476354, -237969304875711315349, 2837709977494504993054]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log02Mem
 k :=  5
 hpow := by decide
 heql := by decide

def Log10Mem : IdealMemCertificate O ℤ B I1
  ![![19, 0, 0, 0, 0], ![17, 1, 0, 0, 0], ![15, 0, 1, 0, 0], ![7, 0, 0, 1, 0], ![1, 0, 0, 0, 1]] ![-2288805750138078, 620125621715449, 93403693655176, 22466222402355, 682300270585169] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-793240029027895, 620125621715449, 93403693655176, 22466222402355, 682300270585169]
 hmem := by decide

def Log10: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R19) ▸ IsPrimitiveRoot.orderOf _) 3 zeta1 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-2288805750138070, 620125621715449, 93403693655176, 22466222402355, 682300270585169]
 hxeq :=  rfl
 m:= 8
 C := ![-2288805750138078, 620125621715449, 93403693655176, 22466222402355, 682300270585169]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log10Mem
 k :=  3
 hpow := by decide
 heql := by decide

def Log11Mem : IdealMemCertificate O ℤ B I1
  ![![19, 0, 0, 0, 0], ![17, 1, 0, 0, 0], ![15, 0, 1, 0, 0], ![7, 0, 0, 1, 0], ![1, 0, 0, 0, 1]] ![-54324600083209633793, -4967282771824132614, -4453797873765804231, 1284007303743294015, -15311415569050906829] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![5434186294059764886, -4967282771824132614, -4453797873765804231, 1284007303743294015, -15311415569050906829]
 hmem := by decide

def Log11: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R19) ▸ IsPrimitiveRoot.orderOf _) 3 zeta2 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-54324600083209633790, -4967282771824132614, -4453797873765804231, 1284007303743294015, -15311415569050906829]
 hxeq :=  rfl
 m:= 3
 C := ![-54324600083209633793, -4967282771824132614, -4453797873765804231, 1284007303743294015, -15311415569050906829]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log11Mem
 k :=  13
 hpow := by decide
 heql := by decide

def Log12Mem : IdealMemCertificate O ℤ B I1
  ![![19, 0, 0, 0, 0], ![17, 1, 0, 0, 0], ![15, 0, 1, 0, 0], ![7, 0, 0, 1, 0], ![1, 0, 0, 0, 1]] ![10068117025306292741206, 920598809183421036433, 825434632072257476354, -237969304875711315349, 2837709977494504993054] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-1007131950276855411004, 920598809183421036433, 825434632072257476354, -237969304875711315349, 2837709977494504993054]
 hmem := by decide

def Log12: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R19) ▸ IsPrimitiveRoot.orderOf _) 3 alpha 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![10068117025306292741207, 920598809183421036433, 825434632072257476354, -237969304875711315349, 2837709977494504993054]
 hxeq :=  rfl
 m:= 1
 C := ![10068117025306292741206, 920598809183421036433, 825434632072257476354, -237969304875711315349, 2837709977494504993054]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log12Mem
 k :=  0
 hpow := by decide
 heql := by decide

def Log20Mem : IdealMemCertificate O ℤ B I2
  ![![7, 0, 0, 0, 0], ![5, 1, 0, 0, 0], ![3, 0, 1, 0, 0], ![3, 0, 0, 1, 0], ![6, 0, 0, 0, 1]] ![-2288805750138075, 620125621715449, 93403693655176, 22466222402355, 682300270585169] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![-1404406461485561, 620125621715449, 93403693655176, 22466222402355, 682300270585169]
 hmem := by decide

def Log20: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R7) ▸ IsPrimitiveRoot.orderOf _) 3 zeta1 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-2288805750138070, 620125621715449, 93403693655176, 22466222402355, 682300270585169]
 hxeq :=  rfl
 m:= 5
 C := ![-2288805750138075, 620125621715449, 93403693655176, 22466222402355, 682300270585169]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log20Mem
 k :=  5
 hpow := by decide
 heql := by decide

def Log21Mem : IdealMemCertificate O ℤ B I2
  ![![7, 0, 0, 0, 0], ![5, 1, 0, 0, 0], ![3, 0, 1, 0, 0], ![3, 0, 0, 1, 0], ![6, 0, 0, 0, 1]] ![-54324600083209633796, -4967282771824132614, -4453797873765804231, 1284007303743294015, -15311415569050906829] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![10269954128612000128, -4967282771824132614, -4453797873765804231, 1284007303743294015, -15311415569050906829]
 hmem := by decide

def Log21: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R7) ▸ IsPrimitiveRoot.orderOf _) 3 zeta2 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-54324600083209633790, -4967282771824132614, -4453797873765804231, 1284007303743294015, -15311415569050906829]
 hxeq :=  rfl
 m:= 6
 C := ![-54324600083209633796, -4967282771824132614, -4453797873765804231, 1284007303743294015, -15311415569050906829]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log21Mem
 k :=  3
 hpow := by decide
 heql := by decide

def Log22Mem : IdealMemCertificate O ℤ B I2
  ![![7, 0, 0, 0, 0], ![5, 1, 0, 0, 0], ![3, 0, 1, 0, 0], ![3, 0, 0, 1, 0], ![6, 0, 0, 0, 1]] ![10068117025306292741202, 920598809183421036433, 825434632072257476354, -237969304875711315349, 2837709977494504993054] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![-1903361838166782983186, 920598809183421036433, 825434632072257476354, -237969304875711315349, 2837709977494504993054]
 hmem := by decide

def Log22: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R7) ▸ IsPrimitiveRoot.orderOf _) 3 alpha 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![10068117025306292741207, 920598809183421036433, 825434632072257476354, -237969304875711315349, 2837709977494504993054]
 hxeq :=  rfl
 m:= 5
 C := ![10068117025306292741202, 920598809183421036433, 825434632072257476354, -237969304875711315349, 2837709977494504993054]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log22Mem
 k :=  5
 hpow := by decide
 heql := by decide

def J : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![2, 0, 0, 0, 0], ![7, -2, 1, -1, 6]] i)))
def MulJ0 : IdealMulEqCertificate O ℤ TT (J) J
  ![![2, 0, 0, 0, 0], ![7, -2, 1, -1, 6]] ![![2, 0, 0, 0, 0], ![7, -2, 1, -1, 6]]
  ![![2, 0, 0, 0, 0], ![1, 1, 2, -1, 10]] where
 T := T
 heq := T_eq_TT
 hI1 := rfl
 hI2 := rfl
 M :=  ![![![4, 0, 0, 0, 0], ![14, -4, 2, -2, 12]], ![![14, -4, 2, -2, 12], ![13, 1, 4, -1, 12]]]
 hmul := by decide
 f :=  ![![![![-4081188906423, 317518993956, 730583512435, -434606084733, 4385377550042], ![-862952717680, 196476917838, 0, -210026688, 4123905]], ![![0, 0, 0, 0, 0], ![220930, 2043, 0, -75, -2]]], ![![![-641789403840, 49931608293, 114888275857, -68344197348, 689624741215], ![-135704061467, 30897076038, 0, -33027852, 648507]], ![![0, 0, 0, 0, 0], ![34739, 322, 0, -12, 0]]]]
 g :=  ![![![![-2081, 607, 42, 79, 120], ![-130, 44, 0, 0, 4]], ![![-9262, 2700, 186, 352, 529], ![-578, 196, 0, 0, 18]]], ![![![-9262, 2700, 186, 352, 529], ![-578, 196, 0, 0, 18]], ![![-6032, 1764, 123, 230, 347], ![-379, 128, 0, 0, 12]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ1 : IdealMulEqCertificate O ℤ TT (J*J) J
  ![![2, 0, 0, 0, 0], ![1, 1, 2, -1, 10]] ![![2, 0, 0, 0, 0], ![7, -2, 1, -1, 6]]
  ![![10068117025306292741207, 920598809183421036433, 825434632072257476354, -237969304875711315349, 2837709977494504993054]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ0
 hI2 := rfl
 M :=  ![![![4, 0, 0, 0, 0], ![14, -4, 2, -2, 12]], ![![2, 2, 4, -2, 20], ![25, 17, 4, 1, 4]]]
 hmul := by decide
 f :=  ![![![![-89431642228285188234682351940645, 6957825060070197907140991837140, 16009371589739123744659875932899, -9523580525028542008589476928622, 96097358976453327522688778567767], ![-18910019872324541283838211495295, 4305426728362777057456376876799, 0, -4602334202357849509688096301, 93140644682593361124156846]], ![![0, 0, 0, 0, 0], ![5298929661380904404862889, 355927775796719739009832, 0, 0, -9147518216122871704774]]]]
 g :=  ![![![![2331818, -3899479, 1650979, -1459514, 9959720]], ![![-68914790, 14613947, 3848794, 645823, 15098536]]], ![![![-81345296, 33101087, -3746963, 7451962, -30888400]], ![![204419729, -1156113, -33487765, 15889884, -174522998]]]]
 hle1 := by decide
 hle2 := by decide

lemma J3 : J ^ 3 =  Ideal.span {alpha} := by
 simp only [pow_succ, pow_one, pow_zero, one_mul]
 simp [ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ1, alpha]

lemma isUnit_zeta1 : IsUnit zeta1 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![344412118014352214, 31492024271224303, 28236629471802842, -8140500563315459, 97072938388913653])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide

lemma isUnit_zeta2 : IsUnit zeta2 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![-778559803182313074925274, 103413255323453356813642, 75739613518786416371803, -18704694124197856516081, 360078571582185268860887])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide



instance hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible

noncomputable instance K_field : Field K := by
  unfold K
  infer_instance

instance K_numberField : NumberField K := by
  unfold K
  infer_instance

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  rw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, P_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by sorry

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K


def SturmRC : SturmBuilderOfList [[-4860, 1350, -150, 75, 0, 1], [1350, -300, 225, 0, 5], [162, -36, 3, -1], [-126, 1, -3], [-225, -31], [1]] [-4860, 1350, -150, 75, 0, 1] [1350, -300, 225, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 5 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 1, 9, 961]
  f := [750, 30, 2, 279936]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [-15, -5], [-8, 3], [-706, 93]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 + 75*X^3 - 150*X^2 + 1350*X - 4860
  l := [-4860, 1350, -150, 75, 0, 1]
  hl := ofList_poly
  hlz := by decide
  hz := by decide
  hAdj := Adj_K
  heq := O_integral_closure
  P := [[-4860, 1350, -150, 75, 0, 1], [1350, -300, 225, 0, 5], [162, -36, 3, -1], [-126, 1, -3], [-225, -31], [1]]
  SB := SturmRC
  k := 1
  r := 3
  hr := by decide
  hreq := by decide

lemma ne_dvd_torsion3 : ¬3 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
 suffices ¬ 3 ∣ 2 from ?_
 · convert this
   rw [O_integral_closure, ← Fintype.card_eq_nat_card]
   convert (Subtype.val_inj.2
    (torsionOrder_eq_two_of_odd_finrank (by rw [K_finrank] ; decide)))
 · decide

def NPCJ : NonPrincipalCertificateNDvdT J where
 p := 3
 hp := by decide
 r := 2
 huc := by
  rw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2]
 hu := fun i =>
  match i with
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
 q := ![7, 19, 7]
 hqP := by
  intro i
  match i with
  | 0 => exact hq7
  | 1 => exact hq19
  | 2 => exact hq7
 I := ![I0, I1, I2]
 hcard := fun i =>
  match i with
  | 0 => N0
  | 1 => N1
  | 2 => N2
 ζ := ![3, 2, 3]
 hr := fun i =>
  match i with
  | 0 => ((orderOf_of_IsOrderOf R7) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf R19) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf R7) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 a := alpha
 n := 3
 hpdvd := by decide
 hJ := J3
 hpndvdt := ne_dvd_torsion3
 M := ![![1, 0, 2], ![0, 1, 0], ![2, 0, 2]]
 hM1 := by
  intro j i hj
  fin_cases i <;> interval_cases j
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log00] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log01] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log10] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log11] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log20] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log21] ; decide
 hM2 := by
  intro i
  match i with
  | 0 => exact Log02
  | 1 => exact Log12
  | 2 => exact Log22
 hDl := by decide
 Minv := ![![2, 0, 1], ![0, 1, 0], ![1, 0, 1]]
 hInv := by decide
 N := ![![1, 0], ![0, 1]]
 hNiv := by decide

theorem J_not_principal : ¬ ∃ b, J = Ideal.span {b} :=
  not_principal_of_NonPrincipalCertificateNDvdT NPCJ
