import IdealArithmetic.IdealArithmetic
import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem
import IdealArithmetic.PrincipalityCertificate
import Mathlib.RingTheory.AdjoinRoot


open BigOperators Classical Matrix Polynomial
--------------------------------------------
-- EXAMPLE
--------------------------------------------

/- Number field `K(α)` with with α root of polynomial `X^5 + 10*X^3 - 10*X^2 - 15*X - 18`.
Class number `5`, generated by class of ideal `J = (2, -1/8*a^4 - 1/8*a^3 - 11/8*a^2 - 1/8*a + 11/4)`. We have `J ^ 5 = (α)`. -/

/- Ring of integers with basis `1, a, a^2, 1/2*a^3 - 1/2*a, 1/24*a^4 - 1/8*a^3 - 5/24*a^2 + 5/24*a - 1/4` -/


noncomputable def P : ℤ[X] := (X^5 + 10*X^3 - 10*X^2 - 15*X - 18 )

def K := AdjoinRoot (map (algebraMap ℤ ℚ) P)

lemma P_irreducible : Irreducible P := sorry
lemma P_degree : P.natDegree = 5 := sorry
lemma P_monic : Monic P := sorry

--local notation "K" =>  AdjoinRoot (map (algebraMap ℤ ℚ) (X^5 + 10*X^3 - 10*X^2 - 15*X - 18 ))

noncomputable instance : CommRing K := by
  unfold K
  infer_instance

noncomputable instance : Algebra ℚ K := by
  unfold K
  infer_instance

noncomputable def Adj_K : IsAdjoinRoot K (map (algebraMap ℤ ℚ) (X^5 + 10*X^3 - 10*X^2 - 15*X - 18 )) := by
  unfold K
  exact AdjoinRoot.isAdjoinRoot (Polynomial.map (algebraMap ℤ ℚ) (X^5 + 10*X^3 - 10*X^2 - 15*X - 18 ))


lemma ofList_poly : ofList [-18, -15, -10, 10, 0, 1] = X^5 + 10*X^3 - 10*X^2 - 15*X - 18  := by
  simp ; ring


noncomputable def O : Subalgebra ℤ K := sorry

noncomputable def TT : TimesTable (Fin 5) ℤ O :=
  { basis := sorry,
    table := ![ ![![1, 0, 0, 0, 0],![0, 1, 0, 0, 0],![0, 0, 1, 0, 0],![0, 0, 0, 1, 0],![0, 0, 0, 0, 1]],
          ![![0, 1, 0, 0, 0],![0, 0, 1, 0, 0],![0, 1, 0, 2, 0],![3, -1, 2, 3, 12],![0, 0, 0, -2, -3]],
          ![![0, 0, 1, 0, 0],![0, 1, 0, 2, 0],![6, -2, 5, 6, 24],![9, 2, 5, -11, 0],![-6, 2, -4, 0, -15]],
          ![![0, 0, 0, 1, 0],![3, -1, 2, 3, 12],![9, 2, 5, -11, 0],![-18, 13, -11, -13, -72],![0, -5, 1, 12, 24]],
          ![![0, 0, 0, 0, 1],![0, 0, 0, -2, -3],![-6, 2, -4, 0, -15],![0, -5, 1, 12, 24],![4, 0, 2, -4, 2]]]
    basis_mul_basis := sorry }

noncomputable def B := TT.basis

lemma B_one : TT.basis 0 = 1 := sorry

lemma B_one_repr : TT.basis.equivFun.symm ![1, 0, 0, 0, 0] = 1 := sorry

def T : Fin 5 → Fin 5 → List ℤ :=
  ![![[1, 0, 0, 0, 0],[0, 1, 0, 0, 0],[0, 0, 1, 0, 0],[0, 0, 0, 1, 0],[0, 0, 0, 0, 1]],
  ![[0, 1, 0, 0, 0],[0, 0, 1, 0, 0],[0, 1, 0, 2, 0],[3, -1, 2, 3, 12],[0, 0, 0, -2, -3]],
  ![[0, 0, 1, 0, 0],[0, 1, 0, 2, 0],[6, -2, 5, 6, 24],[9, 2, 5, -11, 0],[-6, 2, -4, 0, -15]],
  ![[0, 0, 0, 1, 0],[3, -1, 2, 3, 12],[9, 2, 5, -11, 0],[-18, 13, -11, -13, -72],[0, -5, 1, 12, 24]],
  ![[0, 0, 0, 0, 1],[0, 0, 0, -2, -3],[-6, 2, -4, 0, -15],[0, -5, 1, 12, 24],[4, 0, 2, -4, 2]]]

lemma T_eq_TT : ∀ (i j : Fin 5), T i j = List.ofFn (TT.table i j) := by
  simp ; decide


instance : IsDomain O := by
  haveI hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) :=
  {out := (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible}
  letI hola : Field K := by
    unfold K
    exact AdjoinRoot.instField
  haveI : IsDomain K := by infer_instance
  refine Subalgebra.isDomain O

noncomputable section

instance hq151 : Fact $ Nat.Prime 151 := by decide
instance hq11 : Fact $ Nat.Prime 11 := by decide
instance hq31 : Fact $ Nat.Prime 31 := by decide

def R151 : IsOrderOf (6 : ZMod 151) 150 where
 m := 3
 P := ![2, 3, 5]
 e := ![1, 1, 2]
 hP := by decide
 hm := by rfl
 hid := by sorry
 hnid := by decide

def R11 : IsOrderOf (2 : ZMod 11) 10 where
 m := 2
 P := ![2, 5]
 e := ![1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def R31 : IsOrderOf (3 : ZMod 31) 30 where
 m := 3
 P := ![2, 3, 5]
 e := ![1, 1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def I0 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![11, 0, 0, 0, 0], ![4, 1, 0, 0, 0]] i)))
def I1 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![31, 0, 0, 0, 0], ![-4, 1, 0, 0, 0]] i)))
def I2 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![151, 0, 0, 0, 0], ![-48, 1, 0, 0, 0]] i)))

def A0: IdealEqSpanCertificate O ℤ TT I0
 ![![11, 0, 0, 0, 0], ![4, 1, 0, 0, 0]]
 ![![11, 0, 0, 0, 0], ![4, 1, 0, 0, 0], ![6, 0, 1, 0, 0], ![8, 0, 0, 1, 0], ![5, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![11, 0, 0, 0, 0], ![0, 11, 0, 0, 0], ![0, 0, 11, 0, 0], ![0, 0, 0, 11, 0], ![0, 0, 0, 0, 11]], ![![4, 1, 0, 0, 0], ![0, 4, 1, 0, 0], ![0, 1, 4, 2, 0], ![3, -1, 2, 7, 12], ![0, 0, 0, -2, 1]]]
  hmulB := by decide
  f := ![![![1130, 286, 225, 319, 420], ![-2816, -77, -407, -385, 0]], ![![485, 123, 97, 137, 180], ![-1209, -33, -176, -165, 0]], ![![646, 163, 128, 182, 240], ![-1610, -43, -231, -220, 0]], ![![807, 205, 161, 228, 300], ![-2011, -57, -291, -275, 0]], ![![510, 128, 102, 145, 191], ![-1270, -32, -185, -175, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-4, 11, 0, 0, 0], ![-6, 0, 11, 0, 0], ![-8, 0, 0, 11, 0], ![-5, 0, 0, 0, 11]], ![![0, 1, 0, 0, 0], ![-2, 4, 1, 0, 0], ![-4, 1, 4, 2, 0], ![-11, -1, 2, 7, 12], ![1, 0, 0, -2, 1]]]
  hle1 := by decide
  hle2 := by decide

lemma N0 : Nat.card (O ⧸ I0) = 11 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A0)

def A1: IdealEqSpanCertificate O ℤ TT I1
 ![![31, 0, 0, 0, 0], ![-4, 1, 0, 0, 0]]
 ![![31, 0, 0, 0, 0], ![27, 1, 0, 0, 0], ![15, 0, 1, 0, 0], ![1, 0, 0, 1, 0], ![13, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![31, 0, 0, 0, 0], ![0, 31, 0, 0, 0], ![0, 0, 31, 0, 0], ![0, 0, 0, 31, 0], ![0, 0, 0, 0, 31]], ![![-4, 1, 0, 0, 0], ![0, -4, 1, 0, 0], ![0, 1, -4, 2, 0], ![3, -1, 2, -1, 12], ![0, 0, 0, -2, -7]]]
  hmulB := by decide
  f := ![![![14579, -45687, 173495, -86924, 360], ![112282, 10943, 1346857, -930, 0]], ![![14551, -45611, 173219, -86786, 360], ![112066, 10943, 1344718, -930, 0]], ![![14467, -45326, 172118, -86234, 360], ![111418, 10851, 1336162, -930, 0]], ![![7, -19, 85, -43, 0], ![54, 33, 667, 0, 0]], ![![6113, -19159, 72756, -36452, 151], ![47080, 4588, 564811, -390, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-27, 31, 0, 0, 0], ![-15, 0, 31, 0, 0], ![-1, 0, 0, 31, 0], ![-13, 0, 0, 0, 31]], ![![-1, 1, 0, 0, 0], ![3, -4, 1, 0, 0], ![1, 1, -4, 2, 0], ![-5, -1, 2, -1, 12], ![3, 0, 0, -2, -7]]]
  hle1 := by decide
  hle2 := by decide

lemma N1 : Nat.card (O ⧸ I1) = 31 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A1)

def A2: IdealEqSpanCertificate O ℤ TT I2
 ![![151, 0, 0, 0, 0], ![-48, 1, 0, 0, 0]]
 ![![151, 0, 0, 0, 0], ![103, 1, 0, 0, 0], ![112, 0, 1, 0, 0], ![145, 0, 0, 1, 0], ![18, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![151, 0, 0, 0, 0], ![0, 151, 0, 0, 0], ![0, 0, 151, 0, 0], ![0, 0, 0, 151, 0], ![0, 0, 0, 0, 151]], ![![-48, 1, 0, 0, 0], ![0, -48, 1, 0, 0], ![0, 1, -48, 2, 0], ![3, -1, 2, -45, 12], ![0, 0, 0, -2, -51]]]
  hmulB := by decide
  f := ![![![-1125302885, 60112449, -2148657559, 89680410, -39000], ![-3539984657, -25485931, -6759829080, 490750, 0]], ![![-810222539, 43281204, -1547042101, 64570256, -28080], ![-2548802989, -18349973, -4867104178, 353340, 0]], ![![-855232418, 45685577, -1632984074, 68157292, -29640], ![-2690395340, -19369373, -5137483721, 372970, 0]], ![![-1080290729, 57707945, -2062711194, 86093191, -37440], ![-3398385143, -24466506, -6489435720, 471120, 0]], ![![-134142006, 7165738, -256131365, 10690380, -4649], ![-421984738, -3038005, -805807440, 58500, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-103, 151, 0, 0, 0], ![-112, 0, 151, 0, 0], ![-145, 0, 0, 151, 0], ![-18, 0, 0, 0, 151]], ![![-1, 1, 0, 0, 0], ![32, -48, 1, 0, 0], ![33, 1, -48, 2, 0], ![41, -1, 2, -45, 12], ![8, 0, 0, -2, -51]]]
  hle1 := by decide
  hle2 := by decide

lemma N2 : Nat.card (O ⧸ I2) = 151 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A2)

def zeta1 := TT.basis.equivFun.symm ![-11, 18, -2, 2, -3]

def zeta2 := TT.basis.equivFun.symm ![5, 3, 5, 2, 8]

def alpha := TT.basis.equivFun.symm ![0, 1, -1, -1, -4]

def Log00Mem : IdealMemCertificate O ℤ B I0
  ![![11, 0, 0, 0, 0], ![4, 1, 0, 0, 0], ![6, 0, 1, 0, 0], ![8, 0, 0, 1, 0], ![5, 0, 0, 0, 1]] ![-16, 18, -2, 2, -3] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-7, 18, -2, 2, -3]
 hmem := by decide

def Log00: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 4 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-11, 18, -2, 2, -3]
 hxeq :=  rfl
 m:= 5
 C := ![-16, 18, -2, 2, -3]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log00Mem
 k :=  4
 hpow := by decide
 heql := by decide

def Log01Mem : IdealMemCertificate O ℤ B I0
  ![![11, 0, 0, 0, 0], ![4, 1, 0, 0, 0], ![6, 0, 1, 0, 0], ![8, 0, 0, 1, 0], ![5, 0, 0, 0, 1]] ![-1, 3, 5, 2, 8] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-9, 3, 5, 2, 8]
 hmem := by decide

def Log01: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 4 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![5, 3, 5, 2, 8]
 hxeq :=  rfl
 m:= 6
 C := ![-1, 3, 5, 2, 8]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log01Mem
 k :=  9
 hpow := by decide
 heql := by decide

def Log02Mem : IdealMemCertificate O ℤ B I0
  ![![11, 0, 0, 0, 0], ![4, 1, 0, 0, 0], ![6, 0, 1, 0, 0], ![8, 0, 0, 1, 0], ![5, 0, 0, 0, 1]] ![-8, 1, -1, -1, -4] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![2, 1, -1, -1, -4]
 hmem := by decide

def Log02: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 3 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![0, 1, -1, -1, -4]
 hxeq :=  rfl
 m:= 8
 C := ![-8, 1, -1, -1, -4]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log02Mem
 k :=  3
 hpow := by decide
 heql := by decide

def Log10Mem : IdealMemCertificate O ℤ B I1
  ![![31, 0, 0, 0, 0], ![27, 1, 0, 0, 0], ![15, 0, 1, 0, 0], ![1, 0, 0, 1, 0], ![13, 0, 0, 0, 1]] ![-15, 18, -2, 2, -3] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-14, 18, -2, 2, -3]
 hmem := by decide

def Log10: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 3 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-11, 18, -2, 2, -3]
 hxeq :=  rfl
 m:= 4
 C := ![-15, 18, -2, 2, -3]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log10Mem
 k :=  18
 hpow := by decide
 heql := by decide

def Log11Mem : IdealMemCertificate O ℤ B I1
  ![![31, 0, 0, 0, 0], ![27, 1, 0, 0, 0], ![15, 0, 1, 0, 0], ![1, 0, 0, 1, 0], ![13, 0, 0, 0, 1]] ![-17, 3, 5, 2, 8] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![-9, 3, 5, 2, 8]
 hmem := by decide

def Log11: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![5, 3, 5, 2, 8]
 hxeq :=  rfl
 m:= 22
 C := ![-17, 3, 5, 2, 8]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log11Mem
 k :=  17
 hpow := by decide
 heql := by decide

def Log12Mem : IdealMemCertificate O ℤ B I1
  ![![31, 0, 0, 0, 0], ![27, 1, 0, 0, 0], ![15, 0, 1, 0, 0], ![1, 0, 0, 1, 0], ![13, 0, 0, 0, 1]] ![-10, 1, -1, -1, -4] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![1, 1, -1, -1, -4]
 hmem := by decide

def Log12: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 4 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![0, 1, -1, -1, -4]
 hxeq :=  rfl
 m:= 10
 C := ![-10, 1, -1, -1, -4]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log12Mem
 k :=  14
 hpow := by decide
 heql := by decide

def Log20Mem : IdealMemCertificate O ℤ B I2
  ![![151, 0, 0, 0, 0], ![103, 1, 0, 0, 0], ![112, 0, 1, 0, 0], ![145, 0, 0, 1, 0], ![18, 0, 0, 0, 1]] ![-97, 18, -2, 2, -3] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![-13, 18, -2, 2, -3]
 hmem := by decide

def Log20: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R151) ▸ IsPrimitiveRoot.orderOf _) 5 zeta1 3 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![-11, 18, -2, 2, -3]
 hxeq :=  rfl
 m:= 86
 C := ![-97, 18, -2, 2, -3]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log20Mem
 k :=  78
 hpow := by decide
 heql := by decide

def Log21Mem : IdealMemCertificate O ℤ B I2
  ![![151, 0, 0, 0, 0], ![103, 1, 0, 0, 0], ![112, 0, 1, 0, 0], ![145, 0, 0, 1, 0], ![18, 0, 0, 0, 1]] ![-56, 3, 5, 2, 8] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![-9, 3, 5, 2, 8]
 hmem := by decide

def Log21: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R151) ▸ IsPrimitiveRoot.orderOf _) 5 zeta2 4 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![5, 3, 5, 2, 8]
 hxeq :=  rfl
 m:= 61
 C := ![-56, 3, 5, 2, 8]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log21Mem
 k :=  119
 hpow := by sorry
 heql := by decide

def Log22Mem : IdealMemCertificate O ℤ B I2
  ![![151, 0, 0, 0, 0], ![103, 1, 0, 0, 0], ![112, 0, 1, 0, 0], ![145, 0, 0, 1, 0], ![18, 0, 0, 0, 1]] ![-75, 1, -1, -1, -4] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![1, 1, -1, -1, -4]
 hmem := by decide

def Log22: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R151) ▸ IsPrimitiveRoot.orderOf _) 5 alpha 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![0, 1, -1, -1, -4]
 hxeq :=  rfl
 m:= 75
 C := ![-75, 1, -1, -1, -4]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log22Mem
 k :=  5
 hpow := by decide
 heql := by decide

def J : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![2, 0, 0, 0, 0], ![2, 0, -2, -1, -3]] i)))

def MulJ0 : IdealMulEqCertificate O ℤ TT (J) J
  ![![2, 0, 0, 0, 0], ![2, 0, -2, -1, -3]] ![![2, 0, 0, 0, 0], ![2, 0, -2, -1, -3]]
  ![![2, 0, 0, 0, 0], ![4, 2, -2, -1, -4]] where
 T := T
 heq := T_eq_TT
 hI1 := rfl
 hI2 := rfl
 M :=  ![![![4, 0, 0, 0, 0], ![4, 0, -4, -2, -6]], ![![4, 0, -4, -2, -6], ![10, 7, -3, -1, -6]]]
 hmul := by decide
 f :=  ![![![![-66232, 10472, -17929, -13613, -36906], ![13872, -31416, -5749, 3412, 0]], ![![0, 0, 0, 0, 0], ![-1425, -175, 21, -1, 0]]], ![![![-209684, 33154, -56766, -43101, -116851], ![43914, -99462, -18202, 10803, 0]], ![![0, 0, 0, 0, 0], ![-4512, -554, 66, -3, 0]]]]
 g :=  ![![![![36, -30, 8, -3, 20], ![-2, 16, -4, 0, 0]], ![![32, -32, 8, -3, 21], ![0, 16, -4, 0, 0]]], ![![![32, -32, 8, -3, 21], ![0, 16, -4, 0, 0]], ![![32, -34, 9, -4, 21], ![3, 19, -3, 0, 0]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ1 : IdealMulEqCertificate O ℤ TT (J*J) J
  ![![2, 0, 0, 0, 0], ![4, 2, -2, -1, -4]] ![![2, 0, 0, 0, 0], ![2, 0, -2, -1, -3]]
  ![![4, 0, 0, 0, 0], ![2, 11, -9, -3, -14]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ0
 hI2 := rfl
 M :=  ![![![4, 0, 0, 0, 0], ![4, 0, -4, -2, -6]], ![![8, 4, -4, -2, -8], ![8, 8, -12, -5, -20]]]
 hmul := by decide
 f :=  ![![![![114, -28, 147, -63, -13], ![26, 84, -60, 116, 0]], ![![0, 0, 0, 0, 0], ![-20, 16, -4, 0, 0]]], ![![![625, -106, -1028, -344, -1281], ![-877, -73, 13, -156, 0]], ![![0, 0, 0, 0, 0], ![31, -25, 9, 0, 0]]]]
 g :=  ![![![![914, -63, -94, 31, 86], ![208, 464, 36, 0, 0]], ![![2217, -149, -233, 75, 205], ![503, 1125, 87, -1, 0]]], ![![![4604, -308, -484, 156, 424], ![1044, 2336, 180, -2, 0]], ![![8608, -561, -919, 289, 776], ![1946, 4366, 336, -5, 0]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ2 : IdealMulEqCertificate O ℤ TT (J*J*J) J
  ![![4, 0, 0, 0, 0], ![2, 11, -9, -3, -14]] ![![2, 0, 0, 0, 0], ![2, 0, -2, -1, -3]]
  ![![4, 0, 0, 0, 0], ![4, 2, -2, -1, -4]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ1
 hI2 := rfl
 M :=  ![![![8, 0, 0, 0, 0], ![8, 0, -8, -4, -12]], ![![4, 22, -18, -6, -28], ![-2, 39, -25, -7, -40]]]
 hmul := by decide
 f :=  ![![![![4002981397320, -879281682960, 1301355522905, 710156487738, 2083664126898], ![-778948559800, 2051657260240, 100798938720, -36943461676, 0]], ![![6390871272, -624010836, 69187404, 0, 0], ![-990795, 49945, -1817, -49, 0]]], ![![![5150620277056, -1131368251806, 1674448986554, 913755534331, 2681042362515], ![-1002270020434, 2639859254214, 129697594404, -47535005518, 0]], ![![8223108702, -802912266, 89023158, 0, 0], ![-1274852, 64264, -2338, -63, 0]]]]
 g :=  ![![![![-484, 834, 24, 303, 108], ![-252, -1104, -120, 0, 0]], ![![-452, 780, 20, 282, 97], ![-236, -1032, -112, 0, 0]]], ![![![1086, -1906, -58, -695, -255], ![598, 2526, 282, 0, 0]], ![![2445, -4278, -126, -1557, -564], ![1333, 5667, 629, 0, 0]]]]
 hle1 := by decide
 hle2 := by decide

def MulJ3 : IdealMulEqCertificate O ℤ TT (J*J*J*J) J
  ![![4, 0, 0, 0, 0], ![4, 2, -2, -1, -4]] ![![2, 0, 0, 0, 0], ![2, 0, -2, -1, -3]]
  ![![0, 1, -1, -1, -4]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ2
 hI2 := rfl
 M :=  ![![![8, 0, 0, 0, 0], ![8, 0, -8, -4, -12]], ![![8, 4, -4, -2, -8], ![8, 8, -12, -5, -20]]]
 hmul := by decide
 f :=  ![![![![-606792, 133416, -197518, -106843, -315632], ![117600, -311304, -15085, 4897, 0]], ![![-2429, -2445, 105, 0, 0], ![119, -3, 1, 0, 0]]]]
 g :=  ![![![![-8, -17, -13, -8, -17]], ![![37, 17, 31, 15, 40]]], ![![![0, -10, -10, -6, -14]], ![![30, 14, 14, 7, 16]]]]
 hle1 := by decide
 hle2 := by decide

lemma J5 : J ^ 5 =  Ideal.span {alpha} := by
 simp only [pow_succ, pow_one, pow_zero, one_mul]
 simp [ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ3, alpha]
lemma isUnit_zeta1 : IsUnit zeta1 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![1, 2, 0, -6, -9])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide

lemma isUnit_zeta2 : IsUnit zeta2 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![27, -105, 67, 16, 104])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide

 -------
 instance hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible

noncomputable instance K_field : Field K := by
  unfold K
  infer_instance

instance K_numberField : NumberField K := by
  unfold K
  infer_instance

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  rw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, P_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by sorry
--------------------------------------------------------------------

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K
-------


def SturmRC : SturmBuilderOfList [[-18, -15, -10, 10, 0, 1], [-15, -20, 30, 0, 5], [9, 6, 3, -2], [-3, -4, -9], [-39, -25], [1]] [-18, -15, -10, 10, 0, 1] [-15, -20, 30, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 5 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 4, 81, 625]
  f := [50, 25, 16, 11664]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [-15, -10], [-35, 18], [-251, 225]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)


def RC : RankUnitsCertificate O where
  f := X^5 + 10*X^3 - 10*X^2 - 15*X - 18
  l := [-18, -15, -10, 10, 0, 1]
  hl := ofList_poly
  hlz := by decide
  hz := by decide
  hAdj := Adj_K
  heq := O_integral_closure
  P := [[-18, -15, -10, 10, 0, 1], [-15, -20, 30, 0, 5], [9, 6, 3, -2], [-3, -4, -9], [-39, -25], [1]]
  SB := SturmRC
  k := 1
  r := 3
  hr := by decide
  hreq := by decide

lemma ne_dvd_torsion5 : ¬5 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
 suffices ¬ 5 ∣ 2 from ?_
 · convert this
   rw [O_integral_closure, ← Fintype.card_eq_nat_card,
   ←  NumberField.Units.torsionOrder_eq_two_of_odd_finrank (by rw [K_finrank] ; decide)]
   rfl
 · decide

def NPCJ : NonPrincipalCertificateNDvdT J where
 p := 5
 hp := by decide
 r := 2
 huc := by
  rw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2]
 hu := fun i =>
  match i with
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
 q := ![11, 31, 151]
 hqP := by
  intro i
  match i with
  | 0 => exact hq11
  | 1 => exact hq31
  | 2 => exact hq151
 I := ![I0, I1, I2]
 hcard := fun i =>
  match i with
  | 0 => N0
  | 1 => N1
  | 2 => N2
 ζ := ![2, 3, 6]
 hr := fun i =>
  match i with
  | 0 => ((orderOf_of_IsOrderOf R11) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf R31) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf R151) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 a := alpha
 n := 5
 hpdvd := by decide
 hJ := J5
 hpndvdt := ne_dvd_torsion5
 M := ![![4, 4, 3], ![3, 2, 4], ![3, 4, 0]]
 hM1 := by
  intro j i hj
  fin_cases i <;> interval_cases j
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log00] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log01] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log10] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log11] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log20] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log21] ; decide
 hM2 := by
  intro i
  match i with
  | 0 => exact Log02
  | 1 => exact Log12
  | 2 => exact Log22
 hDl := by decide
 Minv := ![![2, 1, 0], ![1, 3, 4], ![3, 3, 3]]
 hInv := by decide
 N := ![![2, 1], ![2, 4]]
 hNiv := by decide

theorem J_not_principal : ¬ ∃ b, J = Ideal.span {b} :=
  not_principal_of_NonPrincipalCertificateNDvdT NPCJ
