import IdealArithmetic.IdealArithmetic
import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem
import IdealArithmetic.PrincipalityCertificate
import Mathlib.RingTheory.AdjoinRoot


open BigOperators Classical Matrix Polynomial
--------------------------------------------
-- EXAMPLE
--------------------------------------------

/- Number field `K(α)` with with α root of polynomial `X^5 - 3*X^3 + 9*X - 8`.
Class number `3`, generated by class of ideal `J = (2, α)`. We have `J ^ 3 = (α)`. -/

/- Ring of integers with basis `1, 1/2*α^4 + 1/2*α, 1/2*α^4 + 1/2*α^3 + 1/2*α^2, α^3, α^4` -/

/- Minkowski's bound is around 25 -/


/-- TIP : Reveal to Lean that K is a field and number field until the very end, otherwise things slow down. -/

noncomputable def P : ℤ[X] := (X ^ 5 - 3 * X ^ 3 + 9 * X - 8)

def K := AdjoinRoot (map (algebraMap ℤ ℚ) P)

lemma P_irreducible : Irreducible P := sorry
lemma P_degree : P.natDegree = 5 := sorry
lemma P_monic : Monic P := sorry

--local notation "K" =>  AdjoinRoot (map (algebraMap ℤ ℚ) (X ^ 5 - 3 * X ^ 3 + 9 * X - 8))

noncomputable instance : CommRing K := by
  unfold K
  infer_instance

noncomputable instance : Algebra ℚ K := by
  unfold K
  infer_instance

noncomputable def Adj_K : IsAdjoinRoot K (map (algebraMap ℤ ℚ) (X ^ 5 - 3 * X ^ 3 + 9 * X - 8)) := by
  unfold K
  exact AdjoinRoot.isAdjoinRoot (Polynomial.map (algebraMap ℤ ℚ) (X ^ 5 - 3 * X ^ 3 + 9 * X - 8))


lemma ofList_poly : ofList [-8, 9, 0, -3, 0, 1] = X ^ 5 - 3 * X ^ 3 + 9 * X - 8 := by
  simp ; ring


noncomputable def O : Subalgebra ℤ K := sorry

noncomputable def TT : TimesTable (Fin 5) ℤ O :=
  { basis := sorry,
    table := ![ ![![1, 0, 0, 0, 0],![0, 1, 0, 0, 0],![0, 0, 1, 0, 0],![0, 0, 0, 1, 0],![0, 0, 0, 0, 1]],
                ![![0, 1, 0, 0, 0],![4, 3, -13, 10, 5],![8, -2, -14, 10, 9],![12, -27, 8, -4, 10],![4, 15, -27, 19, 6]],
                ![![0, 0, 1, 0, 0],![8, -2, -14, 10, 9],![16, -12, -19, 13, 18],![16, -28, -1, 2, 16],![12, 5, -28, 18, 13]],
                ![![0, 0, 0, 1, 0],![12, -27, 8, -4, 10],![16, -28, -1, 2, 16],![0, 16, -18, 9, 4],![24, -54, 16, -8, 19]],
                ![![0, 0, 0, 0, 1],![4, 15, -27, 19, 6],![12, 5, -28, 18, 13],![24, -54, 16, -8, 19],![0, 48, -54, 35, 3]]]
    basis_mul_basis := sorry }

noncomputable def B := TT.basis

lemma B_one : TT.basis 0 = 1 := sorry

lemma B_one_repr : TT.basis.equivFun.symm ![1, 0, 0, 0, 0] = 1 := sorry

def T : Fin 5 → Fin 5 → List ℤ :=
  ![ ![[1, 0, 0, 0, 0],[0, 1, 0, 0, 0],[0, 0, 1, 0, 0],[0, 0, 0, 1, 0],[0, 0, 0, 0, 1]],
  ![[0, 1, 0, 0, 0],[4, 3, -13, 10, 5],[8, -2, -14, 10, 9],[12, -27, 8, -4, 10],[4, 15, -27, 19, 6]],
  ![[0, 0, 1, 0, 0],[8, -2, -14, 10, 9],[16, -12, -19, 13, 18],[16, -28, -1, 2, 16],[12, 5, -28, 18, 13]],
  ![[0, 0, 0, 1, 0],[12, -27, 8, -4, 10],[16, -28, -1, 2, 16],[0, 16, -18, 9, 4],[24, -54, 16, -8, 19]],
  ![[0, 0, 0, 0, 1],[4, 15, -27, 19, 6],[12, 5, -28, 18, 13],[24, -54, 16, -8, 19],[0, 48, -54, 35, 3]]]

lemma T_eq_TT : ∀ (i j : Fin 5), T i j = List.ofFn (TT.table i j) := by
  simp ; decide


instance : IsDomain O := by
  haveI hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) :=
  {out := (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible}
  letI hola : Field K := by
    unfold K
    exact AdjoinRoot.instField
  haveI : IsDomain K := by infer_instance
  refine Subalgebra.isDomain O




noncomputable section


instance hq43 : Fact $ Nat.Prime 43 := by decide
instance hq67 : Fact $ Nat.Prime 67 := by decide
instance hq19 : Fact $ Nat.Prime 19 := by decide

def R43 : IsOrderOf (3 : ZMod 43) 42 where
 m := 3
 P := ![2, 3, 7]
 e := ![1, 1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def R67 : IsOrderOf (2 : ZMod 67) 66 where
 m := 3
 P := ![2, 3, 11]
 e := ![1, 1, 1]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def R19 : IsOrderOf (2 : ZMod 19) 18 where
 m := 2
 P := ![2, 3]
 e := ![1, 2]
 hP := by decide
 hm := by rfl
 hid := by decide
 hnid := by decide

def I0 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![19, 0, 0, 0, 0], ![8, 2, 0, 0, -1]] i)))
def I1 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![43, 0, 0, 0, 0], ![-32, 2, 0, 0, -1]] i)))
def I2 : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![67, 0, 0, 0, 0], ![21, 2, 0, 0, -1]] i)))

def A0: IdealEqSpanCertificate O ℤ TT I0
 ![![19, 0, 0, 0, 0], ![8, 2, 0, 0, -1]]
 ![![19, 0, 0, 0, 0], ![8, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![18, 0, 0, 1, 0], ![8, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![19, 0, 0, 0, 0], ![0, 19, 0, 0, 0], ![0, 0, 19, 0, 0], ![0, 0, 0, 19, 0], ![0, 0, 0, 0, 19]], ![![8, 2, 0, 0, -1], ![4, -1, 1, 1, 4], ![4, -9, 8, 2, 5], ![0, 0, 0, 8, 1], ![8, -18, 0, 3, 17]]]
  hmulB := by decide
  f := ![![![-66195, 21665, -19323, -18411, -76423], ![-21565, 356193, 1368, -1140, 0]], ![![-30492, 9980, -8901, -8409, -35195], ![-9935, 164079, 630, -696, 0]], ![![288, -96, 85, 174, 348], ![102, -1566, -6, -216, 0]], ![![-62714, 20524, -18306, -17447, -72401], ![-20423, 337446, 1296, -1068, 0]], ![![-27872, 9122, -8136, -7752, -32178], ![-9079, 149976, 576, -480, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-8, 19, 0, 0, 0], ![0, 0, 19, 0, 0], ![-18, 0, 0, 19, 0], ![-8, 0, 0, 0, 19]], ![![0, 2, 0, 0, -1], ![-2, -1, 1, 1, 4], ![0, -9, 8, 2, 5], ![-8, 0, 0, 8, 1], ![-2, -18, 0, 3, 17]]]
  hle1 := by decide
  hle2 := by decide

lemma N0 : Nat.card (O ⧸ I0) = 19 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A0)

def A1: IdealEqSpanCertificate O ℤ TT I1
 ![![43, 0, 0, 0, 0], ![-32, 2, 0, 0, -1]]
 ![![43, 0, 0, 0, 0], ![38, 1, 0, 0, 0], ![14, 0, 1, 0, 0], ![41, 0, 0, 1, 0], ![22, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![43, 0, 0, 0, 0], ![0, 43, 0, 0, 0], ![0, 0, 43, 0, 0], ![0, 0, 0, 43, 0], ![0, 0, 0, 0, 43]], ![![-32, 2, 0, 0, -1], ![4, -41, 1, 1, 4], ![4, -9, -32, 2, 5], ![0, 0, 0, -32, 1], ![8, -18, 0, 3, -23]]]
  hmulB := by decide
  f := ![![![76185, -1913674, 43172, 93224, 182921], ![-149898, -2013260, -4902, 62049, 0]], ![![70274, -1765191, 39822, 85162, 168754], ![-138267, -1857050, -4522, 56121, 0]], ![![24526, -615653, 13889, 30228, 58841], ![-48202, -647690, -1577, 20280, 0]], ![![72643, -1824666, 41164, 88859, 174414], ![-142924, -1919620, -4674, 59124, 0]], ![![38994, -979090, 22088, 47696, 93588], ![-76671, -1030040, -2508, 31746, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-38, 43, 0, 0, 0], ![-14, 0, 43, 0, 0], ![-41, 0, 0, 43, 0], ![-22, 0, 0, 0, 43]], ![![-2, 2, 0, 0, -1], ![33, -41, 1, 1, 4], ![14, -9, -32, 2, 5], ![30, 0, 0, -32, 1], ![25, -18, 0, 3, -23]]]
  hle1 := by decide
  hle2 := by decide

lemma N1 : Nat.card (O ⧸ I1) = 43 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A1)

def A2: IdealEqSpanCertificate O ℤ TT I2
 ![![67, 0, 0, 0, 0], ![21, 2, 0, 0, -1]]
 ![![67, 0, 0, 0, 0], ![54, 1, 0, 0, 0], ![65, 0, 1, 0, 0], ![15, 0, 0, 1, 0], ![20, 0, 0, 0, 1]] where
  T := T
  heq := T_eq_TT
  hieq := rfl
  M :=![![![67, 0, 0, 0, 0], ![0, 67, 0, 0, 0], ![0, 0, 67, 0, 0], ![0, 0, 0, 67, 0], ![0, 0, 0, 0, 67]], ![![21, 2, 0, 0, -1], ![4, 12, 1, 1, 4], ![4, -9, 21, 2, 5], ![0, 0, 0, 21, 1], ![8, -18, 0, 3, 30]]]
  hmulB := by decide
  f := ![![![-11187464, -37592922, -3155968, -3140960, -12645691], ![-4439889, 210661936, 37520, -13936, 0]], ![![-9261370, -31120717, -2612619, -2600135, -10468536], ![-3675488, 174393213, 31060, -11728, 0]], ![![-10847544, -36450698, -3060077, -3045292, -12261453], ![-4304987, 204261180, 36380, -14256, 0]], ![![-2504658, -8416326, -706560, -703205, -2831125], ![-993999, 47163120, 8400, -3104, 0]], ![![-3339544, -11221768, -942080, -937600, -3774833], ![-1325332, 62884160, 11200, -4160, 0]]]
  g := ![![![1, 0, 0, 0, 0], ![-54, 67, 0, 0, 0], ![-65, 0, 67, 0, 0], ![-15, 0, 0, 67, 0], ![-20, 0, 0, 0, 67]], ![![-1, 2, 0, 0, -1], ![-12, 12, 1, 1, 4], ![-15, -9, 21, 2, 5], ![-5, 0, 0, 21, 1], ![5, -18, 0, 3, 30]]]
  hle1 := by decide
  hle2 := by decide

lemma N2 : Nat.card (O ⧸ I2) = 67 :=
 ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate O ℤ A2)

def zeta1 := TT.basis.equivFun.symm ![3, -2, -1, 1, 2]

def zeta2 := TT.basis.equivFun.symm ![1, -2, 0, 0, 1]

def alpha := TT.basis.equivFun.symm ![0, -2, 0, 0, 1]

def Log00Mem : IdealMemCertificate O ℤ B I0
  ![![19, 0, 0, 0, 0], ![8, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![18, 0, 0, 1, 0], ![8, 0, 0, 0, 1]] ![-1, -2, -1, 1, 2] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![-1, -2, -1, 1, 2]
 hmem := by decide

def Log00: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R19) ▸ IsPrimitiveRoot.orderOf _) 3 zeta1 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![3, -2, -1, 1, 2]
 hxeq :=  rfl
 m:= 4
 C := ![-1, -2, -1, 1, 2]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log00Mem
 k :=  2
 hpow := by decide
 heql := by decide

def Log01Mem : IdealMemCertificate O ℤ B I0
  ![![19, 0, 0, 0, 0], ![8, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![18, 0, 0, 1, 0], ![8, 0, 0, 0, 1]] ![-8, -2, 0, 0, 1] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![0, -2, 0, 0, 1]
 hmem := by decide

def Log01: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R19) ▸ IsPrimitiveRoot.orderOf _) 3 zeta2 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![1, -2, 0, 0, 1]
 hxeq :=  rfl
 m:= 9
 C := ![-8, -2, 0, 0, 1]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log01Mem
 k :=  8
 hpow := by decide
 heql := by decide

def Log02Mem : IdealMemCertificate O ℤ B I0
  ![![19, 0, 0, 0, 0], ![8, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![18, 0, 0, 1, 0], ![8, 0, 0, 0, 1]] ![-8, -2, 0, 0, 1] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A0
 g := ![0, -2, 0, 0, 1]
 hmem := by decide

def Log02: DiscreteLogCertificate N0 ((orderOf_of_IsOrderOf R19) ▸ IsPrimitiveRoot.orderOf _) 3 alpha 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![0, -2, 0, 0, 1]
 hxeq :=  rfl
 m:= 8
 C := ![-8, -2, 0, 0, 1]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log02Mem
 k :=  3
 hpow := by decide
 heql := by decide

def Log10Mem : IdealMemCertificate O ℤ B I1
  ![![43, 0, 0, 0, 0], ![38, 1, 0, 0, 0], ![14, 0, 1, 0, 0], ![41, 0, 0, 1, 0], ![22, 0, 0, 0, 1]] ![-5, -2, -1, 1, 2] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![0, -2, -1, 1, 2]
 hmem := by decide

def Log10: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R43) ▸ IsPrimitiveRoot.orderOf _) 3 zeta1 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![3, -2, -1, 1, 2]
 hxeq :=  rfl
 m:= 8
 C := ![-5, -2, -1, 1, 2]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log10Mem
 k :=  39
 hpow := by decide
 heql := by decide

def Log11Mem : IdealMemCertificate O ℤ B I1
  ![![43, 0, 0, 0, 0], ![38, 1, 0, 0, 0], ![14, 0, 1, 0, 0], ![41, 0, 0, 1, 0], ![22, 0, 0, 0, 1]] ![-11, -2, 0, 0, 1] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![1, -2, 0, 0, 1]
 hmem := by decide

def Log11: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R43) ▸ IsPrimitiveRoot.orderOf _) 3 zeta2 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![1, -2, 0, 0, 1]
 hxeq :=  rfl
 m:= 12
 C := ![-11, -2, 0, 0, 1]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log11Mem
 k :=  13
 hpow := by decide
 heql := by decide

def Log12Mem : IdealMemCertificate O ℤ B I1
  ![![43, 0, 0, 0, 0], ![38, 1, 0, 0, 0], ![14, 0, 1, 0, 0], ![41, 0, 0, 1, 0], ![22, 0, 0, 0, 1]] ![-11, -2, 0, 0, 1] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A1
 g := ![1, -2, 0, 0, 1]
 hmem := by decide

def Log12: DiscreteLogCertificate N1 ((orderOf_of_IsOrderOf R43) ▸ IsPrimitiveRoot.orderOf _) 3 alpha 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![0, -2, 0, 0, 1]
 hxeq :=  rfl
 m:= 11
 C := ![-11, -2, 0, 0, 1]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log12Mem
 k :=  30
 hpow := by decide
 heql := by decide

def Log20Mem : IdealMemCertificate O ℤ B I2
  ![![67, 0, 0, 0, 0], ![54, 1, 0, 0, 0], ![65, 0, 1, 0, 0], ![15, 0, 0, 1, 0], ![20, 0, 0, 0, 1]] ![-51, -2, -1, 1, 2] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![1, -2, -1, 1, 2]
 hmem := by decide

def Log20: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R67) ▸ IsPrimitiveRoot.orderOf _) 3 zeta1 1 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![3, -2, -1, 1, 2]
 hxeq :=  rfl
 m:= 54
 C := ![-51, -2, -1, 1, 2]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log20Mem
 k :=  52
 hpow := by decide
 heql := by decide

def Log21Mem : IdealMemCertificate O ℤ B I2
  ![![67, 0, 0, 0, 0], ![54, 1, 0, 0, 0], ![65, 0, 1, 0, 0], ![15, 0, 0, 1, 0], ![20, 0, 0, 0, 1]] ![-21, -2, 0, 0, 1] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![1, -2, 0, 0, 1]
 hmem := by decide

def Log21: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R67) ▸ IsPrimitiveRoot.orderOf _) 3 zeta2 0 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![1, -2, 0, 0, 1]
 hxeq :=  rfl
 m:= 22
 C := ![-21, -2, 0, 0, 1]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log21Mem
 k :=  60
 hpow := by decide
 heql := by decide

def Log22Mem : IdealMemCertificate O ℤ B I2
  ![![67, 0, 0, 0, 0], ![54, 1, 0, 0, 0], ![65, 0, 1, 0, 0], ![15, 0, 0, 1, 0], ![20, 0, 0, 0, 1]] ![-21, -2, 0, 0, 1] where
 hieq := ideal_eq_of_IdealEqSpanCertificate _ _ A2
 g := ![1, -2, 0, 0, 1]
 hmem := by decide

def Log22: DiscreteLogCertificate N2 ((orderOf_of_IsOrderOf R67) ▸ IsPrimitiveRoot.orderOf _) 3 alpha 2 where
 r := 5
 hN := by infer_instance
 hpdvd := by decide
 B := B
 hone := B_one
 xcoord :=  ![0, -2, 0, 0, 1]
 hxeq :=  rfl
 m:= 21
 C := ![-21, -2, 0, 0, 1]
 hCeq := by rfl
 hmem := mem_of_certificate O ℤ _ _ _ _ Log22Mem
 k :=  62
 hpow := by decide
 heql := by decide

def J : Ideal O := Ideal.span (Set.range (fun i ↦ TT.basis.equivFun.symm (![![2, 0, 0, 0, 0], ![0, 2, 0, 0, -1]] i)))
def MulJ0 : IdealMulEqCertificate O ℤ TT (J) J
  ![![2, 0, 0, 0, 0], ![0, 2, 0, 0, -1]] ![![2, 0, 0, 0, 0], ![0, 2, 0, 0, -1]]
  ![![4, 0, 0, 0, 0], ![0, 2, 0, 0, -1]] where
 T := T
 heq := T_eq_TT
 hI1 := rfl
 hI2 := rfl
 M :=  ![![![4, 0, 0, 0, 0], ![0, 4, 0, 0, -2]], ![![0, 4, 0, 0, -2], ![0, 0, 2, -1, -1]]]
 hmul := by decide
 f :=  ![![![![1, 0, 0, 0, 0], ![0, 0, 0, 0, 0]], ![![0, 0, 0, 0, 0], ![0, 0, 0, 0, 0]]], ![![![959530, -984469, 231303, 248283, 380650], ![-1174793, -462699, -16515, 0, -279]], ![![0, 0, 0, 0, 0], ![813, 144, 14, 0, 1]]]]
 g :=  ![![![![1, 0, 0, 0, 0], ![0, 0, 0, 0, 0]], ![![-3272, 5570, 0, -1634, -3192], ![3586, 0, 3256, 0, 8]]], ![![![-3272, 5570, 0, -1634, -3192], ![3586, 0, 3256, 0, 8]], ![![-2752, 4684, 0, -1374, -2684], ![3016, 2, 2736, 0, 7]]]]
 hle1 := by decide
 hle2 := by decide

-- If K is just notation for AdjoinRoot, then this causes issues. It does not figure out the
-- right instance of multiplication between ideals. Also, the fact that K has a field instance
-- should be provided later, otherwise this makes it slower.

def MulJ1 : IdealMulEqCertificate O ℤ TT (J*J) J
  ![![4, 0, 0, 0, 0], ![0, 2, 0, 0, -1]] ![![2, 0, 0, 0, 0], ![0, 2, 0, 0, -1]]
  ![![0, -2, 0, 0, 1]] where
 T := T
 heq := T_eq_TT
 hI1 := ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ0
 hI2 := rfl
 M :=  ![![![8, 0, 0, 0, 0], ![0, 8, 0, 0, -4]], ![![0, 4, 0, 0, -2], ![0, 0, 2, -1, -1]]]
 hmul := by decide
 f :=  ![![![![-237953673, 244315050, -58559901, -60410931, -93335826], ![290982966, 117096441, 1832187, 0, 11991]], ![![195536, 46731, 1668, 0, 27], ![-99, -18, 0, 0, -1]]]]
 g :=  ![![![![-9, 0, 6, -3, -4]], ![![-4, 0, 0, 0, 0]]], ![![![-2, 0, 0, 0, 0]], ![![0, -2, 0, 0, 1]]]]
 hle1 := by decide
 hle2 := by decide

lemma J3 : J ^ 3 =  Ideal.span {alpha} := by
 simp only [pow_succ, pow_one, pow_zero, one_mul]
 simp [ideal_eq_mul_of_IdealMulEqCertificate O ℤ TT _ _ _ _ _ MulJ1, alpha]
lemma isUnit_zeta1 : IsUnit zeta1 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![3, -4, -3, 2, 4])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide

lemma isUnit_zeta2 : IsUnit zeta2 := by
 apply isUnit_of_mul_eq_one _ (TT.basis.equivFun.symm ![-7, 4, 4, -3, -5])
 rw [← B_one_repr]
 refine table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis ?_
 rw [← table_mul_eq_table_mul' _ _ T_eq_TT]
 decide

-------------------------------------------------------------------
instance hirr : Fact $ Irreducible (map (algebraMap ℤ ℚ) P) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (P_monic)).1 P_irreducible

noncomputable instance K_field : Field K := by
  unfold K
  infer_instance

instance K_numberField : NumberField K := by
  unfold K
  infer_instance

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  rw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, P_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by sorry
--------------------------------------------------------------------

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K


lemma ne_dvd_torsion3 : ¬3 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
 suffices ¬ 3 ∣ 2 from ?_
 · convert this
   rw [O_integral_closure, ← Fintype.card_eq_nat_card]
   convert (Subtype.val_inj.2
    (torsionOrder_eq_two_of_odd_finrank (by rw [K_finrank] ; decide)))
 · decide

def SturmRC : SturmBuilderOfList [[-8, 9, 0, -3, 0, 1], [9, 0, -9, 0, 5], [20, -18, 0, 3], [-27, 100, -63], [-4752, 3103], [1]] [-8, 9, 0, -3, 0, 1] [9, 0, -9, 0, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 5 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 9, 3969, 9628609]
  f := [10, 3, 15, 208061595]
  epos := by decide
  fpos := by decide
  Q := [[0, 5], [0, 15], [-300, -189], [10924, -195489]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 - 3*X^3 + 9*X - 8
  l := [-8, 9, 0, -3, 0, 1]
  hl := ofList_poly
  hlz := by decide
  hz := by decide
  hAdj := Adj_K
  heq := O_integral_closure
  P := [[-8, 9, 0, -3, 0, 1], [9, 0, -9, 0, 5], [20, -18, 0, 3], [-27, 100, -63], [-4752, 3103], [1]]
  SB := SturmRC
  k := 1
  r := 3
  hr := by decide
  hreq := by decide

def NPCJ : NonPrincipalCertificateNDvdT J where
 p := 3
 hp := by decide
 r := 2
 huc := by
  rw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2]
 hu := fun i =>
  match i with
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
 q := ![19, 43, 67]
 hqP := by
  intro i
  match i with
  | 0 => exact hq19
  | 1 => exact hq43
  | 2 => exact hq67
 I := ![I0, I1, I2]
 hcard := fun i =>
  match i with
  | 0 => N0
  | 1 => N1
  | 2 => N2
 ζ := ![2, 3, 2]
 hr := fun i =>
  match i with
  | 0 => ((orderOf_of_IsOrderOf R19) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf R43) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf R67) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 a := alpha
 n := 3
 hpdvd := by decide
 hJ := J3
 hpndvdt := ne_dvd_torsion3
 M := ![![2, 2, 0], ![0, 1, 0], ![1, 0, 2]]
 hM1 := by
  intro j i hj
  fin_cases i <;> interval_cases j
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log00] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log01] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log10] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log11] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log20] ; decide
  · dsimp ; rw [eq_of_DiscreteLogCertificate Log21] ; decide
 hM2 := by
  intro i
  match i with
  | 0 => exact Log02
  | 1 => exact Log12
  | 2 => exact Log22
 hDl := by decide
 Minv := ![![2, 2, 0], ![0, 1, 0], ![2, 2, 2]]
 hInv := by decide
 N := ![![2, 2], ![0, 1]]
 hNiv := by decide


theorem J_not_principal : ¬ ∃ b, J = Ideal.span {b} :=
  not_principal_of_NonPrincipalCertificateNDvdT NPCJ
