import IdealArithmetic.Examples.NF10_0_21144617347_1.ClassGroupSaturated10_0_21144617347_1_2
import IdealArithmetic.Examples.NF10_0_21144617347_1.RelationIdeals10_0_21144617347_1F0
import IdealArithmetic.Examples.NF10_0_21144617347_1.RelationIdeals10_0_21144617347_1F1
import IdealArithmetic.Examples.NF10_0_21144617347_1.RelationIdeals10_0_21144617347_1F2
import IdealArithmetic.Examples.NF10_0_21144617347_1.RelationIdeals10_0_21144617347_1F3
import IdealArithmetic.Examples.NF10_0_21144617347_1.RelationIdeals10_0_21144617347_1F4
import IdealArithmetic.Examples.NF10_0_21144617347_1.RelationIdeals10_0_21144617347_1F5
import IdealArithmetic.Examples.NF10_0_21144617347_1.PrimesBelowCert10_0_21144617347_1
import Mathlib.NumberTheory.NumberField.ClassNumber
import IdealArithmetic.Signature.ResultantRecursive
import IdealArithmetic.DedekindProject.Discriminant
import IdealArithmetic.Generation.ClassGroupGeneration

set_option linter.all false

/- Number field `K(α)` with α root of polynomial `X^10 - 3*X^9 + 3*X^8 - 6*X^7 + 11*X^6 - 5*X^5 + 7*X^4 - 11*X^3 + 3*X + 1`.
Class group structure `[2]`, generated by class of ideals `[(5, a + 2)]`. -/

/- Ring of integers with basis `[1, a, a^2, a^3, a^4, a^5, a^6, a^7, a^8, 1/309*a^9 - 82/309*a^8 - 8/309*a^7 + 8/309*a^6 - 1/103*a^5 - 77/309*a^4 - 30/103*a^3 - 8/309*a^2 + 14/309*a + 133/309]` -/

open BigOperators Classical Matrix Polynomial Module

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible

instance K_field : Field K := by
  unfold K
  exact AdjoinRoot.instField

instance K_numberField : NumberField K := by
  unfold K
  exact AdjoinRoot.instNumberFieldRat

instance : Module ℚ K := Algebra.toModule
instance : @Algebra ℤ K CommRing.toCommSemiring CommRing.toCommSemiring.toSemiring := Ring.toIntAlgebra K
instance : @CharZero K CommRing.toCommSemiring.toNonAssocSemiring.toAddCommMonoidWithOne.toAddMonoidWithOne := charZero_of_expChar_one' K

lemma K_finrank : Module.finrank ℚ K = 10 := by
  unfold K
  erw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, T_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ [3, 103]
  · fin_cases hc
    exact @pMaximal_of_MaximalOrderCertificateOfUnramifiedLists K 3 _ IsAddTorsionFree.to_noZeroSMulDivisors_int _ O Om hm _ _ M3
    exact @pMaximal_of_MaximalOrderCertificateOfUnramifiedLists K 103 _ IsAddTorsionFree.to_noZeroSMulDivisors_int _ O Om hm _ _ M103
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [3, 103] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']

theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by rw [O_integral_closure] ; rfl

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance DD' : IsDedekindDomain O  := by
  rw [O_integral_closure]
  exact integralClosure.isDedekindDomain ℤ ℚ K

instance : Module.Free ℤ ↥O := Module.Free.of_basis B

instance  : IdemCommSemiring (Ideal O) := Ideal.instIdemCommSemiring
instance : CharZero O := SubsemiringClass.instCharZero O

def SturmRC : SturmBuilderOfList [[1, 3, 0, -11, 7, -5, 11, -6, 3, -3, 1], [3, 0, -33, 28, -25, 66, -42, 24, -27, 10], [-109, -270, 99, 686, -345, 52, -314, 108, 21], [1782, 4218, -2052, -11214, 7233, -1872, 5466, -2544], [25588, 20748, -151320, 86524, 32622, 14192, 6764], [276324, 136420, -1749256, 1458572, 87162, 86744], [-333838, 2044186, 2109060, -16211850, 14562245], [-7906175445, -3173816900, 50391315455, -46516559000], [2649218224255, 4092647616100, -6556095538845], [-14349539607487, 171640783381844], [-2018909208908907]] [1, 3, 0, -11, 7, -5, 11, -6, 3, -3, 1] [3, 0, -33, 28, -25, 66, -42, 24, -27, 10] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 10 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [100, 441, 6471936, 45751696, 7524521536, 212058979440025, 2163790261200481000000, 42982388714463310903934025, 29460558519933095433508840336]
  f := [1, 100, 441, 6471936, 45751696, 7524521536, 212058979440025, 2163790261200481000000, 42982388714463310903934025]
  epos := by decide
  fpos := by decide
  Q := [[-3, 10], [-1647, 210], [-389538, -53424], [73076472, -17207616], [641507080, 586736416], [2675555115090, 1263187380280], [20308795496153525, -677385528714955000], [-139994394150531601449475, 304967004942320234355000], [608388290328115189560755885, -1125293374213568460569730180]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 9 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^10 - 3*X^9 + 3*X^8 - 6*X^7 + 11*X^6 - 5*X^5 + 7*X^4 - 11*X^3 + 3*X + 1
  l := [1, 3, 0, -11, 7, -5, 11, -6, 3, -3, 1]
  hl := T_ofList
  hlz := by decide
  hz := by decide
  hAdj := Adj
  heq := O_integral_closure
  P := [[1, 3, 0, -11, 7, -5, 11, -6, 3, -3, 1], [3, 0, -33, 28, -25, 66, -42, 24, -27, 10], [-109, -270, 99, 686, -345, 52, -314, 108, 21], [1782, 4218, -2052, -11214, 7233, -1872, 5466, -2544], [25588, 20748, -151320, 86524, 32622, 14192, 6764], [276324, 136420, -1749256, 1458572, 87162, 86744], [-333838, 2044186, 2109060, -16211850, 14562245], [-7906175445, -3173816900, 50391315455, -46516559000], [2649218224255, 4092647616100, -6556095538845], [-14349539607487, 171640783381844], [-2018909208908907]]
  SB := SturmRC
  k := 0
  r := 5
  hr := by decide
  hreq := by decide 

def NPCU2 : pMaximalUnitsCertificateDvdT O 2 where 
 hp := by decide
 r := 4
 huc := by 
  erw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2, zeta3, zeta4]
 hu := fun i => 
  match i with 
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
  | 2 => isUnit_zeta3
  | 3 => isUnit_zeta4
 v := v
 m := 2
 hm := by norm_num
 hmv := v_pow_one
 t := 6
 hrle := by decide
 q := ![5, 7, 7, 23, 31, 29]
 hqP := by 
  intro i 
  match i with 
  | 0 => exact Sat2.hq5
  | 1 => exact Sat2.hq7
  | 2 => exact Sat2.hq7
  | 3 => exact Sat2.hq23
  | 4 => exact Sat2.hq31
  | 5 => exact Sat2.hq29
 I := ![Sat2.I0, Sat2.I1, Sat2.I2, Sat2.I3, Sat2.I4, Sat2.I5]
 hcard := fun i =>
  match i with  
  | 0 => Sat2.N0
  | 1 => Sat2.N1
  | 2 => Sat2.N2
  | 3 => Sat2.N3
  | 4 => Sat2.N4
  | 5 => Sat2.N5
 ζ := ![2, 3, 3, 5, 3, 2]
 hr := fun i =>
  match i with 
  | 0 => ((orderOf_of_IsOrderOf Sat2.R5) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf Sat2.R7) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf Sat2.R7) ▸ IsPrimitiveRoot.orderOf _)
  | 3 => ((orderOf_of_IsOrderOf Sat2.R23) ▸ IsPrimitiveRoot.orderOf _)
  | 4 => ((orderOf_of_IsOrderOf Sat2.R31) ▸ IsPrimitiveRoot.orderOf _)
  | 5 => ((orderOf_of_IsOrderOf Sat2.R29) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 M := ![![1, 0, 0, 0, 0], ![1, 0, 1, 1, 1], ![1, 0, 1, 0, 1], ![1, 1, 0, 0, 1], ![0, 0, 0, 1, 1], ![0, 1, 1, 1, 0]]
 hM1 := by 
  intro i j hj
  fin_cases i <;> interval_cases j 
  · erw [eq_of_DiscreteLogCertificate Sat2.Log00] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log01] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log02] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log03] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log10] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log11] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log12] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log13] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log20] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log21] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log22] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log23] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log30] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log31] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log32] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log33] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log40] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log41] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log42] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log43] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log50] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log51] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log52] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log53] ; decide
 hM2 := by 
  intro i 
  fin_cases i 
  · erw [eq_of_DiscreteLogCertificate Sat2.Log04] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log14] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log24] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log34] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log44] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log54] ; decide
 Minv := ![![1, 0, 0, 0, 0], ![1, 1, 1, 1, 1], ![1, 1, 0, 0, 1], ![0, 1, 1, 0, 0], ![0, 1, 1, 0, 1]]
 hInv := by decide

def NPSU2 : pSaturatedClassGroupCertificateDvdT 2 ![J0] ![2] where 
 topMaximalUnitsCertificateDvdT := NPCU2
 a := ![alpha0]
 γ := 1
 hc := by decide
 ψ := ![0]
 iψ := ![0] 
 hψ := by decide 
 hψn := by 
  intro i 
  fin_cases i 
  · decide
 h := fun i =>
  match i with 
  | 0 => by convert J0_pow2
 N := ![![0], ![1], ![0], ![0], ![0], ![0]]
 hM3 := by 
  intro (i : Fin 6) j
  match i , j with 
  | 0, 0 => exact Sat2.Log05
  | 1, 0 => exact Sat2.Log15
  | 2, 0 => exact Sat2.Log25
  | 3, 0 => exact Sat2.Log35
  | 4, 0 => exact Sat2.Log45
  | 5, 0 => exact Sat2.Log55
 hDl := by decide 
 NInv := ![![1, 0, 0, 0, 0, 0], ![1, 0, 1, 0, 1, 1], ![1, 0, 0, 1, 1, 1], ![0, 0, 1, 1, 0, 1], ![0, 0, 1, 1, 1, 1], ![0, 1, 0, 1, 0, 1]]
 hN := by decide 

lemma T_discr : T.discr = -2018909208908907 :=  by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  rw [T_ofList]

theorem K_discr : NumberField.discr K = -21144617347 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl

lemma K_nrComplexPlaces : NumberField.InfinitePlace.nrComplexPlaces K = 5 := by
  rw [nrComplexPlaces_of_RankUnitsCertificate RC]
  rfl

lemma K_nrRealPlaces : NumberField.InfinitePlace.nrRealPlaces K = 0 := by
  rw [nrRealPlaces_of_RankUnitsCertificate RC]
  rfl

theorem K_minowski : minkowskiBoundFB K ≤ (176.57862747676748 : ℝ) := by
  refine K_minkowski_decimal _ ?_
  erw [K_nrComplexPlaces, K_discr, K_finrank]
  have hraux: √21144617347 ≤ 145411.888613 := by
      refine Real.sqrt_le_iff.mpr ?_
      norm_num
  have : 0.00036288 * √21144617347 ≤ 52.777066 := by
    refine le_trans (mul_le_mul_of_nonneg (by rfl) hraux (by norm_num) (by norm_num)) ?_
    norm_num
  norm_num
  try {linarith}

def s := ![7, 7, 7, 7, 7, 5]

def BM : (i : Fin 6) → Fin (e i) → (Fin 1 → ℕ) := by 
  rintro ⟨i, hi⟩ 
  interval_cases i 
  exact ![![1], ![1], ![1], ![1], ![1], ![1]]
  exact ![![1], ![1], ![1], ![1], ![1]]
  exact ![![1], ![1]]
  exact ![![1], ![0], ![0], ![1], ![1], ![0], ![0], ![1], ![1]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0]]

lemma primesGenerationBelow : {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < 177} ⊆ Set.range (Fin.addCasesIter e 𝔭) := by
  rw [← cert_eq_𝔭]
  refine le_primes_below_bound_of_PrimesBelowBoundCertificate_le_of_eq (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv PB177

def 𝔭' : Fin 32 → nonZeroDivisors (Ideal O) := by
  intro i
  have : PB177.β i ∈ List.ofFn PB177.β := by
    simp only [List.mem_ofFn, exists_apply_eq_apply]
  refine Ideal.toNonZeroDivisorOfNeZero ((PB177.β) i)
    (fun hc => ((zero_ne_mem_of_PrimesBelowCertificate_Fn _ PB177) (hc ▸ this) ))

def J : Fin 1 → Ideal O := ![J0]

def J' :  Fin 1 → nonZeroDivisors (Ideal O) := by
  refine fun i => Ideal.toNonZeroDivisorOfNeZero (J i) (?_ )
  unfold J
  rw [← Submodule.zero_eq_bot, ← pow_ne_zero_iff (n := ![2] i) (by fin_cases i <;> decide) , NPSU2.h]
  simp only [ Submodule.zero_eq_bot, ne_eq, Ideal.span_singleton_eq_bot, NPSU2]
  fin_cases i
  · dsimp [alpha0] ; rw [(LinearEquiv.map_eq_zero_iff B.equivFun.symm)] ; decide 

lemma 𝔭'_apply : ∀ (i : Fin 32), ↑(𝔭' i) = (Fin.addCasesIter e 𝔭) i := by
  intro i
  rw [← cert_eq_𝔭]
  rfl

lemma J'_apply : ∀ (i : Fin 1), ↑(J' i) = J i := by
  intro i
  rfl

lemma relations_proof0 (i : Fin 6) : IsInClass O J (𝔭 0 i) (BM 0 i) := by
  show IsInClass O J (𝔭 0 i) (![![1], ![1], ![1], ![1], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R3N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R3N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R5N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R5N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R7N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R7N3

lemma relations_proof1 (i : Fin 5) : IsInClass O J (𝔭 1 i) (BM 1 i) := by
  show IsInClass O J (𝔭 1 i) (![![1], ![1], ![1], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R23N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R29N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R29N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R31N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R31N2

lemma relations_proof2 (i : Fin 2) : IsInClass O J (𝔭 2 i) (BM 2 i) := by
  show IsInClass O J (𝔭 2 i) (![![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R71N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R71N3

lemma relations_proof3 (i : Fin 9) : IsInClass O J (𝔭 3 i) (BM 3 i) := by
  show IsInClass O J (𝔭 3 i) (![![1], ![0], ![0], ![1], ![1], ![0], ![0], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R101N1
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R103N4
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R103N5
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R107N4
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R107N5

lemma relations_proof4 (i : Fin 6) : IsInClass O J (𝔭 4 i) (BM 4 i) := by
  show IsInClass O J (𝔭 4 i) (![![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof5 (i : Fin 4) : IsInClass O J (𝔭 5 i) (BM 5 i) := by
  show IsInClass O J (𝔭 5 i) (![![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

theorem class_group_generator : Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (J' i))) = ⊤ := by
  refine subgroup_closure_eq_classGroup'' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv
      𝔭'_apply J'_apply ?_ primesGenerationBelow (Fin.addCasesIter e BM) ?_
  · refine lt_of_le_of_lt K_minowski ?_
    norm_num
  · refine forall_addCasesIter_prop 𝔭 BM (IsInClass O J) ?_
    rintro ⟨i, hi⟩
    interval_cases i
    · exact relations_proof0
    · exact relations_proof1
    · exact relations_proof2
    · exact relations_proof3
    · exact relations_proof4
    · exact relations_proof5

def ClassGroupO_equiv : (∀ i : Fin 1 , (ZMod (![2] i))) ≃+ Additive (ClassGroup O) := by
  haveI : ∀ (i : Fin 1), NeZero (![2] i) := by
    intro i
    fin_cases i <;>  exact {out := by decide}
  refine ClassGroup_equiv_of_pSaturatedCertificate J'_apply NPSU2.h class_group_generator ?_
  rintro ⟨p, hp1, hp2⟩
  have : ∏ i, ![2] i = ∏ i, (![2] i) ^ (![1] i)  := by decide
  rw [this] at hp2
  have hp_cases : p ∈ [2] := by
    obtain ⟨j ,hj1, hj2⟩  := Prime.exists_mem_finset_dvd (Nat.prime_iff.mp hp1) hp2
    show p ∈ List.ofFn ![2]
    rw [(Nat.prime_dvd_prime_iff_eq hp1 ?_).1 (Nat.Prime.dvd_of_dvd_pow hp1 hj2), List.mem_ofFn]
    exact ⟨j, rfl⟩
    fin_cases j <;> decide
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hp_cases
  by_cases h : p = 2
  simp_rw [h] ; left
  exact NPSU2
  omega

def class_group_equiv : (∀ i : Fin 1 , (ZMod (![2] i))) ≃+ Additive (ClassGroup (NumberField.RingOfIntegers K)) := by
 refine AddEquiv.trans ClassGroupO_equiv ?_
 exact MulEquiv.toAdditive (ClassGroup.congr
    ((Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv))

theorem class_number_K_eq_2 : NumberField.classNumber K = 2 := by
  unfold NumberField.classNumber
  rw [Fintype.card_eq_nat_card, ← Nat.card_congr (Additive.toMul),
    Nat.card_congr (class_group_equiv).symm.toEquiv, Nat.card_pi]
  simp [Fin.isValue, Fin.prod_succ]
  try decide
