import IdealArithmetic.Saturation.PrincipalityCertificate
import IdealArithmetic.Examples.NF3_3_376329_1.PrimesBelowCert3_3_376329_1
import Mathlib.NumberTheory.NumberField.ClassNumber
import IdealArithmetic.Signature.ResultantRecursive
import IdealArithmetic.DedekindProject.Discriminant
import IdealArithmetic.Generation.ClassGroupGeneration

set_option linter.all false

/- Number field `K(α)` with α root of polynomial `X^3 - X^2 - 174*X + 912`.
Class group structure `[]`, generated by class of ideals `[]`. -/

/- Ring of integers with basis `[1, a, 1/2*a^2 - 1/2*a]` -/

open BigOperators Classical Matrix Polynomial Module

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible

instance K_field : Field K := by
  unfold K
  exact AdjoinRoot.instField

instance K_numberField : NumberField K := by
  unfold K
  exact AdjoinRoot.instNumberFieldRat

instance : Module ℚ K := Algebra.toModule
instance : @Algebra ℤ K CommRing.toCommSemiring CommRing.toCommSemiring.toSemiring := Ring.toIntAlgebra K
instance : @CharZero K CommRing.toCommSemiring.toNonAssocSemiring.toAddCommMonoidWithOne.toAddMonoidWithOne := charZero_of_expChar_one' K

lemma K_finrank : Module.finrank ℚ K = 3 := by
  unfold K
  erw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, T_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ [2]
  · fin_cases hc
    exact @pMaximal_of_MaximalOrderCertificateOfUnramifiedLists K 2 _ IsAddTorsionFree.to_noZeroSMulDivisors_int _ O Om hm _ _ M2
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [2] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']

theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by rw [O_integral_closure] ; rfl

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance DD' : IsDedekindDomain O  := by
  rw [O_integral_closure]
  exact integralClosure.isDedekindDomain ℤ ℚ K

instance : Module.Free ℤ ↥O := Module.Free.of_basis B

instance  : IdemCommSemiring (Ideal O) := Ideal.instIdemCommSemiring
instance : CharZero O := SubsemiringClass.instCharZero O

def SturmRC : SturmBuilderOfList [[912, -174, -1, 1], [-174, -2, 3], [-8034, 1046], [1505316]] [912, -174, -1, 1] [-174, -2, 3] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 3 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [9, 1094116]
  f := [1, 9]
  epos := by decide
  fpos := by decide
  Q := [[-1, 3], [22010, 3138]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 2 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^3 - X^2 - 174*X + 912
  l := [912, -174, -1, 1]
  hl := T_ofList
  hlz := by decide
  hz := by decide
  hAdj := Adj
  heq := O_integral_closure
  P := [[912, -174, -1, 1], [-174, -2, 3], [-8034, 1046], [1505316]]
  SB := SturmRC
  k := 3
  r := 3
  hr := by decide
  hreq := by decide 


lemma T_discr : T.discr = 1505316 :=  by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  rw [T_ofList]

theorem K_discr : NumberField.discr K = 376329 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl

lemma K_nrComplexPlaces : NumberField.InfinitePlace.nrComplexPlaces K = 0 := by
  rw [nrComplexPlaces_of_RankUnitsCertificate RC]
  rfl

lemma K_nrRealPlaces : NumberField.InfinitePlace.nrRealPlaces K = 3 := by
  rw [nrRealPlaces_of_RankUnitsCertificate RC]
  rfl

theorem K_minowski : minkowskiBoundFB K ≤ (136.33368887375426 : ℝ) := by
  refine K_minkowski_decimal _ ?_
  erw [K_nrComplexPlaces, K_discr, K_finrank]
  have hraux: √376329 ≤ 613.45661 := by
      refine Real.sqrt_le_iff.mpr ?_
      norm_num
  have : 0.2222222222222222 * √376329 ≤ 136.333691 := by
    refine le_trans (mul_le_mul_of_nonneg (by rfl) hraux (by norm_num) (by norm_num)) ?_
    norm_num
  norm_num
  try {linarith}

def s := ![11, 11, 10]

def BM : (i : Fin 3) → Fin (e i) → (Fin 1 → ℕ) := by 
  rintro ⟨i, hi⟩ 
  interval_cases i 
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]
  exact ![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]]

lemma primesGenerationBelow : {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < 137} ⊆ Set.range (Fin.addCasesIter e 𝔭) := by
  rw [← cert_eq_𝔭]
  refine le_primes_below_bound_of_PrimesBelowBoundCertificate_le_of_eq (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv PB137

def 𝔭' : Fin 38 → nonZeroDivisors (Ideal O) := by
  intro i
  have : PB137.β i ∈ List.ofFn PB137.β := by
    simp only [List.mem_ofFn, exists_apply_eq_apply]
  refine Ideal.toNonZeroDivisorOfNeZero ((PB137.β) i)
    (fun hc => ((zero_ne_mem_of_PrimesBelowCertificate_Fn _ PB137) (hc ▸ this) ))

def J : Fin 1 → Ideal O := ![⊤]

def J' :  Fin 1 → nonZeroDivisors (Ideal O) := by
  refine fun i => Ideal.toNonZeroDivisorOfNeZero (J i) (?_ )
  unfold J
  simp 

lemma 𝔭'_apply : ∀ (i : Fin 38), ↑(𝔭' i) = (Fin.addCasesIter e 𝔭) i := by
  intro i
  rw [← cert_eq_𝔭]
  rfl

lemma J'_apply : ∀ (i : Fin 1), ↑(J' i) = J i := by
  intro i
  rfl

lemma relations_proof0 (i : Fin 12) : IsInClass O J (𝔭 0 i) (BM 0 i) := by
  show IsInClass O J (𝔭 0 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof1 (i : Fin 14) : IsInClass O J (𝔭 1 i) (BM 1 i) := by
  show IsInClass O J (𝔭 1 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

lemma relations_proof2 (i : Fin 12) : IsInClass O J (𝔭 2 i) (BM 2 i) := by
  show IsInClass O J (𝔭 2 i) (![![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0], ![0]] i)
  unfold IsInClass
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl
  · refine ideal_mem_principal_class''' (by decide) J rfl rfl

theorem class_group_generator : Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (J' i))) = ⊤ := by
  refine subgroup_closure_eq_classGroup'' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv
      𝔭'_apply J'_apply ?_ primesGenerationBelow (Fin.addCasesIter e BM) ?_
  · refine lt_of_le_of_lt K_minowski ?_
    norm_num
  · refine forall_addCasesIter_prop 𝔭 BM (IsInClass O J) ?_
    rintro ⟨i, hi⟩
    interval_cases i
    · exact relations_proof0
    · exact relations_proof1
    · exact relations_proof2

def ClassGroupO_equiv : (∀ i : Fin 1 , (ZMod (![1] i))) ≃+ Additive (ClassGroup O) := by
  haveI : ∀ (i : Fin 1), NeZero (![1] i) := by
    intro i
    fin_cases i <;>  exact {out := by decide}
  refine ClassGroup_equiv_of_pSaturatedCertificate J'_apply (a := ![1]) (n := ![1])
    (by simp [J]; exact Eq.symm Ideal.span_singleton_one) class_group_generator ?_
  rintro ⟨p, hp1, hp2⟩
  simp at hp2
  exact (Nat.Prime.ne_one hp1 hp2).elim

def class_group_equiv : (∀ i : Fin 1 , (ZMod (![1] i))) ≃+ Additive (ClassGroup (NumberField.RingOfIntegers K)) := by
 refine AddEquiv.trans ClassGroupO_equiv ?_
 exact MulEquiv.toAdditive (ClassGroup.congr
    ((Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv))

theorem class_number_K_eq_1 : NumberField.classNumber K = 1 := by
  unfold NumberField.classNumber
  rw [Fintype.card_eq_nat_card, ← Nat.card_congr (Additive.toMul),
    Nat.card_congr (class_group_equiv).symm.toEquiv, Nat.card_pi]
  simp [Fin.isValue, Fin.prod_succ]
  try decide
