import IdealArithmetic.Examples.NF4_4_54381317_1.ClassGroupSaturated4_4_54381317_1_3
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F0
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F1
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F2
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F3
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F4
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F5
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F6
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F7
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F8
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F9
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F10
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F11
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F12
import IdealArithmetic.Examples.NF4_4_54381317_1.PrimesBelowCert4_4_54381317_1
import Mathlib.NumberTheory.NumberField.ClassNumber
import IdealArithmetic.Signature.ResultantRecursive
import IdealArithmetic.DedekindProject.Discriminant
import IdealArithmetic.Generation.ClassGroupGeneration

set_option linter.all false

/- Number field `K(α)` with α root of polynomial `X^4 - X^3 - 80*X^2 - 332*X - 383`.
Class group structure `[3, 3]`, generated by class of ideals `[(3, a - 1), (3, a + 1)]`. -/

/- Ring of integers with basis `(1, a, a^2, a^3)` -/

open BigOperators Classical Matrix Polynomial Module

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible

instance K_field : Field K := by
  unfold K
  exact AdjoinRoot.instField

instance K_numberField : NumberField K := by
  unfold K
  exact AdjoinRoot.instNumberFieldRat

instance : Module ℚ K := Algebra.toModule
instance : @Algebra ℤ K CommRing.toCommSemiring CommRing.toCommSemiring.toSemiring := Ring.toIntAlgebra K
instance : @CharZero K CommRing.toCommSemiring.toNonAssocSemiring.toAddCommMonoidWithOne.toAddMonoidWithOne := charZero_of_expChar_one' K

lemma K_finrank : Module.finrank ℚ K = 4 := by
  unfold K
  erw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, T_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ []
  · fin_cases hc
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']

theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by rw [O_integral_closure] ; rfl

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance DD' : IsDedekindDomain O  := by
  rw [O_integral_closure]
  exact integralClosure.isDedekindDomain ℤ ℚ K

instance : Module.Free ℤ ↥O := Module.Free.of_basis B

instance  : IdemCommSemiring (Ideal O) := Ideal.instIdemCommSemiring
instance : CharZero O := SubsemiringClass.instCharZero O

def SturmRC : SturmBuilderOfList [[-383, -332, -80, -1, 1], [-332, -160, -3, 4], [6460, 4144, 643], [1107673, 380140], [54381317]] [-383, -332, -80, -1, 1] [-332, -160, -3, 4] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [16, 413449, 144506419600]
  f := [1, 16, 413449]
  epos := by decide
  fpos := by decide
  Q := [[-1, 4], [-18505, 2572], [863066421, 244430020]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 3 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^4 - X^3 - 80*X^2 - 332*X - 383
  l := [-383, -332, -80, -1, 1]
  hl := T_ofList
  hlz := by decide
  hz := by decide
  hAdj := Adj
  heq := O_integral_closure
  P := [[-383, -332, -80, -1, 1], [-332, -160, -3, 4], [6460, 4144, 643], [1107673, 380140], [54381317]]
  SB := SturmRC
  k := 4
  r := 4
  hr := by decide
  hreq := by decide 

def IC : Ideal O := Ideal.span (Set.range (fun i ↦ B.equivFun.symm (![![5, 0, 0, 0], ![2, 1, 0, 0]] i)))

def AIC: IdealEqSpanCertificate timesTableO IC
 ![![5, 0, 0, 0], ![2, 1, 0, 0]] 
 ![![5, 0, 0, 0], ![2, 1, 0, 0], ![1, 0, 1, 0], ![3, 0, 0, 1]] where
  T := Table
  heq := timesTableT_eq_Table
  hieq := rfl 
  M :=![![![5, 0, 0, 0], ![0, 5, 0, 0], ![0, 0, 5, 0], ![0, 0, 0, 5]], ![![2, 1, 0, 0], ![0, 2, 1, 0], ![0, 0, 2, 1], ![383, 332, 80, 3]]]
  hmulB := by decide
  f := ![![![3, 1, 6, 3], ![-5, 0, -15, 0]], ![![-2, -3, 5, 3], ![6, 5, -15, 0]], ![![-1, -1, 0, 0], ![3, 1, 0, 0]], ![![1, -1, 3, 2], ![-1, 3, -9, 0]]]
  g := ![![![1, 0, 0, 0], ![-2, 5, 0, 0], ![-1, 0, 5, 0], ![-3, 0, 0, 5]], ![![0, 1, 0, 0], ![-1, 2, 1, 0], ![-1, 0, 2, 1], ![-74, 332, 80, 3]]]
  hle1 := by decide
  hle2 := by decide

 lemma ne_dvd_torsion3 : ¬3 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by 
  refine prime_not_dvd_torsion_of_not_dvd (by decide) IC
     (ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate AIC))
     (by decide) (by decide)

def NPCU3 : pMaximalUnitsCertificateNDvdT O 3 where 
 hp := by decide
 r := 3
 huc := by 
  erw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2, zeta3]
 hu := fun i => 
  match i with 
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
  | 2 => isUnit_zeta3
 t := 5
 hrle := by decide
 q := ![43, 43, 151, 61, 97]
 hqP := by 
  intro i 
  match i with 
  | 0 => exact Sat3.hq43
  | 1 => exact Sat3.hq43
  | 2 => exact Sat3.hq151
  | 3 => exact Sat3.hq61
  | 4 => exact Sat3.hq97
 I := ![Sat3.I0, Sat3.I1, Sat3.I2, Sat3.I3, Sat3.I4]
 hcard := fun i =>
  match i with  
  | 0 => Sat3.N0
  | 1 => Sat3.N1
  | 2 => Sat3.N2
  | 3 => Sat3.N3
  | 4 => Sat3.N4
 ζ := ![3, 3, 6, 2, 5]
 hr := fun i =>
  match i with 
  | 0 => ((orderOf_of_IsOrderOf Sat3.R43) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf Sat3.R43) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf Sat3.R151) ▸ IsPrimitiveRoot.orderOf _)
  | 3 => ((orderOf_of_IsOrderOf Sat3.R61) ▸ IsPrimitiveRoot.orderOf _)
  | 4 => ((orderOf_of_IsOrderOf Sat3.R97) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 hpndvdt := ne_dvd_torsion3
 M := ![![0, 1, 1], ![0, 1, 2], ![2, 2, 1], ![0, 0, 0], ![0, 2, 1]]
 hM1 := by 
  intro i j
  fin_cases i <;> fin_cases j 
  · erw [eq_of_DiscreteLogCertificate Sat3.Log00] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log01] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log02] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log10] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log11] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log12] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log20] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log21] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log22] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log30] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log31] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log32] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log40] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log41] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log42] ; decide
 Minv := ![![0, 2, 2], ![2, 2, 0], ![2, 1, 0]] 
 hInv := by decide

def NPSU3 : pSaturatedClassGroupCertificateNDvdT 3 ![J0, J1] ![3, 3] where 
 topMaximalUnitsCertificateNDvdT := NPCU3
 a := ![alpha0,alpha1]
 γ := 2
 hc := by decide
 ψ := ![0, 1]
 iψ := ![0, 1] 
 hψ := by decide 
 hψn := by 
  intro i 
  fin_cases i 
  · decide
  · decide
 h := fun i =>
  match i with 
  | 0 => by convert J0_pow3
  | 1 => by convert J1_pow3
 N := ![![0, 1], ![1, 0], ![2, 0], ![1, 1], ![0, 0]]
 hM2 := by 
  intro (i : Fin 5) j
  match i , j with 
  | 0, 0 => exact Sat3.Log03
  | 0, 1 => exact Sat3.Log04
  | 1, 0 => exact Sat3.Log13
  | 1, 1 => exact Sat3.Log14
  | 2, 0 => exact Sat3.Log23
  | 2, 1 => exact Sat3.Log24
  | 3, 0 => exact Sat3.Log33
  | 3, 1 => exact Sat3.Log34
  | 4, 0 => exact Sat3.Log43
  | 4, 1 => exact Sat3.Log44
 hDl := by decide 
 NInv := ![![0, 2, 2, 0, 0], ![2, 2, 0, 1, 0], ![2, 2, 0, 1, 1], ![0, 1, 0, 0, 1], ![0, 2, 0, 1, 2]]
 hN := by decide 

lemma T_discr : T.discr = 54381317 :=  by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  rw [T_ofList]

theorem K_discr : NumberField.discr K = 54381317 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl

lemma K_nrComplexPlaces : NumberField.InfinitePlace.nrComplexPlaces K = 0 := by
  rw [nrComplexPlaces_of_RankUnitsCertificate RC]
  rfl

lemma K_nrRealPlaces : NumberField.InfinitePlace.nrRealPlaces K = 4 := by
  rw [nrRealPlaces_of_RankUnitsCertificate RC]
  rfl

theorem K_minowski : minkowskiBoundFB K ≤ (691.357086451742 : ℝ) := by
  refine K_minkowski_decimal _ ?_
  erw [K_nrComplexPlaces, K_discr, K_finrank]
  have hraux: √54381317 ≤ 7374.368931999999 := by
      refine Real.sqrt_le_iff.mpr ?_
      norm_num
  have : 0.09375 * √54381317 ≤ 691.357087 := by
    refine le_trans (mul_le_mul_of_nonneg (by rfl) hraux (by norm_num) (by norm_num)) ?_
    norm_num
  norm_num
  try {linarith}

def s := ![10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 5]

def BM : (i : Fin 13) → Fin (e i) → (Fin 2 → ℕ) := by 
  rintro ⟨i, hi⟩ 
  interval_cases i 
  exact ![![0, 0], ![2, 2], ![0, 1], ![1, 0], ![1, 1], ![2, 0], ![0, 2], ![2, 1], ![1, 2], ![1, 1], ![2, 2], ![2, 1], ![1, 2], ![1, 1], ![1, 1], ![2, 2], ![1, 1], ![1, 2], ![2, 1]]
  exact ![![0, 2], ![2, 0], ![1, 2], ![2, 1], ![2, 2]]
  exact ![![2, 2], ![2, 2]]
  exact ![![1, 1], ![1, 1], ![0, 1], ![1, 0], ![1, 0], ![0, 1], ![2, 0], ![0, 2], ![2, 1], ![1, 2], ![2, 1], ![1, 2]]
  exact ![![0, 2], ![1, 0], ![0, 1], ![2, 0], ![1, 2], ![2, 1], ![1, 2], ![2, 1], ![2, 1], ![1, 2]]
  exact ![![0, 0], ![0, 0], ![1, 0], ![0, 2], ![2, 0], ![0, 1]]
  exact ![![1, 0], ![0, 1], ![0, 1], ![0, 2], ![2, 0], ![1, 0], ![0, 0], ![0, 0]]
  exact ![![0, 0], ![0, 0], ![2, 2], ![2, 2], ![2, 0], ![0, 2], ![0, 0], ![0, 0], ![2, 0], ![0, 1], ![1, 0], ![0, 2], ![0, 1], ![1, 0]]
  exact ![![1, 0], ![0, 1], ![2, 2], ![2, 2], ![1, 1], ![1, 1], ![1, 2], ![2, 1], ![1, 2], ![2, 1], ![2, 0], ![0, 2], ![2, 2], ![0, 2], ![2, 2], ![2, 0]]
  exact ![![0, 2], ![2, 0], ![1, 1], ![0, 1], ![1, 1], ![1, 0], ![0, 0], ![0, 0], ![1, 2], ![2, 1], ![1, 2], ![2, 1], ![2, 1], ![1, 2]]
  exact ![![2, 0], ![0, 2], ![2, 0], ![0, 2], ![1, 2], ![2, 1]]
  exact ![![2, 1], ![1, 2], ![1, 2], ![2, 1], ![1, 2], ![2, 1], ![1, 2], ![2, 1], ![1, 1], ![1, 1]]
  exact ![![1, 1], ![1, 1], ![0, 2], ![2, 0], ![1, 0], ![0, 1], ![0, 1], ![1, 0], ![2, 1], ![1, 2]]

lemma primesGenerationBelow : {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < 692} ⊆ Set.range (Fin.addCasesIter e 𝔭) := by
  rw [← cert_eq_𝔭]
  refine le_primes_below_bound_of_PrimesBelowBoundCertificate_le_of_eq (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv PB692

def 𝔭' : Fin 132 → nonZeroDivisors (Ideal O) := by
  intro i
  have : PB692.β i ∈ List.ofFn PB692.β := by
    simp only [List.mem_ofFn, exists_apply_eq_apply]
  refine Ideal.toNonZeroDivisorOfNeZero ((PB692.β) i)
    (fun hc => ((zero_ne_mem_of_PrimesBelowCertificate_Fn _ PB692) (hc ▸ this) ))

def J : Fin 2 → Ideal O := ![J0,J1]

def J' :  Fin 2 → nonZeroDivisors (Ideal O) := by
  refine fun i => Ideal.toNonZeroDivisorOfNeZero (J i) (?_ )
  unfold J
  rw [← Submodule.zero_eq_bot, ← pow_ne_zero_iff (n := ![3, 3] i) (by fin_cases i <;> decide) , NPSU3.h]
  simp only [ Submodule.zero_eq_bot, ne_eq, Ideal.span_singleton_eq_bot, NPSU3]
  fin_cases i
  · dsimp [alpha0] ; rw [(LinearEquiv.map_eq_zero_iff B.equivFun.symm)] ; decide 
  · dsimp [alpha1] ; rw [(LinearEquiv.map_eq_zero_iff B.equivFun.symm)] ; decide 

lemma 𝔭'_apply : ∀ (i : Fin 132), ↑(𝔭' i) = (Fin.addCasesIter e 𝔭) i := by
  intro i
  rw [← cert_eq_𝔭]
  rfl

lemma J'_apply : ∀ (i : Fin 2), ↑(J' i) = J i := by
  intro i
  rfl

lemma relations_proof0 (i : Fin 19) : IsInClass O J (𝔭 0 i) (BM 0 i) := by
  show IsInClass O J (𝔭 0 i) (![![0, 0], ![2, 2], ![0, 1], ![1, 0], ![1, 1], ![2, 0], ![0, 2], ![2, 1], ![1, 2], ![1, 1], ![2, 2], ![2, 1], ![1, 2], ![1, 1], ![1, 1], ![2, 2], ![1, 1], ![1, 2], ![2, 1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R3N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R3N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R3N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R5N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R5N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R5N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R7N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R7N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R11N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R11N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R13N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R13N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R17N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R17N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R19N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R19N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R23N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R23N1

lemma relations_proof1 (i : Fin 5) : IsInClass O J (𝔭 1 i) (BM 1 i) := by
  show IsInClass O J (𝔭 1 i) (![![0, 2], ![2, 0], ![1, 2], ![2, 1], ![2, 2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R43N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R43N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R53N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R53N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R61N1

lemma relations_proof2 (i : Fin 2) : IsInClass O J (𝔭 2 i) (BM 2 i) := by
  show IsInClass O J (𝔭 2 i) (![![2, 2], ![2, 2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R97N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R97N2

lemma relations_proof3 (i : Fin 12) : IsInClass O J (𝔭 3 i) (BM 3 i) := by
  show IsInClass O J (𝔭 3 i) (![![1, 1], ![1, 1], ![0, 1], ![1, 0], ![1, 0], ![0, 1], ![2, 0], ![0, 2], ![2, 1], ![1, 2], ![2, 1], ![1, 2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R149N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R149N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R149N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R149N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R151N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R151N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R167N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R167N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R173N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R173N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R173N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R173N3

lemma relations_proof4 (i : Fin 10) : IsInClass O J (𝔭 4 i) (BM 4 i) := by
  show IsInClass O J (𝔭 4 i) (![![0, 2], ![1, 0], ![0, 1], ![2, 0], ![1, 2], ![2, 1], ![1, 2], ![2, 1], ![2, 1], ![1, 2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R181N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R181N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R181N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R181N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R193N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R193N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R193N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R193N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R229N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R229N1

lemma relations_proof5 (i : Fin 6) : IsInClass O J (𝔭 5 i) (BM 5 i) := by
  show IsInClass O J (𝔭 5 i) (![![0, 0], ![0, 0], ![1, 0], ![0, 2], ![2, 0], ![0, 1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R277N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R277N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R277N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R277N3

lemma relations_proof6 (i : Fin 8) : IsInClass O J (𝔭 6 i) (BM 6 i) := by
  show IsInClass O J (𝔭 6 i) (![![1, 0], ![0, 1], ![0, 1], ![0, 2], ![2, 0], ![1, 0], ![0, 0], ![0, 0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R307N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R307N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R311N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R311N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R311N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R311N3
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)

lemma relations_proof7 (i : Fin 14) : IsInClass O J (𝔭 7 i) (BM 7 i) := by
  show IsInClass O J (𝔭 7 i) (![![0, 0], ![0, 0], ![2, 2], ![2, 2], ![2, 0], ![0, 2], ![0, 0], ![0, 0], ![2, 0], ![0, 1], ![1, 0], ![0, 2], ![0, 1], ![1, 0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R367N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R367N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R373N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R373N2
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R401N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R401N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R401N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R401N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R409N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R409N2

lemma relations_proof8 (i : Fin 16) : IsInClass O J (𝔭 8 i) (BM 8 i) := by
  show IsInClass O J (𝔭 8 i) (![![1, 0], ![0, 1], ![2, 2], ![2, 2], ![1, 1], ![1, 1], ![1, 2], ![2, 1], ![1, 2], ![2, 1], ![2, 0], ![0, 2], ![2, 2], ![0, 2], ![2, 2], ![2, 0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R421N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R421N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R431N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R431N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R433N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R433N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R439N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R439N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R449N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R449N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R457N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R457N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R463N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R463N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R463N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R463N3

lemma relations_proof9 (i : Fin 14) : IsInClass O J (𝔭 9 i) (BM 9 i) := by
  show IsInClass O J (𝔭 9 i) (![![0, 2], ![2, 0], ![1, 1], ![0, 1], ![1, 1], ![1, 0], ![0, 0], ![0, 0], ![1, 2], ![2, 1], ![1, 2], ![2, 1], ![2, 1], ![1, 2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R467N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R467N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R491N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R491N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R491N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R491N3
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · refine ideal_mem_principal_class''' (by decide) J rfl (by unfold_prod)
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R509N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R509N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R541N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R541N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R541N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R541N3

lemma relations_proof10 (i : Fin 6) : IsInClass O J (𝔭 10 i) (BM 10 i) := by
  show IsInClass O J (𝔭 10 i) (![![2, 0], ![0, 2], ![2, 0], ![0, 2], ![1, 2], ![2, 1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R557N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R557N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R587N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R587N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R593N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R593N2

lemma relations_proof11 (i : Fin 10) : IsInClass O J (𝔭 11 i) (BM 11 i) := by
  show IsInClass O J (𝔭 11 i) (![![2, 1], ![1, 2], ![1, 2], ![2, 1], ![1, 2], ![2, 1], ![1, 2], ![2, 1], ![1, 1], ![1, 1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R607N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R607N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R617N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R617N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R617N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R617N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R619N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R619N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R631N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R631N2

lemma relations_proof12 (i : Fin 10) : IsInClass O J (𝔭 12 i) (BM 12 i) := by
  show IsInClass O J (𝔭 12 i) (![![1, 1], ![1, 1], ![0, 2], ![2, 0], ![1, 0], ![0, 1], ![0, 1], ![1, 0], ![2, 1], ![1, 2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R661N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R661N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R673N0
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R673N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R673N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R673N3
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R683N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R683N2
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R691N1
  · convert exists_ne_zero_mul_of_relation (by decide) (by decide) R691N2

theorem class_group_generator : Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (J' i))) = ⊤ := by
  refine subgroup_closure_eq_classGroup'' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv
      𝔭'_apply J'_apply ?_ primesGenerationBelow (Fin.addCasesIter e BM) ?_
  · refine lt_of_le_of_lt K_minowski ?_
    norm_num
  · refine forall_addCasesIter_prop 𝔭 BM (IsInClass O J) ?_
    rintro ⟨i, hi⟩
    interval_cases i
    · exact relations_proof0
    · exact relations_proof1
    · exact relations_proof2
    · exact relations_proof3
    · exact relations_proof4
    · exact relations_proof5
    · exact relations_proof6
    · exact relations_proof7
    · exact relations_proof8
    · exact relations_proof9
    · exact relations_proof10
    · exact relations_proof11
    · exact relations_proof12

def ClassGroupO_equiv : (∀ i : Fin 2 , (ZMod (![3, 3] i))) ≃+ Additive (ClassGroup O) := by
  haveI : ∀ (i : Fin 2), NeZero (![3, 3] i) := by
    intro i
    fin_cases i <;>  exact {out := by decide}
  refine ClassGroup_equiv_of_pSaturatedCertificate J'_apply NPSU3.h class_group_generator ?_
  rintro ⟨p, hp1, hp2⟩
  have : ∏ i, ![3, 3] i = ∏ i, (![3] i) ^ (![2] i)  := by decide
  rw [this] at hp2
  have hp_cases : p ∈ [3] := by
    obtain ⟨j ,hj1, hj2⟩  := Prime.exists_mem_finset_dvd (Nat.prime_iff.mp hp1) hp2
    show p ∈ List.ofFn ![3]
    rw [(Nat.prime_dvd_prime_iff_eq hp1 ?_).1 (Nat.Prime.dvd_of_dvd_pow hp1 hj2), List.mem_ofFn]
    exact ⟨j, rfl⟩
    fin_cases j <;> decide
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hp_cases
  by_cases h : p = 3
  simp_rw [h] ; right
  exact NPSU3
  omega

def class_group_equiv : (∀ i : Fin 2 , (ZMod (![3, 3] i))) ≃+ Additive (ClassGroup (NumberField.RingOfIntegers K)) := by
 refine AddEquiv.trans ClassGroupO_equiv ?_
 exact MulEquiv.toAdditive (ClassGroup.congr
    ((Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv))

theorem class_number_K_eq_9 : NumberField.classNumber K = 9 := by
  unfold NumberField.classNumber
  rw [Fintype.card_eq_nat_card, ← Nat.card_congr (Additive.toMul),
    Nat.card_congr (class_group_equiv).symm.toEquiv, Nat.card_pi]
  simp [Fin.isValue, Fin.prod_succ]
  try decide
